### ISSUE TITLE
I found this error when i use Mitmproxy on Ubuntu15.04

### ISSUE THREAD

**Issue by gagaxiaolong** [mitmproxy/mitmproxy#1021]
Mitmproxy works fine on my Ubuntu15.04 last month,but today I found some problem:

When I type `sudo pip install mitmproxy`,everything is OK:

```
wechat@ubuntu:~$ sudo pip install mitmproxy
[sudo] password for wechat:
Requirement already satisfied (use --upgrade to upgrade): mitmproxy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname<3.6,>=3.5.0.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): blinker<1.5,>=1.4 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2015.11.20.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): configargparse<0.11,>=0.10 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): construct<2.6,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cryptography<1.3,>=1.2.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Flask<0.11,>=0.10.1 in ./.local/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): h2<3.0,>=2.1.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): hpack<3.0,>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): html2text==2016.1.8 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): hyperframe<4.0,>=3.2.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Pillow<3.2,>=3.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): passlib<1.7,>=1.6.5 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyasn1<0.2,>=0.1.9 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL<0.16,>=0.15.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyparsing<2.2,>=2.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyperclip<1.6,>=1.5.22 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): requests<2.10,>=2.9.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): six<1.11,>=1.10 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): tornado<4.4,>=4.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): urwid<1.4,>=1.3.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): watchdog<0.9,>=0.8.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /usr/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask<0.11,>=0.10.1->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from Flask<0.11,>=0.10.1->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask<0.11,>=0.10.1->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado<4.4,>=4.3->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado<4.4,>=4.3->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /usr/local/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /usr/local/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography<1.3,>=1.2.2->mitmproxy)
Cleaning up...
``` 
But when I use Mitmproxy, something is wrong:
```
wechat@ubuntu:~$ mitmproxy
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.17', 'console_scripts', 'mitmproxy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/main.py", line 6, in <module>
    from netlib.version_check import check_pyopenssl_version, check_mitmproxy_version
ImportError: No module named netlib.version_check
```

The error is can't find the module named 'netlib.version_check',but in my system,netlib is already installed:

```
wechat@ubuntu:~$ sudo pip2 install git+https://github.com/mitmproxy/netlib.git@master
Downloading/unpacking git+https://github.com/mitmproxy/netlib.git@master
  Cloning https://github.com/mitmproxy/netlib.git (to master) to /tmp/pip-Dwf0Lo-build
  Running setup.py (path:/tmp/pip-Dwf0Lo-build/setup.py) egg_info for package from git+https://github.com/mitmproxy/netlib.git@master

  Requirement already satisfied (use --upgrade to upgrade): netlib==0.17 from git+https://github.com/mitmproxy/netlib.git@master in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): mitmproxy>=0.17 in /usr/local/lib/python2.7/dist-packages (from netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname<3.6,>=3.5.0.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): blinker<1.5,>=1.4 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2015.11.20.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): configargparse<0.11,>=0.10 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): construct<2.6,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): cryptography<1.3,>=1.2.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): Flask<0.11,>=0.10.1 in ./.local/lib/python2.7/site-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): h2<3.0,>=2.1.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): hpack<3.0,>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): html2text==2016.1.8 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): hyperframe<4.0,>=3.2.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): Pillow<3.2,>=3.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): passlib<1.7,>=1.6.5 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): pyasn1<0.2,>=0.1.9 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL<0.16,>=0.15.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): pyparsing<2.2,>=2.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): pyperclip<1.6,>=1.5.22 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): requests<2.10,>=2.9.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): six<1.11,>=1.10 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): tornado<4.4,>=4.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): urwid<1.4,>=1.3.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): watchdog<0.9,>=0.8.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /usr/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.3,>=1.2.2->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado<4.4,>=4.3->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado<4.4,>=4.3->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /usr/local/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /usr/local/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy>=0.17->netlib==0.17)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography<1.3,>=1.2.2->mitmproxy>=0.17->netlib==0.17)
Cleaning up...
```
 What can i do to fix this issue? THANKS very much!!

**Comment by Kriechi** [comment]
It seems you are using mitmproxy 0.17:
`load_entry_point('mitmproxy==0.17'`

Its is not a good idea to mix pypy releases with github master branches.
Please try to remove all mitmproxy/netlib/pathod packages from your python installation, and try again with a clean pip install.

Also, please note, if you really want to use github latest, there was a big change: mitmproxy & netlib & pathod repository were merged - so this might change a few things for you.

**Comment by gagaxiaolong** [comment]
Thanks very much. I followed ur advice to reinstalled Mitmproxy,everything is OK now!!
