### ISSUE TITLE
bug report:UnicodeDecodeError

### ISSUE THREAD

**Issue by bigfool** [mitmproxy/mitmproxy#1038]
```
##### 
Traceback (most recent call last):
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/__init__.py", line 498, in run
    self.loop.run()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/__init__.py", line 451, in ticker
    self.loop.draw_screen()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/listbox.py", line 457, in render
    (maxcol, maxrow), focus=focus)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/urwid/listbox.py", line 402, in calculate_visible
    next, pos = self.body.get_next( pos )
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/flowlist.py", line 298, in get_next
    f = ConnectionItem(self.master, self.state, f, False) if f else None
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/flowlist.py", line 112, in __init__
    w = self.get_text()
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/flowlist.py", line 120, in get_text
    marked=self.state.flow_marked(self.flow)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/common.py", line 443, in format_flow
    tuple(sorted(d.items())), focus, extended
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/utils.py", line 119, in get
    ret = gen(*args)
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/common.py", line 195, in raw_format_flow
    resp.append(fcol(f["resp_ctype"], rc))
  File "/Users/qizhenfang/Library/Python/2.7/lib/python/site-packages/libmproxy/console/common.py", line 112, in fcol
    s = unicode(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 1: ordinal not in range(128)
```

Mitmproxy Version: 0.16
Operating System: OS X Yosemite 10.10.5

**Comment by mhils** [comment]
Thanks. How can we reproduce this?

**Comment by patrickrbc** [comment]
`
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 65, in <module>
    m.run()
  File "/Library/Python/2.7/site-packages/libmproxy/console/__init__.py", line 594, in run
    self.ui.run_wrapper(self.loop)
  File "/Library/Python/2.7/site-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/Library/Python/2.7/site-packages/libmproxy/console/__init__.py", line 814, in loop
    self.view.keypress(size, k)
  File "/Library/Python/2.7/site-packages/urwid/container.py", line 1112, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/Library/Python/2.7/site-packages/urwid/container.py", line 1583, in keypress
    key = self.focus.keypress(tsize, key)
  File "/Library/Python/2.7/site-packages/urwid/widget.py", line 1474, in keypress
    self.insert_text(key)
  File "/Library/Python/2.7/site-packages/urwid/widget.py", line 1398, in insert_text
    text = self._normalize_to_caption(text)
  File "/Library/Python/2.7/site-packages/urwid/widget.py", line 1415, in _normalize_to_caption
    return text.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
`

I receive this error everytime I try to insert characters like "ã" or "á".

**Comment by mhils** [comment]
Thanks. Insert where?

**Comment by patrickrbc** [comment]
I think in every place I can input text, but I in "Intercept filter" for example.

**Comment by Kriechi** [comment]
So, I just tried starting mitmproxy, press `i`, enter `äöüßáúóãõ`.
No crashes - although the expression is however invalid (which is expected).

What terminal are you using? Which locales are installed and set in your env`

**Comment by patrickrbc** [comment]
I'm in OS X 10.11.3, iTerm, ZSH
LC_TYPE=UTF-8

**Comment by Kriechi** [comment]
Same here.
How do you enter these characters? I'm using dead keys. 
So I first press `ALT+N` to get the `~`, and then `a` - which is converted to `ã` immediately. 
Same for the others. Are you using a different keyboard layout that has some direct keys for these letters?

**Comment by patrickrbc** [comment]
I just press `'` + `a` or `~` + `a`.
<img width="566" alt="screen shot 2016-03-26 at 4 26 35 pm" src="https://cloud.githubusercontent.com/assets/2023252/14062942/9e83fade-f36f-11e5-8f80-97476cab02b3.png">

**Comment by patrickrbc** [comment]
Also, my mitmproxy version is 0.10.1

**Comment by mhils** [comment]
Can you upgrade to 0.16 and replicate this please?

**Comment by patrickrbc** [comment]
There is no error using 0.16 version. Sorry for any inconvenience.

**Comment by Kriechi** [comment]
@bigfool: is your version number in your initial comment correct? Or do you have an old version too?
