### ISSUE TITLE
Close the connection on the way back doesn't seem to work

### ISSUE THREAD

**Issue by ksusasd** [mitmproxy/mitmproxy#1060]
Hello everyone.
I need to reproduce one bug, for this I need to close/drop the connection between client and server AFTER the server has processed the request. Is it possible to simulate such condition in mitmproxy? I am looking for something similar as `drop` in Fiddler.

I have tried to achieve this using the following steps:
1. Create `drop-conn.py` script with the following content:
`def response(context, flow):
    flow.client_conn.finish()`
2. Start mitmproxy with this script
3. Send the request to mitmproxy

But it crashed:
```
Traceback (most recent call last):
  File "/opt/mitmproxy/mitmproxy/proxy/server.py", line 121, in handlest):
    root_layer()2.168.99.101:9000/
  File "/opt/mitmproxy/mitmproxy/proxy/modes/reverse_proxy.py", line 15, in __call__
    layer()://192.168.99.101:9000/
  File "/opt/mitmproxy/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()://192.168.99.101:9000/
  File "/opt/mitmproxy/mitmproxy/protocol/http1.py", line 67, in __call__):
    layer()://192.168.99.101:9000/
  File "/opt/mitmproxy/mitmproxy/protocol/http.py", line 204, in __call__:
    self.send_response_to_client(flow)
  File "/opt/mitmproxy/mitmproxy/protocol/http.py", line 274, in send_response_to_client
    self.send_response(flow.response)
  File "/opt/mitmproxy/mitmproxy/protocol/http.py", line 55, in send_response
    self.send_response_headers(response)
  File "/opt/mitmproxy/mitmproxy/protocol/http1.py", line 39, in send_response_headers
    self.client_conn.wfile.flush()
  File "/opt/mitmproxy/netlib/tcp.py", line 168, in flush
    self.o.flush()168.99.101:9000/wp-admin/install.php?step=1
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
AttributeError: 'NoneType' object has no attribute 'sendall'
   GET http://192.168.99.101:9000/wp-admin/install.php?step=1
mitmproxy has crashed! 2.17kB 111ms
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
       ← 200 text/html 3.19kB 1.13s
   GET http://192.168.99.101:9000/wp-admin/install.php
       ← 200 text/html 3.19kB 1.25s
   GET http://192.168.99.101:9000/wp-admin/install.php
       ← 200 text/html 3.19kB 1.18s
  File "/opt/mitmproxy/mitmproxy/protocol/http1.py", line 39, in send_response_headers
    self.client_conn.wfile.flush()s://github.com/mitmproxy/mitmproxy
  File "/opt/mitmproxy/netlib/tcp.py", line 168, in flush
    self.o.flush() report at: https://github.com/mitmproxy/mitmproxy
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
AttributeError: 'NoneType' object has no attribute 'sendall'

mitmproxy has crashed!
```

Mitmproxy Version: 0.17
Operating System: Docker

**Comment by mhils** [comment]
Have you tried using `context.kill_flow(flow)` ?
