### ISSUE TITLE
Crash when exporting flow with null bytes (pyperclip's gtk implementation)

### ISSUE THREAD

**Issue by dequis** [mitmproxy/mitmproxy#1062]
##### Steps to reproduce the problem:

1. Have pygtk installed
2. Have request flow with nulls somewhere (such as compressed post data)
3. Press 'E' and 'c'
4. Acquire exception

##### What is the expected behavior?

Catch the error, pokemon-style.

##### What went wrong?

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 498, in run
    self.loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/window.py", line 39, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 126, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 81, in keypress
    self.prompt_execute(k)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 106, in prompt_execute
    msg = p(txt, *args)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/common.py", line 291, in export_prompt
    copy_to_clipboard_or_prompt(exporters[k](flow))
  File "/usr/lib/python2.7/site-packages/libmproxy/console/common.py", line 304, in copy_to_clipboard_or_prompt
    pyperclip.copy(toclip)
  File "/usr/lib/python2.7/site-packages/pyperclip/clipboards.py", line 33, in copy_gtk
    cb.set_text(text)
TypeError: Gtk.Clipboard.set_text() argument 1 must be string without null bytes, not str
```

##### Any other comments?

I can't actually get this to copy anything at all to the clipboard but I'm not sure who to blame yet - pyperclip seems to work in an interactive python shell but not in mitmproxy, and a previous version of pyperclip that preferred "xclip" didn't work either.

I'd prefer it if this thing didn't touch my clipboard at all, seems wrong for a console application to do that kind of thing. And this feature that sounded like it was about writing files, but #976 seems to deal with that.

---

Mitmproxy Version: 0.16
Operating System: linux

**Comment by mhils** [comment]
Thanks for the report! This is fixed by @Uberi in #1069. :smiley:
