### ISSUE TITLE
mitmproxy crash

### ISSUE THREAD

**Issue by orenfine** [mitmproxy/mitmproxy#1063]
##### Steps to reproduce the problem:

1. connection is killed (inline script)
2. when looking at the connection details (rightmost) tab - mitmproxy crashes!

##### What is the expected behavior?
Show details screen, or blank screen

##### What went wrong?
Here's the traceback:

```
mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/main.py", line 70, in mitmproxy
    m.run()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 508, in run
    self.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 679, in shutdown
    self.state.killall(self)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/flow.py", line 623, in killall
    self.flows.kill_all(master)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/flow.py", line 535, in kill_all
    f.kill(master)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/models/flow.py", line 151, in kill
    master.handle_error(self)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 725, in handle_error
    self.process_flow(f)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 716, in process_flow
    signals.flow_change.send(self, flow = f)
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowview.py", line 169, in sig_flow_change
    self.show()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/tabs.py", line 67, in show
    body = self.tabs[self.tab_offset][1](),
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowview.py", line 165, in view_details
    return flowdetailview.flowdetails(self.state, self.flow)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowdetailview.py", line 25, in flowdetails
    ["Address", "%s:%s" % sc.address()],
TypeError: 'NoneType' object is not callable
```

##### Any other comments?

---

Mitmproxy Version: 0.16
Operating System: Ubuntu 15.10

**Comment by aisipos** [comment]
I've seen this too - I think caused when editing a response where the client times out.

**Comment by mhils** [comment]
Thanks for the report. This is already fixed on master. :smiley:
