### ISSUE TITLE
mitmproxy crash

### ISSUE THREAD

**Issue by sweetcharity** [mitmproxy/mitmproxy#1068]
##### Steps to reproduce the problem:

1. My scenario is a DNS spoofing
2. mitmproxy --host --spoof -s "mitmnbdf_inline.py mitmnbdf.cfg"
where "mitmnbdf_inline.py" is https://github.com/davinerd/mitmnbdf/blob/master/mitmnbdf_inline.py
3. When I visit spoofed site mitmproxy crashes:

"mitmnbdf_inline.py mitmnbdf.cfg"
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/init.py", line 499, in run
self.loop.run()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
self.run()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in run
self.event_loop.run()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
self._loop()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
self._watch_filesfd
File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in
event_loop, callback, self.get_available_raw_input())
File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
callback(processed, processed_codes)
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
self.process_input(keys)
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
k = self._topmost_widget.keypress(self.screen_size, k)
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/window.py", line 38, in keypress
k = super(self.__class, self).keypress(size, k)
File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
return self.body.keypress( (maxcol, remaining), key )
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 377, in keypress
return urwid.ListBox.keypress(self, size, key)
File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 1001, in keypress
return actual_key(self.keypress_down((maxcol, maxrow)))
File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 1119, in keypress_down
widget, pos = self.body.get_next(pos)
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 279, in get_next
f = ConnectionItem(self.master, self.state, f, False) if f else None
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 106, in __init
w = self.get_text()
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 114, in get_text
marked=self.state.flow_marked(self.flow)
File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/common.py", line 399, in format_flow
contentdesc = netlib.utils.pretty_size(len(f.response.content))
TypeError: object of type 'HTTPFlow' has no len()

mitmproxy has crashed!
_____________________
Mitmproxy Version: 0.16
Operating System: Kali Linux 2016.1

**Comment by mhils** [comment]
The inline script looks wrong: [`flow.response.content = mitmnbdf.flow`](https://github.com/davinerd/mitmnbdf/blob/master/mitmnbdf_inline.py#L583). I don't think this is a bug in mitmproxy.
