### ISSUE TITLE
HTTP/2 does not handle killed requests

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1084]
##### Steps to reproduce the problem:

1. `mitmdump -S test_replay --kill`
2. Open a website that is not contained in the replay file.

##### What went wrong?

```
127.0.0.1:50907: clientconnect
127.0.0.1:50906: clientconnect
127.0.0.1 GET https://news.ycombinator.com/ HTTP/2.0
 << Connection killed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http2.py", line 422, in run
    layer()
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http.py", line 188, in __call__
    self.process_request_hook(flow)
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http.py", line 356, in process_request_hook
    raise Kill()
Kill
```

**Comment by Kriechi** [comment]
Do you have a test for this?

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/blob/423c076c61140c2e953313793263a4cac71e33ca/test/mitmproxy/test_server.py#L770-L783 is pretty much the same for HTTP/1.
