### ISSUE TITLE
Setting a limit in OS X builds (0.16, 0.17) crashes mitmproxy

### ISSUE THREAD

**Issue by clangen-mfp** [mitmproxy/mitmproxy#1087]
##### Steps to reproduce the problem:

1. Launch mitmproxy
2. Press "l" to enter a limit
3. Type any expression, e.g. ".*myhost\.com"

##### What is the expected behavior?

For the limit to be applied to the view.

##### What went wrong?

The app crashes.

##### Any other comments?

0.16 and 0.17 crash. 0.15 works fine.

    Traceback (most recent call last):
      File "site-packages/mitmproxy/console/__init__.py", line 512, in run
      File "site-packages/urwid/main_loop.py", line 278, in run
      File "site-packages/urwid/main_loop.py", line 376, in _run
      File "site-packages/urwid/main_loop.py", line 682, in run
      File "site-packages/urwid/main_loop.py", line 719, in _loop
      File "site-packages/urwid/raw_display.py", line 393, in <lambda>
      File "site-packages/urwid/raw_display.py", line 493, in parse_input
      File "site-packages/urwid/main_loop.py", line 403, in _update
      File "site-packages/urwid/main_loop.py", line 503, in process_input
      File "site-packages/mitmproxy/console/window.py", line 39, in keypress
      File "site-packages/urwid/container.py", line 1116, in keypress
      File "site-packages/mitmproxy/console/statusbar.py", line 126, in keypress
      File "site-packages/mitmproxy/console/statusbar.py", line 83, in keypress
      File "site-packages/mitmproxy/console/statusbar.py", line 106, in prompt_execute
      File "site-packages/mitmproxy/console/__init__.py", line 658, in set_limit
      File "site-packages/mitmproxy/console/__init__.py", line 60, in set_limit
      File "site-packages/mitmproxy/flow.py", line 593, in set_limit
      File "site-packages/mitmproxy/filt.py", line 398, in parse
      File "site-packages/pyparsing.py", line 1162, in parseString
      File "site-packages/pyparsing.py", line 1054, in _parseNoCache
      File "site-packages/pyparsing.py", line 803, in wrapper
    AttributeError: 'NoneType' object has no attribute 'endswith' 

---

Mitmproxy Version: 0.17
Operating System: OS X 10.11.4

**Comment by mhils** [comment]
This seems to be a PyInstaller issue. The relevant part in pyparsing is:
```python
                    try:
                        tb = sys.exc_info()[-1]
                        exc_source_line = traceback.extract_tb(tb)[-1][-1]
                        if not exc_source_line.endswith('#~@$^*)+_(&%#!=-`~;:"[]{}'):   # crashes here
                            raise
                    finally:
                        del tb
```

**Comment by mhils** [comment]
Same issue on the Windows builds. :-/

The workaround is to install mitmproxy from source.

**Comment by mhils** [comment]
Surprisingly, I was wrong to blame Pyinstaller.
https://docs.python.org/2/library/traceback.html#traceback.extract_tb states that `exc_source_line` may be None if the source is not available.

**Comment by mhils** [comment]
You can now get 0.17.1 binaries on https://mitmproxy.org. Thanks for reporting!

**Comment by clangen-mfp** [comment]
0.17.1 works great. Thanks!
