### ISSUE TITLE
mitmproxy crashing on el capitan 10.11.4

### ISSUE THREAD

**Issue by jhelm** [mitmproxy/mitmproxy#1088]
##### Steps to reproduce the problem:

1. Install mitmporoxy 0.17 OSX binaries from https://github.com/mitmproxy/mitmproxy/releases/download/v0.17/mitmproxy-0.17-osx.tar.gz
2. verify python27 is active, run mitmproxy;  (note, running under iTerm, not Apple's Terminal.app'
3. enter 'i' followed by '~q'  the program exists with a crash traceback

##### What is the expected behavior?
the intercept filter would capture all traffic

##### What went wrong?
The following messages appear on the console:

```
MacBook-Pro:tmp jlh$ mitmproxy
Traceback (most recent call last):
  File "site-packages/mitmproxy/console/__init__.py", line 512, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 719, in _loop
  File "site-packages/urwid/raw_display.py", line 393, in <lambda>
  File "site-packages/urwid/raw_display.py", line 493, in parse_input
  File "site-packages/urwid/main_loop.py", line 403, in _update
  File "site-packages/urwid/main_loop.py", line 503, in process_input
  File "site-packages/mitmproxy/console/window.py", line 39, in keypress
  File "site-packages/urwid/container.py", line 1116, in keypress
  File "site-packages/mitmproxy/console/statusbar.py", line 126, in keypress
  File "site-packages/mitmproxy/console/statusbar.py", line 83, in keypress
  File "site-packages/mitmproxy/console/statusbar.py", line 106, in prompt_execute
  File "site-packages/mitmproxy/console/__init__.py", line 663, in set_intercept
  File "site-packages/mitmproxy/flow.py", line 604, in set_intercept
  File "site-packages/mitmproxy/filt.py", line 398, in parse
  File "site-packages/pyparsing.py", line 1162, in parseString
  File "site-packages/pyparsing.py", line 1054, in _parseNoCache
  File "site-packages/pyparsing.py", line 803, in wrapper
AttributeError: 'NoneType' object has no attribute 'endswith'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
MacBook-Pro:tmp jlh$ python --version
Python 2.7.11
MacBook-Pro:tmp jlh$
```

##### Any other comments?

Python installed with MacPorts.  I also tried the py27-mitmproxy port, which cratered even more spectacularly 

Thanks for the great project!
---

Mitmproxy Version: 0.17
Operating System:  OSX 10.11.4

**Comment by MatthewShao** [comment]
The error message is the same as #1087, duplicated?

**Comment by jhelm** [comment]
Matthew, yes.  Apologies all! This is the same bug as #1087, which I failed to find before submitting this.  Closing this one in deference to #1087.  Thank you.  /John

**Comment by jhelm** [comment]
Yes, my apologies.  I didn't turn that one up on my search.  I've closed 
the bug indeference to 1087.  Thank you!  /John

**Comment by mhils** [comment]
You can now get 0.17.1 binaries on https://mitmproxy.org. Thanks for reporting!
