### ISSUE TITLE
Script examples refer to libmproxy - change to mitmproxy

### ISSUE THREAD

**Issue by peterglock** [mitmproxy/mitmproxy#1094]
##### Steps to reproduce the problem:

1. add inline script 'redirect_requests.py' to mitmproxy command line
2. 
3. 

##### What is the expected behavior?
mitmproxy window opens

##### What went wrong?
Get following error
`Script load error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/flow.py", line 694, in load_script
    s.load()
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/script/script.py", line 85, in load
    sys.exc_info()[2]
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/script/script.py", line 80, in load
    exec (code, self.ns, self.ns)
  File "/Users/peterglock/Documents/mitmproxy/mitmproxy/examples/redirect_requests.py", line 1, in <module>
    from libmproxy.protocol.http import HTTPResponse
ScriptException: No module named libmproxy.protocol.http`

##### Any other comments?

changing libmproxy to mitmproxy allows the script to run
---

Mitmproxy Version: 0.18
Operating System: OSX 10.11.5 Beta

**Comment by mhils** [comment]
Thanks for the report. I think we already updated this?
https://github.com/mitmproxy/mitmproxy/blob/master/examples/redirect_requests.py

**Comment by peterglock** [comment]
I must have been using an outdated version of the examples. I've updated from the git repo.
