### ISSUE TITLE
mitmproxy has crashed!CanvasError: Canvas text is wider than the maxcol specified

### ISSUE THREAD

**Issue by minioreo** [mitmproxy/mitmproxy#1113]
##### Steps to reproduce the problem:

1. execute mitmproxy
2. set my mobile phone's WIFI to use mitmproxy
3. mitmproxy crashed

##### What went wrong?
mitmproxy crashed

##### Any other comments?
Traceback (most recent call last):
  File "site-packages/mitmproxy/console/__init__.py", line 512, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 715, in _loop
  File "site-packages/urwid/main_loop.py", line 164, in cb
  File "site-packages/mitmproxy/console/__init__.py", line 456, in ticker
  File "site-packages/urwid/main_loop.py", line 578, in draw_screen
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/container.py", line 1083, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/decoration.py", line 225, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/listbox.py", line 475, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/widget.py", line 1751, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/container.py", line 1520, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/container.py", line 2085, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/widget.py", line 1008, in render
  File "site-packages/urwid/canvas.py", line 1313, in apply_text_layout
  File "site-packages/urwid/canvas.py", line 356, in __init__
CanvasError: Canvas text is wider than the maxcol specified
1
[2]
['\xa1\xfb']

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...

---

Mitmproxy Version:0.17.1
Operating System:OSX 10.11.4 (15E65)

**Comment by mhils** [comment]
Do you have any more detailed steps to reproduce it? I can't trigger that behaviour.
