### ISSUE TITLE
Mitmproxy crashes when making a SSL request

### ISSUE THREAD

**Issue by jvillacorta** [mitmproxy/mitmproxy#1114]
##### Steps to reproduce the problem:

1. Launch mitmproxy
2. On an iPhone with certificates installed navigate to google.com or any website that requires ssl

##### What is the expected behavior?
Connection will be established

##### What went wrong?
```
Crash log:
`Traceback (most recent call last):
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/http1.py", line 67, in __call__
    layer()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 171, in __call__
    self.handle_regular_mode_connect(request)
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 263, in handle_regular_mode_connect
    layer()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 353, in __call__
    self._establish_tls_with_client_and_server()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 437, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 457, in _establish_tls_with_client
    extra_chain_certs = extra_certs,
  File "/Users/jorge/venv.KiteTest/lib/python2.7/site-packages/mitmproxy/models/connections.py", line 84, in convert_to_ssl
    super(ClientConnection, self).convert_to_ssl(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 802, in convert_to_ssl
    **sslctx_kwargs)
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 765, in create_ssl_context
    context = self._create_ssl_context(**sslctx_kwargs)
TypeError: _create_ssl_context() got an unexpected keyword argument 'extra_chain_certs'`
```
##### Any other comments?
This issue does not happen on mitmproxy 0.16 or with other OSX versions

---

Mitmproxy Version: 0.17
Operating System: OSX 10.10.5

**Comment by mhils** [comment]
This looks like you have still an old version of netlib installed?

**Comment by jvillacorta** [comment]
Thanks that was the problem, I upgraded to 0.17 from 0.16 and an older version of netlib was still in the virtualenv
