### ISSUE TITLE
Responding with static content in streaming mode in a script crashes mitmproxy.

### ISSUE THREAD

**Issue by chrisgavinme** [mitmproxy/mitmproxy#1115]
First of all, this may be intended behavior. If that's the case don't hesitate to close this issue, I appreciate it's a bit of a weird thing to do.

It would appear that when mitmproxy is run with the `--stream 0` flag and a script chooses to send an `HTTPResponse` object with static content mitmproxy crashes.

##### Steps to reproduce the problem:

1. Run `mitmdump --stream 0 -s examples/redirect_requests.py`
2. Attempt to access http://example.com/ through mitmproxy.

##### What is the expected behavior?
"helloworld" should be displayed in the browser.

##### What went wrong?
mitmproxy crashes with this traceback:

```
127.0.0.1:40469: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 67, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 204, in __call__
    self.send_response_to_client(flow)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 285, in send_response_to_client
    self.send_response_body(flow.response, chunks)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 42, in send_response_body
    for chunk in http1.assemble_body(response.headers, chunks):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/assemble.py", line 42, in assemble_body
    for chunk in body_chunks:
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 133, in read_body
    content = rfile.read(chunk_size)
AttributeError: 'NoneType' object has no attribute 'read'
```

##### Any other comments?
Thanks for developing this amazing piece of software. It's incredibly useful.

---

Mitmproxy Version: 0.17
Operating System: Linux

**Comment by mhils** [comment]
I somehow screwed up the commit message, but this should be fixed on master with 99178c5! :smiley:
