### ISSUE TITLE
Cookie.CookieError: Illegal key value: _csrf/link

### ISSUE THREAD

**Issue by StevenVanAcker** [mitmproxy/mitmproxy#1118]
##### Steps to reproduce the problem:

1. mitmdump -t .
2. visit http://dailymotion.com using the proxy
3. website tries to set cookie _csrf/link, which crashes mitmdump

##### What is the expected behavior?

I would expect mitmdump to not crash, but either forward the cookie as is, or not forward it.

##### What went wrong?

According to RFC 6265 (Cookie RFC), which refers to RFC 2616 (HTTP), "_csrf/link" is an invalid
cookie name because it contains a "/". Visiting the website with Chrome does not segfault Chrome, but instead continues as if the cookiename is valid. I believe mitmdump should handle this error gracefully instead of crashing.

Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 9, in <module>
    load_entry_point('mitmproxy==0.18', 'console_scripts', 'mitmdump')()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/main.py", line 102, in mitmdump
    master.run()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/dump.py", line 350, in run
    super(DumpMaster, self).run()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/controller.py", line 27, in run
    self.tick(0.1)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow.py", line 845, in tick
    return super(FlowMaster, self).tick(timeout)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/controller.py", line 39, in tick
    handle_func(obj)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/dump.py", line 334, in handle_response
    flow.FlowMaster.handle_response(self, f)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow.py", line 1039, in handle_response
    self.process_new_response(f)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow.py", line 936, in process_new_response
    self.stickycookie_state.handle_response(f)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow.py", line 337, in handle_response
    c = http_cookies.SimpleCookie(str(i))
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 640, in load
    self.__ParseString(rawdata)
  File "/usr/lib/python2.7/Cookie.py", line 677, in __ParseString
    self.__set(K, rval, cval)
  File "/usr/lib/python2.7/Cookie.py", line 589, in __set
    M.set(key, real_value, coded_value)
  File "/usr/lib/python2.7/Cookie.py", line 459, in set
    raise CookieError("Illegal key value: %s" % key)
Cookie.CookieError: Illegal key value: _csrf/link

I would submit a fix myself, but I'm a bit swamped with other work right now

##### Any other comments?

---

Mitmproxy Version: 0.18
Operating System: Ubuntu

**Comment by Kriechi** [comment]
We are using the python standard cookie lib, which states the following in its documentation (py2 and py3 alike):

https://docs.python.org/2/library/cookie.html
https://docs.python.org/3/library/http.cookies.html

> The module formerly strictly applied the parsing rules described in the RFC 2109 and RFC 2068 specifications. It has since been discovered that MSIE 3.0x doesn’t follow the character rules outlined in those specs and also many current day browsers and servers have relaxed parsing rules when comes to Cookie handling. As a result, the parsing rules used are a bit less strict.

> The character set, string.ascii_letters, string.digits and !#$%&'*+-.^_`|~: denote the set of valid characters allowed by this module in Cookie name (as key).

So fixing this or handling gracefully might be tricky - without shipping our own cookie parsing lib.
And just removing the cookie (i.e. gracefully ignoring it) might lead to confusing results and creates more harm than good.

**Comment by Kriechi** [comment]
Or we might be able to get way with it by using this trick: https://bugs.python.org/issue2193#msg124178
