### ISSUE TITLE
Response streaming does not work in replay mode

### ISSUE THREAD

**Issue by ghost** [mitmproxy/mitmproxy#1147]
##### What's the problem?

While testing mitmdump replay I see that it consumes multiple GB of RAM and multiple GB of data went through the network. Because mitmdump eats up all physical memory as well as nearly all memory of swap the system was nearly dead. The client could not load a lot of the test pages.
Friendly killing mitmdump was not successful for more than 20 minutes and in the log files I could see crash reports.
After some search it seems that my client start download of several big files, many of them are bigger than one GB, but abort it after less than two MB.
##### Steps to reproduce the problem:
1. start mitmdump in transparent proxy mode, SSL and --no-pop
2. start on the client a big download like Linux DVD
3. abort download 
4. watch mitmdump downloading the whole file for the next minutes or hours and eating up memory
##### What is the expected behaviour?

The client disconnect and thus does not need the information any more. Therefore mitmdump should abort the download. Additionally for me it seems to be a good idea to not load big files completely into the memory.
##### What went wrong?

One of my test pages contains JavaScript/links to movies. These mp4 files are mostly bigger than one GB bur some of them are only about 500 MB. It seems that Internet Explorer peek into these files. I could not see Firefox doing this. As a result of the behaviour of the Internet Explorer mitmdump tried to download all these files completely and dumping them in the memory. But the sum of all of these files are more than the memory of machine mitmdump is running on. Thus the system slows down a lot and mitmdump is not able to replay other sites.
With this behaviour it is easy for a client to do a denial of service attack against mitmdump, even though it is not the intention of the client.
##### What is an example of the crash log?

For me it seems that mitmdump finished a 'smaller' download and then tries to send it to the client which disconnected minutes ago.
Here is an example:

```
  << 200 OK 692.45MB

 Error in processing of request from 192.168.*.*:50000
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 854, in connection_thread
     self.handle_client_connection(connection, client_address)
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 62, in handle_client_connection
     self.channel
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 75, in __init__
     None)
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/models/connections.py", line 17, in __init__
     super(ClientConnection, self).__init__(client_connection, address, server)
   File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 734, in __init__
     super(BaseHandler, self).__init__(connection)
   File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 461, in __init__
     self.peer_address = Address(connection.getpeername())
   File "/usr/lib/python2.7/socket.py", line 228, in meth
     return getattr(self._sock,name)(*args)
 error: [Errno 107] Transport endpoint is not connected

 ----------------------------------------
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
     root_layer()
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__
     layer()
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 358, in __call__
     layer()
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 67, in __call__
     layer()
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 204, in __call__
     self.send_response_to_client(flow)
   File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 270, in send_response_to_client
     if not flow.response.stream:
 AttributeError: 'NoneType' object has no attribute 'response'

 mitmproxy has crashed!
 Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```
##### Any other comments?

I am aware of different reports like #1081 and I tried the `--stream` option. The result was that most sites in the dump could not be replayed. For example amazon was only a white page with favicon. The last one was not replayed but loaded from the internet. Other sites like weather.com could not be loaded at all. Internet Explorer complained about being unable to load that site and I should check if the address is spelled correctly.

I am also aware of other reports like #1036 #1029 and #1095 but I was not able to find a solution. Maybe with the SQL mitmdump will not eat up all memory. But this will not prevent mitmdump from wasting time to download unnecessary files or prevent `--stream` from destroying replays.

---

Mitmproxy Version: 0.17
Operating System: Kali Linux Rolling (2016.1) 64 Bit and Windows 7 64 Bit

**Comment by mhils** [comment]
Thanks for the detailed bug report and searching on the tracker beforehand. 

Unfortunately, detecting a client disconnect while reading the response is pretty difficult to implement with our current model, and I'd argue it's not really worth the investment/complexity. If you supply `--stream`, mitmproxy should just do just what you are requesting - stop downloading once the client connection goes away. I can open `amazon.com` with `--stream 0` just fine, so I'd say we should rather see that `--stream` works as intended. Any details how I can replicate this issue?

Other than that, `--body-size-limit` would be another workaround, depending on your scenario.

**Comment by Nerudifus** [comment]
It was a replay session. For testing purpose I recorded several sites and tried to replay them. The recording was done without ```--stream```, maybe this is the problem?

I will have a look at ```--body-size-limit``` in the next days.

**Comment by Nerudifus** [comment]
I'm sorry if I should have edit my last post or create a new issue.

I did additional tests on ```--stream```. After adding ```--stream 0``` to my parameter list a run for dumping and another one for replaying was done. Depending on what I can see the client could load the sites without problems on the dumping run. Well at least it seems so. I could see some potential problems although I could not reproduce them. This is maybe a performance problem. But on the replaying run it gets even worse than my last test with a dump without ```--stream``` (but stream option was used in replay). Only a few favicon, less than before, could be loaded. And it seems that none of the loaded icons is a replay, e.g. the original site used another favicon but as a result of the missing site body (see text below) the Internet Explorer does not know the correct URL and tried the default /favicon.ico which is present in these few cases.

Looking at the output of mitmdump nearly every streaming line (I do not know how you call the lines with << which is streaming operator in c++ thus I call it this way) ends with ```(content missing)``` instead of the size. This is true for both runs but in the replay run there are also tracebacks like the following:
```
192.168.*.* GET http://www.amazon.com/
 << 200 OK (content missing)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 67, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 204, in __call__
    self.send_response_to_client(flow)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 285, in send_response_to_client
    self.send_response_body(flow.response, chunks)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 42, in send_response_body
    for chunk in http1.assemble_body(response.headers, chunks):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/assemble.py", line 37, in assemble_body
    for chunk in body_chunks:
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 113, in read_body
    for x in _read_chunked(rfile, limit):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 342, in _read_chunked
    line = rfile.readline(128)
AttributeError: 'NoneType' object has no attribute 'readline'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

The dump file is smaller than usually, normally the file is about 90 to 120 MB but this time it is smaller than 20 MB. 
I also dumped the network traffic with wireshark on the clients. It seems that in replay the HTTP response seems to include all header, even though they are altered, but there is no body at all. In the dump file with ```--stream``` (for amazon) there is ```0:~}``` after ```7:content,``` and in the file created without stream option there is ```61699:``` followed by binary data after the content string.

```
  --stream SIZE         Stream data to the client if response body exceeds the
                        given threshold. If streamed, the body will not be
                        stored in any way. Understands k/m/g suffixes, i.e. 3m
                        for 3 megabytes.
```
In the help information it is written that no body will be saved while using stream option. But is it intended that mitmdump send no body on replay because it was not saved, instead of getting the current body of the original server? I know that it is not a good idea to put in a value of zero even if the body is reloaded from the original server. This will bereave mitmdump of its function, well if I do not misunderstood its function. I used this value because you did it, too.

**Comment by mhils** [comment]
> But is it intended that mitmdump send no body on replay because it was not saved, instead of getting the current body of the original server?

Certainly not intended, but it defies the purpose of a replay if we need to connect to the server. As I see it, there are two distinct issues:

1. Replay a full dump (including contents) with `--stream 0`. Looking at your traceback, there seems to be a bug which makes this fail.
2. Replay a partial dump (no contents) with `--stream 0`. I think we need to exclude flows with a missing body from replay in general.

**Comment by Nerudifus** [comment]
I can not remember that I present a traceback for replay full dump with stream. The traceback in my initial post was without ```--stream```. After a lot of minutes one of the downloads ended an mitmdump tries to send the downloaded data to the closed connection. The traceback in my third post is of a replay of partial dump which was created with stream.
Thus I tried it and you are right. I created a dump without stream operation and killed the bad connection with ```tcpkill```. Thus the dump finished and the machine does not run out of memory. After that I run a replay with ```--stream 0``` and, as already known, sites could not be loaded on client. In the output of mitmdump is for example the following traceback:
```
192.168.*.* GET http://www.amazon.com/
[replay]  << 200 OK 61.8kB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 67, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 204, in __call__
    self.send_response_to_client(flow)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 285, in send_response_to_client
    self.send_response_body(flow.response, chunks)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 42, in send_response_body
    for chunk in http1.assemble_body(response.headers, chunks):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/assemble.py", line 37, in assemble_body
    for chunk in body_chunks:
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 113, in read_body
    for x in _read_chunked(rfile, limit):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 342, in _read_chunked
    line = rfile.readline(128)
AttributeError: 'NoneType' object has no attribute 'readline'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.*.*:4****: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 67, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 204, in __call__
    self.send_response_to_client(flow)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 285, in send_response_to_client
    self.send_response_body(flow.response, chunks)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 42, in send_response_body
    for chunk in http1.assemble_body(response.headers, chunks):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/assemble.py", line 37, in assemble_body
    for chunk in body_chunks:
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 113, in read_body
    for x in _read_chunked(rfile, limit):
  File "/usr/local/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 342, in _read_chunked
    line = rfile.readline(128)
AttributeError: 'NoneType' object has no attribute 'readline'
``` 

Afterwards I tested ```--body-size-limit 10m``` on dump and replay. As far as I can tell it seems to work. Thus it can be used if there is a known upper bound which is small enough. 

At least I tested dumping with ```--stream 10m``` and replaying with ```--body-size-limit 10m```:
``` 
192.168.*.* GET http://www.amazon.com/
[replay]  << 200 OK (content missing)
192.168.*.*:5****: ProtocolException("Error in HTTP connection: HttpException('Cannot assemble flow with missing content',)",)
``` 
Did I misunderstood the help text? I thought with that configuration everything smaller than 10 MB should be loaded in a normal way and thus should be saved in the dump file. In the output of the dumping I could see:
```
192.168.12.150 GET http://www.amazon.com/
 << 200 OK (content missing)
```
And a view into the dump file approve that there is no content saved. As far as I remember the size of the not dumped body should be around 60-70 KB. Please don't misinterpret, there is a lot saved into the dump file like pictures of size of 80 KB. With 90 MB the size of the dump file also confirmed that most of the data is saved but nearly no site could be load in replay. All not dumped files I could see are text files like html, css and js. But There are also such files which could be dumped and thus replayed. At first I thought that the different may be between compression and uncompressed but I could not confirm this. I was not able to see a pattern which files are saved in the dump file and which are not.

**Comment by Kriechi** [comment]
Streaming just got a big overhaul in #2369 and earlier commits.
If you are still experiencing this (or a related issue) please test with the latest git-master version of mitmproxy (and Python 3.5+!) and feel free to open a new issue.
