### ISSUE TITLE
mitmdump crashes when serving mitm.it

### ISSUE THREAD

**Issue by Pastafarianist** [mitmproxy/mitmproxy#1188]
```
Traceback (most recent call last):
  File "/mnt/storage/mitm/mitmproxy/venv/bin/mitmdump", line 9, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmdump')()
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/main.py", line 100, in mitmdump
    master.run()
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/dump.py", line 355, in run
    super(DumpMaster, self).run()
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/controller.py", line 61, in run
    self.tick(0.1)
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/flow/master.py", line 228, in tick
    return super(FlowMaster, self).tick(timeout)
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/controller.py", line 83, in tick
    handle_func(obj)
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/controller.py", line 190, in wrapper
    ret = f(*args, **kwargs)
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/dump.py", line 331, in request
    self.state.delete_flow(f)
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/flow/state.py", line 220, in delete_flow
    self.flows._remove(f)
  File "/mnt/storage/mitm/mitmproxy/mitmproxy/flow/state.py", line 132, in _remove
    self._list.remove(f)
Exception ValueError: list.remove(x): x not in list
mitmproxy.exceptions.ControlException: ControlException('Un-acked message',) in <bound method Reply.__del__ of <mitmproxy.controller.Reply object at 0x957c4f30>> ignored
```
##### Steps to reproduce the problem:

1. Launch `mitmdump`, commit 92cdca50c7a43a5ab59b435e73e3b17dbe01cd3b
2. Go to mitm.it with the stock browser of Android 6.

Note: `mitmproxy` does not crash.

---

Mitmproxy Version: 92cdca50c7a43a5ab59b435e73e3b17dbe01cd3b
Operating System: Debian Jessie ARM

**Comment by cortesi** [comment]
I believe I just fixed this, but I don't have easy access to the Android browser you report in your bug. Please do re-open if you still see the problem. Thanks for reporting this!

**Comment by Pastafarianist** [comment]
Works for me. Thanks for fixing this!
