### ISSUE TITLE
Crash after using newly created flow in mitmproxy console

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1205]
##### Steps to reproduce the problem:

1. Press "n" to create a new flow
2. Press "r" to replay it
3. Delete the flow

##### What went wrong?

```
Traceback (most recent call last):
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/console/__init__.py", line 546, in run
    self.loop.run()
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/console/window.py", line 42, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/console/flowlist.py", line 407, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/Users/cortesi/mitmproxy/mitmproxy/venv/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/console/flowlist.py", line 190, in keypress
    self.flow.kill(self.master)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/models/flow.py", line 158, in kill
    self.reply(exceptions.Kill)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/controller.py", line 223, in __call__
    raise exceptions.ControlException("Message already acked.")
ControlException: Message already acked.
```

---

Mitmproxy Version: -master
Operating System: osx

**Comment by mhils** [comment]
somewhat refs #1265
