### ISSUE TITLE
WindowsError: [Error 183] : 'D:\\code\\mitmproxy\\venv/tcl/tcl8.5'

### ISSUE THREAD

**Issue by hhhaiai** [mitmproxy/mitmproxy#1248]
##### Steps to reproduce the problem:

1. open  win 7 64bit cmd.exe
2.  neweast mitmporoxy
3.  run dev.bat. happen error:

```
Traceback (most recent call last):
  File "d:\tools\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\tools\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\tools\Python27\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "d:\tools\python27\lib\site-packages\virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "d:\tools\python27\lib\site-packages\virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "d:\tools\python27\lib\site-packages\virtualenv.py", line 1136, in install_python
    copy_tcltk(prefix, home_dir, symlink)
  File "d:\tools\python27\lib\site-packages\virtualenv.py", line 1077, in copy_tcltk
    copyfileordir(srcdir, dstdir, symlink)
  File "d:\tools\python27\lib\site-packages\virtualenv.py", line 327, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "d:\tools\python27\lib\shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "d:\tools\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] : 'D:\\code\\mitmproxy\\venv/tcl/tcl8.5'
```

##### What is the expected behavior?

INSTALL  mitmproxy on win7 
##### What went wrong?

venv.. tcl
##### Any other comments? What have you tried so far?

already install ActiveTcl8.6.4.1.299124-win32-x86_64-threaded . Still can't run this command。

---

Mitmproxy Version:  master ..  commit hash.. ccf4723505935f759c1bff5c5cc7d6d986726422
Operating System: win7+cygwin

**Comment by mhils** [comment]
This looks like an error with your Python/pip/virtualenv version, unrelated to mitmproxy. Can you reinstall Python and try again?

**Comment by hhhaiai** [comment]
already reinstall pip and python
