### ISSUE TITLE
Can not install on Raspberry Pi 3

### ISSUE THREAD

**Issue by xros** [mitmproxy/mitmproxy#1249]
##### Steps to reproduce the problem:

1. ```apt-get install python-virtualenv libffi-dev g++ libssl-dev build-enssencial```
2. ```git clone https://github.com/mitmproxy/mitmproxy.git
cd mitmproxy
./dev.sh```
3. then error came out  
```+ pip install -U pip setuptools
Traceback (most recent call last):
  File "/home/pi/software/sniffo/mitmproxy/venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/__init__.py", line 76, in <module>
    from pip.commands import commands, get_summaries, get_similar_commands
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/commands/__init__.py", line 6, in <module>
    from pip.commands.bundle import BundleCommand
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/commands/bundle.py", line 6, in <module>
    from pip.commands.install import InstallCommand
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/commands/install.py", line 5, in <module>
    from pip.req import InstallRequirement, RequirementSet, parse_requirements
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/req/req_install.py", line 42, in <module>
    from pip.utils.hashes import Hashes
  File "/home/pi/software/sniffo/mitmproxy/venv/lib/python2.7/site-packages/pip/utils/hashes.py", line 5, in <module>
    from pip.exceptions import HashMismatch, HashMissing, InstallationError
ImportError: cannot import name HashMissing```

##### What is the expected behavior?

Install mitmproxy on raspberry pi 3 `rasbian 2016-05-27 `

> Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux


##### What went wrong?

ImportError: cannot import name HashMissing


##### Any other comments? What have you tried so far?

Search module `HashMissing` but not found. It's a pip bug?

---

Mitmproxy Version: 0.17.1 (cloned from github right now)
Operating System: rasbian 4.4.11-v7+  armv7l GNU/Linux


<!-- Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks! :) -->

**Comment by dufferzafar** [comment]
@xros This doesn't really seem like a mitmproxy issue. Have you tried installing other packages on your pi?

**Comment by dufferzafar** [comment]
I had a chat with the guys over at #pypa IRC channel and they see this as a broken pip install. Please try to re-install pip.
