### ISSUE TITLE
error Installing in Ubuntu 16.04

### ISSUE THREAD

**Issue by FreelancePentester** [mitmproxy/mitmproxy#1295]
##### Steps to reproduce the problem:

1. sudo pip install mitmproxy==0.16
 

##### What is the expected behavior?

Collecting mitmproxy==0.16
  Downloading mitmproxy-0.16-py2-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 110kB/s 
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.16)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

---

Mitmproxy Version: 0.16
Operating System:Ubuntu 16.04

**Comment by Kriechi** [comment]
seems related to https://github.com/pypa/pip/pull/3307.

**Comment by mhils** [comment]
I'm closing this as this is out of our control. If you encounter this, upgrading pip should help.
