### ISSUE TITLE
Installation from master branch fails

### ISSUE THREAD

**Issue by neurobin** [mitmproxy/mitmproxy#1303]
##### Steps to reproduce the problem:

1. Install with `sudo -H pip install git+https://github.com/mitmproxy/mitmproxy.git`
2. Run `mitmproxy --version`

##### What is the expected behavior?
Should run without any error

##### What went wrong?
It shows the following error:
```python
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typing==3.5.2.2' distribution was not found and is required by mitmproxy

```

##### Any other comments? What have you tried so far?
1. I have tried to `pip uninstall netlib` and `pip install netlib`, but the uninstall command shows `Can't uninstall 'netlib'. No files were found to uninstall.`
2. I have tried to install it by downloading the source and following the hacking section in the README, but get this error:

```python
Traceback (most recent call last):
  File "/home/jahid/softs/mitmproxy-master/venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in <module>
    from .connection import (
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 41, in <module>
    from .util import (
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .response import is_fp_closed
  File "/home/jahid/softs/mitmproxy-master/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/response.py", line 4, in <module>
    from ..exceptions import HeaderParsingError
ImportError: cannot import name HeaderParsingError
```

---

Mitmproxy Version: master branch
Operating System: Xubuntu 14.04.4
Python version: 2.7.6

**Comment by Kriechi** [comment]
What pip version do you have? `pip -V`
Please try updating pip. I'm using 8.1.2 - which works and installs everything properly.
AFAIK we are only testing python 2.7.11 - maybe you could try updating python as well?

**Comment by neurobin** [comment]
Seems like lower version is the cause. with pip 8.1.2 and python 2.7.11 on Xubuntu 16.04 it installed correctly.
