### ISSUE TITLE
Please create a hook for intercepting and modifying CONNECT requests

### ISSUE THREAD

**Issue by pwnall** [mitmproxy/mitmproxy#1304]
The `request` hook for inline scripts appears to not be invoked at all for some CONNECT requests:

Specifically, [this branch](https://github.com/mitmproxy/mitmproxy/blob/1ffc273c9433fc8840b71c79879ae427c93313bd/mitmproxy/protocol/http.py#L156) does not [call the request hook](https://github.com/mitmproxy/mitmproxy/blob/1ffc273c9433fc8840b71c79879ae427c93313bd/mitmproxy/protocol/http.py#L174) at all.

**Comment by mhils** [comment]
This is correct - CONNECT requests are only passed to the script hook in upstream proxy mode at the moment, as they are not forwarded to the server in other settings.

Why do you want to intercept/modify these CONNECT requests?

**Comment by pwnall** [comment]
Thank you for reading my issue and starting a conversation!

I'm using mitmproxy to stub a server. For some hairy reasons, I have to intercept requests to `https://localhost:5000` and redirect them to `http://localhost:5000`. The server doesn't support HTTPS, so when mitmproxy attempts to connect, I get the following stack trace.

```
127.0.0.1:49165: Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 358, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/http1.py", line 67, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 171, in __call__
    self.handle_regular_mode_connect(request)
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 263, in handle_regular_mode_connect
    layer()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 353, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 435, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 429, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 540, in _establish_tls_with_server
    sys.exc_info()[2]
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 507, in _establish_tls_with_server
    alpn_protos=alpn,
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/mitmproxy/models/connections.py", line 185, in establish_ssl
    self.convert_to_ssl(cert=clientcert, sni=sni, **kwargs)
  File "/usr/local/Cellar/mitmproxy/0.17.1/libexec/lib/python2.7/site-packages/netlib/tcp.py", line 665, in convert_to_ssl
    raise TlsException("SSL handshake error: %s" % repr(v))
TlsProtocolException: Cannot establish TLS with localhost:5000 (sni: None): TlsException("SSL handshake error: SysCallError(-1, 'Unexpected EOF')",)
```

**Comment by mhils** [comment]
Would running mitmproxy as a reverse proxy solve your issue? This strips of TLS automatically.

```
mitmproxy -R http://localhost:5000 -p 443
```

**Comment by pwnall** [comment]
If it helps, here is a repro that doesn't involve most of my debugging setup.

1. Start a http server at localhost:5000
2. `mitmproxy -s scripts/dev/proxy_heap_assets.py -e -f -v`
3. `curl --proxy http://localhost:8080 https://localhost:5000 --insecure`

**Comment by mhils** [comment]
Alternatively, you can pass `--no-upstream-cert` and modify `request.scheme` in the script hook for the actual requests.

**Comment by pwnall** [comment]
`--no-upstream-cert` is brilliant, thank you! This solves my problem!

Pushing my luck a bit: can I set this somewhere in a script hook? It'd be nicer if I can enforce this, rather than just document it in my README. Either way, thank you very much, this unblocked me!

**Comment by mhils** [comment]
You could monkeypatch your way at the moment (`context._master.options`), but we may be able to make this an official feature with #1265. No promises yet though.
On an unrelated note, we're always happy to hear what people are building :smiley:

**Comment by pwnall** [comment]
A blog post praising mitmproxy is in the works, but this can give you an idea of what we're doing with it. Once again, thank you very much for the quick help!

```python
"""
This is a mitmproxy script that redirects HTTP requests for Heap assets to a
dev server, which is expected to be listening at http://localhost:8000.

To facilitate VED debugging, the script also redirects all requests from
https://localhost:5000 to http://localhost:5000. This redirect only
works if mitmproxy is started with the --no-upstream-cert argument. Otherwise,
a TlsProtocolException will be raised when a client attempts to connect to
https://localhost:5000.
"""
import posixpath

asset_extensions = [".css", ".js", ".map", ".png"]

"""
mitmproxy hook for inspecting and modifying HTTP requests

See http://docs.mitmproxy.org/en/stable/scripting/inlinescripts.html#request
"""
def request(context, flow):
    if not request_targets_heap_server(flow.request):
        return

    if heap_request_belongs_to_dev(flow.request):
        redirect_to_dev(flow)

"""
True if the request targets Heap production backends that we want to redirect.
"""
def request_targets_heap_server(request):
    # We're currently interested in heapanalytics.com and
    # cdn.heapanalytics.com. This check should cover future production domains
    # that we care about.
    # When we load the VED from https sites, we'll end up trying to load the
    # CSS and JS from https://localhost:5000 instead of htttp://localhost:5000.
    if request.pretty_host.endswith("heapanalytics.com"):
        return True

    if (request.scheme == "https" and request.pretty_host == "localhost" and
            request.port == 5000):
        return True
    return False

"""
True if a request targeting a Heap prod backend should be redirected to dev.
"""
def heap_request_belongs_to_dev(request):
    # The dev backend doesn't understand SSL, so we have to proxy all the
    # requests from https://localhost:5000 to http://localhost:5000
    if request.pretty_host == "localhost" and request.port == 5000:
        return True

    # CONNECT methods do not include the path information we use in the
    # decisions below.
    if request.method == "CONNECT":
        return False

    # Turns out that request.path actually contains the querystring as well. So
    # we need to pull it out ourselves.
    request_path = request.path.split('?')[0]
    path_and_file, extension = posixpath.splitext(request_path)
    if extension in asset_extensions:
        return True

"""
Redirects the current HTTP request in a flow to the dev server.

This assumes that the dev server runs on the same machine as mitmproxy.
"""
def redirect_to_dev(flow):
    flow.request.scheme = "http"
    flow.request.host = "localhost"
    flow.request.port = 8000
```

**Comment by amankumarjain** [comment]
While creating CONNECT call with server i am getting this error(below), after that, i'm not getting any log but request gets forwarded to server without being captured, can you please explain why it is happening
 
error:
Cannot establish TLS with client (sni: {some_domain_name}): TlsException("(-1, 'Unexpected EOF')",)
