### ISSUE TITLE
HTTP2 Error when opening news.ycombinator.com

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1326]
##### Steps to reproduce the problem:

1. Open news.ycombinator.com in Firefox

##### What is the expected behavior?

No errors.

##### What went wrong?

```
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http2.py", line 512, in run
    self()
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http2.py", line 518, in __call__
    layer()
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http.py", line 178, in __call__
    self.get_response_from_server(flow)
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http.py", line 276, in get_response_from_server
    get_response()
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http.py", line 272, in get_response
    self.send_request(flow.request)
  File "c:\users\user\git\mitmproxy\mitmproxy\protocol\http2.py", line 429, in send_request
    raise e
ProtocolError: Stream 3 may not depend on itself
```

---

Mitmproxy Version: master
Operating System: Win64

**Comment by chhsiao90** [comment]
It seams that mitmproxy send request_header with priority_depend_on stream id that was a "client stream id", not  a server stream id   
at http2.py: 418
```python
 try:
     self.server_conn.h2.safe_send_headers(
         self.is_zombie,
         self.server_stream_id,
         headers,
         end_stream=self.no_body,
         priority_weight=self.priority_weight,
         priority_depends_on=self.priority_depends_on,
         priority_exclusive=self.priority_exclusive,
     )
 except Exception as e:
     raise e
 finally:
     self.server_conn.h2.lock.release()
```

**Comment by mhils** [comment]
@chhsiao90: Fantastic find, thanks! :smiley: Do you want to submit a PR that fixes this?

**Comment by chhsiao90** [comment]
@mhils: No problem, I would like to work on this!

**Comment by Kriechi** [comment]
`3` is a client stream id. I assume you are using Firefox?
I think Firefox has this odd behaviour, that it sends a few PriorityFrames at the beginning of a connection, to "reserve" streams (or something like that).

**Comment by chhsiao90** [comment]
The problem is much complicated as I thought if we want to handle PriorityUpdated event.
I had some debug tool to record the h2 event from firefox to server.
And it will create several PriorityUpdated event and each had its stream_id and depends_on stream_id before first Request sent.
```
<RemoteSettingsChanged changed_settings:{4: ChangedSetting(setting=4, original_value=65535, new_value=131072), 5: ChangedSetting(setting=5, original_value=16384, new_value=16384
)}>
<WindowUpdated stream_id:0, delta:12517377>
<PriorityUpdated stream_id:3, weight:201, depends_on:0, exclusive:False>
<PriorityUpdated stream_id:5, weight:101, depends_on:0, exclusive:False>
<PriorityUpdated stream_id:7, weight:1, depends_on:0, exclusive:False>
<PriorityUpdated stream_id:9, weight:1, depends_on:7, exclusive:False>
<PriorityUpdated stream_id:11, weight:1, depends_on:3, exclusive:False>
<RequestReceived stream_id:13, headers:[(u':method', u'GET'), (u':path', u'/from?site=nytimes.com'), (u':authority', u'news.ycombinator.com'), (u':scheme', u'https'), (u'user-ag
ent', u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0'), (u'accept', u'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), (u
'accept-language', u'en-US,en;q=0.5'), (u'accept-encoding', u'gzip, deflate, br'), (u'cookie', u'__cfduid=d44db1f90228df2c224a681f646e888ce1467951413'), (u'pragma', u'no-cache')
, (u'cache-control', u'no-cache')]>
<StreamEnded stream_id:13>
<PriorityUpdated stream_id:13, weight:32, depends_on:11, exclusive:False>
<WindowUpdated stream_id:13, delta:12451840>
 <RemoteSettingsChanged changed_settings:{3: ChangedSetting(setting=3, original_value=None, new_value=128), 4: ChangedSetting(setting=4, original_value=65535, new_value=21474836
47), 5: ChangedSetting(setting=5, original_value=16384, new_value=16777215)}>
 <WindowUpdated stream_id:0, delta:2147418112>
<SettingsAcknowledged changed_settings:{}>
 <SettingsAcknowledged changed_settings:{}>
<RequestReceived stream_id:15, headers:[(u':method', u'GET'), (u':path', u'/news.css?XcgHNoMJ8uG2XlyGKzF0'), (u':authority', u'news.ycombinator.com'), (u':scheme', u'https'), (u
'user-agent', u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0'), (u'accept', u'text/css,*/*;q=0.1'), (u'accept-language', u'en-US,en;q=0.5')
, (u'accept-encoding', u'gzip, deflate, br'), (u'referer', u'https://news.ycombinator.com'), (u'cookie', u'__cfduid=d44db1f90228df2c224a681f646e888ce1467951413'), (u'pragma', u'
no-cache'), (u'cache-control', u'no-cache')]>
<StreamEnded stream_id:15>
<PriorityUpdated stream_id:15, weight:32, depends_on:3, exclusive:False>
```

I had tried created a new stream_id at server connection for each PriorityUpdated arrived.
But I had found that hyper-h2 would always give me stream_id: 1 before first header was sent or push

From hyper-h2 documentation: get_next_available_stream_id()
> The return value from this function does not change until the stream ID has actually been used by sending or pushing headers on that stream. For that reason, it should be called as close as possible to the actual use of the stream ID.

So I had no idea how to handle these weird PriorityUpdated event

**Comment by chhsiao90** [comment]
@Kriechi : 
Thanks for your advice!
I used Firefox as the test client.
Is it abnormal to send several PriorityUpdated event before request sent?
I'm not familiar with PriorityUpdated control on http2.
So maybe the problem is caused by browser?

**Comment by Kriechi** [comment]
Firefox is allowed to do that.
I got a PR almost ready which fixes the problem. However, I think we cannot guarantee 100% accurate priority information between client and server. But it should be good enough to not cause problems.

**Comment by chhsiao90** [comment]
Got it! thanks
