### ISSUE TITLE
Mitmproxy crashes on startup

### ISSUE THREAD

**Issue by rubenvereecken** [mitmproxy/mitmproxy#1358]
`mitmproxy`

Nets me this hairy beast:

```
Traceback (most recent call last):
  File "/home/ruben/anaconda/lib/python2.7/site-packages/mitmproxy-0.18-py2.7.egg/mitmproxy/console/master.py", line 529, in run
    self.loop.run()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/home/ruben/anaconda/lib/python2.7/site-packages/mitmproxy-0.18-py2.7.egg/mitmproxy/console/master.py", line 524, in <lambda>
    lambda *args: self.view_flowlist()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/mitmproxy-0.18-py2.7.egg/mitmproxy/console/master.py", line 612, in view_flowlist
    statusbar.StatusBar(self, flowlist.footer),
  File "/home/ruben/anaconda/lib/python2.7/site-packages/mitmproxy-0.18-py2.7.egg/mitmproxy/console/statusbar.py", line 126, in __init__
    self.redraw()
  File "/home/ruben/anaconda/lib/python2.7/site-packages/mitmproxy-0.18-py2.7.egg/mitmproxy/console/statusbar.py", line 249, in redraw
    t.extend(self.get_status())
  File "/home/ruben/anaconda/lib/python2.7/site-packages/mitmproxy-0.18-py2.7.egg/mitmproxy/console/statusbar.py", line 227, in get_status
    if self.master.stream:
AttributeError: 'ConsoleMaster' object has no attribute 'stream'
```

Mitmproxy Version: 0.18 - fresh off of master
Operating System: Let's say Ubuntu 14.04 and lie

I installed by running `python setup.py install`

**Comment by mhils** [comment]
Fixed, thanks! :smiley:

**Comment by rubenvereecken** [comment]
Cheers man :)
