### ISSUE TITLE
Error when killing finished flow.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1396]
##### Steps to reproduce the problem:

1. `mitmproxy`
2. Record flow.
3. Press `X` on finished flow.

##### What is the expected behavior?
No crash.

##### What went wrong?
```
Traceback (most recent call last):
  File "/media/sf_git/mitmproxy/mitmproxy/console/master.py", line 502, in run
    self.loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/media/sf_git/mitmproxy/mitmproxy/console/window.py", line 42, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/lib/python3.5/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/media/sf_git/mitmproxy/mitmproxy/console/flowlist.py", line 408, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/local/lib/python3.5/dist-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/media/sf_git/mitmproxy/mitmproxy/console/flowlist.py", line 258, in keypress
    self.flow.kill(self.master)
  File "/media/sf_git/mitmproxy/mitmproxy/models/flow.py", line 154, in kill
    self.reply.kill()
  File "/media/sf_git/mitmproxy/mitmproxy/controller.py", line 255, in kill
    self.send(exceptions.Kill)
  File "/media/sf_git/mitmproxy/mitmproxy/controller.py", line 262, in send
    raise exceptions.ControlException("Message already acked.")
mitmproxy.exceptions.ControlException: Message already acked.
```

---

Mitmproxy Version: master
Operating System: Ubuntu 14.04 x64

**Comment by dufferzafar** [comment]
Because this is happening in `flow.kill` It also affects the `d` key (delete flow,)

**Comment by mhils** [comment]
Right. This is a possible duplicate of #1396 and #1374.

**Comment by dufferzafar** [comment]
@mhils THIS issue is #1396 :stuck_out_tongue_closed_eyes:

**Comment by mhils** [comment]
As I said, clear duplicate :stuck_out_tongue: 

I actually meant #1205 I believe.
