### ISSUE TITLE
[PY3] Cannot modify "Set Header" patterns

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1403]
##### Steps to reproduce the problem:

1. `mitmproxy`
2. `o enter a`

##### What went wrong?

```
Traceback (most recent call last):
  File "/media/sf_git/mitmproxy/mitmproxy/console/master.py", line 498, in run
    self.loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/media/sf_git/mitmproxy/mitmproxy/console/window.py", line 42, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/lib/python3.5/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/media/sf_git/mitmproxy/mitmproxy/console/grideditor.py", line 441, in keypress
    self.walker.add()
  File "/media/sf_git/mitmproxy/mitmproxy/console/grideditor.py", line 257, in add
    return self._insert(min(self.focus + 1, len(self.lst)))
  File "/media/sf_git/mitmproxy/mitmproxy/console/grideditor.py", line 251, in _insert
    self.start_edit()
  File "/media/sf_git/mitmproxy/mitmproxy/console/grideditor.py", line 263, in start_edit
    self.focus_col, True, self.editor, self.lst[self.focus]
  File "/media/sf_git/mitmproxy/mitmproxy/console/grideditor.py", line 144, in __init__
    self.editing = SEdit(v)
  File "/media/sf_git/mitmproxy/mitmproxy/console/grideditor.py", line 123, in __init__
    txt = txt.encode("string-escape")
LookupError: unknown encoding: string-escape
```

---

Mitmproxy Version: master
Operating System: Ubuntu 14.04 x64

**Comment by mhils** [comment]
This applies to all features using the GridEditor and is - as far as I tested - the last big thing that hold off Python 3 support :smiley:
