### ISSUE TITLE
console: Javascript content view broken

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1431]
##### Steps to reproduce the problem:

1. Use Python3 to view application/javascript data

##### What is the expected behavior?

No crash

##### What went wrong?

```
Content viewer failed:
Traceback (most recent call last):
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/contentviews.py", line 634, in get_content_view
    ret = viewmode(data, **metadata)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/contentviews.py", line 151, in __call__
    return content_types_map[ct][0](data, **metadata)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/contentviews.py", line 401, in __call__
    res = jsbeautifier.beautify(data, opts)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/contrib/jsbeautifier/__init__.py", line 93, in beautify
    return b.beautify(string, opts)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/contrib/jsbeautifier/__init__.py", line 218, in beautify
    token_text, token_type = self.get_next_token()
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/contrib/jsbeautifier/__init__.py", line 443, in
get_next_token
    if c in self.wordchar:
TypeError: 'in <string>' requires string as left operand, not int
```

---

Mitmproxy version: 0.18
Python version: 3.5.1
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2h  3 May 2016
Mac version: 10.11.6 ('', '', '') x86_64

**Comment by dufferzafar** [comment]
The [beautifier](https://github.com/beautify-web/js-beautify) has been updated since we added it to our codebase. I'll test out whether it has working Python 3 support, and maybe we can just depend on it directly via pip or was there some particular reason to keep the file as-is in the repo?
