### ISSUE TITLE
mitmproxy crashed.

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1438]
On redirecting request using method 1 from examples section, when I am killing mitmproxy, getting following error:
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mitmproxy-0.17.1-py2.7.egg/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
----------------------------------------
Error in processing of request from 10.36.81.212:60796
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mitmproxy-0.17.1-py2.7.egg/netlib/tcp.py", line 854, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/Library/Python/2.7/site-packages/mitmproxy-0.17.1-py2.7.egg/mitmproxy/proxy/server.py", line 64, in handle_client_connection
    h.handle()
  File "/Library/Python/2.7/site-packages/mitmproxy-0.17.1-py2.7.egg/mitmproxy/proxy/server.py", line 152, in handle
    self.channel.tell("clientdisconnect", root_layer)
  File "/Library/Python/2.7/site-packages/mitmproxy-0.17.1-py2.7.egg/mitmproxy/controller.py", line 68, in tell
    m.reply = DummyReply()
AttributeError: 'NoneType' object has no attribute 'reply'

```

**Comment by mhils** [comment]
I believe this should be fixed with the next release. Thanks for the report!
