### ISSUE TITLE
mitmdump crashes on start of server-replay: KeyError: 'marked'

### ISSUE THREAD

**Issue by markus-kusano** [mitmproxy/mitmproxy#1497]
[rec.zip](https://github.com/mitmproxy/mitmproxy/files/428987/rec.zip)

##### Steps to reproduce the problem:

1. Run mitmdump with the attached recording: `mitmdump --server-replay findastation.out`
2. An exception is thrown:

```
Traceback (most recent call last):
  File "/home/markus/src/mitmproxy/venv3.5/bin/mitmdump", line 11, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmdump')()
  File "/home/markus/src/mitmproxy/mitmproxy/main.py", line 102, in mitmdump
    master = dump.DumpMaster(server, dump_options)
  File "/home/markus/src/mitmproxy/mitmproxy/dump.py", line 64, in __init__
    self._readflow(options.server_replay),
  File "/home/markus/src/mitmproxy/mitmproxy/dump.py", line 96, in _readflow
    return flow.read_flows_from_paths(paths)
  File "/home/markus/src/mitmproxy/mitmproxy/flow/io.py", line 83, in read_flows_from_paths
    flows.extend(FlowReader(f).stream())
  File "/home/markus/src/mitmproxy/mitmproxy/flow/io.py", line 49, in stream
    yield models.FLOW_TYPES[data["type"]].from_state(data)
  File "/home/markus/src/mitmproxy/mitmproxy/models/flow.py", line 112, in from_state
    f.set_state(state)
  File "/home/markus/src/mitmproxy/mitmproxy/models/flow.py", line 107, in set_state
    super(Flow, self).set_state(state)
  File "/home/markus/src/mitmproxy/mitmproxy/stateobject.py", line 55, in set_state
    val = state.pop(attr)
KeyError: 'marked'
```

##### What is the expected behavior?

`mitmdump` continues running and the replayed page is served

##### Any other comments? What have you tried so far?

Note that this is a recording made with an olderversion of mitmproxy, probably from about 2 months ago. Other recordings do not crash similarly.

Running on commit 62ab2f2fd5188f31e99560dce788ba85c2933a1a with Python 3.5 on Linux.

Thanks :)

**Comment by dufferzafar** [comment]
This is because we made a change that stores the `marked` attribute (whether or not a flow was marked in the UI) to the "recordings" so old recordings will not work, sadly. 

I'm not sure if we can just keep default values for attributes that were not found in the files.

**Comment by mhils** [comment]
We currently only support version migrations between stable releases. Your traceback hints that you recorded your flows with mitmproxy 0.18 from master. You can fix this by adding `state["marked"] = False` in convert_flow in mitnproxy.flow.io_compat. (IIRC, on mobile atm)

**Comment by mhils** [comment]
@dufferzafar: 0.17- recordings work fine, it's just 0.18 recordings from master (which don't go through the migration) :smiley:

**Comment by markus-kusano** [comment]
Thanks for the fast response :) I should be able to work it out.
