### ISSUE TITLE
HttpSyntaxException during transparent proxy with ca installed on client

### ISSUE THREAD

**Issue by pgconlin** [mitmproxy/mitmproxy#1516]
##### Steps to reproduce the problem:

1. install ca.pem on client machine
2. `mitmproxy -T --ciphers-client ALL --ciphers-server ALL --cert ../certificate-authority/ca.pem -b 192.168.2.200 --conf ../.mitmproxy/standard.conf`

##### What is the expected behavior?
Successful interception

##### What went wrong?

```
192.168.2.101:55347: ProtocolException('Error in HTTP connection: HttpSyntaxException(\'Bad HTTP request line:`
{"content":{"type":"fallback_url"},"operation":"Request"}\',)',)`
192.168.2.101:55347: Traceback (most recent call last):`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle`
    root_layer()`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__  layer()`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 358, in __call__`
    layer()`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 67, in __call__`
    layer()`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 180, in __call__`
    "Error in HTTP connection: %s" % repr(e)), sys.exc_info()[2])`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 156, in __call__`
    request = self.get_request_from_client()`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 238, in get_request_from_client`
    request = self.read_request()`
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/http1.py", line 17, in read_request`
    req = http1.read_request(self.client_conn.rfile, body_size_limit=self.config.body_size_limit)`
  File "/usr/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 12, in read_request`
    request = read_request_head(rfile)`
  File "/usr/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 38, in read_request_head`
    form, method, scheme, host, port, path, http_version = _read_request_line(rfile)`
  File "/usr/lib/python2.7/dist-packages/netlib/http/http1/read.py", line 247, in _read_request_line
    raise HttpSyntaxException("Bad HTTP request line: {}".format(line))`
ProtocolException: Error in HTTP connection: HttpSyntaxException('Bad HTTP request line: {"content":{"type":"fallback_url"},"operation":"Request"}',)`
```
##### Any other comments? What have you tried so far?

---

Mitmproxy Version:
mitmproxy 0.17.1
Operating System:
Linux 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by Kriechi** [comment]
Thanks for the report!
What website are you trying to intercept? 
Is this a public service? 
A regular website or some special application server?

It seems the first line that is read from the client is 
`{"content":{"type":"fallback_url"},"operation":"Request"}` - which is quite weird...

**Comment by mhils** [comment]
I cannot reproduce this either. Any hints?
