### ISSUE TITLE
mitmproxy crashes after typing 'mitmproxy' in terminal

### ISSUE THREAD

**Issue by yychun1990** [mitmproxy/mitmproxy#1537]
##### Steps to reproduce the problem:

1. follow the Hacking method in README until 'py.test'
2. enter 'mitmproxy' in terminal 
3. mitmproxy crashes

##### What is the expected behavior?
Certificate should have been installed

##### What went wrong?
Traceback (most recent call last):
  File "/Users/xxx/mitmproxy/mitmproxy/console/master.py", line 537, in run
    self.loop.run()
  File "/Users/xxx/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/yychun1217/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/Users/xxx/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/Users/xxx/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/Users/xxx/mitmproxy/venv/lib/python2.7/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/Users/xxx/mitmproxy/mitmproxy/console/master.py", line 532, in <lambda>
    lambda *args: self.view_flowlist()
  File "/Users/xxx/mitmproxy/mitmproxy/console/master.py", line 620, in view_flowlist
    statusbar.StatusBar(self, flowlist.footer),
  File "/Users/xxx/mitmproxy/mitmproxy/console/statusbar.py", line 128, in __init__
    self.redraw()
  File "/Users/xxx/mitmproxy/mitmproxy/console/statusbar.py", line 246, in redraw
    t.extend(self.get_status())
  File "/Users/xxx/mitmproxy/mitmproxy/console/statusbar.py", line 151, in get_status
    if self.master.server_playback:
AttributeError: 'ConsoleMaster' object has no attribute 'server_playback'

mitmproxy has crashed!
Please lodge a bug report at:
       	https://github.com/mitmproxy/mitmproxy
Shutting down...

##### Any other comments? What have you tried so far?

---

Mitmproxy Version: 0.18
Operating System: Mac El Capitan 10.11.6

**Comment by yychun1990** [comment]
thx in advance

**Comment by Kriechi** [comment]
Thanks for the bug report.
We are aware of the issue and @cortesi will have a fix ready in a few days.

**Comment by cortesi** [comment]
Fixed. Thanks for reporting this.
