### ISSUE TITLE
Invalid HTTP request form (expected: relative, got: authority)

### ISSUE THREAD

**Issue by d3xt3r01** [mitmproxy/mitmproxy#1579]
##### Steps to reproduce the problem:

1.  mitmproxy -T --no-http2 -p 8888 -v -e --no-mouse
2. curl https://google.com --proxy http://127.0.0.1:8888 -v -k

##### What is the expected behavior?
Page would show up !

##### What went wrong?
```
127.0.0.1:39126: clientconnect
127.0.0.1:39126: HTTP protocol error in client request: Invalid HTTP request form (expected: relative, got: authority)
127.0.0.1:39126: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/usr/lib64/python2.7/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__
    layer()
  File "/usr/lib64/python2.7/site-packages/mitmproxy/protocol/tls.py", line 391, in __call__
    layer()
  File "/usr/lib64/python2.7/site-packages/mitmproxy/protocol/http1.py", line 75, in __call__
    layer()
  File "/usr/lib64/python2.7/site-packages/mitmproxy/protocol/http.py", line 159, in __call__
    sys.exc_info()[2]
  File "/usr/lib64/python2.7/site-packages/mitmproxy/protocol/http.py", line 146, in __call__
    self.validate_request(request)
  File "/usr/lib64/python2.7/site-packages/mitmproxy/protocol/http.py", line 411, in validate_request
    raise netlib.exceptions.HttpException(err_message)
ProtocolException: HTTP protocol error in client request: Invalid HTTP request form (expected: relative, got: authority)

127.0.0.1:39126: clientdisconnect
```

```
$ curl https://google.com --proxy http://127.0.0.1:8888 -v -k
* Rebuilt URL to: https://google.com/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8888 (#0)
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.50.3
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 400 Bad Request
< Content-Length: 214
< Content-Type: text/html
< Connection: close
< Server: mitmproxy 0.18
<
* Received HTTP code 400 from proxy after CONNECT
* Curl_http_done: called premature == 0
* Closing connection 0
curl: (56) Received HTTP code 400 from proxy after CONNECT
```
##### Any other comments? What have you tried so far?

I've tried 0.11.3 and hit a too many files open bug .. I've tried 0.17.1 with same issue ... then moved to master.

---
Mitmproxy Version: mitmproxy 0.18
Operating System: Gentoo

**Comment by dwfreed** [comment]
You're running mitmproxy in transparent mode, but then trying to use it as a regular HTTP proxy.  Transparent mode is meant to be used with something like the iptables REDIRECT target to capture applications not capable of using an HTTP proxy normally.  Drop the transparent mode flag, and curl will work just fine.

**Comment by d3xt3r01** [comment]
Yep, my bad. There should be some message that would recommend this instead of the stacktrace ! :)
Thanks.
