### ISSUE TITLE
Mitmproxy crashes after launch

### ISSUE THREAD

**Issue by ChillarAnand** [mitmproxy/mitmproxy#1604]
##### Steps to reproduce the problem:

1. Install and start proxy, it crashes
2. 
3. 

```
Traceback (most recent call last)
mitmproxy has crashed!nand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/proxy/server.py", line 121,
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 11,
    layer()
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 358, in __call__fd1e393e7c236376641880238704883349a222f7e02b8accb4973e4ba3fa010b999d9b980d52570b268a9
    layer()
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/http1.py", line 67, in __call__a4bd37164054eb3fc7d25f30812060c03e6007c9bed294782f986e33de89beb1f6f77214d55645cf78aa
    layer()
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 171, in __call__efc8ca5ae2da4c034788a6dc037bcb8a59c4a
    self.handle_regular_mode_connect(request)
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 263, in handle_regular_mode_connect
    layer()
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/tls.py", line 358, in __call__ndroid&action=session&advertiser_id=189774&package_name=is.shortcut&data=9eef909e4dfd
    layer()
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/http2.py", line 238, in __call__3944bfc0abcfcc7d9b3b15fcf6a6bfe8a65088ad6d575d7ff49443a6ceb9cf5d290620a873e1c51a998
    if not self._handle_event(event, source_conn, other_conn, is_server):
  File "/home/chillaranand/.virtualenvs/27/local/lib/python2.7/site-packages/mitmproxy/protocol/http2.py", line 199, in _handle_eventcd0a29a0da96368d36e804c783d181a744b7a22556b0788b142276bda1d6de8c6639872de0a7bf
    raise NotImplementedError()
NotImplementedError

```
##### Any other comments? What have you tried so far?

---

Mitmproxy Version:
mitmproxy 0.17

Operating System:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

**Comment by Kriechi** [comment]
Thanks for the report.
What website are you trying to access?
What browser are you using?

You can disable HTTP/2 support to get rid of this error.
HTTP/2 support is greatly improved in the current git master, which will soon be released as a new version to pypi.

**Comment by ChillarAnand** [comment]
I was using chrome and visiting ireff.in . I will try master branch. Thank you.
