### ISSUE TITLE
 macOS 10.12 Crash.

### ISSUE THREAD

**Issue by ximerus** [mitmproxy/mitmproxy#1607]
Hi, guys. After update to macOS 10.12 mitmproxy don't work with anyone params or without params.

Here is traceback:

```
$ mitmproxy   

Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/Library/Python/2.7/site-packages/mitmproxy/main.py", line 45, in mitmproxy
    from . import console
  File "/Library/Python/2.7/site-packages/mitmproxy/console/__init__.py", line 19, in <module>
    from .. import controller, flow, script, contentviews
  File "/Library/Python/2.7/site-packages/mitmproxy/flow.py", line 21, in <module>
    from .onboarding import app
  File "/Library/Python/2.7/site-packages/mitmproxy/onboarding/app.py", line 3, in <module>
    import tornado.web
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 84, in <module>
    from tornado import gen
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1236, in <module>
    import tornado.platform.asyncio
  File "/Library/Python/2.7/site-packages/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio
  File "/Library/Python/2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/Library/Python/2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by Kriechi** [comment]
How did you install mitmproxy?
Did you use pip or the provided binaries for OSX?
Can you try reinstall it and see if the errors goes away?

The actual problem seems to be in asyncio (and not in mitmproxy), so maybe there is a different problem?

**Comment by dwfreed** [comment]
I'd love to know how you installed asyncio on python 2.7, because asyncio doesn't work on python 2.7, which is why you're getting that exception.

**Comment by ximerus** [comment]
asyncio is installed, and I try to install for python3, and whatever don't work.

**Comment by mhils** [comment]
Sorry, but as @dwfreed has hinted at, your Python installation just seems pretty broken. asyncio is

**Comment by martinobonfiglioli** [comment]
Same issue here, any solution to solve it? @ximerus

**Comment by ximerus** [comment]
I'm installed with [Hacks](https://github.com/mitmproxy/mitmproxy#hacking) from doc. Clone repo from github, and run like in manual.

**Comment by ximerus** [comment]
What method help me with clear installation: sudo -H pip install --ignore-installed pyparsing mitmproxy
