### ISSUE TITLE
StackTrace printed if you quit mitmproxy and any flow is in intercept mode

### ISSUE THREAD

**Issue by mkagenius** [mitmproxy/mitmproxy#1620]
##### Steps to reproduce the problem:

1. Launch mitmproxy
2. intercept any request
3. quit mitmproxy while the request still intercept

##### What is the expected behavior?
Did not expect the stacktrace ... earlier it used to be no such error

##### What went wrong?
```
Traceback (most recent call last):
  File "/Users/manish/Work/mitmproxy/venv/bin/mitmproxy", line 11, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmproxy')()
  File "/Users/manish/Work/mitmproxy/mitmproxy/main.py", line 80, in mitmproxy
    m.run()
  File "/Users/manish/Work/mitmproxy/mitmproxy/console/master.py", line 495, in run
    self.shutdown()
  File "/Users/manish/Work/mitmproxy/mitmproxy/console/master.py", line 647, in shutdown
    self.state.killall(self)
  File "/Users/manish/Work/mitmproxy/mitmproxy/flow/state.py", line 269, in killall
    self.flows.kill_all(master)
  File "/Users/manish/Work/mitmproxy/mitmproxy/flow/state.py", line 182, in kill_all
    f.kill(master)
  File "/Users/manish/Work/mitmproxy/mitmproxy/models/flow.py", line 176, in kill
    master.error(self)
  File "/Users/manish/Work/mitmproxy/mitmproxy/controller.py", line 238, in wrapper
    ret = f(master, message)
  File "/Users/manish/Work/mitmproxy/mitmproxy/console/master.py", line 692, in error
    self.process_flow(f)
  File "/Users/manish/Work/mitmproxy/mitmproxy/console/master.py", line 681, in process_flow
    f.intercept(self)
  File "/Users/manish/Work/mitmproxy/mitmproxy/models/flow.py", line 186, in intercept
    self.reply.take()
  File "/Users/manish/Work/mitmproxy/mitmproxy/controller.py", line 314, in take
    raise exceptions.ControlException("Reply is {}, but expected it to be handled.".format(self.state))
mitmproxy.exceptions.ControlException: Reply is committed, but expected it to be handled.
```
##### Any other comments? What have you tried so far?
This may result in problems in saving flows to file? if any request is in intercept mode it might cause abort at that point .. only flows till that point gets saved.. i think, also, har dump may get problem due to this.. 

---

Mitmproxy Version: head, master
Operating System: mac

**Comment by mhils** [comment]
Thanks for the great bug report!
