### ISSUE TITLE
mitmdump client replay is broken

### ISSUE THREAD

**Issue by yifeikong** [mitmproxy/mitmproxy#1666]
##### Steps to reproduce the problem:

1. dump flow to a file by `mitmdump -p 10000 -w stats`
2. replay it by `mitmdump -nc stats`
3. then it crashes

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 11, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/main.py", line 102, in mitmdump
    master = dump.DumpMaster(server, dump_options)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/dump.py", line 41, in __init__
    self.addons.add(*builtins.default_addons())
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/addons.py", line 51, in add
    self.startup(i)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/addons.py", line 40, in startup
    self.master.options.keys()
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/addons.py", line 72, in invoke_with_context
    self.invoke(addon, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/addons.py", line 81, in invoke
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/builtins/clientplayback.py", line 22, in configure
    ctx.log.info(options.client_replay)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/controller.py", line 68, in info
    self(txt, "info")
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/controller.py", line 83, in __call__
    self.master.add_log(text, level)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/controller.py", line 122, in add_log
    self.addons("log", LogEntry(e, level))
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/addons.py", line 85, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/addons.py", line 81, in invoke
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/builtins/termlog.py", line 22, in log
    err=(e.level == "error")
  File "/usr/local/lib/python2.7/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python2.7/site-packages/click/termui.py", line 393, in style
    return ''.join(bits)
TypeError: sequence item 1: expected string, list found
```

##### Any other comments? What have you tried so far?

however, `mitmproxy -c stats` works fine

##### System information

on mac, with pip install mitmproxy, version 0.18.1

**Comment by mhils** [comment]
Thanks, this has been fixed! 😃
