### ISSUE TITLE
TypeError: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by nandub** [mitmproxy/mitmproxy#167]
I tried versions 0.9 and 0.9.1 but I'm getting this error on a Mac OS X Lion 10.7.5

```
> mitmproxy               
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 46, in <module>
    config = proxy.process_proxy_options(parser, options)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy.py", line 664, in process_proxy_options
    authenticator = authenticator
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy.py", line 52, in __init__
    self.certstore = certutils.CertStore(certdir)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by nesttle** [comment]
Similar problem here with mitmproxy 2.0.2 and `-s script.py ` argument:

```
Script error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libmproxy/script/script.py", line 93, in run
    return f(self.ctx, *args, **kwargs)
TypeError: response() takes exactly 1 argument (2 given)
```

netlib-0.17
