### ISSUE TITLE
Can't run windows release 0.18.2

### ISSUE THREAD

**Issue by remoe** [mitmproxy/mitmproxy#1746]
After a first connection it throws the following error:

```
Traceback (most recent call last):
  File "site-packages\netlib\tcp.py", line 918, in connection_thread
  File "site-packages\mitmproxy\proxy\server.py", line 66, in handle_client_connection
  File "site-packages\mitmproxy\proxy\server.py", line 116, in handle
  File "site-packages\mitmproxy\proxy\server.py", line 96, in _create_root_layer
  File "site-packages\mitmproxy\proxy\modes\transparent_proxy.py", line 12, in __init__
  File "site-packages\mitmproxy\platform\windows.py", line 22, in __init__
  File "site-packages\mitmproxy\platform\windows.py", line 235, in setup
  File "site-packages\mitmproxy\platform\windows.py", line 200, in __init__
  File "site-packages\pydivert\windivert.py", line 112, in __init__
ValueError: Unable to find WinDivert.dll

```
##### Steps to reproduce the problem:

1. download release from https://github.com/mitmproxy/mitmproxy/releases/tag/v0.18.2
2. run ```mitmdump.exe -T --host```
3. crash after first connection

##### System information

```
Mitmproxy version: 0.18.2
Python version: 3.5.2
Platform: Windows-7-6.1.7601-SP1
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by mhils** [comment]
Thanks for the report! We need to fix this by manually whitelisting the PyDivert data files in PyInstaller.

**Comment by mhils** [comment]
This should be fixed in the latest snapshot binaries, thanks again!

**Comment by remoe** [comment]
Yes! It works. I've tested it with:

```https://snapshots.mitmproxy.org/v0.19/mitmproxy-0.19dev0325-0xge64d2ce-win32.zip```

 Thanks!
