### ISSUE TITLE
SSLError in requirements.txt: hostname 'snapshots.mitmproxy.org' doesn't match 'slack.mitmproxy.org'

### ISSUE THREAD

**Issue by silascutler** [mitmproxy/mitmproxy#1755]
##### Steps to reproduce the problem:

1. run pip install -r requirements.txt

##### System information
mitmproxy# pip install -r requirements.txt 
Downloading/unpacking https://snapshots.mitmproxy.org/misc/lxml-3.6.0-cp35-cp35m-win32.whl; sys_platform == 'win32' and python_version == '3.5' (from -r requirements.txt (line 1))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: hostname 'snapshots.mitmproxy.org' doesn't match 'slack.mitmproxy.org'

Storing debug log for failure in /root/.pip/pip.log

pip freeze
Landscape-Client==14.12
Mako==0.9.1
MarkupSafe==0.18
PAM==0.4.2
Twisted-Core==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
html5lib==0.999
pyOpenSSL==0.13
pygobject==3.12.0
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
requests==2.2.1
six==1.5.2
ssh-import-id==3.21
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
zenmap==6.40
zope.interface==4.0.5

**Comment by mhils** [comment]
You need to update your pip version so that pip sends a TLS Server Name Indication.

Our server is fine: https://www.ssllabs.com/ssltest/analyze.html?d=snapshots.mitmproxy.org
