### ISSUE TITLE
flowbasic example is broken

### ISSUE THREAD

**Issue by ja8zyjits** [mitmproxy/mitmproxy#1770]
##### Steps to reproduce the problem:

1. Copy the following script

```python
from mitmproxy import controller, proxy
from mitmproxy.proxy.server import ProxyServer
from mitmproxy.options import Options


class MitmProxyServer(controller.Master):

     def __init__(self, server_proxy):
         self.server = None
         self.server_proxy = server_proxy
         self.create_server()
         controller.Master.__init__(self, self.server)


     def create_server(self):
         host, port = self.server_proxy.split(':')
         config = proxy.ProxyConfig(Options(listen_port=int(port), cadir="~/.mitmproxy/"))
         self.server = ProxyServer(config)

     def run(self):
         try:
             controller.Master.run(self)
         except KeyboardInterrupt:
            self.shutdown()

     def handle_request(self, f):
         print "In handle_request"
         f.reply()

     def handle_response(self, f):
         f.reply()

if __name__ == "__main__":
    m = MitmProxyServer('127.0.0.1:8081')
    m.run()
```

2. Run the above script
3. Fails with the following traceback

```python
jitesh@jitesh-laptop:~/projects$ python mit_testing.py 
Traceback (most recent call last):
  File "mit_testing.py", line 38, in <module>
    m = MitmProxyServer('127.0.0.1:8081')
  File "mit_testing.py", line 12, in __init__
    controller.Master.__init__(self, self.server)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/controller.py", line 92, in __init__
    self.addons = addons.Addons(self)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/addons.py", line 14, in __init__
    master.options.changed.connect(self._options_update)
AttributeError: 'ProxyServer' object has no attribute 'changed'
```

##### Any other comments? What have you tried so far?

* I tried to go through the code but the code i have seems to be different from what i can see in the repo
* I cant see anything related to `addons.py` in the current repository
* Can we run `mitmproxy` server in this way?

##### System information

```
jitesh@jitesh-laptop:~/projects$ mitmdump --sysinfo
Mitmproxy version: 0.18.2
Python version: 2.7.12
Platform: Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
```

**Comment by Kriechi** [comment]
You probably are looking at our current master - which has evolved quite a bit from the last release. Please take a look at the correct branch / tag: https://github.com/mitmproxy/mitmproxy/tree/v0.18.2

**Comment by mhils** [comment]
The example in question is broken on master. I'd be fine with throwing it out of the window altogether, but I'll ultimately leave that up to @cortesi.

**Comment by mhils** [comment]
The example on master works again. My previous point still stands, but we can close this for now.
