### ISSUE TITLE
mitmweb error :  AttributeError: 'WebMaster' object has no attribute 'start_stream_to_path'

### ISSUE THREAD

**Issue by Miller1990** [mitmproxy/mitmproxy#1786]
I'm trying to save the flow intercepted by the mitmproxy on the file using this:

mitmweb --wfile out.txt

when I run it returns me the following error: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mitmweb", line 11, in <module>
    sys.exit(mitmweb())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy/main.py", line 139, in mitmweb
    m = web.master.WebMaster(server, web_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy/web/master.py", line 156, in __init__
    err = self.start_stream_to_path(
AttributeError: 'WebMaster' object has no attribute 'start_stream_to_path'

**Comment by mhils** [comment]
Thanks. This is fixed on master already!
