### ISSUE TITLE
Proxy exceptions

### ISSUE THREAD

**Issue by ja8zyjits** [mitmproxy/mitmproxy#1802]
##### Steps to reproduce the problem:

1. copy the script
```python
def proxy_address(flow):
    return ("remote_ip", 18002)

def request(flow):
    address = proxy_address(flow)
    if flow.live:
        print("inside")
        flow.live.change_upstream_proxy_server(address)
def response(flow):
    pdb.set_trace()
    content = flow.response.headers.get("Content-Type", [])
    if [cont for cont in ('html', 'json') if cont in content]:
        pass
    elif  content:
        pass
```
2. run `mitmdump -s "update_mitmproxy.py"`
3. copy this script and run
```python
from selenium import webdriver

def get_proxy():
    from selenium.webdriver.common.proxy import Proxy, ProxyType
    get_proxy = "127.0.0.1:8080" 
    proxy = Proxy({
        'proxyType': ProxyType.MANUAL,
        'httpProxy': get_proxy,
        'sslProxy': get_proxy,
        'ftpProxy': get_proxy,
        'socksProxy':get_proxy,
    })
    return proxy

if __name__ == '__main__':
    response = webdriver.Firefox(proxy=get_proxy())
    url = "http://www.google.com"
    response.get(url)
```
4. the error that i get is
```python
(proxy_ui3) jitesh@jitesh-laptop:~/projects/proxy_ui3$ mitmdump -U "http://localho:8085" -s update_mitmproxy.py 
Loading script: update_mitmproxy.py
Proxy server listening at http://0.0.0.0:8080
127.0.0.1:45158: clientconnect
127.0.0.1:45160: clientconnect
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45160: GET http://www.google.com/
              << 302 Found 231b
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45158: CONNECT tiles-cloudfront.cdn.mozilla.net:443
              << 403 Forbidden 3k
127.0.0.1:45160: clientdisconnect
127.0.0.1:45162: clientconnect
127.0.0.1:45158: clientdisconnect
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45162: CONNECT www.google.com:443
              << 200 Connection established 0b
Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
127.0.0.1:45162: GET https://www.google.com/?gws_rd=ssl HTTP/2.0
              << 200  62k
Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

127.0.0.1:45166: clientconnect
Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

127.0.0.1:45168: clientconnect
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
127.0.0.1:45162: GET https://www.google.com/images/hpp/ic_wahlberg_product_core_48.png8.png HTTP/2.0
              << 200  2k
127.0.0.1:45170: clientconnect
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
127.0.0.1:45162: GET https://www.google.com/images/branding/product/ico/googleg_lodp.ico HTTP/2.0
              << 200  1k
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
127.0.0.1:45162: GET https://www.google.com/images/nav_logo242.png HTTP/2.0
              << 200  21k
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45166: CONNECT ssl.gstatic.com:443
              << 200 Connection established 0b
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
: GET https://www.google.com/xjs/_/js/k=xjs.s.en.uSOoTHNi41A.O/m=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,j,p,d,csi/am=AAiUdFzBAoj_h4C4hXAEqQADgw/rt=j/d=1/t=zcms/rs=ACT90oFM1AuVetyo5hzaw7QTff7TnRJZoQ HTTP/2.0
              << 200  135k
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
: GET https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png HTTP/2.0
              << 200  13k
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45168: CONNECT www.gstatic.com:443
              << 200 Connection established 0b
127.0.0.1:45162: clientdisconnect
127.0.0.1:45166: Error in HTTP connection: TlsProtocolException('Cannot establish TLS with ssl.gstatic.com:443 (sni: ssl.gstatic.com): TlsException("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',)
127.0.0.1:45166: clientdisconnect
127.0.0.1:45168: Error in HTTP connection: TlsProtocolException('Cannot establish TLS with www.gstatic.com:443 (sni: www.gstatic.com): TlsException("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',)
127.0.0.1:45168: clientdisconnect
127.0.0.1:45172: clientconnect
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45170: CONNECT aus4.mozilla.org:443
              << 403 Forbidden 3k
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45172: CONNECT www.gstatic.com:443
              << 200 Connection established 0b
127.0.0.1:45170: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe',)
127.0.0.1:45170: clientdisconnect
Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.gstatic.com:443
(Pdb) c
127.0.0.1:45172: GET https://www.gstatic.com/og/_/js/k=og.og2.en_US.TQruUcVmySQ.O/rt=j/m=def/exm=in,fot/d=1/ed=1/rs=AA2YrTvgRViuC9GGCertnoy9cEgjABZj6Q HTTP/2.0
              << 200  46k
127.0.0.1:45174: clientconnect
127.0.0.1:45176: clientconnect
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45176: CONNECT www.google.com:443
              << 200 Connection established 0b
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
remote_ip:18003
(Pdb) c
127.0.0.1:45174: CONNECT apis.google.com:443
              << 200 Connection established 0b
Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

Script error: Traceback (most recent call last):
  File "update_mitmproxy.py", line 58, in request
    flow.live.change_upstream_proxy_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http.py", line 276, in change_upstream_proxy_server
    return self.set_server(address)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 413, in set_server
    raise exceptions.SetServerNotAllowedException(repr(address))
SetServerNotAllowedException: ('remote_ip', 18003)

> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
www.google.com:443
(Pdb) c
127.0.0.1:45176: POST https://www.google.com/_/og/promos/z HTTP/2.0
              << 200  22b
> /home/jitesh/projects/proxy_ui3/update_mitmproxy.py(67)response()
-> content = flow.response.headers.get("Content-Type", [])
(Pdb) flow.server_conn.address
apis.google.com:443
(Pdb) c
127.0.0.1:45174: GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.U_ZjamIixkk.O/m=gapi_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-vbowTsdJgxjMinuRjWcqUL15H1g/cb=gapi.loaded_0 HTTP/2.0
              << 200  41k
127.0.0.1:45172: clientdisconnect
127.0.0.1:45174: clientdisconnect
127.0.0.1:45176: clientdisconnect

```
##### Any other comments? What have you tried so far?
1. when an exception is raised it re routes through local ip.
2. If that proxy fails, shouldn't it return error rather than routing through the local ip?
3. I tested that Ip with normal browser, there seems to be no such error, also with `python requests` passing proxy ips.
4. I could not find much info `SetServerNotAllowedException`
5. Any help would be greatly appreciated.

##### System information

```bash
(proxy_ui3) jitesh@jitesh-laptop:~/projects/proxy_ui3$ mitmdump --sysinfo
Mitmproxy version: 0.18.2
Python version: 2.7.12
Platform: Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
```

**Comment by Kriechi** [comment]
You are trying to connect to sites that support HTTP/2. Once such a connection is established, changing the server (host) is not possible, since HTTP/2 is a binary state-full protocol.

If you want to change the server dynamically, you have to disable HTTP/2 or filter out the sites.

**Comment by ja8zyjits** [comment]
@Kriechi I followed your advice i added `--no-http2` now i dont have error but even without those errors the outcome is same i.e it will reroute through the local system instead of the upstream proxy server at the same place where it used to show error previously.

**Comment by ja8zyjits** [comment]
Is there is any solution for this issue?? Not so familiar with mitmproxy.


Any help would be greatly appreciated.
Thanks

**Comment by ja8zyjits** [comment]
@Kriechi I take back my statement, it seems to be working, i tried url `http://www.httpbin.org/ip` and it showed my upstream proxy server ip though the `flow.server_conn.address` showed the direct `httpbin.org` server, i would like to close this but some knowledge on that topic would be really helpful.

1]  why does it show  `www.google.com:443` as a server though it is connecting through proxy ip, does it has anything to do with the `ssh tunnel`?
