### ISSUE TITLE
Error parsing TLSv1.2 ClientHello with no extensions

### ISSUE THREAD

**Issue by yifanlu** [mitmproxy/mitmproxy#1816]
```
⇩ [0/0]    [showhost]                                                                                                                                                                        ?:help [*:8001]
Traceback (most recent call last):
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 460, in _parse
⇩ [0/0]    [showhost]                                                                                                                                                                        ?:help [*:8001]
Error: 192.168.2.28:54194: Traceback (most recent call last):
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 460, in _parse
    return packer.unpack(self.fmtstr, _read_stream(stream, self.sizeof()))[0]
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 73, in _read_stream
    raise FieldError("could not read enough bytes, expected %d, found %d" % (length, len(data)))
construct.core.FieldError: could not read enough bytes, expected 2, found 0
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
    return self.subcon._parse(stream, context, path)
Traceback (most recent call last):
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 2696, in _parse
    return self.subcon._parse(stream, context, path)
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 859, in _parse
    subobj = sc._parse(stream, context, path)
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 462, in _parse
    raise FieldError("packer %r error during parsing" % self.fmtstr)
construct.core.FieldError: packer '>H' error during parsing
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
    return cls(raw_client_hello)
Traceback (most recent call last):
  File "/Users/yifanlu/Downloads/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 293, in from_client_conn
    return cls(raw_client_hello)
  File "/Users/yifanlu/Downloads/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 251, in __init__
    self._client_hello = _constructs.ClientHello.parse(raw_client_hello)
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 175, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 186, in parse_stream
    return self._parse(stream, context, "parsing")
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 2696, in _parse
    return self.subcon._parse(stream, context, path)
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 859, in _parse
    subobj = sc._parse(stream, context, path)
  File "/Users/yifanlu/Downloads/mitmproxy/venv3.5/lib/python3.5/site-packages/construct/core.py", line 2700, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.FieldError: packer '>H' error during parsing
    parsing -> ClientHello -> extensions
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
    root_layer()
Traceback (most recent call last):
  File "/Users/yifanlu/Downloads/mitmproxy/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/Users/yifanlu/Downloads/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/Users/yifanlu/Downloads/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 338, in __call__
    self._client_hello = TlsClientHello.from_client_conn(self.client_conn)
  File "/Users/yifanlu/Downloads/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 297, in from_client_conn
    (repr(e), raw_client_hello.encode("hex"))
AttributeError: 'bytes' object has no attribute 'encode'
```

Here is my ClientHello packet

```
Secure Sockets Layer
    SSL Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.1 (0x0302)
        Length: 55
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 51
            Version: TLS 1.1 (0x0302)
            Random
                GMT Unix Time: Dec  4, 2016 22:44:19.000000000 PST
                Random Bytes: 17991bbc1b718f75650857ad440fa366eae285337fa07c76...
            Session ID Length: 0
            Cipher Suites Length: 12
            Cipher Suites (6 suites)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
                Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
                Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)
                Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)

0000   16 03 02 00 37 01 00 00 33 03 02 58 45 0c c3 17  ....7...3..XE...
0010   99 1b bc 1b 71 8f 75 65 08 57 ad 44 0f a3 66 ea  ....q.ue.W.D..f.
0020   e2 85 33 7f a0 7c 76 ce b5 79 99 00 00 0c 00 35  ..3..|v..y.....5
0030   00 2f 00 0a 00 05 00 04 00 ff 01 00              ./..........
```

Seems like in `_constructs.py`, `ClientHello` and `ServerHello` assumes the existence of extensions whereas the RFC allows for no extensions

```
      struct {
          ProtocolVersion client_version;
          Random random;
          SessionID session_id;
          CipherSuite cipher_suites<2..2^16-2>;
          CompressionMethod compression_methods<1..2^8-1>;
          select (extensions_present) {
              case false:
                  struct {};
              case true:
                  Extension extensions<0..2^16-1>;
          };
      } ClientHello;
```

**Comment by Kriechi** [comment]
@yifanlu does PR #1817 fix the bug for you?

**Comment by yifanlu** [comment]
Thanks, will check when I get home.
