### ISSUE TITLE
when run  the mitmproxy on macos AttributeError: 'module' object has no attribute 'IntEnum'

### ISSUE THREAD

**Issue by niasand** [mitmproxy/mitmproxy#1820]
##### Steps to reproduce the problem:

1. input the  command mitmproxy on the iterm2 
2. and then, enter
3.

##### Any other comments? What have you tried so far?
it seems that enum34 on python2.7.12 has no attribute IntEnum

##### System information
1. masoc sierra
2. pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
3. reinstall the mitmproxy, the problem is still exists.

Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.main import mitmproxy
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/main.py", line 11, in <module>
    from mitmproxy.proxy import config
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/proxy/__init__.py", line 4, in <module>
    from .root_context import RootContext
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/proxy/root_context.py", line 10, in <module>
    from mitmproxy import protocol
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/protocol/__init__.py", line 34, in <module>
    from .http import UpstreamConnectLayer
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/protocol/http.py", line 3, in <module>
    import h2.exceptions
  File "/usr/local/lib/python2.7/site-packages/h2/exceptions.py", line 8, in <module>
    import h2.errors
  File "/usr/local/lib/python2.7/site-packages/h2/errors.py", line 14, in <module>
    class ErrorCodes(enum.IntEnum):
AttributeError: 'module' object has no attribute 'IntEnum'

**Comment by Kriechi** [comment]
This seems to be related to one of our dependencies: hyper-h2.
ping @Lukasa

**Comment by Lukasa** [comment]
This almost always happens when there is a *different* module on the `sys.path` called `enum`.

Can you print the output from `python -c "import enum; print enum.__file__"`?

**Comment by niasand** [comment]
```shell
jerry:mycode/ (master) $  python -c "import enum; print enum.__file__"                            [23:19:55]
/usr/local/lib/python2.7/site-packages/enum/__init__.pyc
jerry:mycode/ (master) $
```
Thanks to Kirechi and Lukasa you two . I don't know how this issue happened ,and then I deleted all the files that releated to mitmproxy under the  site-packages folder , and reinstall the mitmproxy via pip ,and it works now.
