### ISSUE TITLE
Intercepting tcp connections with TLS 1.2 and custom certificates

### ISSUE THREAD

**Issue by bottee** [mitmproxy/mitmproxy#1855]
When trying to intercept non HTTPS tcp connections with TLS 1.2 in a local network without DNS name, mitmproxy still creates and sends it's own certificate and following error happens:

----------------------------------------
Error in processing of request from xxx.xxx.xxx.xxx:49811
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mitmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/lib/python3.4/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/usr/lib/python3.4/site-packages/mitmproxy/protocol/tls.py", line 384, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/lib/python3.4/site-packages/mitmproxy/protocol/tls.py", line 470, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/mitmproxy/protocol/tls.py", line 461, in _establish_tls_with_client_and_server
    self.ctx.connect()
  File "/usr/lib/python3.4/site-packages/mitmproxy/protocol/base.py", line 181, in connect
    raise exceptions.ProtocolException("Cannot connect to server, no server address given.")
mitmproxy.exceptions.ProtocolException: Cannot connect to server, no server address given.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/netlib/tcp.py", line 918, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/lib/python3.4/site-packages/mitmproxy/proxy/server.py", line 66, in handle_client_connection
    h.handle()
  File "/usr/lib/python3.4/site-packages/mitmproxy/proxy/server.py", line 144, in handle
    self.client_conn.send(http1.assemble_response(error_response))
  File "/usr/lib/python3.4/site-packages/netlib/http/http1/assemble.py", line 24, in assemble_response
    head = assemble_response_head(response)
  File "/usr/lib/python3.4/site-packages/netlib/http/http1/assemble.py", line 30, in assemble_response_head
    first_line = _assemble_response_line(response.data)
  File "/usr/lib/python3.4/site-packages/netlib/http/http1/assemble.py", line 97, in _assemble_response_line
    response_data.reason,
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

----------------------------------------

##### Steps to reproduce the problem:

1.
creating self signed server cert.pem and client certificate client-cert.pem
2.
client and server are running in local network without dns. 
3.
mitmproxy --tcp xxx.xxx.xxx.xxx:yyyy --cert *=./cert.pem --client-cert ./client-cert.pem

##### Any other comments? What have you tried so far?
 I also tried with -cadir ./ and a corresponding ca.pem but this should not be needed and it is in our real situation not available, also. Still I get the same error.

##### System information

Mitmproxy version: 0.18.2
Python version: 3.4.5
Platform: Linux-4.4.36-8-default-x86_64-with-SuSE-42.2-x86_64
SSL version: OpenSSL 1.0.2j-fips  26 Sep 2016
Linux distro: openSUSE  42.2 x86_64

**Comment by Kriechi** [comment]
Not sure if this is related or not, but mitmproxy does not support Python 3.4.
Could you please try to run it with a support Python version? mitmprxy 0.18.2 support 2.7 and 3.5.

**Comment by bottee** [comment]
Thank you for your fast response! 

I get the same behaviour (mitmproxy certificate during handshake) but without exception here:

Mitmproxy version: 0.18.2
Python version: 2.7.9
Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
SSL version: OpenSSL 1.0.1t  3 May 2016
Linux distro: debian 8.6 

Mitmproxy gives following waring: Client Handshake failed. The client may not trust the proxy's certificate for None.

**Comment by bottee** [comment]
I just repeated my usecase with the current mitmproxy version 1.0.2. I get a warning: 

warn xxx.xxx.xxx.xxx:yyyy: Cannot connect to server, no server address given.

Any ideas?

Mitmproxy version: 1.0.2
Python version: 3.5.2
Platform: Linux-4.4.36-8-default-x86_64-with-SuSE-42.2-x86_64
SSL version: OpenSSL 1.1.0c  10 Nov 2016
Linux distro: openSUSE  42.2 x86_64

**Comment by mhils** [comment]
Closing this as it is unrelated to the original report (https://discourse.mitmproxy.org/t/intercepting-tcp-connections-with-tls-1-2-and-custom-certificates/307/3)
