### ISSUE TITLE
Traceback by running smoke tests

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#1869]
```
127.0.0.1:38112: Traceback (most recent call last):
  File "/home/ubuntu/mitmproxy/mitmproxy/net/tcp.py", line 763, in connect
    connection.connect(self.address())
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/base.py", line 180, in connect
    self.server_conn.connect()
  File "/home/ubuntu/mitmproxy/mitmproxy/connections.py", line 206, in connect
    tcp.TCPClient.connect(self)
  File "/home/ubuntu/mitmproxy/mitmproxy/net/tcp.py", line 768, in connect
    (self.address.host, err)
mitmproxy.exceptions.TcpException: Error connecting to "godaddy.com": [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/http.py", line 195, in handle_regular_connect
    layer()
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 376, in __call__
    self._establish_tls_with_client_and_server()
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 451, in _establish_tls_with_client_and_server
    self.ctx.connect()
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 397, in connect
    self.ctx.connect()
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/base.py", line 184, in connect
    repr(self.server_conn.address), str(e)
mitmproxy.exceptions.ProtocolException: Server connection to godaddy.com:443 failed: Error connecting to "godaddy.com": [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/mitmproxy/mitmproxy/net/tcp.py", line 190, in write
    r = self.o.write(v)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/http.py", line 432, in send_error_response
    self.send_response(response)
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/http.py", line 43, in send_response
    self.send_response_headers(response)
  File "/home/ubuntu/mitmproxy/mitmproxy/proxy/protocol/http1.py", line 43, in send_response_headers
    self.client_conn.wfile.write(raw)
  File "/home/ubuntu/mitmproxy/mitmproxy/net/tcp.py", line 194, in write
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: [Errno 32] Broken pipe
127.0.0.1:38112: clientdisconnect
```

maybe related to #1867

**Comment by mhils** [comment]
`send_error_response` - this is a duplicate.
