### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'host'

### ISSUE THREAD

**Issue by yowenter** [mitmproxy/mitmproxy#1883]
##### Steps to reproduce the problem:
Hi, there,

1.  I start mitmproxy use `./mitmproxy  --port=8081` 
2.  I add the `/$HOME/.mitmproxy/mitmproxy-ca-cert.cer` to the login keychain
3. When I opened 'https://google.com' use chrome  proxed  by switch omega .It raise an error.

 

> Traceback (most recent call last):
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/proxy/server.py", line 120, in handle
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/protocol/tls.py", line 267, in __call__
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
  File "/Users/travis/build/mitmproxy/mitmproxy/libmproxy/protocol/tls.py", line 497, in _find_cert
AttributeError: 'NoneType' object has no attribute 'host'
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

##### Any other comments? What have you tried so far?

But it works well on my iPhone .I installed the cert on my phone, and then I set the network proxy .
I can visit https websites.

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by yowenter** [comment]
Thks, I use brew installed ` mitmproxy 1.0.1`, when I execute `mitmproxy` command , It always raise error like 

`can't connect server, no server address given ` .

**Comment by mhils** [comment]
I'd need a more detailed error description to do anything useful.

**Comment by yowenter** [comment]
> mitmproxy-1.0.2-osx ./mitmproxy --version
mitmproxy 1.0.2

> mitmproxy-1.0.2-osx uname -a
Darwin wenter-mbp 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

When I start the mitmproxy, I use chrome proxy to visit 'https://www.baidu.com', The chrome shows 

`ERR_PROXY_CERTIFICATE_INVALID`   ,the mitmproxy shows error like `can't connect server, no server address given` .
The mitmproxy does not exit,  no other information displayed  though I used verbose .

**Comment by mhils** [comment]
How did you configure your client? `ERR_PROXY_CERTIFICATE_INVALID` sounds like you configured mitmproxy as a HTTPS proxy. Mitmproxy is a HTTP proxy.
