### ISSUE TITLE
AttributeError: '_Union' object has no attribute '__qualname__'

### ISSUE THREAD

**Issue by dserodio** [mitmproxy/mitmproxy#1886]
##### Steps to reproduce the problem:

1. `pip3 install mitmproxy`
2. `mitmproxy`
3. Crash (see below)

##### Any other comments? What have you tried so far?

    $ mitmdump
    Traceback (most recent call last):
      File "/usr/local/bin/mitmdump", line 11, in <module>
        sys.exit(mitmdump())
      File "/usr/local/lib/python3.6/site-packages/mitmproxy/tools/main.py", line 106, in mitmdump
        dump_options = options.Options()
      File "/usr/local/lib/python3.6/site-packages/mitmproxy/options.py", line 123, in __init__
        self.rfile = rfile
      File "/usr/local/lib/python3.6/site-packages/mitmproxy/optmanager.py", line 111, in __setattr__
        self._typecheck(attr, value)
      File "/usr/local/lib/python3.6/site-packages/mitmproxy/optmanager.py", line 122, in _typecheck
        typecheck.check_type(attr, value, expected_type)
      File "/usr/local/lib/python3.6/site-packages/mitmproxy/utils/typecheck.py", line 24, in check_type
        if typeinfo.__qualname__ == "Union":
    AttributeError: '_Union' object has no attribute '__qualname__'

##### System information

mitmproxy 1.0.0
Python 3.6.0
OS X 10.11.6

(`mitmproxy --sysinfo` gives the same traceback above)

**Comment by mhils** [comment]
3.6 already - nice! 😄 

Thanks for the report! We are hitting the same on our CI servers, in #1884, that should be fixed soon. ☺️

**Comment by kavu** [comment]
Yeah, I got it too — with `brew` installation and with usual `pip3`.

**Comment by Kriechi** [comment]
We have a rough fix in #1884 - will be merged soon!

**Comment by mhils** [comment]
In the meantime, please feel free to take our binaries from https://github.com/mitmproxy/mitmproxy/releases/tag/v1.0. We hope to have this fixed ASAP, but we're getting weird CI errors and need to investigate.

**Comment by mhils** [comment]
We just pushed 1.0.1 which fixes compatibility with Python 3.6. Thanks again for reporting this! :smiley:
