### ISSUE TITLE
type object 'Sequence' has no attribute '__args__' using python3.5.0

### ISSUE THREAD

**Issue by wbwkx** [mitmproxy/mitmproxy#1894]
##### Steps to reproduce the problem:

1.pyenv global 3.5.0
2.pip3.5 install mitmproxy
3.mitmproxy -b 10.19.84.140 -p 9999  --no-upstream-cert

##### Any other comments? What have you tried so far?
trying to install from brew, and problem still by raising the py3.6.0 problem.
0.15  runs perfectly under python2.7.10

##### System information

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.0/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 67, in mitmproxy
    console_options = options.Options()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy/options.py", line 117, in __init__
    self.client_replay = client_replay
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy/optmanager.py", line 111, in __setattr__
    self._typecheck(attr, value)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy/optmanager.py", line 122, in _typecheck
    typecheck.check_type(attr, value, expected_type)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy/utils/typecheck.py", line 55, in check_type
    T = typeinfo.__args__[0]
AttributeError: type object 'Sequence' has no attribute '__args__'

**Comment by CapitanShinChan** [comment]
I have a similar error, trying to use it on Kali Linux (Debian based distro).

Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/main.py", line 67, in mitmproxy
    console_options = options.Options()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/options.py", line 123, in __init__
    self.rfile = rfile
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/optmanager.py", line 111, in __setattr__
    self._typecheck(attr, value)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/optmanager.py", line 122, in _typecheck
    typecheck.check_type(attr, value, expected_type)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/utils/typecheck.py", line 29, in check_type
    types = typeinfo.__union_params__
AttributeError: '_Union' object has no attribute '__union_params__'

**Comment by mhils** [comment]
What's your output of `python --version`?

**Comment by wbwkx** [comment]
mine:
```
~ » python --version
Python 3.5.0
```

**Comment by mhils** [comment]
Thanks. Looks like 3.5.2 works, but 3.5.0 doesn't.

@CapitanShinChan: What's your output of `pip freeze`?

**Comment by mhils** [comment]
#1896 has a fix. If CI goes through, I'll ship a patch release right away.

**Comment by CapitanShinChan** [comment]
Mine:

`python --version
Python 2.7.12+`

`python3 --version
Python 3.5.2+`

My error was using `python3 /usr/local/bin/mitmproxy`

Responses from `pip --freeze` and `pip3 --freeze` are in the attachments


[pip_freeze.txt](https://github.com/mitmproxy/mitmproxy/files/675574/pip_freeze.txt)
[pip3_freeze.txt](https://github.com/mitmproxy/mitmproxy/files/675573/pip3_freeze.txt)
