### ISSUE TITLE
crashed using invalid script path

### ISSUE THREAD

**Issue by wbwkx** [mitmproxy/mitmproxy#1909]
##### Steps to reproduce the problem:

1.start proxy from cli
2.using "|" command to load a script and set an invalid path to it. like "~/Desktop/"
3.hit Enter it will crash

##### System information

```
demo » mitmproxy --version
mitmproxy 2.0.0
```

```
demo » mitmproxy --sysinfo
Mitmproxy version: 2.0.0
Python version: 3.5.0
Platform: Darwin-16.3.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.2 ('', '', '') x86_64
```

##### Crash-Log trace

```
   Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/master.py", line 292, in run
    self.loop.run()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/statusbar.py", line 155, in keypress
    return self.master.ab.keypress(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/statusbar.py", line 110, in keypress
    self.prompt_execute(self._w.get_edit_text())
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/statusbar.py", line 133, in prompt_execute
    msg = p(txt)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/statusbar.py", line 21, in __call__
    return self.callback(pth, *self.args)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/tools/console/master.py", line 150, in run_script_once
    sc.run_once(command, [f])
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/addons/script.py", line 208, in run_once
    sc = Script(command)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/addons/script.py", line 136, in __init__
    self.path, self.args = parse_command(command)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/site-packages/mitmproxy-2.0.0-py3.5.egg/mitmproxy/addons/script.py", line 37, in parse_command
    raise exceptions.OptionsError("Not a file: %s" % args[0])
mitmproxy.exceptions.OptionsError: Not a file: /Users/wuten/Desktop

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

**Comment by lymanZerga11** [comment]
@mhils I think the problem is in the `run_once` function in `/mitmproxy/mitmproxy/addons/script.py`. The `Script` class constructor does not handle error in the call to the `parse_command` function.

A possible solution could be to add an except clause in `run_once` and use the error message to warn the user in the `run_script_once` function in `/mitmproxy/mitmproxy/tools/console/master.py`
```
        try:
            sc = Script(command)
        except exceptions.OptionsError as e:
            return str(e)
```
```
        emsg = sc.run_once(command, [f])
        if isinstance(emsg, str):
            signals.add_log("Script error: %s" % emsg, "warn")
```
This seems to fix the current issue. Let me know if there's anything wrong

**Comment by ddworken** [comment]
@lymanZerga11 I think instead of returning a string from there, it might make more sense use ```ctx.log.error``` to log the error immediately and return a script that does nothing. This way you only have to modify one file (the ```/mitmproxy/mitmproxy/addons/script.py```) and don't have to complicate ```/mitmproxy/mitmproxy/tools/console/master.py``` with additional code.

**Comment by lymanZerga11** [comment]
@ddworken oh okay haha. Then this should be enough right? 
```
        try:
            sc = Script(command)
        except exceptions.OptionsError as e:
            ctx.log.error("Script error: %s" % e)
            return None
```

**Comment by ddworken** [comment]
Yeah in my opinion that looks much better. My one concern is that ```None``` is not an instance of a ```Script``` so I think that may cause an error when it returns None. Have you checked that it works? If it doesn't work, then I think you would instead have to return an "empty" Script object.

**Comment by lymanZerga11** [comment]
Yes it works. But maybe it is because the returned Script object is never used in the `run_script_once` function. I guess returning an empty Script object would be safer.
