### ISSUE TITLE
ImportError: cannot import name 'contentviews'

### ISSUE THREAD

**Issue by blshkv** [mitmproxy/mitmproxy#1912]
The latest release and the HEAD copy are affected:
```
mitmproxy
#################################################
# mitmproxy only supports Python 3.5 and above! #
#################################################
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==1.0.2', 'console_scripts', 'mitmproxy')()
  File "/usr/lib64/python3.4/site-packages/mitmproxy/tools/main.py", line 58, in mitmproxy
    from mitmproxy.tools import console
  File "/usr/lib64/python3.4/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/usr/lib64/python3.4/site-packages/mitmproxy/tools/console/master.py", line 25, in <module>
    from mitmproxy.tools.console import flowview
  File "/usr/lib64/python3.4/site-packages/mitmproxy/tools/console/flowview.py", line 9, in <module>
    from mitmproxy import contentviews
  File "/usr/lib64/python3.4/site-packages/mitmproxy/contentviews/__init__.py", line 24, in <module>
    from . import (
  File "/usr/lib64/python3.4/site-packages/mitmproxy/contentviews/auto.py", line 1, in <module>
    from mitmproxy import contentviews
ImportError: cannot import name 'contentviews'
```

I dont think it is a python3.4 problem.

The commit in questions is below:
https://github.com/mitmproxy/mitmproxy/commit/a7ba2f7b46b98d8d688706adf5b1d9495218a91d
mitmproxy/contentviews/auto.py
+from mitmproxy import contentviews

I don't think it makes sense to import its own module.

**Comment by blshkv** [comment]
Unfortunately, python 3.5 is not stable yet on my Linux of choice. I will try to upgrade and report back.
However, it would be sad to see that you don't "support" 3.4 because of one line (which is obviously *wrong*).

**Comment by blshkv** [comment]
ok, that sounds promising. Thank you.

I have highlighted it above already. Please have a look at the following:
mitmproxy/contentviews/auto.py:
```
from mitmproxy import contentviews
``

I'm not python guru, but I don't think "contentviews" files need to import itself. Am I wrong?

**Comment by mhils** [comment]
`contentviews.auto` needs some stuff from `contentviews/__init__.py`, hence the import. I agree this is not intuitive (and can be refactored to be a bit easier to grasp), but that's valid Python code.

**Comment by blshkv** [comment]
__init__ is something like a constructor in python.  So it looks unorthodox then you import from it.  It has been already called during inititialisation. 
And then,  you  have an another import of Auto class in it.  Looks like a recursive import to me...

**Comment by blshkv** [comment]
Ok, I tested with python 3.5 and not able to reproduce the problem.
Just out for curiosity, I found that 3.5 started to support circular imports, see https://docs.python.org/3/whatsnew/3.5.html . The rationale behind that is to resolve potential weird parent-child relationship ( https://bugs.python.org/issue17636 )

However, I still think it is better not to create this complication intentionally.

**Comment by mhils** [comment]
Yes - this certainly isn't a particularly nice code structure. :)
The whole add/get etc functions scream to be moved into a class. I'd be happy for a PR that moves things around in a more sensible way.

**Comment by blshkv** [comment]
Can I suggest to re-open the issue as it was not fixed there is some work need to be done.
