### ISSUE TITLE
Crash Report: OverflowError

### ISSUE THREAD

**Issue by ohhorob** [mitmproxy/mitmproxy#1961]
```
17.199.7.21:51633: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 176, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 245, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 194, in handle_regular_connect
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 176, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 373, in _process_flow
    self.send_response(f.response)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 43, in send_response
    self.send_response_body(response, [response.data.content])
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 48, in send_response_body
    self.client_conn.wfile.write(chunk)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 188, in write
    return self.o.sendall(v)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1285, in sendall
    result = _lib.SSL_write(self._ssl, data + total_sent, left_to_send)
OverflowError: integer 3114393428 does not fit '32-bit int'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

```

##### Steps to reproduce the problem:

1. start proxying iOS device streaming music
2. leave session running a while
3. observe crash report

##### System information

Mac OS X

$ mitmproxy --version
mitmproxy 1.0.2

**Comment by mhils** [comment]
So... just to verify, you have a HTTPS response with a content size of a little bit less than 3114393428 bytes? Or is your actual response size smaller and something else is off?

**Comment by ohhorob** [comment]
I'm not working too closely with the traffic that caused the error.
It's possible something on the iOS device is requesting something that size? (An OS update image or some such?)
I'll try and get more detail the next time it reproduces

**Comment by ohhorob** [comment]
OK, I stopped filtering requests, and found the culprit. It is indeed a 2.9G response for a software update. This is the (redacted) mitmdump log line immediately before the crash:

> 17.199.7.21:56535: clientconnect
> 17.199.7.21:56535: GET https://xxxx/_SoftwareUpdate/xxxx7864f.zip
>                 << 200 OK 2.9g

**Comment by mhils** [comment]
Thanks, this is super useful! :smile

**Comment by mhils** [comment]
This has been fixed in https://github.com/pyca/pyopenssl/pull/603! 😃
