### ISSUE TITLE
mitmproxy crashed when switch tab to Detail Tab with UnicodeDecodeError 0x94

### ISSUE THREAD

**Issue by itrmit** [mitmproxy/mitmproxy#2020]
##### Steps to reproduce the problem:

mitmproxy crash when switch tab to Detail Tab

when I proxying 12306 iOS app for any Request.

```
<!--
    mitmproxy 1.0.2 (Python 3.6.0)
   MAC: 10.11.6
-->
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 292, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 710, in _loop
    self._entering_idle()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 671, in _entering_idle
    callback()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 579, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/local/Cellar/mitmproxy/1.0.2_1/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 838, in draw_screen
    l = l.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

**Comment by mhils** [comment]
Thanks. Can you share a flow where this is happening, either here or in private?
