### ISSUE TITLE
refactor protobuf contentview

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#2021]
Currently the protobuf contentview relies on the `protoc` compiler to be available as shell command (in `$PATH`). 
https://github.com/mitmproxy/mitmproxy/blob/75a0a4c09276ef2aa479c9ae9feab97f7803ed6d/mitmproxy/contentviews/protobuf.py

However, it would be much cleaner to directly use the Python API provided by https://github.com/google/protobuf
https://developers.google.com/protocol-buffers/docs/pythontutorial

We already have that package as dependency, so why not use it?

**Comment by saganshul** [comment]
I will like to fix this issue. I will start working on it now.

**Comment by Kriechi** [comment]
It looks like the Python API from google-protobuf has a some severe limitations and is not capable of decoding serialized messages without the `.proto` file. From the official docs:
> The current Python implementation does not track unknown fields.

So the only output we really can get our hands on is the one from `protoc` CLI tool, and even this only gives us key-value pairs with raw field IDs.

I believe that this could also be done with a simple construct or kaitai decoder to parse the on-the-wire representation into their (nested) key-value tuples.
https://developers.google.com/protocol-buffers/docs/encoding

**Comment by Kriechi** [comment]
kaitai just got protobuf support! https://github.com/kaitai-io/kaitai_struct_formats/commit/d4f066eacb4132807bec3fc8ddf9f6e7e690ae34

**Comment by mhils** [comment]
Yes, implementing this with kaitaistruct is the way to go. 

@saganshul, did you start working on this? Otherwise this is free for pick up again.

**Comment by saganshul** [comment]
@mhils I started looking for support for raw decoding in google prototype python module. 
I got same thing as @Kriechi said.
I will take a look at kaitai_struct_format and try to resolve this issue.

**Comment by saganshul** [comment]
@mhils @Kriechi 
**Error on compiling google_protobuf.ksy using kaitai-struct-compiler**
Exception in thread "main" io.kaitai.struct.translators.TypeMismatchError: called invalid attribute 'size' on expression of type ArrayType(UserTypeInstream(List(group)))
	at io.kaitai.struct.translators.BaseTranslator.detectType(BaseTranslator.scala:337)
	at io.kaitai.struct.TypeProcessor$$anonfun$deriveValueType$1.apply(TypeProcessor.scala:63)
	at io.kaitai.struct.TypeProcessor$$anonfun$deriveValueType$1.apply(TypeProcessor.scala:56)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at io.kaitai.struct.TypeProcessor$.deriveValueType(TypeProcessor.scala:56)
	at io.kaitai.struct.TypeProcessor$$anonfun$deriveValueType$2.apply(TypeProcessor.scala:83)
	at io.kaitai.struct.TypeProcessor$$anonfun$deriveValueType$2.apply(TypeProcessor.scala:81)
	at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
	at io.kaitai.struct.TypeProcessor$.deriveValueType(TypeProcessor.scala:81)
	at io.kaitai.struct.TypeProcessor$.deriveValueTypes(TypeProcessor.scala:44)
	at io.kaitai.struct.TypeProcessor$.processTypes(TypeProcessor.scala:16)
	at io.kaitai.struct.formats.JavaKSYParser$.localFileToSpec(JavaKSYParser.scala:17)
	at io.kaitai.struct.Main$.compileOne(Main.scala:83)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:120)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:115)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.Main$.main(Main.scala:115)
	at io.kaitai.struct.Main.main(Main.scala)

Do you guys know how to fix this?

**Comment by s4chin** [comment]
I am working on this. As of now, we're waiting for KS 0.7 to be released as the `.ksy` file uses `size` which is unsupported for KS < 0.7. Upgrading to 0.7 will also involve recompiling the files used for image parsing in `mitmproxy/contrib/kaitaistruct`.

**Comment by Kriechi** [comment]
@s4chin any update on this?

**Comment by s4chin** [comment]
I asked the KS team about the release date. KS 0.7 was supposed to released this Monday, but was delayed. Now it's 50% done, shouldn't be too long.

**Comment by mhils** [comment]
Thanks! :)
