### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'

### ISSUE THREAD

**Issue by sxss0** [mitmproxy/mitmproxy#2070]
Similar to issue: https://github.com/mitmproxy/mitmproxy/issues/1476

##### Steps to reproduce the problem:

1. mitmdump -T --host -a android4
2. visit location

##### System information
```
Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.1
Platform: Linux-2.6.32-642.13.1.el6.x86_64-x86_64-with-centos-6.8-Final
SSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
Linux distro: CentOS 6.8 Final
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/proxy/protocol/tls.py", line 365, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

Cannot parse Client Hello: TlsProtocolException('Cannot read raw Client Hello: TlsProtocolException(\'Unexpected EOF in TLS handshake: b"\\\\x01\\\\x00\\\\x01\\\\xfc\\\\x03\\\\x03\\\\xac\\\\xf3\\\\xa4\\\\x86\\\\x07.$$\\\\xe0\\\\xb0#\\\\xc7~\\\\x7f%\\\\xf4\\\\xc0\\\\xce\\\\x1b\\\\xfc\\\\xd3s\\\\x82\\\\xdaKu/\\\\xe6\\\\xb6\\\\xc0\\\\xe3~\\\\x00\\\\x00v\\\\xc00\\\\xc0,\\\\xc0(\\\\xc0$\\\\xc0\\\\x14\\\\xc0\\\\n\\\\x00\\\\xa3\\\\x00\\\\x9f\\\\x00k\\\\x00j\\\\x009\\\\x008\\\\x00\\\\x88\\\\x00\\\\x87\\\\xc02\\\\xc0.\\\\xc0*\\\\xc0&\\\\xc0\\\\x0f\\\\xc0\\\\x05\\\\x00\\\\x9d\\\\x00=\\\\x005\\\\x00\\\\x84\\\\xc0/\\\\xc0+\\\\xc0\\\'\\\\xc0#\\\\xc0\\\\x13\\\\xc0\\\\t\\\\x00\\\\xa2\\\\x00\\\\x9e\\\\x00g\\\\x00@\\\\x003\\\\x002\\\\x00\\\\x9a\\\\x00\\\\x99\\\\x00E\\\\x00D\\\\xc01\\\\xc0-\\\\xc0)\\\\xc0%\\\\xc0\\\\x0e\\\\xc0\\\\x04\\\\x00\\\\x9c\\\\x00<\\\\x00/\\\\x00\\\\x96\\\\x00A\\\\xc0\\\\x12\\\\xc0\\\\x08\\\\x00\\\\x16\\\\x00\\\\x13\\\\xc0\\\\r\\\\xc0\\\\x03\\\\x00\\\\n\\\\x00\\\\xff\\\\x01\\\\x00\\\\x01]\\\\x00\\\\x00\\\\x00\\\\x10\\\\x00\\\\x0e\\\\x00\\\\x00\\\\x0blocalhost.android\\\\x00\\\\x0b\\\\x00\\\\x04\\\\x03\\\\x00\\\\x01\\\\x02\\\\x00\\\\n\\\\x004\\\\x002\\\\x00\\\\x0e\\\\x00\\\\r\\\\x00\\\\x19\\\\x00\\\\x0b\\\\x00\\\\x0c\\\\x00\\\\x18\\\\x00\\\\t\\\\x00\\\\n\\\\x00\\\\x16\\\\x00\\\\x17\\\\x00\\\\x08\\\\x00\\\\x06\\\\x00\\\\x07\\\\x00\\\\x14\\\\x00\\\\x15\\\\x00\\\\x04\\\\x00\\\\x05\\\\x00\\\\x12\\\\x00\\\\x13\\\\x00\\\\x01\\\\x00\\\\x02\\\\x00\\\\x03\\\\x00\\\\x0f\\\\x00\\\\x10\\\\x00\\\\x11\\\\x00\\\\r\\\\x00 \\\\x00\\\\x1e\\\\x06\\\\x01\\\\x06\\\\x02\\\\x06\\\\x03\\\\x05\\\\x01\\\\x05\\\\x02\\\\x05\\\\x03\\\\x04\\\\x01\\\\x04\\\\x02\\\\x04\\\\x03\\\\x03\\\\x01\\\\x03\\\\x02\\\\x03\\\\x03\\\\x02\\\\x01\\\\x02\\\\x02\\\\x02\\\\x03\\\\x00\\\\x0f\\\\x00\\\\x01\\\\x01\\\\x00\\\\x15\\\\x00\\\\xdc\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00"\',)',)

  File "/usr/local/lib/python3.5/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/proxy/protocol/tls.py", line 365, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'
```

Edit: Found some information it might be because of  *old* openssl version, ALPN support requires openssl 1.0.2. Will upgrade and retest.

**Comment by Kriechi** [comment]
This is a bit unusual. You should have seen a warning if your OpenSSL is too old.
Did you see a warning like `Cannot parse Client Hello: <...>`?

**Comment by Kriechi** [comment]
On second thought - this should have nothing to do with OpenSSL.
I think this is a bug in our TLS handshake parser...

Can you test without `--host -a android4`, so only `mitmproxy -T`?
Which site are you visiting? Can you give an URL or a specific server that produces this error?
