### ISSUE TITLE
crash when trying to duplicate a flow

### ISSUE THREAD

**Issue by majewsky** [mitmproxy/mitmproxy#2086]
##### Steps to reproduce the problem:

1. Start as usual (i.e. `mitmproxy -p $port`).
1. Record at least one flow.
2. Press <kbd>Shift</kbd><kbd>D</kbd> to duplicate a flow.

Crashes every time. Stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 987, in keypress
    self.make_cursor_visible((maxcol,maxrow))
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 939, in make_cursor_visible
    focus_widget, pos = self.body.get_focus()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 284, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 123, in __init__
    w = self.get_text()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 132, in get_text
    max_url_len=cols,
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/common.py", line 427, in format_flow
    acked = f.reply.state == "committed",
AttributeError: 'NoneType' object has no attribute 'state'
```

##### System information

Mitmproxy version: 2.0.0 (release version)
Python version: 3.6.0
Platform: Linux-4.9.11-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch

**Comment by krsoninikhil** [comment]
I'll fix this.

**Comment by krsoninikhil** [comment]
I think this should be closed as #2098 is merged.

**Comment by Hritik14** [comment]
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.1
Platform: Linux-4.11.6-3-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: arch  

Facing same issue!

**Comment by ritiek** [comment]
@Hritik14 You are using a pretty old version of mitmproxy. You should consider removing and installing the latest release by `pip3 install mitmproxy`

**Comment by Hritik14** [comment]
@ritiek Got it from arch repo. `community/mitmproxy  2.0.2-1        6.18 MiB`

**Comment by Hritik14** [comment]
@ritiek After installing from pip3 
 ```
   Mitmproxy version: 2.0.2 (release version)  
    Python version: 3.6.1
    Platform: Linux-4.11.6-3-ARCH-x86_64-with-arch
    SSL version: OpenSSL 1.1.0f  25 May 2017
    Linux distro: arch
```
Looks pretty much same

**Comment by ujjwal96** [comment]
It is fixed on master

**Comment by ritiek** [comment]
@Hritiek14 I am sorry, it seems like mitmproxy has not been updated on pip either. You should try installing  latest version directly from the master branch; `python3 setup.py install`. That should hopefully work.
