### ISSUE TITLE
Crash on adding a replacement pattern from editor

### ISSUE THREAD

**Issue by ujjwal96** [mitmproxy/mitmproxy#2127]
##### Steps to reproduce the problem:

1. Start mitmproxy 
2. Go to Replacement Editor and add a replacement 
3. Pressing `q` crashes mitmproxy
```
Traceback (most recent call last):
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/home/ujjwal/Github/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/tools/console/grideditor/base.py", line 343, in keypress
    self.callback(self.data_out(res), *self.cb_args, **self.cb_kwargs)
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/optmanager.py", line 198, in setter
    setattr(self, attr, x)
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/optmanager.py", line 163, in __setattr__
    self.update(**{attr: value})
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/optmanager.py", line 185, in update
    self._options[k].set(v)
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/optmanager.py", line 57, in set
    typecheck.check_type(self.name, value, self.typespec)
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/utils/typecheck.py", line 65, in check_type
    check_type(name, v, T)
  File "/home/ujjwal/Github/mitmproxy/mitmproxy/utils/typecheck.py", line 72, in check_type
    raise e
TypeError: Expected <class 'str'> for replacements, but got ('.*', 'foo', 'bar').

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### Any other comments? What have you tried so far?
Seems to be caused by the latest commit.

**Comment by ujjwal96** [comment]
It is probably happening because when we open Replacement editor replacements are converted to tuples like [(".*","foo","bar")] [here](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/options.py#L226)
Then pressing `q` invokes [`self.callback(self.data_out(res), *self.cb_args, **self.cb_kwargs)`](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/grideditor/base.py#L343)
and value of `res` remains a list of tuples.
According to new changes, replacements should be sequence of strings hence it raises the TypeError in typecheck

**Comment by mhils** [comment]
Yes. See @cortesi's last point in https://github.com/mitmproxy/mitmproxy/pull/2120#issuecomment-285222692 :)

**Comment by cortesi** [comment]
This is now fixed in master with the options editor rewrite. We now always use the string format to set replacement patterns. There are still a few things to work on there - progressive error checking, better keybindings for common options, etc. Basically "#helpwanted" but we don't fall on our faces anymore. :)
