### ISSUE TITLE
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by ccaceresahumada** [mitmproxy/mitmproxy#2130]
##### Steps to reproduce the problem:

1. Run `mitmdump -s my_script.py`
2. Start Appium
3. Launch Android app
4. Wait for traffic to occur
5. Check the output from mitmdump

##### Any other comments? What have you tried so far?

I'm using Appium to automate tests in an Android device. The goal is to launch the app and then verify the right events are being sent. 
**my_script.py** captures the traffic and stores it in a database which is later accessed through a service that verifies payloads are valid for each request.

When looking at the mitmdump output I can see the traffic flow, but at some point it crashes with the following information:

```
Traceback (most recent call last):
  File "/usr/local/projects/mitmproxy/mitmproxy/net/tcp.py", line 211, in read
    data = self.o.read(rlen)
  File "/usr/local/projects/mitmproxy/venv3.5/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1304, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/projects/mitmproxy/venv3.5/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http.py", line 177, in __call__
    if not self._process_flow(flow):
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http.py", line 246, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http.py", line 204, in handle_regular_connect
    layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http.py", line 177, in __call__
    if not self._process_flow(flow):
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http.py", line 228, in _process_flow
    request = self.read_request_headers(f)
  File "/usr/local/projects/mitmproxy/mitmproxy/proxy/protocol/http1.py", line 14, in read_request_headers
    http1.read_request_head(self.client_conn.rfile)
  File "/usr/local/projects/mitmproxy/mitmproxy/net/http/http1/read.py", line 52, in read_request_head
    form, method, scheme, host, port, path, http_version = _read_request_line(rfile)
  File "/usr/local/projects/mitmproxy/mitmproxy/net/http/http1/read.py", line 240, in _read_request_line
    line = _get_first_line(rfile)
  File "/usr/local/projects/mitmproxy/mitmproxy/net/http/http1/read.py", line 227, in _get_first_line
    line = rfile.readline()
  File "/usr/local/projects/mitmproxy/mitmproxy/net/tcp.py", line 251, in readline
    ch = self.read(1)
  File "/usr/local/projects/mitmproxy/mitmproxy/net/tcp.py", line 233, in read
    raise exceptions.TlsException(str(e))
mitmproxy.exceptions.TlsException: (104, 'ECONNRESET')

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

```

##### System information

Mitmproxy version: 2.0.0 (2.0.0dev0000-0x91c3a99) 
Python version: 3.5.2
Platform: Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g-fips  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment]
Thanks for the report. This really looks similar to #1843. @Kriechi, thoughts?

**Comment by Kriechi** [comment]
Should we also catch `TlsException` [here](http://github.com/Kriechi/mitmproxy/blob/e9746c51820aadcbb2ddbfa8fc963d9023dd6991/mitmproxy/proxy/protocol/http.py#L206)?

**Comment by sommis** [comment]
Any updates about this topic? I am experiencing the same problem when opening pages blocked by the internet provider. Would be better to modify the output or showing the original provider's web page.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
