### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2148]
##### Steps to reproduce the problem:

```
$ mitmdump -r foo.mitm
Traceback (most recent call last):
  File "C:/Users/user/git/mitmproxy/venv/Scripts/mitmdump-script.py", line 11, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmdump')()
  File "C:\Users\user\git\mitmproxy\mitmproxy\tools\main.py", line 112, in mitmdump
    run(dump.DumpMaster, args)
  File "C:\Users\user\git\mitmproxy\mitmproxy\tools\main.py", line 74, in run
    master = MasterKlass(opts, server)
  File "C:\Users\user\git\mitmproxy\mitmproxy\tools\dump.py", line 28, in __init__
    self.load_flows_file(options.rfile)
  File "C:\Users\user\git\mitmproxy\mitmproxy\master.py", line 186, in load_flows_file
    return self.load_flows(freader)
  File "C:\Users\user\git\mitmproxy\mitmproxy\master.py", line 170, in load_flows
    self.load_flow(i)
  File "C:\Users\user\git\mitmproxy\mitmproxy\master.py", line 161, in load_flow
    getattr(self, e)(o)
  File "C:\Users\user\git\mitmproxy\mitmproxy\controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "C:\Users\user\git\mitmproxy\mitmproxy\addonmanager.py", line 89, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "C:\Users\user\git\mitmproxy\mitmproxy\addonmanager.py", line 84, in invoke
    func(*args, **kwargs)
  File "C:\Users\user\git\mitmproxy\mitmproxy\addons\dumper.py", line 224, in response
    self.echo_flow(f)
  File "C:\Users\user\git\mitmproxy\mitmproxy\addons\dumper.py", line 196, in echo_flow
    self._echo_request_line(f)
  File "C:\Users\user\git\mitmproxy\mitmproxy\addons\dumper.py", line 129, in _echo_request_line
    if self.flow_detail < 1 and len(url) > terminalWidthLimit:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

##### Any other comments? What have you tried so far?

It seems like the addon is not updated (it still has flow_details=None), if I step into the master in the debugger, flow_details is an int.

##### System information

Mitmproxy version: 3.0.0 (2.0.0dev0142-0x124a6c9)
Python version: 3.5.2
Platform: Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
SSL version: OpenSSL 1.0.2g-fips  1 Mar 2016
Linux distro: Ubuntu 14.04 trusty

**Comment by cortesi** [comment]
Do you have a test foo.mitm for me that demonstrates this issue? Failing that, some info on how it was generated? I can't reproduce it by playing around with the current master.

**Comment by mhils** [comment]
Can't reproduce this on master, seems to be fixed! :)
