### ISSUE TITLE
mitmproxy crashes with error 'Reason: image not found' with brew install

### ISSUE THREAD

**Issue by dclaze** [mitmproxy/mitmproxy#2164]
Tried installing via [Homebrew](https://brew.sh/)

##### Steps to reproduce the problem:
1. brew install 
```
brew install mitmproxy
==> Installing dependencies for mitmproxy: libpng, freetype, jpeg
==> Installing mitmproxy dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.21.el_capitan.bo
######################################################################## 100.0%
==> Pouring libpng-1.6.21.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/libpng16
/usr/local/include is not writable.

You can try again using:
  brew link libpng
==> Summary
🍺  /usr/local/Cellar/libpng/1.6.21: 25 files, 1.2M
==> Installing mitmproxy dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.6.3.el_capitan.b
######################################################################## 100.0%
==> Pouring freetype-2.6.3.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/freetype2
/usr/local/include is not writable.

You can try again using:
  brew link freetype
==> Summary
🍺  /usr/local/Cellar/freetype/2.6.3: 61 files, 2.5M
==> Installing mitmproxy dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.el_capitan.bottle.2
######################################################################## 100.0%
==> Pouring jpeg-8d.el_capitan.bottle.2.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/jconfig.h
/usr/local/include is not writable.

You can try again using:
  brew link jpeg
==> Summary
🍺  /usr/local/Cellar/jpeg/8d: 19 files, 713.7K
==> Installing mitmproxy
==> Downloading https://homebrew.bintray.com/bottles/mitmproxy-0.16.el_capitan.b
######################################################################## 100.0%
==> Pouring mitmproxy-0.16.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/mitmproxy/0.16: 1,317 files, 19.8M
```
2. mitmproxy --version
```
mitmproxy
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.16', 'console_scripts', 'mitmproxy')()
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/main.py", line 45, in mitmproxy
    from . import console
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 17, in <module>
    from .. import controller, flow, script, contentviews
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 16, in <module>
    from . import controller, tnetstring, filt, script, version, flow_format_compat
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/script/__init__.py", line 2, in <module>
    from .script_context import ScriptContext
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/script/script_context.py", line 5, in <module>
    from .. import contentviews
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/contentviews.py", line 23, in <module>
    from PIL import Image
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/vendor/lib/python2.7/site-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: dlopen(/usr/local/Cellar/mitmproxy/0.16/libexec/vendor/lib/python2.7/site-packages/PIL/_imaging.so, 2): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/Cellar/mitmproxy/0.16/libexec/vendor/lib/python2.7/site-packages/PIL/_imaging.so
  Reason: image not found

```
##### System information
System Version: OS X 10.11.6
Homebrew 0.9.9
mitmproxy/0.16

**Comment by Kriechi** [comment]
Please use the latest homebrew 1.1.11. 
Then you will also be able to get the latest mitmproxy v2.0.1.

**Comment by DomT4** [comment]
@dclaze If the formulae from Homebrew are that old and a `brew update` doesn't work to resolve the issue you probably want to try [this](https://github.com/Homebrew/brew#update-bug).

`mitmproxy` 2.0.1 will be merged as part of https://github.com/Homebrew/homebrew-core/pull/10925, hopefully soon. Just chasing down the last few issues.
