### ISSUE TITLE
Crash when opening detail view in master branch

### ISSUE THREAD

**Issue by dequis** [mitmproxy/mitmproxy#2205]
##### Steps to reproduce the problem:

1. Host in 10.0.0.1 with transparent proxy config and `mitmproxy --mode transparent`
2. Device with `10.0.0.1 example.net` in /etc/hosts (not configured for transparent mitm)
3. Open example.net in device (should show bad gateway)
4. Open flow in mitmproxy
5. Press tab twice to get to detail view
6. Crash

##### Any other comments? What have you tried so far?

```
$ mitmproxy --mode transparent
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/master.py", line 295, in run
    self.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/flowview.py", line 502, in keypress
    key = super().keypress(size, key)
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/tabs.py", line 38, in keypress
    self.change_tab((self.tab_offset + 1) % n)
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/tabs.py", line 33, in change_tab
    self.show()
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/tabs.py", line 67, in show
    body = self.tabs[self.tab_offset][1](),
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/flowview.py", line 176, in view_details
    return flowdetailview.flowdetails(self.view, self.flow)
  File "/usr/lib/python3.6/site-packages/mitmproxy-3.0.0-py3.6.egg/mitmproxy/tools/console/flowdetailview.py", line 34, in flowdetails
    ["Resolved Address", "{}:{}".format(sc.ip_address[0], sc.ip_address[1])],
TypeError: 'NoneType' object is not subscriptable

mitmproxy has crashed!
```

##### System information

Revision 1e81747a2afb142bc6ef5c53c6d4572b94ee4495

Mitmproxy version: 3.0.0 (release version)
Python version: 3.6.0
Platform: Linux-4.9.11-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch

**Comment by mhils** [comment]
Thanks. This seems to be related to #2183.

**Comment by mhils** [comment]
fixed, thanks again.
