### ISSUE TITLE
Crash with duplicate flow

### ISSUE THREAD

**Issue by cym13** [mitmproxy/mitmproxy#2210]
##### Steps to reproduce the problem:

1. Start mitmproxy
2. Go to any url such as https://github.com/mitmproxy/mitmproxy
3. Hit 'D' to duplicate the flow
4. The application crashes

##### Stacktrace

DTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 987, in keypress
    self.make_cursor_visible((maxcol,maxrow))
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 939, in make_cursor_visible
    focus_widget, pos = self.body.get_focus()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 284, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 123, in __init__
    w = self.get_text()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 132, in get_text
    max_url_len=cols,
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/common.py", line 427, in format_flow
    acked = f.reply.state == "committed",
AttributeError: 'NoneType' object has no attribute 'state'

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...

##### System information

Mitmproxy version: 2.0.1 (release version)
Python version: 3.6.0
Platform: Linux-4.10.2-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch

**Comment by mhils** [comment]
Thanks! This has been fixed on master already, so things should work again with the next release.
