### ISSUE TITLE
KeyError: 'sdch, gzip'

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#2246]
##### Steps to reproduce the problem:

1:     #----------------------------------------------------------------------
    def response(self, flow):
        # Gather outgoing data size
        if flow.response.content:
            self.outgoing_data_size += len(flow.response.raw_content)
2. Go to google.com and search "test"
3. Red text flys by saying:
Script error: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 48, in decode
    decoded = custom_decode[encoding](encoded)
KeyError: 'sdch, gzip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 50, in decode
    decoded = codecs.decode(encoded, encoding, errors)
LookupError: unknown encoding: sdch, gzip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 791, in response
    if flow.response.content:
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/message.py", line 97, in get_content
    content = encoding.decode(self.raw_content, ce)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 61, in decode
    repr(e),
ValueError: LookupError when decoding b'\x1f\x8b with 'sdch, gzip': LookupError('unknown encoding: sdch, gzip',)

##### Any other comments? What have you tried so far?
Looks like gzip is supported, but I don't see anything about sdch. Looks to be missing

**Comment by mhils** [comment]
Now that's a bit confusing - my understanding is that the `Content-Encoding` header names the agreed-on encoding, so it shouldn't be a list. Can you share a mitmproxy dump file with a flow that has this issue?

**Comment by Mradr** [comment]
![untitled](https://cloud.githubusercontent.com/assets/937790/25303509/16daf6fc-271a-11e7-8d87-58504a0657b0.png)

**Comment by mhils** [comment]
Thanks. 

@cortesi: is it right that we do not call `request.constrain_encoding()` on flows by default?

**Comment by mhils** [comment]
Pretty sure this is an error and we should do that.
