### ISSUE TITLE
MemoryError,mitmproxy has crashed!

### ISSUE THREAD

**Issue by nmweizi** [mitmproxy/mitmproxy#2332]
```
Traceback (most recent call last):
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\server.py", line 119, in handle
    root_layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\tls.py", line 398, in __call__
    layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\http1.py", line 72, in __call__
    layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\http.py", line 370, in _process_flow
    self.read_response_body(f.request, f.response)
MemoryError
127.0.0.1:61302: Traceback (most recent call last):
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\server.py", line 119, in handle
    root_layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\tls.py", line 398, in __call__
    layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\http1.py", line 72, in __call__
    layer()
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "d:\python35\lib\site-packages\mitmproxy-3.0.0-py3.5.egg\mitmproxy\proxy\protocol\http.py", line 370, in _process_flow
    self.read_response_body(f.request, f.response)
MemoryError

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

Mitmproxy version: 3.0.0 (release version)
Python version: 3.5.3
Platform: Windows-10-10.0.14393-SP0
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Windows version: 10 10.0.14393 SP0 Multiprocessor Free

**Comment by ujjwal96** [comment]
Can you include the steps to reproduce?

**Comment by nmweizi** [comment]
1.d:\python35\Scripts\mitmdump.exe  --listen-host 127.0.0.1 --listen-port 8080 -s reps.py  -k
2.Browse the web, and the web is video.
3.This error is not timed

**Comment by nmweizi** [comment]
![image](https://cloud.githubusercontent.com/assets/1232444/25981655/037070ca-3709-11e7-821d-da6577292981.png)

**Comment by nmweizi** [comment]
reps.py
def start():
    # if len(sys.argv) != 3:
    #    raise ValueError('Usage: -s "modify_response_body.py old new"')
    # You may want to use Python's argparse for more sophisticated argument
    # parsing.
    pass


def request(flow):
    if 'method=setSKProgress' in flow.request.pretty_url:
        if flow.replace('%22time%22:.*,', '%22time%22:2400,') > 0:
            mitmproxy.ctx.log('-' * 40)
            mitmproxy.ctx.log.error('->   patch setSKProgress ok!')
            mitmproxy.ctx.log('-' * 40)
    pass


def response(flow):
    if 'CW0/index.html' in flow.request.pretty_url:
        # with decoded(flow.response):
        # if 'login' in flow.request.pretty_url:
        if flow.replace('onPlay:', 'onPlay1:') > 0:
            mitmproxy.ctx.log('-' * 40)
            mitmproxy.ctx.log.error('->   patch onComplete ok!')
            mitmproxy.ctx.log('-' * 40)

**Comment by Ritiek** [comment]
I am not sure if this will help but try passing something like `--stream 500k` when starting mitmdump.

**Comment by nmweizi** [comment]
mitmdump: error: unrecognized arguments: --stream

**Comment by nmweizi** [comment]
ok.
mitmproxy.ctx.options.stream_large_bodies = '5m'
