### ISSUE TITLE
Crash when press shift + D

### ISSUE THREAD

**Issue by shaynewang** [mitmproxy/mitmproxy#2345]
##### Steps to reproduce the problem:
mitmproxy crashes when 

1. run mitmproxy
2. after receive some packets
3. press ```shift``` + ```D```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/listbox.py", line 987, in keypress
    self.make_cursor_visible((maxcol,maxrow))
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/listbox.py", line 939, in make_cursor_visible
    focus_widget, pos = self.body.get_focus()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 284, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 123, in __init__
    w = self.get_text()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 132, in get_text
    max_url_len=cols,
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/common.py", line 427, in format_flow
    acked = f.reply.state == "committed",
AttributeError: 'NoneType' object has no attribute 'state'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### System information

```mitmproxy --version
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-16.5.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.4 ('', '', '') x86_64
```

**Comment by Ritiek** [comment]
@shaynewang I had this issue. Did you try installing directly from the master branch? It fixed for me. Seems like mitmproxy has not been updated on pypi.

**Comment by mhils** [comment]
Thanks for reporting this. As @Ritiek already remarked (thanks!), this is fixed on master and will be fixed with the next release. :)

refs #2086
