### ISSUE TITLE
Crash in flowfilter

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#2357]
```
Addon error: Traceback (most recent call last):
  File "mitmproxy/addons/dumper.py", line 212, in match
    elif flowfilter.match(self.filter, f):
  File "mitmproxy/flowfilter.py", line 537, in match
    return flt(flow)
  File "mitmproxy/flowfilter.py", line 55, in filter_types
    return fn(self, flow)
  File "mitmproxy/flowfilter.py", line 347, in __call__
    return self.re.search(f.request.pretty_url)
AttributeError: 'NoneType' object has no attribute 'pretty_url'
```

on git-master

**Comment by Kriechi** [comment]
fixed by 4fb9cc1a69f7000e274a2f26d91d2b198bc7c8b1
