### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by JonhSilver** [mitmproxy/mitmproxy#2371]
Traceback (most recent call last):
  File "pymultitor/examples/on_string/b.py", line 117, in <module>
    process = execute_pymultitor()
  File "pymultitor/examples/on_string/b.py", line 23, in execute_pymultitor
    pymultitor_module = imp.load_source('pymultitor', pymultitor_path)
  File "c:\Python27\pymultitor\pymultitor.py", line 19, in <module>
    from mitmproxy.proxy import ProxyServer, ProxyConfig
  File "c:\Python27\lib\site-packages\mitmproxy\proxy\__init__.py", line 4, in <
module>
    from .root_context import RootContext
  File "c:\Python27\lib\site-packages\mitmproxy\proxy\root_context.py", line 8,
in <module>
    from mitmproxy import controller
  File "c:\Python27\lib\site-packages\mitmproxy\controller.py", line 9, in <modu
le>
    from mitmproxy import addons
  File "c:\Python27\lib\site-packages\mitmproxy\addons\__init__.py", line 3, in
<module>
    from mitmproxy.addons import check_alpn
  File "c:\Python27\lib\site-packages\mitmproxy\addons\check_alpn.py", line 2, i
n <module>
    from mitmproxy.net import tcp
  File "c:\Python27\lib\site-packages\mitmproxy\net\tcp.py", line 987
    print(u'-' * 40, file=fp)
                         ^
SyntaxError: invalid syntax

**Comment by JonhSilver** [comment]
Traceback (most recent call last):
  File "pymultitor/examples/on_string/b.py", line 117, in <module>
    process = execute_pymultitor()
  File "pymultitor/examples/on_string/b.py", line 23, in execute_pymultitor
    pymultitor_module = imp.load_source('pymultitor', pymultitor_path)
  File "c:\Python27\pymultitor\pymultitor.py", line 19, in <module>
    from mitmproxy.proxy import ProxyServer, ProxyConfig
  File "c:\Python27\lib\site-packages\mitmproxy\proxy\__init__.py", line 4, in <
module>
    from .root_context import RootContext
  File "c:\Python27\lib\site-packages\mitmproxy\proxy\root_context.py", line 8,
in <module>
    from mitmproxy import controller
  File "c:\Python27\lib\site-packages\mitmproxy\controller.py", line 9, in <modu
le>
    from mitmproxy import addons
  File "c:\Python27\lib\site-packages\mitmproxy\addons\__init__.py", line 3, in
<module>
    from mitmproxy.addons import check_alpn
  File "c:\Python27\lib\site-packages\mitmproxy\addons\check_alpn.py", line 2, i
n <module>
    from mitmproxy.net import tcp
  File "c:\Python27\lib\site-packages\mitmproxy\net\tcp.py", line 14, in <module
>
    from mitmproxy.utils import strutils
  File "c:\Python27\lib\site-packages\mitmproxy\utils\strutils.py", line 6
    def always_bytes(str_or_bytes: Optional[AnyStr], *encode_args) -> Optional[b
ytes]:
                                 ^
SyntaxError: invalid syntax

**Comment by Kriechi** [comment]
mitmproxy requires Python 3.5 or higher.
Please install a newer Python and try installing mitmproxy again with `pip3 install mitmproxy`.
