### ISSUE TITLE
cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_...'

### ISSUE THREAD

**Issue by martin3991** [mitmproxy/mitmproxy#2372]
Hello,
because of some new features, which aren't in version 2.0.2,
I installed mitmproxy from master by:
```
git clone https://github.com/mitmproxy/mitmproxy.git
cd mitmproxy
pip install --src . -r requirements.txt
```
But when I start mitmproxy, I get:
```
Traceback (most recent call last):
  File "/home/mitm/.local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/__init__.py", line 3, in <module>
    from . import script  # noqa
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/script/__init__.py", line 1, in <module>
    from .concurrent import concurrent
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/script/concurrent.py", line 6, in <module>
    from mitmproxy import eventsequence
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/eventsequence.py", line 2, in <module>
    from mitmproxy import http
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/http.py", line 4, in <module>
    from mitmproxy import flow
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/flow.py", line 6, in <module>
    from mitmproxy import connections
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/connections.py", line 7, in <module>
    from mitmproxy import certs
  File "/home/mitm/.local/lib/python3.5/site-packages/mitmproxy/certs.py", line 11, in <module>
    import OpenSSL
  File "/home/mitm/.local/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/mitm/.local/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/mitm/.local/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/mitm/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/home/mitm/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/mitm/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/mitm/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 84, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_X25519'
```

Also when I install it from wheel from: [https://snapshots.mitmproxy.org/v3.0.0/](https://snapshots.mitmproxy.org/v3.0.0/)

Does someone else get it too?

##### System information
- Ubuntu 16.04

**Comment by Ritiek** [comment]
@martin3991 I had a similar problem once (but not same), installing [cryptography](https://github.com/pyca/cryptography) from source fixed it for me. You might have luck.

**Comment by Kriechi** [comment]
Seems like you OpenSSL version is too old or does not match what cryptography expect to find.
Please refer to the cryptography docs to fix your environment: https://cryptography.io/en/latest/installation/#supported-platforms

**Comment by martin3991** [comment]
@Ritiek you were right. The cryptography package was the problem.
The versions 1.8.1 and 1.8.2 caused the error.
But with version 1.9 it works.

**Comment by harsh23tyagi** [comment]
Though this chain is closed, but i faced the same issue. It might happen due to a conflict of the cryptography bundle in multiple libraries. I just uninstalled the cryptography bundle and reinstalled it again which reflected all the libraries that were using it. I use conda.
Just do the following:
conda uninstall cryptography
-------------Post uninstalling---------
conda install cryptography
