### ISSUE TITLE
Intercepting flows to mitm.it crashes mitmproxy

### ISSUE THREAD

**Issue by jtl999** [mitmproxy/mitmproxy#2431]
Trying out mitmproxy. When I capture a connection and attempt to accept it mitmproxy crashes.

##### Steps to reproduce the problem:

1. Install mitmproxy from homebrew, trust the CA certificate, configure Chrome proxy settings.
2. Capture a flow/connection (in my case I navigated to `mitm.it`)
3. Accept the flow, mitmproxy will now crash.

##### Any other comments? What have you tried so far?
```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowview.py", line 513, in keypress
    self.flow.resume()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/flow.py", line 179, in resume
    self.reply.ack()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/controller.py", line 155, in ack
    self.send(self.obj, force)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/controller.py", line 166, in send
    raise exceptions.ControlException("There is already a reply message.")
mitmproxy.exceptions.ControlException: There is already a reply message.
```

##### System information

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.11.6 ('', '', '') x86_64

**Comment by jtl999** [comment]
Just reproduced the same crash under Debian 8.8 with the precompiled binaries (I have too much time tonight) while capturing and accepting a flow to `mitm.it` as well. Didn't seem to happen with other domains either.

Stacktrace and mitmproxy version info

```
Traceback (most recent call last):
  File "mitmproxy/tools/console/master.py", line 281, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 719, in _loop
  File "site-packages/urwid/raw_display.py", line 393, in <lambda>
  File "site-packages/urwid/raw_display.py", line 493, in parse_input
  File "site-packages/urwid/main_loop.py", line 403, in _update
  File "site-packages/urwid/main_loop.py", line 503, in process_input
  File "mitmproxy/tools/console/window.py", line 84, in keypress
  File "site-packages/urwid/container.py", line 1128, in keypress
  File "mitmproxy/tools/console/flowlist.py", line 417, in keypress
  File "site-packages/urwid/listbox.py", line 985, in keypress
  File "mitmproxy/tools/console/flowlist.py", line 169, in keypress
  File "mitmproxy/flow.py", line 179, in resume
  File "mitmproxy/controller.py", line 155, in ack
  File "mitmproxy/controller.py", line 166, in send
mitmproxy.exceptions.ControlException: There is already a reply message.

root@mitmproxy:~# mitmproxy --version
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian 8.8
```

**Comment by mhils** [comment]
Thanks for looking into this and apologies for the late reply - I though this'd be a copy of an issue discussed on Slack, but apparently you are an unrelated user. :-)

Can you confirm that this only applies to mitm.it, but not to other domains?

**Comment by jtl999** [comment]
> Can you confirm that this only applies to mitm.it, but not to other domains?

Confirmed, only affects mitm.it, reproduced on both Darwin and Debian.

**Comment by Kriechi** [comment]
This still is reproducible with v3.0.0rc1.
Intercepting mitm.it results in a crash. Other domains work.

**Comment by kajojify** [comment]
Reproduced on Ubuntu 16.04 with Firefox.

**Comment by jtl999** [comment]
On much further analysis this is probably caused by the `onboarding` addon and the internal response bypassing mitmproxy 
![mitmproxy_addon](https://user-images.githubusercontent.com/1234670/83391792-dd3fca80-a3a8-11ea-97b7-a756e149a654.png)

Because of this other domains are fine and I'm unsure if spending time towards fixing this would be of interest.

**Comment by alt-glitch** [comment]
Trying to reproduce this issue on Manjaro 20.2.1 but mimproxy seems to be intercepting mitm.it requests properly. Am I missing something here or has this bug been resolved?
![image](https://user-images.githubusercontent.com/52913345/107598435-b4641a80-6c43-11eb-96aa-1c82ff30454c.png)
**System Information**
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.10.7-3-MANJARO-x86_64-with-glibc2.32

**Comment by jtl999** [comment]
> Am I missing something here or has this bug been resolved?

Appears to have been fixed since my last comment.
