### ISSUE TITLE
TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by chenzx** [mitmproxy/mitmproxy#2441]
When i try to access flow.request.url in requestheaders event, something wrong happened:

```
    def requestheaders(self, flow):
        print(repr(flow.request.headers))
        if not flow.request.url:
            print("flow.request.url is None")
            return
        if not flow.request.path:
            print("flow.request.path is None")
            return
        print("flow.request.url={} flow.request.path={}".format(flow.request.url, flow.request.path))
```

**Comment by chenzx** [comment]
```
Reloading script: mitmproxy-addon-http-ALG.py
127.0.0.1:61596: clientconnect
Request(OPTIONS /openapi/recommend/homepage/playlist?deviceId=gm)
Script error: Traceback (most recent call last):
  File "mitmproxy-addon-http-ALG.py", line 35, in requestheaders
    print("flow.request.url={} flow.request.path={}".format(flow.request.url, flow.request.path))
  File "mitmproxy\net\http\request.py", line 240, in url
  File "mitmproxy\net\http\url.py", line 82, in unparse
  File "mitmproxy\net\http\url.py", line 140, in hostport
TypeError: %d format: a number is required, not NoneType
```

**Comment by Kriechi** [comment]
This should already be fixed in git-master.
