### ISSUE TITLE
Problem with glibc

### ISSUE THREAD

**Issue by paskyorg** [mitmproxy/mitmproxy#2445]
##### Steps to reproduce the problem:

1. I downloaded mitmproxy-2.0.2-linux.tar.gz and untar it.
2. I ran ./mitmdump or ./mitmproxy and I got error either with glibc-2.14 and glibc-2.15. 

##### Any other comments? What have you tried so far?

After first problem, I downloaded glibc 2.14 and compiled it in /opt/glibc-2.14, because my linux has glibc-2.12. Before, when it fails again, I downloaded glibc 2.15, and it fails again.

##### System information
Centos 6.8 with Python 3.5.3 installed from sources.

```
 ./mitmproxy
Error loading Python lib '/tmp/_MEIydkhSO/libpython3.5m.so.1.0': /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIydkhSO/libpython3.5m.so.1.0)

# export LD_LIBRARY_PATH=/opt/glibc-2.14/lib
# ./mitmproxy
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/pkg_resources/__init__.py", line 33, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "platform.py", line 117, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "subprocess.py", line 438, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /opt/glibc-2.14/lib/libc.so.6: version `GLIBC_2.15' not found (required by /tmp/_MEI4qJfox/select.so)
Failed to execute script pyi_rth_pkgres

# export LD_LIBRARY_PATH=/opt/glibc-2.15/lib
# ./mitmproxy
Error loading Python lib '/tmp/_MEIlZpAhU/libpython3.5m.so.1.0': /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIlZpAhU/libpython3.5m.so.1.0)
```

**Comment by mhils** [comment]
Thanks. We seem to be hitting this: https://stackoverflow.com/a/17654364/934719. 
We build our binaries using Travis CI - I'm happy to accept a patch that makes binaries with a lower glibc version, but a cursory search indicates that this is nontrivial. My recommendation would be to either use our Docker container or upgrade your system.

@Kriechi or @cortesi may have a more informed opinion on this, I'm primarily on Windows. :)

**Comment by mhils** [comment]
I just commited e02138d, which mandates that our binaries should be built on Ubuntu 12.04. This is old enough for our purposes.
