### ISSUE TITLE
While Image Upload it Crashed

### ISSUE THREAD

**Issue by amankumarjain** [mitmproxy/mitmproxy#2458]
Request to send body with image file

Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 238, in keypress
    self.master.view_flow(self.flow)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 374, in view_flow
    flowview.help_context
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 141, in sig_push_view_state
    self.loop.draw_screen()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/listbox.py", line 485, in render
    canvas = widget.render((maxcol,))
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 1007, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/canvas.py", line 1313, in apply_text_layout
    return TextCanvas(t, a, c, maxcol=maxcol)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/urwid/canvas.py", line 356, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified

**Comment by mhils** [comment]
Thanks. Can you share the file that causes this?

**Comment by ujjwal96** [comment]
I think this is fixed on git-master. Can you verify?
ref: #1796
