### ISSUE TITLE
Keyerror in compat 0.17 - peer_address

### ISSUE THREAD

**Issue by rabo-soc** [mitmproxy/mitmproxy#2495]
I get this error when loading an old 0.17 dump file:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/2.0.2/bin/mitmdump", line 11, in <module>
    load_entry_point('mitmproxy==2.0.2', 'console_scripts', 'mitmdump')()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/main.py", line 120, in mitmdump
    master = dump.DumpMaster(dump_options, server)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/dump.py", line 55, in __init__
    self.load_flows_file(options.rfile)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/master.py", line 182, in load_flows_file
    return self.load_flows(freader)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/master.py", line 164, in load_flows
    for i in fr.stream():
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/io.py", line 42, in stream
    data = io_compat.migrate_flow(data)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/io_compat.py", line 152, in migrate_flow
    flow_data = converters[flow_version[:2]](flow_data)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/io_compat.py", line 61, in convert_017_018
    data["server_conn"]["ip_address"] = data["server_conn"].pop("peer_address")
KeyError: 'peer_address'
```

##### Steps to reproduce the problem:

1. Create an outfile with mitmproxy 0.17
2. Open with mitmdump 2.0.2
3. Get a keyerror on "peer_address"

##### Any other comments? What have you tried so far?

Was told on slack to create an issue, however I can't supply the test files because they contain sensitive data.

##### System information

$ /usr/local/Cellar/mitmproxy/2.0.2/bin/mitmdump --version
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.2
Platform: Darwin-16.7.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.6 ('', '', '') x86_64

**Comment by Dutchy-** [comment]
Commenting from my actual account to keep track of it - accidentally created the issue on the wrong account.

**Comment by mhils** [comment]
0.17 is old enough that we won't maintain this ourselves anymore, but I'd certainly accept a PR that fixes this, which should be easy.
