### ISSUE TITLE
mitmdump error message

### ISSUE THREAD

**Issue by juamc2503** [mitmproxy/mitmproxy#2517]
##### Steps to reproduce the problem:

1.why mitmdump is giving me this error after 5 mins connection??

##### System information

```
:~$ sudo su
/home/ubuntu# mitmdump --host -dd -s "./phone.py ALL" -w logfile.txt | grep "Tried to accept - code"
404 GET /favicon.ico (66.176.89.253) 0.26ms
Tried to accept - code 410
----------------------------------------
Error in processing of request from 103.235.255.31:41455
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/tcp.py", line 932, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/server.py", line 63, in handle_client_connection
    self.channel
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/server.py", line 76, in __init__
    None)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/connections.py", line 33, in __init__
    super().__init__(client_connection, address, server)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/tcp.py", line 795, in __init__
    super().__init__(connection)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/tcp.py", line 455, in __init__
    self.ip_address = Address(connection.getpeername())
OSError: [Errno 107] Transport endpoint is not connected

----------------------------------------

```

**Comment by mhils** [comment]
Not sure what is happening here - how can we reproduce this?

**Comment by juamc2503** [comment]
I dont know really but i stopped my vm then started again  and its working again my script, and not giving me the error
