### ISSUE TITLE
error: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

### ISSUE THREAD

**Issue by henrymark92** [mitmproxy/mitmproxy#2521]
1. Execute mitmproxy/platform/windows.py

Here log:
```
 * Transparent proxy active.
   Filter: tcp.DstPort == 80 or tcp.DstPort == 443
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\python32\python-2.7.10\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\python32\python-2.7.10\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:/source/SmartAuto/mitmproxy/platform/windows.py", line 314, in request_local
    client = (packet.src_addr, packet.src_port)
  File "C:\python32\python-2.7.10\lib\site-packages\pydivert\models.py", line 416, in src_addr
    return addr_to_string(self.address_family, src_addr, self.encoding)
  File "C:\python32\python-2.7.10\lib\site-packages\pydivert\winutils.py", line 59, in addr_to_string
    return inet_ntop(socket.AF_INET6, struct.pack("<IIII", *value), encoding)
  File "C:\python32\python-2.7.10\lib\site-packages\pydivert\winutils.py", line 119, in inet_ntop
    raise socket.error(FormatError())
error: The system detected an invalid pointer address in attempting to use a pointer argument in a call.
```

**Comment by mhils** [comment]
`C:\python32\python-2.7.10` - this looks like your Python installation is borked? Mitmproxy requires Python 3.5.

**Comment by henrymark92** [comment]
I'm using version mitmproxy-0.17.1

**Comment by mhils** [comment]
We're not supprintg 0.17 anymore, please upgrade.

**Comment by henrymark92** [comment]
* Transparent proxy active.
   Filter: tcp.DstPort == 80 or tcp.DstPort == 443
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Gigabyte/PycharmProjects/untitled1/mitmproxy/platform/windows.py", line 331, in request_local
    self._request(packet)
  File "C:/Users/Gigabyte/PycharmProjects/untitled1/mitmproxy/platform/windows.py", line 359, in _request
    packet.dst_addr, packet.dst_port = self.proxy_addr, self.proxy_port
  File "C:\Python35\lib\site-packages\pydivert\packet\__init__.py", line 257, in dst_addr
    self.ip.dst_addr = val
  File "C:\Python35\lib\site-packages\pydivert\packet\header.py", line 43, in __setattr__
    return super(Header, self).__setattr__(key, value)
  File "C:\Python35\lib\site-packages\pydivert\packet\ip.py", line 54, in dst_addr
    self.raw[self._dst_addr] = socket.inet_pton(self._af, val)
OSError: [WinError 10022] An invalid argument was supplied

**Comment by mhils** [comment]
What's the value of `val` in the traceback you posted?

**Comment by henrymark92** [comment]
val = 192.168.1.130

**Comment by mhils** [comment]
`socket.inet_pton(socket.AF_INET, "192.168.1.130")` works fine for me, that can't be the value that causes the issue.
