### ISSUE TITLE
Duplicating a flow crashes mitmproxy

### ISSUE THREAD

**Issue by mictee** [mitmproxy/mitmproxy#2531]
##### Steps to reproduce the problem:

1. Start mitmproxy with default configuration
2. Log any traffic
3. Press [D] to duplicate a flow

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 987, in keypress
    self.make_cursor_visible((maxcol,maxrow))
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 939, in make_cursor_visible
    focus_widget, pos = self.body.get_focus()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 284, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 123, in __init__
    w = self.get_text()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 132, in get_text
    max_url_len=cols,
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/common.py", line 427, in format_flow
    acked = f.reply.state == "committed",
AttributeError: 'NoneType' object has no attribute 'state'
```

##### Any other comments? What have you tried so far?
I've tried duplicating different kinds of flows. As the final line in the traceback seems to hint that the selected flow's reply may be empty, I made sure to select flows with fully captured (not pending) responses.

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Linux-4.12.4-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: arch

**Comment by ujjwal96** [comment]
Thanks for the report, this is already fixed on git-master

**Comment by majewsky** [comment]
Any idea when the next release comes? I'm still impeded by this bug. Using master is not an option.
