### ISSUE TITLE
OSError: [WinError 10022] An invalid argument was supplied

### ISSUE THREAD

**Issue by henrymark92** [mitmproxy/mitmproxy#2535]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Gigabyte/PycharmProjects/untitled1/mitmproxy/platform/windows.py", line 331, in request_local
    self._request(packet)
  File "C:/Users/Gigabyte/PycharmProjects/untitled1/mitmproxy/platform/windows.py", line 359, in _request
    packet.dst_addr, packet.dst_port = self.proxy_addr, self.proxy_port
  File "C:\Python35\lib\site-packages\pydivert\packet\__init__.py", line 257, in dst_addr
    self.ip.dst_addr = val
  File "C:\Python35\lib\site-packages\pydivert\packet\header.py", line 43, in __setattr__
    return super(Header, self).__setattr__(key, value)
  File "C:\Python35\lib\site-packages\pydivert\packet\ip.py", line 55, in dst_addr
    self.raw[self._dst_addr] = socket.inet_pton(self._af, val)
OSError: [WinError 10022] An invalid argument was supplied

**Comment by ujjwal96** [comment]
Please tell the steps to reproduce, mitmproxy version used and other relevant details. I doubt anyone can help just by looking at the stack trace.

**Comment by henrymark92** [comment]
I'm using win7 64bit. I has tried run the windows.py file and I got an above error
