### ISSUE TITLE
Crash when trying to save listed Websocket flows

### ISSUE THREAD

**Issue by securisec** [mitmproxy/mitmproxy#2550]
##### Steps to reproduce the problem:

1. Make a websocket request with python websocket. Test url is ws://139.59.13.232:4200
2. Try to write flow to disk
3. Crash

##### Any other comments? What have you tried so far?
`Traceback (most recent call last):
  File "mitmproxy/tools/console/master.py", line 281, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 719, in _loop
  File "site-packages/urwid/raw_display.py", line 393, in <lambda>
  File "site-packages/urwid/raw_display.py", line 493, in parse_input
  File "site-packages/urwid/main_loop.py", line 403, in _update
  File "site-packages/urwid/main_loop.py", line 503, in process_input
  File "mitmproxy/tools/console/window.py", line 84, in keypress
  File "site-packages/urwid/container.py", line 1116, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 155, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 110, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 133, in prompt_execute
  File "mitmproxy/tools/console/statusbar.py", line 21, in __call__
  File "mitmproxy/tools/console/master.py", line 388, in save_flows
  File "mitmproxy/tools/console/master.py", line 382, in _write_flows
  File "mitmproxy/io.py", line 27, in add
  File "mitmproxy/contrib/tnetstring.py", line 66, in dump
  File "mitmproxy/contrib/tnetstring.py", line 57, in dumps
  File "mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
  File "mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
  File "mitmproxy/contrib/tnetstring.py", line 149, in _rdumpq
ValueError: unserializable object: <WebSocketFlow (4 messages)> (<class 'mitmproxy.websocket.WebSocketFlow'>)`

##### System information

`Mitmproxy version: 2.0.1 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.4.0-89-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid `

**Comment by Kriechi** [comment]
Thanks for reporting this!

I believe this should already be fixed by https://github.com/mitmproxy/mitmproxy/pull/2114
Would you mind trying with the current git master version?

**Comment by securisec** [comment]
Thanks. I just upgraded to the latest release 2.0.2 and am getting the same error. 
`Traceback (most recent call last):
  File "mitmproxy/tools/console/master.py", line 281, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 719, in _loop
  File "site-packages/urwid/raw_display.py", line 393, in <lambda>
  File "site-packages/urwid/raw_display.py", line 493, in parse_input
  File "site-packages/urwid/main_loop.py", line 403, in _update
  File "site-packages/urwid/main_loop.py", line 503, in process_input
  File "mitmproxy/tools/console/window.py", line 84, in keypress
  File "site-packages/urwid/container.py", line 1116, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 155, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 110, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 133, in prompt_execute
  File "mitmproxy/tools/console/statusbar.py", line 21, in __call__
  File "mitmproxy/tools/console/master.py", line 388, in save_flows
  File "mitmproxy/tools/console/master.py", line 382, in _write_flows
  File "mitmproxy/io.py", line 27, in add
  File "mitmproxy/contrib/tnetstring.py", line 66, in dump
  File "mitmproxy/contrib/tnetstring.py", line 57, in dumps
  File "mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
  File "mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
  File "mitmproxy/contrib/tnetstring.py", line 149, in _rdumpq
ValueError: unserializable object: <WebSocketFlow (4 messages)> (<class 'mitmproxy.websocket.WebSocketFlow'>)

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...
$ mitmproxy --version
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.4.0-89-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid `

**Comment by Kriechi** [comment]
mitmproxy v2.0.2 does not yet contain this fix.
Please try the current git master version.

**Comment by securisec** [comment]
Looks like it is working as expected. Thanks!
