### ISSUE TITLE
Mitm crashed after device on iOS go to ppq.apple.com

### ISSUE THREAD

**Issue by alter-al** [mitmproxy/mitmproxy#2557]
##### Steps to reproduce the problem:

1. mitmproxy -s redirect.py (with own hosts)
2. connect iphone with mitmproxy via mitm.it
3. tap on [verify ios app](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/iphone6-ios9-enterprise-profile_settings-verify_app.png) (iphone tried to go on ppq.apple.com)

*Actual result:*
mitmproxy has crashed

##### Any other comments? What have you tried so far?
It happens rarely and, to fix, just restart the mitmproxy. I tried to --ignore ppq.apple.com and apple.com, but it didn't help.

##### System information

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.2
Platform: Darwin-16.7.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.6 ('', '', '') x86_64

##### Crash log

    mitmproxy has crashed!
    Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
    Traceback (most recent call last):
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
    Error: 100.100.121.115:63386: Traceback (most recent call last):Traceback (most recent call last):ocol/http1.py", line 72, in __call__
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handleexec/lib/python3.6/site-packages/mi    root_layer()otocol/http.py", line 188, in __call__
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__ython3.6/site-packages/milayer()xy/protocol/http.py", line 257, in _process_flow
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__/python3.6/site-packages/mi    layer()xy/protocol/http.py", line 206, in handle_regular_connect
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 72, in __call__python3.6/site-packages/milayer()xy/protocol/rawtcp.py", line 34, in __call__
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__python3.6/site-packages/mi    if not self._process_flow(flow):l_read_select
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 257, in _process_flow
    return self.handle_regular_connect(f)
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/rawtcp.py", line 34, in __call__
    r = mitmproxy.net.tcp.ssl_read_select(conns, 10)
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 387, in ssl_read_select
    ] or select.select(rlist, (), (), timeout)[0]
    ValueError: filedescriptor out of range in select()

    mitmproxy has crashed!
    Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
    Traceback (most recent call last):
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    Error: 100.100.121.115:63388: Traceback (most recent call last):
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 257, in _process_flow
    return self.handle_regular_connect(f)
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mTraceback (most recent call last):
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 257, in _process_flow
    return self.handle_regular_connect(f)
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/rawtcp.py", line 34, in __call__
    r = mitmproxy.net.tcp.ssl_read_select(conns, 10)
    File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 387, in ssl_read_select
    ] or select.select(rlist, (), (), timeout)[0]
    ValueError: filedescriptor out of range in select()

**Comment by mhils** [comment]
Thanks for the report. Unless you can provide better instructions for reproducing this I unforunately don't see anything actionable in here. Any hints how this can be reproduced consistently?

**Comment by alter-al** [comment]
I can add, that if mitmproxy working very long (example 4-7 days) without breaks, it begins to disconnect internet connection at the device (and occurs many crashes, such as bug with ppq.apple.com)
