### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by michaeladm** [mitmproxy/mitmproxy#2578]
##### Steps to reproduce the problem:

1. In the cmd run mitmweb --replace-from-file :~s:"</head":2.txt
2. In Chrome http://some.site
3. Its sems to work, but ...

##### Any other comments? What have you tried so far?
```
#-----------------------
#File "2.txt"
#<script type="text/javascript">
#</script>
#</head
#-----------------------
C:\>mitmweb --replace-from-file :~s:"</head":2.txt
Proxy server listening at http://0.0.0.0:8080/
Web   server listening at http://127.0.0.1:8081/
127.0.0.1:61709: clientconnect
127.0.0.1:61709: HTTP protocol error in client request: Bad HTTP request line: b'\x05\x01\x00'
127.0.0.1:61709: clientdisconnect
127.0.0.1:61721: clientconnect
127.0.0.1:61722: clientconnect
127.0.0.1:61722: HTTP protocol error in client request: Bad HTTP request line: b'\x05\x01\x00'
127.0.0.1:61722: clientdisconnect
127.0.0.1:62288: clientconnect
ERROR:tornado.application:Exception in callback <function WebMaster.run.<locals>.<lambda> at 0x04E81108>
Traceback (most recent call last):
  File "site-packages\tornado\ioloop.py", line 1041, in _run
  File "mitmproxy\tools\web\master.py", line 109, in <lambda>
  File "mitmproxy\master.py", line 109, in tick
  File "mitmproxy\controller.py", line 70, in wrapper
  File "mitmproxy\addonmanager.py", line 90, in __call__
  File "mitmproxy\addonmanager.py", line 85, in invoke
  File "mitmproxy\addons\replace.py", line 93, in response
  File "mitmproxy\addons\replace.py", line 83, in execute
  File "mitmproxy\addons\replace.py", line 112, in replace
  File "mitmproxy\net\http\message.py", line 261, in replace
  File "mitmproxy\net\http\message.py", line 100, in get_content
ValueError: Invalid Content-Encoding: utf-8
127.0.0.1:62293: clientconnect
```
```
#-----------------------
# script https://wiki.lkqd.com/pages/viewpage.action?pageId=852444
#File "1.txt"
#<script type="text/javascript">
#.... a lot of code with ....src=https://www.xxxxx.com/dfdf ...
#</script>
#</head
#-----------------------
C:\>mitmweb --replace-from-file :~s:"</head":1.txt
Proxy server listening at http://0.0.0.0:8080/
Web   server listening at http://127.0.0.1:8081/
127.0.0.1:61251: clientdisconnect
ERROR:tornado.application:Exception in callback <function WebMaster.run.<locals>.<lambda> at 0x04E81108>
Traceback (most recent call last):
  File "site-packages\tornado\ioloop.py", line 1041, in _run
  File "mitmproxy\tools\web\master.py", line 109, in <lambda>
  File "mitmproxy\master.py", line 109, in tick
  File "mitmproxy\controller.py", line 70, in wrapper
  File "mitmproxy\addonmanager.py", line 90, in __call__
  File "mitmproxy\addonmanager.py", line 85, in invoke
  File "mitmproxy\addons\termlog.py", line 27, in log
  File "site-packages\click\termui.py", line 420, in secho
  File "site-packages\click\utils.py", line 259, in echo
  File "site-packages\click\_compat.py", line 577, in _safe_write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
  File "c:\projects\mitmproxy\.tox\rtool\lib\encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 75-83: character maps to <undefined>
127.0.0.1:61319: clientdisconnect
```
##### System information

Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.3
Platform: Windows-10-10.0.14393
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 10 10.0.14393  Multiprocessor Free

**Comment by mhils** [comment]
Thanks for the report. The error you are mentioning is already fixed on master and will be fixed with the next release. :)
