### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by sikmir** [mitmproxy/mitmproxy#2579]
### Steps to reproduce the problem ###

```bash
$ docker pull docker pull mitmproxy/mitmproxy:2.0.2
$ cat << 'EOF' > docker-compose.yml
version: '3'
services:
  mitmproxy:
    image: mitmproxy/mitmproxy:2.0.2
    container_name: mitmproxy
    ports:
      - 8080:8080
    volumes:
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
EOF
$ docker-compose up -d mitmproxy
$ docker-compose logs mitmproxy
Attaching to mitmproxy
mitmproxy    | Traceback (most recent call last):
mitmproxy    |   File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/master.py", line 281, in run
mitmproxy    |     self.loop.run()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
mitmproxy    |     self._run()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
mitmproxy    |     self.event_loop.run()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
mitmproxy    |     self._loop()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
mitmproxy    |     self._watch_files[fd]()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
mitmproxy    |     event_loop, callback, self.get_available_raw_input())
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 427, in get_available_raw_input
mitmproxy    |     codes = self._get_gpm_codes() + self._get_keyboard_codes()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 501, in _get_keyboard_codes
mitmproxy    |     code = self._getch_nodelay()
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 635, in _getch_nodelay
mitmproxy    |     return self._getch(0)
mitmproxy    |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 545, in _getch
mitmproxy    |     return ord(os.read(self._term_input_file.fileno(), 1))
mitmproxy    | TypeError: ord() expected a character, but string of length 0 found
mitmproxy    |
mitmproxy    | mitmproxy has crashed!
mitmproxy    | Please lodge a bug report at:
mitmproxy    |  https://github.com/mitmproxy/mitmproxy
mitmproxy    | Shutting down...
```
The same problem with ```latest``` tag.

**Comment by Kriechi** [comment]
I think you need `tty: true` for mitmproxy to work, and maybe other flags as well to get an interactive UI with ncurses in your terminal.

If you only want `mitmdump` or `mitmweb`, please see https://github.com/mitmproxy/docker-releases#usage

**Comment by sikmir** [comment]
Sure, I've missed ```command: mitmdump -w ...```. Thanks!

**Comment by HasBert** [comment]
@Kriechi I am trying to start `mitmproxy/mitmproxy:latest mitmroxy` with docker-compose up. You said that I need ncurses. Do you have any experience / instructions with this? `mitmdump` works so far. If I start my container with this command:
```yaml
version: '3'
services:
  mitmproxy:
      image: mitmproxy/mitmproxy:latest
      container_name: mitmproxy
      #restart: unless-stopped
      command: mitmproxy
      volumes: 
        - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
      tty: true
      stdin_open: true
```

I get this error:

```bash
$ docker-compose up
Recreating mitmproxy ... 
Recreating mitmproxy ... done
Attaching to mitmproxy
mitmproxy    | Traceback (most recent call last):
mitmproxy    |   File "/usr/bin/mitmproxy", line 11, in <module>
mitmproxy    |     sys.exit(mitmproxy())
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/_main.py", line 149, in mitmproxy
mitmproxy    |     run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/_main.py", line 133, in run
mitmproxy    |     master.run()
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 206, in run
mitmproxy    |     self.window = window.Window(self)
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 149, in __init__
mitmproxy    |     WindowStack(master, "flowlist"),
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 57, in __init__
mitmproxy    |     commands = commands.Commands(master),
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/commands.py", line 132, in __init__
mitmproxy    |     oh = CommandHelp(master)
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/commands.py", line 108, in __init__
mitmproxy    |     super().__init__(self.widget(""))
mitmproxy    |   File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/commands.py", line 120, in widget
mitmproxy    |     [urwid.Text(i) for i in textwrap.wrap(txt, cols)]
mitmproxy    |   File "/usr/lib/python3.6/textwrap.py", line 379, in wrap
mitmproxy    |     return w.wrap(text)
mitmproxy    |   File "/usr/lib/python3.6/textwrap.py", line 354, in wrap
mitmproxy    |     return self._wrap_chunks(chunks)
mitmproxy    |   File "/usr/lib/python3.6/textwrap.py", line 248, in _wrap_chunks
mitmproxy    |     raise ValueError("invalid width %r (must be > 0)" % self.width)
mitmproxy    | ValueError: invalid width 0 (must be > 0)
mitmproxy exited with code 1
```

**Comment by sixcorners** [comment]
I don't think docker-compose up lets mitmproxy look at the width of your terminal.
I too am trying to start mitmproxy then attach to it later but it doesn't look like it's possible.
