### ISSUE TITLE
Included pyopenssl version not working - pkg_resources.DistributionNotFound: The 'pyOpenSSL<17.4,>=17.3' distribution was not found and is required by mitmproxy

### ISSUE THREAD

**Issue by victorhooi** [mitmproxy/mitmproxy#2590]
##### Steps to reproduce the problem:

1. Install mitmproxy (HEAD - dd9f1b2) using homebrew on OSX
2. Run "mitmweb"

##### Any other comments? What have you tried so far?

I just tried install mitmproxy using:
```
brew install --HEAD mitmproxy
```

However, when I try to run it, it's complaining about the pyopenssl version - however, my understanding is that this is included with mitmproxy:

```
victorhooi@victorhooi-macbookpro ~> mitmproxy --version
Traceback (most recent call last):
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 16.2.0 (/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages), Requirement.parse('pyOpenSSL<17.4,>=17.3'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/victorhooi/homebrew/bin/mitmproxy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/victorhooi/homebrew/Cellar/mitmproxy/HEAD-dd9f1b2_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyOpenSSL<17.4,>=17.3' distribution was not found and is required by mitmproxy
```

##### System information

I'm on HEAD - version dd9f1b2fad19a793481de842e9e6c2de3d46adde (dd9f1b2)

This is on OSX 10.12.6, with Python 3.6.3.

**Comment by mhils** [comment]
pyOpenSSL is included in our prebuilt binaries, but if you use Homebrew that will take care of installing it. In other words, this'd need an update of the homebrew formula, which likely would break the current stable. Long story short, if you want HEAD, I'd recommend installing it using pip into your own virtualenv.
