### ISSUE TITLE
UnicodeError: label too long

### ISSUE THREAD

**Issue by sc911** [mitmproxy/mitmproxy#2625]
##### Steps to reproduce the problem:

1. Two Virtual-Box-VMs, Host: Win 8.1, Client: Win 10, ProxyVM: Ubuntu 16.04.3 LTS
2. Followed this guide: http://docs.mitmproxy.org/en/stable/tutorials/transparent-dhcp.html
3. As I want to capture traffic of a specific app I added the following entries to ip tables
`-A PREROUTING -i enp0s8 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8888`
`-A PREROUTING -i enp0s8 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 8888`
`-A PREROUTING -i enp0s8 -p tcp -m tcp --dport 8080 -j REDIRECT --to-ports 8888`
`-A PREROUTING -i enp0s8 -p tcp -m tcp --dport 8081 -j REDIRECT --to-ports 8888`
4. Starting `mitmdump -T --insecure -p 8888 -w dumpfile`
5. Opening a browser and surfing works as expected
6. On Opening the app mitmproxy throws this:
```
192.168.3.62:49847: clientconnect
192.168.3.62:49847: Certificate Verification Error for XXX.XXX.XXX.XXX:8080: hostname 'no-hostname' doesn't match 'XXXXXXXXXX'
192.168.3.62:49847: Ignoring server verification error, continuing with connection
192.168.3.62:49847: Traceback (most recent call last):
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/encodings/idna.py", line 167, in encode
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 119, in handle
  File "mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 376, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 462, in _establish_tls_with_client_and_server
  File "mitmproxy/proxy/protocol/tls.py", line 466, in _establish_tls_with_client
  File "mitmproxy/proxy/protocol/tls.py", line 583, in _find_cert
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)

Traceback (most recent call last):
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/encodings/idna.py", line 167, in encode
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 119, in handle
  File "mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 376, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 462, in _establish_tls_with_client_and_server
  File "mitmproxy/proxy/protocol/tls.py", line 466, in _establish_tls_with_client
  File "mitmproxy/proxy/protocol/tls.py", line 583, in _find_cert
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.3.62:49847: clientdisconnect

```

##### System information
```
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.4.0-87-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid
```

**Comment by sc911** [comment]
OK, using sslsplit I found that all messages are Remote Invocations of Spring Framework. Nothing near to http...
