### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#2632]
##### Steps to reproduce the problem:

1. Random Error when working with a Samsung device

```
 Cannot parse Client Hello: TlsProtocolException('Cannot read raw Client Hello: TlsProtocolException(\'Unexpected EOF in TLS handshake: b"\\\\x01\\\\x00\\\\x01\\\\xfc\\\\x03\\\\x03\\\\x16\\\\xc8\\\\xca\\\\x11\\\\x80\\\\x8a\\\\x87\\\\x80\\\\x98{S_d)p\\\\xb4\\\\x97f\\\\xaeJ}\\\\x94\\\\xcew\\\\x9b\\\\\\\\\\\\xee\\\\x8en\\\\x0e\\\\x0c\\\\x1b \\\\xad\\\\xc6!l\\\\xfeD\\\\x04\\\\x00\\\\n\\\\x8f+_ t\\\\xf8\\\\xc2\\\\xb9\\\\xab\\\'4\\\\xf9\\\\xa1\\\\xd9\\\\xea\\\\xc6\\\\x16d\\\\xea\\\\x1b\\\\x8a\\\\x8e\\\\xdf\\\\x00(\\\\xc0+\\\\xc0,\\\\xcc\\\\xa9\\\\xc0/\\\\xc00\\\\xcc\\\\xa8\\\\x00\\\\x9e\\\\x00\\\\x9f\\\\xc0\\\\t\\\\xc0\\\\n\\\\xc0\\\\x13\\\\xc0\\\\x14\\\\x003\\\\x009\\\\x00\\\\x9c\\\\x00\\\\x9d\\\\x00/\\\\x005\\\\xc0\\\\x11\\\\x00\\\\x05\\\\x01\\\\x00\\\\x01\\\\x8b\\\\xff\\\\x01\\\\x00\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x14\\\\x00\\\\x12\\\\x00\\\\x00\\\\x0fmail.mail01.org\\\\x00\\\\x17\\\\x00\\\\x00\\\\x00#\\\\x00\\\\xb0\\\\xe8B\\\\xe8\\\\x03BX\\\\x8c\\\\xd1\\\\x19\\\\x8f=\\\\x83\\\\xadO\\\\xa0+\\\\x98J\\\\xdfR\\\\xffD\\\\xc3\\\\xea/3\\\\xd4\\\\xf37e\\\\xa3\\\\xde\\\\x07\\\\x19\\\\xd0\\\\xdf\\\\xcd|\\\\xdf$\\\\xceA\\\\t.`\\\\x94\\\\xf0\\\\x0c\\\\xef\\\\xf8\\\\x97:\\\\xadpV\\\\x8e\\\\x04\\\\xb04\\\\xb9\\\\xcd\\\\xafA\\\\xce\\\\xf6\\\\xacbHk\\\\xb2\\\\\\\\\\\\x9f\\\\x19\\\\xac\\\\xbd\\\\xf60\\\\xeb\\\\xa3\\\\xd2x\\\\xf2\\\\x18\\\\xed{\\\\xa2\\\\x8b\\\\xec\\\\x1a\\\\xfc\\\\xf1E\\\\xe5\\\\x1e\\\\xc8\\\\xd7\\\\xf5]\\\\xed\\\\xed\\\\xb2}\\\\xa3\\\\x90h\\\\xc4\\\\x1a\\\\xcc\\\\xf2%\\\\xba\\\\xfa\\\\x0c\\\\xd3q\\\\xe2\\\\xc2\\\\xdc\\\'1\\\\xa4\\\\x8c\\\\xdc\\\\xa1}|Q\\\\xdf\\\\x8d\\\\x1b\\\\x90\\\\xd8>\\\\x032 \\\\x19\\\\nl\\\\xee\\\\x16\\\\xccC\\\\x81\\\\x96\\\\x842\\\\xcf\\\\xdb\\\\xe2*B\\\\xf6dk\\\\x9f\\\\x9c\\\\x9bvp\\\\x19\\\\xc67\\\\xaf\\\\xec#\\\\x82)\\\\xa2\\\\x183J\\\\x94\\\\x15\\\\x8bb\\\\x00\\\\r\\\\x00\\\\x16\\\\x00\\\\x14\\\\x06\\\\x01\\\\x06\\\\x03\\\\x05\\\\x01\\\\x05\\\\x03\\\\x04\\\\x01\\\\x04\\\\x03\\\\x03\\\\x01\\\\x03\\\\x03\\\\x02\\\\x01\\\\x02\\\\x03\\\\x00\\\\x10\\\\x00\\\\x0b\\\\x00\\\\t\\\\x08http/1.1\\\\x00\\\\x0b\\\\x00\\\\x02\\\\x01\\\\x00\\\\x00\\\\n\\\\x00\\\\x04\\\\x00\\\\x02\\\\x00\\\\x17\\\\x00\\\\x15\\\\x00{\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00"\',)',)
172.56.10.210:48383: Cannot parse Client Hello: TlsProtocolException('Cannot read raw Client Hello: TlsProtocolException(\'Unexpected EOF in TLS handshake: b"\\\\x01\\\\x00\\\\x01\\\\xfc\\\\x03\\\\x03\\\\x16\\\\xc8\\\\xca\\\\x11\\\\x80\\\\x8a\\\\x87\\\\x80\\\\x98{S_d)p\\\\xb4\\\\x97f\\\\xaeJ}\\\\x94\\\\xcew\\\\x9b\\\\\\\\\\\\xee\\\\x8en\\\\x0e\\\\x0c\\\\x1b \\\\xad\\\\xc6!l\\\\xfeD\\\\x04\\\\x00\\\\n\\\\x8f+_ t\\\\xf8\\\\xc2\\\\xb9\\\\xab\\\'4\\\\xf9\\\\xa1\\\\xd9\\\\xea\\\\xc6\\\\x16d\\\\xea\\\\x1b\\\\x8a\\\\x8e\\\\xdf\\\\x00(\\\\xc0+\\\\xc0,\\\\xcc\\\\xa9\\\\xc0/\\\\xc00\\\\xcc\\\\xa8\\\\x00\\\\x9e\\\\x00\\\\x9f\\\\xc0\\\\t\\\\xc0\\\\n\\\\xc0\\\\x13\\\\xc0\\\\x14\\\\x003\\\\x009\\\\x00\\\\x9c\\\\x00\\\\x9d\\\\x00/\\\\x005\\\\xc0\\\\x11\\\\x00\\\\x05\\\\x01\\\\x00\\\\x01\\\\x8b\\\\xff\\\\x01\\\\x00\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x14\\\\x00\\\\x12\\\\x00\\\\x00\\\\x0fmail.mail01.org\\\\x00\\\\x17\\\\x00\\\\x00\\\\x00#\\\\x00\\\\xb0\\\\xe8B\\\\xe8\\\\x03BX\\\\x8c\\\\xd1\\\\x19\\\\x8f=\\\\x83\\\\xadO\\\\xa0+\\\\x98J\\\\xdfR\\\\xffD\\\\xc3\\\\xea/3\\\\xd4\\\\xf37e\\\\xa3\\\\xde\\\\x07\\\\x19\\\\xd0\\\\xdf\\\\xcd|\\\\xdf$\\\\xceA\\\\t.`\\\\x94\\\\xf0\\\\x0c\\\\xef\\\\xf8\\\\x97:\\\\xadpV\\\\x8e\\\\x04\\\\xb04\\\\xb9\\\\xcd\\\\xafA\\\\xce\\\\xf6\\\\xacbHk\\\\xb2\\\\\\\\\\\\x9f\\\\x19\\\\xac\\\\xbd\\\\xf60\\\\xeb\\\\xa3\\\\xd2x\\\\xf2\\\\x18\\\\xed{\\\\xa2\\\\x8b\\\\xec\\\\x1a\\\\xfc\\\\xf1E\\\\xe5\\\\x1e\\\\xc8\\\\xd7\\\\xf5]\\\\xed\\\\xed\\\\xb2}\\\\xa3\\\\x90h\\\\xc4\\\\x1a\\\\xcc\\\\xf2%\\\\xba\\\\xfa\\\\x0c\\\\xd3q\\\\xe2\\\\xc2\\\\xdc\\\'1\\\\xa4\\\\x8c\\\\xdc\\\\xa1}|Q\\\\xdf\\\\x8d\\\\x1b\\\\x90\\\\xd8>\\\\x032 \\\\x19\\\\nl\\\\xee\\\\x16\\\\xccC\\\\x81\\\\x96\\\\x842\\\\xcf\\\\xdb\\\\xe2*B\\\\xf6dk\\\\x9f\\\\x9c\\\\x9bvp\\\\x19\\\\xc67\\\\xaf\\\\xec#\\\\x82)\\\\xa2\\\\x183J\\\\x94\\\\x15\\\\x8bb\\\\x00\\\\r\\\\x00\\\\x16\\\\x00\\\\x14\\\\x06\\\\x01\\\\x06\\\\x03\\\\x05\\\\x01\\\\x05\\\\x03\\\\x04\\\\x01\\\\x04\\\\x03\\\\x03\\\\x01\\\\x03\\\\x03\\\\x02\\\\x01\\\\x02\\\\x03\\\\x00\\\\x10\\\\x00\\\\x0b\\\\x00\\\\t\\\\x08http/1.1\\\\x00\\\\x0b\\\\x00\\\\x02\\\\x01\\\\x00\\\\x00\\\\n\\\\x00\\\\x04\\\\x00\\\\x02\\\\x00\\\\x17\\\\x00\\\\x15\\\\x00{\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00"\',)',)
 Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/protocol/http1.py", line 72, in __call__
    layer()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/protocol/http.py", line 257, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/proxy/protocol/tls.py", line 365, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'
```

##### Any other comments? What have you tried so far?
Nothing yet, but looking into the problem. Figure I send in the log

##### System information
Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.3
Platform: Linux-4.10.0-38-generic-x86_64-with-Ubuntu-17.04-zesty
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 17.04 zesty

**Comment by Kriechi** [comment]
This should be fixed in git-master and v3.0.0rc1.
