### ISSUE TITLE
Fresh Kali Install - ImportError: cannot import name 'UBInt16'

### ISSUE THREAD

**Issue by Drakota** [mitmproxy/mitmproxy#2648]
##### Steps to reproduce the problem:

1. Install newest Kali Linux
2. apt-get update && apt-get dist-upgrade
3. Try to open mitmproxy
4. Gets an error 
```
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 11, in <module>
    load_entry_point('mitmproxy==2.0.2', 'console_scripts', 'mitmproxy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/main.py", line 12, in <module>
    from mitmproxy.tools import cmdline  # noqa
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/cmdline.py", line 10, in <module>
    from mitmproxy.addons import view
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/__init__.py", line 7, in <module>
    from mitmproxy.addons import onboarding
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboardingapp/app.py", line 8, in <module>
    from mitmproxy.proxy import config
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/__init__.py", line 2, in <module>
    from .root_context import RootContext
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/root_context.py", line 3, in <module>
    from mitmproxy.proxy import protocol
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/__init__.py", line 39, in <module>
    from .tls import TlsClientHello
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 7, in <module>
    from mitmproxy.contrib import tls_parser
  File "/usr/lib/python3/dist-packages/mitmproxy/contrib/tls_parser.py", line 8, in <module>
    from construct import (Array, Bytes, Struct, UBInt16, UBInt32, UBInt8, PascalString, Embed, TunnelAdapter, GreedyRange, Switch, OptionalGreedyRange, Optional)
ImportError: cannot import name 'UBInt16'
```
##### Any other comments? What have you tried so far?
Reinstalling pip with easy_install

##### System information
Kali Linux 2017.3

mitmproxy 2.0.2

**Comment by Kriechi** [comment]
Thanks for you bug report!

We are not maintaining or involved in any way with the Kali Linux repositories. It seems like your construct package  is incompatible with mitmproxy 2.0.2. See https://github.com/mitmproxy/mitmproxy/commit/33689c6b2d2373279ec9ca7bbdef75319d1d1d9c

In mitmproxy on git-master we already removed the construct dependancy to avoid this issue. See https://github.com/mitmproxy/mitmproxy/pull/2353
