### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by ichux** [mitmproxy/mitmproxy#2657]
##### Steps to reproduce the problem:
```
ichux@ubuntu:~$ mitmproxy 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 48, in decode
    decoded = custom_decode[encoding](encoded)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 118, in decode_gzip
    return gfile.read()
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/export.py", line 82, in python_code
    writearg("json", json.loads(flow.request.text))
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/message.py", line 195, in get_text
    content = self.get_content(strict)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/message.py", line 97, in get_content
    content = encoding.decode(self.raw_content, ce)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 61, in decode
    repr(e),
ValueError: EOFError when decoding b'\x1f\x8b with 'gzip': EOFError('Compressed file ended before the end-of-stream marker was reached',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 48, in decode
    decoded = custom_decode[encoding](encoded)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 118, in decode_gzip
    return gfile.read()
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/local/lib/python3.5/dist-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 155, in keypress
    return self.master.ab.keypress(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 108, in keypress
    self.prompt_execute(k)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 133, in prompt_execute
    msg = p(txt)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 31, in __call__
    return self.callback(txt, *self.args)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/common.py", line 328, in export_to_clip_or_file
    writer(exporter(flow))
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/export.py", line 84, in python_code
    writearg("data", flow.request.content)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/message.py", line 97, in get_content
    content = encoding.decode(self.raw_content, ce)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/http/encoding.py", line 61, in decode
    repr(e),
ValueError: EOFError when decoding b'\x1f\x8b with 'gzip': EOFError('Compressed file ended before the end-of-stream marker was reached',)

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### Any other comments? What have you tried so far?
I wanted to save to a python file with the _E_ command but since the request contained bytes, the whole thing crashed.

##### System information

```
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-103-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
```

**Comment by mhils** [comment]
Thanks for the report. We removed the Python export for the upcoming release (https://github.com/mitmproxy/mitmproxy/issues/2465), so this is no longer relevant. Thanks anyway!
