### ISSUE TITLE
UnicodeEncodeError visiting some random websites

### ISSUE THREAD

**Issue by StevenVanAcker** [mitmproxy/mitmproxy#2723]
##### Steps to reproduce the problem:

1. start mitmdump with default parameters
2. point your browser through it
3. visit http://www.priceminister.com/

mitmdump crashes with:
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 9, in <module>
    load_entry_point('mitmproxy==2.0.2', 'console_scripts', 'mitmdump')()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/main.py", line 126, in mitmdump
    master.run()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/dump.py", line 69, in run
    super().run()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/master.py", line 84, in run
    self.tick(0.1)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/master.py", line 109, in tick
    handle_func(obj)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addonmanager.py", line 90, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 224, in response
    self.echo_flow(f)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 203, in echo_flow
    self._echo_response_line(f)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 192, in _echo_response_line
    self.echo(line)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 54, in echo
    click.secho(text, file=self.outfp, **style)
  File "/usr/local/lib/python3.5/dist-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.5/dist-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 58: ordinal not in range(128)

##### Any other comments? What have you tried so far?

the issue can be resolved by setting the PYTHONIOENCODING env var to "utf8", but it would be nicer if the crash didn't happen ;)

##### System information

Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.2
Platform: Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

I use the 2.0.x branch from github

**Comment by Kriechi** [comment]
Thanks for the bug report.
I just tested this with the latest git-master - and this error seems to be fixed.
