### ISSUE TITLE
mitmproxy crashed when press D

### ISSUE THREAD

**Issue by qingyunha** [mitmproxy/mitmproxy#2726]
##### Steps to reproduce the problem:

1. start mitmproxy, make some request
2. press Shift-d or D 
3.
```
Traceback (most recent call last):
  File "mitmproxy/tools/console/master.py", line 281, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 719, in _loop
  File "site-packages/urwid/raw_display.py", line 393, in <lambda>
  File "site-packages/urwid/raw_display.py", line 493, in parse_input
  File "site-packages/urwid/main_loop.py", line 403, in _update
  File "site-packages/urwid/main_loop.py", line 503, in process_input
  File "mitmproxy/tools/console/window.py", line 84, in keypress
  File "site-packages/urwid/container.py", line 1128, in keypress
  File "mitmproxy/tools/console/flowlist.py", line 417, in keypress
  File "site-packages/urwid/listbox.py", line 987, in keypress
  File "site-packages/urwid/listbox.py", line 939, in make_cursor_visible
  File "mitmproxy/tools/console/flowlist.py", line 284, in get_focus
  File "mitmproxy/tools/console/flowlist.py", line 123, in __init__
  File "mitmproxy/tools/console/flowlist.py", line 132, in get_text
  File "mitmproxy/tools/console/common.py", line 427, in format_flow
AttributeError: 'NoneType' object has no attribute 'state'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### System information

Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.11.3-1-ARCH-x86_64-with-arch-Arch-Linux
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: arch Arch Linux

**Comment by ujjwal96** [comment]
Thanks for the bug report but this issue is already fixed on master.
