### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by bobotay** [mitmproxy/mitmproxy#273]
My system info:

```
Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AM D64)] on win32
```

Got this error after command "pip install mitmproxy":

```
Downloading/unpacking mitmproxy
  Running setup.py (path:C:\Users\[EXCLUDED]\AppData\Local\Temp\pip_build_[EXCLUDED]\mit
mproxy\setup.py) egg_info for package mitmproxy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\isaiah\AppData\Local\Temp\pip_build_isaiah\mitmproxy\setup.
py", line 74, in <module>
        long_description = file(os.path.join(pdir(), "README.txt")).read()
    NameError: name 'file' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\[EXCLUDED]\AppData\Local\Temp\pip_build_[EXCLUDED]\mitmproxy\setup.py",
 line 74, in <module>

    long_description = file(os.path.join(pdir(), "README.txt")).read()

NameError: name 'file' is not defined

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\[EXCLUDED]\App
Data\Local\Temp\pip_build_[EXCLUDED]\mitmproxy
Storing debug log for failure in C:\Users\[EXCLUDED]\pip\pip.log
```

**Comment by JPS46225** [comment]
Hi Max (mhils)

I was just reading your comment about mitmproxy only being supported up to Python 2.7. I was wondering whether this was still the case, or if it had been updated to support the latest Python release?
