### ISSUE TITLE
Replacement Addon does not handle invalid encoding gracefully

### ISSUE THREAD

**Issue by AntiverX** [mitmproxy/mitmproxy#2734]
```
Traceback (most recent call last):
  File "mitmproxy/net/http/encoding.py", line 50, in decode
LookupError: unknown encoding: gzip,rc4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "specs/mitmdump", line 3, in <module>
  File "mitmproxy/tools/main.py", line 126, in mitmdump
  File "mitmproxy/tools/dump.py", line 69, in run
  File "mitmproxy/master.py", line 84, in run
  File "mitmproxy/master.py", line 109, in tick
  File "mitmproxy/controller.py", line 70, in wrapper
  File "mitmproxy/addonmanager.py", line 90, in __call__
  File "mitmproxy/addonmanager.py", line 85, in invoke
  File "mitmproxy/addons/replace.py", line 93, in response
  File "mitmproxy/addons/replace.py", line 83, in execute
  File "mitmproxy/addons/replace.py", line 112, in replace
  File "mitmproxy/net/http/message.py", line 261, in replace
  File "mitmproxy/net/http/message.py", line 97, in get_content
  File "mitmproxy/net/http/encoding.py", line 61, in decode
ValueError: LookupError when decoding b'\x1f\x8b with 'gzip,rc4': LookupError('unknown encoding: gzip,rc4',)
Failed to execute script mitmdump
```

**Comment by Kriechi** [comment]
Which operating system and mitmproxy version are you running?
Paste the output of "mitmproxy --version" here. 

When did this occur? Did you visit a specific website? Which actions did you take before this?

**Comment by AntiverX** [comment]
Ubuntu 17.10

Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.13.0-21-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid

I use the following command to redirct my traffic using port 80 to 8080
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner antiver --dport 80 -j REDIRECT --to-port 8080
and rum mitmdump to repalace something.

I'm not sure which site cause the problem, because much traffic go throught mitmdump. It breaks down after some time ,perhaps half of  a day.

Is there any way to log the site which cause the error? So I can give you more deatail.

Thanks。

**Comment by AntiverX** [comment]
I'm trying to collect the output. If that happens again ,I will inform you.
Thanks.

**Comment by AntiverX** [comment]
@Kriechi Hi, I have get the log file.

[case1.txt](https://github.com/mitmproxy/mitmproxy/files/1594436/case1.txt)
[case2.txt](https://github.com/mitmproxy/mitmproxy/files/1594437/case2.txt)

**Comment by AntiverX** [comment]
here is a similar quesiton

https://stackoverflow.com/questions/31730474/why-cant-i-decode-the-zhihu-com-response-using-urllib-request-urlopenurl-read

**Comment by mhils** [comment]
Thanks for the detailed report. Whatever website is causing this does misbehave - "rc4" is an (insecure) encryption mechanism and not an encoding scheme. We can't really do much on this front. What we should however do is fix the traceback in the replacement addon, that should not happen.

**Comment by dweinstein** [comment]
just to add to the list of "weird encodings", I've also seen `gzip, deflate` as another

**Comment by mhils** [comment]
This should be fixed now, thanks again!
