### ISSUE TITLE
Mitmproxy crashes, when trying to export the flow in the folder with incorrect path

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2750]
##### Steps to reproduce the problem:

1. Run mitmproxy without root privileges.
2. Start intercepting something.
3. Choose any flow.
4. Press `e`. Choose a part of the flow - `cookies` for example. 
5. Press `w` to save `cookies`.
6. Try to save `cookies` to the directory which requires only root permissions.

I am getting:
```
Traceback (most recent call last):
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/master.py", line 216, in run
    self.loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/window.py", line 318, in keypress
    k = super().keypress(size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/statusbar.py", line 149, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/statusbar.py", line 104, in keypress
    self.prompt_execute(self._w.get_value())
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/statusbar.py", line 124, in prompt_execute
    msg = p(txt)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 17, in __call__
    ret = self.master.commands.call(cmd)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 221, in call
    return self.call_args(parts[0], parts[1:])
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 212, in call_args
    return self.commands[path].call(args)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 101, in call
    ret = self.func(*pargs)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 251, in wrapper
    return function(*args, **kwargs)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/consoleaddons.py", line 463, in grideditor_save
    with open(path, "w", newline='', encoding="utf8") as fp:
PermissionError: [Errno 13] Permission denied: '/file.txt'
```

##### System information
Mitmproxy: 3.0.0.dev1101 (commit d9d4d15) binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-104-generic-x86_64-with-debian-stretch-sid

**Comment by kajojify** [comment]
**A little update.**
All exceptions, that Python `open()` function can produce because of incorrect path are relevant to this issue. To break Mitmproxy with `IsADirectoryError` just input "\/" in 6th step:
```
Traceback (most recent call last):
  File "mitmproxy/tools/console/master.py", line 216, in run
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 719, in _loop
  File "site-packages/urwid/raw_display.py", line 393, in <lambda>
  File "site-packages/urwid/raw_display.py", line 493, in parse_input
  File "site-packages/urwid/main_loop.py", line 403, in _update
  File "site-packages/urwid/main_loop.py", line 503, in process_input
  File "mitmproxy/tools/console/window.py", line 293, in keypress
  File "site-packages/urwid/container.py", line 1116, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 149, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 104, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 124, in prompt_execute
  File "mitmproxy/tools/console/commandexecutor.py", line 17, in __call__
  File "mitmproxy/command.py", line 221, in call
  File "mitmproxy/command.py", line 212, in call_args
  File "mitmproxy/command.py", line 101, in call
  File "mitmproxy/command.py", line 251, in wrapper
  File "mitmproxy/tools/console/consoleaddons.py", line 463, in grideditor_save
IsADirectoryError: [Errno 21] Is a directory: '\\/'
```

**Comment by kajojify** [comment]
@Kriechi I have just found two more places in mitmproxy with the same file exceptions. Do I have to open new issue or we can leave it for this (I will write an update here then).

**Comment by kira0204** [comment]
@kajojify What are those two places where you found the exceptions, just curious

**Comment by kajojify** [comment]
@kira0204 #2783 
PR was created for this issue https://github.com/mitmproxy/mitmproxy/pull/2761
I am waiting for the guy, that was working on it :)

**Comment by kajojify** [comment]
Working on it.

**Comment by kajojify** [comment]
Closed in https://github.com/mitmproxy/mitmproxy/pull/2809
