### ISSUE TITLE
Editing set-cookie attributes crashes mitmproxy

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2753]
##### Steps to reproduce the problem:

1. Create a flow with response and edit its set-cookies
2. Press enter on the Attributes column.

```
Traceback (most recent call last):
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/master.py", line 216, in run
    self.loop.run()
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/user/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/user/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 303, in keypress
    k
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/keymap.py", line 130, in handle
    return self.executor(b.command)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 17, in __call__
    ret = self.master.commands.call(cmd)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 221, in call
    return self.call_args(parts[0], parts[1:])
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 212, in call_args
    return self.commands[path].call(args)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 101, in call
    ret = self.func(*pargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 251, in wrapper
    return function(*args, **kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/consoleaddons.py", line 174, in nav_select
    self.master.inject_key("m_select")
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/master.py", line 181, in inject_key
    self.loop.process_input([key])
  File "/home/user/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 299, in keypress
    k = super().keypress(size, k)
  File "/home/user/venv/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/user/venv/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 36, in keypress
    ret = super().keypress(size, key)
  File "/home/user/venv/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/grideditor/base.py", line 356, in keypress
    elif column.keypress(key, self) and not self.handle_key(key):
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/grideditor/col_subgrid.py", line 30, in keypress
    editor.master.view_grideditor(
AttributeError: 'ConsoleMaster' object has no attribute 'view_grideditor'
```

##### System information

Mitmproxy: 3.0.0.dev0002 (commit 299df48)
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial

**Comment by ankitsaini2609** [comment]
I have found where the bug lies, Probably `'view_grideditor'` function is not included in `ConsoleMaster` class.
`view_grideditor` function is present in released version2.0.2:- [check here](https://github.com/mitmproxy/mitmproxy/blob/2.0.x/mitmproxy/tools/console/master.py#L333)
While `view_grideditor` function in not included in development version [check here](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/master.py)
Am I on the right path?

**Comment by kajojify** [comment]
It seems I fixed it, but another (I suppose, not related) problem appeared - if I edit attributes, the result won't be saved. Continue working on it. 
@ankitsaini2609 Sorry, I didn't warn, that I was working on it. When I started to work on this issue, almost nobody were working on issues, so there was no any point to say "working on it".

**Comment by ankitsaini2609** [comment]
@kajojify  kindly comment on all the issues in which you are working immediately so other people know that, yes you are working on that issues and you had to tell me that you are working on that issue, a warning is something different and how would you know that nobody was working on that issue?

**Comment by kajojify** [comment]
@ankitsaini2609 again, I am sorry. It won't be happened again. 
If you want, you can take this one. It will be fair, I think :)

**Comment by ankitsaini2609** [comment]
@kajojify no problem, you can work on it since you already solved half of the problem. :)

**Comment by kajojify** [comment]
**Update**
While working on this issue, I found a new bug. 
If we edit any part of flow in grideditor and then decide to enter Help tab (or any other) by pressing `ctrl+?`, all our editings won't be saved and will disappear.
I'll include the fix into my PR.
