### ISSUE TITLE
Binary (unicode) replacements will crash mitmproxy

### ISSUE THREAD

**Issue by M-DiMartino** [mitmproxy/mitmproxy#2801]
##### Steps to reproduce the problem:

1.  Add a regex replacement for responses (~s) with the regex containing unicode characters (for instance, '\u0020\u1200\u1234'). The replacement can be anything. Note how mitmproxy changes all the '\\' to a double one, thinking it is matching the '\\' itself.
2. If mitmproxy receives a response, it will crash with the message: 'bad escape \u at position 0'

##### Any other comments? What have you tried so far?
I have also tried to replace binary data by using '\x20\x12\x00\x12\x34'. This will also crash the application, although with a different error message.

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.3
Platform: Linux-4.9.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.1.0g  2 Nov 2017
Linux distro: Kali kali-rolling kali-rolling

#### Complete stack trace for using '\u0123' as replacement.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 239, in ticker
    changed = self.tick(timeout=0)
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 109, in tick
    handle_func(obj)
  File "/usr/lib/python3/dist-packages/mitmproxy/controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "/usr/lib/python3/dist-packages/mitmproxy/addonmanager.py", line 90, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/replace.py", line 93, in response
    self.execute(flow)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/replace.py", line 83, in execute
    self.replace(f.response, rex, s)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/replace.py", line 100, in replace
    obj.replace(rex, s, flags=re.DOTALL)
  File "/usr/lib/python3/dist-packages/mitmproxy/net/http/message.py", line 263, in replace
    pattern, repl, self.content, flags=flags, count=count
  File "/usr/lib/python3.6/re.py", line 202, in subn
    return _compile(pattern, flags).subn(repl, string, count)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \u at position 0

#### Complete stack trace for using '\x12\xe7' as replacement.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 239, in ticker
    changed = self.tick(timeout=0)
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 109, in tick
    handle_func(obj)
  File "/usr/lib/python3/dist-packages/mitmproxy/controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "/usr/lib/python3/dist-packages/mitmproxy/addonmanager.py", line 90, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/replace.py", line 93, in response
    self.execute(flow)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/replace.py", line 83, in execute
    self.replace(f.response, rex, s)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/replace.py", line 100, in replace
    obj.replace(rex, s, flags=re.DOTALL)
  File "/usr/lib/python3/dist-packages/mitmproxy/net/http/message.py", line 257, in replace
    pattern = strutils.escaped_str_to_bytes(pattern)
  File "/usr/lib/python3/dist-packages/mitmproxy/utils/strutils.py", line 99, in escaped_str_to_bytes
    return codecs.escape_decode(data)[0]
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce7' in position 8: surrogates not allowed

**Comment by mhils** [comment]
Thanks! Can you please test if this still applies with the latest release candidate? Also, does it happen with _every_ flow, or only specific ones?

**Comment by cabreak2** [comment]
It happens with every flow.
I have tried it with mitmproxy 3.0.0 and it still shows the same error (although, it doesn't crash).

If I add the replacement:  _/~s/\x89\x88\x87/pqr_
After going out of the window, it will automatically convert it to  _['/~s/\udc89\udc89\udc87/pqr']_
which will result into an error when any response is received: _UnicodeEncodeError: 'utf-8' codec can't encode character '\udc89' in position 8: surrogates not allowed_

Not sure, but it seems like binary replacements are simply not supported.

**Comment by cabreak2** [comment]
Any additional information on triaging the issue ?

**Comment by mhils** [comment]
Thanks for the heads-up. Issue description is clear I think, we just need to get to the bottom of it and find a fix. :-)

**Comment by Kriechi** [comment]
fixed by #3486
