### ISSUE TITLE
AttributeError: 'module' object has no attribute '_lib'

### ISSUE THREAD

**Issue by Kr0nZ** [mitmproxy/mitmproxy#281]
Not sure why this is happening, mitmproxy was working fine previously but now it just fails with this error msg. I haven't updated or changed anything, I even tried updating mitmproxy using (sudo pip install --upgrade mitmproxy) but I still get same msg

<pre>
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 43, in <module>
    config = process_proxy_options(parser, options)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/config.py", line 107, in process_proxy_options
    certforward = options.certforward,
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/config.py", line 27, in __init__
    self.certstore = certutils.CertStore.from_store(self.confdir, CONF_BASENAME)
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 153, in from_store
    dh = klass.load_dhparam(dhp)
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 133, in load_dhparam
    bio = OpenSSL.SSL._lib.BIO_new_file(path, b"r")
AttributeError: 'module' object has no attribute '_lib'
</pre>

**Comment by julianharty** [comment]
FWIW I had a similar problem on my Windows 7 64-bit workstation where _lib wasn't found.
I had OpenSSL version 0.15.1

    python -c "import os, inspect, OpenSSL; print OpenSSL.__version__,  '\n', dir(OpenSSL.SSL)"

My fix was to uninstall mitmproxy and pyopenssl using pip and then force the reinstall after I renamed the OpenSSL directory/folder in site-packages (I actually used Windows Explorer, I've faked the command line rename command to indicate what I did)

    pip uninstall mitmproxy pyopenssl
    ren C:\Python27\Lib\site-packages\OpenSSL C:\Python27\Lib\site-packages\_OpenSSL
    pip install --no-deps --force-reinstall --upgrade -I mitmproxy pyopenssl
