### ISSUE TITLE
Crash just by being used as a proxy. 

### ISSUE THREAD

**Issue by eldraco** [mitmproxy/mitmproxy#2815]
##### Steps to reproduce the problem:
Not sure if possible.

1. start mitmproxy
2. someone connected and used the proxy and triggered the error
3.

##### Any other comments? What have you tried so far?
Output of mitmproxy error

Traceback (most recent call last): in HTTP connection: TcpDisconnect('[Errno 104] Connection reset by peer',)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 242, in ticker
    self.loop.set_alarm_in(0.01, self.ticker)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 165, in set_alarm_in
    return self.event_loop.alarm(sec, cb)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 604, in alarm
    heapq.heappush(self._alarms, (tm, callback))
TypeError: unorderable types: function() < function()

mitmproxy has crashed!

##### System information
Python version: 3.5.3
Platform: Linux-4.12.0-1-amd64-x86_64-with-debian-buster-sid
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: debian buster/sid

**Comment by mhils** [comment]
Thanks for the report. Is that happening consistently, or a random crash? Which urwid version are you using (you can see that using `pip freeze`)?

**Comment by eldraco** [comment]
No. One-time Crash.

urwid==1.3.1

**Comment by mhils** [comment]
Thanks for the speedy reply. You're running into https://github.com/urwid/urwid/issues/246 here, which should be fixed with the latest urwid release. We'll bump the minimum requirement for mitmproxy!
