### ISSUE TITLE
mitmproxy crushes when duplicating flow

### ISSUE THREAD

**Issue by pannzh** [mitmproxy/mitmproxy#2844]
##### Steps to reproduce the problem:

1.  Start mitmproxy as regular mode
2.  Client use it as http_proxy
3.  Select the flow and press 'D' (duplicate flow), and mitmproxy throws following exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 987, in keypress
    self.make_cursor_visible((maxcol,maxrow))
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 939, in make_cursor_visible
    focus_widget, pos = self.body.get_focus()
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/flowlist.py", line 284, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/flowlist.py", line 123, in __init__
    w = self.get_text()
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/flowlist.py", line 132, in get_text
    max_url_len=cols,
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/common.py", line 427, in format_flow
    acked = f.reply.state == "committed",
AttributeError: 'NoneType' object has no attribute 'state'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### System information

I was using the latest docker images and here is the output of  `mitmproxy --version`:
```
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-4.9.0-4-amd64-x86_64-with
SSL version: OpenSSL 1.0.2n  7 Dec 2017
```

**Comment by mhils** [comment]
Thanks. I believe this is already fixed on master and the 3.0 release candidates, feel free to re-open if that's not the case.
