### ISSUE TITLE
Mitmproxy crashes, when we try to set 'true' for add_upstream_certs_to_client_chain option

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2876]
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Press `O` to enter Options tab. 
3. Press `Enter` to set `true` for `add_upstream_certs_to_client_chain` option.

You will see traceback:
```
Traceback (most recent call last):
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/master.py", line 216, in run
    self.loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/window.py", line 313, in keypress
    k
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/keymap.py", line 130, in handle
    return self.executor(b.command)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 17, in __call__
    ret = self.master.commands.call(cmd)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 221, in call
    return self.call_args(parts[0], parts[1:])
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 212, in call_args
    return self.commands[path].call(args)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 101, in call
    ret = self.func(*pargs)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/command.py", line 251, in wrapper
    return function(*args, **kwargs)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/consoleaddons.py", line 175, in nav_select
    self.master.inject_key("m_select")
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/master.py", line 181, in inject_key
    self.loop.process_input([key])
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/options.py", line 281, in keypress
    return self.focus_item.keypress(tsize, key)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/options.py", line 194, in keypress
    self.master.options.toggler(foc.opt.name)()
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/optmanager.py", line 238, in toggle
    setattr(self, attr, not getattr(self, attr))
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/optmanager.py", line 171, in __setattr__
    self.update(**{attr: value})
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/optmanager.py", line 210, in update
    u = self.update_known(**kwargs)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/optmanager.py", line 206, in update_known
    self.changed.send(self, updated=updated)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/proxy/config.py", line 52, in configure
    "The verify-upstream-cert requires certificate verification to be disabled. "
mitmproxy.exceptions.OptionsError: The verify-upstream-cert requires certificate verification to be disabled. If upstream certificates are verified then extra upstream certificates are not available for inclusion to the client chain.
```

##### Any other comments? What have you tried so far?

If we set `true` for `ssl_insecure` option, we will be able to set `true` for `add_upstream_certs_to_client_chain` option successfully.

##### System information

Mitmproxy: 3.0.0.dev113 (commit 93425d4) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by fenilgandhi** [comment]
This is due to a predefined check in if condition. Now either we can set both set to true when `add_upstream_certs_to_client_chain` or gracefully handle the error and decline changing the value untill `ssl_insecure` is also not true.
[https://github.com/mitmproxy/mitmproxy/blob/3934dbb5ad6bf69fd22f682a74b2933874f9f01f/mitmproxy/proxy/config.py#L50](url)
>```python 
>if options.add_upstream_certs_to_client_chain and not options.ssl_insecure:
 >   raise exceptions.OptionsError(
 >       "The verify-upstream-cert requires certificate verification to be disabled. "
 >       "If upstream certificates are verified then extra upstream certificates are "
 >       "not available for inclusion to the client chain."
 >   )

```

**Comment by mhils** [comment]
> or gracefully handle the error and decline changing the value 

This is the correct way. Implicitly disabling TLS certificate verification would be a bad idea.

**Comment by fenilgandhi** [comment]
Ok thanks, i will take that path.
