### ISSUE TITLE
OSError: Binding to 'localhost' is prohibited. Please use '::1' or '127.0.0.1' directly.

### ISSUE THREAD

**Issue by GHXST01** [mitmproxy/mitmproxy#2967]
```
C:\Users\Admin>mitmweb
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mitmproxy\proxy\server.py", line 46, in __init__
    (config.options.listen_host, config.options.listen_port)
  File "c:\program files\python36\lib\site-packages\mitmproxy\net\tcp.py", line 559, in __init__
    raise socket.error("Binding to 'localhost' is prohibited. Please use '::1' or '127.0.0.1' directly.")
OSError: Binding to 'localhost' is prohibited. Please use '::1' or '127.0.0.1' directly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\mitmweb.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\mitmproxy\tools\main.py", line 164, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "c:\program files\python36\lib\site-packages\mitmproxy\tools\main.py", line 97, in run
    server = proxy.server.ProxyServer(pconf)
  File "c:\program files\python36\lib\site-packages\mitmproxy\proxy\server.py", line 51, in __init__
    if self.socket:
AttributeError: 'ProxyServer' object has no attribute 'socket'
```

As the error suggests, localhost should be replaced with 127.0.0.1 .
This is in the latest version 3.0.3

**Comment by GHXST01** [comment]
Edit: Found out the 'localhost' was coming from the `config.yaml` file in `.mitmproxy`.
Maybe reminiscent from an older version?

**Comment by Kriechi** [comment]
Please provide the important information we asked for in the issue template.
Which OS are you using? Which OS Version?
How did you install mitmproxy?
