### ISSUE TITLE
Crash when scrolling to last line of the flow

### ISSUE THREAD

**Issue by sebw** [mitmproxy/mitmproxy#2973]
##### Steps to reproduce the problem:

1. Open mitmproxy
2. Create some traffic
3. Try to scroll down to the last line of the "Flows" by using the "end" key on the keyboard

##### System information

```
./mitmproxy --version
Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.14.14-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
```

```
Traceback (most recent call last):
  File "mitmproxy/tools/console/master.py", line 225, in run
  File "site-packages/urwid/main_loop.py", line 286, in run
  File "site-packages/urwid/main_loop.py", line 384, in _run
  File "site-packages/urwid/main_loop.py", line 788, in run
  File "site-packages/urwid/main_loop.py", line 825, in _loop
  File "site-packages/urwid/raw_display.py", line 404, in <lambda>
  File "site-packages/urwid/raw_display.py", line 502, in parse_input
  File "site-packages/urwid/main_loop.py", line 411, in _update
  File "site-packages/urwid/main_loop.py", line 511, in process_input
  File "mitmproxy/tools/console/window.py", line 309, in keypress
  File "site-packages/urwid/container.py", line 1131, in keypress
  File "mitmproxy/tools/console/window.py", line 44, in keypress
  File "site-packages/urwid/container.py", line 1131, in keypress
  File "mitmproxy/tools/console/flowlist.py", line 87, in keypress
  File "site-packages/urwid/listbox.py", line 1025, in keypress
  File "site-packages/urwid/listbox.py", line 1035, in _keypress_max_right
AttributeError: 'FlowListWalker' object has no attribute 'positions'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

**Comment by kajojify** [comment]
Relevant traceback, when pressing `Home`.

**Comment by fenilgandhi** [comment]
I am working on a similar error. Maybe the fix will patch bug also.
Already on it.
