### ISSUE TITLE
Log message encode error

### ISSUE THREAD

**Issue by Gigiarum** [mitmproxy/mitmproxy#2979]
##### Steps to reproduce the problem:

1. Start mitmdump with this script
```
import base64

from mitmproxy import ctx
from mitmproxy.utils import strutils


def response(flow):
    ctx.log.info("url=[{}].".format(flow.request.url))

    mimeType = flow.response.headers.get('Content-Type', '')
    ctx.log.info("mimeType=[{}]".format(mimeType))

    if strutils.is_mostly_bin(flow.response.content):
        ctx.log.info("encoding=[base64]")
        text = base64.b64encode(flow.response.content).decode() # Store binary data as base64
    else:
        text = flow.response.get_text(strict=False)
    ctx.log.info("text=[{}]".format(text))
```
2. Connect to [this](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Soldatietiopia.jpg/150px-Soldatietiopia.jpg) url
3. This exception will throw when the script tries to print text to log
```
Addon error: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mitmproxy/addons/termlog.py", line 37, in log
    err=(e.level == "error")
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-40: ordinal not in range(128)
```

##### Any other comments? What have you tried so far?

It seems the problem is in the get_text function of Message class.

Same exception when you point to a url returned with mimeType "text/html; charset=ISO-8859-1".

##### System information

Mitmproxy: 3.0.3
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-3.16.0-5-amd64-x86_64-with-debian-8.9

I described partially the problem [here](https://discourse.mitmproxy.org/t/server-disconnected-on-redirect/868).

**Comment by Gigiarum** [comment]
New way to get the problem

##### Steps to reproduce the problem:

1. Start mitmdump with this script
```
from mitmproxy import ctx

def configure(updated):
    ctx.log.info("à è ì ò ù")
```
in an ANSI encoded file.

2. You will see this exception in console
```
Loading script: encoding_error.py
Addon error: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mitmproxy/addonmanager.py", line 67, in safecall
    yield
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mitmproxy/addons/script.py", line 77, in tick
    ns = load_script(self.fullpath)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mitmproxy/addons/script.py", line 30, in load_script
    loader.exec_module(m)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "encoding_error2.py", line 4
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe0 in position 0: invalid continuation byte
```

3. If the script file is converted in UTF-8 this exception will throw
```
Loading script: encoding_error2.py
Addon error: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mitmproxy/addons/termlog.py", line 37, in log
    err=(e.level == "error")
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 31: ordinal not in range(128)
```

**Comment by mhils** [comment]
Thanks for the reduced traceback - very helpful! I guess someone has to read through http://click.pocoo.org/5/python3/#python3-limitations and figure out what we are doing wrong. 😄

**Comment by cortesi** [comment]
This appears to be fixed in master - there's been a lot of change around the logging code. Please re-open if I'm missing something. 
<img width="487" alt="screen shot 2018-05-12 at 11 28 09" src="https://user-images.githubusercontent.com/22544/39950756-ca60cc64-55d7-11e8-861b-5f3dc6f511be.png">
