### ISSUE TITLE
Python H11 0.8.0 Breaks mitmproxy

### ISSUE THREAD

**Issue by Oliver-Fish** [mitmproxy/mitmproxy#3009]
##### Steps to reproduce the problem:

1. Upgrade from Python-h11-0.7.0 to 0.8.0

##### Any other comments? What have you tried so far?
After Upgrading I get the following error (Please note that 0.8.0 is now being pushed by Arch Linux Repos)

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (h11 0.8.0 (/usr/lib/python3.6/site-packages), Requirement.parse('h11~=0.7.0'), {'wsproto'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (h11 0.8.0 (/usr/lib/python3.6/site-packages), Requirement.parse('h11~=0.7.0'), {'wsproto'})

##### System information

Mitmproxy: 3.0.3 
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.15.11-1-ARCH-x86_64-with-arch

**Comment by Kriechi** [comment]
Not much we can do about this. Thats the reason why we have dependency management.

mitmproxy depends on `wsproto>=0.11.0`.
wsproto depends on `h11 ~= 0.7.0`.

I would recommend opening an issue with wsproto, or even better send PR to fix the incompatibility.
