### ISSUE TITLE
AttributeError: 'FlowListWalker' object has no attribute 'positions'

### ISSUE THREAD

**Issue by alxchk** [mitmproxy/mitmproxy#3030]
##### Steps to reproduce the problem:

1. Start mitmproxy (git master, all deps are up2date)
2. Record some traffic
3. Press "End" key

##### System information

Version: b5c3883b7886a73043b6cc292ce4a51066ca260a

```Traceback (most recent call last):
  File "/home/user/Software/network/mitmproxy/mitmproxy/tools/console/master.py", line 227, in run
    self.loop.run()
  File "/home/user/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/user/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/user/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/user/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/user/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/user/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/user/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/user/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/user/Software/network/mitmproxy/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/home/user/.local/lib/python3.6/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/user/Software/network/mitmproxy/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/home/user/.local/lib/python3.6/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/user/Software/network/mitmproxy/mitmproxy/tools/console/flowlist.py", line 87, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/home/user/.local/lib/python3.6/site-packages/urwid/listbox.py", line 1025, in keypress
    return actual_key(self._keypress_max_right())
  File "/home/user/.local/lib/python3.6/site-packages/urwid/listbox.py", line 1035, in _keypress_max_right
    self.focus_position = next(iter(self.body.positions(reverse=True)))
AttributeError: 'FlowListWalker' object has no attribute 'positions'
```

**Comment by cortesi** [comment]
Hi there. This is a bug that recently emerged in the Urwid library, which we rely on. Our honorary ambassador to the Urwid project - that's you, @kajojify - has opened an issue to track this here:

https://github.com/urwid/urwid/issues/294

I'm inclined at this point to either a) intercept and implement our own home/end  or b) look at what is needed to implement a `positions` method that Urwid will understand.

**Comment by fenilgandhi** [comment]
Same as #2973

**Comment by cortesi** [comment]
@fenilgandhi Right you are. We'll close this one as a dupe. Thanks for reporting @alxchk.
