### ISSUE TITLE
Getting "OSError: raw write() returned invalid length 2 (should have been between 0 and 1)"

### ISSUE THREAD

**Issue by YafimK** [mitmproxy/mitmproxy#3037]
Getting the following:
Traceback (most recent call last):
  File "mitmproxy\addons\dumper.py", line 218, in response
  File "mitmproxy\addons\dumper.py", line 190, in echo_flow
  File "mitmproxy\addons\dumper.py", line 138, in _echo_request_line
  File "mitmproxy\addons\dumper.py", line 48, in echo
  File "site-packages\click\termui.py", line 420, in secho
  File "site-packages\click\utils.py", line 259, in echo
  File "site-packages\click\_compat.py", line 577, in _safe_write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 175, in write_plain_text
OSError: raw write() returned invalid length 2 (should have been between 0 and 1)

##### Steps to reproduce the problem:
Record any site using mitmdump 3 on windows 10 November's creators update

##### System information
Mitmproxy: 3.0.0 binary
Python:    3.5.3
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Windows-10-10.0.16299

**Comment by YafimK** [comment]
Simple recording from browser using mitmdump
I found similiar bug reporting here - https://stackoverflow.com/questions/47356993/oserror-raw-write-returned-invalid-length-when-using-print-in-python

**Comment by Kriechi** [comment]
People in the SO thread seem to have success with upgrading to Python 3.6.
Since mitmproxy now requires py36, I think we can close this.

**Comment by YafimK** [comment]
Reproduced again on windows 10 creators update with python 3.6.5

> Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\dumper.py", line 218, in response
  File "mitmproxy\addons\dumper.py", line 190, in echo_flow
  File "mitmproxy\addons\dumper.py", line 138, in _echo_request_line
  File "mitmproxy\addons\dumper.py", line 48, in echo
  File "site-packages\click\termui.py", line 420, in secho
  File "site-packages\click\utils.py", line 259, in echo
  File "site-packages\click\_compat.py", line 577, in _safe_write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 175, in write_plain_text
OSError: raw write() returned invalid length 4 (should have been between 0 and 2)
