### ISSUE TITLE
Bug Report: Crash when reading application/gzip encoded file

### ISSUE THREAD

**Issue by Obaied** [mitmproxy/mitmproxy#3040]
##### Steps to reproduce the problem:

1. Setup Android with an SSL certificate and hook it up as a client on port 3223
2. `mitmproxy -p 3223`
3. Send a POST request with an application/gzip encoded body from the client (Android device) to a server
4. The POST request appears on mitmproxy. If I press enter on it, it crashes. Here's the crash log:

```
~/Desktop/test » mitmproxy -p 3223                                                                                                 ab@391232
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 225, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 816, in _loop
    self._entering_idle()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 777, in _entering_idle
    callback()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/listbox.py", line 501, in render
    canvas = widget.render((maxcol,))
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/widget.py", line 1004, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/canvas.py", line 1315, in apply_text_layout
    return TextCanvas(t, a, c, maxcol=maxcol)
  File "/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/site-packages/urwid/canvas.py", line 358, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified
146
[146, 147, 146, 94, 146, 140]
[b'an: .?........?Vm??8.?+(??Mj;/.?S?????e+]_.9?.?u??q?r???N??.?3?..?=?g?g????Fh?z?/????EE?\t??Z{s?.???.????xs0.m??;?m?cB?8?)?,??HC??.?..???<$?', b"?9?..gq??L.hD???Y?<.?H?..Q?'??,??t?R@?T^m??G?.b?R??4?/A)KPJ.?b?c<?.??.Fs<??.?0jEY??.?jmM?N^.=Y?5?m..??????CO????`... ??.???V?.;?BD?./f?I??o7???zzlL", b"]H%??h?..?;??X?{.7Tu??w.??F?..8@?.?JA?.?Ga?#???.g#/?B??x????@?>????<N?h?????gd|.T)..?.Yn'???.??A/?4w??.5F?sur????R#V??3?O??.?.,(A?Ae?=???B????N*>?", b"?.??.O??Ar!?=?k??h)?*zG?F>|}E..??/???N?o'?57??$@.??..?.?.}?\\?!??.?{.?q??cT??.f????v=?.??)T?`.?", b'??.?Y???u?.}?>1??y??\t??w?.??..tl?B??.?.8J9?k%?~?*E?u.h??8!?;?.?r]Q{\\I?`9???^qG.<C8qfX???DwJ?B.\\?V??x`..%(?^Y?.??B1??X.Y??Q??.DC?.t?i_??l?EPm?.~q??', b'???n???w?B?[?3u??r5??!r?]?u?DFyfd.?f\\?4W??,J?T{y.?7?$?.0Q?????k?.}.???W?(..:n?..Eu?A]G8?/.?<??bbO1?.?d.?..??u9?W?A??/v?.n??66?f?????.A?8<|..']

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### System information

```
Mitmproxy: 3.0.3
Python:    3.6.5
OpenSSL:   OpenSSL 1.0.2o  27 Mar 2018
Platform:  Darwin-17.4.0-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Thanks. How can we reproduce this easily?

**Comment by Obaied** [comment]
Closest I could get to recreating it without actually supplying the private server is to run 'copy as curl' on a Burp interception: 

```
curl -i -s -k  -X $'POST' \
    -H $'X-ARTISAN-DEVICEID: dc630d9ef8ea05d4' -H $'X-ARTISAN-APPID: eaac60820245cd517df84a82cab19751' -H $'X-JASON-SDKVERSION: 4.0.1' -H $'X-JASON-APPVERSION: 8' -H $'X-JASON-OSVERSION: 21' -H $'X-JASON-OSTYPE: android' -H $'Content-Type: multipart/form-data; boundary=thisIsMyFileBoundary' -H $'Content-Encoding: gzip' -H $'Content-Length: 1147' -H $'User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.0; Custom Phone - 5.0.0 - API 21 - 768x1280 Build/LRX21M)' -H $'Host: analytics.ma.jason.com' -H $'Connection: close' -H $'Accept-Encoding: gzip, deflate' \
    --data-binary $'--thisIsMyFileBoundary\x0d\x0aContent-Disposition: form-data; name=\"analytics\"; filename=\"analytics.gzip\"\x0d\x0aContent-Type: application/gzip\x0d\x0a\x0d\x0a\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xedV[o\xa38\x14\xfe+\x88\xa7]\xa9dl\x02\x04\xd2\xa7\xee4\xb3\xaa\xd4\xce\x8c\x9at\xb5\x97\xa9\x90\xc1&\xb1\x0a62&iv\xd4\xff\xbe\x87\xdcj\xd2\x84T\xa3}\x98\x87<q\xb1\xbfs|\xbes\xf1\xf7\xddfs&te\x0f\xff\xf9nW\xe9\x8c\x15\xe4\x0f\xa6*.\x85=\xb4\xdd\x1e\xb2/\xec\xaaN\x0a\xae5S\xf6\x10\xb6\xb0\xaaY\xbc\xa1\xb0\xac\xb1\xef\xba\x91\xd7\x8f0r\xfa,\x09\xfc,\x0c\x1c\x1a\xa5\x89\xe3y\xa1\xef\x10\x7f\x10:\x19\x0b\xd2\x04g.\x19D\x09\xd8\xa2l\xceS\xb6B\xd34\xe8#\x1a\xb1,d\x04\xf9\xd4\x83\xd5)\xe1\xb0\"\xea<\x7f\xb9\xb0I\xaa\xd7\xa7\xf8$\x15\x9b*Y\x0b\xca(l\"e\xb9\xc23B\xd2\x00\x85.r=?\xa5>\x1e\xd0,\xf4H\xe8\xa6$\xc1\xd1\xc0\xc7\xb05%\x9aM\xa5Z\xc2\xee\xab\xb2\xcc9|7&aA\x0a\xadd\xbe\xf6\xb5\xfb\x1c5Ll\xff\xe9e\xc9\x007\x1e\x8d\xc77_>74\xac#\x9f\xf0\x02\xfe\xa3\x1eB}\xd8\x04\x1f\x95&Ei\x0fqoGF\x10\x85\xa3\x08\x16\xc9\xb4\xa1\xf5\xf1\xc2\xe6\x9a\x15\x9b\xd7R\xc9\x8c\xe7lE\xb7 \x8d)\xf0^\x83\xfbe\x9cJ\xca\xc0\xcf\x9c\xe4u\xf3\xbb\xae\xec\xdd)*\xad\xb8\x98\xda/\x17;\x10\x17\xe07\xcf!);D\xeb\xdco\x11\x9b\xf3\xc7+w\x86\x1f\xec\xbd\xfa\xc9rI\xf4\x9e\x1b\x0a$\x1a\xdb]\x84C\x07y\x0e\xf2\'\x18\x0d\xfb\x83\xa1\x8f\xfe~5\xd0lnH1m@\xc2\xe2\xd5\xeb\xab\x91\xbb\xa55y\xf8<\xb2\xaeW\xe5\xd0\x15\xe7\xba`\xe2\x94(\xc5\xcd`\xed+A\x95\xe4\xb4\x0b;#\x8a.\x88b\x93f\xc3+\xf2c]iYX_gR0\xcb\xb1\xfc\x1e$\x13\x9eW_o,\x17\xc3\xcb \x08\x9f\xb1\x1b\xa2.\xd3P1\x82\xad\x0a4\xd6m\xeb\x0b\x9e\xf1.$\xb0\xf1[\xcdsj@\xc2\x13\xfb\xe3\xf9\xba#\xf7Y\xc4\xbd\xe0\xc4\x19\xb7\xc0\xbab*&S\xd6J\xfc5\xc9\xe7\xfc\xe9\xdb\x07\xb7\x87\x81\x80_n\xb9\xa8\x9f/\xad\x87KkCm\xc3\xcc\xa5\xf5^\xb6\xacUT\xdf>\xdc\xde\xff\xe9\xe2\xbb_\xbb\x0e\xb6\xadDn\x92\xf0\x03\xc3\xe4\xa8\x83B&\xd0c\xb1`z!\xd5\xd3~c\xb9Agj\xabT1&\xe2\x05\xa7zf\xa0 \xce\xce>\x81\xf9\x98\x91f\xb4qY\x18\xb0\xb2\xe1\xad3K\xb5R\x90\x97xKJG\xbb\xf9C?\x1c\xf6O\xb7\x1b\xbf\x85\x99\x9e\x9bFpg\x85\xad\xd3\xddN\xc7\x81\xe9||\x16Uq\xc6U\xb5\x8b\xc10c0\x9dH\x993\"\x0eP\x9d\x93\xa5\xac\x01\xcd\xffem\xc2O\xb6!\xa1P\xe1\x9a7\xd5\xdd:=\x8e\x10\x0e\xfa\x9d%Bt\x1b\xd2\xf71B\x11\xa1\x0e\x84\x8d\x1do\xe0!\x87P\x8f:\x09\xf61\xf1\xa2\xd4\xf3Q\xe7Qd\xb5?\x09\xc8\xe9\x09\xb5!\x802Qq\xbd43\xd6C\x1d\xd5\xb6\xa9\xef#\x17G\x1f\xbf\xa7\xbeg\x8cOg\xad{\xa0\xc5\xf5\x1b\x9f%I\x9f`\x82\xec\xcf\xa0T\x16=]\x0b\xd6+\x96\xcd\x83\x9e\x1c\xe89\xa9\xdeU\xec\xeb\xbb\xc5;Q\xec\xeb\xeeI\xdfp\xf00\xbe\xee\xcc>\xcc:\xcd\xaaOJ\x16\xbf\xdfM\x0c\x1cd\xbf\x8b\x04c\x18\x1f\x9e\xdf\xdbE\x93o\xfat\x00\xe3\xc1\x1c\xc5\x9d\xb8\xcd\xcdW@`f/\xff\x1f\xb7WYW\xb3\x91 I\xce\xcc\x0e\xf8k4\xeeN\x9c\x98\xd6P\x01\x06\x82\x89\x13\x1d\xf16n\xdf,\xec\xe3Q\'\x0a\xba\xc7\x14C\xe2I\xc8E\xa7\xbb\xadR(\xeb\xfdF|\x0e\x83880\xc1\x1e\x1b\xf4O\xa9y\xd7R\xee\x87\x94nK\xd1\xbeC\xe0N\xee\xaf>\x8e\xee\x0f\xe8\xdb 8\xa6o\x07~t\xd6\xb7g}{\xd6\xb7g}{\xd6\xb7g}{\xd6\xb7g}{\xd6\xb7?\xa5\xbe}|\xf9\x0ff\x88?\xc7\xe0\x15\x00\x00\x0d\x0a--thisIsMyFileBoundary--\x0d\x0a' \
    $'https://analytics.ma.jason.com/analytics'
```

**Comment by mhils** [comment]
This curl just hangs for me, is that correct?
