### ISSUE TITLE
Crash on escape when there's a very long response

### ISSUE THREAD

**Issue by mahenzon** [mitmproxy/mitmproxy#3049]
##### Steps to reproduce the problem:

1. Start sniffing. We need a request with a huge JSON in response. Open a response
2. Scroll down the decoded JSON to the line `Stopped displaying data after 512 lines. Press f to load all data.`
3. Press `f`
4. Scroll to the bottom
5. Press the `esc` key (multiple times)

Hooray! It crashed!

##### System information

Running on macOS 10.13.14

```
# mitmproxy --version 
Mitmproxy: 3.0.4 
Python:    3.6.5
OpenSSL:   OpenSSL 1.0.2o  27 Mar 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit
```

**Traceback:**
```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 227, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 475, in parse_input
    codes, wait_for_more)
  File "/usr/local/Cellar/mitmproxy/3.0.4/libexec/lib/python3.6/site-packages/urwid/escape.py", line 387, in process_keyqueue
    if run[0] == "esc" or run[0].find("meta ") >= 0:
AttributeError: 'tuple' object has no attribute 'find'

mitmproxy has crashed!
<!-- Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks! :) -->
```

**Comment by kajojify** [comment]
@surik00 Hello! Thanks for the report.
Didn't you press `mouse1` button and `esc` button one by one or together? 
This issue probably refers to urwid's issue: https://github.com/urwid/urwid/issues/188 and https://github.com/urwid/urwid/issues/104
If you press `esc` and right after that `mouse1`, you will get the same traceback.

**Comment by surik00** [comment]
Hello. Nope. No mouse clicks. Only keyboard control

**Comment by mhils** [comment]
Pretty sure that this is an urwid issue (@kajojify already linked to a good candidate), so I'll close this here.

**Comment by cortesi** [comment]
We should keep issues like this open, even if the root is a bug in another project. It lets us keep track of what's outstanding from these projects, and sometimes there are workarounds (like the one I recently committed for urwid/urwid#294).

**Comment by Prinzhorn** [comment]
The linked urwid issues have since been closed, so I guess this is solved
