### ISSUE TITLE
tcp_message script not working

### ISSUE THREAD

**Issue by cstefan2** [mitmproxy/mitmproxy#3113]
Hi,

I tried to execute the TCP message replace script from the doc but it seems is not working. I don't know if this is a issue with the doc script or with mitmproxy.

The script was unchanged.

##### Steps to reproduce the problem:

1. mitmdump --mode transparent --tcp-host ".*" -k -s examples/complex/tcp_message.py

Loading script: examples/tcp_message.py
Proxy server listening at http://*:8080
192.168.1.241:37604: clientconnect
::ffff:192.168.1.241:37604: Certificate verification error for None: hostname 'no-hostname' doesn't match either of '*.local.org', 'local.org'
::ffff:192.168.1.241:37604: Ignoring server verification error, continuing with connection
Addon error: Traceback (most recent call last):
  File "examples/tcp_message.py", line 16, in tcp_message
    modified_msg = tcp_msg.message.replace("foo", "bar")
AttributeError: 'TCPFlow' object has no attribute 'message'

192.168.1.241:37604 -> tcp -> 10.0.0.2:5443
Addon error: Traceback (most recent call last):
  File "examples/tcp_message.py", line 16, in tcp_message
    modified_msg = tcp_msg.message.replace("foo", "bar")
AttributeError: 'TCPFlow' object has no attribute 'message'

192.168.1.241:37604 <- tcp <- 10.0.0.2:5443

##### System information

mitmdump --version
Mitmproxy: 3.0.4 
Python:    3.6.0
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-3.19.0-65-generic-x86_64-with-debian-jessie-sid

**Comment by cstefan2** [comment]
Thanks, Is possible to post here an update example I really need one.

**Comment by cstefan2** [comment]
Many thanks. I confirm is working.
