### ISSUE TITLE
4.0.0 No module named 'mitmproxy.contrib.kaitaistruct'

### ISSUE THREAD

**Issue by ilovezfs** [mitmproxy/mitmproxy#3132]
##### Steps to reproduce the problem:

1. pip3 install mitmproxy
2. mitmproxy --version
3.

##### Any other comments? What have you tried so far?

```
(v) iMac-TMP:mymitmproxy400 joe$ ./v/bin/mitmproxy --version
Traceback (most recent call last):
  File "./v/bin/mitmproxy", line 7, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/tools/main.py", line 18, in <module>
    from mitmproxy.tools import cmdline  # noqa
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/tools/cmdline.py", line 3, in <module>
    from mitmproxy.addons import core
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/addons/__init__.py", line 1, in <module>
    from mitmproxy.addons import anticache
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/addons/anticache.py", line 1, in <module>
    from mitmproxy import ctx
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/ctx.py", line 1, in <module>
    import mitmproxy.master  # noqa
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/master.py", line 7, in <module>
    from mitmproxy import addonmanager
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/addonmanager.py", line 8, in <module>
    from mitmproxy import eventsequence
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/eventsequence.py", line 4, in <module>
    from mitmproxy import flow
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/flow.py", line 5, in <module>
    from mitmproxy import connections
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/connections.py", line 9, in <module>
    from mitmproxy.net import tcp
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 12, in <module>
    from mitmproxy.net import tls
  File "/Users/joe/Developer/mymitmproxy400/v/lib/python3.6/site-packages/mitmproxy/net/tls.py", line 18, in <module>
    from mitmproxy.contrib.kaitaistruct import tls_client_hello
ModuleNotFoundError: No module named 'mitmproxy.contrib.kaitaistruct'
(v) iMac-TMP:mymitmproxy400 joe$ 
```

##### System information

python 3.6.5 macOS

**Comment by Kriechi** [comment]
Thanks for the report. Looks like our build process messed up the uploaded wheels.
We'll investigate an release a new wheel (?) or cut a new release.

**Comment by ilovezfs** [comment]
This is happening with source builds too. See https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/24214/

**Comment by ilovezfs** [comment]
It looks like the first bad commit is 9a53525b83d4250f430de8bd4b375c5695743c4c

**Comment by Kriechi** [comment]
v4.0.1 has landed and should fix this issue.

**Comment by ilovezfs** [comment]
Thanks @Kriechi! It works now.
