### ISSUE TITLE
mitmweb - unexpected 500 error when doing flow dumps

### ISSUE THREAD

**Issue by gcmurphy** [mitmproxy/mitmproxy#3145]
##### Steps to reproduce the problem:

I've had some difficulty creating a standalone reproducer for this. **In order to trigger it I changed some addon configuration option values, and then attempted to save the flow.** 

```python
ERROR:tornado.application:Uncaught exception GET /flows/dump (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/flows/dump', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/tools/web/app.py", line 229, in get
    fw.add(f)
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/io/io.py", line 26, in add
    d = flow.get_state()
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/flow.py", line 94, in get_state
    d = super().get_state()
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 31, in get_state
    state[attr] = get_state(cls, val)
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 94, in get_state
    return _process(typeinfo, val, False)
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 77, in _process
    for k, v in val.items()
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 77, in <dictcomp>
    for k, v in val.items()
  File "/Users/grantmurphy/.local/share/virtualenvs/mitmproxy-h3iGBSQq/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 81, in _process
    assert isinstance(val, (int, str, bool, bytes))
AssertionError
ERROR:tornado.access:500 GET /flows/dump (127.0.0.1) 5.16ms

```

##### System information

mitmproxy --version
Mitmproxy: 4.0.1 
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit

**Comment by gcmurphy** [comment]
Added a `print("INSTANCE OF " + str(type(val)))` above [this line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/stateobject.py#L81) and it looks related to something being interpreted as a 'float' in my addon code. 

```
INSTANCE OF <class 'float'>
ERROR:tornado.application:Uncaught exception GET /flows/dump (127.0.0.1)
```

I think this can be addressed as a part of #3144.
