### ISSUE TITLE
proxyauth option breaks flow state access in addons

### ISSUE THREAD

**Issue by drzax** [mitmproxy/mitmproxy#3180]
##### Steps to reproduce the problem:

1. Create `test.py` addon
```py
from mitmproxy import ctx
class AuthTest:
    def response(self, flow):
        ctx.log.info('Getting flow state')
        flow.get_state()
        ctx.log.info('Got flow state')

addons = [
    AuthTest()
]
```
2. Start `mitmdump`, navigate to example.com and observe the log
```bash
mitmdump -s server/test.py
Loading script server/test.py
Proxy server listening at http://*:8080
...
[::1]:56410: GET http://example.com/
          << 200 OK 606b
Getting flow state
Got flow state
```
3. Re-start `mitmdump` with proxyauth applied and navigate to example.com again
```bash
mitmdump -s server/test.py --set proxyauth=foo:bar
Loading script server/test.py
Proxy server listening at http://*:8080
...
[::1]:56290: GET http://example.com/
          << 200 OK 606b
Getting flow state
Addon error: Traceback (most recent call last):
  File "server/test.py", line 5, in response
    flow.get_state()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/flow.py", line 94, in get_state
    d = super().get_state()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 31, in get_state
    state[attr] = get_state(cls, val)
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 94, in get_state
    return _process(typeinfo, val, False)
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 77, in _process
    for k, v in val.items()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 77, in <dictcomp>
    for k, v in val.items()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/stateobject.py", line 81, in _process
    assert isinstance(val, (int, str, bool, bytes))
AssertionError
```

##### Any other comments? What have you tried so far?

There's a FIXME [right near the code that's breaking](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/stateobject.py#L80), but I think it's a red herring. My best guess is that proxy auth adds something to the flow state that isn't in the list of allowed types `int, str, bool, bytes`—possibly a `dict`.

##### System information

```bash
mitmdump --version
Mitmproxy: 4.0.1
Python:    3.6.5
OpenSSL:   OpenSSL 1.0.2o  27 Mar 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit
```

**Comment by cortesi** [comment]
I think that assert can basically go. We want values to be serialisable, but we don't want to implement a type checker in that spot. This will change once we have the planned session store in place. Thoughts?
