### ISSUE TITLE
Segmentation Fault Help!

### ISSUE THREAD

**Issue by c0rpse** [mitmproxy/mitmproxy#3262]
Glibc problem.I changed the glibc version and tried to execute mitmproxy.But all of them were failed.
They looks like bellow:

[localhost software]# LD_LIBRARY_PATH=/home/work/libs/glibc-2.17/lib ./mitmproxy
./mitmproxy: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
[localhost software]# LD_LIBRARY_PATH=/home/work/libs/glibc-2.15/lib ./mitmproxy 
Segmentation fault
[localhost software]# LD_LIBRARY_PATH=/home/work/libs/glibc-2.14/lib ./mitmproxy 
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pkg_resources/__init__.py", line 33, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "platform.py", line 117, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "subprocess.py", line 438, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/rtool/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /home/work/libs/glibc-2.14/lib/libc.so.6: version `GLIBC_2.15' not found (required by /tmp/_MEICvKEA3/select.so)
[30568] Failed to execute script pyi_rth_pkgres
[localhost software]# LD_LIBRARY_PATH=/home/work/libs/glibc-2.17/lib ./mitmproxy 
./mitmproxy: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

**Comment by Kriechi** [comment]
Please provide more information.
What OS are you using?
Which mitmproxy version?
How did you install mitmproxy?
Why are you setting the library path?

**Comment by kajojify** [comment]
Please, reopen this (and give us a little bit more information :) ), if you still have any problems.
