### ISSUE TITLE
Starting proxy from custom script raises AttributeError: No such option: body_size_limit

### ISSUE THREAD

**Issue by llazzaro** [mitmproxy/mitmproxy#3263]
##### Steps to reproduce the problem:

using the following python code:

``` python
import os
import sys

from mitmproxy import http
from mitmproxy.master import Master
from mitmproxy.proxy import ProxyConfig, ProxyServer
from mitmproxy.options import Options

class TestInterceptor(Master):
    def __init__(self, options, server, data_queue):
        Master.__init__(self, options)
        self.server = server
        self.data_queue = data_queue

    def run(self):
        while True:
            try:
                Master.run(self)
            except KeyboardInterrupt:
                self.shutdown()
                sys.exit(0)

def start_proxy(port, data_queue):
    options = Options(
        listen_port=port,
    )
    #options.body_size_limit='3m'
    config = ProxyConfig(
        options=options,
    #    cacert = os.path.expanduser('./mitmproxy.pem'),
    )
    server = ProxyServer(config)
    print('Intercepting Proxy listening on {0}'.format(port))
    m = TestInterceptor(options, server, data_queue)
    m.run()
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/protocol/http.py", line 282, in _process_flow
    f.request.data.content = b"".join(self.read_request_body(request))
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/proxy/protocol/http1.py", line 23, in read_request_body
    human.parse_size(self.config.options.body_size_limit)
  File "/Users/leonardolazzaro/.pyenv/versions/picks/lib/python3.6/site-packages/mitmproxy-4.0.3-py3.6.egg/mitmproxy/optmanager.py", line 172, in __getattr__
    raise AttributeError("No such option: %s" % attr)
AttributeError: No such option: body_size_limit
```

##### System information

Mitmproxy: 4.0.3
Python:    3.6.1
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-17.6.0-x86_64-i386-64bit

**Comment by Kriechi** [comment]
Looks like you are missing the `core` addon.
You can add it to your master with something like `master.addons.add(core.Core())`

**Comment by llazzaro** [comment]
@Kriechi thanks that solved my issue!
