### ISSUE TITLE
Intermittent crashing

### ISSUE THREAD

**Issue by ldelossa** [mitmproxy/mitmproxy#3267]
##### Steps to reproduce the problem:

Intermittent

##### Any other comments? What have you tried so far?

Followed directions in issue and opened bug report. 

##### System information

Issue:

rror: [::1]:57274: Traceback (most recent call last):(more in eventlog)Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 279, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 354, in _establish_tls_with_client_and_server
    self.ctx.connect()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 300, in connect
    self.ctx.connect()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/base.py", line 166, in connect
    self.server_conn.connect()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/connections.py", line 267, in connect
    tcp.TCPClient.connect(self)
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/net/tcp.py", line 463, in connect
    self.ip_address = connection.getpeername()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 12, in __call__
    self.disconnect()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/proxy/protocol/base.py", line 147, in disconnect
    self.server_conn.finish()
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/connections.py", line 299, in finish
    tcp.TCPClient.finish(self)
  File "/usr/local/Cellar/mitmproxy/4.0.3_1/libexec/lib/python3.7/site-packages/mitmproxy/net/tcp.py", line 324, in finish
    self.wfile.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

**Comment by mhils** [comment]
Thanks for the report. We definitely need more details to act on this, how can we reproduce it?

**Comment by KristobalJunta** [comment]
Not sure if necroposting, but I've just encountered the very tsame error.
The context is: I am writing a scraper, that runs multiple processes, and I route them all through mitmproxy.
All scraper processes send similar requests to one website, and the specific type of pages on that site. So, I would assume that problem is not with the requests.
What I have observed for now, is that in the large sequens of requests, this error occurs from time to time, with no obvious pattern, and then mitmproxy recovers ok.
Not sure yet how can I investigate this further.

**Tech details:**
python 3.6
mitmproxy 4.0.4
centos 7.4

**Traceback:**
```
mitmproxy has crashed!
192.168.11.162:41684: Traceback (most recent call last):
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 262, in _process_flow
    return self.handle_upstream_connect(f)
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 226, in handle_upstream_connect
    f.request.scheme
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 496, in establish_server_connection
    self.connect()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 300, in connect
    self.ctx.connect()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/base.py", line 166, in connect
    self.server_conn.connect()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/connections.py", line 267, in connect
    tcp.TCPClient.connect(self)
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 463, in connect
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 26, in __call__
    self.disconnect()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/base.py", line 147, in disconnect
    self.server_conn.finish()
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/connections.py", line 299, in finish
    tcp.TCPClient.finish(self)
  File "/var/proxy/proxy-server/src/.venv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 324, in finish
    self.wfile.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

**Comment by zongrongjin** [comment]
The same problem I got, do you solve it : )

**Comment by mhils** [comment]
This should be fixed on master, please upgrade, try again, and open a new issue if it persists.
