### ISSUE TITLE
mitmdrump crashes with --ssl-insecure option with certain website requests

### ISSUE THREAD

**Issue by kwilson7770** [mitmproxy/mitmproxy#3270]
##### Steps to reproduce the problem:

1. Install mitmproxy for [Ubuntu Desktop 18.04.1](https://gist.github.com/kwilson7770/176743c16e6bf7ce5ee550fb88e15a38) or [CentOS-7-x86_64-Minimal-1804](https://gist.github.com/kwilson7770/457650ca951e9e2c67f982a0e7b7e5c5)
2. Install mitmproxy-ca certificate on Windows 10 host. Confirm web browsing works with trust in the proxy
3. Monitor "mitmdump --mode transparent --no-http2 --ssl-insecure" command output and see it crashes when Windows 10 tries to go to its websites (e.g. v10.vortex-win.data.microsoft.com). The following error message will be displayed:

```
::ffff:10.0.0.209:50088: Certificate verification error for v20.vortex-win.data.microsoft.com: unable to get local issuer certificate (errno: 20, depth: 1)
::ffff:10.0.0.209:50088: Ignoring server verification error, continuing with connection
10.0.0.209:50088: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 118, in read
    data = self.o.read(rlen)
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 1783, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 1631, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 282, in _process_flow
    f.request.data.content = b"".join(self.read_request_body(request))
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/http/http1/read.py", line 138, in read_body
    content = rfile.read(chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 140, in read
    raise exceptions.TlsException(str(e))
mitmproxy.exceptions.TlsException: (104, 'ECONNRESET')

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 118, in read
    data = self.o.read(rlen)
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 1783, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 1631, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 282, in _process_flow
    f.request.data.content = b"".join(self.read_request_body(request))
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/http/http1/read.py", line 138, in read_body
    content = rfile.read(chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 140, in read
    raise exceptions.TlsException(str(e))
mitmproxy.exceptions.TlsException: (104, 'ECONNRESET')

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

##### Any other comments? What have you tried so far?

If I remove --ssl-insecure, mitmdump no longer crashes, but instead displays:

Certificate verification error for v20.vortex-win.data.microsoft.com: unable to get local issuer certificate (errno: 20, depth: 1)
Invalid certificate, closing connection. Pass --insecure to disable validation.

In addition, when running mitmdump --mode transparent --ssl-insecure (without --no-http2), it also crashes.

I tried setting up a CentOS 7 version 1804 server and it has the same error messages and behavior.

##### System information

Mitmproxy: 4.0.3
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
