### ISSUE TITLE
Crash on ECONNRESET

### ISSUE THREAD

**Issue by qwelias** [mitmproxy/mitmproxy#3300]
##### Steps to reproduce the problem:

1. use upstream proxy mode
2. get a ECONNRESET

##### Any other comments? What have you tried so far?
```
Error: 10.6.245.204:49483: Traceback (most recent call last):(more in eventlog)Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mitmproxy/net/tcp.py", line 95, in write
    return self.o.sendall(v)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1765, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1631, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 262, in _process_flow
    return self.handle_upstream_connect(f)
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 236, in handle_upstream_connect
    return layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 87, in __call__
    layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http2.py", line 327, in __call__
    self._initiate_server_conn()
  File "/usr/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http2.py", line 113, in _initiate_server_conn
    self.server_conn.send(self.connections[self.server_conn].data_to_send())
  File "/usr/lib/python3.7/site-packages/mitmproxy/connections.py", line 273, in send
    self.wfile.write(message)
  File "/usr/lib/python3.7/site-packages/mitmproxy/net/tcp.py", line 101, in write
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: (104, 'ECONNRESET')

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

##### System information
Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.18.3-arch1-1-ARCH-x86_64-with-arch

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
