### ISSUE TITLE
TypeError on running as user

### ISSUE THREAD

**Issue by qwelias** [mitmproxy/mitmproxy#3301]
##### Steps to reproduce the problem:

1. `$ sudo pacman -S mitmproxy`
2. `$ mitmproxy`

##### Any other comments? What have you tried so far?
```
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 11, in <module>
    load_entry_point('mitmproxy==4.0.4', 'console_scripts', 'mitmproxy')()
  File "/usr/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 149, in mitmproxy
    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
  File "/usr/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 93, in run
    os.path.join(opts.confdir, OPTIONS_FILE_NAME),
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 527, in load_paths
    load(opts, txt)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 507, in load
    opts.update_defer(**data)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 221, in update_defer
    unknown = self.update_known(**kwargs)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 216, in update_known
    self._options[k].set(v)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 57, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "/usr/lib/python3.7/site-packages/mitmproxy/utils/typecheck.py", line 63, in check_option_type
    raise e
TypeError: Expected typing.Sequence[str] for client_replay, but got <class 'ruamel.yaml.comments.CommentedSeq'>.
```
Under root works as expected

##### System information

Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.18.3-arch1-1-ARCH-x86_64-with-arch

**Comment by elijahbal** [comment]
With mitmproxy-4.0.4-2 as the archlinux version, I don't have the problem at all.

Can you try to `pacman -Syu` and tell if the problem is still occuring ?

**Comment by qwelias** [comment]
So I've added before the `instanceof` check
```python
        if (name == "client_replay"):
            print((name, value, typeinfo, T))
```
and the output seems to be the for user and root, but user still throws:
```
▶ sudo mitmproxy --version
('client_replay', [], typing.Sequence[str], <class 'str'>)
('client_replay', [], typing.Sequence[str], <class 'str'>)
Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.18.3-arch1-1-ARCH-x86_64-with-arch

~                                                                                                                                                                                                                 
▶ mitmproxy --version     
('client_replay', [], typing.Sequence[str], <class 'str'>)
('client_replay', [], typing.Sequence[str], <class 'str'>)
('client_replay', [], typing.Sequence[str], <class 'str'>)
('client_replay', [], typing.Sequence[str], <class 'str'>)
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 11, in <module>
    load_entry_point('mitmproxy==4.0.4', 'console_scripts', 'mitmproxy')()
  File "/usr/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 149, in mitmproxy
    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
  File "/usr/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 93, in run
    os.path.join(opts.confdir, OPTIONS_FILE_NAME),
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 527, in load_paths
    load(opts, txt)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 507, in load
    opts.update_defer(**data)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 221, in update_defer
    unknown = self.update_known(**kwargs)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 216, in update_known
    self._options[k].set(v)
  File "/usr/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 57, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "/usr/lib/python3.7/site-packages/mitmproxy/utils/typecheck.py", line 67, in check_option_type
    raise e
TypeError: Expected typing.Sequence[str] for client_replay, but got <class 'ruamel.yaml.comments.CommentedSeq'>.


```

**Comment by qwelias** [comment]
I'm not good at python, but in JS `instanceof` could yield the same type of false-negative result if value is from different realm than the constructor the check is performed against.

**Comment by elijahbal** [comment]
qwelias: can you create a new user on your system with the sole purpose to test mitmproxy.

I think it may be related to your PYTHONPATH being messed up with, or a related question.

Also, you should update python-ruaeml I believe, since this is this thing that causes havock with the typechecker.

**Comment by dg1727** [comment]
I'm having a similar problem.  I was using the binaries of mitmproxy 4.0.4 from https://mitmproxy.org/downloads/#4.0.4/ namely https://snapshots.mitmproxy.org/4.0.4/mitmproxy-4.0.4-linux.tar.gz and they worked OK.  

But I'm developing an addon that needs a library that isn't in the binaries, so I switched to the interpreted version of mitmproxy from pip3.6.  This is on Linux Mint 18.3.  

```Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/_main.py", line 149, in mitmproxy
    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/_main.py", line 93, in run
    os.path.join(opts.confdir, OPTIONS_FILE_NAME),
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/optmanager.py", line 527, in load_paths
    load(opts, txt)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/optmanager.py", line 507, in load
    opts.update_defer(**data)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/optmanager.py", line 221, in update_defer
    unknown = self.update_known(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/optmanager.py", line 216, in update_known
    self._options[k].set(v)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/optmanager.py", line 57, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/utils/typecheck.py", line 63, in check_option_type
    raise e
TypeError: Expected typing.Sequence[str] for certs, but got <class 'ruamel.yaml.comments.CommentedSeq'>.
```

As suggested, I'm running mitmproxy as its own user.  The same exception happens when the interpreted version of mitmproxy is run as root.  $PYTHONPATH is blank.  

▶ `pip3.6 install ruamel.yaml`
```
Requirement already satisfied: ruamel.yaml in /usr/local/lib/python3.6/dist-packages (0.15.64)
```
On the test computer, `python3` is a symlink to `python3.6`

BTW, how did @qwelias include the > shell prompt?  Even copying-and-pasting from his comment didn't work for me (I could paste the right-arrow character, but not on the same line as a multiline code block.)  :stuck_out_tongue:

**Comment by dg1727** [comment]
```
▶ mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-33-generic-x86_64-with-LinuxMint-18.3-sylvia
```
A reboot didn't fix it.  Neither did removing all addons from my addons folder.

**Comment by qwelias** [comment]
@elijahbal 
Recent upgrade to `python-ruamel-yaml-0.15.74-1` have fixed the issue
