### ISSUE TITLE
Upgrade ruamel.yaml

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3321]
Upgrading ruamel.yaml currently breaks mitmproxy. We need to adjust mitmproxy to the ruamel.yaml changes.

config.yaml
```
ignore_hosts:
- example.com
- example.org
```

Traceback:
```
λ mitmproxy
Traceback (most recent call last):
  File "/home/user/venv/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmproxy')()
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/_main.py", line 149, in mitmproxy
    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/_main.py", line 93, in run
    os.path.join(opts.confdir, OPTIONS_FILE_NAME),
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/optmanager.py", line 527, in load_paths
    load(opts, txt)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/optmanager.py", line 507, in load
    opts.update_defer(**data)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/optmanager.py", line 221, in update_defer
    unknown = self.update_known(**kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/optmanager.py", line 216, in update_known
    self._options[k].set(v)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/optmanager.py", line 57, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/utils/typecheck.py", line 63, in check_option_type
    raise e
TypeError: Expected typing.Sequence[str] for ignore_hosts, but got <class 'ruamel.yaml.comments.CommentedSeq'>.
```

**Comment by borjasantosdiez** [comment]
I'm having the exact same issue with mitmproxy 4.0.4, and even going back to ruamel.yaml 0.15.54 hasn't solved the issue.

**Comment by nemaniarjun** [comment]
I would like to work on this @mhils I have used ruamel.yaml earlier for another project.

**Comment by nemaniarjun** [comment]
@mhils  the version of rualmel is the latest in my installation and the above config file works. So this issue too can be closed! :)
