### ISSUE TITLE
mitmdump crashes with https in transparent mode

### ISSUE THREAD

**Issue by Jblackman18** [mitmproxy/mitmproxy#3325]
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.20.1:56381: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/lib/python2.7/dist-packages/libmproxy/proxy/modes/transparent_proxy.py", line 21, in __call__
    layer()
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 408, in _establish_tls_with_client
    alpn_select_callback=self.__alpn_select_callback,
  File "/usr/lib/python2.7/dist-packages/libmproxy/models/connections.py", line 82, in convert_to_ssl
    super(ClientConnection, self).convert_to_ssl(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 759, in convert_to_ssl
    **sslctx_kwargs)
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 722, in create_ssl_context
    context = self._create_ssl_context(**sslctx_kwargs)
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 504, in _create_ssl_context
    context.load_verify_locations(ca_pemfile, ca_path)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 528, in load_verify_locations
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

##### Steps to reproduce the problem:
1.  mitmproxy -T --host
2. direct traffic to the proxy on port 8080 for both http and https
3. http seems to work.
4. https fails.
5. default directory for the mitmproxy certs is in tact with the certs.

##### Any other comments? What have you tried so far?

This works with mitmproxy 0.9 on a different system

##### System information
mitmproxy 0.15
ubuntu 16.04
Python 2.7.12

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by Jblackman18** [comment]
Sorry to waste your time.  I had thought I had the latest version but that is not the case.  All good now.
