### ISSUE TITLE
Transport endpoint is not connected exception

### ISSUE THREAD

**Issue by EndUser509** [mitmproxy/mitmproxy#3342]
I am running mitmdump in transparent mode with an iOS client going through. Once a day or so I get the following crash dump on the screen but mitmdump continues to function:
``` 
Exception in thread TCPConnectionHandler (ProxyServer: ::ffff:192.168.1.23:64925 -> :::8080):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git/mitmproxy/mitmproxy/net/tcp.py", line 588, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/home/user/git/mitmproxy/mitmproxy/proxy/server.py", line 66, in handle_client_connection
    self.channel
  File "/home/user/git/mitmproxy/mitmproxy/proxy/server.py", line 78, in __init__
    None)
  File "/home/user/git/mitmproxy/mitmproxy/connections.py", line 38, in __init__
    super().__init__(client_connection, address, server)
  File "/home/usergit/mitmproxy/mitmproxy/net/tcp.py", line 487, in __init__
    super().__init__(connection)
  File "/home/user/git/mitmproxy/mitmproxy/net/tcp.py", line 295, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected
```
Probably some missing exception handling.

##### System information

Mitmproxy: 5.0.0.dev (+81, commit 3f6147e)
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.17.19-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight

**Comment by mhils** [comment]
Thanks for the report and sorry for the late reply! Looks like a bug with clients that are disconnecting too fast.

**Comment by Lucadaff** [comment]
I still have the same problem, mitmdump continues to work but it is a little bit annoying because this errors produce a lot of rumor in my application logs.

**Comment by forkingna** [comment]
Is this bug fixed?

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
