### ISSUE TITLE
Error in Auto Content viewer when parsing a JPEG

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#3360]
##### Steps to reproduce the problem:

1. Download those JPEGs:
```
https://img.lemde.fr/2018/10/09/1/0/3008/2005/184/122/60/0/4991a85_fz3CllPV3V0pbxyjvHkXiu7G.jpg
https://img.lemde.fr/2018/10/09/0/56/4770/3180/184/122/60/0/2616eb7_ZEmpnu_LH1c1xeTNOJ5uM5uh.jpg

```
Got this error:
```
ERROR:  Auto Content viewer failed: 	ERROR			
Traceback (most recent call last):	ERROR			
  File "mitmproxy/contentviews/__init__.py", line 130, in get_content_view	ERROR			
  File "mitmproxy/contentviews/auto.py", line 17, in __call__	ERROR			
  File "mitmproxy/contentviews/image/view.py", line 36, in __call__	ERROR			
  File "mitmproxy/contentviews/image/image_parser.py", line 78, in parse_jpeg	ERROR			
  File "mitmproxy/contrib/kaitaistruct/exif_be.py", line 572, in ifd0	ERROR			
  File "mitmproxy/contrib/kaitaistruct/exif_be.py", line 31, in __init__	ERROR			
  File "mitmproxy/contrib/kaitaistruct/exif_be.py", line 522, in __init__	ERROR			
  File "enum.py", line 291, in __call__	ERROR			
  File "enum.py", line 533, in __new__	ERROR			
  File "enum.py", line 546, in _missing_	ERROR			
ValueError: 9 is not a valid FieldTypeEnum	ERROR	
```

##### Any other comments? What have you tried so far?
Not sure if those JPEG are malformed, and how mitmproxy should handle this case

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks for the report. We're using the excellent Kaitai Struct to parse images, it looks like their JPEG definition doesn't work for these files. This is an excellent way for first time contributors to help improving mitmproxy:

1. Fix the kaitai struct definition (https://github.com/kaitai-io/kaitai_struct_formats/blob/master/image/jpeg.ksy) to accept the JPEGs. Not sure what field type 9 is, that needs to be investigated. :-)
2. Recompile the ksy file and update https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/contrib/kaitaistruct/jpeg.py
3. Submit a PR to kaitai and mitmproxy!


I mirrored the first picture at https://uploads.hi.ls/2018-10/4991a85_fz3CllPV3V0pbxyjvHkXiu7G.jpg in case it goes down.

**Comment by prateek1192** [comment]
I have started working on this and would update my findings in some time.

**Comment by tomlabaude** [comment]
Thanks guys!
