### ISSUE TITLE
Crashed on image upload

### ISSUE THREAD

**Issue by ichux** [mitmproxy/mitmproxy#3379]
##### Steps to reproduce the problem:

1. I ran a simple Python Flask application for uploading a file
2. It worked well for a file like .txt but failed for an image
3. Please note that the file was properly uploaded to the server
4. The image is attached

<img width="1045" alt="screen_shot_2018-09-29_at_12 45 08" src="https://user-images.githubusercontent.com/30695966/48056825-dd6aea80-e1b2-11e8-95c9-012ae97f0555.png">

5. Error is shown below

```
Traceback (most recent call last):
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/listbox.py", line 501, in render
    canvas = widget.render((maxcol,))
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/widget.py", line 1004, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/canvas.py", line 1315, in apply_text_layout
    return TextCanvas(t, a, c, maxcol=maxcol)
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/urwid/canvas.py", line 358, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified 
133
[86, 133, 133, 101, 114, 92, 134, 133, 133, 134, 134, 133, 133, 134, 133, 133, 44, 135, 134, 133, 66, 133, 133, 96, 78, 130, 102, 109, 133, 113, 132, 125, 132, 84, 123, 133, 134, 103, 94, 123, 134, 133, 134, 107, 123, 134, 133, 134, 107, 123, 134, 133, 134, 133, 135, 133, 133, 122, 21, 134, 133, 133, 134, 133, 133, 135, 130, 129, 130, 133, 133, 55, 134, 111, 25, 132, 105, 118, 122, 115, 105, 133, 133, 134, 133, 133, 133, 133, 133, 134, 134, 120, 133, 133, 133, 134, 134, 134, 133, 117, 72, 133, 134, 134, 133, 133, 134, 134, 130, 127, 131, 67, 135, 5, 133, 134, 133, 133, 136, 133, 99, 133, 134, 135, 134, 133, 134, 133, 133, 132, 91, 133, 134, 82, 122, 133, 133, 133, 133, 134, 134, 134, 134, 16, 133, 133, 134, 133, 134, 133, 133, 133, 134, 21, 130, 89, 114, 133, 133, 135, 133, 133, 112, 134, 133, 133, 135, 133, 126, 59, 130, 134, 38, 129, 133, 134, 134, 133, 46, 134, 84, 131, 133, 133, 60, 133, 132, 135, 133, 135, 134, 132, 134, 131, 135, 133, 109, 132, 135, 132, 86, 134, 133, 134, 133, 133, 133, 54, 134, 134, 111, 127, 122, 134, 133, 131, 133, 134, 134, 133, 134, 134, 130, 74, 70, 96, 97, 133, 133, 132, 107, 73, 64, 133, 112, 132, 81, 73, 64, 133, 112, 132, 81, 73, 64, 133, 112, 132, 130, 133, 133, 133, 133, 133, 133, 133, 111]
[b'file: ?PNG....IHDR...*...?.....???....(iCCPICC Profile..H???.XS?.??$$$?@.???.)??H?*?.I                                               ', b'??.T???kAE.+?"??Z.Yl??"??C..e],?Py?.??????}s?3g?s???..T??"Q.?.@?0W..?????$=.. ....@?(??.'Q?H?B.....IEND?B`?"]

Traceback (most recent call last):
  File "/Users/ichux/Documents/.venv/proxy/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
TypeError: 'NoneType' object is not callable
mitmproxy has crashed!
```

##### Any other comments? What have you tried so far?
I haven't tried any other thing except for the fact that it worked will with a .txt file but failed for an image.

##### System information
mitmproxy==4.0.4

**Comment by milanoid** [comment]
Same here.

Running mitmproxy (4.0.4) in terminal on a Mac. When I try to open request/response details by hitting enter key on a POST request which uploads an image then the mitmproxy crashes.

**Comment by JoakJohaTech** [comment]
> Same here.
> 
> Running mitmproxy (4.0.4) in terminal on a Mac. When I try to open request/response details by hitting enter key on a POST request which uploads an image then the mitmproxy crashes.

I have the same exact issue, it works fine on Json/text. But on Images it crashes the whole app and I have to close the terminal instance.
 
Mitmproxy: 12.2.1 binary
Python:    3.14.0
OpenSSL:   OpenSSL 3.5.4 30 Sep 2025
Platform:  macOS-15.7.4-arm64-arm-64bit-Mach-O

Testing the web server version (mitmweb) it does not crash like the terminal does. But it reveailed that the payload was a base64 encoded PNG that became a 2.3mb Request once it was injected inside a JSON object. I think it crashes trying to parse this? Maybe the terminal could have a simular cutoff safety like the webserver for displaying these enormus Requests and not just crash. I wish this app I'm investigating would't do this from the start.
