### ISSUE TITLE
mitmdump --save_stream_file does not flush to the stream file on exit

### ISSUE THREAD

**Issue by blizzardplus** [mitmproxy/mitmproxy#3385]
##### Steps to reproduce the problem:

`mitmdump` does not flush to the stream file (through "--save_stream_file" or "-w" options) on exit. A number of times, I have run the `mitmdump` and I can see the flows on the std output, but the stream file is empty upon exit. I am wondering if there's any mechanism to force the tool to flush all flows or manage how frequently it is written to file?

##### Any other comments? What have you tried so far?

1.Run Mitmdump by calling `run` from from mitmproxy.tools.main.
2.The function creates a `master` object from `dump.DumpMaster` in the case of `mitmdump`.
3. I tried calling  `master.addons.get("save").done()` just before I call  `master.shutdown()`  but none of them seems to flush the remaining flows to the dump file.
4- This seems to improve the result and the resulting stream files are not empty. However, I don't see any size change in the stream file upon exit, even though I can clearly see new flows on the std output, so I believe there are flows that have been captured by the tool but not reflected in the stream file.

##### System information

Mitmproxy: 4.0.4 (+3, commit 5603eb5)
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.1-pre5 (beta) 17 Apr 2018
Platform:  Linux-4.9.35-v7+-armv7l-with-debian-8.0

**Comment by bretehlert** [comment]
I have a similar problem, where the stream file is truncated. This can be reproduced by making the same sequence of requests.

mitmdump.exe --mode "upstream:https://myproxy:8080" --ssl-insecure -p 8989 -w "test.dump"
```
Proxy server listening at http://*:8989
[::1]:12786: clientconnect
[::1]:12786: GET http://elines.coscoshipping.com/ebtracking/public/bill/containers/6194000840
          << 200 OK 2.2k
[::1]:12786: GET http://elines.coscoshipping.com/ebtracking/public/container/status/SEGU6334180?billNumber=6194000840
          << 200 OK 1.62k
[::1]:12786: GET http://elines.coscoshipping.com/ebtracking/public/container/status/FSCU8962294?billNumber=6194000840
          << 200 OK 1.61k
[::1]:12786: GET http://elines.coscoshipping.com/ebtracking/public/container/status/CSLU6010441?billNumber=6194000840
          << 200 OK 1.62k
[::1]:12786: GET http://elines.coscoshipping.com/ebtracking/public/container/status/CCLU6693579?billNumber=6194000840
          << 200 OK 1.61k
[::1]:12786: GET http://elines.coscoshipping.com/ebtracking/public/container/status/DFSU6036004?billNumber=6194000840
          << 200 OK 1.61k
[::1]:12786: clientdisconnect
```

The attached [test.zip](https://github.com/mitmproxy/mitmproxy/files/2614082/test.zip) contains the resulting test.dump file.

Then running with option -S on the same file and invoking the same requests, the process exits abruptly.

**Comment by blizzardplus** [comment]
This might be related. Sometimes when I call the `master.addons.get("save").done()` I get the following error:

```
Exception in thread Thread-173:
Traceback (most recent call last):
  File "/home/user1/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user1/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user1/Desktop/proj1/mitmproxy_runner.py", line 75, in shutdown_master
    master.addons.get("save").done()
  File "/home/user1/.pyenv/versions/3.6.4/lib/python3.6/site-packages/mitmproxy/addons/save.py", line 108, in done
    for f in self.active_flows:
RuntimeError: Set changed size during iteration
```
