### ISSUE TITLE
error setting ssl_insecure to true

### ISSUE THREAD

**Issue by javixeneize** [mitmproxy/mitmproxy#3395]
Hi

Im having an error when setting ssl_insecure option

Im running:

mitmdump -w test.txt --set ssl_insecure=true

The error i have is 

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "site-packages/mitmproxy/main.py", line 88, in mitmdump
  File "site-packages/mitmproxy/cmdline.py", line 165, in get_common_options
argparse.ArgumentTypeError: Malformed filter pattern:
mitmdump returned -1

How should i set ssl_insecure when using mitmdump?

THanks

**Comment by CapitanShinChan** [comment]
Just use the parameter "_--ssl-insecure_"
