### ISSUE TITLE
MemoryError occurs after a few minutes of streaming DASH encoded video

### ISSUE THREAD

**Issue by cmck** [mitmproxy/mitmproxy#3399]
##### Steps to reproduce the problem:

1. Setup mitmdump in transparent mode: `/usr/local/bin/mitmdump --mode transparent --listen-port 8081`
2. Navigate to a website where video of type MPEG-DASH is playing
3. Observe the requests for the video stream in mitmdump:
<ip>:<port>: GET http://<server>/some_dash_stream_file.mp4
                   << 206 Partial Content 2.18m
...

Actual:
For each stream request, 'clientconnect' is observed in the log. No 'clientdisconnect' is observed. It looks like one thread is created for each http request but they never close

Followed by:

```
Error in processing of request from ('::ffff:192.168.42.244', 55736, 0, 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/net/tcp.py", line 621, in serve_forever
    t.start()
  File "/usr/local/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
and eventually upon subsequent requests:

```
<ip>:<port>: GET http://<server>/some_dash_stream_file.mp4
                   << 206 Partial Content 32.22k
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 392, in _process_flow
    self.read_response_body(f.request, f.response)
MemoryError

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

##### Any other comments? What have you tried so far?

Is it possible for mitmproxy to completely ignore these requests? or for them to be re-written in such a way that one thread isn't created for each request? is this a bug? thanks :)

I have tried:
1. --ignore-hosts ip regex:80 for the video stream IP address
2. --set http2=false
3. --set stream_large_bodies=1
4. using mitmdump with a script that sets `flow.response.stream = True` for the video stream requests

##### System information

Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0f  25 May 2017
Platform:  Linux-4.14.79-v7+-armv7l-with-debian-9.6

**Comment by cmck** [comment]
Some new information about this issue - it was not seen on a much lower spec, single core machine (older raspberry Pi, with 512mb memory). On the higher spec machine (pi, four cores, 1gb memory) it occurred after approx 5 mins of streaming

**Comment by mhils** [comment]
This should be fixed on master, please open a new issue if that's not the case!
