### ISSUE TITLE
error: IOError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by yigitkonur** [mitmproxy/mitmproxy#3413]
##### Steps to reproduce the problem:

1. Trying to start a new proxy with end of & to run on background
2. Waiting for 2-3 seconds.
3. Then, we see this error:

```
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 64, in <module>
    m.run()
  File "/usr/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 538, in run
    self.ui.run_wrapper(self.loop)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 237, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 746, in loop
    size = self.drawscreen()
  File "/usr/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 723, in drawscreen
    size = self.ui.get_cols_rows()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 511, in get_cols_rows
    buf = fcntl.ioctl(0, termios.TIOCGWINSZ, ' '*4)
IOError: [Errno 25] Inappropriate ioctl for device
```

##### Any other comments? What have you tried so far?
I'm running MITMPROXY on EdgeRouter - EdgeOS - Debian Based.

##### System information

mitmproxy 0.8

**Comment by Kriechi** [comment]
Sorry, but we do not support mitmproxy v0.8 - which is 5-6 years old.
Please upgrade to v4.0.4 (requires Python 3) or v0.18.2 (last compatible release for Python 2.7, but also unsupported).
