### ISSUE TITLE
Searching is broken in master

### ISSUE THREAD

**Issue by Transfusion** [mitmproxy/mitmproxy#3422]
##### Steps to reproduce the problem:

1. Visit any site via mitmproxy
2. Go to the Response tab, press `/` to search and enter any string

##### Any other comments? What have you tried so far?

```
$ mitmproxy --mode socks5
Traceback (most recent call last):
  File "/home/transfusion/mitmproxy/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/transfusion/mitmproxy/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/home/transfusion/mitmproxy/venv/lib/python3.6/site-packages/urwid/container.py", line 1119, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/home/transfusion/mitmproxy/mitmproxy/tools/console/statusbar.py", line 192, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/home/transfusion/mitmproxy/mitmproxy/tools/console/statusbar.py", line 139, in keypress
    self.command_history.add_command(self._w.cbuf, True)
AttributeError: 'Edit' object has no attribute 'cbuf'

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```

##### System information

Mitmproxy: 5.0.0.dev (+209, commit e2bcca4)
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by rjt-gupta** [comment]
The fix seems to working fine. Is there anything else that needs to be done?

**Comment by dimitar-petrov** [comment]
Hi Guys,

Is there a reason not to merge this fix?

I am facing the same issue:

```
Mitmproxy: 4.0.4
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1c  28 May 2019
Platform:  Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch
```

**Comment by alt-glitch** [comment]
Hi @Transfusion, @dimitar-petrov;
Have you tried updating to the latest version? Searching seems to work fine on mitmproxy.
In the following screenshot, the search function seems to work perfectly fine. 
![image](https://user-images.githubusercontent.com/52913345/107952171-693d6500-6fbf-11eb-99d9-f210b929d582.png)
It works for SOCKS 5 mode too
Any steps to reproduce your particular issue?
```
❯ mitmproxy --version
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.10.7-3-MANJARO-x86_64-with-glibc2.32
```

**Comment by Prinzhorn** [comment]
I'm gonna go ahead and close this. If someone can provide clear steps to reproduce it feel free to post them here.
