### ISSUE TITLE
Bug report. mitmproxy has crashed!

### ISSUE THREAD

**Issue by scorpioRED** [mitmproxy/mitmproxy#3431]
##### Steps to reproduce the problem:

Try to debug ios application

##### Any other comments? What have you tried so far?
Traceback (most recent call last):ack (most recent call last):(more in eventlog)
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 279, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 354, in _establish_tls_with_client_and_server
    self.ctx.connect()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 300, in connect__
    self.ctx.connect()ss_flow(flow):
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/base.py", line 166, in connects_flow
    self.server_conn.connect()
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/connections.py", line 267, in connect establish_server_connection
    tcp.TCPClient.connect(self)
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 463, in connect in connect
    self.ip_address = connection.getpeername()
OSError: [Errno 22] Invalid argument4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 300, in connect
    self.ctx.connect()
During handling of the above exception, another exception occurred:e-packages/mitmproxy/proxy/protocol/base.py", line 166, in connect
    self.server_conn.connect()
Traceback (most recent call last):y/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/connections.py", line 267, in connect
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()al/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 463, in connect
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 12, in __call__
    self.disconnect()nvalid argument
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/base.py", line 147, in disconnect
    self.server_conn.finish()exception, another exception occurred:
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/connections.py", line 299, in finish
    tcp.TCPClient.finish(self)st):
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 324, in finishandle
    self.wfile.flush()
AttributeError: 'NoneType' object has no attribute 'flush'on3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 12, in __call__
    self.disconnect()
mitmproxy has crashed!lar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/proxy/protocol/base.py", line 147, in disconnect
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/connections.py", line 299, in finish
    tcp.TCPClient.finish(self)
  File "/usr/local/Cellar/mitmproxy/4.0.1/libexec/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 324, in finish
    self.wfile.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

##### System information

Mitmproxy: 4.0.1 
Python:    3.6.5
OpenSSL:   OpenSSL 1.0.2o  27 Mar 2018
Platform:  Darwin-17.3.0-x86_64-i386-64bit

**Comment by KristobalJunta** [comment]
Same error as #3267

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
