### ISSUE TITLE
mitmproxy crashed when request url param include a string without urlencode !

### ISSUE THREAD

**Issue by hbhuyt** [mitmproxy/mitmproxy#3439]
mitmproxy crashed when request url param include a string without urlencode !
how can I catch this error and add some codes?

HttpSyntaxException("Bad HTTP request line: b'GET http://www.goodtime.com/f10/stock/stk_assetrestruct.do?tradingcode=600052&secuabbr=\\xe6\\xb5\\x99\\xe6\\xb1\\x9f\\xe5\\xb9\\xbf\\xe5\\x8e\\xa6&comcode=228819&indunum=1010010000&type=region HTTP/1.1'",)

127.0.0.1:11993: clientdisconnect
127.0.0.1:11998: Traceback (most recent call last):
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\tcp.py", line 118, in read
    data = self.o.read(rlen)
  File "C:\WinPython\python-3.6.6.amd64\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 286, in __call__
    layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 83, in __call__
    layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 242, in _process_flow
    request = self.read_request_headers(f)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 15, in read_request_headers
    http1.read_request_head(self.client_conn.rfile)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\http\http1\read.py", line 53, in read_request_head
    headers = _read_headers(rfile)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\http\http1\read.py", line 330, in _read_headers
    line = rfile.readline()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\tcp.py", line 158, in readline
    ch = self.read(1)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\tcp.py", line 136, in read
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Traceback (most recent call last):
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\tcp.py", line 118, in read
    data = self.o.read(rlen)
  File "C:\WinPython\python-3.6.6.amd64\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 286, in __call__
    layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 83, in __call__
    layer()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 242, in _process_flow
    request = self.read_request_headers(f)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 15, in read_request_headers
    http1.read_request_head(self.client_conn.rfile)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\http\http1\read.py", line 53, in read_request_head
    headers = _read_headers(rfile)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\http\http1\read.py", line 330, in _read_headers
    line = rfile.readline()
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\tcp.py", line 158, in readline
    ch = self.read(1)
  File "C:\WinPython\python-3.6.6.amd64\lib\site-packages\mitmproxy\net\tcp.py", line 136, in read
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
127.0.0.1:11998: clientdisconnect
127.0.0.1:12006: clientconnect
127.0.0.1:12007: clientconnect
127.0.0.1:12007: HTTP protocol error in client request: Bad HTTP request line: b'GET http://www.goodtime.com/f10/stock/stockmainpage.do?tradingcode=600152&secuabbr=\xe7\xbb\xb4\xe7\xa7\x91\xe6\x8a\x80\xe6\x9c\xaf HTTP/1.1'

**Comment by Kriechi** [comment]
Fixed by #3464
