### ISSUE TITLE
mitmproxy has crashed

### ISSUE THREAD

**Issue by JamesZBL** [mitmproxy/mitmproxy#3445]
##### Steps to reproduce the problem:

1. mitmdump -m transparent -s addons.py
2. several hours later there comes the log
3. log:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 118, in read
    data = self.o.read(rlen)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 282, in _process_flow
    f.request.data.content = b"".join(self.read_request_body(request))
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/http/http1/read.py", line 138, in read_body
    content = rfile.read(chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 136, in read
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: [Errno 110] Connection timed out

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

##### System information

Mitmproxy: 4.0.4
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
