### ISSUE TITLE
Brew Install macOS 10.14

### ISSUE THREAD

**Issue by moisesvs** [mitmproxy/mitmproxy#3492]
##### Steps to reproduce the problem:

1. brew install mitmproxy

##### Any other comments? What have you tried so far?

When you run this command. The output command is the following:

```
Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
/usr/local/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x0000010259e108> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Library/Homebrew/brew.rb:30:in `<main>'
```

##### System information

macOS 10.14

**Comment by Kriechi** [comment]
We do not maintain the homebrew formulae.
