### ISSUE TITLE
mitmproxy.exceptions.TcpDisconnect: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by jszurdi** [mitmproxy/mitmproxy#3495]
##### Steps to reproduce the problem:

It is not a persistent problem.
I visited https://ipleak.net/ and one time I got the below exception.
Weirdly mitmproxy didn't actually stop because  my script was able to use it for two more requests afterward.

I use an upstream proxy server and I intercept messages.

##### Any other comments? What have you tried so far?

https://ipleak.net/
har_files/988580/
screenshots/988580/
Took [1.2397181987762451] seconds to launch the browser
Took [13.238298892974854] seconds to request the page
[31m[22m[::1]:36210: Traceback (most recent call last):
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 95, in write
    return self.o.sendall(v)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1668, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1540, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 262, in _process_flow
    return self.handle_upstream_connect(f)
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 236, in handle_upstream_connect
    return layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 87, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 328, in __call__
    self._complete_handshake()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 119, in _complete_handshake
    self.client_conn.send(self.connections[self.client_conn].data_to_send())
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/connections.py", line 108, in send
    self.wfile.write(message)
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 101, in write
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: (104, 'ECONNRESET')
[0m
Traceback (most recent call last):
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 95, in write
    return self.o.sendall(v)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1668, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1540, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 262, in _process_flow
    return self.handle_upstream_connect(f)
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 236, in handle_upstream_connect
    return layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 87, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 328, in __call__
    self._complete_handshake()
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 119, in _complete_handshake
    self.client_conn.send(self.connections[self.client_conn].data_to_send())
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/connections.py", line 108, in send
    self.wfile.write(message)
  File "/home/jszurdi/tds/tds3/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 101, in write
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: (104, 'ECONNRESET')

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Link followed as  vanilla :  https://ipleak.net/

##### System information

Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.18.0-15-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by cooperq** [comment]
I have the same problem on mitmproxy 5.1.1

**Comment by mhils** [comment]
This should be fixed on master. If that's not the case, please open a new issue!
