### ISSUE TITLE
macOS transparent proxy PermissionError

### ISSUE THREAD

**Issue by adamyonk** [mitmproxy/mitmproxy#3504]
##### Steps to reproduce the problem:

Trying to proxy all traffic from macOS through to mitmproxy. Followed the [steps](https://docs.mitmproxy.org/stable/howto-transparent/#macos) to set up transparent proxy on macOS where host listens to its own traffic.

1. When I try to enable `pf` (step 4),
    ```
    ❯ sudo pfctl -e
    Password:
    No ALTQ support in kernel
    ALTQ related functions disabled
    pf enabled
    ```
    Are the ALTQ warnings OK/expected?
1. After `sudo -u nobody mitmproxy --mode transparent --showhost`:
```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    ws = cls()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 562, in __init__
    self.add_entry(entry)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 618, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1965, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2035, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2474, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2849, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2438, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2628, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1411, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1519, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/PKG-INFO'
```

##### Any other comments? What have you tried so far?

Poked around GitHub, StackOverflow, and the forums for this error, but couldn't find any related issues.

##### System information

```
Mitmproxy: 4.0.4
Python:    3.7.2
OpenSSL:   OpenSSL 1.0.2q  20 Nov 2018
Platform:  Darwin-18.2.0-x86_64-i386-64bit
```

**Comment by adamyonk** [comment]
🤦‍♂️ I guess `nobody` isn't an actual user. So since you need to run mitmproxy as a different user as your own I'm assuming you need to create one on macOS using `dscl`?

**Comment by mhils** [comment]
This really isn't a mitmproxy problem, more of a Python issue.
```
'/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/PKG-INFO'
```
isn't readable as nobody. This gets imported before any mitmproxy code is run.

**Comment by adamyonk** [comment]
```
❯ sudo -u nobody ls -al /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/SOURCES.txt
-rwx------  1 adam  staff  529 Jul 31  2018 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/SOURCES.txt
```

Sorry, I'm not sure how to debug this farther. Do I just need to change permissions on that file, or is there some reason it's getting installed with the wrong permissions? This was a homebrew install.

**Comment by OmarKhattab** [comment]
I have this same issue `PermissionError: [Errno 13] Permission denied: '/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/PKG-INFO'`

**Comment by iliaskarim** [comment]
@adamyonk @OmarKhattab install with pip: `pip3 install mitmproxy`

**Comment by GuinGuinGuin** [comment]
@adamyonk i am facing the same issue, did you manage to find a fix?

**Comment by adamyonk** [comment]
@GuinGuinGuin its been so long, I don't remember what happened with this, I may have ended up trying to install it via pip instead of homebrew.
