### ISSUE TITLE
Crash: Can't create thread

### ISSUE THREAD

**Issue by reardenlife** [mitmproxy/mitmproxy#3515]
To be exact: RuntimeError: can't start new thread

Cent OS 7.  Got 8k file descriptors limit.  1GB RAM total + some swap.  About 500MB usually free.

Got the latest version from the master branch.
Started the mitmproxy on localhost in transparent mode.  Redirected some tor http traffic from local exit node.  After about 12 hours and may be few dozens of thousands requests, I am having a crash:
( output is intermingled with requests a little bit )

```text
(venv) [root@v48807 mitmproxy]# mitmproxy --mode transparent --set block_global=false --listen-host 127.0.0.1


pt/mitmproxy/mitmproxy/net/tcp.py", line 621, in serve_forever
    t.start()/172.217.10.68/sorry/index?continue=http://www.google.fr/search%3Fq%3Detude%2
  File "/usr/local/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new threadvirtualisation+economie+transporteur+express+internati
       onal+up…
----------------------------------------
----------------------------------------continue=http://www.google.fr/search%3Fq%3Dvirtual
Error in processing of request from ('185.22.153.244', 35888)
Traceback (most recent call last):
  File "/opt/mitmproxy/mitmproxy/net/tcp.py", line 621, in serve_foreverone+2001&num=100&h
    t.start()S…
  File "/usr/local/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())ntinue=http://www.google.fr/search%3Fq%3Denjeux%
RuntimeError: can't start new thread
       ← 503 text/html 3.09k 449ms
----------------------------------------l+petrole+energie+fossile+concurrents&num=100&hl=e
----------------------------------------
Error in processing of request from ('185.22.153.244', 35890)
Traceback (most recent call last):index?continue=http://www.google.fr/search%3Fq%3Dtotal%2
  File "/opt/mitmproxy/mitmproxy/net/tcp.py", line 621, in serve_forever
    t.start()text/html 3.08k 425ms
  File "/usr/local/lib/python3.7/threading.py", line 847, in starts&num=100&hl=en-US&gbv=1
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
   GET http://172.217.10.68/sorry/index?continue=http://www.google.fr/search%3Fq%3Ddossier
----------------------------------------
       ← 503 text/html 3.05k 448ms
>> GET http://172.217.3.99/search?q=guide-pratique+administratif&num=100&hl=en-US&gbv=1&pr
       md=ivns…
       ← 302 text/html 450b 1.74s
   GET http://172.217.10.68/sorry/index?continue=http://www.google.fr/search%3Fq%3Dguide-p
       ratique…
```

**Comment by reardenlife** [comment]
Tell me how mitmproxy works.  Does it create a new thread for each connection?

If so, any way to switch to async architecture so I can use a fixes pool of threads?

**Comment by reardenlife** [comment]
Alright so after about 24k HTTP requests mitmproxy took up about 712MB of RAM.

Does it keep all of the requests in memory or what?

**Comment by reardenlife** [comment]
Alright.  Let me run mitmdump with debug logs for a while.  Lets see what happens.

**Comment by reardenlife** [comment]
About 30k requests went through mitmdump.  It grew from about 60 MB to 220MB and keeps growing.  Number of open file descriptors fluctuates around 100.

Let me upload the debug log.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
