### ISSUE TITLE
How to build windows binary

### ISSUE THREAD

**Issue by mAmged** [mitmproxy/mitmproxy#3517]
I want to build windows portable binary couln't find any documentations for this, like this https://snapshots.mitmproxy.org/4.0.4/mitmproxy-4.0.4-windows.zip

any help please?
thanks,

**Comment by mhils** [comment]
Binaries are built by our CI script, so please take a look at them. 
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!

**Comment by mAmged** [comment]
@mhils I followed your comment on one of discourse posts and tried to run the CI command ` tox -e cibuild -- build` and I got this error
```
cibuild run-test: commands[1] | python ./release/cibuild.py build
Traceback (most recent call last):
  File "./release/cibuild.py", line 532, in <module>
    cli()
  File "C:\Users\mypc\Downloads\Compressed\33mitmproxy-4.0.4\.tox\cibuild\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mypc\Downloads\Compressed\33mitmproxy-4.0.4\.tox\cibuild\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\mypc\Downloads\Compressed\33mitmproxy-4.0.4\.tox\cibuild\lib\site-packages\click\core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\mypc\Downloads\Compressed\33mitmproxy-4.0.4\.tox\cibuild\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mypc\Downloads\Compressed\33mitmproxy-4.0.4\.tox\cibuild\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./release/cibuild.py", line 474, in build
    be.dump_info()
  File "./release/cibuild.py", line 184, in dump_info
    print(f"cibuild.{attr}={getattr(self, attr)}", file=fp)
  File "./release/cibuild.py", line 289, in version
    raise BuildError("We're on neither a tag nor a branch - could not establish version")
__main__.BuildError: We're on neither a tag nor a branch - could not establish version
ERROR: InvocationError for command 'C:\Users\mypc\Downloads\Compressed\33mitmproxy-4.0.4\.tox\cibuild\Scripts\python.EXE' ./release/cibuild.py build (exited with code 1)
______________________________________________________ summary _______________________________________________________
ERROR:   cibuild: commands failed
```

thanks
