### ISSUE TITLE
Crash: Memory error

### ISSUE THREAD

**Issue by reardenlife** [mitmproxy/mitmproxy#3518]
The setup is the same as in my previous post: https://github.com/mitmproxy/mitmproxy/issues/3515

The source of the problem should be the same - resource leakage.

```text

-:49420: Traceback (most recent call last):
  File "/opt/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/opt/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/http.py", line 392, in _process_flow
    self.read_response_body(f.request, f.response)
MemoryError

Traceback (most recent call last):
  File "/opt/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/opt/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/http.py", line 392, in _process_flow
    self.read_response_body(f.request, f.response)
MemoryError

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
-:49420: clientdisconnect
```

**Comment by Prinzhorn** [comment]
If this is still an issue with the latest release, feel free to open a new issue.
