### ISSUE TITLE
Crash: Can't parse client hello

### ISSUE THREAD

**Issue by reardenlife** [mitmproxy/mitmproxy#3519]
```text
Traceback (most recent call last):
  File "/opt/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()ug report at: https://github.com/mitmproxy/mitmproxy
  File "/opt/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 268, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
-:58670: Cannot parse Client Hello: TlsProtocolException('Cannot read raw Client Hello: TlsProtocolException(\'Unexpected EOF in TLS handshake: b\\\'\\\\x01\\\\x00\\\\x01\\\\xfc\\\\x03\\\\x03\\\\x06\\\\x7f\\\\xa7\\\\x02\\\\xf8\\\\x10\\\\x05\\\\x8c\\\\xe1QT\\\\x8f\\\\x17\\\\xa0\\\\xfbN\\\\xf0\\\\xd2\\\\x15\\\\x0b\\\\x9bk\\\\x9c\\\\x88\\\\xd8\\\\xe5\\\\xaa\\\\x9d\\\\x95f<\\\\xc0 `\\\\xdf\\\\x86\\\\x88\\\\x80\\\\x90\\\\x95!\\\\x02S\\\\xa76M\\\\xed\\\\xe86&\\\\xf8\\\\r\\\\x18\\\\xb3\\\\x1e\\\\xbaB\\\\x1a\\\\xff\\\\xa9F\\\\xdbA}=\\\\x00$\\\\x13\\\\x01\\\\x13\\\\x03\\\\x13\\\\x02\\\\xc0+\\\\xc0/\\\\xcc\\\\xa9\\\\xcc\\\\xa8\\\\xc0,\\\\xc00\\\\xc0\\\\n\\\\xc0\\\\t\\\\xc0\\\\x13\\\\xc0\\\\x14\\\\x003\\\\x009\\\\x00/\\\\x005\\\\x00\\\\n\\\\x01\\\\x00\\\\x01\\\\x8f\\\\x00\\\\x00\\\\x00\\\\x1c\\\\x00\\\\x1a\\\\x00\\\\x00\\\\x17ru-92-53-3.fri-gate.biz\\\\x00\\\\x17\\\\x00\\\\x00\\\\xff\\\\x01\\\\x00\\\\x01\\\\x00\\\\x00\\\\n\\\\x00\\\\x0e\\\\x00\\\\x0c\\\\x00\\\\x1d\\\\x00\\\\x17\\\\x00\\\\x18\\\\x00\\\\x19\\\\x01\\\\x00\\\\x01\\\\x01\\\\x00\\\\x0b\\\\x00\\\\x02\\\\x01\\\\x00\\\\x00#\\\\x00\\\\x00\\\\x00\\\\x10\\\\x00\\\\x0e\\\\x00\\\\x0c\\\\x02h2\\\\x08http/1.1\\\\x00\\\\x05\\\\x00\\\\x05\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x003\\\\x00k\\\\x00i\\\\x00\\\\x1d\\\\x00 \\\\xa2\\\\xe8\\\\xdd\\\\xb0\\\\xbdg\\\\x96\\\\xfbY\\\\x98P\\\\xb9l8\\\\xa9\\\\x0c\\\\xdb X2\\\\x93\\\\x98\\\\xe6\\\\xc1\\\\x06\\\\x9b\\\\x1eY\\\\xdf\\\\xe5\\\\xed\\\\x0e\\\\x00\\\\x17\\\\x00A\\\\x04\\\\x7f\\\\xe5+wN\\\\x17"\\\\x86\\\\x05\\\\n\\\\xd0|\\\\xbb\\\\xd5\\\\x1c\\\\x83.\\\\x1aXm\\\\xf6\\\\xc5S\\\\x06s\\\\xf0\\\\xaf=\\\\x08)g\\\\xcf\\\\n!\\\\xd7\\\\x0fig?>\\\\rK\\\\x04\\\\n<\\\\xff\\\\x8e\\\\x080\\\\x8a\\\\\\\\\\\\x83\\\\xa7\\\\x03\\\\xa7\\\\xe7v\\\\xe8{;\\\\xd6K\\\\xe1\\\\x1b\\\\x00+\\\\x00\\\\t\\\\x08\\\\x03\\\\x04\\\\x03\\\\x03\\\\x03\\\\x02\\\\x03\\\\x01\\\\x00\\\\r\\\\x00\\\\x18\\\\x00\\\\x16\\\\x04\\\\x03\\\\x05\\\\x03\\\\x06\\\\x03\\\\x08\\\\x04\\\\x08\\\\x05\\\\x08\\\\x06\\\\x04\\\\x01\\\\x05\\\\x01\\\\x06\\\\x01\\\\x02\\\\x03\\\\x02\\\\x01\\\\x00-\\\\x00\\\\x02\\\\x01\\\\x01\\\\x00\\\\x1c\\\\x00\\\\x02@\\\\x01\\\\x00\\\\x15\\\\x00\\\\x87\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\'\')')
---:58670: Traceback (most recent call last):
  File "/opt/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/opt/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/opt/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 268, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'
```

Why the software crashes if the input data is invalid?  Why not to ignore it?

**Comment by kajojify** [comment]
@reardenlife Hello! Thank you for the report!
Please, provide more details concerning this issue.
What are steps to reproduce?
What data do you input?

**Comment by kajojify** [comment]
Do you have the same setup as here? https://github.com/mitmproxy/mitmproxy/issues/3515

**Comment by reardenlife** [comment]
@kajojify

Well, the input data is different every time - as I explained before, I am dumping the traffic from TOR exit node.

Various crashes happening afterwards.
