### ISSUE TITLE
mitmproxy crashes with ImportError

### ISSUE THREAD

**Issue by jkugler** [mitmproxy/mitmproxy#3533]
##### Steps to reproduce the problem:

1. Download version 4
2. Untar
3. Run mitmproxy

##### Any other comments? What have you tried so far?
N/A

##### System information
Cannot get version (see below). This is CentOS 7.5

```
# ./mitmproxy --version
Traceback (most recent call last):
  File "release/specs/mitmproxy_main", line 2, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/tools/main.py", line 22, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/tools/_main.py", line 13, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/tools/cmdline.py", line 3, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/addons/__init__.py", line 1, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/addons/anticache.py", line 1, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/ctx.py", line 1, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/master.py", line 7, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/addonmanager.py", line 8, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/eventsequence.py", line 5, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/http.py", line 6, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/net/http/__init__.py", line 1, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/net/http/request.py", line 10, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/net/http/message.py", line 5, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "mitmproxy/net/http/encoding.py", line 11, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/brotli/__init__.py", line 3, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/brotli/brotli.py", line 5, in <module>
  File "/home/travis/build/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIPX2BPF/libstdc++.so.6)
[45449] Failed to execute script mitmproxy_main
```

**Comment by mikesxf** [comment]
Hi, have you solved the problem? I meet the same problem and it is said that I can download source code of GLIBC_2.18, compile and install it. I'm not sure whether it works.

**Comment by yousong** [comment]
I am having the same issue.  Seems like the same kind of issue with #2445

```
➜  ~ rpm -qf /lib64/libc.so.6
glibc-2.17-260.el7_6.5.x86_64
➜  ~ strings /lib64/libc.so.6 | grep 'GLIBC_2.1'
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
___sys_nerr_GLIBC_2_1
___sys_errlist_GLIBC_2_1
memcpy@@GLIBC_2.14
_sys_nerr@@GLIBC_2.12
posix_spawn@@GLIBC_2.15
posix_spawnp@@GLIBC_2.15
_sys_errlist@@GLIBC_2.12
GLIBC_2.11
GLIBC_2.16
GLIBC_2.10
GLIBC_2.17
GLIBC_2.13
```

**Comment by Haran** [comment]
CentOS 7.8.2003 - problem persists, top-notch GLIBC is 2.17 and no chance of getting any upgrade. According to the forum posts, CentOS maintainers are proud of not having 2.18. Can we have it 2.17, please?

**Comment by jkugler** [comment]
@Haran Can you link to that forum thread? I'm pretty sure Redhat would not do a 2.17 -> 2.18 upgrade in a distro without changing the major version. Redhat/CentOS 8 has glibc 2.28.

Some possible tips here: https://serverfault.com/questions/894625/safely-upgrade-glibc-on-centos-7

**Comment by mhils** [comment]
We build our releases using PyInstaller on GitHub CI runners, and that combo doesn't allow us to support earlier glibc versions. Please go bother RedHat.

**Comment by fbacchella** [comment]
The build ands tests are done using ubuntu-latest. That open the door to a lot of problems. That's Redhat fault.

**Comment by mhils** [comment]
Tests are run on ubuntu-latest, which never caused any problems. Binary builds are done on the oldest Ubuntu version available on GitHub actions.

**Comment by fbacchella** [comment]
Yes, because they don't do what they are expected to do: detect problems before they happens on users environments. And everything is done using the latest (not the oldest) ubuntu. If I look at https://github.com/mitmproxy/mitmproxy/blob/master/.github/workflows/main.yml, I see:

```
runs-on: ubuntu-latest
```

on all sections.

**Comment by mhils** [comment]
Binaries are built on `ubuntu-16.04`:
https://github.com/mitmproxy/mitmproxy/blob/880cea66bba2bd126b353d2822466300861f1289/.github/workflows/main.yml#L100

Supporting (very) old Linux versions doesn't justify the additional effort and complexity of splitting up our CI pipeline onto multiple CI providers.

**Comment by jkugler** [comment]
> Supporting (very) old Linux versions doesn't justify the additional effort and complexity of splitting up our CI pipeline onto multiple CI providers.

Redhat 7 isn't "very old." It's still a currently supported version of Redhat.

**Comment by mhils** [comment]
Again, building with an older glibc version would introduce significant complexity for us, so it's not going to happen. You can install mitmproxy via any of the other methods described at https://docs.mitmproxy.org/stable/overview-installation/.

As a final remark, please consider your attitude/entitlement towards open source maintainers.
