### ISSUE TITLE
Changing Host/Port while running the proxy breaks it. 

### ISSUE THREAD

**Issue by armudgal** [mitmproxy/mitmproxy#3539]
##### Steps to reproduce the problem:

1. Run `mitmproxy`
2. Press <kbd>O</kbd> and go to port
3. Change the port and press <kbd>Enter</kbd>

### Traceback

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/tools/console/options.py", line 283, in keypress
    return self.focus_item.keypress(tsize, key)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/tools/console/options.py", line 177, in keypress
    d = self.master.options.parse_setval(foc.opt.name, v)
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 332, in parse_setval
    if o.typespec in (str, typing.Optional[str]):
AttributeError: 'str' object has no attribute 'typespec'
```

##### Any other comments? What have you tried so far?
`mitmproxy --listen-port <port>` works fine

##### System information

```
Mitmproxy: 4.0.4
Python:    3.7.3
OpenSSL:   OpenSSL 1.0.2r  26 Feb 2019
Platform:  Darwin-17.7.0-x86_64-i386-64bit
```

ref: https://github.com/mitmproxy/mitmproxy/issues/2932#issuecomment-369048094

**Comment by normanr** [comment]
I think affects any option that accepts a string value (bools seem fine).

**Comment by mhils** [comment]
This crash is fixed. Changing the port will probably not work anyways at the moment, but that will be fixed by the sans-io implementation at some point. Thanks again!
