### ISSUE TITLE
Mtimdump crashes when replaying websockets

### ISSUE THREAD

**Issue by bebef1987** [mitmproxy/mitmproxy#3564]
##### Steps to reproduce the problem:

1. Start mitmdump in record mode  `mitmdump-linux --set save_stream_file=websocket.mp`
2. In browser open  http://websocket.org/echo.html
3.  Click `Connect` and Send message
4. Close proxy
5.  Start mitmdump in replay mode  `mitmdump-linux --set server_replay=websocket.mp`
6. In browser open  http://websocket.org/echo.html
7.  Click `Connect` and Send message
8. Check output

first we get addon error:
```
mitmdump-linux --set server_replay=/home/florinstrugariu/mozilla/raptor-studio/record/websocket.mp
Addon error: Traceback (most recent call last):
  File "mitmproxy/addons/serverplayback.py", line 174, in configure
  File "mitmproxy/command.py", line 275, in wrapper
  File "mitmproxy/addons/serverplayback.py", line 79, in load_flows
AttributeError: 'WebSocketFlow' object has no attribute 'response'
```
and when we click `connect` in replay mode we get
```
127.0.0.1:40402: GET http://websocket.org/img/favicon.ico
[replay]               << 200 OK 3.55k
127.0.0.1:40480: clientconnect
127.0.0.1:40480: GET http://echo.websocket.org/?encoding=text
[replay]               << 101 Web Socket Protocol Handshake 0b
WebSocket connection closed by client: 1000 (message missing), unknown status code
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 121, in handle
  File "mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 286, in __call__
  File "mitmproxy/proxy/protocol/http1.py", line 83, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 188, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
  File "mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
  File "mitmproxy/proxy/protocol/http1.py", line 83, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 188, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 447, in _process_flow
  File "mitmproxy/proxy/protocol/websocket.py", line 193, in __call__
  File "mitmproxy/net/tcp.py", line 227, in ssl_read_select
TypeError: argument must be an int, or have a fileno() method.

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
127.0.0.1:40480: Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 121, in handle
  File "mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 286, in __call__
  File "mitmproxy/proxy/protocol/http1.py", line 83, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 188, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
  File "mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
  File "mitmproxy/proxy/protocol/http1.py", line 83, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 188, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 447, in _process_flow
  File "mitmproxy/proxy/protocol/websocket.py", line 193, in __call__
  File "mitmproxy/net/tcp.py", line 227, in ssl_read_select
TypeError: argument must be an int, or have a fileno() method.

127.0.0.1:40480: clientdisconnect
```
##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid

**Comment by mhils** [comment]
Long story short, we currently don't support WebSocket replay. Sorry!

**Comment by tarekziade** [comment]
@mhils maybe it should be stated here https://docs.mitmproxy.org/stable/concepts-protocols/#websocket because mitproxy current does record all the websocket traffic, so it's not obvious that the replay is not working. Also, if WebSocketFlow.response raises a NotImplementedError with a clear message saying it's not supported, it would make things even clearer imho.

**Comment by mhils** [comment]
Good point, thanks!
