### ISSUE TITLE
search some test. crash

### ISSUE THREAD

**Issue by hhhaiai** [mitmproxy/mitmproxy#3576]
##### Steps to reproduce the problem:

1. custom parser metod.
2. search text （/， then “xxx”）
3. enter ，then crash.

```
Traceback (most recent call last):
  File "/Users/sanbo/dev/mitm/mitmproxy/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/sanbo/dev/mitm/mitmproxy/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/Users/sanbo/dev/mitm/mitmproxy/venv/lib/python3.7/site-packages/urwid/container.py", line 1119, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/Users/sanbo/dev/mitm/mitmproxy/mitmproxy/tools/console/statusbar.py", line 192, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/Users/sanbo/dev/mitm/mitmproxy/mitmproxy/tools/console/statusbar.py", line 139, in keypress
    self.command_history.add_command(self._w.cbuf, True)
AttributeError: 'Edit' object has no attribute 'cbuf'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

##### System information

Mitmproxy: 5.0.0.dev (+237, commit 8353f4a)
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-18.6.0-x86_64-i386-64bit

**Comment by hhhaiai** [comment]
https://github.com/Transfusion/mitmproxy/commit/490e9fa73c0953078e4e4e603a231a867522af9d

**Comment by hhhaiai** [comment]
fixed
