### ISSUE TITLE
Permission denied: '/root/.mitmproxy'

### ISSUE THREAD

**Issue by josh7** [mitmproxy/mitmproxy#3588]
I installed mitmproxy in django project and run it in docker, but getting this problem.

server: Ubuntu: 18.04

```
class StartView(APIView):

    def get(self, request):
        path = os.path.join(BASE_DIR, 'mockup', 'mock_addon.py')
        os.system('mitmdump -s %s -p %s' % (path, PROXY_PORT))
        return Response({'msg': '1'})
```

```
mitm_1        | Traceback (most recent call last):
mitm_1        |   File "/usr/local/bin/mitmdump", line 10, in <module>
mitm_1        |     sys.exit(mitmdump())
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/tools/_main.py", line 166, in mitmdump
mitm_1        |     m = run(dump.DumpMaster, cmdline.mitmdump, args, extra)
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/tools/_main.py", line 95, in run
mitm_1        |     pconf = process_options(parser, opts, args)
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/tools/_main.py", line 59, in process_options
mitm_1        |     return proxy.config.ProxyConfig(opts)
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/config.py", line 43, in __init__
mitm_1        |     self.configure(options, set(options.keys()))
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/config.py", line 60, in configure
mitm_1        |     CONF_BASENAME
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/certs.py", line 184, in from_store
mitm_1        |     key, ca = cls.create_store(path, basename)
mitm_1        |   File "/usr/local/lib/python3.6/site-packages/mitmproxy/certs.py", line 201, in create_store
mitm_1        |     os.makedirs(path)
mitm_1        |   File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
mitm_1        |     mkdir(name, mode)
mitm_1        | PermissionError: [Errno 13] Permission denied: '/root/.mitmproxy'
```

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
