### ISSUE TITLE
OSError: [Errno 24] Too many open files on macOS Mojave

### ISSUE THREAD

**Issue by nlykkei** [mitmproxy/mitmproxy#3598]
I'm having the below issue, when opening a few tabs in Firefox configured to use `mitmproxy` as its HTTP proxy server. The error can easily be reproduced. How to mitigate the error?

### Steps to reproduce:
1. Start mitmproxy `mitmproxy --listen-host 127.0.0.1 --listen-port 8080`
2. Configure Firefox to use `mitmproxy` as HTTP proxy.
3. Open +3 websites in tabs.

### System information:
```
Nicolass-MacBook-Pro:~ nlykkei$ mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.7.4
OpenSSL:   OpenSSL 1.0.2s  28 May 2019
Platform:  Darwin-18.6.0-x86_64-i386-64bit
```

### Error information:
```
: Exception in thread ServerThread (('::ffff:127.0.0.1', 8080, 0, 0)):
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/master.py", line 37, in run
    self.server.serve_forever()
  File "/usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/mitmproxy/net/tcp.py", line 607, in serve_forever
    connection, client_address = self.socket.accept()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files
```

### Files opened by mitmproxy:
```
Nicolass-MacBook-Pro:~ nlykkei$ lsof -np 1708
COMMAND    PID    USER   FD      TYPE             DEVICE  SIZE/OFF    NODE NAME
python3.7 1708 nlykkei  cwd       DIR                1,5      2272 1078647 /Users/nlykkei
python3.7 1708 nlykkei  txt       REG                1,5     12552 8894163 /usr/local/Cellar/mitmproxy/4.0.4/libexec/bin/python3.7
python3.7 1708 nlykkei  txt       REG                1,5   2361608 8754397 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Python
python3.7 1708 nlykkei  txt       REG                1,5     18192 8754600 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     30176 8754568 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/zlib.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     16648 8754583 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_bz2.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     32360 8754574 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_lzma.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    134356 7854609 /usr/local/Cellar/xz/5.2.4/lib/liblzma.5.dylib
python3.7 1708 nlykkei  txt       REG                1,5     14952 8754558 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/grp.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     38136 8754547 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     25148 8754605 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     15812 8754576 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     30976 8754575 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/select.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     37248 8754588 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     76616 8754579 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_datetime.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    172236 8754573 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/pyexpat.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     26868 8754559 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_hashlib.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    371128 7801663 /usr/local/Cellar/openssl/1.0.2s/lib/libssl.1.0.0.dylib
python3.7 1708 nlykkei  txt       REG                1,5   1864096 7801648 /usr/local/Cellar/openssl/1.0.2s/lib/libcrypto.1.0.0.dylib
python3.7 1708 nlykkei  txt       REG                1,5     33988 8754546 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_blake2.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     84060 8754549 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_sha3.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      9812 8754564 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_bisect.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     15308 8754612 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_random.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     75932 8754556 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      9096 8754603 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_opcode.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    102512 8754551 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      8956 8754607 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_contextvars.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     56608 8754563 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_asyncio.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     15880 8754545 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_queue.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      8936 8754599 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_uuid.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5   1057884 8754566 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/unicodedata.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    106348 8754581 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      9492 8894774 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so
python3.7 1708 nlykkei  txt       REG                1,5    146848 8895731 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    745832 8894775 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
python3.7 1708 nlykkei  txt       REG                1,5    313172 8894984 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/_ruamel_yaml.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     48908 8754548 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/array.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5    712320 8894921 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/brotli/_brotli.abi3.so
python3.7 1708 nlykkei  txt       REG                1,5     30540 8754552 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_csv.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     34936 8754604 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_json.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      8736 8895511 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/tornado/speedups.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     88416 8754570 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     76496 8754586 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_curses.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     18648 8754550 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/fcntl.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5      8712 8754594 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_crypt.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     15396 8754597 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_scproxy.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     14636 8894215 /usr/local/Cellar/mitmproxy/4.0.4/libexec/lib/python3.7/site-packages/urwid/str_util.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     19252 8754569 /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/termios.cpython-37m-darwin.so
python3.7 1708 nlykkei  txt       REG                1,5     21024 9472536 /Library/Preferences/Logging/.plist-cache.Xd28eiEW
python3.7 1708 nlykkei  txt       REG                1,5    973824 6227558 /usr/lib/dyld
python3.7 1708 nlykkei    0u      CHR               16,4 0t9069022    1157 /dev/ttys004
python3.7 1708 nlykkei    1u      CHR               16,4 0t9069022    1157 /dev/ttys004
python3.7 1708 nlykkei    2u      CHR               16,4 0t9069022    1157 /dev/ttys004
python3.7 1708 nlykkei    3u   KQUEUE                                      count=0, state=0xa
python3.7 1708 nlykkei    4u     unix 0xf3d07d8d37cfa23f       0t0         ->0xf3d07d8d37cfb9af
python3.7 1708 nlykkei    5u     unix 0xf3d07d8d37cfb9af       0t0         ->0xf3d07d8d37cfa23f
python3.7 1708 nlykkei    6u      CHR               16,4 0t9069022    1157 /dev/ttys004
python3.7 1708 nlykkei    7u     IPv6 0xf3d07d8d35285eff       0t0     TCP 127.0.0.1:http-alt (LISTEN)
python3.7 1708 nlykkei    8u    systm 0xf3d07d8d384451bf       0t0         [ctl com.apple.netsrc id 8 unit 33]
python3.7 1708 nlykkei    9      PIPE 0xf3d07d8d330b7bbf     16384         ->0xf3d07d8d330b527f
python3.7 1708 nlykkei   10      PIPE 0xf3d07d8d330b527f     16384         ->0xf3d07d8d330b7bbf
python3.7 1708 nlykkei   12   NPOLICY                                      
python3.7 1708 nlykkei   31u     IPv6 0xf3d07d8d37b634bf       0t0     TCP 127.0.0.1:http-alt->127.0.0.1:54887 (ESTABLISHED)
python3.7 1708 nlykkei   34u     IPv4 0xf3d07d8d2cc12f7f       0t0     TCP 192.168.0.141:54901->185.29.135.42:https (ESTABLISHED)
python3.7 1708 nlykkei   73u     IPv4 0xf3d07d8d35167bff       0t0     TCP 192.168.0.141:54902->185.29.135.42:https (ESTABLISHED)
python3.7 1708 nlykkei  120u     IPv6 0xf3d07d8d37bc693f       0t0     TCP 127.0.0.1:http-alt->127.0.0.1:54882 (ESTABLISHED)
python3.7 1708 nlykkei  168u     unix 0xf3d07d8d37cfa3cf       0t0         ->0xf3d07d8d37cfa307

```

**Comment by mhils** [comment]
This should be fixed on master. If that's not the case, please open a new issue!
