### ISSUE TITLE
cut.clip request.raw_content crashes mitmproxy

### ISSUE THREAD

**Issue by christoph-winf** [mitmproxy/mitmproxy#3599]
##### Steps to reproduce the problem:

1. open an set of with recorded flows with mitmproxy
2. choose a flow press "CTRL" + "L" (lowcase L) and insert "@focus request.raw_content" to start the cut.clip command to copy the raw content of the request
3. mitmproxy crashes (see error message below)

crash message: 
$ mitmproxy -r 190709_mpow_experiment1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.6/dist-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1119, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/statusbar.py", line 187, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/statusbar.py", line 135, in keypress
    self.prompt_execute(self._w.get_edit_text())
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/statusbar.py", line 155, in prompt_execute
    msg = p(txt)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/commandexecutor.py", line 17, in __call__
    ret = self.master.commands.execute(cmd)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/command.py", line 245, in execute
    return self.call_strings(parts[0], parts[1:])
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/command.py", line 233, in call_strings
    return self.commands[path].call(args)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/command.py", line 105, in call
    ret = self.func(*self.prepare_args(args))
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/command.py", line 275, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/addons/cut.py", line 133, in clip
    fp.write(strutils.always_str(v))
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/utils/strutils.py", line 24, in always_str
    return str_or_bytes.decode(*decode_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

##### Any other comments? What have you tried so far?
Same problem occures with this cut.clip commands:
"request.text",         
 "request.content", 

##### System information

$ mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-55-generic-x86_64-with-LinuxMint-19.1-tessa

**Comment by ylmrx** [comment]
I can't reproduce, can you share the flow ?
