### ISSUE TITLE
mitmproxy is not working on Kali Linux (no attribute 'WSGIAdapter')

### ISSUE THREAD

**Issue by johhnry** [mitmproxy/mitmproxy#3618]
Hi guys,

I am on Kali Linux (4.19.0-kali5-amd64 #1 SMP Debian x86_64 GNU/Linux) and I never used mitmproxy before, it was pre-installed by default.

##### Steps to reproduce the problem:

1. Running `mitmproxy` from command line

##### System information

This is the output of the console : 

```
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 11, in <module>
    load_entry_point('mitmproxy==4.0.4', 'console_scripts', 'mitmproxy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/main.py", line 22, in <module>
    from ._main import *  # noqa
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/_main.py", line 13, in <module>
    from mitmproxy.tools import cmdline  # noqa
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/cmdline.py", line 3, in <module>
    from mitmproxy.addons import core
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/__init__.py", line 11, in <module>
    from mitmproxy.addons import onboarding
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboardingapp/app.py", line 13, in <module>
    class Adapter(tornado.wsgi.WSGIAdapter):
AttributeError: module 'tornado.wsgi' has no attribute 'WSGIAdapter'
```

Thanks in advance

**Comment by cserb** [comment]
same here on arch linux

**Comment by lfalke** [comment]
same here. Is there a workaround?

**Comment by qwelias** [comment]
Same error for 
`Linux epamrgos 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux`

**Comment by fabmazz** [comment]
Same problem here, using arch linux, with python tornado 6.0.3 library. It seems that this library has changed, and since arch likes to keep all packages up-to-date with upstream, it has published this new version.
I tried building mitmproxy from git (latest commit, 0b0b4cc), but all tests fail:
```ERROR collecting test/examples/test_examples.py ________________
test/examples/test_examples.py:4: in <module>
    from mitmproxy.test import taddons
mitmproxy/test/taddons.py:10: in <module>
    from mitmproxy.addons import script, core
mitmproxy/addons/__init__.py:11: in <module>
    from mitmproxy.addons import onboarding
mitmproxy/addons/onboarding.py:2: in <module>
    from mitmproxy.addons.onboardingapp import app
mitmproxy/addons/onboardingapp/app.py:13: in <module>
    class Adapter(tornado.wsgi.WSGIAdapter):
E   AttributeError: module 'tornado.wsgi' has no attribute 'WSGIAdapter'
```
This means that it has to be considered a bug of mitmproxy,

**Comment by nomis6432** [comment]
Looks like python tornado has removed WSGIAdapter since version 6.0 . 

https://www.tornadoweb.org/en/stable/releases/v6.0.0.html?highlight=WSGIAdapter

Downgrading to an earlier version should fix the issue for the time being.

**Comment by piescotch** [comment]
This issue I think has been fixed with commit https://github.com/mitmproxy/mitmproxy/commit/902ef59d01f45613ce33520159e157697bcc6f9f
