### ISSUE TITLE
start proxy from python

### ISSUE THREAD

**Issue by chuky3000x** [mitmproxy/mitmproxy#3621]
I try to start the mitmproxy from python script. I have found a solution for this [here](https://stackoverflow.com/questions/50789144/i-need-an-alternative-to-mitmproxy-for-python).

But for this code i get an error:

```
root@debian:/bin/test# python3 testproxy
['<mitmproxy.addons.termlog.TermLog object at 0x7f70052f7940>',
 '<mitmproxy.addons.termstatus.TermStatus object at 0x7f70052f7978>',
 '<mitmproxy.addons.core.Core object at 0x7f70052f79b0>',
 '<mitmproxy.addons.browser.Browser object at 0x7f70052f79e8>',
 '<mitmproxy.addons.block.Block object at 0x7f70052f7a58>',
 '<mitmproxy.addons.anticache.AntiCache object at 0x7f70052f7a20>',
 '<mitmproxy.addons.anticomp.AntiComp object at 0x7f70052f7ac8>',
 '<mitmproxy.addons.check_ca.CheckCA object at 0x7f70052f7b00>',
 '<mitmproxy.addons.clientplayback.ClientPlayback object at 0x7f70052f7b38>',
 '<mitmproxy.addons.cut.Cut object at 0x7f70052f7c50>',
 '<mitmproxy.addons.disable_h2c.DisableH2C object at 0x7f70052f7c88>',
 '<mitmproxy.addons.export.Export object at 0x7f70052f7cc0>',
 '<mitmproxy.addons.onboarding.Onboarding object at 0x7f70052f7cf8>',
 '<mitmproxy.addons.proxyauth.ProxyAuth object at 0x7f70052f7d68>',
 '<mitmproxy.addons.replace.Replace object at 0x7f70052f7dd8>',
 '<mitmproxy.addons.script.ScriptLoader object at 0x7f70052f7e10>',
 '<mitmproxy.addons.serverplayback.ServerPlayback object at 0x7f70052f7e48>',
 '<mitmproxy.addons.setheaders.SetHeaders object at 0x7f70052f7e80>',
 '<mitmproxy.addons.stickyauth.StickyAuth object at 0x7f70052f7eb8>',
 '<mitmproxy.addons.stickycookie.StickyCookie object at 0x7f70052f7ef0>',
 '<mitmproxy.addons.streambodies.StreamBodies object at 0x7f70052f7f28>',
 '<mitmproxy.addons.save.Save object at 0x7f70052f7f60>',
 '<mitmproxy.addons.upstream_auth.UpstreamAuth object at 0x7f70052f7f98>',
 '<mitmproxy.addons.dumper.Dumper object at 0x7f70052f7fd0>',
 '<mitmproxy.addons.keepserving.KeepServing object at 0x7f7005285668>',
 '<mitmproxy.addons.readfile.ReadFileStdin object at 0x7f7005285588>',
 '<mitmproxy.tools.dump.ErrorCheck object at 0x7f70052f7908>']
Proxy server listening at http://127.0.0.1:8080
127.0.0.1:53014: clientconnect
127.0.0.1:53014: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http.py", line 254, in _process_flow
    self.read_request_body(f.request)
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http1.py", line 23, in read_request_body
    human.parse_size(self.config.options.body_size_limit)
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/optmanager.py", line 172, in __getattr__
    raise AttributeError("No such option: %s" % attr)
AttributeError: No such option: body_size_limit

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http.py", line 254, in _process_flow
    self.read_request_body(f.request)
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http1.py", line 23, in read_request_body
    human.parse_size(self.config.options.body_size_limit)
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/optmanager.py", line 172, in __getattr__
    raise AttributeError("No such option: %s" % attr)
AttributeError: No such option: body_size_limit

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

I would like to use mitmproxy to capture http request and response to  extract the cookies (first and third party) from it. For this purposes i would like to start the proxy, open a website with selenium, capture the requests and responses and finally analyse on "Cookie" and "Set-Cookie" fields in the headers.

**Comment by mhils** [comment]
I don't think this is a mitmproxy issue but an issue in your code.
