### ISSUE TITLE
mitmproxy crashed

### ISSUE THREAD

**Issue by doraeqing** [mitmproxy/mitmproxy#3636]
```
Traceback (most recent call last):
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/Users/xxx/venv_godeye/lib/python3.7/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by ylmrx** [comment]
Hi, 

Can you provide some informations on what you were doing when it crashed ? The last few requests, or any scenario so we can reproduce this behavior ?
