### ISSUE TITLE
Forwarding proxy crashes when trying to view details of a POST containing multipart file data

### ISSUE THREAD

**Issue by bdobrzelecki** [mitmproxy/mitmproxy#3637]
admins-MacBook-Pro:~ bartek$ miproxyeb --mode reverse:https://host
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/listbox.py", line 501, in render
    canvas = widget.render((maxcol,))
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/widget.py", line 1004, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/canvas.py", line 1315, in apply_text_layout
    return TextCanvas(t, a, c, maxcol=maxcol)
  File "/usr/local/Cellar/mitmproxy/4.0.4_1/libexec/lib/python3.7/site-packages/urwid/canvas.py", line 358, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified
134
[119, 123, 134, 134, 25, 116, 134, 134, 134, 134, 134, 135, 134, 134, 97, 120, 135, 135, 135, 134, 134, 111, 135, 108, 134, 134, 134, 83, 134, 122, 79, 133, 129, 134, 121, 17, 119, 135, 134, 93, 76, 134, 134, 98, 127, 135, 134, 135, 121, 39, 128, 20, 134, 135, 134, 136, 134, 134, 75, 134, 135, 136, 134, 134, 134, 135, 33, 133, 89, 134, 133, 134, 92, 135, 135, 136, 109, 132, 136, 134, 134, 135, 115, 135, 118, 97, 73, 90, 130, 132, 134, 84, 126, 134, 134, 134, 109, 135, 136, 135, 63, 134, 134, 110, 107, 133, 134, 134, 134, 134, 135, 134, 119, 62, 134, 136, 31, 134, 134, 131, 133, 135, 135, 135, 75, 93, 134, 92, 135, 135, 134, 20, 134, 135, 79, 134, 119, 131, 128, 41, 136, 134, 122, 134, 120, 136, 102, 129, 133, 132, 1, 134, 135, 134, 138, 136, 105, 129, 58, 78, 134, 134, 135, 87, 95, 97, 136, 134, 14, 134, 127, 135, 135, 133, 136, 59, 134, 133, 136, 134, 134, 134, 110, 134, 134, 101, 46, 134, 134, 73, 135, 116, 130, 89, 79, 134, 130, 104, 84, 76, 135, 135, 135, 134, 135, 95, 104, 134, 22, 133, 133, 101, 34, 135, 132, 134, 135, 99, 88, 134, 134, 136, 134, 134, 83, 134, 120, 134, 134, 133, 115, 111, 134, 134, 134, 133, 126, 134, 134, 134, 79, 132, 85, 90, 54, 95, 134, 137, 135, 134, 135, 1, 136, 73, 134, 134, 93, 132, 106, 65, 134, 135, 134, 134, 135, 90, 82, 114, 135, 134, 133, 133, 1, 134, 41, 135, 54, 134, 134, 39, 131, 134, 134, 136, 132, 134, 134, 135, 134, 135, 134, 135, 135, 135, 131, 35, 111, 93, 50, 134, 134, 131, 116, 134, 134, 134, 128, 136, 133, 1, 135, 8, 135, 118, 134, 83, 134, 134, 114, 134, 134, 135, 133, 135, 136, 134, 130, 38, 135, 134, 134, 135, 133, 1, 135, 134, 133, 112, 106, 134, 135, 134, 135, 106, 61]
[b'file:            ?PNG....IHDR..~...?.....X.?~....sRGB.??.?...\tpHYs...#...#.x??v...YiTXtXML:com.adobe.xmp.....<x:xmpmeta

**Comment by mhils** [comment]
Thanks for filing this! I can't really seem to reproduce this, could you share a flow file with a flow that crashes mitmproxy?

Thanks!
