### ISSUE TITLE
mitmproxy 5.0 faults on requests, Linux Mint 19.2

### ISSUE THREAD

**Issue by CoolCold** [mitmproxy/mitmproxy#3757]
#### Problem Description
Running mitmproxy in transparent mode - after several seconds (requests) it fails. Error message is:
```
coolcold@coolcold-ThinkPad-X230:~/mitmproxy-5.0.0$ ./mitmproxy -v --mode transparent
Traceback (most recent call last):
  File "mitmproxy/master.py", line 86, in run_loop
  File "site-packages/urwid/main_loop.py", line 286, in run
  File "site-packages/urwid/main_loop.py", line 384, in _run
  File "site-packages/urwid/main_loop.py", line 1484, in run
  File "site-packages/urwid/compat.py", line 58, in reraise
  File "asyncio/events.py", line 88, in _run
  File "site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
  File "site-packages/urwid/main_loop.py", line 572, in entering_idle
  File "site-packages/urwid/main_loop.py", line 586, in draw_screen
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/container.py", line 1086, in render
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/decoration.py", line 226, in render
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/container.py", line 1086, in render
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/listbox.py", line 471, in render
  File "site-packages/urwid/listbox.py", line 356, in calculate_visible
  File "mitmproxy/tools/console/flowlist.py", line 57, in get_focus
  File "mitmproxy/tools/console/flowlist.py", line 12, in __init__
  File "mitmproxy/tools/console/flowlist.py", line 22, in get_text
  File "mitmproxy/tools/console/common.py", line 561, in format_flow
  File "mitmproxy/tools/console/common.py", line 427, in raw_format_table
  File "mitmproxy/tools/console/common.py", line 200, in colorize_host
  File "site-packages/publicsuffix2/__init__.py", line 356, in get_tld
  File "site-packages/publicsuffix2/__init__.py", line 86, in __init__
  File "/home/runner/work/mitmproxy/mitmproxy/.tox/cibuild/lib/python3.7/codecs.py", line 904, in open
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEI07uosx/publicsuffix2/public_suffix_list.dat'

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```
path in message
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEI07uosx/publicsuffix2/public_suffix_list.dat'
```
changes for random part, i.e. can be `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIfgpH44/publicsuffix2/public_suffix_list.dat'`

#### Steps to reproduce the behavior:
1. run mitmproxy with `./mitmproxy -v --mode transparent`
2. wait
3. fail

#### System Information
Paste the output of "mitmproxy --version" here.
```
coolcold@coolcold-ThinkPad-X230:~/mitmproxy-5.0.0$ ./mitmproxy --version
Mitmproxy: 5.0.0 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid
```
OS
```
coolcold@coolcold-ThinkPad-X230:~/mitmproxy-5.0.0$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 19.2 Tina
Release:        19.2
Codename:       tina
```

https://snapshots.mitmproxy.org/5.0.0/mitmproxy-5.0.0-linux.tar.gz is the source of binaries.

UPDATE: checked with 4.0.4 - so far for 200 request works fine

**Comment by newkedison** [comment]
same issue for me when run in upstream mode

OS: 
```
No LSB modules are available. 
Distributor ID: Ubuntu 
Description:    Ubuntu 16.04.6 LTS   
Release:        16.04  
Codename:       xenial  
```

mitmproxy version:
````
Mitmproxy: 5.0.0 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-4.4.0-143-generic-x86_64-with-debian-stretch-sid
````

**Comment by Kriechi** [comment]
@mhils is this a problem with the new CI that it fails at included certain files? Or is publicsuffix2 broken for us?

**Comment by mhils** [comment]
Ugh, that seems to be a PyInstaller issue. Let's ship a patch release.

**Comment by mhils** [comment]
56e108bcfc7ef9e151b543aab3576856bfa6d322 should fix this, once CI passes we'll have a new release.

**Comment by mhils** [comment]
5.0.1 is available, thanks again! 😃
