### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'find'

### ISSUE THREAD

**Issue by abinhho** [mitmproxy/mitmproxy#3765]
#### Problem Description
I tried to run successfully but when I hit ESC, below error displayed.

#### Steps to reproduce the behavior:
1. Run `$ mitmproxy -p 9999 --mode socks5 --showhost`
```
Traceback (most recent call last):
  File "/Users/binhho/Documents/t-mobile/mitmproxy/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/raw_display.py", line 475, in parse_input
    codes, wait_for_more)
  File "/Users/binhho/Documents/t-mobile/mitmproxy/venv/lib/python3.7/site-packages/urwid/escape.py", line 387, in process_keyqueue
    if run[0] == "esc" or run[0].find("meta ") >= 0:
AttributeError: 'tuple' object has no attribute 'find'
```
#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 6.0.0.dev (+17, commit 406f8ac)
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-19.2.0-x86_64-i386-64bit
```

**Comment by Kriechi** [comment]
This should be fixed in the recent urwid version 2.1.0: https://github.com/urwid/urwid/pull/304
We need to test and fix incompatibilities with this new dependency.
