### ISSUE TITLE
mitmdump fails after install

### ISSUE THREAD

**Issue by jlaw9** [mitmproxy/mitmproxy#3776]
#### Problem Description
After installing mitmproxy, I get the following OpenSSL.crypto error when running mitmdump:

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 11, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/_main.py", line 164, in mitmdump
    m = run(dump.DumpMaster, cmdline.mitmdump, args, extra)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/_main.py", line 94, in run
    pconf = process_options(parser, opts, args)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/_main.py", line 56, in process_options
    return proxy.config.ProxyConfig(opts)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/config.py", line 41, in __init__
    self.configure(options, set(options.keys()))
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/config.py", line 68, in configure
    key_size
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/certs.py", line 201, in from_store
    raw)
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/crypto.py", line 1837, in load_certificate
    _raise_current_error()
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
```

#### Steps to reproduce the behavior:
1. `pip3 install mitmproxy`
2. `mitmdump`

#### System Information
Mitmproxy: 5.0.1
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-4.15.0-66-generic-x86_64-with-LinuxMint-19.1-tessa

**Comment by mhils** [comment]
DId you have a preexisting ~/.mitmproxy folder? Does ~/.mitmproxy/mitmproxy-ca.pem have any contents?

**Comment by jlaw9** [comment]
Yes I did, and that file was empty. Removing that folder fixed the problem. Thank you!
