### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by SandyLinhNguyen** [mitmproxy/mitmproxy#3790]
#### Problem Description
Sorry for my bad english.
I was using [locust-replay](https://github.com/zlorb/locust.replay) and it base on mitmproxy to write a scenario for load test

#### Steps to reproduce the behavior:
1. Using command: mitmproxy --anticache -s locust_extractor.py
2. Using option: locust.code.clip @all
After that it show the output below:
Traceback (most recent call last):
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/Users/linhsandy/Downloads/mitmproxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1119, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/tools/console/statusbar.py", line 201, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/tools/console/statusbar.py", line 149, in keypress
    self.prompt_execute(text)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/tools/console/statusbar.py", line 169, in prompt_execute
    msg = p(txt)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/tools/console/statusbar.py", line 115, in execute_command
    execute(txt)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/command.py", line 265, in execute
    return self.call_strings(command_name, args)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/command.py", line 251, in call_strings
    return self.commands[command_name].call(args)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/Users/linhsandy/Downloads/mitmproxy/mitmproxy/command.py", line 295, in wrapper
    return function(*args, **kwargs)
  File "locust_extractor.py", line 224, in code_clip
    data = strutils.always_str(self.context.locust_code(flows[0]))
IndexError: list index out of range

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

#### System Information
MacOS Mini High Sierra

Python version: 3.8.1

Mitmproxy: 6.0.0.dev (+33, commit b020a11)
Python:    3.8.1
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  macOS-10.13.6-x86_64-i386-64bit

**Comment by mhils** [comment]
As indicated in the last line, this seems to be an issue in `locust_extractor.py`, which isn't part of mitmproxy. Please contact the locust folks! 😃
