### ISSUE TITLE
Crash - most recent call last - rawtcp

### ISSUE THREAD

**Issue by evadogstar** [mitmproxy/mitmproxy#3810]
#### Problem Description
Time to time proxy crash with this errors. The same for `mimtdump`

`error: 192.168.1.2:49336: Traceback (most recent call last):                                                                                                       
  File "mitmproxy/proxy/server.py", line 121, in handle                                                                                                                File "mitmproxy/proxy/modes/reverse_proxy.py", line 13, in __call__                                                                                                
  File "mitmproxy/proxy/protocol/tls.py", line 285, in __call__                                                                                                        File "mitmproxy/proxy/protocol/rawtcp.py", line 47, in __call__                                                                                                    
TypeError: shutdown() takes 1 positional argument but 2 were given  
`
#### Steps to reproduce the behavior:
It is reverse proxy with this additional params `--ssl-insecure  --tcp '.*' -s ./xxx.py` 
`xxx.py` simple script from example that change some chars in raw text.

#### System Information

Mitmproxy: 5.0.1 binary
Python:    3.7.5

**Comment by evadogstar** [comment]
@Kriechi I don't know. It's only what I see at my console output....

**Comment by mhils** [comment]
> Very curios crash:
> 
> https://github.com/mitmproxy/mitmproxy/blob/735b8e35c9d142e43f002dfe224f431399548e3b/mitmproxy/proxy/protocol/rawtcp.py#L47
> 
> 
> This should never receive two arguments... or is this traceback misleading?

I believe `self` is the first argument here.

**Comment by evadogstar** [comment]
@mhils if it's possible.... maybe issue related to ipv6. I guess after I disable ipv6 on the system issue do not come again. But it's not 100%

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
