### ISSUE TITLE
mitmweb "Address already in use" on MacOS 10.15

### ISSUE THREAD

**Issue by gstaniak** [mitmproxy/mitmproxy#3812]
#### Problem Description
tornado/netutil.py, line 174 throws OSError (48) "Address already in use" when starting mitmweb -- mitmproxy 4.04. from macports, Tornado 6.0.3_0 pulled as a dependency. I'm positive nothing actually listens on the port I select (or on the default one for that matter). Could this be related to ports?

#### Steps to reproduce the behavior:
1. $ mitmweb-3.7 --listen-host 127.0.0.1 --listen-port 65012
Traceback (most recent call last):
  File "/opt/local/bin/mitmweb-3.7", line 11, in <module>
    load_entry_point('mitmproxy==4.0.4', 'console_scripts', 'mitmweb')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 174, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 133, in run
    master.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mitmproxy/tools/web/master.py", line 110, in run
    http_server.listen(self.options.web_port, self.options.web_iface)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
2. $ nc -l 65012
3. $ lsof -i -n -P | egrep LIST
Spotify    2141 <user>   33u  IPv4 0xe37c6710344ffca9      0t0  TCP *:59116 (LISTEN)
Spotify    2141 <user>   52u  IPv4 0xe37c67101dedf4a1      0t0  TCP *:57621 (LISTEN)
nc        17929 <user>    3u  IPv4 0xe37c67101c2ef831      0t0  TCP *:65012 (LISTEN)

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 4.0.4
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Darwin-19.2.0-x86_64-i386-64bit

**Comment by gstaniak** [comment]
This is for a newer version installed by pip with all-dependencies (after uninstalling all relevant ports):

$ mitmweb
Traceback (most recent call last):
  File "/Users/<user>/Library/Python/3.7/bin/mitmweb", line 8, in <module>
    sys.exit(mitmweb())
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/mitmproxy/tools/_main.py", line 172, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/mitmproxy/tools/_main.py", line 131, in run
    master.run()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/mitmproxy/tools/web/master.py", line 110, in run
    http_server.listen(self.options.web_port, self.options.web_iface)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use

[greg.staniak@dyngus ~]$ mitmproxy --version
Mitmproxy: 5.0.1
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-19.2.0-x86_64-i386-64bit

**Comment by mhils** [comment]
> OSError: [Errno 48] Address already in use

MacOS returns an error when mitmproxy tries to bind to 65012. I think this is not a mitmproxy bug, but maybe macOS now allowing you to bind to ephemeral ports.

**Comment by gstaniak** [comment]
I don't think it's an OS issue: I can start mitmproxy on port 65012 without any issue, it's mitmweb that has a problem with that, in the versions and configurations that I tried. Please re-open the ticket.

**Comment by hsskey** [comment]
@gstaniak Hi did u solve this issue?
almost same here like this

```
## working well
mitmproxy
```

```
## it is not working 
(Error starting proxy server: OSError(48, 'Address already in use')
mitmweb
```

**Comment by gstaniak** [comment]
Hi @hsskey, I didn't solve it anyway. The issue was closed as an OS-level problem, even though it didn't look like that at all. I just switched to Charles.

**Comment by mhils** [comment]
If mitmproxy is working but mitmweb isn't, we probably can't bind to port 8081. We don't do anything fancy at all here, so you likely have something running on 8081.

**Comment by hsskey** [comment]
@mhils thansk for your reply but it is not real
cuz when i checked port 80 (sudo lsof -i :81) 
there is no using port on my mac
