### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by yarafan** [mitmproxy/mitmproxy#3819]
#### Problem Description
 ```
Traceback (most recent call last):                                                                                                                                        [5/8175]
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/container.py", line 1085, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/container.py", line 1085, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/listbox.py", line 470, in render
    middle, top, bottom = self.calculate_visible(
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/listbox.py", line 416, in calculate_visible
    next, pos = self._body.get_next( pos )
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 68, in get_next
    f = FlowItem(self.master, self.master.view[pos])
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 12, in __init__
    w = self.get_text()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 17, in get_text
    return common.format_flow(
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/common.py", line 561, in format_flow
    return raw_format_table(tuple(sorted(d.items())))
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/common.py", line 488, in raw_format_table
    rc = 'gradient_%02d' % int(99 - 100 * min(math.log2(1 + 1000 * f['duration']) / 12, 0.99))
ValueError: math domain error
```
#### Steps to reproduce the behavior:
1. Save replay with mitmdump for https request
2. edit request body
3. Save flow
4. Replay flow

#### System Information
Mitmproxy: 5.0.1
Python:    3.8.1
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  macOS-10.15.3-x86_64-i386-64bit

**Comment by italankin** [comment]
Seems like a duplicate of 3778

**Comment by yarafan** [comment]
Build from master branch works as expected, brew version is outdated
