### ISSUE TITLE
mitmproxy has crashed! TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by nikhiljakks** [mitmproxy/mitmproxy#3842]
I'm adding a 12 seconds delay to the response using a custom addon 

```
class http_proxy:
              def response(self, flow):
                       time.sleep(12) 


addons = [
    http_proxy()
]
```

```
Traceback (most recent call last):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 414, in _process_flow
    self.send_response(f.response)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 41, in send_response
    self.send_response_headers(response)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 53, in send_response_headers
    raw = http1.assemble_response_head(response)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/net/http/http1/assemble.py", line 28, in assemble_response_head
    first_line = _assemble_response_line(response.data)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/net/http/http1/assemble.py", line 93, in _assemble_response_line
    return b"%s %d %s" % (
TypeError: %d format: a number is required, not NoneType

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1085, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1085, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/listbox.py", line 470, in render
    middle, top, bottom = self.calculate_visible(
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/listbox.py", line 356, in calculate_visible
    focus_widget, focus_pos = self._body.get_focus()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 57, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 12, in __init__
    w = self.get_text()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 17, in get_text
    return common.format_flow(
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/common.py", line 561, in format_flow
    return raw_format_table(tuple(sorted(d.items())))
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/common.py", line 443, in raw_format_table
    ccol = codes.get(f["resp_code"] // 100, "code_other")
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
(venv) Nikhils-MacBook-Pro:http_proxy nikhiljakkannavar$ 
(venv) Nikhils-MacBook-Pro:http_proxy nikhiljakkannavar$ 
(venv) Nikhils-MacBook-Pro:http_proxy nikhiljakkannavar$ 
(venv) Nikhils-MacBook-Pro:http_proxy nikhiljakkannavar$ 
(venv) Nikhils-MacBook-Pro:http_proxy nikhiljakkannavar$ mitmproxy -s http_proxy.py --set respDelay=12 --set urlPattern="am_avchls290_clear"  --set maxCount=1
Traceback (most recent call last):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 414, in _process_flow
    self.send_response(f.response)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 41, in send_response
    self.send_response_headers(response)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 53, in send_response_headers
    raw = http1.assemble_response_head(response)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/net/http/http1/assemble.py", line 28, in assemble_response_head
    first_line = _assemble_response_line(response.data)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/net/http/http1/assemble.py", line 93, in _assemble_response_line
    return b"%s %d %s" % (
TypeError: %d format: a number is required, not NoneType

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1085, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1085, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/listbox.py", line 470, in render
    middle, top, bottom = self.calculate_visible(
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/urwid/listbox.py", line 356, in calculate_visible
    focus_widget, focus_pos = self._body.get_focus()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 57, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 12, in __init__
    w = self.get_text()
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 17, in get_text
    return common.format_flow(
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/common.py", line 561, in format_flow
    return raw_format_table(tuple(sorted(d.items())))
  File "/Users/nikhiljakkannavar/PycharmProjects/http_proxy/venv/lib/python3.8/site-packages/mitmproxy/tools/console/common.py", line 443, in raw_format_table
    ccol = codes.get(f["resp_code"] // 100, "code_other")
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```

**Comment by mhils** [comment]
1. Your example addon doesn't work, it misses an `import time`.
2. After fixing this, mitmproxy is working as expected for me.

This looks like you have a bug in some other addon you wrote.
