### ISSUE TITLE
pip install mitmproxy error when install zstandard on win10 

### ISSUE THREAD

**Issue by GZHua** [mitmproxy/mitmproxy#3860]
#### Problem Description

pip install mitmproxy error when install zstandard on win10 

#### Steps to reproduce the behavior:
1. pip install mitmproxy
2.
ERROR: Command errored out with exit status 1:
     command: 'd:\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\91644\\AppData\\Local\\Temp\\pip-install-qgx70sc1\\zstandard\\setup.py'"'"'; __file__='
"'"'C:\\Users\\91644\\AppData\\Local\\Temp\\pip-install-qgx70sc1\\zstandard\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(
compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\91644\AppData\Local\Temp\pip-install-qgx70sc1\zstandard\pip-egg-info'
         cwd: C:\Users\91644\AppData\Local\Temp\pip-install-qgx70sc1\zstandard\
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\91644\AppData\Local\Temp\pip-install-qgx70sc1\zstandard\setup.py", line 70, in <module>
        import make_cffi
      File "C:\Users\91644\AppData\Local\Temp\pip-install-qgx70sc1\zstandard\make_cffi.py", line 179, in <module>
        preprocessed = preprocess(header)
      File "C:\Users\91644\AppData\Local\Temp\pip-install-qgx70sc1\zstandard\make_cffi.py", line 127, in preprocess
        process = subprocess.Popen(args + [input_file], stdout=subprocess.PIPE,
      File "d:\programs\python\python38\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "d:\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] 系统找不到指定的文件。
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

#### System Information
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by GZHua** [comment]
I resolved it. 
use pip install mitmproxy in wsl, and add a .pth file which content is wsl's sit-packages address for window sit-packages
