### ISSUE TITLE
Gracefully handle non-existent file with --rfile

### ISSUE THREAD

**Issue by AdrianVollmer** [mitmproxy/mitmproxy#3934]
#### Problem Description
When trying to read a flow from a file that doesn't exist (maybe because of a typo), you get a TypeError exception. An error message saying the the file was not found would be better.

#### Steps to reproduce the behavior:
1. See:
```
$ mitmproxy --rfile non-existent-file
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/urwid/compat.py", line 55, in reraise
    value = tp()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```

#### System Information
Mitmproxy: 4.0.4
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.4.0-4-amd64-x86_64-with-glibc2.29

**Comment by sarthak212** [comment]
Maybe you should try the updated version of Mitmproxy. It shows proper error for this command.

**Comment by mhils** [comment]
Thanks @sarthak212!
