### ISSUE TITLE
Mitmproxy crash when using upstream and http2

### ISSUE THREAD

**Issue by Shnitzelil** [mitmproxy/mitmproxy#3943]
#### Problem Description
Starting mitmproxy (5.0.1 and also happen on 5.1.1, 5.2.0) using upstream mode.
Trying to access to wikipedia during this I faced crashes.
Disabling http2, working perfectly.

Traceback (most recent call last):
  File "mitmproxy\net\tcp.py", line 197, in peek
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 121, in handle
  File "mitmproxy\proxy\modes\http_proxy.py", line 23, in __call__
  File "mitmproxy\proxy\protocol\tls.py", line 285, in __call__
  File "mitmproxy\proxy\protocol\http1.py", line 83, in __call__
  File "mitmproxy\proxy\protocol\http.py", line 190, in __call__
  File "mitmproxy\proxy\protocol\http.py", line 264, in _process_flow
  File "mitmproxy\proxy\protocol\http.py", line 238, in handle_upstream_connect
  File "mitmproxy\proxy\protocol\http.py", line 89, in __call__
  File "mitmproxy\proxy\protocol\tls.py", line 278, in __call__
  File "mitmproxy\proxy\protocol\tls.py", line 368, in _establish_tls_with_client_and_server
  File "mitmproxy\proxy\protocol\tls.py", line 389, in _establish_tls_with_client
  File "mitmproxy\connections.py", line 139, in convert_to_tls
  File "mitmproxy\net\tls.py", line 477, in from_file
  File "mitmproxy\net\tls.py", line 410, in get_client_hello
  File "mitmproxy\net\tcp.py", line 199, in peek
mitmproxy.exceptions.TcpException: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

#### Steps to reproduce the behavior:
1. Start mitmproxy behind a proxy (use upstream mode)
2. Open IE
3. Navigate to wikipedia by using the search bar.

#### System Information
Mitmproxy: 5.1.1 binary
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Windows-10-10.0.18362-SP0

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.

**Comment by Arkango** [comment]
Hi, with the latest version mitmproxy with upstream crash too. Attached the exception occurred.

![Screenshot 2021-11-19 at 10 25 04](https://user-images.githubusercontent.com/23188987/142598802-2e412d9d-ed3f-4218-a0e2-705288270f88.png)

**Comment by mhils** [comment]
@Arkango: Please open a new issue with clear instructions on how this can be reproduced.
