### ISSUE TITLE
mitmproxy crashes when entering regex escape character in half-open string

### ISSUE THREAD

**Issue by liona24** [mitmproxy/mitmproxy#3949]
#### Problem Description
When adding a regex to the `replacements` option in interactive mode mitmproxy crashes when entering a leading `"` which is not yet closed followed by an escape character. 

#### Steps to reproduce the behavior:
1. Start `mitmproxy`
2. Type `: set replacements "/abc`
3. Now upon entering an escape character `\` mitmproxy crashes

It is working if you preemptively close the quotation marks, i.e. `: set replacements ""` and then continue entering your pattern within.

#### System Information

Crash Dump:
```
Traceback (most recent call last):
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/urwid/container.py", line 1119, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/tools/console/statusbar.py", line 201, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/tools/console/statusbar.py", line 152, in keypress
    self._w.keypress(size, k)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/tools/console/commander/commander.py", line 234, in keypress
    self.update()
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/tools/console/commander/commander.py", line 237, in update
    self._w.set_text([self.leader, self.cbuf.render()])
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/tools/console/commander/commander.py", line 74, in render
    parts, remaining = self.master.commands.parse_partial(self.text)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/mitmproxy/command.py", line 176, in parse_partial
    parts: typing.List[str] = command_lexer.expr.parseString(cmdstr, parseAll=True)
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/home/milk/.local/pipx/venvs/mitmproxy/lib/python3.6/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '"'  (at char 17), (line:1, col:18)

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```

Version:
```
Mitmproxy: 5.0.1
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by euan-b** [comment]
Hi. I've confirmed I can recreate with mitmproxy 5.0.1 (changeset 2204ee2d55843eff0857e16127a0e07477318df6) on Ubuntu 18.04 based container. i cannot recreate with latest master (changeset 3372b77e93c7adf98f6d067bf7bb01ded42054c0).
