### ISSUE TITLE
App crashed when trying to copy the response content using "cut.clip @focus response.raw_content"

### ISSUE THREAD

**Issue by arpitsinghmrt** [mitmproxy/mitmproxy#3965]
Crash log:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/raw_display.py", line 403, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/urwid/container.py", line 1119, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/statusbar.py", line 201, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/statusbar.py", line 149, in keypress
    self.prompt_execute(text)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/statusbar.py", line 169, in prompt_execute
    msg = p(txt)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/statusbar.py", line 115, in execute_command
    execute(txt)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/tools/console/commandexecutor.py", line 17, in __call__
    ret = self.master.commands.execute(cmd)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/command.py", line 265, in execute
    return self._call_strings(command_name, args)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/command.py", line 251, in _call_strings
    return self.commands[command_name].call(args)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/command.py", line 295, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/addons/cut.py", line 133, in clip
    fp.write(strutils.always_str(v))  # type: ignore
  File "/usr/local/Cellar/mitmproxy/5.0.1_1/libexec/lib/python3.8/site-packages/mitmproxy/utils/strutils.py", line 26, in always_str
    return str_or_bytes.decode(*decode_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

```

**Comment by mhils** [comment]
It's definitely a bug that we crash here, but for most purposes, you really want to use `.text` instead of `.raw_content` with `cut.clip`. Binary content and the clipboard really doesn't mix well.

**Comment by arpitsinghmrt** [comment]
Thanks, @mhils for the help. cheers
