### ISSUE TITLE
Crash when opening TCP flow view

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3972]
#### Problem Description

```
Traceback (most recent call last):
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/user/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/user/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/user/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/home/user/venv/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise                                                                                   [*:8080]
    raise value
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/user/venv/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/user/venv/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/user/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/user/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 312, in keypress
    return self.master.keymap.handle(
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/keymap.py", line 144, in handle
    return self.executor(b.command)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 266, in execute
    return self.call_strings(command_name, args)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/consoleaddons.py", line 192, in nav_select
    self.master.inject_key("m_select")
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/master.py", line 185, in inject_key
    self.loop.process_input([key])
  File "/home/user/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/home/user/venv/lib/python3.8/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/home/user/venv/lib/python3.8/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/flowlist.py", line 103, in keypress
    self.master.commands.execute("console.view.flow @focus")
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 266, in execute
    return self.call_strings(command_name, args)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/consoleaddons.py", line 339, in view_flow
    self.master.switch_view("flowview")
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/master.py", line 222, in switch_view
    self.window.push(name)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 234, in push
    self.focus_changed()
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 211, in focus_changed
    i.call("focus_changed")
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/window.py", line 120, in call
    getattr(self.top_window(), name)(*args, **kwargs)
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/flowview.py", line 319, in focus_changed
    self.body.focus_changed()
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/flowview.py", line 75, in focus_changed
    self.show()
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/tabs.py", line 73, in show
    body = self.tabs[self.tab_offset][1](),
IndexError: list index out of range
```` 

#### Steps to reproduce the behavior:
1. mitmproxy -nr [`repro.mitm`](https://github.com/mitmproxy/mitmproxy/files/4567863/repro.zip)
2. Open the HTTP flow's detail view (enter tab tab) 
3. Return to the flow list (q)
4. Select the TCP flow (down, enter)

#### System Information
Mitmproxy: 6.0.0.dev (+40, commit 3d46e98)
Python:    3.8.0
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.27

**Comment by sarthak212** [comment]
When we visit a request and press `tab` to alter view I think a tab counter increases with each tab but it didn't get decrease to the first view as we press `q` because when you view another request the respective view according to preview request is open by default on that request
Steps to produce this
1. Visit first HTTP request
2. press tab (view change to the response)
3. press q
4. Visit the second request

Its default view is the response not request. In this case first request has three views so as you press tab two times it's counter increase but when you view the second request it has only two views so the counter doesn't find view according to tab index.
For solution, I think we have to decrease the counter when we return to flow list with pressing `q`
Correct me if I am wrong @mhils

**Comment by mhils** [comment]
> For solution, I think we have to decrease the counter when we return to flow list with pressing q

It's a bit more subtle than that: It's useful to keep the tab index around if we transition from an HTTP to an HTTP flow (e.g. I want to compare responses), but we need to not fail when we change to TCP flows.

**Comment by sarthak212** [comment]
What about if tab offset is greater than tabs length then it fallback to zero index.

**Comment by Prinzhorn** [comment]
I think the PR wasn't properly linked and this has been resolved for a while
