### ISSUE TITLE
Piping mitmdump output to another program and quitting the latter early results in BrokenPipeErrors

### ISSUE THREAD

**Issue by JustAnotherArchivist** [mitmproxy/mitmproxy#3988]
#### Problem Description
Piping mitmdump output to another program and exiting that latter program before it has read all of mitmdump's output produces a *lot* of `BrokenPipeError: [Errno 32] Broken pipe` errors.

#### Steps to reproduce the behavior:
1. Capture a non-trivial amount of traffic: `mitmdump -w outfile`; the nature of the traffic (HTTP/HTTPS/WebSocket) does not seem to matter. The outfile has to be large enough for the next command to produce enough output that the pipe buffer gets backlogged.
2. Print the contents of the dump file and pipe it to something like `less`: `mitmdump -nr outfile | less`
3. Quit `less` with the `q` key.
4. mitmdump produces a traceback similar to the following for every record in the outfile that has not been consumed by `less` prior to quitting:

```
Addon error: Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/mitmproxy/addons/termlog.py", line 31, in log
    click.secho(
  File ".../lib/python3.8/site-packages/click/termui.py", line 548, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File ".../lib/python3.8/site-packages/click/utils.py", line 273, in echo
    file.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

```
Addon error: Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/mitmproxy/addons/dumper.py", line 263, in websocket_message
    self.echo(f.message_info(message))
  File ".../lib/python3.8/site-packages/mitmproxy/addons/dumper.py", line 70, in echo
    click.secho(text, file=self.outfp, **style)
  File ".../lib/python3.8/site-packages/click/termui.py", line 548, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File ".../lib/python3.8/site-packages/click/utils.py", line 273, in echo
    file.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

#### Attempted workarounds and possible solution
The obvious workaround is to first make the second program consume everything and only then quit. For example, with `less`, pressing `G` to scroll to the bottom of the output before quitting. However, since `less` keeps everything in memory, this may not be feasible for large dump files.

Killing metadump with `^C` after quitting `less` does not seem to help.

For this particular use case of displaying file information, the ideal solution would be to simply exit on a `BrokenPipeError`. This would also mean that the rest of the dump file would not be processed, needlessly wasting CPU time. But the general case is probably rather to disable all further output to stdout but keep processing (e.g. if a dump file is being filtered into another file).

#### System Information
```
$ mitmproxy --version
Mitmproxy: 5.1.1 (+2, commit a8ca63f)
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.6.0-1-amd64-x86_64-with-glibc2.29
```

This is a current Debian sid system. The `(+2, commit a8ca63f)` info on the mitmproxy version is a bug (#3987) and can be disregarded; this is a clean 5.1.1 installation.

**Comment by mhils** [comment]
Do we have any examples of where pipes break and exiting is not the desired behavior?

**Comment by JustAnotherArchivist** [comment]
* The main one that I briefly hinted at above: `mitmdump -nr infile -w outfile filter | less` should presumably continue filtering from infile into outfile when less exits. Basically any operation involving `-w`.
* I'm not sure what the expected behaviour is when supplying a script with `-s`.
* Replay?

**Comment by mhils** [comment]
Well I'd argue that these examples are a bit contrived. Why do you need/want `| less` for that invocation? We can't fix all use cases, I think it's more useful if we just exit on a broken pipe. We can maybe shoot an error to stderr, but I feel we don't even have to do that. grep etc. don't have that either.

**Comment by JustAnotherArchivist** [comment]
I agree: they might not be terribly realistic. But generally, I pipe to `less` if I know a command produces a lot of output and don't want that in my scrollback or if I want to search through the output interactively, and I could see that happening with such mitmdump commands.

True, `grep`, `head`, et al. don't produce a warning, but they don't have any options with side effects – the stdout output is their only product, so silently ignoring that error is a safe thing to do once stdout is a broken pipe. And in the case of mitmproxy commands without side effects, such as `mitmdump -nr infile | less`, that would also be true. But I'd argue that commands with side effects, such as ones involving `-w`, need to be handled a bit more carefully. I think a warning on stderr in the `-w` case would be a good idea, but I'm not so sure about other options.

**Comment by JustAnotherArchivist** [comment]
@myfingerhurt I'm not sure about the other things you mentioned, but about this:

>  `mitmweb mitmweb -s mitm_anatomy.py 2>&1 > /tmp/mitm.log` did save both stderr and stdout to `mitm.log` but only flushed to the file after terminated. I needed the real-time log for tail -F to work with another program.

You may want to try setting the `PYTHONUNBUFFERED` environment variable to a non-empty value.
