### ISSUE TITLE
Use xss_scanner.py crashed

### ISSUE THREAD

**Issue by caimaoy** [mitmproxy/mitmproxy#4017]
#### Problem Description
Use xss_scanner.py crashed

#### Steps to reproduce the behavior:
1.  Use the file `xss_scanner.py` in example-comple
2. Command `mitmproxy -s xss_scanner.py`
3. Use the proxy and open some websites
4. crashed!
```shell
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
mitmproxy has crashed!
Traceback (most recent call last):
  File "/Users/yuechen/.pyenv/versions/3.7.3/envs/mitm-3.7.3/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Users/yuechen/.pyenv/versions/3.7.3/envs/mitm-3.7.3/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
TypeError: 'NoneType' object is not callable

Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```
#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.0.1
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-18.7.0-x86_64-i386-64bit

**Comment by mhils** [comment]
refs #4031
