### ISSUE TITLE
AttributeError: type object 'SettingsFrame' has no attribute 'ENABLE_CONNECT_PROTOCOL

### ISSUE THREAD

**Issue by Apuyuseng** [mitmproxy/mitmproxy#4018]
#### Problem Description
```shell
$ mitmweb 
Traceback (most recent call last):
  File "/home/apu/.local/bin/mitmweb", line 5, in <module>
    from mitmproxy.tools.main import mitmweb
  File "/home/apu/.local/lib/python3.7/site-packages/mitmproxy/tools/main.py", line 22, in <module>
    from ._main import *  # noqa
  File "/home/apu/.local/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 17, in <module>
    from mitmproxy import proxy
  File "/home/apu/.local/lib/python3.7/site-packages/mitmproxy/proxy/__init__.py", line 2, in <module>
    from .root_context import RootContext
  File "/home/apu/.local/lib/python3.7/site-packages/mitmproxy/proxy/root_context.py", line 4, in <module>
    from mitmproxy.proxy import protocol
  File "/home/apu/.local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/__init__.py", line 36, in <module>
    from .http2 import Http2Layer
  File "/home/apu/.local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http2.py", line 7, in <module>
    from h2 import connection
  File "/home/apu/.local/lib/python3.7/site-packages/h2/connection.py", line 23, in <module>
    from .events import (
  File "/home/apu/.local/lib/python3.7/site-packages/h2/events.py", line 14, in <module>
    from .settings import ChangedSetting, _setting_code_from_int
  File "/home/apu/.local/lib/python3.7/site-packages/h2/settings.py", line 25, in <module>
    class SettingCodes(enum.IntEnum):
  File "/home/apu/.local/lib/python3.7/site-packages/h2/settings.py", line 60, in SettingCodes
    ENABLE_CONNECT_PROTOCOL = SettingsFrame.ENABLE_CONNECT_PROTOCOL
AttributeError: type object 'SettingsFrame' has no attribute 'ENABLE_CONNECT_PROTOCOL'
```

#### Steps to reproduce the behavior:
1. `pip3 install mitmproxy` 
2. `cmd run mitmweb`

#### System Information
```shell
$ pip3 list | grep mitmproxy
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
mitmproxy                5.1.1

```

**Comment by Apuyuseng** [comment]
need upgrade h2
```
pip3 install --upgrade h2
```

**Comment by MetalPort** [comment]
(Apuyuseng) Son of a gun! It worked!!!

**Comment by das-shurveer-madan** [comment]
![scrappy error image code](https://user-images.githubusercontent.com/96683543/147406291-0802e003-8844-4f3c-9120-7d3dd330cd07.png)

**Comment by das-shurveer-madan** [comment]
i am facing the sam eissue i guess please help me out

**Comment by 787264137** [comment]
awesome solution，could not believe it..........
