### ISSUE TITLE
mitmproxy  dictionary changed size during iteration

### ISSUE THREAD

**Issue by CGpythoner** [mitmproxy/mitmproxy#4057]
#### Problem Description
在使用mitmproxy作为二级代理时，出现了错误。
 flow.live.change_upstream_proxy_server((proxy, 8080))
#### Steps to reproduce the behavior:
1. mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 262, in _process_flow
    return self.handle_upstream_connect(f)
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 236, in handle_upstream_connect
    return layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 87, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 279, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 365, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 369, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 501, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/lib/python3.6/site-packages/mitmproxy/certs.py", line 326, in get_cert
    self.expire(entry)
  File "/usr/lib/python3.6/site-packages/mitmproxy/certs.py", line 156, in expire
    for k, v in list(self.certs.items()):
RuntimeError: dictionary changed size during iteration

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 4.0.4
Python: 3.6.3
OpenSSL: OpenSSL 1.0.2o 27 Mar 2018
Platform: Linux-3.10.0-1062.el7.x86_64-with

**Comment by mhils** [comment]
Hi, how can reproduce this?
