### ISSUE TITLE
Mitmweb fails with addons/options-configure.py example.

### ISSUE THREAD

**Issue by jekoie** [mitmproxy/mitmproxy#4059]
I am new to learn it, but i follow official [demo][1], it can't working?
```python
Proxy server listening at http://*:8888
ERROR:tornado.application:Uncaught exception GET /options.json (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/options.json', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "c:\users\jekoie\appdata\local\programs\python\python37-32\lib\site-packages\tornado\web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\users\jekoie\appdata\local\programs\python\python37-32\lib\site-packages\mitmproxy\tools\web\app.py", line 453, in get
    self.write(optmanager.dump_dicts(self.master.options))
  File "c:\users\jekoie\appdata\local\programs\python\python37-32\lib\site-packages\mitmproxy\optmanager.py", line 469, in dump_dicts
    t = typecheck.typespec_to_str(o.typespec)
  File "c:\users\jekoie\appdata\local\programs\python\python37-32\lib\site-packages\mitmproxy\utils\typecheck.py", line 85, in typespec_to_str
    raise NotImplementedError
NotImplementedError
ERROR:tornado.access:500 GET /options.json (127.0.0.1) 3.91ms
````

[1]: https://docs.mitmproxy.org/stable/addons-options/#handling-configuration-updates

**Comment by mhils** [comment]
Thanks for reporting this. It's is a bug in mitmweb only, mitmproxy and mitmdump are unaffected.

Repro:
```
mitmweb -s examples/addons/options-configure.py
```
