### ISSUE TITLE
dumper.py POST request with non utf8 encoding crashes mitmproxy

### ISSUE THREAD

**Issue by guysoft** [mitmproxy/mitmproxy#4070]
#### Problem Description
I have a client that uses cp1255 encoding. When it poses to download I get:

```python
Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/addons/dumper.py", line 246, in response                                                
    self.echo_flow(f)                                                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/addons/dumper.py", line 218, in echo_flow                                               
    self._echo_request_line(f)                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/addons/dumper.py", line 166, in _echo_request_line                                      
    self.echo(line)                                                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/addons/dumper.py", line 70, in echo                                                     
    click.secho(text, file=self.outfp, **style)                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/click/termui.py", line 548, in secho                                                              
    return echo(message, file=file, nl=nl, err=err, color=color)                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/click/utils.py", line 272, in echo                                                                
    file.write(message)                                                                                                                          
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 138-143: surrogates not allowed  
```

#### Steps to reproduce the behavior:
1. I am not sure, but I think posting non-unicode chars from the client seems to be breaking it, Is there a way I can capture from the dumper what its trying to do?

#### System Information
```
Mitmproxy: 5.1.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.14.171-136.231.amzn2.x86_64-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
Yeah, this definitely looks like a bug. Thanks!

**Comment by dlbas** [comment]
@mhils, I also wish to take a look at this one, if you don't mind 🙃

**Comment by mhils** [comment]
I think this is fixed. If anyone can still trigger this, please comment here with steps how to reproduce. :)

**Comment by guysoft** [comment]
Don't think I have how to test it here.
