### ISSUE TITLE
Crash Mitmproxy when turn on mode transparent

### ISSUE THREAD

**Issue by danghuong18** [mitmproxy/mitmproxy#4076]
#### Problem Description
I was learning about mitmproxy and trying to run it, I realized that when I ran the following command (admin rights):

> mitmdump --mode transparent --ssl-insecure

it would cause mitmproxy crash:

```
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.1.223:51720: clientdisconnect
192.168.1.223:51722: clientconnect
192.168.1.223:51722: GET https://140.82.113.26/_sockets/u/53718521/ws?session=eyJ2IjoiVjMiLCJ1Ijo1MzcxODUyMSwicyI6NTUzMzc5MDA2LCJjIjoxOTU3MjMyNzE1LCJ0IjoxNTkzNzU3MDg3fQ%3D%3D--4fceba1ee908439bbfbb6dd7ff882aa7f445a82584e481ea2c0a372f3b277360&shared=true
                  << 101 Switching Protocols 0b
192.168.1.223:51722: Traceback (most recent call last):
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\modes\transparent_proxy.py", line 19, in __call__
    layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 285, in __call__
    layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 83, in __call__
    layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 190, in __call__
    if not self._process_flow(flow):
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 449, in _process_flow
    layer = WebSocketLayer(self, f)
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\websocket.py", line 71, in __init__
    data = self.connections[self.server_conn].send(request)
  File "c:\python\python38-32\lib\site-packages\wsproto\connection.py", line 109, in send
    raise LocalProtocolError("Event {} cannot be sent.".format(event))
wsproto.utilities.LocalProtocolError: Event Request(host='140.82.113.26', target='/_sockets/u/53718521/ws?session=eyJ2IjoiVjMiLCJ1Ijo1MzcxODUyMSwicyI6NTUzMzc5MDA2LCJjIjoxOTU3MjMyNzE1LCJ0IjoxNTkzNzU3MDg3fQ%3D%3D--4fceba1ee908439bbfbb6dd7ff882aa7f445a82584e481ea2c0a372f3b277360&shared=true', extensions=[<PerMessageDeflate client_max_window_bits=15; client_no_context_takeover; server_max_window_bits=15; server_no_context_takeover>], extra_headers=[], subprotocols=[]) cannot be sent.
Traceback (most recent call last):
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\modes\transparent_proxy.py", line 19, in __call__
    layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 285, in __call__
    layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 83, in __call__
    layer()
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 190, in __call__
    if not self._process_flow(flow):
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 449, in _process_flow
    layer = WebSocketLayer(self, f)
  File "c:\python\python38-32\lib\site-packages\mitmproxy\proxy\protocol\websocket.py", line 71, in __init__
    data = self.connections[self.server_conn].send(request)
  File "c:\python\python38-32\lib\site-packages\wsproto\connection.py", line 109, in send
    raise LocalProtocolError("Event {} cannot be sent.".format(event))
wsproto.utilities.LocalProtocolError: Event Request(host='140.82.113.26', target='/_sockets/u/53718521/ws?session=eyJ2IjoiVjMiLCJ1Ijo1MzcxODUyMSwicyI6NTUzMzc5MDA2LCJjIjoxOTU3MjMyNzE1LCJ0IjoxNTkzNzU3MDg3fQ%3D%3D--4fceba1ee908439bbfbb6dd7ff882aa7f445a82584e481ea2c0a372f3b277360&shared=true', extensions=[<PerMessageDeflate client_max_window_bits=15; client_no_context_takeover; server_max_window_bits=15; server_no_context_takeover>], extra_headers=[], subprotocols=[]) cannot be sent.


mitmproxy has crashed!
```

Can someone help me with this problem? Thanks!

#### System Information
The version information I'm using is as follows:

> Mitmproxy: 5.1.1
> Python:    3.8.2
> OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
> Platform:  Windows-10-10.0.18362-SP0

**Comment by mhils** [comment]
see #4082
