### ISSUE TITLE
Exception in thread TCPConnectionHandler

### ISSUE THREAD

**Issue by mazhechao** [mitmproxy/mitmproxy#4103]
#### Problem Description
lot of exceptions when running mitmproxy
```
Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/python36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python36/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 602, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/local/python36/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 66, in handle_client_connection
    self.channel
  File "/usr/local/python36/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 78, in __init__
    None)
  File "/usr/local/python36/lib/python3.6/site-packages/mitmproxy/connections.py", line 38, in __init__
    super().__init__(client_connection, address, server)
  File "/usr/local/python36/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 489, in __init__
    super().__init__(connection)
  File "/usr/local/python36/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 297, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected
```

#### System Information
```
Mitmproxy: 5.2 binary
Python:    3.7.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.9.0-0.bpo.6-amd64-x86_64-with-debian-8.11
```

**Comment by mhils** [comment]
Thanks, how can we reproduce this issue?

**Comment by mazhechao** [comment]
I am not very sure. May be raw tcp connection, one SYN packet and one RST+ACK packet follows.
Our mitmproxy is behind a load balance server, which will send tcp packets to check if real ip and port are alive continuously.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
