### ISSUE TITLE
TcpDisconnect right after OpenSSL.SSL.SysCallError

### ISSUE THREAD

**Issue by heavyimage** [mitmproxy/mitmproxy#4105]
#### Problem Description

I'm getting an exception which urges me to log it on github, so I am.

```
Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/net/tcp.py", line 95, in write
    return self.o.sendall(v)
  File "/root/mitmproxy/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1789, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/root/mitmproxy/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/root/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/root/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/root/mitmproxy/mitmproxy/proxy/protocol/http2.py", line 348, in __call__
    self._complete_handshake()
  File "/root/mitmproxy/mitmproxy/proxy/protocol/http2.py", line 134, in _complete_handshake
    self.client_conn.send(self.connections[self.client_conn].data_to_send())
  File "/root/mitmproxy/mitmproxy/connections.py", line 108, in send
    self.wfile.write(message)
  File "/root/mitmproxy/mitmproxy/net/tcp.py", line 101, in write
    raise exceptions.TcpDisconnect(str(e))
mitmproxy.exceptions.TcpDisconnect: (104, 'ECONNRESET')

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

#### Steps to reproduce the behavior:
1. I'm using transparent mode to mitm the traffic between an android app and the web; It'd be a bit hard to list reproduction steps, I fear...
2. Is there any generic explanation for what sort of traffic might be causing this exception?  Maybe something out of specification? 

#### System Information
```
Mitmproxy: 6.0.0.dev (+4, commit 46fbba6)
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.7.0-1-amd64-x86_64-with-debian-10.4
```

Thanks for any help you can provide!

**Comment by mhils** [comment]
That looks like an OpenSSL error we don't catch properly - if this only happens for some traffic, this could be an indicator for certificate pinning. 

(this should ultimately be fixed with #1775, but that will take some time)

**Comment by heavyimage** [comment]
Him, okay, thanks.  

I'm trying to work around some complex pinning so maybe I haven't caught all of it just quite yet.  Thanks!

**Comment by heavyimage** [comment]
So I'm poking at this more because this seems to be causing a lot of problems.  I modified the code to print the string that was causing the write to fail:

```
diff --git a/mitmproxy/net/tcp.py b/mitmproxy/net/tcp.py
index b76a48bf..1e51479b 100644
--- a/mitmproxy/net/tcp.py
+++ b/mitmproxy/net/tcp.py
@@ -98,7 +98,7 @@ class Writer(_FileLike):
                     self.add_log(v[:r])
                     return r
             except (SSL.Error, socket.error) as e:
-                raise exceptions.TcpDisconnect(str(e))
+                raise exceptions.TcpDisconnect("%s\nwritestring: %s" % (str(e), v))


 class Reader(_FileLike):
```

And the error now looks like this:
```
10.0.0.55:38431: Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/net/tcp.py", line 95, in write
    return self.o.sendall(v)
  File "/root/mitmproxy/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1789, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/root/mitmproxy/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/root/mitmproxy/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/root/mitmproxy/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/root/mitmproxy/mitmproxy/proxy/protocol/http2.py", line 348, in __call__
    self._complete_handshake()
  File "/root/mitmproxy/mitmproxy/proxy/protocol/http2.py", line 134, in _complete_handshake
    self.client_conn.send(self.connections[self.client_conn].data_to_send())
  File "/root/mitmproxy/mitmproxy/connections.py", line 108, in send
    self.wfile.write(message)
  File "/root/mitmproxy/mitmproxy/net/tcp.py", line 102, in write
    raise exceptions.TcpDisconnect("%s\nwritestring: %s" % (str(e), v))
mitmproxy.exceptions.TcpDisconnect: (104, 'ECONNRESET')
writestring: b'\x00\x00*\x04\x00\x00\x00\x00\x00\x00\x01\x00\x00\x10\x00\x00\x02\x00\x00\x00\x00\x00\x04\x00\x00\xff\xff\x00\x05\x00\x00@\x00\x00\x08\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x06\x00\x01\x00\x00'
```

Do those bytes mean anything to you or do you have any idea what this might be / mean?

Thanks for any help you can offer.

**Comment by mhils** [comment]
mitmproxy wants to send data, but the peer has reset the connection.
Doesn't matter too much what we wanted to send in this case, it's already
too late 😛

Again - I haven't looked closer because on mobile - likely certificate
pinning.

**Comment by heavyimage** [comment]
Thanks @mhils -- I really really appreciate the reply!!  I'll keep digging.
