### ISSUE TITLE
Crashes when trying to read from STDIN

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4113]
#### Problem Description
Always crashes when trying to read from STDIN.

#### Steps to reproduce the behavior:
1. Create an empty file `empty`, i.e. `touch empty`.
2. ` tail -f ./empty | mitmproxy --rfile - -n` 

**What happens:**
```
$ tail -f ./empty | mitmproxy --rfile - -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 55, in reraise
    value = tp()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

$ tail -f ./empty | mitmproxy --rfile empty -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 436, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 510, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 644, in _getch_nodelay
    return self._getch(0)
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 554, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

```

**Important:** If you load the file directly, it _always_ works!

Also, with a real-life file, the errors vary. It always takes a long time showing nothing and then crashes:
```
$ tail -f ./mitmproxy-flow.cap | mitmproxy --rfile - -n

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 55, in reraise
    value = tp()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
sys:1: RuntimeWarning: coroutine 'Master._shutdown' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

$ tail -f ./mitmproxy-flow.cap | mitmproxy --rfile - -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 55, in reraise
    value = tp()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
sys:1: RuntimeWarning: coroutine 'Master._shutdown' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

I've also tried to not write into the file simoultaneously, and avoid using the `-f` command with tail. Nothing prevents the crashes.
```
$ tail ./empty | mitmproxy --rfile - -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 436, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 510, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 644, in _getch_nodelay
    return self._getch(0)
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 554, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

**Important:** When loading the file directly (not from STDIN), it works without any problem, even for an empty file!

Previous crashes/information: https://github.com/mitmproxy/mitmproxy/issues/1002#issuecomment-665169972

#### System Information
```
$ mitmproxy --version
Mitmproxy: 5.2
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.4.51-v7l+-armv7l-with-debian-10.4
```

**Comment by mhils** [comment]
I assume you only get this traceback when using mitmproxy, not mitmdump? If some, please verify if it still happens with the latest urwid version and file a report upstream.

**Comment by rugk** [comment]
Whatever it does, it also seems to write strange files into the PWD:
```
$ ls -la M*
-rw-r--r-- 1 pi pi 0 Jul 29 14:18 MuZ3N0YXRpYy5jb22CHWNvbm5lY3Rpdml0eWNoZWNrLmdzdGF0aWMuY29tMB0G
-rw-r--r-- 1 pi pi 0 Jul 29 14:18 MuZ3N0YXRpYy5jb22CHWNvbm5lY3Rpdml0eWNoZWNrLmdzdGF0aWMuY29tMB0GMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEA
```

`mitmdump` does not seem to crash, at least, if doing `tail -f ./empty | mitmdump --rfile - -n` for a test…

> If some, please verify if it still happens with the latest urwid version and file a report upstream.

I have no idea how to do that and what urwid even is. Seems to be some Python package, I've installed `mitmproxy` with `pip`…

**Comment by mhils** [comment]
It's the console ui library we depend on. The traceback indicates that the error is triggered there. It's nothing we can fix in mitmproxy.

**Comment by rugk** [comment]
```
$ pip3 list| grep urwid
urwid              2.0.1
$ pip3 show urwid
Name: urwid
Version: 2.0.1
Summary: A full-featured console (xterm et al.) user interface library
Home-page: http://urwid.org/
Author: Ian Ward
Author-email: ian@excess.org
License: LGPL
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: 
```

---

I've reinstalled mitmproxy via `pipx` now (assuming this uses a more recent version of urwid), but the issue still happens:
```
$ tail ./empty | mitmproxy --rfile - -n
Traceback (most recent call last):
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 436, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 510, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 644, in _getch_nodelay
    return self._getch(0)
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 554, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

I have no idea to find the version of urwid. (ref https://github.com/pipxproject/pipx/issues/457)
Even doing `pipx inject mitmproxy urwid` did not help:
```
$ tail ./empty | mitmproxy --rfile - -n
Traceback (most recent call last):
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 436, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 510, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 644, in _getch_nodelay
    return self._getch(0)
  File "/home/pi/.local/pipx/venvs/mitmproxy/lib/python3.7/site-packages/urwid/raw_display.py", line 554, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

**Comment by mhils** [comment]
`pip install --upgrade urwid` should upgrade your urwid installation. We currently pin to 2.0.1 because urwid 2.1.0 had some major bugs, but they've just relased 2.1.1 a few days ago.

**Comment by rugk** [comment]
Yeah, seems it always uses your pin…


```
$ sudo pip3 install mitmproxy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mitmproxy
  Using cached https://files.pythonhosted.org/packages/2a/3c/c46bf732fecec25c502f46b016d9aa49757095e04f91f3b5ca9d71d80ccc/mitmproxy-5.2-py3-none-any.whl
Requirement already satisfied: certifi>=2019.9.11 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2020.6.20)
Requirement already satisfied: pyOpenSSL<19.2,>=19.1.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (19.1.0)
Requirement already satisfied: wsproto<0.16,>=0.14 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (0.15.0)
Requirement already satisfied: publicsuffix2<3,>=2.20190812 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2.20191221)
Requirement already satisfied: passlib<1.8,>=1.6.5 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (1.7.2)
Requirement already satisfied: cryptography<3.0,>=2.9 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2.9.2)
Requirement already satisfied: protobuf<3.12,>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (3.11.3)
Requirement already satisfied: hyperframe<6,>=5.1.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (5.2.0)
Requirement already satisfied: click<8,>=7.0 in /usr/lib/python3/dist-packages (from mitmproxy) (7.0)
Requirement already satisfied: Brotli<1.1,>=1.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (1.0.7)
Requirement already satisfied: flask<1.2,>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (1.1.2)
Requirement already satisfied: h2<4,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (3.2.0)
Requirement already satisfied: blinker<1.5,>=1.4 in /usr/lib/python3/dist-packages (from mitmproxy) (1.4)
Requirement already satisfied: pyasn1<0.5,>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (0.4.8)
Requirement already satisfied: urwid!=2.1.0,==2.0.1 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2.0.1)
Requirement already satisfied: tornado<7,>=4.3 in /usr/lib/python3/dist-packages (from mitmproxy) (5.1.1)
Requirement already satisfied: pyparsing<2.5,>=2.4.2 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2.4.7)
Requirement already satisfied: ruamel.yaml<0.17,>=0.16 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (0.16.10)
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (0.8)
Requirement already satisfied: ldap3<2.8,>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2.7)
Requirement already satisfied: sortedcontainers<2.2,>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (2.1.0)
Requirement already satisfied: pyperclip<1.9,>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (1.8.0)
Requirement already satisfied: zstandard<0.14,>=0.11 in /usr/local/lib/python3.7/dist-packages (from mitmproxy) (0.13.0)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from pyOpenSSL<19.2,>=19.1.0->mitmproxy) (1.12.0)
Requirement already satisfied: h11>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from wsproto<0.16,>=0.14->mitmproxy) (0.9.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.7/dist-packages (from cryptography<3.0,>=2.9->mitmproxy) (1.14.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf<3.12,>=3.6.0->mitmproxy) (40.8.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from flask<1.2,>=1.1.1->mitmproxy) (2.11.2)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.7/dist-packages (from flask<1.2,>=1.1.1->mitmproxy) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/lib/python3/dist-packages (from flask<1.2,>=1.1.1->mitmproxy) (0.24)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.7/dist-packages (from h2<4,>=3.2.0->mitmproxy) (3.0.0)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /usr/local/lib/python3.7/dist-packages (from ruamel.yaml<0.17,>=0.16->mitmproxy) (0.2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography<3.0,>=2.9->mitmproxy) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->flask<1.2,>=1.1.1->mitmproxy) (1.1.0)
Installing collected packages: mitmproxy
Successfully installed mitmproxy-5.2
$ pip3 install --upgrade urwid
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Collecting urwid
  Downloading https://www.piwheels.org/simple/urwid/urwid-2.1.1-cp37-cp37m-linux_armv7l.whl (258kB)
    100% |████████████████████████████████| 266kB 1.2MB/s 
mitmproxy 5.2 has requirement urwid!=2.1.0,==2.0.1, but you'll have urwid 2.1.1 which is incompatible.
Installing collected packages: urwid
Successfully installed urwid-2.1.1

```

Also, why now `pip` again, if I use `pipx` as your guide recommends – as far as I see, I could not notice any advantage of `pipx`.

**Comment by rugk** [comment]
Still does not work though:
```
$ pip3 list|grep urwid
urwid              2.1.1
$ tail ./empty | mitmproxy --rfile - -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/raw_display.py", line 417, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/raw_display.py", line 449, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/raw_display.py", line 523, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/raw_display.py", line 661, in _getch_nodelay
    return self._getch(0)
  File "/home/pi/.local/lib/python3.7/site-packages/urwid/raw_display.py", line 571, in _getch
    return ord(os.read(fd, 1))
TypeError: ord() expected a character, but string of length 0 found

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

```

**Comment by mhils** [comment]
pipx works just as well, it's just a more user-friendly wrapper around virtualenvs. Please feel free to report this upstream, urwid shouldn't crash if you provide a file as stdin. That being said, you don't want to pipe into `mitmproxy`, that doesn't work well because you need stdin for keyboard input.

As a general comment, you have posted a serious double-digit number of comments over the last two days on our issue tracker. We appreciate feedback, but can't cope with that. Please tune down your volume considerably and try to be more helpful than demanding. Thanks.

**Comment by rugk** [comment]
Done: https://github.com/urwid/urwid/issues/423
