### ISSUE TITLE
Does not interpret key presses and mouse correctly

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4114]
#### Problem Description
I know `mitmproxy` worked once with mouse and key (when I've tried it locally).

#### Steps to reproduce the behavior:
0. SSH into a remote device. (client: zsh/GNOME Terminal; remote: bash)
1. Start `mitmproxy` like this: `mitmproxy --rfile ./mitmproxy-flow.cap -n`
2. Press arrow keys or anything else.

I get a screen like this and nothing happens:
![grafik](https://user-images.githubusercontent.com/11966684/88800784-fbf3ef00-d1a8-11ea-807d-96f2963f56b7.png)

I I then Ctrl+C to exit, it ends with a crash:
```
$ mitmproxy --rfile ./mitmproxy-flow.cap -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 436, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 510, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 644, in _getch_nodelay
    return self._getch(0)
  File "/usr/local/lib/python3.7/dist-packages/urwid/raw_display.py", line 554, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
````

**Note:** htop e.g. works with mouse and keyboard input, so my setup is not wrong here.

#### System Information

Mitmproxy: 5.2
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.4.51-v7l+-armv7l-with-debian-10.4itmproxy --version" here.

**Comment by mhils** [comment]
I tried to reproduce this using the steps you provided. Works just fine for me.

**Comment by Kriechi** [comment]
@rugk your instruction steps seem to be missing the "tail -f ./empty" pipe - or where does it come from in the trace you provided? What are you trying to achieve with this?

**Comment by rugk** [comment]
Ahh, ignore that. I was just lazy to not remove that (**edit:** done now). Mitmproxy ignores that…

Ahhh, after upgrading to [urwid v2.1.1](https://github.com/mitmproxy/mitmproxy/issues/4113#issuecomment-665658799) _this_ now wporks…
