### ISSUE TITLE
Flaky cross-polluting test

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4136]
From https://github.com/mitmproxy/mitmproxy/runs/957862340:
```python
=================================== FAILURES ===================================
__________ TestTermLog.test_output[None-expected_out0-expected_err0] ___________

self = <test.mitmproxy.addons.test_termlog.TestTermLog object at 0x7fc2cb7bd100>
outfile = None, expected_out = ['one', 'three'], expected_err = ['four']
capfd = <_pytest.capture.CaptureFixture object at 0x7fc2d9e7f9d0>

    @pytest.mark.usefixtures('capfd')
    @pytest.mark.parametrize('outfile, expected_out, expected_err', [
        (None, ['one', 'three'], ['four']),
        (sys.stdout, ['one', 'three', 'four'], []),
        (sys.stderr, [], ['one', 'three', 'four']),
    ])
    def test_output(self, outfile, expected_out, expected_err, capfd):
        t = termlog.TermLog(outfile=outfile)
        with taddons.context(t) as tctx:
            tctx.options.termlog_verbosity = "info"
            tctx.configure(t)
            t.log(log.LogEntry("one", "info"))
            t.log(log.LogEntry("two", "debug"))
            t.log(log.LogEntry("three", "warn"))
            t.log(log.LogEntry("four", "error"))
        out, err = capfd.readouterr()
        assert out.strip().splitlines() == expected_out
>       assert err.strip().splitlines() == expected_err
E       assert ['Traceback (most recent call last):',\n '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/server.py", '\n 'line 121, in handle',\n '    root_layer()',\n '  File '\n '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/modes/http_proxy.py", '\n 'line 9, in __call__',\n '    layer()',\n '  File '\n '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/tls.py", '\n 'line 285, in __call__',\n '    layer()',\n '  File '\n '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http1.py", '\n 'line 103, in __call__',\n '    layer()',\n '  File '\n '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http.py", '\n 'line 203, in __call__',\n '    if not self._process_flow(flow):',\n '  File '\n '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http.py", '\n 'line 451, in _process_flow',\n '    if self.check_close_connection(f):',\n '  File '\n '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http1.py", '\n 'line 88, in check_close_connection',\n '    flow.response.http_version,',\n "AttributeError: 'NoneType' object has no attribute 'http_version'",\n '',\n 'mitmproxy has crashed!',\n 'Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy',\n 'four'] == ['four']
E         At index 0 diff: 'Traceback (most recent call last):' != 'four'
E         Left contains 19 more items, first extra item: '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/server.py", line 121, in handle'
E         Full diff:
E           [
E         +  'Traceback (most recent call last):',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/server.py", '
E         +  'line 121, in handle',
E         +  '    root_layer()',
E         +  '  File '
E         +  '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/modes/http_proxy.py", '
E         +  'line 9, in __call__',
E         +  '    layer()',
E         +  '  File '
E         +  '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/tls.py", '
E         +  'line 285, in __call__',
E         +  '    layer()',
E         +  '  File '
E         +  '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http1.py", '
E         +  'line 103, in __call__',
E         +  '    layer()',
E         +  '  File '
E         +  '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http.py", '
E         +  'line 203, in __call__',
E         +  '    if not self._process_flow(flow):',
E         +  '  File '
E         +  '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http.py", '
E         +  'line 451, in _process_flow',
E         +  '    if self.check_close_connection(f):',
E         +  '  File '
E         +  '"/home/runner/work/mitmproxy/mitmproxy/mitmproxy/proxy/protocol/http1.py", '
E         +  'line 88, in check_close_connection',
E         +  '    flow.response.http_version,',
E         +  "AttributeError: 'NoneType' object has no attribute 'http_version'",
E         +  '',
E         +  'mitmproxy has crashed!',
E         +  'Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy',
E            'four',
E           ]

test/mitmproxy/addons/test_termlog.py:27: AssertionError
``` 

This one is really ugly:

 - It's not caused by the TermLog test
 - I'm unable to repro it locally
 - The stacktrace doesn't make much sense. Some concurrent code unsetting `flow.response`?

🤷

**Comment by mhils** [comment]
This one could be more helpful: 
```python
__________ TestTermLog.test_output[None-expected_out0-expected_err0] ___________

self = <test.mitmproxy.addons.test_termlog.TestTermLog object at 0x7fb5f7e93588>
outfile = None, expected_out = ['one', 'three'], expected_err = ['four']
capfd = <_pytest.capture.CaptureFixture object at 0x7fb5f7e93390>

    @pytest.mark.usefixtures('capfd')
    @pytest.mark.parametrize('outfile, expected_out, expected_err', [
        (None, ['one', 'three'], ['four']),
        (sys.stdout, ['one', 'three', 'four'], []),
        (sys.stderr, [], ['one', 'three', 'four']),
    ])
    def test_output(self, outfile, expected_out, expected_err, capfd):
        t = termlog.TermLog(outfile=outfile)
        with taddons.context(t) as tctx:
            tctx.options.termlog_verbosity = "info"
            tctx.configure(t)
            t.log(log.LogEntry("one", "info"))
            t.log(log.LogEntry("two", "debug"))
            t.log(log.LogEntry("three", "warn"))
            t.log(log.LogEntry("four", "error"))
        out, err = capfd.readouterr()
        assert out.strip().splitlines() == expected_out
>       assert err.strip().splitlines() == expected_err
E       assert ['Exception in thread ProxyThread (*:40649):',\n 'Traceback (most recent call last):',\n '  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/threading.py", '\n 'line 916, in _bootstrap_inner',\n '    self.run()',\n '  File "/home/runner/work/mitmproxy/mitmproxy/test/mitmproxy/tservers.py", '\n 'line 116, in run',\n '    self.tmaster.run()',\n '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line '\n '108, in run',\n '    self.run_loop(loop.run_forever)',\n '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line 92, '\n 'in run_loop',\n '    loop = asyncio.get_event_loop()',\n '  File '\n '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '\n 'line 694, in get_event_loop',\n '    return get_event_loop_policy().get_event_loop()',\n '  File '\n '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '\n 'line 602, in get_event_loop',\n '    % threading.current_thread().name)',\n "RuntimeError: There is no current event loop in thread 'ProxyThread "\n "(*:40649)'.",\n '',\n 'Exception in thread ProxyThread (*:38931):',\n 'Traceback (most recent call last):',\n '  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/threading.py", '\n 'line 916, in _bootstrap_inner',\n '    self.run()',\n '  File "/home/runner/work/mitmproxy/mitmproxy/test/mitmproxy/tservers.py", '\n 'line 116, in run',\n '    self.tmaster.run()',\n '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line '\n '108, in run',\n '    self.run_loop(loop.run_forever)',\n '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line 92, '\n 'in run_loop',\n '    loop = asyncio.get_event_loop()',\n '  File '\n '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '\n 'line 694, in get_event_loop',\n '    return get_event_loop_policy().get_event_loop()',\n '  File '\n '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '\n 'line 602, in get_event_loop',\n '    % threading.current_thread().name)',\n "RuntimeError: There is no current event loop in thread 'ProxyThread "\n "(*:38931)'.",\n '',\n 'four'] == ['four']
E         At index 0 diff: 'Exception in thread ProxyThread (*:40649):' != 'four'
E         Left contains 32 more items, first extra item: 'Traceback (most recent call last):'
E         Full diff:
E           [
E         +  'Exception in thread ProxyThread (*:40649):',
E         +  'Traceback (most recent call last):',
E         +  '  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/threading.py", '
E         +  'line 916, in _bootstrap_inner',
E         +  '    self.run()',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/test/mitmproxy/tservers.py", '
E         +  'line 116, in run',
E         +  '    self.tmaster.run()',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line '
E         +  '108, in run',
E         +  '    self.run_loop(loop.run_forever)',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line 92, '
E         +  'in run_loop',
E         +  '    loop = asyncio.get_event_loop()',
E         +  '  File '
E         +  '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '
E         +  'line 694, in get_event_loop',
E         +  '    return get_event_loop_policy().get_event_loop()',
E         +  '  File '
E         +  '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '
E         +  'line 602, in get_event_loop',
E         +  '    % threading.current_thread().name)',
E         +  "RuntimeError: There is no current event loop in thread 'ProxyThread "
E         +  "(*:40649)'.",
E         +  '',
E         +  '',
E         +  'Exception in thread ProxyThread (*:38931):',
E         +  'Traceback (most recent call last):',
E         +  '  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/threading.py", '
E         +  'line 916, in _bootstrap_inner',
E         +  '    self.run()',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/test/mitmproxy/tservers.py", '
E         +  'line 116, in run',
E         +  '    self.tmaster.run()',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line '
E         +  '108, in run',
E         +  '    self.run_loop(loop.run_forever)',
E         +  '  File "/home/runner/work/mitmproxy/mitmproxy/mitmproxy/master.py", line 92, '
E         +  'in run_loop',
E         +  '    loop = asyncio.get_event_loop()',
E         +  '  File '
E         +  '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '
E         +  'line 694, in get_event_loop',
E         +  '    return get_event_loop_policy().get_event_loop()',
E         +  '  File '
E         +  '"/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/asyncio/events.py", '
E         +  'line 602, in get_event_loop',
E         +  '    % threading.current_thread().name)',
E         +  "RuntimeError: There is no current event loop in thread 'ProxyThread "
E         +  "(*:38931)'.",
E         +  '',
E            'four',
E           ]

test/mitmproxy/addons/test_termlog.py:27: AssertionError
```
