### ISSUE TITLE
AttributeError running mitmproxy 5.2 from pip on Debian Buster

### ISSUE THREAD

**Issue by avdi** [mitmproxy/mitmproxy#4150]
#### Problem Description
mitmproxy fails with an AttributeError after being install via pip on Debian Buster

#### Steps to reproduce the behavior:
1. `pip3 install mitmproxy`
2. `mitmproxy`

Results:

```
$ /usr/local/bin/mitmproxy 
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 6, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/tools/main.py", line 22, in <module>
    from ._main import *  # noqa
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/tools/_main.py", line 17, in <module>
    from mitmproxy import proxy
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/__init__.py", line 2, in <module>
    from .root_context import RootContext
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/root_context.py", line 4, in <module>
    from mitmproxy.proxy import protocol
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/__init__.py", line 36, in <module>
    from .http2 import Http2Layer
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/proxy/protocol/http2.py", line 7, in <module>
    from h2 import connection
  File "/usr/local/lib/python3.7/dist-packages/h2/connection.py", line 23, in <module>
    from .events import (
  File "/usr/local/lib/python3.7/dist-packages/h2/events.py", line 14, in <module>
    from .settings import ChangedSetting, _setting_code_from_int
  File "/usr/local/lib/python3.7/dist-packages/h2/settings.py", line 25, in <module>
    class SettingCodes(enum.IntEnum):
  File "/usr/local/lib/python3.7/dist-packages/h2/settings.py", line 60, in SettingCodes
    ENABLE_CONNECT_PROTOCOL = SettingsFrame.ENABLE_CONNECT_PROTOCOL
AttributeError: type object 'SettingsFrame' has no attribute 'ENABLE_CONNECT_PROTOCOL'
```

**Comment by mhils** [comment]
What's your output of `pip freeze`?

**Comment by avdi** [comment]
Unfortunately I wound up blowing away all the pip-installed libraries, and I no longer have time to reproduce this 😞
