### ISSUE TITLE
RootContext object has no attribute change_upstream_prxoy_server

### ISSUE THREAD

**Issue by hfdzlsw** [mitmproxy/mitmproxy#4182]
when i use change_upstream_prxoy_server method, it cause the exception below
>INFO: Traceback (most recent call last):
  File "C:\Program Files\airtest_script\start_mitmproxy.py", line 42, in request
    flow.live.change_upstream_prxoy_server(proxy)
  File "c:\program files\python36\lib\site-packages\mitmproxy\proxy\protocol\base.py", line 73, in __getattr__
    return getattr(self.ctx, name)
  File "c:\program files\python36\lib\site-packages\mitmproxy\proxy\protocol\base.py", line 73, in __getattr__
    return getattr(self.ctx, name)
  File "c:\program files\python36\lib\site-packages\mitmproxy\proxy\protocol\base.py", line 73, in __getattr__
    return getattr(self.ctx, name)
  [Previous line repeated 5 more times]
AttributeError: 'RootContext' object has no attribute 'change_upstream_prxoy_server'

Python: 3.6.4
Mitmproxy: 5.0.0
Command: mitmdump -q -s "start_mitmproxy.py" --mode upstream:http://localhost:8081 --ssl-insecure

**Comment by hfdzlsw** [comment]
my code
>class ProxyService:
    def request(self, flow):
        if flow.request.method == "CONNECT":
            return
        try:
            if flow.live:
                flow.live.change_upstream_prxoy_server(("11.18.228.37", 4239))
        except Exception as e:
            self.ps_log.info(''.join(traceback.format_exception(etype=type(e), value=e, tb=e.__traceback__)))
addons = [
    ProxyService()
]
