### ISSUE TITLE
Running mitmweb on Windows 10 reports OSError: [WinError 10013]

### ISSUE THREAD

**Issue by BanChengClub** [mitmproxy/mitmproxy#4196]
#### Problem Description
Use mitmdump -p * (any port) to start normally without problems.
Using mitmweb -p *(any port) on Windows 10 prompts the following error:

C:\Users\administrator>mitmweb -p 8898
Traceback (most recent call last):
  File "d:\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Python\Python38\Scripts\mitmweb.exe\__main__.py", line 7, in <module>
  File "d:\programs\python\python38\lib\site-packages\mitmproxy\tools\_main.py", line 173, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "d:\programs\python\python38\lib\site-packages\mitmproxy\tools\_main.py", line 132, in run
    master.run()
  File "d:\programs\python\python38\lib\site-packages\mitmproxy\tools\web\master.py", line 108, in run
    http_server.listen(self.options.web_port, self.options.web_host)
  File "d:\programs\python\python38\lib\site-packages\tornado\tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "d:\programs\python\python38\lib\site-packages\tornado\netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [WinError 10013] An attempt was made to access the socket in a way that is not allowed by the access permissions.

#### Steps to reproduce the behavior:
1. Use CMD to open the command line window;
2. Enter mitmweb -p 8898, or any port; press Enter.
3. An error was reported: OSError: [WinError 10013] An attempt was made to access the socket in a way that is not allowed by the access authority.

#### System Information
C:\Users\administrator>mitmproxy --version
Error: mitmproxy's console interface is not supported on Windows. You can run mitmdump or mitmweb instead.

C:\Users\administrator>mitmdump --version
Mitmproxy: 5.2
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Windows-10-10.0.18362-SP0

C:\Users\administrator>mitmweb --version
Mitmproxy: 5.2
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Windows-10-10.0.18362-SP0

**Comment by sumerzhang** [comment]
It looks like an access permission problem. You can try to open command line as an administrator.

**Comment by BanChengClub** [comment]
> It looks like an access permission problem. You can try to open command line as an administrator.

it doesn't work，and I still have the same problem with Mitmproxy V6.0.2

**Comment by sjstein** [comment]
I am also having a very similar issue:

```
mitmproxy\bin>mitmweb -r ..\..\..\Downloads\login-choose_event-ride.flow
Traceback (most recent call last):
  File "mitmweb", line 4, in <module>
  File "mitmproxy\tools\main.py", line 168, in mitmweb
  File "mitmproxy\tools\main.py", line 127, in run
  File "mitmproxy\tools\web\master.py", line 108, in run
  File "tornado\tcpserver.py", line 151, in listen
  File "tornado\netutil.py", line 161, in bind_sockets
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
[17668] Failed to execute script mitmweb
```

```
mitmproxy\bin>mitmweb --version
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.19041-SP0

```
This is being run on a windows console run with elevated privs.

**Comment by TomasHubelbauer** [comment]
Seems to also be a problem in 7.0

**Comment by mhils** [comment]
FWIW this works perfectly fine for me, I'm not really sure what the issue is here.

**Comment by TomasHubelbauer** [comment]
I downgraded to 4.0.4 as I've seen that suggested somewhere and it did not help. The full error:
![image](https://user-images.githubusercontent.com/6831144/125940461-88a6ba13-cb23-458a-9f71-23755f7d6a1e.png)
Seems like an OS config issues as opposed to MITMproxy issue. I had Fiddler running and I thought it might have been interfering but killing it did not help.

**Comment by mhils** [comment]
Shot in the dark: Does it help if you specify `--web-host` to some internal/external IP?
We really just ask tornado to spawn a socket, there's nothing fancy going on on mitmproxy's side.

**Comment by TomasHubelbauer** [comment]
Huh
![image](https://user-images.githubusercontent.com/6831144/125941469-ee2d9f26-ea0f-4fbe-8073-f819019e0cff.png)
Looks like Windows itself is hogging 8081, not sure why.
Maybe MITMproxy could ask whether the user wants to select a random port if binding to the default one doesn't work. I've seen this behavior in some JS tooling and I think it is pretty user-friendly.

**Comment by Kaitoxic** [comment]
Same error

**Comment by keithgh1** [comment]
> Same error

@Kaitoxic 

It's been a couple years since I've played with this, but I think the problem I experienced was that another application on my system was already using the ports it was trying to listen on. Maybe 8080? or 8081?

Anyways, I'd look up what default port numbers mitmproxy uses by default, and then run a local command on an elevated command prompt run as administrator:

netstat -anob | find "LISTENING"

to look for a conflict.

If you find a conflict, either uninstall/stop that application that conflicts, or simply change the port numbers mitmproxy uses.

Hope this helps!
