### ISSUE TITLE
The phone can't be turned on mitm.it 

### ISSUE THREAD

**Issue by liyuemin7** [mitmproxy/mitmproxy#4200]
#### Problem Description
The phone can't be turned on mitm.it 
#### Steps to reproduce the behavior:
1. mitmweb -p 8080 
2. open mitm.it  
3.error :
114.240.84.34:37485: clientdisconnect
Exception in thread TCPConnectionHandler (ProxyServer: ::ffff:114.240.84.34:59258 -> :::8080):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 602, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 66, in handle_client_connection
    self.channel
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 78, in __init__
    None)
  File "/usr/lib/python3.6/site-packages/mitmproxy/connections.py", line 38, in __init__
    super().__init__(client_connection, address, server)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 489, in __init__
    super().__init__(connection)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 297, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected
#### System Information
Mitmproxy: 5.2
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core

**Comment by mhils** [comment]
This looks like an error in your network configuration. Does it work if you use a regular browser? How do you configure your client device?
