### ISSUE TITLE
mitmproxy crashed!

### ISSUE THREAD

**Issue by zhangli63** [mitmproxy/mitmproxy#4229]
#### Problem Description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 107, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 201, in __call__
    if not self._process_flow(flow):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 274, in _process_flow
    return self.handle_regular_connect(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 219, in handle_regular_connect
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 357, in _establish_tls_with_client_and_server
    self.ctx.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 299, in connect
    self.ctx.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/base.py", line 164, in connect
    self.server_conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/connections.py", line 267, in connect
    tcp.TCPClient.connect(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 465, in connect
    self.ip_address = connection.getpeername()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 12, in __call__
    self.disconnect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/proxy/protocol/base.py", line 147, in disconnect
    self.server_conn.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/connections.py", line 299, in finish
    tcp.TCPClient.finish(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 326, in finish
    self.wfile.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

mitmproxy has crashed!

#### Steps to reproduce the behavior:
1. Use it as usual, it happened suddenly

#### System Information
Mitmproxy: 5.2
Python:    3.8.3
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  macOS-10.15.2-x86_64-i386-64bit

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
