### ISSUE TITLE
can't run mitmweb.exe on windows

### ISSUE THREAD

**Issue by mickant** [mitmproxy/mitmproxy#4230]
#### Steps to reproduce the behavior:
1. use cmd to run command: C:\Program Files (x86)\mitmproxy\bin\mitmweb.exe
2. it shows reference to d:\****

#### System Information
C:\Program Files (x86)\mitmproxy\bin>mitmweb.exe
Traceback (most recent call last):
  File "mitmweb", line 2, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\main.py", line 22, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\_main.py", line 14, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\master.py", line 7, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\addonmanager.py", line 8, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\eventsequence.py", line 5, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\http.py", line 7, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\__init__.py", line 1, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\request.py", line 11, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\message.py", line 5, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\encoding.py", line 11, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\brotli.py", line 8, in <module>
ImportError: DLL load failed: The specified module could not be found.
[8592] Failed to execute script mitmweb

**Comment by jaybauson** [comment]
Following this as I have the same issue.

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/issues/5015
