### ISSUE TITLE
Crash when deleting temporary file

### ISSUE THREAD

**Issue by cweiske** [mitmproxy/mitmproxy#4233]
#### Problem Description
mitmproxy 5.1.1 crashed when I opened the request body in an external editor and then moved the temporary file to another location while the editor was open. When I exited the editor, mitmproxy probably wanted to clean up and delete the file and crashed.

I moved the file to another location because i wanted to use its contents for further analysis.

#### Steps to reproduce the behavior:
1. Run mitmproxy until a flow is visible
2. Show the flow details
3. Press "v" ("View flow body in an external viewer") and select "request".
4. Editor opens
5. Delete the temporary file
6. Close the editor
7. mitmproxy crashes

```
$ mitmproxy --mode transparent --showhost
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 598, in keypress
    return self.top_w.keypress(self.top_w_size(size,
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/overlay.py", line 149, in keypress
    self.master.keymap.handle("global", key)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/keymap.py", line 144, in handle
    return self.executor(b.command)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 266, in execute
    return self.call_strings(command_name, args)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/consoleaddons.py", line 191, in nav_select
    self.master.inject_key("m_select")
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 185, in inject_key
    self.loop.process_input([key])
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 598, in keypress
    return self.top_w.keypress(self.top_w_size(size,
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/overlay.py", line 139, in keypress
    self.callback(self.choices[self.walker.index])
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/consoleaddons.py", line 253, in callback
    self.master.commands.call_strings(cmd, repl)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/consoleaddons.py", line 370, in bodyview
    self.master.spawn_external_viewer(content, t)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 174, in spawn_external_viewer
    os.unlink(name)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/mproxyjtgyzkct'
```

#### System Information
```
Mitmproxy: 5.1.1
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.8.0-2-amd64-x86_64-with-glibc2.29
```

**Comment by Kriechi** [comment]
possibly related: #4185

**Comment by mhils** [comment]
Looks like we just need to catch the error here. This should be an easy fix, PRs welcome! 😃

**Comment by lups2000** [comment]
is this still an issue? There was a PR but it has been closed. 
I cannot reproduce it on macOS
