### ISSUE TITLE
crash with attribute error

### ISSUE THREAD

**Issue by rachmadaniHaryono** [mitmproxy/mitmproxy#4258]
#### Problem Description
Mitmproxy crash with following error

<details>
  <summary>error</summary>
  
```python
Traceback (most recent call last):
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/main_loop.py", line 1454, in faux_idle_callback
    callback()
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/main_loop.py", line 574, in entering_idle
    self.draw_screen()
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/main_loop.py", line 588, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/container.py", line 1089, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/container.py", line 1089, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/listbox.py", line 439, in render
    middle, top, bottom = self.calculate_visible(
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/listbox.py", line 330, in calculate_visible
    offset_rows, inset_rows = self.get_focus_offset_inset(
  File "/home/r3r/envs/mitmproxy_image/lib/python3.8/site-packages/urwid/listbox.py", line 907, in get_focus_offset_inset
    focus_rows = focus_widget.rows((maxcol,), True)
AttributeError: 'NoneType' object has no attribute 'rows'
```
</details>

i don't know if it is my own script or mitmproxy error but i would be thankful if anyone have any idea how to debug/fix it

#### Steps to reproduce the behavior:

1. run mitmproxy with following script https://github.com/rachmadaniHaryono/mitmproxy-image/blob/dev/mitmproxy_image/script.py
2. configure your browser for mitmproxy 
3. browse around

#### System Information
Mitmproxy: 5.3.0
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-5.8.0-26-generic-x86_64-with-glibc2.32

**Comment by mhils** [comment]
How did you install mitmproxy? This might be related to an outdated urwid version.

**Comment by rachmadaniHaryono** [comment]
with pypi

here is result of pip freeze

<details>
  <summary>list</summary>
  
appdirs==1.4.4
asgiref==3.3.0
attrs==20.2.0
backcall==0.2.0
blinker==1.4
Brotli==1.0.9
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.4
coverage==5.3
cryptography==3.2.1
decorator==4.4.2
docopt==0.6.2
fancycompleter==0.9.1
filelock==3.0.12
flake8==3.8.4
Flask==1.1.2
flask-shell-ipython==0.4.1
h11==0.11.0
h2==4.0.0
hpack==4.0.0
hydrus-api==2.14.3
hyperframe==6.0.0
idna==2.10
iniconfig==1.1.1
ipdb==0.13.4
ipython==7.18.1
ipython-genutils==0.2.0
isort==5.6.4
itsdangerous==1.1.0
jedi==0.17.2
Jinja2==2.11.2
kaitaistruct==0.8
ldap3==2.8.1
MarkupSafe==1.1.1
mccabe==0.6.1
mitmproxy==5.3.0
-e git+git@github.com:rachmadaniHaryono/mitmproxy-image.git@7cbfaf85b01a5f10c448154b1d0b0275bc3ca922#egg=mitmproxy_image
msgpack==1.0.0
mypy==0.790
mypy-extensions==0.4.3
packaging==20.4
parso==0.7.1
passlib==1.7.4
pathtools==0.1.2
pdbpp==0.10.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.0.0
pluggy==0.13.1
prompt-toolkit==3.0.8
protobuf==3.11.3
ptyprocess==0.6.0
publicsuffix2==2.20191221
py==1.9.0
pyasn1==0.4.8
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
Pygments==2.7.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyperclip==1.8.1
pyrepl==0.9.0
pytest==6.1.1
pytest-cov==2.10.1
pytest-flake8==1.0.6
pytest-mypy==0.7.0
pytest-watch==4.2.0
PyYAML==5.3.1
requests==2.24.0
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
six==1.15.0
sortedcontainers==2.1.0
toml==0.10.1
tornado==6.0.4
traitlets==5.0.4
typed-ast==1.4.1
typing-extensions==3.7.4.3
urllib3==1.25.10
urwid==2.1.2
watchdog==0.10.3
wcwidth==0.2.5
Werkzeug==1.0.1
wmctrl==0.3
wsproto==0.15.0
zstandard==0.13.0
</details>

**Comment by mhils** [comment]
Hm, tricky. Do you encounter the same issue without your script? 

The entire traceback points to urwid, which makes it a bit tricky to debug. I don't see anything particular in your script that looks promising, maybe the interaction with the view addon? This probably needs a good bunch of print() debugging from urwid code...

**Comment by rachmadaniHaryono** [comment]
> Do you encounter the same issue without your script?

i will test it

> I don't see anything particular in your script that looks promising, maybe the interaction with the view addon? 

so this function https://github.com/rachmadaniHaryono/mitmproxy-image/blob/7725ce9b10827bdd89f9b5fad6d0e40fb519eb7f/mitmproxy_image/script.py#L86

that is customized from https://github.com/mitmproxy/mitmproxy/blob/2774928319b706d8b6f85919f8811776342986c9/mitmproxy/addons/view.py#L415

**Comment by Kriechi** [comment]
This looks like a problem with your addon...
If you can reproduce it with the core mitmproxy (without modifications), please feel free to reopen this issue.
