### ISSUE TITLE
mitmproxy crash while reverting duplicated flow.

### ISSUE THREAD

**Issue by evilpan** [mitmproxy/mitmproxy#4275]
#### Problem Description
mitmproxy crash when revert duplicated (edited) flow.

#### Steps to reproduce the behavior:
1. replay a flow
2. duplicate that flow
3. revert the dupllicated flow

expected behavior: the duplicated flow is reverted. 
what happend in reality:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/window.py", line 312, in keypress
    return self.master.keymap.handle(
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/keymap.py", line 144, in handle
    return self.executor(b.command)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/command.py", line 266, in execute
    return self.call_strings(command_name, args)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/consoleaddons.py", line 209, in nav_down
    self.master.inject_key("down")
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/master.py", line 188, in inject_key
    self.loop.process_input([key])
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/usr/local/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/usr/local/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 104, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 982, in keypress
    return actual_key(self._keypress_down((maxcol, maxrow)))
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 1104, in _keypress_down
    self.change_focus((maxcol,maxrow), pos,
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 826, in change_focus
    self._body.set_focus(position)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/console/flowlist.py", line 66, in set_focus
    self.master.view.focus.index = index
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/view.py", line 654, in index
    self.flow = self.view[idx]
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/view.py", line 640, in flow
    raise ValueError("Attempt to set focus to flow not in view")
ValueError: Attempt to set focus to flow not in view

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```

#### System Information
Paste the output of "mitmproxy --version" here.
```
$ mitmproxy --version
Mitmproxy: 5.3.0
Python:    3.8.4
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Thanks for the report!

**Comment by lups2000** [comment]
This seems to have been fixed! :)
