### ISSUE TITLE
crash accessing .mitmproxy/command_history

### ISSUE THREAD

**Issue by igors** [mitmproxy/mitmproxy#4287]
#### Problem Description
mitmproxy crashes if `.mitmproxy/command_history` is inaccessible due to permissions

#### Steps to reproduce the behavior:
```$ mitmproxy --mode "reverse:https://qa1.onepeloton.com" -p 9999
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/urwid/container.py", line 1123, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 201, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 149, in keypress
    self.prompt_execute(text)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 169, in prompt_execute
    msg = p(txt)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 113, in execute_command
    self.master.commands.call("commands.history.add", txt)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/command.py", line 243, in call
    return self.commands[command_name].func(*args)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/addons/command_history.py", line 51, in add_command
    with self.history_file.open("a") as f:
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/Users/***/.mitmproxy/command_history'

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy```

#### System Information
Mitmproxy: 5.3.0
Python:    3.9.0
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit

**Comment by Prinzhorn** [comment]
What would be the expected behavior? mitmproxy controls `.mitmproxy` and it's contents so it be should allowed to assume that it has access to everything in this folder. How did you end up with wrong permissions?

**Comment by igors** [comment]
Expected behavior: not crash, ideally display an error message instead. Chances are I ended up with this by running mitmproxy as root before - `.mitmproxy/command_history` was owned by root.

**Comment by mhils** [comment]
I don't consider this important enough to keep this issue open, but I'd be more than happy to merge a PR that fixes this. :)
