### ISSUE TITLE
Modifying responses

### ISSUE THREAD

**Issue by jdan** [mitmproxy/mitmproxy#433]
When I intercept a request, how can I modify the response before sending it back to the client? Everytime I tab over to "Response" I see "No response. Press e and edit any aspect to add one."

Hitting e and typing anything crashes mitmproxy:

```
Traceback (most recent call last):
  File "/Users/jordan/.virtualenv/khan27/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 610, in run
    self.ui.run_wrapper(self.loop)
  File "/Users/jordan/.virtualenv/khan27/lib/python2.7/site-packages/urwid/display_common.py", line 757, in run_wrapper
    return fn()
  File "/Users/jordan/.virtualenv/khan27/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 835, in loop
    self.prompt_execute(k)
  File "/Users/jordan/.virtualenv/khan27/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 762, in prompt_execute
    msg = p(txt, *args)
  File "/Users/jordan/.virtualenv/khan27/lib/python2.7/site-packages/libmproxy/console/flowview.py", line 579, in edit
    200, "OK", flow.ODictCaseless(), "", None
  File "/Users/jordan/.virtualenv/khan27/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 673, in __init__
    assert isinstance(headers, ODictCaseless) or headers is None
AssertionError

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Shutting down...
```

This is version 0.11.1. 0.11 also fails.

**Comment by XiananLi** [comment]
Hi may I ask, when I intercepted the package, how can i modify the html script in the response package

**Comment by kajojify** [comment]
@XiananLi Hello! Could you please give more concrete example of what you want to do? :)

**Comment by Chingkhuba** [comment]
Hi,

 I am using mitmproxy as reverse proxy. I access the  site of a http upstream server through the mitmproxy ip:port url.

I want to modify the content of each response. Its a hyperlink which contains the absolute url pointing to the upstream http server. Because the hyperlink in the html response contains the absolute url with ip of the upstream http server, when I click on the link, it takes me directly to the upstream http server bypassing the mitmproxy server.

Documentation says I dont have much of a choice but to use hostname/domain mapping in os hosts file, but that's not an option for me.
I am looking for a solution using some command parameters in mitmproxy to rewrite content/pattern etc. I am sure this should be achievable. Alternately, I could also modify the source code directly and repack, but I am kinda lazy to check the re build process.

Can anybody help!

Regards
