### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by jkorinth** [mitmproxy/mitmproxy#4351]
#### Problem Description
The windows installer starts the gui after installation; every access to a website is causing one or more of the traces below. mitmproxy Web UI does not show any data.

````
Web server listening at http://127.0.0.1:8081/
Proxy server listening at http://*:8080
127.0.0.1:50240: clientconnect
Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 565, in request
  File "mitmproxy\addons\view.py", line 503, in add
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 50, in _sig_view_add
  File "mitmproxy\tools\web\app.py", line 213, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable
````

#### Steps to reproduce the behavior:
1.  Install Windows mitmproxy via installer.
2.  Setup Windows system proxy.
3.  Access website with HTTPS.

#### System Information
There is no mitmproxy executable in the installation folder; version is 6.0.0 according to installer.

**Comment by mhils** [comment]
Thanks for the report! I may have screwed this up. mitmproxy and mitmdump should work just fine, expect a 6.0.1 release soon. :)

**Comment by mhils** [comment]
6.0.1 is out, thanks again!
