### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by JReverse** [mitmproxy/mitmproxy#4355]
#### Problem Description
When loading a Flow / Dump from past sniffs it gives this error

#### Steps to reproduce the behavior:
1.  Open mitm ui
2.  Load a flow / dump of sniff
3.  Error occurs in console

#### System Information
Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 571, in response
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 565, in request
  File "mitmproxy\addons\view.py", line 503, in add
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 50, in _sig_view_add
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 571, in response
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 565, in request
  File "mitmproxy\addons\view.py", line 503, in add
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 50, in _sig_view_add
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 571, in response
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 565, in request
  File "mitmproxy\addons\view.py", line 503, in add
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 50, in _sig_view_add
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 571, in response
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 565, in request
  File "mitmproxy\addons\view.py", line 503, in add
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 50, in _sig_view_add
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 571, in response
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\view.py", line 612, in update
  File "blinker\base.py", line 266, in send
  File "blinker\base.py", line 266, in <listcomp>
  File "mitmproxy\tools\web\master.py", line 57, in _sig_view_update
  File "mitmproxy\tools\web\app.py", line 214, in broadcast
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable

ERROR:tornado.application:Uncaught exception GET /flows.json (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/flows.json', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "tornado\web.py", line 1702, in _execute
  File "mitmproxy\tools\web\app.py", line 229, in get
  File "mitmproxy\tools\web\app.py", line 126, in write
  File "tornado\escape.py", line 75, in json_encode
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable
ERROR:tornado.access:500 GET /flows.json (127.0.0.1) 93.02ms

**Comment by mhils** [comment]
Which mitmproxy version are you on?

**Comment by JReverse** [comment]
> Which mitmproxy version are you on?

@mhils 6.0.1 the latest downloaded from github

**Comment by mhils** [comment]
Could you please paste the output of `mitmproxy --version`?

**Comment by JReverse** [comment]
> Could you please paste the output of `mitmdump --version`?

Mitmproxy: 6.0.1 binary
Python:    3.9.0
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.19041-SP0

@mhils

**Comment by mhils** [comment]
Thanks! This is fixed by 0407ce3. 6.0.2 is just going through our CI pipeline, once https://github.com/mitmproxy/mitmproxy/actions/runs/423683015 is done in about 15 minutes you should be able to upgrade! 😃
