### ISSUE TITLE
Crash when opening detail view

### ISSUE THREAD

**Issue by alex1704** [mitmproxy/mitmproxy#4382]
#### Problem Description
Application crashes when open Detail tab.

#### Steps to reproduce the behavior:
1. open in browser https://example.com/
2. go to flow
3. open Detail tab

```
Traceback (most recent call last):
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/master.py", line 56, in run_loop
    loop()
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Users/alex/work/code/python/mitmproxy/venv/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/tabs.py", line 41, in keypress
    self.change_tab((self.tab_offset + 1) % n)
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/tabs.py", line 34, in change_tab
    self.show()
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/tabs.py", line 73, in show
    body = self.tabs[self.tab_offset % len(self.tabs)][1](),
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/flowview.py", line 176, in view_details
    return flowdetailview.flowdetails(self.view, self.flow)
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/flowdetailview.py", line 72, in flowdetails
    parts.append(("Alt names", ", ".join(strutils.bytes_to_escaped_str(x) for x in c.altnames)))
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/tools/console/flowdetailview.py", line 72, in <genexpr>
    parts.append(("Alt names", ", ".join(strutils.bytes_to_escaped_str(x) for x in c.altnames)))
  File "/Users/alex/work/code/python/mitmproxy/mitmproxy/utils/strutils.py", line 95, in bytes_to_escaped_str
    raise ValueError(f"data must be bytes, but is {data.__class__.__name__}")
ValueError: data must be bytes, but is str

mitmproxy has crashed!
```

#### System Information
Mitmproxy: 7.0.0.dev (+261, commit d8c3e8a)
Python:    3.9.0
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit

**Comment by Prinzhorn** [comment]
I can reproduce this with the +494 master on Ubuntu. But I get a different error.

For future issues please put your error message in the message body and not as an attachment. Otherwise it cannot be found by others via search engines or the GitHub search functionality.

```
Traceback (most recent call last):
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/master.py", line 56, in run_loop
    loop()
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/window.py", line 312, in keypress
    return self.master.keymap.handle(
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/keymap.py", line 144, in handle
    return self.executor(b.command)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/command.py", line 266, in execute
    return self.call_strings(command_name, args)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/consoleaddons.py", line 188, in nav_next
    self.master.inject_key("m_next")
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/master.py", line 188, in inject_key
    self.loop.process_input([key])
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/tabs.py", line 39, in keypress
    self.change_tab((self.tab_offset + 1) % n)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/tabs.py", line 34, in change_tab
    self.show()
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/tabs.py", line 73, in show
    body = self.tabs[self.tab_offset % len(self.tabs)][1](),
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/flowview.py", line 176, in view_details
    return flowdetailview.flowdetails(self.view, self.flow)
  File "/home/alex/Projects/super-secret-name/src/forks/mitmproxy/mitmproxy/tools/console/flowdetailview.py", line 58, in flowdetails
    c = sc.certificate_list[0]
IndexError: tuple index out of range
```
