### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by shifengboy** [mitmproxy/mitmproxy#4429]
#### Problem Description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/mitmweb", line 8, in <module>
    sys.exit(mitmweb())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mitmproxy/tools/main.py", line 168, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mitmproxy/tools/main.py", line 127, in run
    master.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mitmproxy/tools/web/master.py", line 108, in run
    http_server.listen(self.options.web_port, self.options.web_host)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use

#### Steps to reproduce the behavior:
1. mitmweb --listen-port 8083

#### System Information
Mitmproxy: 6.0.2
Python:    3.9.0
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  macOS-10.16-x86_64-i386-64bit

**Comment by shifengboy** [comment]
This problem is caused by the fact that my port 8081 is being used. After killing the process, it will work properly
