### ISSUE TITLE
cert expiration error - dictionary keys changed during iteration

### ISSUE THREAD

**Issue by esquid2** [mitmproxy/mitmproxy#4477]
Not sure what changed to cause this but now my mitmproxy is always crashing with the following error below now complaining about deleting keys in the dictionary that is being iterated over.

Attached a (very hacky) patch which gets it working on my system at least.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 279, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 365, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 369, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 501, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/lib/python3/dist-packages/mitmproxy/certs.py", line 326, in get_cert
    self.expire(entry)
  File "/usr/lib/python3/dist-packages/mitmproxy/certs.py", line 156, in expire
    for k, v in list(self.certs.items()):
RuntimeError: dictionary keys changed during iteration

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

-----

system info:

DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

$ dpkg -L mitmproxy
...
||/ Name           Version      Architecture Description
+++-==============-============-============-========================================
ii  mitmproxy      4.0.4-6.1    all          SSL-capable man-in-the-middle HTTP proxy

-----

[certs.py.patch.txt](https://github.com/mitmproxy/mitmproxy/files/6085551/certs.py.patch.txt)

**Comment by Kriechi** [comment]
mitmproxy 4.0.4 is multiple major releases behind and no longer supported.
