### ISSUE TITLE
Crash with Windscribe Chrome addon

### ISSUE THREAD

**Issue by DainBB** [mitmproxy/mitmproxy#4479]
#### Problem Description

While trying debug Windscribe addon some module of mitmproxy consistently crashing when addon tries access HTTPS GET                 nosslscribe.com / with following message dumped to console

Exception in thread Http2SingleStreamLayer-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 722, in run
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 203, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 257, in _process_flow
    request: http.HTTPRequest = self.read_request_headers(f)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 392, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 513, in read_request_headers
    scheme = self.request_message.headers.pop(':scheme')
  File "/usr/lib64/python3.6/_collections_abc.py", line 795, in pop
    value = self[key]
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/coretypes/multidict.py", line 39, in __getitem__
    raise KeyError(key)
KeyError: ':scheme'

#### Steps to reproduce the behavior:
1. Fresh install of Windows 10, latest Chrome and Chrome Windscribe addon without account
2. Try enable Windscribe 
3. Observe consistent crash of mitmproxy when it tries access nosslscribe.com

#### System Information
Mitmproxy: 5.3.0
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.1.12-124.48.5.el7uek.x86_64-x86_64-with-oracle-7.9

**Comment by mhils** [comment]
This problem should be fixed on master. Can you please [upgrade](https://mitmproxy.org/downloads/#branches/master/) and try again?

**Comment by DainBB** [comment]
Thank you for your reply 

Unfortunately I can't run Linux binaries on OL7/Centos7 due to 
"ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIZhxDFc/libstdc++.so.6)"
and can't compile from latest source code because of
"mitmproxy requires Python '>=3.8' but the running Python is 3.6.8"
as well as pipx does not install anything later than 5.3.0

I'll try install OL/Centos 8 but it will take time.

Regards,
Dain

**Comment by DainBB** [comment]
Getting same issue on 6.0.2
# ./mitmproxy --version
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.17-2036.103.3.1.el8uek.x86_64-x86_64-with-glibc2.28

Traceback (most recent call last):   nosslscribe.com /                                                                                                                       200         text/plain   12b 620ms Ex  File "threading.py", line 954, in _bootstrap_inner
  File "mitmproxy/proxy/protocol/http2.py", line 722, in run
  File "mitmproxy/proxy/protocol/http.py", line 204, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 258, in _process_flow
  File "mitmproxy/proxy/protocol/http2.py", line 392, in wrapper
  File "mitmproxy/proxy/protocol/http2.py", line 513, in read_request_headers
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/_collections_abc.py", line 819, in pop
  File "mitmproxy/coretypes/multidict.py", line 39, in __getitem__est_headers
KeyError: ':scheme'toolcache/Python/3.9.1/x64/lib/python3.9/_collections_abc.py", line 819, in pop
Exception in thread Http2SingleStreamLayer-9:ne 39, in __getitem__
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "mitmproxy/proxy/protocol/http2.py", line 722, in run
  File "mitmproxy/proxy/protocol/http.py", line 204, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 258, in _process_flow
  File "mitmproxy/proxy/protocol/http2.py", line 392, in wrapper
  File "mitmproxy/proxy/protocol/http2.py", line 513, in read_request_headers
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/_collections_abc.py", line 819, in pop
  File "mitmproxy/coretypes/multidict.py", line 39, in __getitem__est_headers
KeyError: ':scheme'toolcache/Python/3.9.1/x64/lib/python3.9/_collections_abc.py", line 819, in pop

**Comment by DainBB** [comment]
Attached offending flow, please let me know if you need anything else

[nossl.zip](https://github.com/mitmproxy/mitmproxy/files/6100960/nossl.zip)

**Comment by mhils** [comment]
Thanks! Can you please check if this still is an issue on master (7.0.0.dev, not 6.0.2, linked above)?

**Comment by DainBB** [comment]
I'm unable to verify it on master as I'm getting 522 Certificate verify failed: Hostname mismatch for everything related to windscribe.com domain, which is not an issue on 6.0.2

**Comment by mhils** [comment]
Thanks. Could you please run `mitmdump -vvv --set proxy_debug`, and attach the output here for a flow with this error?
