### ISSUE TITLE
Crash on invalid HTTP/2 state transition

### ISSUE THREAD

**Issue by bastienleonard** [mitmproxy/mitmproxy#4512]
#### Problem Description

mitmproxy crashes with the following error when enabling HTTP/2 in an Android app:

```
Exception in thread Http2SingleStreamLayer-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/h2/stream.py", line 117, in process_input
    func, target_state = _transitions[(self.state, input_)]
KeyError: (<StreamState.HALF_CLOSED_LOCAL: 5>, <StreamInputs.SEND_DATA: 3>)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http2.py", line 722, in run
    layer()
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http.py", line 204, in __call__
::ffff:10.13.21.34:43378: TcpDisconnect("(32, 'EPIPE')")
    if not self._process_flow(flow):
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http.py", line 382, in _process_flow
10.13.21.34:43378: clientdisconnect
    get_response()
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http.py", line 375, in get_response
    self.send_request_body(f.request, [f.request.data.content])
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http2.py", line 392, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http2.py", line 624, in send_request_body
    self.connections[self.server_conn].safe_send_body(
  File "/usr/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http2.py", line 71, in safe_send_body
    self.send_data(stream_id, frame_chunk)
  File "/usr/lib/python3.9/site-packages/h2/connection.py", line 857, in send_data
    frames = self.streams[stream_id].send_data(
  File "/usr/lib/python3.9/site-packages/h2/stream.py", line 935, in send_data
    self.state_machine.process_input(StreamInputs.SEND_DATA)
  File "/usr/lib/python3.9/site-packages/h2/stream.py", line 121, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input StreamInputs.SEND_DATA in state StreamState.HALF_CLOSED_LOCAL
```

As far as I understand, this means that our client (OkHttp) is sending data when the stream is closed for client :arrow_right: server communication.
To the best of our knowledge we don’t do anything special on the client side, but I wonder if improper resource disposal could be the cause somehow.
It would be great to at least prevent mitmproxy from crashing and display an error message instead. This would allow checking which request is causing the error, and hopefully using mitmproxy more or less normally for other requests.
For what it’s worth, Charles doesn’t have issues with the same app.

#### Steps to reproduce the behavior:

I don’t see a straightforward way of sharing this. I tried saving the flow to a file, but when replaying from the file the crash didn’t happen.

#### System Information

>Mitmproxy: 6.0.2
>Python:    3.9.2
>OpenSSL:   OpenSSL 1.1.1j  16 Feb 2021
>Platform:  Linux-5.11.1-arch1-1-x86_64-with-glibc2.33

**Comment by mhils** [comment]
Hi @bastienleonard, does upgrading to master help? We have a completely new proxy core there that will be part of the next release.

You can find precompiled binaries at https://mitmproxy.org/downloads/#branches/master/ :)

**Comment by bastienleonard** [comment]
Yes it works on master! Nice to see that big improvements are ongoing on the proxy as well. :)
