### ISSUE TITLE
mitmproxy has crashed - filedescriptor out of range

### ISSUE THREAD

**Issue by dc-avasilev** [mitmproxy/mitmproxy#4514]
#### Problem Description
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 100, in __call__
    layer()
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 204, in __call__
    if not self._process_flow(flow):
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 277, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 222, in handle_regular_connect
    layer()
  File "/usr/lib/python3.8/site-packages/mitmproxy/proxy/protocol/rawtcp.py", line 39, in __call__
    r = mitmproxy.net.tcp.ssl_read_select(conns, 10)
  File "/usr/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 229, in ssl_read_select
    ] or select.select(rlist, (), (), timeout)[0]
ValueError: filedescriptor out of range in select()
```

#### Steps to reproduce the behavior:
1. docker run --rm -it -v $HOME/.mitmproxy:/home/mitmproxy/.mitmproxy -w /home/mitmproxy/.mitmproxy -p 8888:8888 -p 127.0.0.1:8081:8081 mitmproxy/mitmproxy mitmweb
2. use it with simple script witch adds headers in request and response

#### System Information
mitmproxy - v6.0.2

**Comment by mhils** [comment]
Hi, does upgrading to master help? We have a completely new proxy core there that will be part of the next release.

You can find precompiled binaries at https://mitmproxy.org/downloads/#branches/master/ and we have a :dev docker tag :)

**Comment by dc-avasilev** [comment]
on :dev docker tag - seems to work fine

**Comment by mhils** [comment]
Excellen, then this will be fixed with the next release 😃
