### ISSUE TITLE
KeyError on stream_window_updated

### ISSUE THREAD

**Issue by rachmadaniHaryono** [mitmproxy/mitmproxy#4527]
#### Problem Description
```python
error: 127.0.0.1:35292: mitmproxy has crashed!
Traceback (most recent call last):
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/server.py", line 276, in server_event
    for command in layer_commands:
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 255, in handle_event
    yield from self._handle(event)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 640, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 661, in event_to_child
    yield from self.event_to_child(stream, command.event)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 649, in event_to_child
    for command in child.handle_event(event):
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 531, in passthrough
    for command in self.child_layer.handle_event(event):
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/tunnel.py", line 85, in _handle_event
    yield from self.event_to_child(event)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/tunnel.py", line 104, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/tunnel.py", line 72, in _handle_event
    yield from self.receive_data(event.data)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/tls.py", line 239, in receive_data
    yield from self.event_to_child(
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/tunnel.py", line 104, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 640, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 649, in event_to_child
    for command in child.handle_event(event):
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/_http2.py", line 296, in _handle_event
    yield from super()._handle_event(event)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/_http2.py", line 137, in _handle_event
    events = self.h2_conn.receive_data(event.data)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/_http_h2.py", line 98, in receive_data
    self.stream_window_updated(event.stream_id)
  File "/home/r3r/git/mitmproxy/mitmproxy/proxy/layers/http/_http_h2.py", line 115, in stream_window_updated
    stream: h2.stream.H2Stream = self.streams[stream_id]
KeyError: 79
```
unfortunately i don't know how to reproduce the error.
above error only printed on event log and didn't crash mitmproxy

e:
on my last submitted issue Kriechi said this:
```
This looks like a problem with your addon...
If you can reproduce it with the core mitmproxy (without modifications), please feel free to reopen this issue.
```
if this is look like problem with my addon again, i'm ok if this issue is closed

#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Mitmproxy: 7.0.0.dev (+388, commit 4e376c6)
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.8.0-48-generic-x86_64-with-glibc2.32

**Comment by mhils** [comment]
Thanks! It would be fantastic to have a clear repro, but we have to work with what we have. :) I'll take a look of the traceback is enough.

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/pull/4529 should fix this! 😃
