### ISSUE TITLE
new proxy core hangs instead of failing if listening port unavailable

### ISSUE THREAD

**Issue by r00t-** [mitmproxy/mitmproxy#4544]
ran into this because my script that restarts mitmdump to rotate the dump file or for #4456
uses a hardcoded delay after killing the old instance.
recently it took longer than usual for the old instance to die and release the port;
i always ended up with an newly started instance that was running but not listening on any ports.

did some bisecting on
```
time timeout 60 mitmdump -w /dev/null ; [ $? != 124 ]
```

and ended up on https://github.com/mitmproxy/mitmproxy/commit/e0e7934d22c4e5e42802a2e666c6d76e26728790

sadly i'm not familiar enough with python/asyncio to fix this.

it seems that `await asyncio.start_server()` simply never returns if it fails to bind the port...
https://github.com/mitmproxy/mitmproxy/commit/e0e7934d22c4e5e42802a2e666c6d76e26728790#diff-a5cc10fb7c496a1ea1c4f24aec72d0acecb34eaf5e50002d09c1f86e3132e55bR111
("Proxy server listening at " is never printed)

the docs don't mention anything about error behaviour:
https://docs.python.org/3.8/library/asyncio-stream.html#asyncio.start_server

**Comment by Prinzhorn** [comment]
Thanks for reporting this!

> it seems that `await asyncio.start_server()` simply never returns if it fails to bind the port...

I think it raises, but in `mitmdump` the error is swallowed somewhere. If you try `mitmproxy` it crashes

```
Traceback (most recent call last):
  File "/home/alex/Projects/src/forks/mitmproxy/mitmproxy/master.py", line 54, in run_loop
    loop()
  File "/home/alex/Projects/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/alex/Projects/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/alex/Projects/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/home/alex/Projects/src/forks/mitmproxy/venv/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/home/alex/Projects/src/forks/mitmproxy/mitmproxy/addons/proxyserver.py", line 120, in refresh_server
    self.server = await asyncio.start_server(
  File "/usr/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use

```

There might be a difference in error handling because of how addon errors are handled in `mitmproxy` vs `mitmdump`? After all `Proxyserver` is just an addon and the server is tarted from within the `configure` hook. @mhils probably already knows what's happening.

>  recently it took longer than usual for the old instance to die and release the port;

Is this something worth investigating as well? How are you stopping the instance?

**Comment by mhils** [comment]
Which platform is this happening on? We used to specify the following socket options:

https://github.com/mitmproxy/mitmproxy/blob/0407ce3106d7106ae4a6db2b3c1340f54e77f550/mitmproxy/net/tcp.py#L579-L582

`asyncio.start_server` should do pretty much the same. My understanding is that `reuse_address` will automatically be set to True on Unix if not specified ([src](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server)). Keepalive should not matter either.

**Comment by mhils** [comment]
Regarding what @Prinzhorn said, looks like we do have a mitmdump issue here. Repro on Windows:

```
$ mitmdump -p 123123123123
# hangs
```

```
$ mitmproxy -p 123123123123
# raises socket.gaierror
```

**Comment by Prinzhorn** [comment]
> Repro on Windows:

I'm seeing the same on Linux/Ubuntu. And I wrapped the `start_server` in try/catch to make sure it actually raises, which it does. So the options are correct.

**Comment by r00t-** [comment]
> Which platform is this happening on?

for me: linux, debian unstable, `Python 3.9.2`.

> > recently it took longer than usual for the old instance to die and release the port;

> Is this something worth investigating as well? How are you stopping the instance?

don't think that little change in shutdown time is worth investigating...
my script does some very naive "send sigterm, wait a few seconds, restart".
with #4456 the instance usually has >2gig of allocated objects at that point,
so it's no surprise that teardown takes some time.
but it was surprising that a new instance was actually running but not accepting requests.

thanks for looking into this, once i know about it, it's nothing that can't be worked around,
but it's kind of a weird error as you noticed. as said, sadly i can't help much with analysis.

**Comment by mbargiel** [comment]
I just ran into this issue where `mitmdump` appears to swallow the error (if any) and happily keep running. My problem is that I'm programmatically starting `mitmdump` and waiting for it to log on `stdout` to detect that I can start issuing HTTP requests (I'm running it over the command-line in a non-Python context for tests), and if I happen to rerun fast enough and hit this behaviour, nothing gets sent to `stdout` and my script therefore hangs.

Are there any suggested workaround? Maybe there is a better way to wait for mitmdump to be ready than expect "something" to be written to its `stdout`?

More specifics (in case this is relevant to my question):
- Installed mitmproxy/mitmdump using Homebrew (2-3 weeks ago, so it must be pretty recent)
- Running mitmdump from a Nodejs script (Node 12.20)

**Comment by Prinzhorn** [comment]
> Are there any suggested workaround? Maybe there is a better way to wait for mitmdump to be ready than expect "something" to be written to its `stdout`?

I personally run a gRPC server in both Node.js and mitmdump (via addon) so both can freely communicate.

In your case a simple socket or any type of ipc should work to send a signal. Mitmdump addons are really powerful. The [`running`](https://docs.mitmproxy.org/stable/api/events.html#LifecycleEvents.running) hook should be the right place, but be aware that it's currently fired twice https://github.com/mitmproxy/mitmproxy/issues/3584 (I keep a flag to prevent duplicate logic)

**Comment by r00t-** [comment]
for some very pragmatic less complex workarounds:
* if you do all of this programatically anyway, simply choose a random listen port on each startup
* alternatively test if the port is available by trying to bind it yourself before mitmdump startup (don't forget reuseaddr)
* instead of waiting for stdout output, wait for a successful response to a simple request (just the error message on sending "GET / HTTP/1.0\r\n\r\n" works fine.)
