### ISSUE TITLE
AssertionError: assert not self.tls

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4551]
The repro website is NSFW / porn (see also https://hackerone.com/chaturbate)

#### Problem Description

```
[::1]:60890: mitmproxy has crashed!
Traceback (most recent call last):
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/server.py", line 276, in server_event
    for command in layer_commands:
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 255, in handle_event
    yield from self._handle(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 613, in _handle_event
    yield from self.event_to_child(stream, event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 649, in event_to_child
    for command in child.handle_event(event):
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 531, in passthrough
    for command in self.child_layer.handle_event(event):
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 129, in handle_event
    yield from self.__continue(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 220, in __continue
    yield from self.__process(command_generator, event.reply)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 183, in __process
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/tunnel.py", line 85, in _handle_event
    yield from self.event_to_child(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/tls.py", line 306, in event_to_child
    yield from super().event_to_child(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/tunnel.py", line 124, in event_to_child
    yield from self.start_handshake()
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/tls.py", line 294, in start_handshake
    yield from self.start_tls()
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/tls.py", line 152, in start_tls
    assert not self.tls
AssertionError
```

#### Steps to reproduce the behavior:
1. `mitmdump --quiet`
2. `chromium --user-data-dir=`mktemp --directory` --start-maximized --no-default-browser-check --no-first-run --disable-translate --disable-extensions --incognito --proxy-server="localhost:8080" https://chaturbate.com` (don't mind all the arguments, I use that all the time aliased as `clean-chrome-instance`)

#### System Information

```
Mitmproxy: 7.0.0.dev (+417, commit 1b0fce6)
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.8.0-48-generic-x86_64-with-glibc2.29
```

**Comment by Prinzhorn** [comment]
Happens on https://imgur.com/ as well

I originally thought this was unrelated, but I'm seeing duplicate connection IDs with the crash (thank my UNIQUE contraints)

```py
_serverConnectionIds = {}

def server_connected(data):
  global _serverConnectionIds

  server = data.server

  if server.id in _serverConnectionIds:
    print('duplicate')
    print(server.id)
  else:
    _serverConnectionIds[server.id] = True
```

```
duplicate
08c89ca2-3f4d-45ae-ab1b-4ca71be87ed8
[::1]:33644: mitmproxy has crashed!
Traceback (most recent call last):
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/server.py", line 276, in server_event
    for command in layer_commands:
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 255, in handle_event
    yield from self._handle(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 613, in _handle_event
    yield from self.event_to_child(stream, event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 649, in event_to_child
    for command in child.handle_event(event):
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 531, in passthrough
    for command in self.child_layer.handle_event(event):
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 129, in handle_event
    yield from self.__continue(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 220, in __continue
    yield from self.__process(command_generator, event.reply)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layer.py", line 183, in __process
    command = command_generator.send(send)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/tunnel.py", line 85, in _handle_event
    yield from self.event_to_child(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/tls.py", line 306, in event_to_child
    yield from super().event_to_child(event)
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/tunnel.py", line 124, in event_to_child
    yield from self.start_handshake()
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/tls.py", line 294, in start_handshake
    yield from self.start_tls()
  File "/home/alex/src/forks/mitmproxy/mitmproxy/proxy/layers/tls.py", line 152, in start_tls
    assert not self.tls
AssertionError

```

**Comment by Prinzhorn** [comment]
My guess (as always) are race conditions. That's why I use these websites, they produce a lot of requests (tons of images at once)

**Comment by mhils** [comment]
Thanks! That's very likely caused by aa815a52469ce8e09f404c6f5e66af0f47c78829. We need a log with `--set proxy_debug -vvv`. If you have one great, otherwise I'll see if I can reproduce this in ~2 weeks.

**Comment by Prinzhorn** [comment]
There are some AssertionError in there 

[vvv.log](https://github.com/mitmproxy/mitmproxy/files/6273115/vvv.log)
