### ISSUE TITLE
Bring your own root CA

### ISSUE THREAD

**Issue by reegnz** [mitmproxy/mitmproxy#4598]
#### Problem Description

I like to use [mkcert](https://github.com/FiloSottile/mkcert) to generate self-signed certificates.
It would be great if I could tell mitmproxy to use the same root certificate to sign certificates instead of generating it's own root certificate. I'd rather just manage a single root.

#### Proposal
Allow a --root-ca-cert and --roo-ca-key flag where I can pass my own self-signed root certificate.

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/concepts-certificates/#using-a-custom-certificate-authority - does this answer your question? :)

**Comment by reegnz** [comment]
I tried that, but mkcert is not going to use the rootCA I pass in `--certs` to sign certificates when doing https MITM. That flag only expects certificates that it should trust, but not signing keys, so MITMproxy issues the certs with that key.

After inspecting the source, it seems like -certs is most definitely not for defining a certificate signing key:
https://github.com/mitmproxy/mitmproxy/blob/5a03098d23b7a2ad2ecfbbb33f6ac0bbd4692790/mitmproxy/addons/tlsconfig.py#L231-L265

I guess easiest option right now would be to try and softlink my keys into the $HOME/.mitmproxy folder.

**Comment by reegnz** [comment]
OK, found the issue I think:
https://github.com/mitmproxy/mitmproxy/blob/5a03098d23b7a2ad2ecfbbb33f6ac0bbd4692790/mitmproxy/certs.py#L475-L483

Here it's hardcoded to use the default_ca, and as far as I'm seeing that can only be residing in the configpath.

**Comment by mhils** [comment]
The section I linked to mentions that you need to replace `~/.mitmproxy/mitmproxy-ca.pem`, or change your confdir, not `--certs` :-)

**Comment by reegnz** [comment]
@mhils right, but if my certificates don't have the same filename patterns (eg. CA root mkcert is generating) then I don't have much of an option. confdir wouldn't work. :( 

So I tried softlinking:

```
❯ ln -s -f $(mkcert -CAROOT)/rootCA-key.pem $HOME/.mitmproxy/mitmproxy-ca.pem
❯ ln -s -f $(mkcert -CAROOT)/rootCA.pem $HOME/.mitmproxy/mitmproxy-ca-cert.pem
❯ mitmproxy
Traceback (most recent call last):
  File "/Users/zoltanreegn/.local/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/tools/main.py", line 143, in mitmproxy
    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/tools/main.py", line 88, in run
    pconf = process_options(parser, opts, args)
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/tools/main.py", line 51, in process_options
    return proxy.config.ProxyConfig(opts)
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/proxy/config.py", line 41, in __init__
    self.configure(options, set(options.keys()))
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/proxy/config.py", line 66, in configure
    self.certstore = certs.CertStore.from_store(
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/certs.py", line 206, in from_store
    ca = OpenSSL.crypto.load_certificate(
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1951, in load_certificate
    _raise_current_error()
  File "/Users/zoltanreegn/.local/pipx/venvs/mitmproxy/lib/python3.9/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'get_name', 'no start line')]
```

No luck...

**Comment by reegnz** [comment]
Ok, so this worked:
```
cat $(mkcert -CAROOT)/rootCA-key.pem $(mkcert -CAROOT)/rootCA.pem > mitmproxy-ca.pem
```

I guess that should be written in the docs then (private key + certificate concatenated after eachother in the same file).

**Comment by mhils** [comment]
At the moment this is only mentioned at https://docs.mitmproxy.org/stable/concepts-certificates/#ca-and-cert-files, but I'd be happy to merge a PR that adds a bit of explanation to https://docs.mitmproxy.org/stable/concepts-certificates/#using-a-custom-certificate-authority 😃

**Comment by reegnz** [comment]
@mhils I've adjusted the docs a bit, I hope that's what you meant.
