### ISSUE TITLE
Mitmproxy Crash

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#461]
This is from the latest commit as of now: https://github.com/mitmproxy/mitmproxy/commit/e089061996b6637179ddb0a17e6b203255deb2fb

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/protocol/http.py", line 982, in handle_messages
    while self.handle_flow():
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/protocol/http.py", line 1055, in handle_flow
    ret = self.process_request(flow, req)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/protocol/http.py", line 1248, in process_request
    return self.process_connect_request(self.c.server_conn.address)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/protocol/http.py", line 1395, in process_connect_request
    self.c.establish_ssl(server=True, client=True)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/proxy/server.py", line 215, in establish_ssl
    chain_file=chain_file
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/proxy/connection.py", line 66, in convert_to_ssl
    tcp.BaseHandler.convert_to_ssl(self, *args, **kwargs)
  File "build/bdist.macosx-10.10-x86_64/egg/netlib/tcp.py", line 432, in convert_to_ssl
    self.connection.do_handshake()
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1076, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
KeyError: 0

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by mhils** [comment]
Hi there,

thanks for the report! Unfortunately, @cortesi and I are fairly busy right now. We'll certainly get back to your issue, but it may take a bit - sorry for that.

Cheers,
Max

**Comment by mhils** [comment]
Hi Ryan,

which OS are you on?

Cheers,
Max

**Comment by Fuzion24** [comment]
OSX 10.10.2

**Comment by mhils** [comment]
Ok. Any way how you can reproduce this issue?

Thanks!
Max

**Comment by Fuzion24** [comment]
I'll close this until I have a reliable way to reproduce.
