### ISSUE TITLE
mitmdump crashes on TCP proxying

### ISSUE THREAD

**Issue by yoavfrancis** [mitmproxy/mitmproxy#464]
Hi there,

When running mitmdump (current git master version with the current git version of libmproxy and the other dependencies) with TCP proxying mode and browsing on Google Chrome (Win7) to Google.com and running a few searches - I get a few "crash" errors

These are the following messages I got:
```
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.0.18:54049: Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/root/mitmproxy/mitmproxy/libmproxy/protocol/tcp.py", line 79, in handle_messages
    dst.connection.send(contents)
  File "/root/mitmproxy/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 950, in send
    self._raise_ssl_error(self._ssl, result)
  File "/root/mitmproxy/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (32, 'EPIPE')

Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/root/mitmproxy/mitmproxy/libmproxy/protocol/tcp.py", line 45, in handle_messages
    contents = src.rfile.read(1)
  File "/root/mitmproxy/mitmproxy/netlib/netlib/tcp.py", line 132, in read
    raise NetLibDisconnect
NetLibDisconnect

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.0.18:54064: Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/root/mitmproxy/mitmproxy/libmproxy/protocol/tcp.py", line 45, in handle_messages
    contents = src.rfile.read(1)
  File "/root/mitmproxy/mitmproxy/netlib/netlib/tcp.py", line 132, in read
    raise NetLibDisconnect
NetLibDisconnect
```

Thanks for keeping up the great work :)!
Yoav

**Comment by yoavfrancis** [comment]
On a deeper look , it seems that the handling mechanism in protocol\http.py catches exceptions of type:

```
        except (
                HttpAuthenticationError,
                http.HttpError,
                proxy.ProxyError,
                tcp.NetLibError,
        ), e:
```

While protocol\tcp.py only catches `socket.error` exception.

So this explains why the NetLibXXX errors are raised (While on http proxying they are handled and logged) - However, regarding the other errors (Those that come from PyOpenSSL) - what's should be done with them?

**Comment by mhils** [comment]
Hey Yoav,

thanks for investigating. The errors you are seeing are apparently unexpected client or server disconnects. While we usually operate on plain sockets here (performance), this is not the case if SSL/TLS comes into play. It looks like there are two unrelated issues:

1. We should catch NetLibError as you indicated.
2. If there's SSL, we should only use the netlib wrappers (not dst.connection itself) for sending data, so that PyOpenSSLs errors appear as NetlibErrors.

I just commited a fix, let me know how it works.

Cheers,
Max

**Comment by yoavfrancis** [comment]
Hi Max!

Thanks for the super-fast response.
Your solution indeed fixes up a lot the errors - but there's still an error:

```

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.0.18:62969: Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/root/mitmproxy/mitmproxy/libmproxy/protocol/tcp.py", line 59, in handle_messages
    dst.connection.shutdown()
  File "/root/mitmproxy/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1157, in shutdown
    _raise_current_error()
  File "/root/mitmproxy/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
Error: []


mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.0.18:63911: Traceback (most recent call last):
  File "/root/mitmproxy/mitmproxy/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/root/mitmproxy/mitmproxy/libmproxy/protocol/tcp.py", line 59, in handle_messages
    dst.connection.shutdown()
  File "/root/mitmproxy/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1157, in shutdown
    _raise_current_error()
  File "/root/mitmproxy/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
Error: []
```

I tried omitting the "connection" from `dst.connection.shutdown` - however it seems that the `shutdown` method is not implemented in `ServerConnection` (libmproxy\proxy\connection.py) nor at `TCPClient` (netlib\tcp.py) - so my guess would be that it needs to be properly implemented in `TCPClient` (as it is in `TCPServer`) in netlib so things would work well?

Thanks,
Yoav

**Comment by mhils** [comment]
Closing (py)OpenSSL Connections is the worst PITA you can ever imagine (feel free to read through the comments in netlib.tcp...). I'd say screw it, just `return` here. We'll clean up everything on a higher level anyway. Fix commited, let me know how it works.

Cheers,
Max

**Comment by yoavfrancis** [comment]
Seems to do the trick :) Smart idea just leaving the cleanup to a higher level.
Thanks again!
