### ISSUE TITLE
v7 long running crash: RuntimeError: Cannot load trusted certificates

### ISSUE THREAD

**Issue by maceip** [mitmproxy/mitmproxy#4648]
#### Problem Description
after running mitmproxy v7 on my laptop macos (x86) for about a week I started seeing this crash, which caused me to have to kill and restart the service. Laptop lid had been closed and opened many times, etc.:

```console
[::1]:58609: server connect
Addon error: Traceback (most recent call last):
  File "mitmproxy/net/tls.py", line 176, in create_proxy_server_context
  File "OpenSSL/SSL.py", line 695, in load_verify_locations
  File "OpenSSL/_util.py", line 57, in exception_from_error_queue
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy/addons/tlsconfig.py", line 118, in tls_start
  File "mitmproxy/addons/tlsconfig.py", line 202, in create_proxy_server_ssl_conn
  File "mitmproxy/net/tls.py", line 178, in create_proxy_server_context
RuntimeError: Cannot load trusted certificates (ca_pemfile='/var/folders/bl/0xqk69bj57bgyth0vq78gx340000gn/T/_MEI0mDcad/certifi/cacert.pem', ca_path=None).

[::1]:58609: No TLS context was provided, failing connection.
[::1]:58609: mitmproxy has crashed!
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 279, in server_event
  File "mitmproxy/proxy/layer.py", line 168, in handle_event
  File "mitmproxy/proxy/layer.py", line 255, in handle_event
  File "mitmproxy/proxy/layer.py", line 168, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 690, in _handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 726, in event_to_child
  File "mitmproxy/proxy/layer.py", line 168, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 608, in passthrough
  File "mitmproxy/proxy/layer.py", line 168, in handle_event
  File "mitmproxy/proxy/tunnel.py", line 85, in _handle_event
  File "mitmproxy/proxy/layers/tls.py", line 306, in event_to_child
  File "mitmproxy/proxy/tunnel.py", line 104, in event_to_child
  File "mitmproxy/proxy/layer.py", line 168, in handle_event
  File "mitmproxy/proxy/tunnel.py", line 85, in _handle_event
  File "mitmproxy/proxy/tunnel.py", line 104, in event_to_child
  File "mitmproxy/proxy/layer.py", line 168, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 690, in _handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 726, in event_to_child
  File "mitmproxy/proxy/layer.py", line 129, in handle_event
  File "mitmproxy/proxy/layer.py", line 220, in __continue
  File "mitmproxy/proxy/layer.py", line 207, in __process
  File "mitmproxy/proxy/tunnel.py", line 57, in _handle_event
  File "mitmproxy/proxy/layers/tls.py", line 306, in event_to_child
  File "mitmproxy/proxy/tunnel.py", line 124, in event_to_child
  File "mitmproxy/proxy/layers/tls.py", line 294, in start_handshake
  File "mitmproxy/proxy/layers/tls.py", line 159, in start_tls
AssertionError

[::1]:58609: Server TLS handshake failed. connection closed
```

#### Steps to reproduce the behavior:
not sure yet how to reliably reproduce this other than running mitmdump for long periods of time. I dont have -vvv logs 

#### System Information
Mitmproxy: 7.0.0.dev binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  macOS-11.2.3-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks!

Some background here: The mitmproxy binaries are generated using PyInstaller and work similar to a self-extracting zip file: On start they first need to extract some resources to a temporary directory so that they can then by read by Python code.

In your particular case, the trusted CA certs were extracted to `/var/folders/bl/0xqk69bj57bgyth0vq78gx340000gn/T/_MEI0mDcad/certifi/cacert.pem`, and then later on couldn't be retrieved anymore. That's a bit weird - either something is deleting mitmproxy's files under its feet, or some other funky stuff is going on. Unless you have any explanation for this, could you check if the respective file exists the next time you hit this error?

**Comment by maceip** [comment]
it looks like macos will delete everything in DARWIN_USER_TEMP_DIR after 3
days

% getconf DARWIN_USER_TEMP_DIR
/var/folders/bl/0xqk69bj57bgyth0vq78gx340000gn/T/

so storing trusted CA certs in there is likely going to cause problems. Is
there a way to get it to load certs from a more permanent location?

**Comment by mhils** [comment]
Generally speaking we are just relying on what PyInstaller is doing here, so this ideally should be fixed upstream.
There are two viable workarounds from our end: 

1. Install mitmproxy via other means. Our default recommendation is `brew`, but I realize that this doesn't work for snapshots. Alternatively, `pipx` (or regular pip) should work just as well.
2. Fix mitmproxy/addons/tlsconfig.py to re-use the same `SSL.Context`. This is a rather complex undertaking, but would enable some overall some performance benefits.

**Comment by maceip** [comment]
ok this makes sense. closing
