### ISSUE TITLE
Exception in thread TCPConnectionHandler, OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by Satamana** [mitmproxy/mitmproxy#4657]
#### Problem Description
Hi, we collect website requests and responses with Selenium and Mitmproxy in AWS Fargate docker containers. Most of the scans finish ok, but some of them freeze on this error. Also, If the exception below appears, the container runs until I stop it, it doesn't stop after the exception.

Exception in thread TCPConnectionHandler (ProxyServer: ::ffff:194.26.29.147:37992 -> :::8080):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 602, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 62, in handle_client_connection
    h = ConnectionHandler(
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 75, in __init__
    self.client_conn = connections.ClientConnection(
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/connections.py", line 38, in __init__
    super().__init__(client_connection, address, server)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 489, in __init__
    super().__init__(connection)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 297, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

#### System Information
Mitmproxy 6.0.2
Python 3.8
Linux 5.8.0-55-generic #62~20.04.1-Ubuntu x86_64

**Comment by mhils** [comment]
This should be fixed in the latest 7.0 snapshots (https://github.com/mitmproxy/mitmproxy/issues/4632#issuecomment-860181919). Can I ask you to upgrade and try again? 😃

**Comment by Satamana** [comment]
Thanks. I will upgrade after release and answer then.
