### ISSUE TITLE
mitm dump crashed 

### ISSUE THREAD

**Issue by THAVASIGTI** [mitmproxy/mitmproxy#4667]
#### Steps to reproduce the behavior:
1. Mitmproxy : 6.0.2 binary
2. python 3.9.1
3. ubuntu 18.04 lts

Addon error: Traceback (most recent call last):
  File "mitmproxy/addons/termlog.py", line 31, in log
  File "click/termui.py", line 548, in secho
  File "click/utils.py", line 273, in echo
BrokenPipeError: [Errno 32] Broken pipe

Addon error: Traceback (most recent call last):
  File "mitmproxy/addons/dumper.py", line 268, in response
  File "mitmproxy/addons/dumper.py", line 236, in echo_flow
  File "mitmproxy/addons/dumper.py", line 174, in _echo_request_line
  File "mitmproxy/addons/dumper.py", line 72, in echo
  File "click/termui.py", line 548, in secho
  File "click/utils.py", line 273, in echo
BrokenPipeError: [Errno 32] Broken pipe

Addon error: Traceback (most recent call last):
  File "mitmproxy/addons/termlog.py", line 31, in log
  File "click/termui.py", line 548, in secho
  File "click/utils.py", line 273, in echo
BrokenPipeError: [Errno 32] Broken pipe

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by Prinzhorn** [comment]
Can you provide **Steps to reproduce the behavior**? Or does it happen immediately when you start `mitmproxy`?

v7 will be released soon, does the error happen with the latest version as well? You can download a build here https://mitmproxy.org/downloads/#branches/main/
