### ISSUE TITLE
Question regarding --ignore

### ISSUE THREAD

**Issue by gfrench17** [mitmproxy/mitmproxy#468]
Hi Max,

is it possible to define an inverted list with --ignore, i.e. instead of 

--ignore google.com -> disregard google.com content via Port 443

define something like

--ingore (ignore everything except for mySite.com and myOtherSite.com)

Cheers
Gordon

**Comment by mhils** [comment]
Hi @gfrench17,

you can use a negative lookahead in the regex:
`--ignore "^(?!mysite.com)(?!myothersite.com)"`

I'll add an example to the docs.

Cheers,
Max

**Comment by ryanzzff** [comment]
Is this the correct way to open in Terminal?
```
~$ mitmproxy --ignore "^(?!google\.com)"
```
but I got this error:
```
-bash: !google\.com: event not found
```
and I tried to escape the `!`: 
```
~$ mitmproxy --ignore "^(?\!google\.com)"
```
I got this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 3, in <module>
    mitmproxy()
  File "/Library/Python/2.7/site-packages/libmproxy/main.py", line 89, in mitmproxy
    proxy_config = process_proxy_options(parser, options)
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/config.py", line 196, in process_proxy_options
    ssl_ports=ssl_ports
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/config.py", line 78, in __init__
    self.check_ignore = HostMatcher(ignore_hosts)
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/config.py", line 17, in __init__
    self.regexes = [re.compile(p, re.IGNORECASE) for p in self.patterns]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of pattern
```

please help, thanks.

**Comment by mhils** [comment]
@ryanzzff: sorry for the late reply - you need to use single quotes. The docs are updated accordingly now.
