### ISSUE TITLE
http-stream-modify addon example doesn't work

### ISSUE THREAD

**Issue by cbenien** [mitmproxy/mitmproxy#4706]
#### Problem Description
I'm trying to write an addon that randomly modifies the response chunk sizes (not the content), to be used as a chaos testing tool for our software. I've set up a vanilla mitmproxy and copied the example code from https://docs.mitmproxy.org/stable/addons-examples/#http-stream-modify into a local file `chunk.py` and get the following error at runtime:

```
$ docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 8080:8080 mitmproxy/mitmproxy mitmdump --mode reverse:httpbin.org -s /home/mitmproxy/.mitmproxy/chunk.py
Loading script /home/mitmproxy/.mitmproxy/chunk.py
Proxy server listening at http://*:8080
172.17.0.1:45402: client connect
172.17.0.1:45402: server connect httpbin.org (52.201.75.114:443)
172.17.0.1:45402: Streaming response from httpbin.org.
172.17.0.1:45402: mitmproxy has crashed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/server.py", line 279, in server_event
    for command in layer_commands:
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/tunnel.py", line 85, in _handle_event
    yield from self.event_to_child(event)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/tls.py", line 320, in event_to_child
    yield from super().event_to_child(event)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/tunnel.py", line 104, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 690, in _handle_event
    yield from self.event_to_child(stream, event)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 755, in event_to_child
    yield from self.event_to_child(conn, command.event)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 740, in event_to_child
    for command in child.handle_event(event):
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/_http1.py", line 52, in _handle_event
    yield from self.send(event)
  File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/_http1.py", line 203, in send
    raw = b"%x\r\n%s\r\n" % (len(event.data), event.data)
TypeError: object of type 'generator' has no len()
```

#### Steps to reproduce the behavior:
1. Run above docker command which acts as a reverse proxy to http://httpbin.org
2. Run the following curl command: `curl -i localhost:8080/stream/2`

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 7.0.0
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.28
```

**Comment by mhils** [comment]
Thanks for the heads-up! The API indeed changed here, `.stream` is not a generator anymore, it's now called repeatedly with one chunk of data each time. We need to update the example and ideally also add some integration tests.

**Comment by cbenien** [comment]
Thanks, that helps already. Here's a small example I put together with the new API. Feel free to use this for the examples if you like it:
```
from mitmproxy import ctx


class StreamModifier:
    def __init__(self, flow):
        self.flow = flow
        self.idx = 0

    def process_chunk(self, chunk):
        ctx.log.info(f"Received chunk {self.idx} with length {len(chunk)} for URL {self.flow.request.url}")
        self.idx += 1
        return chunk


def responseheaders(flow):
    mod = StreamModifier(flow)
    flow.response.stream = mod.process_chunk
```

**Comment by cbenien** [comment]
Is there a way to change the number of chunks in the stream with this API? E.g. merge two chunks together or split one chunk into two? With the old generator API, that would have been possible (in theory)

**Comment by mhils** [comment]
Not right now, sorry. You can probably change that easily by hacking around here:
https://github.com/mitmproxy/mitmproxy/blob/2d75d06eb69c1f52f72aefe5b1f02a4ff72dcfce/mitmproxy/proxy/layers/http/__init__.py#L320-L334

and here for requests:

https://github.com/mitmproxy/mitmproxy/blob/2d75d06eb69c1f52f72aefe5b1f02a4ff72dcfce/mitmproxy/proxy/layers/http/__init__.py#L230-L258
