### ISSUE TITLE
"Cannot assemble flow with missing content" when exporting streamed flow in raw format

### ISSUE THREAD

**Issue by KORraNpl** [mitmproxy/mitmproxy#4714]
#### Problem Description
When a response (and possibly request, haven't checked that) is streamed and user tries to command `:export.clip raw @focus`, there is an exception:

```
Traceback (most recent call last):
  File "/Users/korran/Projects/mitmproxy/mitmproxy/master.py", line 54, in run_loop
    loop()
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/tools/console/window.py", line 316, in keypress
    k = super().keypress(size, k)
  File "/Users/korran/Projects/mitmproxy/venv/lib/python3.9/site-packages/urwid/container.py", line 1123, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/tools/console/statusbar.py", line 201, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/tools/console/statusbar.py", line 149, in keypress
    self.prompt_execute(text)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/tools/console/statusbar.py", line 169, in prompt_execute
    msg = p(txt)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/tools/console/statusbar.py", line 115, in execute_command
    execute(txt)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/command.py", line 273, in execute
    return self.call_strings(command_name, args)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/command.py", line 259, in call_strings
    return self.commands[command_name].call(args)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/command.py", line 129, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/command.py", line 303, in wrapper
    return function(*args, **kwargs)
  File "/Users/korran/Projects/mitmproxy/mitmproxy/addons/export.py", line 189, in clip
    v = strutils.always_str(func(flow))
  File "/Users/korran/Projects/mitmproxy/mitmproxy/addons/export.py", line 121, in raw
    return b"".join([raw_request(f), separator, raw_response(f)])
  File "/Users/korran/Projects/mitmproxy/mitmproxy/addons/export.py", line 109, in raw_response
    return assemble.assemble_response(cleanup_response(f))
  File "/Users/korran/Projects/mitmproxy/mitmproxy/net/http/http1/assemble.py", line 17, in assemble_response
    raise ValueError("Cannot assemble flow with missing content")
ValueError: Cannot assemble flow with missing content
```
#### Steps to reproduce the behavior:
1. Run mitmproxy with `--set stream_large_bodies=10k`
2. `curl -x 127.0.0.1 www.google.com 1>/dev/null`
3. `:export.clip raw @focus`

#### System Information
```
Mitmproxy: 8.0.0.dev (+17, commit 13131e2)
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  macOS-11.5.1-x86_64-i386-64bit
```
This exception is explicitly raised when `flow.response.content` is `None`, but I think it's still valuable to export whatever is available in a flow. I was thinking about setting some artificial content (or `b''`) for streamed request/response, but it doesn't seem like a good idea.

**Comment by mhils** [comment]
Thanks for the clear report! 😃
