### ISSUE TITLE
Cannot use upstream nordvpn proxy

### ISSUE THREAD

**Issue by tsoernes** [mitmproxy/mitmproxy#4726]
#### Problem Description
When using an upstream proxy from NordVPN, then connecting to mitmproxy through Google Chome, mitmproxy crashes 
#### Steps to reproduce the behavior:
```
mitmproxy --listen-port 8080 --ssl-insecure --mode upstream:https://se416.nordvpn.com:89 --upstream-auth USER:PASS 

```
```
mitmdump --listen-port 8081 --ssl-insecure --mode upstream:https://de873.nordvpn.com:89 --upstream-auth USER:PASS                 
Proxy server listening at http://*:8081
[::1]:53806: clientconnect
::1:53806: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53806: Ignoring server verification error, continuing with connection
[::1]:53808: clientconnect
::1:53808: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53808: Ignoring server verification error, continuing with connection
[::1]:53810: clientconnect
::1:53810: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53810: Ignoring server verification error, continuing with connection
[::1]:53812: clientconnect
[::1]:53814: clientconnect
::1:53812: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53812: Ignoring server verification error, continuing with connection
::1:53814: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53814: Ignoring server verification error, continuing with connection
[::1]:53816: clientconnect
::1:53816: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53816: Ignoring server verification error, continuing with connection
[::1]:53818: clientconnect
::1:53818: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)
::1:53818: Ignoring server verification error, continuing with connection
[::1]:53806: Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 396, in convert_to_tls
    self.connection.do_handshake()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1828, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1566, in _raise_ssl_error
    _raise_current_error()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'unexpected message')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 445, in _establish_tls_with_server
    self.server_conn.establish_tls(
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/connections.py", line 369, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 399, in convert_to_tls
    raise self.ssl_verification_error
mitmproxy.exceptions.InvalidCertificateException: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 100, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 204, in __call__
    if not self._process_flow(flow):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 279, in _process_flow
    return self.handle_upstream_connect(f)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 252, in handle_upstream_connect
    return layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 101, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 455, in _establish_tls_with_server
    raise exceptions.InvalidServerCertificate(str(e))
mitmproxy.exceptions.InvalidServerCertificate: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 26, in __call__
    self.disconnect()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/base.py", line 153, in disconnect
    self.server_conn.close()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 380, in close
    close_socket(self.connection._socket)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 239, in close_socket
    sock.shutdown(socket.SHUT_WR)
TypeError: shutdown() takes 1 positional argument but 2 were given

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 396, in convert_to_tls
    self.connection.do_handshake()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1828, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1566, in _raise_ssl_error
    _raise_current_error()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'unexpected message')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 445, in _establish_tls_with_server
    self.server_conn.establish_tls(
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/connections.py", line 369, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 399, in convert_to_tls
    raise self.ssl_verification_error
mitmproxy.exceptions.InvalidCertificateException: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http1.py", line 100, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 204, in __call__
    if not self._process_flow(flow):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 279, in _process_flow
    return self.handle_upstream_connect(f)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 252, in handle_upstream_connect
    return layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/http.py", line 101, in __call__
    layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/tls.py", line 455, in _establish_tls_with_server
    raise exceptions.InvalidServerCertificate(str(e))
mitmproxy.exceptions.InvalidServerCertificate: Certificate verification error for localhost: Hostname mismatch (errno: 62, depth: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 26, in __call__
    self.disconnect()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/proxy/protocol/base.py", line 153, in disconnect
    self.server_conn.close()
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 380, in close
    close_socket(self.connection._socket)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 239, in close_socket
    sock.shutdown(socket.SHUT_WR)
TypeError: shutdown() takes 1 positional argument but 2 were given

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
[::1]:53806: clientdisconnect
[::1]:53820: clientconnect
```

#### System Information
```
mitmproxy --version                                                                                                                                                     (base) 1.4m
Mitmproxy: 6.0.2
Python:    3.8.8
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.12.15-200.fc33.x86_64-x86_64-with-glibc2.10
```

**Comment by mhils** [comment]
Please upgrade to the latest mitmproxy release and try again!
