### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by jamime** [mitmproxy/mitmproxy#478]
I have seen multiple places claiming windows support for `mitmdump` however I can not get it to launch.

> C:\Python34\Scripts>py mitmdump
Traceback (most recent call last):
  File "mitmdump", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\Users\IEUser\Downloads\mitmproxy-master\mitmproxy-master\mitmdump", line 2, in <module>
    from libmproxy.main import mitmdump
  File "c:\users\ieuser\downloads\mitmproxy-master\mitmproxy-master\libmproxy\main.py", line 73
    except ProxyServerError, v:
                           ^
SyntaxError: invalid syntax

Am I doing something wrong? This worked fine on my Mac.

I've tried installing via pip and git and I get the same error.

**Comment by mhils** [comment]
Hi Jamie,

we do have Windows support for mitmdump, but we're still Python 2 only.

Cheers,
Max
