### ISSUE TITLE
An exception occurs when call flow.copy() in version 7

### ISSUE THREAD

**Issue by FeeiCN** [mitmproxy/mitmproxy#4781]
#### Problem Description
An exception occurs when call flow.copy() in version 7

#### Steps to reproduce the behavior:
1. add a custom script, and run `mitmdump -s=bac.py`
in bac.py, flow.copy() in response function, then ctx.master.commands.call("replay.client", [flow_copy])
```python
@concurrent
    def response(self, flow: http.HTTPFlow) -> None:
        print(f'< [RESP] {flow.request.method} {flow.request.url}')

        resp = flow.response.get_text(strict=False)

        # 此次响应是否为重放探测，是则检测响应内容判定越权，不是则发起重放探测请求
        if hasattr(flow.request, 'is_replay_detect') and flow.request.is_replay_detect:
            # print('   > 漏洞检测请求不做修改，跳过')
            return
        else:
            # GET方式的Query部分，测试用例：漏洞管理平台、GitHub Avatar
            print(f'   > GET Query探测，共{len(flow.request.query)}个参数')
            for i, key in enumerate(dict(flow.request.query)):
                value = flow.request.query[key]
                print(f'      > [{i + 1}] {key} = {value}')
                if re.match(self.regex_number, value):  # 如果Value为纯数字
                    # 白名单情况-timestamp，长度为10位（秒）或者13位（毫秒）且首位为1(如果是2则会增加20年左右)数字，例如1624001999117(ms) 1624002166(s)
                    if len(value) in [10, 13] and value[:1] == '1':
                        print(f'         > 此参数为时间戳，跳过检测')
                        return
                    print(f'         > 参数{key}的值{value}，可能存在越权漏洞')
                    uniq_mark = self.uniq_mark(flow, key)
                    if uniq_mark not in self.processed_requests:
                        print(
                            f'         > 历史上并未探测过，{uniq_mark} processed_requests_len: {len(self.processed_requests)}')
                        replay_flows = []
                        payloads = self.payloads_number(value)
                        for payload in payloads:
                            flow_copy = flow.copy()
                            flow_copy.request.query[key] = payload
                            print(f'            > 值{value}更改为{payload}，发起探测请求 {flow_copy.request.url}')
                            flow_copy.request.is_replay_detect = True
                            ctx.master.commands.call("replay.client", [flow_copy])
```
2. `https_proxy=http://127.0.0.1:8080 curl --cacert ~/.mitmproxy/mitmproxy-ca-cert.pem https://feei.cn/a.php\?a\=123`
3. exception detail
```Traceback (most recent call last):
  File "bac.py", line 198, in response
    flow_copy = flow.copy()
  File "mitmproxy/http.py", line 1244, in copy
  File "mitmproxy/flow.py", line 166, in copy
  File "mitmproxy/controller.py", line 78, in __init__
  File "mitmproxy/controller.py", line 16, in __init__
  File "asyncio/locks.py", line 177, in __init__
  File "asyncio/events.py", line 642, in get_event_loop
RuntimeError: There is no current event loop in thread 'ScriptThread'.```
```
➜  bac git:(main) ✗ mitmproxy --version
Mitmproxy: 7.0.2
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.5-x86_64-i386-64bit

➜  bac git:(main) ✗ pip3 show mitmproxy
Name: mitmproxy
Version: 7.0.2
Summary: An interactive, SSL/TLS-capable intercepting proxy for HTTP/1, HTTP/2, and WebSockets.
Home-page: http://mitmproxy.org
Author: Aldo Cortesi
Author-email: aldo@corte.si
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: h11, msgpack, asgiref, Brotli, zstandard, cryptography, protobuf, ruamel.yaml, ldap3, click, pyOpenSSL, hyperframe, blinker, pyparsing, publicsuffix2, tornado, kaitaistruct, sortedcontainers, certifi, pyperclip, urwid, wsproto, passlib, flask, h2
Required-by:
```

**Comment by mhils** [comment]
This should be fixed in mitmproxy 8. 😃
