### ISSUE TITLE
mitmproxy crashes when I try to copy binary content

### ISSUE THREAD

**Issue by huseyinturan** [mitmproxy/mitmproxy#4795]
#### Problem Description
When I try to copy request content that has a binary format, mitmproxy crashes.
Coping binary data to the clipboard may be ridiculous but I just want to report this crash.

Traceback (most recent call last):
  File "mitmproxy/master.py", line 54, in run_loop
  File "urwid/main_loop.py", line 287, in run
  File "urwid/main_loop.py", line 385, in _run
  File "urwid/main_loop.py", line 1494, in run
  File "urwid/compat.py", line 58, in reraise
  File "asyncio/events.py", line 80, in _run
  File "urwid/raw_display.py", line 416, in <lambda>
  File "urwid/raw_display.py", line 515, in parse_input
  File "urwid/main_loop.py", line 412, in _update
  File "urwid/main_loop.py", line 513, in process_input
  File "mitmproxy/tools/console/window.py", line 316, in keypress
  File "urwid/container.py", line 1123, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 201, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 149, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 169, in prompt_execute
  File "mitmproxy/tools/console/statusbar.py", line 115, in execute_command
  File "mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
  File "mitmproxy/command.py", line 273, in execute
  File "mitmproxy/command.py", line 259, in call_strings
  File "mitmproxy/command.py", line 129, in call
  File "mitmproxy/command.py", line 303, in wrapper
  File "mitmproxy/addons/cut.py", line 136, in clip
  File "mitmproxy/utils/strutils.py", line 46, in always_str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 3: invalid start byte

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy/issues

#### Steps to reproduce the behavior:
1.  Ctrl+L
2. @all request.content
3. Enter

#### System Information
Mitmproxy: 7.0.2 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.11.0-27-generic-x86_64-with-glibc2.31

**Comment by Prinzhorn** [comment]
Thanks for reporting this, there are several related / duplicate issues already. #3965
