### ISSUE TITLE
 mitmproxy has crashed!

### ISSUE THREAD

**Issue by JReverse** [mitmproxy/mitmproxy#4797]
#### Problem Description
mitmproxy has crashed!

#### Steps to reproduce the behavior:
1. Sniff App

#### System Information
Mitmproxy: 7.0.2 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.4.0-73-generic-x86_64-with-glibc2.31

#### Crash Logs

Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 279, in server_event
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/layer.py", line 255, in handle_event
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 740, in _handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 761, in event_to_child
  File "mitmproxy/proxy/layers/http/__init__.py", line 749, in event_to_child
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 617, in passthrough
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/tunnel.py", line 85, in _handle_event
  File "mitmproxy/proxy/layers/tls.py", line 320, in event_to_child
  File "mitmproxy/proxy/tunnel.py", line 104, in event_to_child
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/tunnel.py", line 72, in _handle_event
  File "mitmproxy/proxy/layers/tls.py", line 254, in receive_data
  File "mitmproxy/proxy/tunnel.py", line 104, in event_to_child
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 740, in _handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 761, in event_to_child
  File "mitmproxy/proxy/layers/http/__init__.py", line 749, in event_to_child
  File "mitmproxy/proxy/layer.py", line 144, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 136, in _handle_event
  File "mitmproxy/proxy/utils.py", line 23, in _check_event_type
AssertionError: Unexpected event type at HttpStream.state_done: Expected no events, got RequestData(stream_id=1, data=b'\x81\x81\xcf\xaa\xf0\xb3\xff').

**Comment by Prinzhorn** [comment]
>     1. Sniff App

Which app? It might not follow the HTTP spec correctly or do some other funny things. I fear we cannot help you without more detailed steps. Or it might not communicate via HTTP at all, try using mitmproxy in raw tcp mode. Look into the `tcp_hosts` option, e.g. `--tcp-hosts '.*'`
