### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Chellane** [mitmproxy/mitmproxy#4818]
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (http://127.0.0.1:8081/static/app.js:7:8533)
    at Object.enqueueSetState (http://127.0.0.1:8081/static/app.js:5:44513)
    at t.wc.setState (http://127.0.0.1:8081/static/app.js:1:3945)
    at t.onViewportUpdate (http://127.0.0.1:8081/static/app.js:58:46463)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:45760)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:43815)
    at Yi (http://127.0.0.1:8081/static/app.js:7:1828)
    at dk (http://127.0.0.1:8081/static/app.js:9:5215)
    at Mt.unstable_runWithPriority (http://127.0.0.1:8081/static/app.js:1:12961)
    at gg (http://127.0.0.1:8081/static/app.js:5:40220)

Component Stack:
    at AutoScrollWrapper (http://127.0.0.1:8081/static/app.js:58:43448)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:47416)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3036)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)

**Comment by mhils** [comment]
Which mitmproxy version are you using?
