### ISSUE TITLE
mitmproxy crashes if string option is edited

### ISSUE THREAD

**Issue by italankin** [mitmproxy/mitmproxy#4852]
#### Problem Description
Editing options via GUI causes fatal error:

```
TypeError: parse_setval() missing 1 required positional argument: 'currentvalue'
```

<details>
<summary>Full traceback</summary>

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/mitmproxy/master.py", line 54, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/window.py", line 316, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/window.py", line 50, in keypress
    ret = super().keypress(size, key)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/options.py", line 290, in keypress
    return self.focus_item.keypress(tsize, key)
  File "/usr/local/Cellar/mitmproxy/7.0.4/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/options.py", line 184, in keypress
    d = self.master.options.parse_setval(foc.opt, v)
TypeError: parse_setval() missing 1 required positional argument: 'currentvalue'
```
</details>

#### Steps to reproduce the behavior:
1. Start mitmproxy
2. Open options (`O`)
3. Select `view_filter` option (or any other string option)
4. Enter valid filter expression or just press `Enter` twice

#### System Information
```
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.6-x86_64-i386-64bit
```

**Comment by italankin** [comment]
Mitmproxy was installed via `brew`

**Comment by ilyaigpetrov** [comment]
Still reproducible on:
```
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.4.0-100-generic-x86_64-with-glibc2.31
```
