### ISSUE TITLE
HttpStream.state_wait_for_request_headers error

### ISSUE THREAD

**Issue by pocket-live** [mitmproxy/mitmproxy#4870]
#### Problem Description
```
mit_server          | 2021-10-19T07:17:01.079759751Z 37.103.81.174:57654: mitmproxy has crashed!
mit_server          | 2021-10-19T07:17:01.079788763Z Traceback (most recent call last):
mit_server          | 2021-10-19T07:17:01.079794934Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/server.py", line 279, in server_event
mit_server          | 2021-10-19T07:17:01.079799991Z     for command in layer_commands:
mit_server          | 2021-10-19T07:17:01.079804504Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
mit_server          | 2021-10-19T07:17:01.079809056Z     command = command_generator.send(send)
mit_server          | 2021-10-19T07:17:01.079813637Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 255, in handle_event
mit_server          | 2021-10-19T07:17:01.079818387Z     yield from self._handle(event)
mit_server          | 2021-10-19T07:17:01.079826095Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
mit_server          | 2021-10-19T07:17:01.079830842Z     command = command_generator.send(send)
mit_server          | 2021-10-19T07:17:01.079835186Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 740, in _handle_event
mit_server          | 2021-10-19T07:17:01.079839927Z     yield from self.event_to_child(handler, event)
mit_server          | 2021-10-19T07:17:01.079844281Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 761, in event_to_child
mit_server          | 2021-10-19T07:17:01.079849161Z     yield from self.event_to_child(stream, command.event)
mit_server          | 2021-10-19T07:17:01.079853589Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 749, in event_to_child
mit_server          | 2021-10-19T07:17:01.079858633Z     for command in child.handle_event(event):
mit_server          | 2021-10-19T07:17:01.079863297Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
mit_server          | 2021-10-19T07:17:01.079902048Z     command = command_generator.send(send)
mit_server          | 2021-10-19T07:17:01.079906606Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 136, in _handle_event
mit_server          | 2021-10-19T07:17:01.079910826Z     yield from self.client_state(event)
mit_server          | 2021-10-19T07:17:01.079914867Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/utils.py", line 23, in _check_event_type
mit_server          | 2021-10-19T07:17:01.079919260Z     raise AssertionError(
mit_server          | 2021-10-19T07:17:01.079925280Z AssertionError: Unexpected event type at HttpStream.state_wait_for_request_headers: Expected RequestHeaders, got RequestData(stream_id=1, data=b"\x16\x03\x03\x00\xbe\x01\x00\x00\xba\x03\x03anp\xedr'\xd2\xa1\xe5\xf0 9\xf7\r\xef\x9dd/\x8d\xf8r*&K\xf7(\xe8\xd6\xf6\x96\x16\xa3\x00\x00*\xc0,\xc0+\xc00\xc0/\x00\x9f\x00\x9e\xc0$\xc0#\xc0(\xc0'\xc0\n\xc0\t\xc0\x14\xc0\x13\x00\x9d\x00\x9c\x00=\x00<\x005\x00/\x00\n\x01\x00\x00g\x00\x00\x00&\x00$\x00\x00!authentication-prod.ar.indazn.com\x00\n\x00\x08\x00\x06\x00\x1d\x00\x17\x00\x18\x00\x0b\x00\x02\x01\x00\x00\r\x00\x1a\x00\x18\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x02\x01\x04\x03\x05\x03\x02\x03\x02\x02\x06\x01\x06\x03\x00#\x00\x00\x00\x17\x00\x00\xff\x01\x00\x01\x00").
mit_server          | 2021-10-19T07:17:01.079939109Z 
mit_server          | 2021-10-19T07:17:04.149705128Z 37.103.81.174:49416: mitmproxy has crashed!
mit_server          | 2021-10-19T07:17:04.149733496Z Traceback (most recent call last):
mit_server          | 2021-10-19T07:17:04.149738250Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/server.py", line 279, in server_event
mit_server          | 2021-10-19T07:17:04.149742511Z     for command in layer_commands:
mit_server          | 2021-10-19T07:17:04.149746107Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
mit_server          | 2021-10-19T07:17:04.149749966Z     command = command_generator.send(send)
mit_server          | 2021-10-19T07:17:04.149753507Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 255, in handle_event
mit_server          | 2021-10-19T07:17:04.149757131Z     yield from self._handle(event)
mit_server          | 2021-10-19T07:17:04.149760429Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
mit_server          | 2021-10-19T07:17:04.149763878Z     command = command_generator.send(send)
mit_server          | 2021-10-19T07:17:04.149767309Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 740, in _handle_event
mit_server          | 2021-10-19T07:17:04.149770905Z     yield from self.event_to_child(handler, event)
mit_server          | 2021-10-19T07:17:04.149774329Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 749, in event_to_child
mit_server          | 2021-10-19T07:17:04.149777989Z     for command in child.handle_event(event):
mit_server          | 2021-10-19T07:17:04.149781325Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 135, in handle_event
mit_server          | 2021-10-19T07:17:04.149784903Z     command_generator = self._handle_event(event)
mit_server          | 2021-10-19T07:17:04.149788233Z   File "/usr/local/lib/python3.9/site-packages/mitmproxy/proxy/utils.py", line 23, in _check_event_type
mit_server          | 2021-10-19T07:17:04.149805983Z     raise AssertionError(
mit_server          | 2021-10-19T07:17:04.149809318Z AssertionError: Unexpected event type at HttpStream._handle_event: Expected Start|HttpEvent, got ConnectionClosed(connection=Server({'id': '…a2bdcc', 'address': ('api-global.netflix.com', 443), 'state': <ConnectionState.CAN_WRITE: 2>, 'timestamp_start': 1634627762.836605, 'timestamp_tcp_setup': 1634627763.5006588, 'peername': ('34.214.223.171', 443), 'sockname': ('172.23.0.4', 57018)})).
```

#### Steps to reproduce the behavior:
1. After a period of use, the client shuts down the proxy and the server keeps printing error messages
2.The client is iphone

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.28

**Comment by mhils** [comment]
Thanks! That was very helpful. #4871 has a fix for the first error, you should be able to access updated dev snapshots from https://mitmproxy.org/downloads/#branches/main/ in ~20 minutes 😃 

I _think_ the second error is directly caused by the first and should also go away. If that's not the case, please open a new issue with a `--set proxy_debug` logfile. :)
