### ISSUE TITLE
RuntimeWarning: coroutine 'Proxyserver.handle_connection' was never awaited / OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by Artemis21** [mitmproxy/mitmproxy#4895]
#### Problem Description

Unexpected crash.

Error message:

```
Traceback (most recent call last):
  File "mitmproxy/master.py", line 54, in run_loop
  File "urwid/main_loop.py", line 287, in run
  File "urwid/main_loop.py", line 385, in _run
  File "urwid/main_loop.py", line 1494, in run
  File "urwid/compat.py", line 58, in reraise
  File "asyncio/selector_events.py", line 164, in _accept_connection
  File "socket.py", line 293, in accept
OSError: [Errno 24] Too many open files

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
mitmproxy/tools/console/master.py:218: RuntimeWarning: coroutine 'Proxyserver.handle_connection' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <coroutine object ConnectionHandler.open_connection at 0x7f9f776b5040>
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 153, in open_connection
  File "asyncio/streams.py", line 52, in open_connection
  File "asyncio/base_events.py", line 1081, in create_connection
  File "asyncio/base_events.py", line 1113, in _create_connection_transport
  File "asyncio/selector_events.py", line 700, in close
  File "asyncio/base_events.py", line 746, in call_soon
  File "asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

#### Steps to reproduce the behavior:

This has only happened once and I do not know what was different from usual.

#### System Information

```
Mitmproxy: 7.0.2 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.11.0-38-generic-x86_64-with-glibc2.33
```

**Comment by Artemis21** [comment]
Upgraded to `7.0.4` and got the same error again. Some more information:

 - Running normally, I get errors: "Certificate verify failed: unable to get local issuer certificate".
 - To work round this, I run `mitmproxy --ssl-insecure` as recommended on another issue.
 - Every request in the logs gets repeated more than ten times a second.
 - None of the requests have a response body, though they should.
 - The crash occurs.

**Comment by mhils** [comment]
How are you running mitmproxy? This looks like you are running in an infinite loop where mitmproxy connects to itself.

**Comment by Artemis21** [comment]
Indeed, my bad. Sorry.
