### ISSUE TITLE
mitmproxy has crashed!  in transparent mode

### ISSUE THREAD

**Issue by ingen2** [mitmproxy/mitmproxy#4896]
Mitmproxy has crashed! When I use transparent mode behind of upstream mode:

Commands: 
`tty1:  ./mitmproxy --mode transparent -p 8081`

`tty2: ./mitmproxy  --mode upstream:http://127.0.0.1:8081  -p 8082`

Error: 
Traceback (most recent call last):
  File "mitmproxy/master.py", line 54, in run_loop
  File "urwid/main_loop.py", line 287, in run
  File "urwid/main_loop.py", line 385, in _run
  File "urwid/main_loop.py", line 1494, in run
  File "urwid/compat.py", line 58, in reraise
  File "asyncio/selector_events.py", line 164, in _accept_connection
  File "socket.py", line 293, in accept
OSError: [Errno 24] Too many open files

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
Exception ignored in: <coroutine object ConnectionHandler.open_connection at 0x7fd881f8a5c0>
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 153, in open_connection
  File "asyncio/streams.py", line 52, in open_connection
  File "asyncio/base_events.py", line 1081, in create_connection
  File "asyncio/base_events.py", line 1113, in _create_connection_transport
  File "asyncio/selector_events.py", line 700, in close
  File "asyncio/base_events.py", line 746, in call_soon
  File "asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by Prinzhorn** [comment]
Sounds a lot like this https://github.com/mitmproxy/mitmproxy/issues/4895#issuecomment-962657061

Try starting the tty1 instance in regular mode if you want to chain two instances. You are connecting to 8081 as an upstream proxy _through_ 8081 as a transparent proxy (endless loop)
