### ISSUE TITLE
Crashing in transparent mode.

### ISSUE THREAD

**Issue by steven-agg** [mitmproxy/mitmproxy#4898]
#### Problem Description
I'm running in transparent mode on an ec2 machine and crashing. Any help would be greatly appreciated. Thank You! Steven.

#### Steps to reproduce the behavior:
1. New ec2 machine server 2019 (Same behavior in ubuntu 20.04 and redhat)
2. (admin elevated powershell window) mitmweb --mode transparent --set block_global=false
3. On my home firewall I have a nat rule to redirect my http traffic to port 8080 of the ec2 machine.
4. Navigate to http://mitm.it from my home pc

#### System Information
mitmproxy --version
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.17763-SP0

#### More Info
mitmweb --mode transparent --set block_global=false
Web server listening at http://127.0.0.1:8081/
Proxy server listening at http://*:8080
68.129.238.100:45194: client connect
68.129.238.100:45194: Transparent mode failure: AttributeError("'Resolver' object has no attribute 'wfile'")
68.129.238.100:7076: client connect
68.129.238.100:7076: Transparent mode failure: AttributeError("'Resolver' object has no attribute 'wfile'")
68.129.238.100:45194: mitmproxy has crashed!
Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 279, in server_event
  File "mitmproxy\proxy\layer.py", line 144, in handle_event
  File "mitmproxy\proxy\layer.py", line 257, in handle_event
  File "mitmproxy\proxy\layer.py", line 129, in handle_event
  File "mitmproxy\proxy\layer.py", line 220, in __continue
  File "mitmproxy\proxy\layer.py", line 183, in __process
  File "mitmproxy\proxy\layer.py", line 271, in _handle_event
  File "mitmproxy\proxy\layer.py", line 285, in _ask
  File "mitmproxy\proxy\layer.py", line 144, in handle_event
  File "mitmproxy\proxy\layers\http\__init__.py", line 740, in _handle_event
  File "mitmproxy\proxy\layers\http\__init__.py", line 761, in event_to_child
  File "mitmproxy\proxy\layers\http\__init__.py", line 749, in event_to_child
  File "mitmproxy\proxy\layer.py", line 144, in handle_event
  File "mitmproxy\proxy\layers\http\__init__.py", line 136, in _handle_event
  File "mitmproxy\proxy\layers\http\__init__.py", line 162, in state_wait_for_request_headers
AssertionError

On pfsense firewall create nat rule:
source ip: 192.168.50.4 (my workstation)
source port: *
target ip: *
target port: 80
translated ip: (my aws server ip)
translated port: 8080

Wireshark running port 8080 on aws machine shows properly formed http requests:

GET / HTTP/1.1
Host: mitm.it
Connection: keep-alive
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

**Comment by steven-agg** [comment]
I'm reading the manual now and it seems like my issue might be the way i'm doing nat?

`when the packet arrives at the mitmproxy machine, it must still be addressed to the target server. This means that Network Address Translation should not be applied before the traffic reaches mitmproxy, since this would remove the target information, leaving mitmproxy unable to determine the real destination.`

**Comment by mhils** [comment]
If you want it to look things up based on the Host header (assuming no other info is available), you can use regular mode in mitmproxy 7+. :)
