### ISSUE TITLE
Mitmproxy crashed with 'unknown certificate type'

### ISSUE THREAD

**Issue by bayandin** [mitmproxy/mitmproxy#490]
Sometimes mitmproxy is crashing with error:

```
Traceback (most recent call last):
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 982, in handle_messages
    while self.handle_flow():
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1055, in handle_flow
    ret = self.process_request(flow, req)
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1248, in process_request
    return self.process_connect_request(self.c.server_conn.address)
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1395, in process_connect_request
    self.c.establish_ssl(server=True, client=True)
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 215, in establish_ssl
    chain_file=chain_file
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/libmproxy/proxy/connection.py", line 66, in convert_to_ssl
    tcp.BaseHandler.convert_to_ssl(self, *args, **kwargs)
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/netlib/tcp.py", line 428, in convert_to_ssl
    ctx = self._create_ssl_context(cert, key, **sslctx_kwargs)
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/netlib/tcp.py", line 412, in _create_ssl_context
    ctx.use_certificate(cert.x509)
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/OpenSSL/SSL.py", line 406, in use_certificate
    _raise_current_error()
  File "/Users/bayandin/tools/mitmproxy/lib/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
Error: [('SSL routines', 'SSL_SET_CERT', 'unknown certificate type')]

Segmentation fault: 11
```

I use Python 2.7.9, OS X 10.10 and use mitm proxy for capturing traffic from Android 5.0.1

**Comment by mhils** [comment]
Hi there,

1. Which version of mitmproxy?
2. Are you using any custom certificates or something like that?
3. Which domain are you accessing?
4. Could you post the crash output of `mitmdump -vv`?

Cheers,
Max

**Comment by bayandin** [comment]
Hi Max,

1. mitmproxy 0.11.3, 
2. Nope, I use only default certificates that provided by mitmproxy,
3. and 4. This error is rarely reproduced, I repeating one scenario over and over again and it fails just one time. I'll try to catch this error again with extended logging.

Thanks.

**Comment by bayandin** [comment]
Hey Max,

Seems, I caught error with mitmdump -vv. Full log is realy big, so I save a part of it: https://gist.github.com/bayandin/d44a83e93989a4b499bd

It's ok?

**Comment by mhils** [comment]
Thanks. This might be a pyOpenSSL issue - how can I reproduce it?

**Comment by bayandin** [comment]
Hmm, this can be a little difficult. I turn on proxy for android and run tests for web site on it. And this error occurs sometimes. So I don't know a proper way to reproduce it :(

**Comment by mhils** [comment]
Hm. I tried to reproduce your issue over the last 20 minutes, but no luck. The traceback in the gist is different from the one in the initial post, but both don't make much sense to me. We're calling standard OpenSSL APIs here and they fail for no apparent reason.

**Comment by K0den** [comment]
I get that error when trying to access m.facebook.com from safari on IOS 8.2. mitmproxy 0.11.3 running on osx 10.10

**Comment by mhils** [comment]
Closed for now. Please let us know if you have a way for us to reproduce this on the latest version.
