### ISSUE TITLE
Incompatible with python-cryptography 35.0.0: Valid PEM but no BEGIN CERTIFICATE/END CERTIFICATE delimiters. Are you sure this is a certificate?

### ISSUE THREAD

**Issue by kpcyrd** [mitmproxy/mitmproxy#4917]
#### Problem Description

Starting mitmproxy with python-cryptography 35.0.0 installed causes a traceback to be logged into the event log.

#### Steps to reproduce the behavior:
1. Run `mitmproxy` without argumetns
2. `Error: Addon error: Traceback (most recent call last):(more in eventlog)` is visible in the bottom line
3. Press `shift+e` to get to the event log:

```
error: Addon error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mitmproxy/addons/tlsconfig.py", line 237, in running
    self.configure("confdir")  # pragma: no cover
  File "/usr/lib/python3.9/site-packages/mitmproxy/addons/tlsconfig.py", line 244, in configure
    self.certstore = certs.CertStore.from_store(
  File "/usr/lib/python3.9/site-packages/mitmproxy/certs.py", line 337, in from_store
    return cls.from_files(ca_file, dhparam_file, passphrase)
  File "/usr/lib/python3.9/site-packages/mitmproxy/certs.py", line 343, in from_files
    ca = Cert.from_pem(raw)
  File "/usr/lib/python3.9/site-packages/mitmproxy/certs.py", line 70, in from_pem
    cert = x509.load_pem_x509_certificate(data)  # type: ignore
  File "/usr/lib/python3.9/site-packages/cryptography/x509/base.py", line 436, in load_pem_x509_certificate
    return rust_x509.load_pem_x509_certificate(data)
ValueError: Valid PEM but no BEGIN CERTIFICATE/END CERTIFICATE delimiters. Are you sure this is a certificate?

info: Proxy server listening at http://*:8080
```

#### System Information

```
$ mitmproxy --version
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.14.18-hardened1-1-hardened-x86_64-with-glibc2.33
```

Installed from Arch Linux, https://bugs.archlinux.org/task/72408

**Comment by mhils** [comment]
This is a downstream packaging problem. We currently state that we are not compatible with 35.0.0:
https://github.com/mitmproxy/mitmproxy/blob/9a469806eb6a202f5b35c011368fd240a16f5397/setup.py#L75

I fixed the root cause in cryptography as well: https://github.com/pyca/cryptography/pull/6365
