### ISSUE TITLE
mitmproxy depends on `pkg_resources` at runtime but does not specify `install_requires=setuptools`

### ISSUE THREAD

**Issue by asottile** [mitmproxy/mitmproxy#4918]
#### Problem Description

https://github.com/mitmproxy/mitmproxy/blob/0ca458fd6475ee48728147f3b529467a75e912a4/mitmproxy/contrib/kaitaistruct/exif.py#L7

the `pkg_resources` module is provided by `setuptools`

installation into a minimal environment (for example, bazel) will break without also needing to specify `setuptools`

mitmproxy should depend on `setuptools`

#### Steps to reproduce the behavior:

1. simulate a minimal environment:

```
virtualenv venv
venv/bin/pip install mitmproxy
venv/bin/pip uninstall setuptools
venv/bin/pip install mitmproxy  # make sure we actually have its deps even after uninstalling
```

2. run `mitmproxy --help`

```console
$ venv/bin/mitmproxy --help
Traceback (most recent call last):
  File "venv/bin/mitmproxy", line 5, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/tools/main.py", line 8, in <module>
    from mitmproxy import exceptions, master
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/master.py", line 10, in <module>
    from mitmproxy import eventsequence
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/eventsequence.py", line 8, in <module>
    from mitmproxy.proxy import layers
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/proxy/layers/__init__.py", line 1, in <module>
    from . import modes
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/proxy/layers/modes.py", line 9, in <module>
    from mitmproxy.proxy.layers import tls
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/proxy/layers/tls.py", line 8, in <module>
    from mitmproxy.net import tls as net_tls
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/net/tls.py", line 18, in <module>
    from mitmproxy.contrib.kaitaistruct import tls_client_hello
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/contrib/kaitaistruct/tls_client_hello.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

#### System Information
Paste the output of "mitmproxy --version" here.

```console
$ venv/bin/mitmproxy --version
Traceback (most recent call last):
  File "venv/bin/mitmproxy", line 5, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/tools/main.py", line 8, in <module>
    from mitmproxy import exceptions, master
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/master.py", line 10, in <module>
    from mitmproxy import eventsequence
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/eventsequence.py", line 8, in <module>
    from mitmproxy.proxy import layers
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/proxy/layers/__init__.py", line 1, in <module>
    from . import modes
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/proxy/layers/modes.py", line 9, in <module>
    from mitmproxy.proxy.layers import tls
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/proxy/layers/tls.py", line 8, in <module>
    from mitmproxy.net import tls as net_tls
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/net/tls.py", line 18, in <module>
    from mitmproxy.contrib.kaitaistruct import tls_client_hello
  File "/tmp/y/venv/lib/python3.8/site-packages/mitmproxy/contrib/kaitaistruct/tls_client_hello.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by mhils** [comment]
Thanks! This file is auto-generated by [Kaitai Struct](https://kaitai.io/). Shouldn't Kaitai specify setuptools as a dependency here?

**Comment by mhils** [comment]
(I don't mind adding the dependency to mitmproxy, but it feels like solving this upstream should solve it for more projects)

**Comment by asottile** [comment]
I think technically since the source file is inside mitmproxy it should be specified here -- though kataistruct probably also uses pkg_resources as well

ideally it should use `importlib.metadata` and then it wouldn't need a dependency at all (since mitmproxy is python3.8+)

**Comment by mhils** [comment]
> I think technically since the source file is inside mitmproxy it should be specified here -- though kataistruct probably also uses pkg_resources as well

Yeah, we are in murky waters here. The Kaitai compiler auto-generates this file, so everyone who uses `kaitaistruct` will also depend on `pkg_resources`. This is not mentioned on http://doc.kaitai.io/lang_python.html, which does mention `enum34`. 

My understanding is that in an ideal world, 1) Kaitai's compiler would generate code that uses `importlib.metadata`, 2) Kaitai's runtime would specify a conditional dependency on `importlib-metadata` for Python <= 3.7. Would you agree with that assessment?

Whatsoever, happy to merge your PR so that we this fixed on our end. Ieally we could add a reference to a Kaitai issue right away so that we can eventually remove it.

**Comment by asottile** [comment]
yep! that sounds spot on
