### ISSUE TITLE
Too many open files crash after ~36 hours of frequent response handling

### ISSUE THREAD

**Issue by AurumTheEnd** [mitmproxy/mitmproxy#4933]
#### Problem Description
After running mitmproxy for approximately 36 hours, it crashed with the following error:
```
Traceback (most recent call last):
  File "mitmproxy/master.py", line 54, in run_loop
  File "urwid/main_loop.py", line 287, in run
  File "urwid/main_loop.py", line 385, in _run
  File "urwid/main_loop.py", line 1494, in run
  File "urwid/compat.py", line 58, in reraise
  File "asyncio/selector_events.py", line 164, in _accept_connection
  File "socket.py", line 293, in accept
OSError: [Errno 24] Too many open files

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
```

Using my own addon script to pass the response contents through a socket to a Rust server running locally:
```py
from mitmproxy import ctx
from mitmproxy import http
import socket
import datetime


class VehiclesListener:
    def __init__(self):
        pass

    def response(self, flow: http.HTTPFlow):
        if "vehicles.json" in flow.request.path and flow.response and flow.response.content:
            ctx.log.info(f"got vehicles at { datetime.datetime.now().isoformat() }")

            s = socket.socket()
            connected = s.connect_ex(('127.0.0.1', 9999))

            if connected == 0:
                ctx.log.info("socket connected, sending")
                s.send(flow.response.content)
            else:
                ctx.log.info("socket failed to connect!")

            s.close()


addons = [
    VehiclesListener()
]

```

Since the trace mentions a socket, I would assume the crash has something to do with my addon, though I have no proof.

#### Steps to reproduce the behavior:
1. Run mitmproxy as `mitmproxy --proxyauth any -s ./saver.py --verbose -p 8052`
2. Have the addon script react to a response every 5 seconds for approximately 36 hours (it listens to an API request that is automatically sent by a website)
3. ???
4. Get crash.

#### System Information
```
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.14.14-200.fc34.x86_64-x86_64-with-glibc2.33
```

**Comment by AurumTheEnd** [comment]
Output of `ulimit`:
```sh
$ ulimit -aH
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 62554
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 524288
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 62554
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Comment by mhils** [comment]
Thanks for filing this! Seems like _someone_ is not properly cleaning up sockets _somewhere_. Let's assume this is something that builds up continuously. Could you experiment with sending `SIGUSR1` to your mitmproxy instance after it has been running for a few requests and see if you can identify anything that sticks out / increases with runtime? Feel free to ask stupid questions if anything is unclear.

**Comment by AurumTheEnd** [comment]
> Could you experiment with sending `SIGUSR1` to your mitmproxy instance after it has been running for a few requests and see if you can identify anything that sticks out / increases with runtime?

Running `kill -SIGUSR1 <PID>` leaves no output in either of the terminals, and simply kills the mitmproxy instance. Do I need to have something else set up? Never done this before.

**Comment by mhils** [comment]
Not really. Does it work if you use mitmdump? Here's an example from my local machine:

https://user-images.githubusercontent.com/1019198/142848741-ae2667d8-b841-4f1b-bb8c-35d45cf27bd3.mp4

**Comment by AurumTheEnd** [comment]
Probably worth noting that I am running the binaries from https://mitmproxy.org/, which probably do not have the debugging/signal handling code within, would that be correct? Will try from sources.

**Comment by AurumTheEnd** [comment]
Sending the signal works with `mitmdump`. Here is a first dump:
```
****************************************************
Summary
=======
(psutil not installed, skipping some debug info)

Threads
=======
MainThread
asyncio_0
asyncio_1

Memory
=======
19 <class 'mitmproxy.proxy.server.TimeoutWatchdog'>
19 <class 'mitmproxy.connection.Client'>
19 <class 'mitmproxy.proxy.layers.modes.HttpProxy'>
22 <class 'mitmproxy.connection.Server'>
27 <class 'mitmproxy.proxy.layers.http._http1.Http1Server'>
35 <class 'mitmproxy.proxy.layers.http.HttpLayer'>
37 <class 'mitmproxy.proxy.server.ConnectionIO'>
44 <class 'mitmproxy.command.Command'>
46 <class 'mitmproxy.certs.Cert'>
60 <class 'mitmproxy.proxy.layers.http.HttpStream'>
60 <class 'mitmproxy.http.HTTPFlow'>
60 <class 'mitmproxy.http.Request'>
60 <class 'mitmproxy.http.RequestData'>
60 <class 'mitmproxy.http.Response'>
60 <class 'mitmproxy.http.ResponseData'>
70 <class 'mitmproxy.proxy.layer.NextLayer'>
73 <class 'mitmproxy.optmanager._Option'>
120 <class 'mitmproxy.http.Headers'>
133 <class 'mitmproxy.proxy.context.Context'>
1260 <class 'mitmproxy.websocket.WebSocketMessage'>

Tasks
=======
127.0.0.1:42500: timeout watchdog (age: 106s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42504: server connection handler for push.services.mozilla.com:443 (44.241.251.147:443) (age: 105s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42514: Proxyserver.handle_connection (age: 101s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42494: server connection handler for gateway.messenger.com:443 (157.240.30.13:443) (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42512: timeout watchdog (age: 101s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42514: client connection handler (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42500: server connection manager ('gateway.discord.gg', 443) (age: 106s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42490: timeout watchdog (age: 108s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42490: server connection manager ('gateway.messenger.com', 443) (age: 108s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42498: Proxyserver.handle_connection (age: 107s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42510: server connection manager ('detectportal.firefox.com', 80) (age: 101s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42514: server connection manager ('detectportal.firefox.com', 80) (age: 101s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42492: Proxyserver.handle_connection (age: 108s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42496: Proxyserver.handle_connection (age: 108s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42500: server connection handler for gateway.discord.gg:443 (162.159.135.234:443) (age: 106s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42496: timeout watchdog (age: 108s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42502: timeout watchdog (age: 106s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42514: server connection handler for detectportal.firefox.com:80 ([2600:1901:0:38d7::]:80) (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42492: timeout watchdog (age: 108s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42496: client connection handler (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42502: Proxyserver.handle_connection (age: 106s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42508: timeout watchdog (age: 102s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42522: Proxyserver.handle_connection (age: 25s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42508: Proxyserver.handle_connection (age: 102s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42492: client connection handler (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42496: server connection manager ('gateway.messenger.com', 443) (age: 108s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42502: client connection handler (age: 106s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42508: client connection handler (age: 102s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42510: server connection handler for detectportal.firefox.com:80 ([2600:1901:0:38d7::]:80) (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42522: timeout watchdog (age: 25s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42502: server connection manager ('gateway.discord.gg', 443) (age: 106s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42508: server connection manager ('alive.github.com', 443) (age: 102s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42496: server connection handler for gateway.messenger.com:443 (157.240.30.13:443) (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42490: server connection handler for gateway.messenger.com:443 (157.240.30.13:443) (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42494: timeout watchdog (age: 108s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42502: server connection handler for gateway.discord.gg:443 (162.159.136.234:443) (age: 106s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42508: server connection handler for alive.github.com:443 (140.82.114.25:443) (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42512: server connection handler for detectportal.firefox.com:80 ([2600:1901:0:38d7::]:80) (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42522: client connection handler (age: 25s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42514: timeout watchdog (age: 101s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42516: Proxyserver.handle_connection (age: 100s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42516: timeout watchdog (age: 100s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42504: Proxyserver.handle_connection (age: 106s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42498: timeout watchdog (age: 107s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42510: Proxyserver.handle_connection (age: 101s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42498: client connection handler (age: 107s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42510: timeout watchdog (age: 101s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42516: client connection handler (age: 100s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42494: Proxyserver.handle_connection (age: 108s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42498: server connection manager ('mapa.idsjmk.cz', 443) (age: 107s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42504: timeout watchdog (age: 106s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42510: client connection handler (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42494: client connection handler (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42498: server connection handler for mapa.idsjmk.cz:443 (195.181.210.250:443) (age: 107s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42504: client connection handler (age: 106s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42512: server connection manager ('detectportal.firefox.com', 80) (age: 101s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42494: server connection manager ('gateway.messenger.com', 443) (age: 108s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42500: Proxyserver.handle_connection (age: 106s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42504: server connection manager ('push.services.mozilla.com', 443) (age: 106s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42512: client connection handler (age: 101s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42500: client connection handler (age: 106s)
    data = await reader.read(65535)  # at server.py:218
Task-1
    await asyncio.sleep(ReloadInterval)  # at script.py:131
127.0.0.1:42512: Proxyserver.handle_connection (age: 101s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42518: client connection handler (age: 100s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42490: Proxyserver.handle_connection (age: 108s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42518: Proxyserver.handle_connection (age: 100s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42524: timeout watchdog (age: 25s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
client playback (age: 110s)
    self.inflight = await self.queue.get()  # at clientplayback.py:136
127.0.0.1:42518: timeout watchdog (age: 100s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42490: client connection handler (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42524: server connection manager ('avatars.githubusercontent.com', 443) (age: 25s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42518: server connection manager ('edge-chat.messenger.com', 443) (age: 100s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42520: server connection manager ('contile.services.mozilla.com', 443) (age: 48s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42524: server connection handler for avatars.githubusercontent.com:443 ([2606:50c0:8003::154]:443) (age: 25s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42520: Proxyserver.handle_connection (age: 48s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42526: Proxyserver.handle_connection (age: 24s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42526: timeout watchdog (age: 24s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42518: server connection handler for edge-chat.messenger.com:443 ([2a03:2880:f03d:12:face:b00c:0:2]:443) (age: 100s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42526: client connection handler (age: 24s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42520: timeout watchdog (age: 48s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42526: server connection manager ('collector.githubapp.com', 443) (age: 24s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42520: client connection handler (age: 48s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42528: Proxyserver.handle_connection (age: 24s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42528: timeout watchdog (age: 24s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42528: client connection handler (age: 24s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42520: server connection handler for contile.services.mozilla.com:443 (34.117.237.239:443) (age: 48s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42528: server connection manager ('api.github.com', 443) (age: 24s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42522: server connection manager ('github.com', 443) (age: 25s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42528: server connection handler for api.github.com:443 (140.82.121.5:443) (age: 24s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42522: server connection handler for github.com:443 (140.82.121.4:443) (age: 25s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42524: client connection handler (age: 25s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42524: Proxyserver.handle_connection (age: 25s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42526: server connection handler for collector.githubapp.com:443 (3.233.111.32:443) (age: 24s)
    data = await reader.read(65535)  # at server.py:218
```

**Comment by mhils** [comment]
Thanks. This looks normal to me so far. You have 19 active client connections (`client connection handler` tasks), but all of them are guarded with a `timeout watchdog` task, which should kill them after ten minutes of complete inactivity. Seeing either with an age >600 would be a cause for concern. 

If you install from sources or PyPI (https://docs.mitmproxy.org/stable/overview-installation/#installation-from-the-python-package-index-pypi) and also install `psutil` into the same virtualenv you should also see all active sockets in the dump. If you dislike the kill, you can uncomment it here: https://github.com/mitmproxy/mitmproxy/blob/57ae779b154e36f43461f40eea473643f7090b76/mitmproxy/utils/debug.py#L103

**Comment by AurumTheEnd** [comment]
This is after running for about 20 mins: I see some ages of 600s+.
```
****************************************************
Summary
=======
(psutil not installed, skipping some debug info)

Threads
=======
MainThread
asyncio_0
asyncio_1
asyncio_2

Memory
=======
14 <class 'mitmproxy.proxy.layers.modes.HttpProxy'>
15 <class 'mitmproxy.proxy.layers.http.HttpClient'>
19 <class 'mitmproxy.connection.Server'>
21 <class 'mitmproxy.proxy.layers.http._http1.Http1Server'>
23 <class 'mitmproxy.certs.CertStoreEntry'>
25 <class 'mitmproxy.proxy.layers.http.HttpLayer'>
26 <class 'mitmproxy.proxy.server.ConnectionIO'>
44 <class 'mitmproxy.command.Command'>
50 <class 'mitmproxy.certs.Cert'>
50 <class 'mitmproxy.proxy.layer.NextLayer'>
73 <class 'mitmproxy.optmanager._Option'>
317 <class 'mitmproxy.http.Response'>
317 <class 'mitmproxy.http.ResponseData'>
322 <class 'mitmproxy.proxy.layers.http.HttpStream'>
322 <class 'mitmproxy.http.HTTPFlow'>
322 <class 'mitmproxy.http.Request'>
322 <class 'mitmproxy.http.RequestData'>
377 <class 'mitmproxy.proxy.context.Context'>
639 <class 'mitmproxy.http.Headers'>
2418 <class 'mitmproxy.websocket.WebSocketMessage'>

Tasks
=======
127.0.0.1:42904: client connection handler (age: 295s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42822: Proxyserver.handle_connection (age: 1055s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42900: server connection handler for detectportal.firefox.com:80 (34.107.221.82:80) (age: 304s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42904: timeout watchdog (age: 295s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42900: server connection manager ('detectportal.firefox.com', 80) (age: 305s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42896: Proxyserver.handle_connection (age: 305s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42846: client connection handler (age: 942s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42862: client connection handler (age: 552s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42826: server connection manager ('push.services.mozilla.com', 443) (age: 1052s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42822: timeout watchdog (age: 1055s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
client playback (age: 1059s)
    self.inflight = await self.queue.get()  # at clientplayback.py:136
127.0.0.1:42898: Proxyserver.handle_connection (age: 305s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42862: timeout watchdog (age: 552s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42922: server connection handler for gateway.messenger.com:443 ([2a03:2880:f03d:d:face:b00c:0:2825]:443) (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42904: server connection handler for gateway.messenger.com:443 (157.240.30.13:443) (age: 295s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42930: server connection handler for github.com:443 (140.82.121.3:443) (age: 70s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42826: server connection handler for push.services.mozilla.com:443 (34.215.36.246:443) (age: 1052s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42900: client connection handler (age: 305s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42898: timeout watchdog (age: 305s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42846: server connection manager ('edge-chat.messenger.com', 443) (age: 942s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42928: server connection manager ('gateway.messenger.com', 443) (age: 71s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42818: Proxyserver.handle_connection (age: 1055s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42832: timeout watchdog (age: 1004s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42924: Proxyserver.handle_connection (age: 108s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42904: server connection manager ('gateway.messenger.com', 443) (age: 295s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42822: server connection manager ('alive.github.com', 443) (age: 1055s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42928: Proxyserver.handle_connection (age: 71s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42900: Proxyserver.handle_connection (age: 305s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42826: client connection handler (age: 1052s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42930: server connection manager ('github.com', 443) (age: 70s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42818: timeout watchdog (age: 1055s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42832: Proxyserver.handle_connection (age: 1004s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42896: server connection manager ('detectportal.firefox.com', 80) (age: 305s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42924: timeout watchdog (age: 108s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42818: client connection handler (age: 1055s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42898: server connection manager ('detectportal.firefox.com', 80) (age: 305s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42896: timeout watchdog (age: 305s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42922: client connection handler (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42818: server connection manager ('mapa.idsjmk.cz', 443) (age: 1055s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42832: client connection handler (age: 1004s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42930: timeout watchdog (age: 70s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42862: Proxyserver.handle_connection (age: 552s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42896: client connection handler (age: 305s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42928: timeout watchdog (age: 71s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42832: server connection manager ('gateway.discord.gg', 443) (age: 1004s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42930: Proxyserver.handle_connection (age: 70s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42846: server connection handler for edge-chat.messenger.com:443 (157.240.30.18:443) (age: 942s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42922: server connection manager ('gateway.messenger.com', 443) (age: 108s)
    await asyncio.wait([new_handler])  # at server.py:200
127.0.0.1:42822: server connection handler for alive.github.com:443 (140.82.112.26:443) (age: 1055s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42924: client connection handler (age: 108s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42900: timeout watchdog (age: 305s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42826: Proxyserver.handle_connection (age: 1052s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42928: client connection handler (age: 71s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42818: server connection handler for mapa.idsjmk.cz:443 (195.181.210.250:443) (age: 1055s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42922: Proxyserver.handle_connection (age: 108s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42904: Proxyserver.handle_connection (age: 295s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42826: timeout watchdog (age: 1052s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42846: Proxyserver.handle_connection (age: 942s)
    await handler.handle_client()  # at proxyserver.py:183
127.0.0.1:42928: server connection handler for gateway.messenger.com:443 (157.240.30.13:443) (age: 71s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42898: client connection handler (age: 305s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42846: timeout watchdog (age: 942s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
127.0.0.1:42898: server connection handler for detectportal.firefox.com:80 (34.107.221.82:80) (age: 304s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42930: client connection handler (age: 70s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42922: timeout watchdog (age: 108s)
    await asyncio.sleep(self.CONNECTION_TIMEOUT - (time.time() - self.last_activity))  # at server.py:48
Task-1
    await asyncio.sleep(ReloadInterval)  # at script.py:131
127.0.0.1:42822: client connection handler (age: 1055s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42832: server connection handler for gateway.discord.gg:443 (162.159.135.234:443) (age: 1004s)
    data = await reader.read(65535)  # at server.py:218
127.0.0.1:42896: server connection handler for detectportal.firefox.com:80 (34.107.221.82:80) (age: 304s)
    data = await reader.read(65535)  # at server.py:218
****************************************************
```

**Comment by mhils** [comment]
To clarify: it is fine to have connections with > 600s, think for example of a long-running WebSocket connection. Connections are only killed if there is no activity from either client nor server for ten minutes.

**Comment by AurumTheEnd** [comment]
@mhils Out of sheer curiosity, which commit fixes this?

I couldn't find any referencing this issue number. Hopefully I'm not 👨‍🦯

**Comment by mhils** [comment]
I think the actual fix here is the timeout watchdog introduced by https://mitmproxy.org/posts/new-proxy-core/. The last output in https://github.com/mitmproxy/mitmproxy/issues/4933#issuecomment-975426740 looked reasonable, and I haven't heard anyone else reporting similar issues in the last year.

**Comment by AurumTheEnd** [comment]
I see. Thanks for the response, the post is a nice summary.
