### ISSUE TITLE
String options are read from the config file incorrectly

### ISSUE THREAD

**Issue by marwinxxii** [mitmproxy/mitmproxy#5010]
#### Problem Description
In version `7.0.4` options with type `str` and `Optional[str]` are read incorrectly from the config file, only last character is used.

#### Steps to reproduce the behavior:
1. Create add-on `test_option_addon.py`:
```python
from typing import Optional
from mitmproxy import ctx

class OptionTestAddon:
    def load(self, loader) -> None:
        loader.add_option(
            name="test_option",
            typespec=Optional[str],
            default=None,
            help="Will it fail?"
        )

    def configure(self, updates) -> None:
        print("test_option value: " + ctx.options.test_option)

addons = [OptionTestAddon()]
```
2. in `~/.mitmproxy/config.yaml` define:
```yaml
test_option: abcdef
```
3. Run `mitmdump -s test_option_addon.py` and it prints:
```
test_option value: f
Loading script ../../../zmisc/option_test_addon.py
Proxy server listening at http://*:8080
```

while `abcdef` is expected.

I've tried wrapping value in the quotes, but the result is the same.

#### System Information
```
Mitmproxy: 7.0.4
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-10.16-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Thanks for the clear and concise report, clearly looks like a bug. Does specifying them as command line args with `--set` work?

**Comment by marwinxxii** [comment]
@mhils yes, as command line argument it works fine:

`mitmdump -s ../../../zmisc/option_test_addon.py --set test_option=abcdef` (when option in the config file is commented out).

produces:
```
test_option value: abcdef
Loading script ../../../zmisc/option_test_addon.py
Proxy server listening at http://*:8080
```

**Comment by marwinxxii** [comment]
I've tried following test on both `main` and `v7.0.4` and it passes successfully, probably I'm missing something:

`test_optmanager.py`:
```python
def test_read_config(tmp_path):
    config_path = tmp_path / "config.yaml"
    config_yaml_text = """
    three: value_three
    """
    with open(config_path, "w") as f:
        f.write(config_yaml_text)
    manager = TD2()
    optmanager.load_paths(manager, config_path)
    assert manager.three == "value_three"
```

**Comment by mhils** [comment]
```
λ cat ~/.mitmproxy/config.yaml
intercept: foo
```

works correctly for me. This might be an issue with initially-unknown options (`OptManager.process_deferred`).

**Comment by marwinxxii** [comment]
I've tried with other types of addon options:
- `Sequence[str]` works fine
- `bool` gives me other weird/unrelated? issue:
```
error: Addon error: Traceback (most recent call last):
  File "…/zvenv/lib/python3.9/site-packages/mitmproxy/addonmanager.py", line 43, in safecall
    yield
  File "…/zvenv/lib/python3.9/site-packages/mitmproxy/addons/script.py", line 103, in loadscript
    ctx.master.addons.register(ns)
  File "…/zvenv/lib/python3.9/site-packages/mitmproxy/addonmanager.py", line 190, in register
    self.master.options.process_deferred()
  File "…/zvenv/lib/python3.9/site-packages/mitmproxy/optmanager.py", line 324, in process_deferred
    for optval in optvals:
TypeError: 'bool' object is not iterable
```

**Comment by marwinxxii** [comment]
Here is a test to reproduce the issue:

```patch
diff --git a/test/mitmproxy/test_optmanager.py b/test/mitmproxy/test_optmanager.py
index d0f05678f..60e753c0f 100644
--- a/test/mitmproxy/test_optmanager.py
+++ b/test/mitmproxy/test_optmanager.py
@@ -7,6 +7,8 @@ import argparse
 from mitmproxy import options
 from mitmproxy import optmanager
 from mitmproxy import exceptions
+from mitmproxy import addonmanager
+from mitmproxy.master import Master
 
 
 class TO(optmanager.OptManager):
@@ -459,3 +461,27 @@ def test_set():
     opts.process_deferred()
     assert "deferredsequenceoption" not in opts.deferred
     assert opts.deferredsequenceoption == ["a", "b"]
+
+
+def test_read_config(tmp_path):
+    class OptionTestAddon:
+        def load(self, loader) -> None:
+            loader.add_option(
+                name="test_option",
+                typespec=typing.Optional[str],
+                default=None,
+                help="Will it fail?"
+            )
+
+    config_path = tmp_path / "config.yaml"
+    config_yaml_text = """
+    test_option: abcdef
+    """
+    with open(config_path, "w") as f:
+        f.write(config_yaml_text)
+    options = TD2()
+    am = addonmanager.AddonManager(Master(options))
+    optmanager.load_paths(options, config_path)
+    am.register(OptionTestAddon())
+    options.process_deferred()
+    assert options.test_option == "abcdef"
```

produces:
```
>       assert options.test_option == "abcdef"
E       AssertionError: assert 'f' == 'abcdef'
E         - abcdef
E         + f
```


@mhils would it be possible to implement somehow integration tests?
For example currently `mitmproxy --options` dumps only default values, but maybe we could have a function to collect and initialise all of them (including from addons) to assert over them?

**Comment by marwinxxii** [comment]
I would be happy to implement some kind of a contract/integration test, if you have any hints where to start, would be great.

**Comment by mhils** [comment]
Fixed in v8, thanks again for bearing with me! 😃 🍰
