### ISSUE TITLE
OSError: [WinError 10038]

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#5016]
Using this:

https://snapshots.mitmproxy.org/branches/main/mitmproxy-main-windows.zip

From December 25, if I capture some requests with `mitmproxy.exe`, then start scrolling down, the program crashes:

~~~
Traceback (most recent call last):k 182ms
  File "mitmproxy\master.py", line 54, in run_loopey=4VCYIJUCDLOUELGD1V8WBVYBN…
  File "urwid\main_loop.py", line 287, in run
  File "urwid\main_loop.py", line 385, in _runi_key=4VCYIJUCDLOUELGD1V8WBVYBNV…
  File "urwid\main_loop.py", line 1494, in run
  File "urwid\compat.py", line 58, in reraisearing
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost4a17a9-…
OSError: [WinError 10038] An operation was attempted on something that is not a socket
   GET https://23.198.7.167/1.0/gateway.php?api_key=4VCYIJUCDLOUELGD1V8WBVYBNV…
       ← 200 application/json 25b 184ms
mitmproxy has crashed!.7.167/1.0/gateway.php?api_key=4VCYIJUCDLOUELGD1V8WBVYBN…
Please lodge a bug report at:n 148b 162ms
   POST https://github.com/mitmproxy/mitmproxy/issues4VCYIJUCDLOUELGD1V8WBVYBN…
Exception in thread Tornado selector:51ms
Traceback (most recent call last):nt
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in runcontent_cards/sync
  File "tornado\platform\asyncio.py", line 573, in _run_select
  File "asyncio\base_events.py", line 791, in call_soon_threadsafeLGD1V8WBVYBN…
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closedteway.php?api_key=4VCYIJUCDLOUELGD1V8WBVYBNV…
~~~

**Comment by mhils** [comment]
Thanks! The best workaround is to either us mitmdump or mitmweb, or to use mitmproxy from WSL.

**Comment by 89z** [comment]
Just to note, this is only on `main`, the latest release version works as expected. However I am concerned that whatever commit caused this might remain on the next released version.

**Comment by bratao** [comment]
+1 , browsing with main using Firefox on Windows 10 I get the same error( browsing to www.speedtest.net)

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/issues/5141

**Comment by mhils** [comment]
I've fixed the underlying bug in CPython (https://bugs.python.org/issue43253), and made sure that it doesn't crash mitmproxy anymore in #5181.

**Comment by 89z** [comment]
whoa, you are badass! Thank you!
