### ISSUE TITLE
OSError: [Errno 10048]

### ISSUE THREAD

**Issue by neeraj0793-05** [mitmproxy/mitmproxy#5041]
#### Problem Description
When i am trying to open mitmproxy it is showing this error

OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8080): only one usage of each socket address (protocol/network address/port) is normally permitted

#### here is log
Traceback (most recent call last):
  File "mitmproxy\master.py", line 54, in run_loop
  File "urwid\main_loop.py", line 287, in run
  File "urwid\main_loop.py", line 385, in _run
  File "urwid\main_loop.py", line 1494, in run
  File "urwid\compat.py", line 58, in reraise
  File "mitmproxy\addons\proxyserver.py", line 154, in refresh_server
  File "asyncio\streams.py", line 94, in start_server
  File "asyncio\base_events.py", line 1494, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8080): only one usage of each socket address (protocol/network address/port) is normally permitted

mitmproxy has crashed!

#### System Information
Mitmproxy: 7.0.4 binary

**Comment by Prinzhorn** [comment]
There's probably already something listening on port 8080 on that machine (a different service or a different instance of mitmproxy), try a different port via `--listen-port` parameter. This doesn't look like a bug in mitmproxy, so I'm closing this.
