### ISSUE TITLE
mitmproxy v7.0.4 crash in HTTPS reverse proxy mode (not showing w/ v6.0.2)

### ISSUE THREAD

**Issue by vrubiolo** [mitmproxy/mitmproxy#5115]
#### Problem Description
First, a big thanks for the excellent tool that `mitmproxy` is. Its quality and excellent documentation make for a very good experience when using it!

I am trying to inspect the traffic to/from the Vagrant cloud (https://www.vagrantup.com/) when a virtual machine archive is downloaded and set up `mitmproxy` over HTTPS in reverse proxy mode.

I am seeing an immediate crash when attempting a VM download/bringup:
```
$ sudo /home/vrubiolo/bin/mitmproxy -v -m reverse:https://vagrantcloud.com:443  -p 443
Traceback (most recent call last):
  File "mitmproxy/master.py", line 54, in run_loop
  File "urwid/main_loop.py", line 287, in run
  File "urwid/main_loop.py", line 385, in _run
  File "urwid/main_loop.py", line 1494, in run
  File "urwid/compat.py", line 58, in reraise
  File "asyncio/selector_events.py", line 164, in _accept_connection
  File "socket.py", line 293, in accept
OSError: [Errno 24] Too many open files

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
Exception ignored in: <coroutine object ConnectionHandler.open_connection at 0x7f66a49bf8c0>
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 153, in open_connection
  File "asyncio/streams.py", line 52, in open_connection
  File "asyncio/base_events.py", line 1081, in create_connection
  File "asyncio/base_events.py", line 1113, in _create_connection_transport
  File "asyncio/selector_events.py", line 700, in close
  File "asyncio/base_events.py", line 746, in call_soon
  File "asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

I have tried to isolate the issue and can reproduce it without Vagrant and a simple `curl` instead.

#### Steps to reproduce the behavior:
0. Retrieve `mitmproxy 7.0.4` from the main website (Linux binary)
1. Edit `/etc/hosts` and add the following mapping in there: `127.0.0.1 vagrantcloud.com`
2. Start `mitmproxy` in reverse proxy mode: `sudo /home/vrubiolo/bin/mitmproxy -v -m reverse:https://vagrantcloud.com:443  -p 443`
3. Initiate a download via the following command (taken from the Vagrant debug log):
`curl -q -I --fail --location --max-redirs 10 --verbose --user-agent "Vagrant/2.2.19 (+https://www.vagrantup.com; ruby2.7.4)" --continue-at - -H Accept: application/json https://vagrantcloud.com/generic/alpine310`

#### System Information
```
$ ~/bin/mitmproxy --version
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.15.18-200.fc35.x86_64-x86_64-with-glibc2.34
```

This is Fedora 35.

#### Workaround
Use `mitmproxy` v6.0.2 instead of `7.0.4`:
```
~/Downloads/mitmproxy-6 --version
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.15.18-200.fc35.x86_64-x86_64-with-glibc2.34
```

**Comment by vrubiolo** [comment]
Thanks @mhils for the hint (I am still a beginner w/ `mitmproxy`). I will try your suggestion and report back.
Yes, it did work w/ v6x, I could go further and it did not crash (I encountered certificate errors but this was expected)
