### ISSUE TITLE
mitmproxy 8.0.0 crashes with plugin

### ISSUE THREAD

**Issue by hazcod** [mitmproxy/mitmproxy#5202]
#### Problem Description

I install mitmproxy 8.0.0 with my own plugin enabled, but this crashes with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/addons/errorcheck.py", line 20, in _shutdown_if_errored
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 149, in mitmdump
    run(dump.DumpMaster, cmdline.mitmdump, args, extra)
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 122, in run
    return asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 644, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

**Comment by mhils** [comment]
This sounds like your own plugin prints an error log entry during start?
