### ISSUE TITLE
`mitmproxy has crashed` Please lodge a bug report

### ISSUE THREAD

**Issue by RafaelEstevamReis** [mitmproxy/mitmproxy#5267]
#### Problem Description
Mitm crashed and asked to sent this report
I just click in a flow and it crashed
This is the first time I use mitmp so I don't understant a lot of it yet

#### Steps to reproduce the behavior:
1. I could not reproduce after it happened, I clicked other flows and nothing happened

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 8.0.0 binary
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.19043-SP0
```
I was using the mitmweb at the moment (if helps)

Crash data:
```
SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at http://127.0.0.1:8081/static/app.js:58:37975
    at Object.ci [as useMemo] (http://127.0.0.1:8081/static/app.js:5:60363)
    at Ct.useMemo (http://127.0.0.1:8081/static/app.js:1:8594)
    at Messages (http://127.0.0.1:8081/static/app.js:58:37962)
    at Ch (http://127.0.0.1:8081/static/app.js:5:55397)
    at li (http://127.0.0.1:8081/static/app.js:5:65240)
    at ck (http://127.0.0.1:8081/static/app.js:9:9936)
    at bk (http://127.0.0.1:8081/static/app.js:9:1017)
    at ak (http://127.0.0.1:8081/static/app.js:9:923)

Component Stack:
    at Messages (http://127.0.0.1:8081/static/app.js:58:37722)
    at section
    at TcpMessages (http://127.0.0.1:8081/static/app.js:58:39323)
    at div
    at FlowView (http://127.0.0.1:8081/static/app.js:58:39868)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:47480)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3048)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)
```

Since I could not reproduce, I don't know what more I can attach or write about it =/
Thank you

**Comment by mohamedmostafadawood** [comment]
I have used it in the same version you posted and I did not face such a problem.
I assume you may have pressed an incorrect thing by mistake.
I want to help you if I can reproduce the error :)

**Comment by RafaelEstevamReis** [comment]
I have no idea what happened
As I said, is the first time I used it, so I can't easily "do things" to try

There is any thing I can do to help? Any command, configuration, debug mode, etc, then hope for it happen again, and then, post here?
