### ISSUE TITLE
mitmproxy console: crash when copying binary data to clipboard

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#531]
```
Traceback (most recent call last):
  File "/Users/cortesi/mitmproxy/mitmproxy/libmproxy/console/__init__.py", line 426, in run
    self.loop.run()
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/cortesi/mitmproxy/mitmproxy/libmproxy/console/window.py", line 14, in keypress
    k = urwid.Frame.keypress(self, self.master.loop.screen_size, k)
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/Users/cortesi/mitmproxy/mitmproxy/libmproxy/console/statusbar.py", line 105, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/Users/cortesi/mitmproxy/mitmproxy/libmproxy/console/statusbar.py", line 69, in keypress
    self.prompt_execute(k)
  File "/Users/cortesi/mitmproxy/mitmproxy/libmproxy/console/statusbar.py", line 92, in prompt_execute
    msg = p(txt, *args)
  File "/Users/cortesi/mitmproxy/mitmproxy/libmproxy/console/common.py", line 259, in copy_flow
    pyperclip.copy(data)
  File "/Users/cortesi/mitmproxy/venv.mitmproxy/lib/python2.7/site-packages/pyperclip/__init__.py", line 88, in _copyOSX
    p.communicate(input=text.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 2: ordinal not in range(128)
```

**Comment by mhils** [comment]
fixed by #532
