### ISSUE TITLE
mitmproxy crash on do_handshake

### ISSUE THREAD

**Issue by moozer** [mitmproxy/mitmproxy#5310]
#### Steps to reproduce the behavior:
1. install
2. start mitmproxy or mitmweb
3. 

#### System Information

```
# mitmproxy --version                                       
Mitmproxy: 8.0.0
Python:    3.8.12
OpenSSL:   LibreSSL 3.4.1
Platform:  OpenBSD-7.0-amd64-64bit-ELF
```

The error is like this;
```
...
192.168.111.100:60410: client connect
192.168.111.100:60410: server connect 52.40.173.137:443
Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/tlsconfig.py", line 216, in tls_start_server
    ssl_ctx = net_tls.create_proxy_server_context(
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/net/tls.py", line 154, in create_proxy_server_context
    SSL._lib.X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS | SSL._lib.X509_CHECK_FLAG_NEVER_CHECK_SUBJECT  # type: ignore
AttributeError: module 'lib' has no attribute 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

192.168.111.100:60410: No TLS context was provided, failing connection.
192.168.111.100:60410: mitmproxy has crashed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 290, in server_event
    for command in layer_commands:
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layer.py", line 255, in handle_event
    yield from self._handle(event)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layer.py", line 129, in handle_event
    yield from self.__continue(event)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layer.py", line 220, in __continue
    yield from self.__process(command_generator, event.reply)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layer.py", line 207, in __process
    command = next(command_generator)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/tunnel.py", line 90, in _handle_event
    yield from self.event_to_child(event)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layers/tls.py", line 358, in event_to_child
    for command in super().event_to_child(event):
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/tunnel.py", line 129, in event_to_child
    yield from self.start_handshake()
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layers/tls.py", line 354, in start_handshake
    yield from self.receive_handshake_data(b"")
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/proxy/layers/tls.py", line 212, in receive_handshake_data
    self.tls.do_handshake()
AttributeError: 'NoneType' object has no attribute 'do_handshake'

192.168.111.100:60410: Server TLS handshake failed. connection closed
...

```

It resembles #4683. That one is reported to be fixed in version 7.0.0 and I am doing 8.0.0

**Comment by mhils** [comment]
How did you install mitmproxy? The problem very likely is that you're using LibreSSL, not OpenSSL.

**Comment by moozer** [comment]
That was a quick answer. thanks.

I did a normal `pip install mitmproxy`
It took a long time and required rust to be installed.

I'm looking into if I can install openssl instead of libressl.

**Comment by mhils** [comment]
Alternatively, you can likely fix this by just removing the ` | SSL._lib.X509_CHECK_FLAG_NEVER_CHECK_SUBJECT` part in `/usr/local/lib/python3.8/site-packages/mitmproxy/net/tls.py`. This is mostly defense-in-depth, LibreSSL may be smart enough to not check subjects anyways. 🙃 If that fixes it, I'd be happy to merge a PR that makes mitmproxy work with LibreSSL. :)

**Comment by moozer** [comment]
That did the trick. thanks.

Screenshot from an accepted certificate in the browser
![image](https://user-images.githubusercontent.com/810413/166122409-8f99930e-fd76-4211-8ff2-a2c6a62dbff6.png)
