### ISSUE TITLE
PytestUnraisableExceptionWarning: RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5353]
#### Problem Description

`test_proxyserver:test_dns` currently causes a `PytestUnraisableExceptionWarning` at a random other test when running the testsuite:

```python
test/mitmproxy/addons/test_readfile.py::TestReadFileStdin::test_stdin
  /mnt/c/Users/user/git/mitmproxy/.tox/linux/py/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object ConnectionHandler.handle_connection at 0x7fa0fbffbd80>

  Traceback (most recent call last):
    File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
      await getter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/proxy/server.py", line 248, in handle_connection
      data = await reader.read(65535)
    File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/net/udp.py", line 267, in read
      return await self._packets.get()
    File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
      getter.cancel()  # Just in case getter is not done yet.
    File "/usr/lib/python3.10/asyncio/base_events.py", line 745, in call_soon
      self._check_closed()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 510, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

The problem is that pytest-asyncio closes the event loop while we still have an "active" UDP connection. One fix would be to just swallow these errors in `udp.py` (and return `b""`), alternatively we could manually cancel all active tasks in the respective test. I'm leaning towards the former. @Meitinger, any opinions? :)

#### Steps to reproduce the behavior:

1. `tox -e py`

#### System Information
```
Mitmproxy: 9.0.0.dev (+5, commit ef457a0)
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
```

**Comment by Meitinger** [comment]
Since this error might occur outside of the test as well, I totally agree that it should be dealt with in a general way.

Maybe instead of swallowing the exception, I'd be happy to work on one of the following changes:
1. When creating a `DatagramWriter` that manages a `DatagramReader`, use a registration mechanism that allows it to receive a notification once the protocol get's `close`ed. This way closing the `UdpServer` results in a `feed_eof` call on all readers. (Maybe also call a `asyncio.sleep(0)` afterwards.)
2. To prevent this issue from possibly affecting other protocols as well, go over all `_connections` in https://github.com/mitmproxy/mitmproxy/blob/4a2ca7563108d2256909309c770feb0c5b481397/mitmproxy/addons/proxyserver.py#L274 and explicitly close them.
