### ISSUE TITLE
AssertionError, probably because of HTTP/2 PING

### ISSUE THREAD

**Issue by EndUser509** [mitmproxy/mitmproxy#5377]
#### Problem Description
I found this stack trace in my error log today. I have been running `mitmdump` in this version for a few weeks now so I don't think I can easily reproduce it:
```
192.168.0.10:59300: mitmproxy has crashed!
Traceback (most recent call last):
  File "/home/user/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 911, in event_to_child
    stream = self.streams[command.event.stream_id]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/mitmproxy/mitmproxy/proxy/server.py", line 333, in server_event
    for command in layer_commands:
  File "/home/user/mitmproxy/mitmproxy/proxy/layer.py", line 143, in handle_event
    command = command_generator.send(send)
  File "/home/user/mitmproxy/mitmproxy/proxy/layer.py", line 256, in handle_event
    yield from self._handle(event)
  File "/home/user/mitmproxy/mitmproxy/proxy/layer.py", line 143, in handle_event
    command = command_generator.send(send)
  File "/home/user/mitmproxy/mitmproxy/proxy/tunnel.py", line 79, in _handle_event
    yield from self.receive_data(event.data)
  File "/home/user/mitmproxy/mitmproxy/proxy/layers/tls.py", line 335, in receive_data
    yield from self.event_to_child(
  File "/home/user/mitmproxy/mitmproxy/proxy/layers/tls.py", line 408, in event_to_child
    yield from super().event_to_child(event)
  File "/home/user/mitmproxy/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/home/user/mitmproxy/mitmproxy/proxy/layer.py", line 143, in handle_event
    command = command_generator.send(send)
  File "/home/user/mitmproxy/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
    yield from self.event_to_child(event)
  File "/home/user/mitmproxy/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/home/user/mitmproxy/mitmproxy/proxy/layer.py", line 143, in handle_event
    command = command_generator.send(send)
  File "/home/user/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/home/user/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 914, in event_to_child
    assert isinstance(
AssertionError
```
The connection that produced the error did this:
```
[2022-05-26 10:30:27] 192.168.0.10:59300: client connect
[2022-05-26 10:30:27] 192.168.0.10:59300: server connect 12.34.56.78:443
[2022-05-26 10:30:27] 192.168.0.10:59300: GET https://example.com/index.html HTTP/2.0
[2022-05-26 10:31:25] 192.168.0.10:59300: Send HTTP/2 keep-alive PING to 12.34.56.78:443
[2022-05-26 10:32:25] 192.168.0.10:59300: Send HTTP/2 keep-alive PING to 12.34.56.78:443
[2022-05-26 10:33:24] 192.168.0.10:59300: Send HTTP/2 keep-alive PING to 12.34.56.78:443
[2022-05-26 10:34:19] 192.168.0.10:59300: Send HTTP/2 keep-alive PING to 12.34.56.78:443
[2022-05-26 10:34:27] 192.168.0.10:59300: client disconnect
[2022-05-26 10:34:27] 192.168.0.10:59300: closing transports...
[2022-05-26 10:34:27] 192.168.0.10:59300: server disconnect 12.34.56.78:443
[2022-05-26 10:34:27] 192.168.0.10:59300: transports closed!
```
Unfortunately there are no timestamps in the error log. My guess is though that this is the result of adding HTTP/2 PING support. The solution is probably to add `Wakeup` and/or `RequestWakeup` to the assertion in `mitmproxy/proxy/layers/http/__init__.py`:
```
                   # We may be getting errors for a specific stream even though we've already finished handling it.
                    assert isinstance(
                        command.event, (RequestProtocolError, ResponseProtocolError)
                    )
```
But maybe I am wrong and there is another event type actually missing in the assertion.

**Comment by mhils** [comment]
Thanks for reporting this - I think it has been fixed by https://github.com/mitmproxy/mitmproxy/commit/4a2ca7563108d2256909309c770feb0c5b481397 :)
