### ISSUE TITLE
Crash using HTTP proxy with selenium, error on stream 25

### ISSUE THREAD

**Issue by DMaxter** [mitmproxy/mitmproxy#5434]
#### Problem Description
I'm starting mitmproxy programmatically in order to use it as a proxy for selenium, and add it my addon, which simply uses the `response` HTTP hook
I spawn one proxy for each webdriver I start, because I need to obtain the requests of each URL I visit
However, when running for a bit, it crashes with the following output (I have stdout disabled because mitmproxy logs too much stuff, so I only have stderr output - traceback from python):

```
downloader-scrapper-1  | 127.0.0.1:52632: mitmproxy has crashed!
downloader-scrapper-1  | Traceback (most recent call last):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 911, in event_to_child
downloader-scrapper-1  |     stream = self.streams[command.event.stream_id]
downloader-scrapper-1  | KeyError: 25
downloader-scrapper-1  |
downloader-scrapper-1  | During handling of the above exception, another exception occurred:
downloader-scrapper-1  |
downloader-scrapper-1  | Traceback (most recent call last):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/server.py", line 325, in server_event
downloader-scrapper-1  |     for command in layer_commands:
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 256, in handle_event
downloader-scrapper-1  |     yield from self._handle(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(handler, event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 899, in event_to_child
downloader-scrapper-1  |     for command in child.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 743, in passthrough
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 79, in _handle_event
downloader-scrapper-1  |     yield from self.receive_data(event.data)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 335, in receive_data
downloader-scrapper-1  |     yield from self.event_to_child(
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 408, in event_to_child
downloader-scrapper-1  |     yield from super().event_to_child(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(handler, event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 914, in event_to_child
downloader-scrapper-1  |     assert isinstance(
downloader-scrapper-1  | AssertionError
downloader-scrapper-1  |
downloader-scrapper-1  | 127.0.0.1:52632: mitmproxy has crashed!
downloader-scrapper-1  | Traceback (most recent call last):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 911, in event_to_child
downloader-scrapper-1  |     stream = self.streams[command.event.stream_id]
downloader-scrapper-1  | KeyError: 25
downloader-scrapper-1  |
downloader-scrapper-1  | During handling of the above exception, another exception occurred:
downloader-scrapper-1  |
downloader-scrapper-1  | Traceback (most recent call last):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/server.py", line 325, in server_event
downloader-scrapper-1  |     for command in layer_commands:
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 256, in handle_event
downloader-scrapper-1  |     yield from self._handle(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(handler, event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 899, in event_to_child
downloader-scrapper-1  |     for command in child.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 743, in passthrough
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 79, in _handle_event
downloader-scrapper-1  |     yield from self.receive_data(event.data)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 335, in receive_data
downloader-scrapper-1  |     yield from self.event_to_child(
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 408, in event_to_child
downloader-scrapper-1  |     yield from super().event_to_child(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(handler, event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 914, in event_to_child
downloader-scrapper-1  |     assert isinstance(
downloader-scrapper-1  | AssertionError
downloader-scrapper-1  |
downloader-scrapper-1  | 127.0.0.1:52632: mitmproxy has crashed!
downloader-scrapper-1  | Traceback (most recent call last):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 911, in event_to_child
downloader-scrapper-1  |     stream = self.streams[command.event.stream_id]
downloader-scrapper-1  | KeyError: 25
downloader-scrapper-1  |
downloader-scrapper-1  | During handling of the above exception, another exception occurred:
downloader-scrapper-1  |
downloader-scrapper-1  | Traceback (most recent call last):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/server.py", line 325, in server_event
downloader-scrapper-1  |     for command in layer_commands:
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 256, in handle_event
downloader-scrapper-1  |     yield from self._handle(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(handler, event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 899, in event_to_child
downloader-scrapper-1  |     for command in child.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 743, in passthrough
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 79, in _handle_event
downloader-scrapper-1  |     yield from self.receive_data(event.data)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 335, in receive_data
downloader-scrapper-1  |     yield from self.event_to_child(
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 408, in event_to_child
downloader-scrapper-1  |     yield from super().event_to_child(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
downloader-scrapper-1  |     for command in self.child_layer.handle_event(event):
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
downloader-scrapper-1  |     command = command_generator.send(send)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
downloader-scrapper-1  |     yield from self.event_to_child(handler, event)
downloader-scrapper-1  |   File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 914, in event_to_child
downloader-scrapper-1  |     assert isinstance(
downloader-scrapper-1  | AssertionError
```

A while after, I got a few messages stating

```socket.send() raised exception``` but I don't if they are on the selenium side because proxy has died or from mitmproxy itself for some other reason

The proxy works fine for a while, it just crashes without apparent reason. When running with 3 proxies, 2 crashed after a while and the other continued to produce results

#### Steps to reproduce the behavior:
1. Start mitmproxy
2. Start selenium and use mitmproxy as the proxy
3. Wait for this error to show

#### System Information
```
Mitmproxy: 8.1.0
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.18.6-zen1-1-zen-x86_64-with-glibc2.31
```

**Comment by mhils** [comment]
This should be fixed in 8.1.1.
