### ISSUE TITLE
Error when trying to start server playback

### ISSUE THREAD

**Issue by evrom** [mitmproxy/mitmproxy#546]
I am trying to replay the server from a file. The file opens perfectly fine in mitmproxy.
This is on mitmproxy 0.11.3

I get this error when hitting 'S' in mitmproxy
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 614, in run
    self.ui.run_wrapper(self.loop)
  File "/usr/local/lib/python2.7/dist-packages/urwid/display_common.py", line 757, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 841, in loop
    self.prompt_execute()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 766, in prompt_execute
    msg = p(txt, *args)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 524, in server_playback_path
    self.options.replay_ignore_params, self.options.replay_ignore_content
TypeError: start_server_playback() takes exactly 9 arguments (8 given)

mitmproxy has crashed!
```
And I get this error when executing `mitmproxy -S mitmoutput.mitm`
```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 3, in <module>
    mitmproxy()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/main.py", line 97, in mitmproxy
    m = console.ConsoleMaster(server, console_options)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 430, in __init__
    self.server_playback_path(options.server_replay)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 524, in server_playback_path
    self.options.replay_ignore_params, self.options.replay_ignore_content
TypeError: start_server_playback() takes exactly 9 arguments (8 given)
```

**Comment by evrom** [comment]
I will try installing the latest code from github, and see if that fixes the error.

**Comment by evrom** [comment]
Updating to latest code from github fixes the error.

**Comment by mhils** [comment]
Thanks for investigating yourself! :-)
