### ISSUE TITLE
ValueError: mutable default <class 'mitmproxy.contentviews.grpc.ProtoParser.ParserOptions'> for field parser_options is not allowed: use default_factory on python 3.11

### ISSUE THREAD

**Issue by rathann** [mitmproxy/mitmproxy#5474]
#### Problem Description
mitmproxy fails to start throwing a `ValueError` exception:
```
ValueError: mutable default <class 'mitmproxy.contentviews.grpc.ProtoParser.ParserOptions'> for field parser_options is not allowed: use default_factory
```

#### Steps to reproduce the behavior:
1. Install mitmproxy 8.1.1 on Fedora rawhide (37)
2. run the binary

#### System Information
```
$ /usr/bin/mitmproxy --version
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 118, in mitmproxy
    from mitmproxy.tools import console
  File "/usr/lib/python3.11/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/usr/lib/python3.11/site-packages/mitmproxy/tools/console/master.py", line 26, in <module>
    from mitmproxy.tools.console import consoleaddons
  File "/usr/lib/python3.11/site-packages/mitmproxy/tools/console/consoleaddons.py", line 6, in <module>
    from mitmproxy import contentviews
  File "/usr/lib/python3.11/site-packages/mitmproxy/contentviews/__init__.py", line 23, in <module>
    from . import (
  File "/usr/lib/python3.11/site-packages/mitmproxy/contentviews/grpc.py", line 952, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'mitmproxy.contentviews.grpc.ProtoParser.ParserOptions'> for field parser_options is not allowed: use default_factory
```

**Comment by mhils** [comment]
We don't officially support Python 3.11 yet, but thanks for the pointer!

**Comment by lampuiho** [comment]
I have tried running mitmdump after activating venv with source env/bin/activate (after creating it with python3.9 -m venv env, which came after installing python3-pip, python3.9-dev python3.9-venv, and python3.9distutils) However, I still see 3.11 library  /usr/lib/python3.11/dataclasses.py being imported and used. When I run python3, I can see that I'm indeed on 3.9. Does mitm run python differently that it somehow escapes the venv?

**Comment by mhils** [comment]
We don't do anything special, but FWIW the comment above is outdated. Please refer to our main README für the supported Python versions. At the moment that's 3.9 minimum for mitmproxy 9.x, and Python 3.10+ for the current main branch. :)
