### ISSUE TITLE
8.1.1: "OSError: [Errno 48] Address already in use" -- error message could use improvement

### ISSUE THREAD

**Issue by jcollum-nutrien** [mitmproxy/mitmproxy#5491]
#### Problem Description

```
~ mitmweb
Traceback (most recent call last):
  File "/opt/homebrew/bin/mitmweb", line 33, in <module>
    sys.exit(load_entry_point('mitmproxy==8.1.1', 'console_scripts', 'mitmweb')())
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 144, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 114, in run
    return asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 111, in main
    await master.run()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/master.py", line 48, in run
    await self.running()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/web/master.py", line 83, in running
    http_server.listen(self.options.web_port, self.options.web_host)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
```

OK that's cryptic. What address? How do I override it? 

#### Proposal

The error message should: 

1. tell me what address it's trying to use
2. give me a suggestion for fixing it -- can I use `MITM_PORT=8082 mitmweb` or something similar? 

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by Prinzhorn** [comment]
#5495 was merged, the error should now include more relevant info.
