### ISSUE TITLE
ImportError: No module named libmproxy though it's installed!

### ISSUE THREAD

**Issue by Seek4samurai** [mitmproxy/mitmproxy#5500]
This seems to be a weird problem in during installation of mitmproxy.
During installing it shows as:

`(base) seek4samurai@ubuntu:~$ pip install mitmproxy==0.18.2`

```
Collecting urwid<1.4,>=1.3.1
  Using cached urwid-1.3.1.tar.gz (588 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/seek4samurai/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0lczvtyo/urwid_80875501551347dd8026ccc0cfa168b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0lczvtyo/urwid_80875501551347dd8026ccc0cfa168b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r4eaje3f
         cwd: /tmp/pip-install-0lczvtyo/urwid_80875501551347dd8026ccc0cfa168b1/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 462, in __init__
        _Distribution.__init__(
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
        self.finalize_options()
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 886, in finalize_options
        ep(self)
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 907, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 305, in invalid_unless_false
        raise DistutilsSetupError(f"{attr} is invalid.")
    distutils.errors.DistutilsSetupError: use_2to3 is invalid.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-0lczvtyo/urwid_80875501551347dd8026ccc0cfa168b1/setup.py", line 85, in <module>
        setup(**setup_d)
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/seek4samurai/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 114, in setup
        raise SystemExit("error in %s setup command: %s" % \
    SystemExit: error in urwid setup command: use_2to3 is invalid.
    error in urwid setup command: use_2to3 is invalid.
    Couldn't build the extension module, trying without it...
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/85/5d/9317d75b7488c335b86bd9559ca03a2a023ed3413d0e8bfe18bea76f24be/urwid-1.3.1.tar.gz#sha256=cfcec03e36de25a1073e2e35c2c7b0cc6969b85745715c3a025a31d9786896a1 (from https://pypi.org/simple/urwid/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement urwid<1.4,>=1.3.1 (from mitmproxy) (from versions: 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2)
ERROR: No matching distribution found for urwid<1.4,>=1.3.1
```
```
(base) seek4samurai@ubuntu:~$ pip install urwid
Requirement already satisfied: urwid in ./anaconda3/lib/python3.9/site-packages (2.1.1)
```
It says No matching distribution found for urwid but it's already installed.
Anyway to fix this issue?

**Comment by mhils** [comment]
The mitmproxy version you're trying to install is (vastly) outdated. Official installation guidance is at https://docs.mitmproxy.org/stable/overview-installation/.
