### ISSUE TITLE
mitmweb crash on main

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#5521]
#### Problem Description

Bisected to [83e543c3e66654b952f1979c0adaa62df91b2832](https://github.com/mitmproxy/mitmproxy/commit/83e543c3e66654b952f1979c0adaa62df91b2832)

![image](https://user-images.githubusercontent.com/679144/183923788-99832ee1-7c36-495b-8c86-5bf50b2305e5.png)

```
Component Stack:
    at PureOption (http://localhost:8081/static/app.js:62:134)
    at ConnectFunction (http://localhost:8081/static/app.js:51:11352)
    at div
    at div
    at div
    at div
    at div
    at PureOptionModal (http://localhost:8081/static/app.js:62:1549)
    at ConnectFunction (http://localhost:8081/static/app.js:51:11352)
    at div
    at div
    at div
    at div
    at ModalLayout (http://localhost:8081/static/app.js:60:14486)
    at OptionModal
    at PureModal (http://localhost:8081/static/app.js:62:2852)
    at div
    at ProxyAppMain (http://localhost:8081/static/app.js:62:3048)
    at ConnectFunction (http://localhost:8081/static/app.js:51:11352)
    at Provider (http://localhost:8081/static/app.js:51:8664)
```

#### Steps to reproduce the behavior:
1. `mitmweb`
2. Open http://127.0.0.1:8081/
3. Click "Edit Options"

![Screenshot from 2022-08-10 16-15-22](https://user-images.githubusercontent.com/679144/183924122-90a89fd4-aa44-4bda-92a1-5be3f6ba6714.png)

#### System Information

```
Mitmproxy: 9.0.0.dev (+57, commit fbcffee)
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.15.0-43-generic-x86_64-with-glibc2.35
```

**Comment by mhils** [comment]
Fixed on main :)
