### ISSUE TITLE
React Error when scrolling down mitmweb

### ISSUE THREAD

**Issue by KinlyDev** [mitmproxy/mitmproxy#5525]
When scrolling through a capture on mitmweb it crashes with the following:

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (http://127.0.0.1:8081/static/app.js:7:8533)
    at Object.enqueueSetState (http://127.0.0.1:8081/static/app.js:5:44513)
    at Oc.setState (http://127.0.0.1:8081/static/app.js:1:3945)
    at t.onViewportUpdate (http://127.0.0.1:8081/static/app.js:58:48851)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:48148)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:46203)
    at Yi (http://127.0.0.1:8081/static/app.js:7:1828)
    at dk (http://127.0.0.1:8081/static/app.js:9:5215)
    at Dt.unstable_runWithPriority (http://127.0.0.1:8081/static/app.js:1:12961)
    at gg (http://127.0.0.1:8081/static/app.js:5:40220)

Component Stack:
    at AutoScrollWrapper (http://127.0.0.1:8081/static/app.js:58:45836)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:49804)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3048)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)

It seems to do it only when I use the scroll wheel on the mouse to scroll through the flows.

Mitmproxy: 8.1.0 binary
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Windows-10-10.0.22000-SP0

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/search?q=Minified+React+error+%23185&type=issues
https://github.com/mitmproxy/mitmproxy/issues/5198
#5507
