### ISSUE TITLE
pip install error on Ubuntu due to pyOpenSSL breaking change

### ISSUE THREAD

**Issue by dkozel** [mitmproxy/mitmproxy#557]
I just tried a vanilla sudo pip install mitmproxy from Ubuntu 14.10 and it failed to run with the following error.

    sudo mitmproxy --version
    Traceback (most recent call last):
      File "/usr/local/bin/mitmproxy", line 2, in <module>
        from libmproxy.main import mitmproxy
      File "/usr/local/lib/python2.7/dist-packages/libmproxy/main.py", line 6, in <module>
        from . import version, cmdline
      File "/usr/local/lib/python2.7/dist-packages/libmproxy/cmdline.py", line 6, in <module>
        from . import filt, utils, version
      File "/usr/local/lib/python2.7/dist-packages/libmproxy/filt.py", line 37, in <module>
        from .protocol.http import decoded
      File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/__init__.py", line 1, in <module>
        from .primitives import *
      File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/primitives.py", line 4, in <module>
        import netlib.tcp
      File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 8, in <module>
        from OpenSSL import SSL 
      File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL 
      File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
        from OpenSSL._util import (
      File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
        from cryptography.hazmat.bindings.openssl.binding import Binding
    ImportError: No module named cryptography.hazmat.bindings.openssl.binding

I resolved this by reverting pyOpenSSL to 0.14. The pip install process had installed pyOpenSSL-0.15.1-py2.py3-none-any.whl

    sudo pip install pyOpenSSL==0.14

This was for mitmproxy 0.11.3

Thanks for the very useful software.

**Comment by mhils** [comment]
Thanks for the report. Looks like there finally a new pyOpenSSL release, we
should adjust ASAP.

(cc @cortesi)

Cheers,
Max

Derek Kozel <notifications@github.com> schrieb am Mi., 15. Apr. 2015 17:36:

**Comment by elitest** [comment]
Having trouble re-producing, this, not sure it is a pyOpenSSL issue.  I have mitmproxy 0.11.4 on an Ubuntu 14.04 machine and it is running fine with the 0.15.1 release of pyOpenSSL.

**Comment by mhils** [comment]
Thanks @elitest - I was on mobile earlier, looks like you're right here. @dkozel, can you still reproduce the issue somehow? If so, I'd be very interested in the output of `pip freeze`.

Thanks!
Max

**Comment by dkozel** [comment]
I'll give it a shot tomorrow. This was a completely fresh machine, I had to
install pip just before!

**Comment by dkozel** [comment]
sudo pip install pip-autoremove
    sudo pip-autoremove mitmproxy
    sudo pip-autoremove pyOpenSSL
    sudo pip install mitmproxy

This did not cause the issue to reoccur. I guess close up this issue and I'll reopen if I can persuade it to come up again. I'm having trouble getting mitmproxy to intercept my Android app communications so I'll be playing with different systems all day.

Thanks again.

**Comment by vsalles** [comment]
dkozel  thanks
