### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by polarxy** [mitmproxy/mitmproxy#5581]
Traceback (most recent call last):

  File "D:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)

  File "D:\Python39\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues

**Comment by Prinzhorn** [comment]
Please fill out the issue template that is presented when you create a new bug report.
