### ISSUE TITLE
Help Test WireGuard Mode

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5592]
We've merged our super shiny new WireGuard mode! ✨ There is a blogpost by @decathorpe upcoming, but you can probably figure things out by running `mitmweb --mode wireguard` if you want to dive in an test things.

Let's embrace integration hell and use this issue to collect bugs discovered during testing:

#### 1. InvalidStateError

```
[13:37:22.599][10.0.0.1:50682] Client TLS handshake failed. The client does not trust the proxy's certificate for android-context-data.googleapis.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))
[13:37:22.601] Traceback (most recent call last):

  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)

asyncio.exceptions.InvalidStateError: invalid state

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
```

Test setup: Firefox on Android 13 + mitmweb on Windows. This often happens after "Client TLS handshake failed" errors... 
This one is probably by far the hardest issue to debug and may have its roots in Rust-land. @decathorpe, any ideas?

#### 2. ✅ <s>DNS Configuration</s>

The current WireGuard config does not specify a DNS server. This means that DNS queries are then made outside of the tunnel (which coincidentally does not work with my test setup). I'll follow up with a PR in a minute.

#### 3. ✅ <s>KeyErrors on Exit</s>

I got `KeyErrors` on exit for this line:
https://github.com/mitmproxy/mitmproxy/blob/03b643b8cdd9d43043b24be41b3dbbde2f37ff46/mitmproxy/addons/proxyserver.py#L122

...which I can't reproduce anymore somehow. The problem here is clear though, `sockname` is static (0.0.0.0:51820) and `peername` is reused which yields non-unique connection ids. Conceptually this should affect regular transparent mode as well, not just WireGuard. The easiest fix would probably be to refactor the injection mechanism to not rely on 5-tuples, or to fix it properly for both WireGuard and transparent mode.

**Comment by decathorpe** [comment]
> 1. InvalidStateError

Not sure where this comes from. According to the Python docs, this exception is raised when some internal state of a `Task` or `Future` is made invalid. I could not find references to this exception in the `pyo3-asyncio` crate, so the exception is raised on the Python side, but the *cause* might be on the Rust side. I *think* all async / coroutines in mitmproxy_wireguard are correct, but it might be a good place to start (for example, is the GIL held everywhere it needs to be?).

**Comment by mhils** [comment]
Yes - https://github.com/awestlake87/pyo3-asyncio/pull/39 might serve as some inspiration on what it might be.

**Comment by mhils** [comment]
I think I figured out how we get `InvalidStateError`s:

1. When our Rust future completes, pyo3-asyncio checks if the Python future has already been cancelled and calls `set_result` if that's not the case:
https://github.com/awestlake87/pyo3-asyncio/blob/bc2d75d292f9c7080de3fa7fbf7c63ee62c446e1/src/generic.rs#L576-L588
2. `set_result` calls `asyncio.call_soon_threadsafe` to set the result: 
    https://github.com/awestlake87/pyo3-asyncio/blob/bc2d75d292f9c7080de3fa7fbf7c63ee62c446e1/src/generic.rs#L319-L320
4. The Python future gets cancelled by mitmproxy.
5. The call we scheduled in step 2 is now executed, but setting a result on an already-closed future raises an `InvalidStateError`.

The correct fix is probably to not schedule a call to `Future.set_result`, but schedule a call to our_method_that_checks_cancellation_first_and_then_sets_the_result. @decathorpe, do you think you can tackle a fix for this and then send a PR upstream? Otherwise I'll give it a go, but you're the Rust expert here. 😅

**Comment by decathorpe** [comment]
Hum, I tried to work on a fix for the `InvalidStateError` bug, but couldn't quite figure out how to do it, so I reported the problem here (and linked my attempted fix): https://github.com/awestlake87/pyo3-asyncio/issues/77

**Comment by decathorpe** [comment]
With mitmproxy_wireguard 0.1.10, I included a temporary fix for the race condition that causes `InvalidStateError`s (until the problem is resolved in pyo3-asyncio upstream). I tried running `mitmweb --mode wireguard` with this version, and didn't see any `InvalidStateError`s being thrown. 🚀

**Comment by mhils** [comment]
@decathorpe: I managed to this this one during testing with an Android device, any ideas?

```
thread 'tokio-runtime-worker' panicked at 'The destination buffer is too small', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/boringtun-0.5.2/src/noise/session.rs:198:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[15:58:33.604][10.0.0.1:35446] server connect 142.250.185.106:443
[15:58:33.609] WireGuard server task failed: task 11 panicked
[15:58:33.610] WireGuard server task shut down early, exiting.
```

**Comment by mhils** [comment]
Ok, the problem here are large DNS responses which are answered by mitmproxy locally:

1. Client sends DNS request for `discover-pa.googleapis.com`
2. mitmweb resolves locally (to a whole bunch of IPs)
3. Response datagram is too large (~2000 bytes). We only notice that when wrapping for WireGuard.

Now we certainly could fix our local DNS resolver to cut off at some point, but that's not fixing the root cause. We could also just be receiving large (close to 1500 bytes) packets from upstream. Instead, we should probably add IP fragmentation for UDP packets? 

The good news is that smoltcp seems to have merged support for IPv4 fragmentation about a month ago (https://github.com/smoltcp-rs/smoltcp/pull/634). So it seems like the proper place to fix this would be to pass all UDP packets through our smol stack as well? Doesn't sound ideal, but not sure what the alternatives would be.

**Comment by decathorpe** [comment]
Fix committed and released: https://pypi.org/project/mitmproxy-wireguard/0.1.14/

**Comment by KOLANICH** [comment]
https://github.com/KOLANICH-libs/sio-smoltcp.rs (also contains python bindings) + https://github.com/KOLANICH-libs/BoringTUN.py may be helpful

**Comment by Surendrajat** [comment]
I encountered the following error while running in `wireguard` mode:

```
[13:50:14.828][10.0.0.1:42650] Closing connection due to inactivity: Client(10.0.0.1:42650, state=open)
[13:50:14.829][10.0.0.1:42650] client disconnect
[13:50:15.731][10.0.0.1:37865] mitmproxy has crashed!
['Traceback (most recent call last):\n', '  File "/opt/homebrew/Cellar/mitmproxy/9.0.1/libexec/lib/python3.11/site-packages/mitmproxy/proxy/server.py", line 275, in handle_connection\n    await self.drain_writers()\n', '  File "/opt/homebrew/Cellar/mitmproxy/9.0.1/libexec/lib/python3.11/site-packages/mitmproxy/proxy/server.py", line 310, in drain_writers\n    for transport in self.transports.values():\n', 'RuntimeError: dictionary changed size during iteration\n']
[13:50:15.731][10.0.0.1:37865] client disconnect
[13:50:15.732][10.0.0.1:37865] error establishing server connection: client disconnected
[13:50:15.905][10.0.0.1:37866] mitmproxy has crashed!
['Traceback (most recent call last):\n', '  File "/opt/homebrew/Cellar/mitmproxy/9.0.1/libexec/lib/python3.11/site-packages/mitmproxy/proxy/server.py", line 275, in handle_connection\n    await self.drain_writers()\n', '  File "/opt/homebrew/Cellar/mitmproxy/9.0.1/libexec/lib/python3.11/site-packages/mitmproxy/proxy/server.py", line 310, in drain_writers\n    for transport in self.transports.values():\n', 'RuntimeError: dictionary changed size during iteration\n']
[13:50:15.905][10.0.0.1:37866] client disconnect
```

Is it due to `wireguard` or an issue with mitmproxy itself?

**Comment by mhils** [comment]
Thanks, @Surendrajat!
This has already been fixed in https://github.com/mitmproxy/mitmproxy/commit/b9dc95cb8c3e2ea65800a0f01d9348d056dd32f6. :)

**Comment by Surendrajat** [comment]
@mhils wow. Thanks a lot.

**Comment by mhils** [comment]
@itsjamie: Take a look at https://docs.mitmproxy.org/stable/howto-ignoredomains/

> we would love to be able to provide certs to be used to decrypt traffic like in the normal proxy mode.

That should also work equally well provided your clients send cleartext SNIs.

**Comment by malachid** [comment]
I downloaded the linux tar.gz, extracted those and ran `mitmweb --mode wireguard` as per the blog post (and above).  According to the blog post, if it doesn't find encryption keys, it will autogenerate them.  Instead, it fails with a missing `/home/<username>/.mitmproxy/wireguard.conf`.

**Comment by mhils** [comment]
What's your output for mitmweb --version?

**Comment by malachid** [comment]
> What's your output for mitmweb --version?

Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.0-60-generic-x86_64-with-glibc2.35

**Comment by decathorpe** [comment]
Yeah, the missing creation of the .mitmproxy directory has been fixed in the development branch, but no release with that fix has been published yet:

https://github.com/mitmproxy/mitmproxy/commit/c9ccd6f4b3917b33300d8d187bb7eee4d1a5b41e

(which happened shortly *after* the latest release, 9.0.1)

**Comment by shaggycrew** [comment]
Since you guys are talking about modes I was wondering what I'm doing wrong in my router to get custom routing to work with mitmproxy

These are the rules I'm using in my router routing tables

IPV4     192.168.1.0/24     IP_DATA      192.168.1.7     AUTO     STATIC

These are the rules I'm using on my device 

sudo iptables -t nat -A PREROUTING -p tcp -s 192.168.1.0/24 -j DNAT  --to-destination 192.168.1.7:8080

sudo iptables -t nat -A POSTROUTING -j MASQUERADE


Note: I can't access iptables

**Comment by konsumer** [comment]
This seems useful, but I can't seem to get it to work with an android emulator.

I tested with the old regular proxy (setting emulator proxy to `192.168.86.24:8080`) and it works ok with Chrome app.

If I setup this config-file:

```ini
[Interface]
PrivateKey = <SOME_STRING>
Address = 10.0.0.1/32
DNS = 10.0.0.53

[Peer]
PublicKey = <SOME_STRING>
AllowedIPs = 0.0.0.0/0
Endpoint = 192.168.86.24:51820
```
On device I use wireguard app, from googleplay, and install the config file, and toggle it on.

`192.168.86.24` is my computer's LAN IP, so I used that, but mitm in docker says `172.17.0.2:51820`.

On my machine, I run this:

```
docker run -d --rm -it -v ${PWD}/.mitm:/home/mitmproxy/.mitmproxy -p 51820:51820 -p 8080:8080 -p 8081:8081 mitmproxy/mitmproxy mitmweb --web-host 0.0.0.0 --showhost --mode wireguard
```

I get the web UI, but no traffic gets sent there, and the emulator has no internet.

Am I setting it up wrong?

**Comment by forlayo** [comment]
mDNS is not passing from the device connecting through WireGuard to the regular network, then MITM proxy can't be used with wireguard to check services that depends on mDNS for being discovered before connecting to them
