### ISSUE TITLE
Option type typing.Sequence results in errors

### ISSUE THREAD

**Issue by ZeroRin** [mitmproxy/mitmproxy#5610]
#### Problem Description
The document says:
```markdown
The following types are supported for options.

- Primitive types - `str`, `int`, `float`, `bool`.
- Optional values, annotated using `typing.Optional`.
- Sequences of values, annotated using `typing.Sequence`.
```

However, adding an option with `typespec=typing.Sequence` results in an IndexError,  `typespec=typing.Sequence[str]` results in an NotImplementedError, while with `typespec=abc.Sequence[str]` it works

#### Steps to reproduce the behavior:
1. Write a toy addon `test.py`
```python
from mitmproxy.addonmanager import Loader
from mitmproxy import ctx
from collections import abc
import typing

class Addon:
    def load(self, loader:Loader):
        loader.add_option(
            name="seq",
            typespec=typing.Sequence,
            default=['123'],
            help="A sequence",
        )

    def running(self):
        print('running')
        print(ctx.options.seq)

addons = [Addon()]
```
2. Run `mitmdump.exe -s test.py --set seq=foo`, an error occurred
```log
Addon error: Traceback (most recent call last):
  File "test.py", line 8, in load
    loader.add_option(
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\addonmanager.py", line 92, in add_option
    self.master.options.add_option(name, typespec, default, help, choices)
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\optmanager.py", line 115, in add_option
    self._options[name] = _Option(name, typespec, default, help, choices)
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\optmanager.py", line 36, in __init__
    typecheck.check_option_type(name, default, typespec)
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\utils\typecheck.py", line 43, in check_option_type
    T = typing.get_args(typeinfo)[0]
IndexError: tuple index out of range
```
3. Change to `typing.Sequence[str]` results in another error
```log
Addon error: Traceback (most recent call last):
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\addonmanager.py", line 44, in safecall
    yield
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\addons\script.py", line 112, in loadscript
    ctx.master.addons.register(ns)
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\addonmanager.py", line 187, in register
    self.master.options.process_deferred()
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\optmanager.py", line 344, in process_deferred
    value = self._parse_setval(self._options[optname], value.val)
  File "D:\miniconda3\envs\gfl\lib\site-packages\mitmproxy\optmanager.py", line 392, in _parse_setval
    raise NotImplementedError(f"Unsupported option type: {o.typespec}")
NotImplementedError: Unsupported option type: typing.Sequence[str]
```
4. By changing the typespec to `abc.Sequence[str]` the code work as expected.

#### System Information
Mitmproxy: 8.1.1
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Windows-10-10.0.17763-SP0

**Comment by mazen-r** [comment]
I can work on this issue.
Chaning `typing.Sequence` to 'abc.Sequence[str]' in Docs solves the issue right ?

**Comment by mhils** [comment]
Yes. `collections.abc.Sequence`, please. :) For bonus points we could catch usage of `typing.Sequence` in `OptManager.add_option`, but just fixing the docs is a great first step. 👍
