### ISSUE TITLE
Example of invoking individual tests (CONTRIBURING.md) is broken

### ISSUE THREAD

**Issue by abbbe** [mitmproxy/mitmproxy#5614]
#### Problem Description

The following example is given at https://github.com/mitmproxy/mitmproxy/blob/main/CONTRIBUTING.md:
```
cd test/mitmproxy/addons
pytest --cov mitmproxy.addons.anticache --cov-report term-missing --looponfail test_anticache.py
```

It fails:
```
root@fw6b:/mitmproxy# cd test/mitmproxy/addons
root@fw6b:/mitmproxy/test/mitmproxy/addons# pytest --cov mitmproxy.addons.anticache --cov-report term-missing --looponfail test_anticache.py

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-log-0.6.0/src/lib.rs:570:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: mitmproxy_wireguard::mitmproxy_wireguard
   4: PyInit_mitmproxy_wireguard
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: _PyEval_EvalFrameDefault
   9: _PyFunction_Vectorcall
  10: _PyEval_EvalFrameDefault
  11: _PyFunction_Vectorcall
  12: _PyEval_EvalFrameDefault
  13: _PyFunction_Vectorcall
  14: _PyEval_EvalFrameDefault
  15: _PyFunction_Vectorcall
  16: _PyEval_EvalFrameDefault
  17: _PyFunction_Vectorcall
  18: _PyEval_EvalFrameDefault
  19: _PyFunction_Vectorcall
  20: <unknown>
  21: _PyObject_CallMethodIdObjArgs
  22: PyImport_ImportModuleLevelObject
  23: _PyEval_EvalFrameDefault
  24: <unknown>

  26: <unknown>
  27: <unknown>
  28: _PyEval_EvalFrameDefault
  29: _PyFunction_Vectorcall
  30: _PyEval_EvalFrameDefault
  31: _PyFunction_Vectorcall
  32: _PyEval_EvalFrameDefault
  33: _PyFunction_Vectorcall
  34: _PyEval_EvalFrameDefault
  35: _PyFunction_Vectorcall
  36: _PyEval_EvalFrameDefault
  37: _PyFunction_Vectorcall
  38: <unknown>
  39: _PyObject_CallMethodIdObjArgs
  40: PyImport_ImportModuleLevelObject
  41: _PyEval_EvalFrameDefault
  42: <unknown>
  43: PyEval_EvalCode
  44: <unknown>
  45: <unknown>
  46: _PyEval_EvalFrameDefault
  47: _PyFunction_Vectorcall
  48: _PyEval_EvalFrameDefault
  49: _PyFunction_Vectorcall
  50: _PyEval_EvalFrameDefault
  51: _PyFunction_Vectorcall
  52: _PyEval_EvalFrameDefault
  53: _PyFunction_Vectorcall
  54: _PyEval_EvalFrameDefault
  55: _PyFunction_Vectorcall
  56: <unknown>
  57: _PyObject_CallMethodIdObjArgs
  58: PyImport_ImportModuleLevelObject
  59: <unknown>
  60: <unknown>

  66: <unknown>
  67: _PyObject_CallMethodIdObjArgs
  68: PyImport_ImportModuleLevelObject
  69: _PyEval_EvalFrameDefault
  70: <unknown>
  71: PyEval_EvalCode
  72: <unknown>
  73: <unknown>
  74: _PyEval_EvalFrameDefault
  75: _PyFunction_Vectorcall
  76: _PyEval_EvalFrameDefault
  77: _PyFunction_Vectorcall
  78: _PyEval_EvalFrameDefault
  79: _PyFunction_Vectorcall
  80: _PyEval_EvalFrameDefault
  81: _PyFunction_Vectorcall
  82: _PyEval_EvalFrameDefault
  83: _PyFunction_Vectorcall
  84: <unknown>
  85: _PyObject_CallMethodIdObjArgs
  86: PyImport_ImportModuleLevelObject
  87: <unknown>
  88: <unknown>
  89: PyObject_Call
  90: _PyEval_EvalFrameDefault
  91: _PyFunction_Vectorcall
  92: _PyEval_EvalFrameDefault
  93: _PyFunction_Vectorcall
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/usr/local/lib/python3.10/site.py", line 604, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/local/lib/python3.10/site.py", line 387, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/lib/python3.10/site.py", line 226, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/lib/python3.10/site.py", line 186, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "/mitmproxy/venv/lib/python3.10/site-packages/pytest_cov/embed.py", line 74, in init
    cov.start()
  File "/mitmproxy/venv/lib/python3.10/site-packages/coverage/control.py", line 576, in start
    self._init_for_start()
  File "/mitmproxy/venv/lib/python3.10/site-packages/coverage/control.py", line 530, in _init_for_start
    self._inorout.configure(self.config)
  File "/mitmproxy/venv/lib/python3.10/site-packages/coverage/inorout.py", line 280, in configure
    modfile, path = file_and_path_for_module(pkg)
  File "/mitmproxy/venv/lib/python3.10/site-packages/coverage/inorout.py", line 122, in file_and_path_for_module
    spec = importlib.util.find_spec(modulename)
  File "/usr/local/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/mitmproxy/mitmproxy/addons/__init__.py", line 6, in <module>
    from mitmproxy.addons import clientplayback
  File "/mitmproxy/mitmproxy/addons/clientplayback.py", line 20, in <module>
    from mitmproxy.proxy import commands, events, layers, server
  File "/mitmproxy/mitmproxy/proxy/server.py", line 21, in <module>
    import mitmproxy_wireguard as wg
  File "/mitmproxy/venv/lib/python3.10/site-packages/mitmproxy_wireguard/__init__.py", line 1, in <module>
    from .mitmproxy_wireguard import *
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SetLoggerError(())
Traceback (most recent call last):
  File "/mitmproxy/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/mitmproxy/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/mitmproxy/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/mitmproxy/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/mitmproxy/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/mitmproxy/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/mitmproxy/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/mitmproxy/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/mitmproxy/venv/lib/python3.10/site-packages/xdist/looponfail.py", line 37, in pytest_cmdline_main
    looponfail_main(config)
  File "/mitmproxy/venv/lib/python3.10/site-packages/xdist/looponfail.py", line 47, in looponfail_main
    remotecontrol.loop_once()
  File "/mitmproxy/venv/lib/python3.10/site-packages/xdist/looponfail.py", line 117, in loop_once
    self.setup()
  File "/mitmproxy/venv/lib/python3.10/site-packages/xdist/looponfail.py", line 78, in setup
    self.gateway = self.initgateway()
  File "/mitmproxy/venv/lib/python3.10/site-packages/xdist/looponfail.py", line 70, in initgateway
    return execnet.makegateway("popen")
  File "/mitmproxy/venv/lib/python3.10/site-packages/execnet/multi.py", line 134, in makegateway
    gw = gateway_bootstrap.bootstrap(io, spec)
  File "/mitmproxy/venv/lib/python3.10/site-packages/execnet/gateway_bootstrap.py", line 101, in bootstrap
    bootstrap_import(io, spec)
  File "/mitmproxy/venv/lib/python3.10/site-packages/execnet/gateway_bootstrap.py", line 35, in bootstrap_import
    s = io.read(1)
  File "/mitmproxy/venv/lib/python3.10/site-packages/execnet/gateway_base.py", line 402, in read
    raise EOFError("expected %d bytes, got %d" % (numbytes, len(buf)))
EOFError: expected 1 bytes, got 0
```

At the same time, full test (tox -e) works and this code works too:
```
cd test/mitmproxy/contentviews/
pytest --cov mitmproxy.contentviews.mqtt --cov-report term-missing --looponfail test_mqtt.py
```

I wonder what and I doing wrong.

#### Steps to reproduce the behavior:

```
cd release/docker
wget https://snapshots.mitmproxy.org/8.1.1/mitmproxy-8.1.1-py3-none-any.whl
sudo docker build -t mitmproxy-dvp --build-arg MITMPROXY_WHEEL=mitmproxy-8.1.1-py3-none-any.whl .
sudo docker run -it --name mitmproxy-dvp -v $PWD/../..:/mitmproxy mitmproxy-dvp /bin/bash

cd /mitmproxy
python3 -m venv venv
venv/bin/pip install -e ".[dev]"
```

This fails:
```
cd test/mitmproxy/addons
/mitmproxy/venv/bin/pytest --cov mitmproxy.addons.anticache --cov-report term-missing --looponfail test_anticache.py```
```

This works:
```
cd test/mitmproxy/contentviews/
/mitmproxy/venv/bin/pytest --cov mitmproxy.contentviews.mqtt --cov-report term-missing test_mqtt.py
```

#### System Information

```
root@793fc5fbbbb9:/mitmproxy# venv/bin/mitmproxy --version
Mitmproxy: 9.0.0.dev
Python:    3.10.7
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Linux-5.15.0-48-generic-x86_64-with-glibc2.31
```

**Comment by mhils** [comment]
Thanks for the report, @abbbe!

@decathorpe, any idea what's going on here?

**Comment by decathorpe** [comment]
Does pytest run tests in parallel? I think tox runs them sequentially, if I remember correctly.
Reading the source code at the site of the crash, it looks like it fails to set the global logger, which should only happen if it's already been set up (which might happen if tests run in parallel?)

**Comment by decathorpe** [comment]
Either way, I just published a new version of mitmproxy_wireguard (v0.1.11) which makes failures to initialize the logger non-fatal, which should solve this problem (I hope).

Could you try again after either rebuilding the venv or updating this dependency, i.e. `venv/bin/pip install --upgrade mitmproxy_wireguard`?

**Comment by abbbe** [comment]
Have you observed the same behaviour in your branch before the patch?

**Comment by decathorpe** [comment]
The workaround wasn't pushed to the mitmproxy project directly, but one of its dependencies, mitmproxy_wireguard. You don't need to cherry-pick a commit, but only update this dependency in the venv (or delete the `venv` directory entirely and run the "reproducer" steps again).

**Comment by abbbe** [comment]
I am sorry for being slow, but could you please elaborate your code makes it way into my git working directory, if it is not in wireguard's git repository? And impacts the behaviour of the test scripts in 'main' branch?

**Comment by decathorpe** [comment]
The crash you reported in this ticket is not caused by code in mitmproxy, but by code in one of its dependencies (mitmproxy_wireguard), which was installed when you ran `venv/bin/pip install -e ".[dev]"`. If you remove the "venv" directory and re-trace your reproduction steps, you should get the new version that has the fix.

**Comment by abbbe** [comment]
Thank you for explanations.

I confirm the problem has disappeared, if I redo the reproduction steps I have described in the first message it works.
I suppose we can consider this issue closed.
