### ISSUE TITLE
Traceback (most recent call last):   File "/usr/bin/mitmproxy", line 33,on3.10/dist-packages/flask/__init__.py", line 21, in <module>     

### ISSUE THREAD

**Issue by akhatab54** [mitmproxy/mitmproxy#5616]
#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System InformationTraceback (most recent call last):
  File "/usr/bin/mitmproxy", line 33, in <module>
    sys.exit(load_entry_point('mitmproxy==8.1.1', 'console_scripts', 'mitmproxy')())
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/main.py", line 118, in mitmproxy
    from mitmproxy.tools import console
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/console/master.py", line 18, in <module>
    from mitmproxy import addons
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/__init__.py", line 15, in <module>
    from mitmproxy.addons import onboarding
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboardingapp/__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3/dist-packages/itsdangerous/__init__.py)

Paste the output of "mitmproxy --version" here.

**Comment by mhils** [comment]
Looks like you're using an outdated flask version while using an up-to-date itsdangerous version. You need to update your Python dependencies, this is not a mitmproxy bug.
