### ISSUE TITLE
11.4 broken with 2.7

### ISSUE THREAD

**Issue by Mila432** [mitmproxy/mitmproxy#567]
Finished processing dependencies for mitmproxy==0.11.4
root@server:/var/www/html/mitmproxy# mitmproxy
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.11.4', 'console_scripts', 'mitmproxy')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/main.py", line 6, in <module>
    from . import version, cmdline
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/cmdline.py", line 6, in <module>
    from . import filt, utils, version
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/filt.py", line 37, in <module>
    from .protocol.http import decoded
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/protocol/http.py", line 9, in <module>
    from netlib import http, tcp, http_status, http_cookies
ImportError: cannot import name http_cookies

**Comment by mhils** [comment]
For reference: If you install mitmproxy from master, you need netlib from master as well. Even better, you should use our dev instructions at https://github.com/mitmproxy/mitmproxy#hacking
