### ISSUE TITLE
Latest release broken on Ubuntu 22.04 - ImportError: libffi.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#5699]
#### Problem Description

https://askubuntu.com/questions/1286772/libffi-so-7-cannot-open-shared-object-file-no-such-file-or-directory

I don't think our users should do anything with their system to make the binary run, correct?

```
$ ./mitmdump 
Traceback (most recent call last):
  File "mitmdump", line 3, in <module>
  File "mitmproxy/tools/main.py", line 131, in mitmdump
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "mitmproxy/tools/dump.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "mitmproxy/addons/__init__.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "mitmproxy/addons/cut.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyperclip/__init__.py", line 52, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
[50935] Failed to execute script 'mitmdump' due to unhandled exception!
```

#### Steps to reproduce the behavior:

1. `mitmdump`

Repros in a clean `docker run --rm -it ubuntu:22.04` as well

#### System Information

9.0.0 just downloaded (I cannot run `mitmdump --version` as it doesn't launch)

**Comment by mhils** [comment]
Huh, thanks for raising this. The compiled binary _does_ include `libffi.so.7.1.0`, so I'm not sure what exactly is broken here.

**Comment by mhils** [comment]
pyinstaller 5.1 with Python 3.10 works. Let's see who's at fault here.
