### ISSUE TITLE
Release 9.0.0 broken

### ISSUE THREAD

**Issue by maarten-v** [mitmproxy/mitmproxy#5700]
#### Problem Description
When pulling the latest docker image with version 9.0.0 it's not possible anymore to see the requests, and requests are not successfull  anymore.

#### Steps to reproduce the behavior:
1. update to latest docker image with version 9.0.0

#### System Information
docker with image  9.0.0

Debug log:

```
[13:26:05.031] HTTP(S) proxy listening at *:8080.
[13:26:05.031] Web server listening at http://0.0.0.0:8081/
[13:26:05.206] Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/addons/tlsconfig.py", line 301, in running
    self.configure("confdir")  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/addons/tlsconfig.py", line 308, in configure
    self.certstore = certs.CertStore.from_store(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/certs.py", line 358, in from_store
    cls.create_store(path, basename, key_size)
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/certs.py", line 407, in create_store
    (path / f"{basename}-ca.pem").write_bytes(
  File "/usr/local/lib/python3.11/pathlib.py", line 1067, in write_bytes
    with self.open(mode='wb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/mitmproxy/.mitmproxy/mitmproxy-ca.pem'
[13:26:05.208] No web browser found. Please open a browser and point it to http://0.0.0.0:8081/
[13:26:17.523][172.20.0.11:34088] client connect
[13:26:17.553][172.20.0.11:34088] server connect hidden.nl:443 (87.233.92.107:443)
[13:26:17.641] Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/addons/tlsconfig.py", line 152, in tls_start_client
    entry = self.get_cert(tls_start.context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/addons/tlsconfig.py", line 380, in get_cert
    return self.certstore.get_cert(altnames[0], altnames, organization)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_cert'
[13:26:17.641][172.20.0.11:34088] No TLS context was provided, failing connection.
[13:26:17.643][172.20.0.11:34088] client disconnect
[13:26:17.644][172.20.0.11:34088] server disconnect hidden.nl:443 (87.233.92.107:443)
```

**Comment by mhils** [comment]
How are you invoking docker? The problem is here: 
```
PermissionError: [Errno 13] Permission denied: '/home/mitmproxy/.mitmproxy/mitmproxy-ca.pem'
```

**Comment by maarten-v** [comment]
this is in my docker compose file:

   ```
 mitmproxy:
      image: mitmproxy/mitmproxy
      container_name: mitmproxy
      volumes:
        - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
      ports:
        - "8081:8081"
        - "8080"
      command: mitmweb --web-host 0.0.0.0
      networks:
        - traefik
```

the linking of the the homefolder is something I just added to try if that fixes it, it didn't.
Maybe importing the certificates is mandatory now? But that changed then from the previous version 8.1.1.

**Comment by mhils** [comment]
I'm traveling this week and can't investigate deeply, but this looks like a problem due to https://github.com/mitmproxy/mitmproxy/commit/8023b224985d5853a624ebd4a1ff7b8d79ece433. Not sure why that doesn't work here.

**Comment by maarten-v** [comment]
I didn't have that .mitmproxy folder locally, but after adding the link it was created by docker I guess, with owner root:root.
I changed the ownership to myself and now it works.
So I can get it to work again, but it's a change from the previous version where it wasn't necessary.

**Comment by mhils** [comment]
#5702 fixes this. We'll likely ship a patch release for OpenSSL tomorrow anyways. :)
