### ISSUE TITLE
mitmproxy 9.0.0 crashes on startup:  Expected collections.abc.Sequence[str] for mode, but got <class 'str'>.

### ISSUE THREAD

**Issue by hazcod** [mitmproxy/mitmproxy#5712]
#### Problem Description

mitmproxy 9.0.0 on python:slim-bullseye Docker image seems to crash with the following error log:

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 143, in mitmdump
    run(dump.DumpMaster, cmdline.mitmdump, args, extra)
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 120, in run
    return asyncio.run(main())
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 78, in main
    optmanager.load_paths(
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/optmanager.py", line 564, in load_paths
    load(opts, txt)
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/optmanager.py", line 546, in load
    opts.update_defer(**data)
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/optmanager.py", line 237, in update_defer
    unknown = self.update_known(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/optmanager.py", line 232, in update_known
    self._options[k].set(v)
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/optmanager.py", line 58, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/utils/typecheck.py", line 45, in check_option_type
    raise e
```

Configuration:
```
mode: regular

websocket: true
stream_websockets: false

block_global: false
block_private: false

console_eventlog_verbosity: debug
termlog_verbosity: debug

verbose: true

flow_detail: 0
console_mouse: false
command_history: false
relax_http_form_validation: true

http2: true
http2_priority: false

rawtcp: false

ciphers_client: ALL
ciphers_server: ALL

certs: ["mitmproxy-ca.pem"]
key_size: 2048
```

#### Steps to reproduce the behavior:
1. Run mitmproxy 9.0.0 via `/usr/local/bin/mitmdump --set confdir=/etc/mitmproxy/`.

#### System Information
```
Mitmproxy: 9.0.0
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.49-linuxkit-aarch64-with-glibc2.31
```

**Comment by mhils** [comment]
You've cut off the error message here which would be helpful. It looks like
one of the options in your config has an invalid type now. The only thing
we've changed is that mode expects a sequence of strings, so it's very
likely that. We may need to improve the error message for this, but you
left it out so it's hard to tell. :)

**Comment by hazcod** [comment]
@mhils That was it! Thanks.
Can we include that in the release docs?

**Comment by mhils** [comment]
Done!
