### ISSUE TITLE
mitmproxy has crashed.

### ISSUE THREAD

**Issue by yrousan** [mitmproxy/mitmproxy#5713]
TypeError: t.join is not a function
    at Footer (http://127.0.0.1:8081/static/app.js:67:13240)
    at Ch (http://127.0.0.1:8081/static/app.js:5:55364)
    at li (http://127.0.0.1:8081/static/app.js:5:65205)
    at ck (http://127.0.0.1:8081/static/app.js:9:9934)
    at bk (http://127.0.0.1:8081/static/app.js:9:1017)
    at ak (http://127.0.0.1:8081/static/app.js:9:923)
    at Tj (http://127.0.0.1:8081/static/app.js:9:765)
    at Lj (http://127.0.0.1:8081/static/app.js:7:11182)
    at http://127.0.0.1:8081/static/app.js:5:40449
    at Rt.unstable_runWithPriority (http://127.0.0.1:8081/static/app.js:1:12961)

Component Stack:
    at Footer (http://127.0.0.1:8081/static/app.js:67:12856)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:69:3070)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:58:5505)
    at Provider (http://127.0.0.1:8081/static/app.js:58:2818)

**Comment by mhils** [comment]
Please clear your browser cache and use the latest mitmproxy version.
