### ISSUE TITLE
Crash in libmproxy

### ISSUE THREAD

**Issue by cppisking** [mitmproxy/mitmproxy#574]
Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\libmproxy\proxy\server.py", line 99, in handle
        protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
      File "C:\Python27\lib\site-packages\libmproxy\protocol\http.py", line 982, in handle_messages
        while self.handle_flow():
      File "C:\Python27\lib\site-packages\libmproxy\protocol\http.py", line 1055, in handle_flow
        ret = self.process_request(flow, req)
      File "C:\Python27\lib\site-packages\libmproxy\protocol\http.py", line 1248, in process_request
        return self.process_connect_request(self.c.server_conn.address)
      File "C:\Python27\lib\site-packages\libmproxy\protocol\http.py", line 1395, in process_connect_request
        self.c.establish_ssl(server=True, client=True)
      File "C:\Python27\lib\site-packages\libmproxy\proxy\server.py", line 215, in establish_ssl
        chain_file=chain_file
      File "C:\Python27\lib\site-packages\libmproxy\proxy\connection.py", line 66, in convert_to_ssl
        tcp.BaseHandler.convert_to_ssl(self, *args, **kwargs)
      File "C:\Python27\lib\site-packages\netlib\tcp.py", line 428, in convert_to_ssl
        ctx = self._create_ssl_context(cert, key, **sslctx_kwargs)
      File "C:\Python27\lib\site-packages\netlib\tcp.py", line 411, in _create_ssl_context
        ctx.use_privatekey(key)
      File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 680, in use_privatekey
        self._raise_passphrase_exception()
      File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 640, in _raise_passphrase_exception
        _raise_current_error()
      File "C:\Python27\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    Error: [('SSL routines', 'SSL_SET_PKEY', 'unknown certificate type')]

Unfortunately I don't have much more useful insight to provide here.  This happened while I was connected to a server I have using libmproxy (not using the inline scripts approach).  The certificate is correctly installed on my phone, and I've been using everything successfully for some time now and it was an all of a sudden kind of thing that I'm unable to make happen again.

**Comment by mhils** [comment]
Thanks for the report. We need some more insight what could have triggered this. Can you somehow reproduce it consistently? Any particular website/combo/...?

**Comment by cppisking** [comment]
I will keep trying, but I've only seen it one time, and at the time I wasn't logging the request URLs.  So right now I don't know what it was.  I will keep an eye out and see if I can catch it with better logging.

**Comment by mhils** [comment]
Ok, closing until then. Thanks!
