### ISSUE TITLE
problems after upgrading mac , and then upgrading mitmproxy

### ISSUE THREAD

**Issue by gg4u** [mitmproxy/mitmproxy#5773]
I had mitmproxy 8.1.1 installed and working fine.
I had to update mac OS (Big sur).

After that:
- launching mimtweb by clicking on the file, it was working ok, but launching mitmproxy from terminal, was giving error:

```

(base) MacBook-Pro:mitmproxy-8.1.1-osx gg4u$ mitmproxy --ssl-insecure
Traceback (most recent call last):
  File "/Users/XXX/Sites/miniconda3/bin/mitmproxy", line 5, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/tools/main.py", line 9, in <module>
    from mitmproxy import exceptions, master
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/master.py", line 5, in <module>
    from mitmproxy import addonmanager, hooks
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/addonmanager.py", line 11, in <module>
    from mitmproxy import hooks
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/hooks.py", line 7, in <module>
    import mitmproxy.flow
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/flow.py", line 6, in <module>
    from mitmproxy import connection
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/connection.py", line 8, in <module>
    from mitmproxy import certs
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/mitmproxy/certs.py", line 17, in <module>
    import OpenSSL
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 2): Library not loaded: @rpath/libssl.1.1.dylib
  Referenced from: /Users/XXX/Sites/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
  Reason: image not found
(base) MacBook-Pro:mitmproxy-8.1.1-osx gg4u$ 


```
## What I did:
tried to update cryptography module:
`pip3 install --upgrade cryptography`
but :
```

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mitmproxy 8.1.1 requires cryptography<38,>=36, but you have cryptography 38.0.4 which is incompatible.
mitmproxy 8.1.1 requires wsproto<1.2,>=1.0, but you have wsproto 1.2.0 which is incompatible.


```

So I updated mitmproxy:
```

pip3 install --upgrade mitmproxy

mitmproxy --version
Mitmproxy: 9.0.1
Python:    3.9.13
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-11.6.7-x86_64-i386-64bit
```

But now I cannot launch it:
```

mitmweb

[Errno 48] HTTP(S) proxy failed to listen on *:8080 with [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
Try specifying a different port by using `--mode regular@8081`.

```
```

mitmproxy
Error on startup: [Errno 48] HTTP(S) proxy failed to listen on *:8080 with [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
Try specifying a different port by using `--mode regular@8081`.
```

**Comment by mhils** [comment]
> Error on startup: [Errno 48] HTTP(S) proxy failed to listen on *:8080 with [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use


This message states that you already have an application listening on port 8080. You can go find and kill that application, or simply restart your machine.
