### ISSUE TITLE
An 'AttributeError' error is raised when attempting to inject a WebSocket payload

### ISSUE THREAD

**Issue by MaDKaTZe** [mitmproxy/mitmproxy#5808]
#### Problem Description

The following error is raised when trying to inject a payload to the client for a WebSocket flow:

```
warn: [15:49:35.042] Cannot inject WebSocket messages into non-WebSocket flows.
error: [15:49:35.043] Traceback (most recent call last):

  File "asyncio/events.py", line 80, in _run
  File "urwid/raw_display.py", line 416, in <lambda>
  File "urwid/raw_display.py", line 515, in parse_input
  File "urwid/main_loop.py", line 412, in _update
  File "urwid/main_loop.py", line 513, in process_input
  File "mitmproxy/tools/console/window.py", line 304, in keypress
  File "urwid/container.py", line 1123, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 203, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 145, in keypress
  File "mitmproxy/tools/console/statusbar.py", line 174, in prompt_execute
  File "mitmproxy/tools/console/statusbar.py", line 110, in execute_command
  File "mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
  File "mitmproxy/command.py", line 285, in execute
  File "mitmproxy/command.py", line 273, in call_strings
  File "mitmproxy/command.py", line 144, in call
  File "mitmproxy/command.py", line 315, in wrapper
  File "mitmproxy/addons/proxyserver.py", line 293, in inject_websocket
  File "mitmproxy/addons/proxyserver.py", line 273, in inject_event

AttributeError: 'str' object has no attribute 'client_conn'
```

#### Steps to reproduce the behavior:

1. Try executing the following command, whilst focused on a flow: `inject.websocket @focus true 'something' true`

#### System Information

```
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.0-56-generic-x86_64-with-glibc2.35
```

**Comment by Prinzhorn** [comment]
I don't know what exactly is going on, but the literal string `@focus` makes it into the command instead of the flow instance.

**Comment by themavik** [comment]
Fix in #8141.
