### ISSUE TITLE
Impossible to use server replay and guarantee proxy will not go outside of recorded file?

### ISSUE THREAD

**Issue by xrd** [mitmproxy/mitmproxy#581]
I'm confused if mitmdump/mitmproxy supports recording to a file, using a recorded file to replay, but guaranteeing that any additional requests outside of the recording list will not be made to live servers.

I had assumed the ` -k, --kill            Kill extra requests during replay.` switch would prevent extra requests, but I think I am wrong (or am using it incorrectly).

My use case: I want to use mitmdump as an automated testing tool for mobile applications. I'd like to start mitmdump as a proxy, setup the proxy on the mobile device, do a run with real request recorded to a file, then restart mitmdump in replay mode, and guarantee any additional requests made by the mobile device client never hit the internet. This allows me to run my automated tests without worrying about doing anything improper, even if I am running against a production environment.

Is this type of usage supported? 

The commands I used:

```
$ mitmdump -w sample_recording
....
$ mitmdump -k -S sample_recording
...
```

**Comment by mhils** [comment]
Hi @xrd,

this is perfectly supported. You may see some outgoing tcp connections, but mitmproxy won't send any requests upstream (this is a technical limitation we're trying to overcome).

Cheers,
Max

**Comment by ntulele** [comment]
Hi @mhils , 
I have essentially the identical use case that @xrd described.  Could you elaborate more re. the nature of the extraneous calls?    
I'm definitely seeing requests made upstream, despite the --kill flag.  My working theory is that the calls are all associated with establishing the TLS/SSL handshaking/intermeditation (which I'd expect to be unnecessary when --kill is specified), but I need to be able to confirm that.   

Here are some details from my investigation thus far:
* My recording/playback use case begins with mitmdump-proxied browser page load of an HTTPS URL.   
* If, and only if, I block all outbound traffic from mitmproxy/mitmdump (using Little Snitch), the initial URL load  in the browser (which is being proxied) fails immediately.  Here's the command and traceback:
```python
$ mitmdump -S unitedsmDirect -k --replay-ignore-content --port 1234 -ddd -v
127.0.0.1:52090: clientconnect
127.0.0.1:52090: request
  -> Request(CONNECT unitedsm.taleo.net:443)
127.0.0.1:52090: Set new server address: ('unitedsm.taleo.net', 443)
127.0.0.1:52090: serverconnect
  -> unitedsm.taleo.net:443
127.0.0.1:52090: Establish TLS with client
127.0.0.1:52090: ALPN for client: http/1.1
127.0.0.1:52090: ProtocolException('Server connection to unitedsm.taleo.net:443 failed: Error connecting to "unitedsm.taleo.net": [Errno 64] Host is down',)
127.0.0.1:52090: Traceback (most recent call last):
  File "site-packages/mitmproxy/proxy/server.py", line 121, in handle
  File "site-packages/mitmproxy/proxy/modes/http_proxy.py", line 11, in __call__
  File "site-packages/mitmproxy/protocol/tls.py", line 358, in __call__
  File "site-packages/mitmproxy/protocol/http1.py", line 67, in __call__
  File "site-packages/mitmproxy/protocol/http.py", line 171, in __call__
  File "site-packages/mitmproxy/protocol/http.py", line 263, in handle_regular_mode_connect
  File "site-packages/mitmproxy/protocol/tls.py", line 353, in __call__
  File "site-packages/mitmproxy/protocol/tls.py", line 435, in _establish_tls_with_client_and_server
  File "site-packages/mitmproxy/protocol/tls.py", line 428, in _establish_tls_with_client_and_server
  File "site-packages/mitmproxy/protocol/tls.py", line 384, in connect
  File "site-packages/mitmproxy/protocol/base.py", line 190, in connect
  File "site-packages/mitmproxy/protocol/base.py", line 181, in connect
  File "site-packages/mitmproxy/models/connections.py", line 164, in connect
  File "site-packages/netlib/tcp.py", line 709, in connect
ProtocolException: Server connection to unitedsm.taleo.net:443 failed: Error connecting to "unitedsm.taleo.net": [Errno 64] Host is down

127.0.0.1:52090: clientdisconnect
```

**Comment by ntulele** [comment]
Hi @mhils , 
I have essentially the identical use case that @xrd described.  Could you elaborate more re. the nature of the extraneous calls?    
I'm definitely seeing requests made upstream, despite the --kill flag.  My working theory, seemingly supported by the traceback below, is that the calls are all associated with establishing the TLS/SSL handshaking/intermeditation (which I'd expect to be unnecessary when --kill is specified).   

_Are you able to confirm that the only requests during playback with --kill are for the TSL/SSL handshake/spoofing setup?_   

Where in the code might I disable these outbound calls? 
(My though is that I could then insert a check for the --kill flag to control this behavior, since there shouldn't be any outbound requests when that's set)

Here are some details from my investigation thus far:
* My recording/playback use case begins with an mitmdump-proxied browser page load of an HTTPS URL:  
* If, and only if, I block all outbound traffic from mitmproxy/mitmdump (using Little Snitch), the initial https call by the browser fails immediately.  

Here's the command and traceback (where I've replaced my real endpoint with "subdomain.domain")

```bash
$ mitmdump -S subdomainDirect -k --replay-ignore-content --port 1234 -ddd -v
127.0.0.1:52090: clientconnect
127.0.0.1:52090: request
  -> Request(CONNECT subdomain.domain.net:443)
127.0.0.1:52090: Set new server address: ('subdomain.domain.net', 443)
127.0.0.1:52090: serverconnect
  -> subdomain.domain.net:443
127.0.0.1:52090: Establish TLS with client
127.0.0.1:52090: ALPN for client: http/1.1
127.0.0.1:52090: ProtocolException('Server connection to subdomain.domain.net:443 failed: Error connecting to "subdomain.domain.net": [Errno 64] Host is down',)
127.0.0.1:52090: Traceback (most recent call last):
  File "site-packages/mitmproxy/proxy/server.py", line 121, in handle
  File "site-packages/mitmproxy/proxy/modes/http_proxy.py", line 11, in __call__
  File "site-packages/mitmproxy/protocol/tls.py", line 358, in __call__
  File "site-packages/mitmproxy/protocol/http1.py", line 67, in __call__
  File "site-packages/mitmproxy/protocol/http.py", line 171, in __call__
  File "site-packages/mitmproxy/protocol/http.py", line 263, in handle_regular_mode_connect
  File "site-packages/mitmproxy/protocol/tls.py", line 353, in __call__
  File "site-packages/mitmproxy/protocol/tls.py", line 435, in _establish_tls_with_client_and_server
  File "site-packages/mitmproxy/protocol/tls.py", line 428, in _establish_tls_with_client_and_server
  File "site-packages/mitmproxy/protocol/tls.py", line 384, in connect
  File "site-packages/mitmproxy/protocol/base.py", line 190, in connect
  File "site-packages/mitmproxy/protocol/base.py", line 181, in connect
  File "site-packages/mitmproxy/models/connections.py", line 164, in connect
  File "site-packages/netlib/tcp.py", line 709, in connect
ProtocolException: Server connection to subdomain.domain.net:443 failed: Error connecting to "subdomain.domain.net": [Errno 64] Host is down                                    

127.0.0.1:52090: clientdisconnect
```

Thank you!!

**Comment by mhils** [comment]
@ntulele, this looks like you just want `--no-upstream-cert`?

**Comment by ntulele** [comment]
I didn't see that option!  (argh...)    
It worked!
Thank you very much for the quick reply.
