### ISSUE TITLE
Problems in Windows 32bit

### ISSUE THREAD

**Issue by choijaehyung-c** [mitmproxy/mitmproxy#5821]
#### Problem Description
Cannot close a running event loop (python,windows 32bit)

#### Steps to reproduce the behavior:
1. The code works on Windows 64bit, but an error occurs on 32bit (it was built with the correct version in the 32bit environment)
2. 
code : {
```
import asyncio
import sys
from mitmproxy import options
from mitmproxy.tools import dump
from time import sleep as tSleep

class RequestLogger:
    def request(self, flow):
        print(flow.request)
    
    def response(self, flow):
        print(flow.response)

async def start_proxy(host, port):
    opts = options.Options(listen_host=host, listen_port=port)

    master = dump.DumpMaster(
        opts,
        with_termlog=False,
        with_dumper=False,
    )
    master.addons.add(RequestLogger())
    
    await master.run()
    return master


if __name__ == '__main__':
    host="127.0.0.1"
    port=8899
    asyncio.run(start_proxy(host, port))
```
}    

error : {
Traceback (most recent call last):
  File "test3333.py", line 29, in <module>
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "test3333.py", line 23, in start_proxy
  File "mitmproxy\master.py", line 108, in run
  File "mitmproxy\master.py", line 96, in run_loop
  File "asyncio\selector_events.py", line 88, in close
RuntimeError: Cannot close a running event loop
[17168] Failed to execute script 'test3333' due to unhandled exception!
}

guess : {

https://stackoverflow.com/questions/51862318/runtimeerror-cannot-close-a-running-event-loop
}

3. 
guess point on 64bit (from mitmproxy import master): {
    ```
async def run(self) -> None:
        old_handler = self.event_loop.get_exception_handler()
        self.event_loop.set_exception_handler(self._asyncio_exception_handler)
        try:
            self.should_exit.clear()

            if ec := self.addons.get("errorcheck"):
                await ec.shutdown_if_errored()
            if ps := self.addons.get("proxyserver"):
                await ps.setup_servers()
            if ec := self.addons.get("errorcheck"):
                await ec.shutdown_if_errored()
                ec.finish()
            await self.running()
            try:
                await self.should_exit.wait()
            finally:
                # .wait might be cancelled (e.g. by sys.exit)
                await self.done()
        finally:
            self.event_loop.set_exception_handler(old_handler)
```
}
guess point on 32bit (from mitmproxy import master): {
    ```
def run_loop(self, loop):
        self.start()
        asyncio.ensure_future(self.running())

        exc = None
        try:
            loop()
        except Exception:  # pragma: no cover
            exc = traceback.format_exc()
        finally:
            if not self.should_exit.is_set():  # pragma: no cover
                self.shutdown()
            loop = asyncio.get_event_loop()
            tasks = asyncio.all_tasks(loop) if sys.version_info >= (3, 7) else asyncio.Task.all_tasks(loop)
            for p in tasks:
                p.cancel()
            loop.close() <<<

        if exc:  # pragma: no cover
            print(exc, file=sys.stderr)
            print("mitmproxy has crashed!", file=sys.stderr)
            print("Please lodge a bug report at:", file=sys.stderr)
            print("\thttps://github.com/mitmproxy/mitmproxy", file=sys.stderr)

        self.addons.trigger("done")

    def run(self, func=None):
        loop = asyncio.get_event_loop()
        self.run_loop(loop.run_forever)

```}


#### System Information
64bit : mitmproxy --9.0.1
32bit : mitmproxy --5.3.0

###P.S.
please help me T_T ( like TWICE TT ) that python code..
OR
Is there a Windows 32bit version of "mitmdump.exe"?

**Comment by mhils** [comment]
We only support 64 bit Windows, sorry.

**Comment by choijaehyung-c** [comment]
Does the 32bit 5.3.0 version no longer work?

**Comment by choijaehyung-c** [comment]
> We only support 64 bit Windows, sorry.

Does the 32bit 5.3.0 version no longer work?
