### ISSUE TITLE
Using script with wireguard mode crashes mitmproxy

### ISSUE THREAD

**Issue by SapiensAnatis** [mitmproxy/mitmproxy#5855]
#### Problem Description
I am using a script to redirect traffic to a local dev server. It works fine on regular mode.

I wanted to try out wireguard mode, but my script to redirect the requests no longer works, producing the following error.

(I've heard you can use a custom DNS over wireguard to achieve this, but I didn't have much luck with acrylic and dnsmasq is Linux-only)

There's probably something wrong with my script, but I still don't think a crash is the intended result.

```
[python] Received request to 48cc81cdb8de30e061928f56e9bd4b4d.baas.nintendo.com
[python] Request matched regex, redirecting
[20:49:50.321][10.0.0.1:40764] mitmproxy has crashed!
['Traceback (most recent call last):\n', '  File "C:\\Users\\jay0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\mitmproxy\\proxy\\server.py", line 275, in handle_connection\n    await self.drain_writers()\n', '  File "C:\\Users\\jay0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\mitmproxy\\proxy\\server.py", line 310, in drain_writers\n    for transport in self.transports.values():\n', 'RuntimeError: dictionary changed size during iteration\n']
[20:49:50.322][10.0.0.1:40764] client disconnect
[20:49:50.322][10.0.0.1:40764] error establishing server connection: client disconnected
[20:49:50.325][10.0.0.1:40764] server disconnect 172.217.169.81:443
[20:49:54.948][10.0.0.1:57058] client connect
[20:49:55.947][10.0.0.1:57060] client connect
[20:49:55.949][10.0.0.1:1201] client connect
[20:49:55.972][10.0.0.1:52026] client connect
[20:49:56.211][10.0.0.1:52026] server connect 13.112.235.88:443
[python] Received request to omotenashi.cygames.jp
[python] Request matched regex, redirecting
[20:49:56.698][10.0.0.1:52026] mitmproxy has crashed!
['Traceback (most recent call last):\n', '  File "C:\\Users\\jay0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\mitmproxy\\proxy\\server.py", line 275, in handle_connection\n    await self.drain_writers()\n', '  File "C:\\Users\\jay0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\mitmproxy\\proxy\\server.py", line 310, in drain_writers\n    for transport in self.transports.values():\n', 'RuntimeError: dictionary changed size during iteration\n']
[20:49:56.699][10.0.0.1:52026] client disconnect
[20:49:56.700][10.0.0.1:52026] error establishing server connection: client disconnected
[20:49:56.702][10.0.0.1:52026] server disconnect 13.112.235.88:443
[20:49:56.949][10.0.0.1:57058] error establishing server connection: [WinError 1225] The remote computer refused the network connection
[20:49:56.949][10.0.0.1:57058] client disconnect
[20:49:57.545][10.0.0.1:57064] client connect
[20:49:57.950][10.0.0.1:57060] error establishing server connection: [WinError 1225] The remote computer refused the network connection
[20:49:57.951][10.0.0.1:57060] client disconnect
[20:49:57.952][10.0.0.1:52030] client connect
[20:49:58.212][10.0.0.1:52030] server connect 13.112.235.88:443
[python] Received request to omotenashi.cygames.jp
[python] Request matched regex, redirecting
[20:49:58.744][10.0.0.1:52030] mitmproxy has crashed!
['Traceback (most recent call last):\n', '  File "C:\\Users\\jay0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\mitmproxy\\proxy\\server.py", line 275, in handle_connection\n    await self.drain_writers()\n', '  File "C:\\Users\\jay0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\mitmproxy\\proxy\\server.py", line 310, in drain_writers\n    for transport in self.transports.values():\n', 'RuntimeError: dictionary changed size during iteration\n']
```

#### Steps to reproduce the behavior:
1. Use the following script:
https://gist.github.com/SapiensAnatis/3d034e652ba41b6eea5d1c2b47316b27
2. Attempt to connect to a domain that matches one of the regexes (you may need to change these)
3. Crash?

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 9.0.1
Python:    3.10.6
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.22623-SP0

**Comment by mhils** [comment]
Thanks for the report! This should already be fixed on main! :)
