### ISSUE TITLE
AssertionError: Unexpected event: <AlternativeServiceAvailable origin:https://kaspersky.com:443, field_value:h3=":443">

### ISSUE THREAD

**Issue by JannisBush** [mitmproxy/mitmproxy#5880]
#### Problem Description
Mitmproxy crashes for certain responses, probably related to HTTP3.

#### Steps to reproduce the behavior:
1. Run `mitmproxy`
2. Run `curl --proxy http://localhost:8080 -k https://kaspersky.com`
3. Observe error in mitmproxy
```
error: 127.0.0.1:62672: mitmproxy has crashed!
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/server.py", line 331, in server_event
    for command in layer_commands:
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 167, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 256, in handle_event
    yield from self._handle(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 167, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 846, in _handle_event
    yield from self.event_to_child(stream, event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 899, in event_to_child
    for command in child.handle_event(event):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 167, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 743, in passthrough
    for command in self.child_layer.handle_event(event):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 167, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
    yield from self.event_to_child(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/tls.py", line 408, in event_to_child
    yield from super().event_to_child(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 167, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
    yield from self.event_to_child(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 258, in handle_event
    yield from super().handle_event(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 128, in handle_event
    yield from self.__continue(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 219, in __continue
    yield from self.__process(command_generator, event.reply)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 206, in __process
    command = next(command_generator)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 275, in _handle_event
    yield from self._ask()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 289, in _ask
    yield from self.layer.handle_event(e)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
    command = command_generator.send(send)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 890, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 899, in event_to_child
    for command in child.handle_event(event):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 143, in handle_event
    command = command_generator.send(send)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http2.py", line 440, in _handle_event
    for cmd in self._handle_event2(event):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http2.py", line 513, in _handle_event2
    yield from super()._handle_event(event)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http2.py", line 175, in _handle_event
    if (yield from self.handle_h2_event(h2_event)):
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http2.py", line 572, in handle_h2_event
    return (yield from super().handle_h2_event(event))
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http2.py", line 265, in handle_h2_event
    raise AssertionError(f"Unexpected event: {event!r}")
AssertionError: Unexpected event: <AlternativeServiceAvailable origin:https://kaspersky.com:443, field_value:h3=":443">
```

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 8.1.1
Python:    3.10.6
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-13.1-arm64-arm-64bit
```

**Comment by sujaldev** [comment]
> probably related to HTTP3.

Not sure but I think this is an issue with HTTP2, probably because kaspersky.com sets an `alt-svc` header in the response and there is no handling for that yet. I'll work on this.

**Comment by mhils** [comment]
Thanks! As the first fix we probably just want to swallow that so that it doesn't crash + add a test.
