### ISSUE TITLE
 Traceback (most recent call last):

### ISSUE THREAD

**Issue by a639612262010** [mitmproxy/mitmproxy#5939]
![image](https://user-images.githubusercontent.com/61104521/220069201-288b71ea-fff0-497b-9009-a2c27ff6e37e.png)
Traceback (most recent call last):

  File "C:\Users\63147\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)

  File "C:\Users\63147\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/issues/5581

Please fill out the issue template that is presented when you create a new bug report (version, steps to reproduce)

**Comment by Black-Face-Kk** [comment]
Reproduce the process
1: When the browser is proxied from port 8080, this problem will occur if the link to the visited website cannot be accessed.
