### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by lila202212** [mitmproxy/mitmproxy#5945]
Traceback (most recent call last):

  File "C:\Python\lib\asyncio\windows_events.py", line 571, in accept_coro
    await future

  File "C:\Python\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)

  File "C:\Python\lib\asyncio\windows_events.py", line 560, in finish_accept
    ov.getresult()

OSError: [WinError 64] 指定的网络名不再可用。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
Traceback (most recent call last):

  File "C:\Python\lib\asyncio\proactor_events.py", line 819, in loop
    conn, addr = f.result()

  File "C:\Python\lib\asyncio\windows_events.py", line 571, in accept_coro
    await future

  File "C:\Python\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)

  File "C:\Python\lib\asyncio\windows_events.py", line 560, in finish_accept
    ov.getresult()

OSError: [WinError 64] 指定的网络名不再可用。

**Comment by Prinzhorn** [comment]
Please fill out the issue template that is presented when you create a new bug report (version, steps to reproduce)
