### ISSUE TITLE
UI crash after deleting a few flows

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#595]
```
➜  ~  mitmproxy --version
mitmproxy 0.12.0
```

```
➜  ~  mitmproxy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 457, in run
    self.loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/console/window.py", line 21, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 350, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/local/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 167, in keypress
    self.state.delete_flow(self.flow)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 98, in delete_flow
    ret = flow.State.delete_flow(self, f)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/flow.py", line 556, in delete_flow
    self.flows._remove(f)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/flow.py", line 470, in _remove
    self._list.remove(f)
ValueError: list.remove(x): x not in list

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

**Comment by Fuzion24** [comment]
I think this is a dupe of #592

**Comment by cortesi** [comment]
Thanks for reporting this. I'll do a minor point release to address this in the next few days.
