### ISSUE TITLE
Failed to execute script 'mitmweb' due to unhandled exception!

### ISSUE THREAD

**Issue by parisa-hr** [mitmproxy/mitmproxy#5956]
#### Problem Description
Hi I cant run and use this app, How should I use it?

Traceback (most recent call last):
  File "mitmproxy/tools/web/master.py", line 100, in running
  File "tornado/tcpserver.py", line 183, in listen
  File "tornado/netutil.py", line 162, in bind_sockets
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmweb", line 4, in <module>
  File "mitmproxy/tools/main.py", line 150, in mitmweb
  File "mitmproxy/tools/main.py", line 120, in run
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 650, in run_until_complete
  File "mitmproxy/tools/main.py", line 117, in main
  File "mitmproxy/master.py", line 59, in run
  File "mitmproxy/tools/web/master.py", line 105, in running
OSError: [Errno 98] Web server failed to listen on 127.0.0.1:8081 with [Errno 98] Address already in use
Try specifying a different port by using `--set web_port=8082`.
[170030] Failed to execute script 'mitmweb' due to unhandled exception!

![image](https://user-images.githubusercontent.com/44742050/221840169-a7a451bf-06a6-4d54-a5fb-6aa6f7e64084.png)

#### System Information
Paste the output of "mitmproxy --version" here.

mitmproxy-9.0.1-linux

Ubuntu 20.04
Python 3.8.10

**Comment by mhils** [comment]
Please check the error message: 

> OSError: [Errno 98] Web server failed to listen on 127.0.0.1:8081 with [Errno 98] Address already in use
Try specifying a different port by using --set web_port=8082.
