### ISSUE TITLE
a crash in mitmweb ui 

### ISSUE THREAD

**Issue by namelin2** [mitmproxy/mitmproxy#6000]
#### Steps to reproduce the behavior:
1. start mitmweb --mode sock5
2. and wait log
3. crash

#### System Information
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (http://127.0.0.1:8081/static/app.js:7:8533)
    at Object.enqueueSetState (http://127.0.0.1:8081/static/app.js:5:44513)
    at kc.setState (http://127.0.0.1:8081/static/app.js:1:3945)
    at t.onViewportUpdate (http://127.0.0.1:8081/static/app.js:58:46527)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:45824)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:43879)
    at Yi (http://127.0.0.1:8081/static/app.js:7:1828)
    at dk (http://127.0.0.1:8081/static/app.js:9:5215)
    at Mt.unstable_runWithPriority (http://127.0.0.1:8081/static/app.js:1:12961)
    at gg (http://127.0.0.1:8081/static/app.js:5:40220)

Component Stack:
    at AutoScrollWrapper (http://127.0.0.1:8081/static/app.js:58:43512)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:47480)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3048)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)

**Comment by Prinzhorn** [comment]
What version of mitmproxy and browser?

**Comment by Prinzhorn** [comment]
I assume this is https://github.com/mitmproxy/mitmproxy/issues/5198 , feel free to re-open if it happens with the latest version.
