### ISSUE TITLE
Crash after attempting to delete requests

### ISSUE THREAD

**Issue by tigertoes** [mitmproxy/mitmproxy#601]
##### Steps to reproduce the problem:
1. MITM some traffic, over say, 20 minutes
2. Start deleting (explicitly pressing "d") requests in the dump
3. After deleting some, mitm crashes.

##### What is the expected behavior?
Not to crash, I suppose.

##### What went wrong?
Stack trace:

    Traceback (most recent call last):
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 614, in run
        self.ui.run_wrapper(self.loop)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/vendor/lib/python2.7/site-packages/urwid/display_common.py", line 757, in run_wrapper
        return fn()
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 845, in loop
        k = self.view.keypress(size, k)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/vendor/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
        return self.body.keypress( (maxcol, remaining), key )
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 269, in keypress
        return urwid.ListBox.keypress(self, size, key)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/vendor/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
        key = focus_widget.keypress((maxcol,),key)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 147, in keypress
        self.state.delete_flow(self.flow)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 331, in delete_flow
        ret = flow.State.delete_flow(self, f)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 548, in delete_flow
        self.flows._remove(f)
      File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 462, in _remove
        self._list.remove(f)
    ValueError: list.remove(x): x not in list

    mitmproxy has crashed!
    Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
    Shutting down...

##### Any other comments?

This could be a one-off, I'm having difficulty reproducing consistently it but thought it would be best to log it here in case someone else sees it and can. I'm also unable to give you the session (I didn't save it, and it contained sensitive data).

---
mitmproxy version: mitmproxy 0.11.3
Operating System: OS X 10.10.3

**Comment by cortesi** [comment]
Hi there. This issue has been fixed on the current master - a new release (0.12.1) will be out in the next week. In the meantime, if you're keen, you can check out the github master. Thanks for reporting the problem!
