### ISSUE TITLE
Seeing the following error starting on Friday, March 31st.

### ISSUE THREAD

**Issue by chrids88** [mitmproxy/mitmproxy#6042]
#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by chrids88** [comment]
Seeing the following error starting yesterday (March 31st):

```
Traceback (most recent call last):

  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 159, in _accept_connection

  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 293, in accept

OSError: [Errno 24] Too many open files

```
Been proxying for a few weeks using just one device (iPhone 13) without issue. 

Yesterday I proxied with a new device (iPhone X) with success and then tried to proxy with a Google Pixel before realizing thiss wasn't possible. Within an hour I started getting the above error regardless of which iOS device I tried to proxy with.

**Comment by ericbeland** [comment]
What's your mitmproxy version?

**Comment by chrids88** [comment]
System Information

```
$ mitmproxy --version
Mitmproxy: 8.1.1
Python:    3.10.8
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-12.6.1-x86_64-i386-64bit
```

**Comment by ericbeland** [comment]
Can you upgrade to 9.0.1 and retry?

**Comment by chrids88** [comment]
Thanks Eric.

**Comment by chrids88** [comment]
Still seeing error:

```
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy/issues
[11:19:10.608] Traceback (most recent call last):

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 165, in _accept_connection
    conn, addr = sock.accept()
                 ^^^^^^^^^^^^^

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^

OSError: [Errno 24] Too many open files
```

**Comment by MatrixManAtYrService** [comment]
I had this problem recently.  To see how many open files linux would allow I ran:
```
$ ulimit -n
1024
```

Then, to increase it, I ran
```
$ ulimit -n 4096
$ ulimit -n 
4096
```

Then the problem went away.

It appears to be a per-shell setting, so you have to run it in the same shell that you later use to run mitmproxy.  Probably there's a way to make it permanent, but I don't know it off hand.

**Comment by changsin** [comment]
I also encounter this issue with mitmproxy. The repro is to have a sudden surge of internet traffic.
This happens even more often when I run it as a macOS daemon. What I understand is that the system puts certain limitations on a daemon process. Whenever this happens, our mitmproxy wrapper process restarts.


[15:12:33.558] Traceback (most recent call last):

  File "asyncio/selector_events.py", line 164, in _accept_connection

  File "socket.py", line 293, in accept

OSError: [Errno 24] Too many open files

Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy/issues

**Comment by userAman16** [comment]
running with **connection_strategy=lazy** worked

 `sudo mitmweb --mode transparent --listen-port 443 --set connection_strategy=lazy`
