### ISSUE TITLE
About the ConnectionResetError error problem when the program is running

### ISSUE THREAD

**Issue by Black-Face-Kk** [mitmproxy/mitmproxy#6124]
#### Problem Description
When running as a python plugin, this error problem is sometimes reported
When this error is reported, the program seems to stop working

Traceback (most recent call last):

   File "asyncio\events.py", line 80, in_run
   File "asyncio\proactor_events.py", line 165, in _call_connection_lost

ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host。
Please lodge a bug report at:

	https://github.com/mitmproxy/mimtproxy/issues

#### System Information
Mitmproxy: 9.0.1
Python:    3.11.3
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.22621-SP0

**Comment by Prinzhorn** [comment]
Thanks for reporting. This is now the third time this has been reported, but without steps to reproduce this we cannot do anything about it.

If you can, then provide detailed steps what exactly you did. If you can't reproduce this consistently, then at least provide _any_ hint as to what you were doing (what does the addon do, what kind of traffic are you proxying, etc.)

https://github.com/mitmproxy/mitmproxy/issues/5581
https://github.com/mitmproxy/mitmproxy/issues/5939

**Comment by Black-Face-Kk** [comment]
Reproduce the process
1: When the browser is proxied from port 8080, this problem will occur if the link to the visited website cannot be accessed.

**Comment by Srijan67** [comment]
> Reproduce the process 1: When the browser is proxied from port 8080, this problem will occur if the link to the visited website cannot be accessed.

**Comment by Srijan67** [comment]
@Prinzhorn @Black-Face-Kk  are you able to reproduce this bug and is it fixed?

**Comment by Prinzhorn** [comment]
No clear steps to reproduce the error have been provided. I have no idea what "this problem will occur if the link to the visited website cannot be accessed" means. We need clear steps that we can follow along.
