### ISSUE TITLE
can't type `~all` in search text input of the web, but can only paste `~all`

### ISSUE THREAD

**Issue by NewUserHa** [mitmproxy/mitmproxy#6168]
#### Problem Description
the search text input keeps deleting/emptying the user's input:

* can't input `~all`, it immediately becomes empty when starting from `l`
* can't use `~q` to filter out all requests like https://docs.mitmproxy.org/stable/mitmproxytutorial-interceptrequests/ said, only a tooltip with "has no response"
* can't input `!~a` too, it becomes empty after typing the `a`
* `~s ~t ".*text/html.*"` can't work as well.
* typing `~a` can be deleted sometimes too.

Can the input box stop delete the user's input when there's any error or even any interval between inputs?
Maybe the error filter is only glitched and what happened is the user just typo.

#### System Information
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.17134-SP0

**Comment by NewUserHa** [comment]
And typing `~s ~t "text"` cause a crash:
```
mitmproxy has crashed.
TypeError: Cannot read properties of undefined (reading 'length')
    at MessageUtils.get_first_header (http://127.0.0.1:8081/static/app.js:62:5783)
    at RequestUtils.getContentType (http://127.0.0.1:8081/static/app.js:62:5482)
    at contentTypeFilter (http://127.0.0.1:8081/static/app.js:64:15917)
    at andFilter (http://127.0.0.1:8081/static/app.js:64:11223)
    at http://127.0.0.1:8081/static/app.js:65:50039
    at Array.map (<anonymous>)
    at t.render (http://127.0.0.1:8081/static/app.js:65:49968)
    at qi (http://127.0.0.1:8081/static/app.js:5:68270)
    at pi (http://127.0.0.1:8081/static/app.js:5:68058)
    at ck (http://127.0.0.1:8081/static/app.js:9:10018)

Component Stack:
    at AutoScrollWrapper (http://127.0.0.1:8081/static/app.js:65:46267)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:58:5505)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:65:52003)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:69:3070)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:58:5505)
    at Provider (http://127.0.0.1:8081/static/app.js:58:2818)
```

**Comment by mhils** [comment]
> * can't input `~all`, it immediately becomes empty when starting from `l`

I'm unable to reproduce this at all, can you please provide steps to reproduce?

**Comment by NewUserHa** [comment]
it's just normal typing

**Comment by mhils** [comment]
Which browser is this? Do you see anything in the event log? How do you access mitmproxy, locally or over a network?

**Comment by NewUserHa** [comment]
chrome version 114.
remember no.
localhost.

**Comment by andy74139** [comment]
I run it by using `mitmweb` command on terminal, and it opens a local web page `127.0.0.1:8081`
It happens even I use on mac only.
Mac connects to a wifi, and sometimes I use mobile phone using proxy to mitm.

Mitmproxy: 9.0.1
Python:    3.11.2
OpenSSL:   OpenSSL 1.1.1t  7 Feb 2023
Platform:  macOS-13.3.1-arm64-arm-64bit

OS: MacOS Version 13.3.1
Browser: Chrome Version 115.0.5790.114 (Official Build) (arm64)
Console log:
```
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/vendor.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/app.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I just tried Firefox, it also has the issue.
The difference is it recovers the text box slower, so usually I can type the filter I want.

**Comment by NewUserHa** [comment]
10.1.3 fixed this issue.
but it sometimes still happens when you first time type at the \<text\> element
