### ISSUE TITLE
0.12.0 crashes when creating a new request

### ISSUE THREAD

**Issue by majewsky** [mitmproxy/mitmproxy#618]
To reproduce, start mitmproxy and type "ng\<Enter>" on the main view (which should generate a new request, using the default URL of `http://www.example.com`). This immediately produces the following stacktrace for me:

```
$ mitmproxy -p 8888
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 457, in run
    self.loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/window.py", line 21, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 123, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 82, in keypress
    self.prompt_execute(self._w.get_edit_text())
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 104, in prompt_execute
    msg = p(txt, *args)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 302, in new_request
    f = self.master.create_request(method, scheme, host, port, path)
  File "/usr/lib/python2.7/site-packages/libmproxy/flow.py", line 801, in create_request
    headers = ODictCaseless()
NameError: global name 'ODictCaseless' is not defined
```

**Comment by mhils** [comment]
Good find. Thanks!
