### ISSUE TITLE
Crashing - idna.py - UnicodeError: label empty or too long

### ISSUE THREAD

**Issue by p4l4din** [mitmproxy/mitmproxy#622]
While scrolling down within the mitmproxy window using the arrow key it crashes. Repeatable multiple times when using mitmproxy to intercept the following site http://www.buddharadio.com.au 

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 478, in run
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 496, in process_input
    event, button, col, row, focus=True ):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/window.py", line 32, in mouse_event
    self.keypress(args[0], "down")
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 358, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/listbox.py", line 1001, in keypress
    return actual_key(self._keypress_down((maxcol, maxrow)))
  File "/usr/local/lib/python2.7/dist-packages/urwid/listbox.py", line 1119, in _keypress_down
    widget, pos = self.body.get_next(pos)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 260, in get_next
    f = ConnectionItem(self.master, self.state, f, False) if f else None
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 104, in __init__
    w = self.get_text()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 111, in get_text
    hostheader = self.master.showhost
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/common.py", line 375, in format_flow
    req_url = f.request.pretty_url(hostheader=hostheader),
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 607, in pretty_url
    self.pretty_host(hostheader),
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 599, in pretty_host
    return host.encode("idna")
  File "/usr/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

mitmproxy has crashed!
```

**Comment by cortesi** [comment]
Thanks for the report! This has been fixed in  7890450.
