### ISSUE TITLE
Stops starting after some time of working

### ISSUE THREAD

**Issue by AqlaSolutions** [mitmproxy/mitmproxy#6260]
```

Traceback (most recent call last):
  File "mitmproxy", line 3, in <module>
  File "mitmproxy\tools\main.py", line 126, in mitmproxy
  File "mitmproxy\tools\main.py", line 120, in run
  File "asyncio\runners.py", line 189, in run
  File "asyncio\runners.py", line 59, in __enter__
  File "asyncio\runners.py", line 137, in _lazy_init
  File "asyncio\events.py", line 805, in new_event_loop
  File "asyncio\events.py", line 695, in new_event_loop
  File "asyncio\windows_events.py", line 315, in __init__
  File "asyncio\proactor_events.py", line 635, in __init__
  File "asyncio\proactor_events.py", line 780, in _make_self_pipe
  File "socket.py", line 632, in socketpair
OSError: [WinError 10055] Невозможно выполнить операцию на сокете, т.к. буфер слишком мал или очередь переполнена
[47848] Failed to execute script 'mitmproxy' due to unhandled exception!
sys:1: RuntimeWarning: coroutine 'run.<locals>.main' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function BaseEventLoop.__del__ at 0x0000021B0CC5AAC0>
Traceback (most recent call last):
  File "asyncio\base_events.py", line 691, in __del__
  File "asyncio\proactor_events.py", line 692, in close
  File "asyncio\proactor_events.py", line 772, in _close_self_pipe
AttributeError: 'ProactorEventLoop' object has no attribute '_ssock'


Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.19044-SP0
```
WinError 10055 usually means that some sockets were not properly closed and the system is out of free ports for outgoing connections and listening.

**Comment by mhils** [comment]
Do you have any hints on how to reproduce this?

**Comment by AqlaSolutions** [comment]
I don't think there is an easy way unless you can launch tens of telegram accounts through your proxy each joined to 60+ group.

Also I have to restart mitmproxy each hour because it stops accepting connections. For me this bug appeared after 12+ hours of such work.

**Comment by mhils** [comment]
It would be useful to have a script or something that reproduces that deterministically, otherwise I'm afraid there's not too much I can do here. You can maybe fiddle with https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/utils/debug.py to get some intermediate output, but that is currently using Unix signals and needs some adjustments.

**Comment by mhils** [comment]
We pretty much should be doing that, you can check https://github.com/mitmproxy/mitmproxy/blob/d4ec24d85dd108002ce38cd1265460546d8b7354/mitmproxy/proxy/server.py#L271-L321 yourself if you want...
