### ISSUE TITLE
Installation error in Windows 8

### ISSUE THREAD

**Issue by sajid-dsi** [mitmproxy/mitmproxy#629]
Hi,
I'm trying to install mitmproxy. My OS is Windows 8, 64 bit. Python is 2.7.10 for 64 bit.

I'm running the command prompt in 'Administrative' mode, granting permission to Administrator for all Files and Folders.My command and the generated error logs are as follow:
```
pip install mitmproxy
--skipping success logs----following are error logs---
    Installed c:\users\humaira\appdata\local\temp\easy_install-sd_aqy\cryptograp
hy-0.9.1\.eggs\pycparser-2.14-py2.7.egg
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 've
ctors'
    _Cryptography_cffi_a269d620xd5c405b7.c
    src\cryptography\hazmat\bindings\__pycache__\_Cryptography_cffi_a269d620xd5c
405b7.c(217) : fatal error C1083: Cannot open include file: 'openssl/aes.h': No
such file or directory
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\humaira\appdata\local\temp\pip-build-n4tzb8\netlib\setup.py
", line 87, in <module>
        "install": CFFIInstall,
      File "C:\Python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 268, in __in
it__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 313, in fetc
h_build_eggs
        replace_conflicting=True,
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 830,
in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1075,
 in best_match
        return self.obtain(req, installer)
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1087,
 in obtain
        return installer(requirement)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 380, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 633, in easy_install
        rmtree(tmpdir)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 2197, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 2197, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 2197, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 2202, in rmtree
        onerror(os.remove, fullname, sys.exc_info())
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1609, in auto_chmod
        return func(arg)
    WindowsError: [Error 5] Access is denied: 'c:\\users\\humaira\\appdata\\loca
l\\temp\\easy_install-sd_aqy\\cryptography-0.9.1\\.eggs\\cffi-1.1.2-py2.7-win-am
d64.egg\\_cffi_backend.pyd'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\humaira\
appdata\local\temp\pip-build-n4tzb8\netlib
```
I've granted permission to temp folder, but still it's giving the error. To me, it seems like the error starts from here:
"fatal error C1083: Cannot open include file: 'openssl/aes.h': No
such file or directory"

Any suggestions/comments?? Thanks in advance.

**Comment by cortesi** [comment]
Hi there. We've just uploaded a wheel package for 32-bit Python on Windows that smooths this over by including pre-compiled dependencies. We should have a 64-bit build up soon too.

**Comment by sajid-dsi** [comment]
Hi,
Thanks for the update! Finally, I've been able to install it!!

**Comment by mhils** [comment]
refs mitmproxy/netlib/issues/68
