### ISSUE TITLE
How to build mitmproxy_rs?

### ISSUE THREAD

**Issue by kpcyrd** [mitmproxy/mitmproxy#6311]
#### Problem Description

I'm preparing the 10.0.0 update of mitmproxy for Arch Linux and noticed:

```
% mitmproxy
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 5, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/usr/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 15, in <module>
    from mitmproxy import master
  File "/usr/lib/python3.11/site-packages/mitmproxy/master.py", line 4, in <module>
    from . import ctx as mitmproxy_ctx
  File "/usr/lib/python3.11/site-packages/mitmproxy/ctx.py", line 1, in <module>
    import mitmproxy.log
  File "/usr/lib/python3.11/site-packages/mitmproxy/log.py", line 8, in <module>
    from mitmproxy import hooks
  File "/usr/lib/python3.11/site-packages/mitmproxy/hooks.py", line 11, in <module>
    import mitmproxy.flow
  File "/usr/lib/python3.11/site-packages/mitmproxy/flow.py", line 12, in <module>
    from mitmproxy import connection
  File "/usr/lib/python3.11/site-packages/mitmproxy/connection.py", line 15, in <module>
    from mitmproxy.proxy import mode_specs
  File "/usr/lib/python3.11/site-packages/mitmproxy/proxy/mode_specs.py", line 33, in <module>
    import mitmproxy_rs
ModuleNotFoundError: No module named 'mitmproxy_rs'
```

I've then started preparing a new package that provides `mitmproxy_rs` but didn't manage to build a working wheel.

Using this command:
```
maturin build --release --strip
```

I got this warning during build and the wheel fails to import at the testing stage:
```
   Compiling exr v1.7.0
   Compiling x25519-dalek v2.0.0-rc.3
   Compiling boringtun v0.5.3
   Compiling prost-build v0.11.9
   Compiling mitmproxy v0.2.2 (/build/python-mitmproxy-rs/src/mitmproxy_rs-0.2.2)
   Compiling image v0.24.6
    Finished release [optimized] target(s) in 1m 08s
⚠️  Warning: Couldn't find the symbol `PyInit_mitmproxy` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `mitmproxy` as module name
📦 Built wheel for abi3 Python ≥ 3.10 to /build/python-mitmproxy-rs/src/mitmproxy_rs-0.2.2/target/wheels/mitmproxy-0.2.2-cp310-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl
==> Starting check()...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mitmproxy_rs'
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Build failed, check /var/lib/archbuild/extra-x86_64/user-7/build
```

I looked into the github actions file and tried to copy the flags over:
```
maturin build --release --strip --compatibility manylinux2014 --zig --sdist
```

but maturin rejects them as invalid:
```
==> Extracting sources...
  -> Extracting python-mitmproxy-rs-0.2.2.tar.gz with bsdtar
==> Starting build()...
error: unexpected argument '--zig' found

  note: to pass '--zig' as a value, use '-- --zig'

Usage: maturin build --release --strip --compatibility [<compatibility>...] [ARGS]...

For more information, try '--help'.
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /var/lib/archbuild/extra-x86_64/user-7/build
```

Instructions appreciated, thanks!

**Comment by mhils** [comment]
> ⚠️  Warning: Couldn't find the symbol `PyInit_mitmproxy` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` 

For maturin, make sure to invoke it in ./ffi and not the root directory. We should look into make this more clear, suggestions appreciated. :)

refs #6303

**Comment by kpcyrd** [comment]
Thanks, running it in ./ffi fixed it!

I've successfully built and uploaded [mitmproxy-10.0.0-1-any.pkg.tar.zst to Arch Linux](https://archlinux.org/packages/extra/any/mitmproxy/). :tada:
