### ISSUE TITLE
Mitmproxy Crashes on Disconnect with Websocket Addon

### ISSUE THREAD

**Issue by ericbeland** [mitmproxy/mitmproxy#6324]
#### Problem Description

I am making an addon that allows you to hang a websocket onto any website accessed through the proxy by requesting it at ws://yoursite.com/WebsocketMe.  I have handshaking that _seems_ to work, and I followed the example in the addon. However, I wonder if I'm missing something as if I for example, turn off my wifi, it crashes mitmproxy.  It seems to crash on any trigger for connection cleanup, I _think_. If this can be fixed, it might be an interesting item for a contrib addon. 

Any ideas on what I've missed or if this is actually a bug?

```python
import mitmproxy.http
import logging
import time
import hashlib
import base64
import json
from mitmproxy import ctx, http


class Myws:

    def __init__(self):
        self.handshaked = False

    def compute_websocket_accept_value(self, key: str) -> str:
        magic_string = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
        combined = key + magic_string
        accept_value = base64.b64encode(hashlib.sha1(combined.encode()).digest()).decode('utf-8')
        return accept_value

    def request(self, f: mitmproxy.http.HTTPFlow):
        logging.info(f'request: {f.request.url}')
        if 'WebsocketMe' in f.request.url:
            # Generate the handshake response
            websocket_key = f.request.headers.get('Sec-WebSocket-Key', '')
            websocket_accept = self.compute_websocket_accept_value(websocket_key)
            response_headers = [
                (b"Upgrade", b"websocket"),
                (b"Connection", b"Upgrade"),
                (b"Sec-WebSocket-Accept", websocket_accept.encode()), 
            ]
            timestamp_start = time.time()
            timestamp_end = timestamp_start
            self.handshaked = True
            f.response = mitmproxy.http.Response(
                http_version=f.request.http_version,
                status_code=101,
                reason=b"Switching Protocols",
                headers=response_headers,
                content=b"",
                trailers=[],
                timestamp_start=timestamp_start,
                timestamp_end=timestamp_end
            )


    def websocket_message(self, f: mitmproxy.http.HTTPFlow):
        assert f.websocket is not None 
        message = f.websocket.messages[-1]
        if message.from_client:
            logging.info(f"Received message from client: {message.content}")
        else:
            logging.info(f"Received message from server (unexpected!): {message.content}")

        content = message.content
        message.drop()

        try:
            data = json.loads(content)
            logging.info(data)
        except json.JSONDecodeError:
            logging.error("Invalid JSON string")
        
addons = [Myws()]

```

#### Steps to reproduce the behavior:
1. save the file above to myws.py
2. run `mitmdump -s ./myws.py`
3. Use mitmproxy as a proxy in firefox
4. In firefox, in the console run: 

```javascript
let webSocket = new WebSocket('ws://playground.browserup.com/WebsocketMe');
    webSocket.onopen = function (event) {
      console.log('connection is open wss!')
      webSocket.send('{"foo": "bar"}');
    } 
```

5. It will look happy enough in the console, and in the log.

6. Disconnect your wifi

  7. You should see something like this error:

```bash
127.0.0.1:65309: GET http://detectportal.firefox.com/success.txt?ipv4
 << [Errno 8] nodename nor servname provided, or not known
[16:12:29.915][[::1]:65310] error establishing server connection: [Errno 8] nodename nor servname provided, or not known
[16:12:29.915][127.0.0.1:65309] client disconnect
[::1]:65310: GET http://detectportal.firefox.com/success.txt?ipv6
 << [Errno 8] nodename nor servname provided, or not known
[16:12:29.917][[::1]:65310] client disconnect
[16:12:29.986][127.0.0.1:65276] Received WebSocket ping from client (payload: b'PING')
[16:12:29.991][127.0.0.1:65276] mitmproxy has crashed!
Traceback (most recent call last):
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/server.py", line 344, in server_event
    for command in layer_commands:
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layer.py", line 257, in handle_event
    yield from self._handle(event)
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 896, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 923, in event_to_child
    yield from self.event_to_child(stream, command.event)
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 905, in event_to_child
    for command in child.handle_event(event):
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 749, in passthrough
    for command in self.child_layer.handle_event(event):
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 896, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 923, in event_to_child
    yield from self.event_to_child(stream, command.event)
  File "/Users/ebeland/apps/mitmproxy/mitmproxy/proxy/layers/http/__init__.py", line 925, in event_to_child
    conn = self.connections[command.connection]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: Server({'id': '…943eec', 'address': ('playground.browserup.com', 80), 'state': <ConnectionState.OPEN: 3>, 'transport_protocol': 'tcp', 'sockname': ('192.168.86.247', 65277), 'timestamp_start': 1692216745.372886, 'timestamp_tcp_setup': 1692216745.447434, 'peername': ('147.135.114.251', 80)})
```

#### System Information
Mitmproxy: 10.0.0.dev (+225, commit 8891e84)
Python:    3.11.4
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-13.3.1-arm64-arm-64bit

**Comment by ericbeland** [comment]
It looks like the problem is that it is trying to handle a cancel event on a connection that doesn't exist.

Locally, if I put an `if` clause to guard against the connection being missing [here](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/proxy/layers/http/__init__.py#L954-L956), it _seems_ like that fixes this bug. I'm not sure if that would have side effects, though?

                if command.connection in self.connections:
                    conn = self.connections[command.connection]
                    yield from self.event_to_child(conn, command.event)
                    
With that change, the log looks normal, as in, no stack trace, but I do see:

Error in WebSocket connection to playground.browserup.com:80: WebSocket Error: ABNORMAL_CLOSURE
[20:59:10.761][127.0.0.1:63989] client disconnect
[20:59:10.761][127.0.0.1:63989] closing transports...

**Comment by ShayYaari** [comment]
Hi,
Any followup regarding this one as I experience the same issue.

Thanks :)
