### ISSUE TITLE
mitmproxy can't launch

### ISSUE THREAD

**Issue by xuixian** [mitmproxy/mitmproxy#636]
install on the raspberry pi2 ,followed by the:
http://jeffq.com/blog/setting-up-a-man-in-the-middle-device-with-raspberry-pi-part-1/

os: 2015-05-05-raspbian-wheezy
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

Is there something wrong ?

Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/main.py", line 40, in mitmproxy
    from . import console
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 18, in <module>
    from . import flowlist, flowview, help, window, signals, options
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 4, in <module>
    from . import common, signals
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/common.py", line 115, in <module>
    if urwid.util.detected_encoding:
AttributeError: 'module' object has no attribute 'detected_encoding'

**Comment by xuixian** [comment]
kali Linux passed ~!
