### ISSUE TITLE
unable to open mitmweb

### ISSUE THREAD

**Issue by surcross** [mitmproxy/mitmproxy#6379]
### _Problem Description_
i can't open mitmweb in browser
**when run mitmweb in bash,it showed:**
ks@kswift:~$ mitmweb
Web server listening at http://127.0.0.1:8081/
[15010:15010:0924/140620.961544:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[15010:15010:0924/140620.979713:ERROR:assistance_home_client.cc(32)] File path /home/ks/.config/microsoft-edge/Default
[15010:15010:0924/140622.517126:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[15010:15010:0924/140625.932567:ERROR:CONSOLE(2)] "Blocked autofocusing on a <cib-action-bar> element in a cross-origin subframe.", source: https://edgeservices.bing.com/rp/QIpJBNwEhuCqahIRRTEDF2Ar8w8.br.js (2)
[15010:15010:0924/140625.952278:ERROR:CONSOLE(2)] "Blocked autofocusing on a <textarea> element in a cross-origin subframe.", source: https://edgeservices.bing.com/rp/QIpJBNwEhuCqahIRRTEDF2Ar8w8.br.js (2)

**when I ctrl c ,it shows:**
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
TypeError: 'NoneType' object is not callable

Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x00005623ceab28a0)

Current thread 0x00007f7841423000 (most recent call first):
  <no Python frame>

Extension modules: _cffi_backend, _ruamel_yaml, _brotli, tornado.speedups, google.protobuf.pyext._message, markupsafe._speedups, greenlet._greenlet, msgpack._cmsgpack (total: 8)
Aborted (core dumped)

### Steps to reproduce the behavior:
1. type mitmweb in browser

### System Information
ks@kswift:~$ mitmproxy --version
Mitmproxy: 6.0.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.0.2 15 Mar 2022
Platform:  Linux-5.19.0-50-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by surcross** [comment]
> Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

after upgrading to 10.1.0, it can work now.  thank you
