### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by jrfnl** [mitmproxy/mitmproxy#6400]
#### Problem Description

_I'm hoping I'm reporting this in the correct place. Please forgive me if I got it wrong (I'm not a Python dev)_ 🙏🏻 

A GitHub actions workflow for one of the projects I'm involved in broke recently and this looks to be related to the `werkzeug.urls` package having released a 3.0.0 version and being a sub-dependency of mitmproxy via the Flask package.

The Flask package has released a new major (3.0.0) as well, which fixes this issue and (merged) PR #6390 updates Flask for mitmproxy, but that PR is not yet included in a tagged release.

In the mean time, I'm not sure how I can get the builds for the project using `mitmproxy` working again. Any help would be appreciated!

#### Steps to reproduce the behavior:
```yaml
name: Test

on:
  push:

jobs:
  reproduce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Setup proxy server
        run: pip3 install mitmproxy

      - name: Check mitmproxy version
        run: mitmdump --version
```

#### System Information
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mitmproxy/tools/main.py", line 137, in mitmdump
    from mitmproxy.tools import dump
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mitmproxy/tools/dump.py", line 1, in <module>
    from mitmproxy import addons
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mitmproxy/addons/__init__.py", line 14, in <module>
    from mitmproxy.addons import onboarding
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mitmproxy/addons/onboardingapp/__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/werkzeug/urls.py)
Error: Process completed with exit code 1.
```

**Comment by mhils** [comment]
Hi there! The first problem I see here is `python-version: '3.8'`, which means you won't pick up the latest mitmproxy release. mitmproxy 10 requires Python 3.10 or above. :)

**Comment by jrfnl** [comment]
@mhils Thank you for your quick response! Running tests with an updated Python version now to see if that resolves the build failures. Will get back to you once the build finishes. 🤞🏻

**Comment by jrfnl** [comment]
[Test build](https://github.com/WordPress/Requests/actions/runs/6458835376) has finished running and is working again.

Thank you so much @mhils for the seemingly simple solution, but one which can be darn hard to figure out if one is not very familiar with the Python ecosystem (like me). 💞
