### ISSUE TITLE
KeyError in proxyserver.py when handling TCP connection

### ISSUE THREAD

**Issue by Twi1ight** [mitmproxy/mitmproxy#6405]
#### Problem Description
I encountered a KeyError exception while using mitmproxy. The error occurred while the program was handling a TCP connection. Here's the full traceback:

```
[15:24:29.478] Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/mitmproxy/proxy/mode_servers.py", line 168, in handle_tcp_connection
    await handler.handle_client()

  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)

  File "/usr/local/lib/python3.9/dist-packages/mitmproxy/addons/proxyserver.py", line 122, in register_connection
    del self.connections[connection_id]

KeyError: ('tcp', ('127.0.0.1', 51356), ('127.0.0.1', 8080))

``` 
The problem seems to arise from a key not being found in a dictionary (self.connections) during the execution of del self.connections[connection_id] within the register_connection function.

#### Steps to reproduce the behavior:
1. setup a squid reverse proxy to mitmproxy
2. run mitmdump with command: mitmdump -s proxy--set termlog_verbosity=warn --set flow_detail=0 --set connection_strategy=lazy --set websocket=false --set ssl_insecure=true --listen-host 127.0.0.1 --certs my.pem
3. when act as an open proxy, sometimes the error occurs

#### System Information
Mitmproxy: 9.0.1
Python:    3.9.2
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.10.0-23-amd64-x86_64-with-glibc2.31

**Comment by Prinzhorn** [comment]
Thanks for reporting this. Does this happen with the latest 10.1.1 as well?

**Comment by mhils** [comment]
It likely does, we're getting rid of that very mechanism though. Leaving it open until it's finished. :)

**Comment by duanhao123** [comment]
I had the same problem. Did you solve it?If you solve it, please tell me how to solve it
