### ISSUE TITLE
The agent failed, the connection request failed

### ISSUE THREAD

**Issue by wlfzsd** [mitmproxy/mitmproxy#6484]
[13:17:34.901] Traceback (most recent call last):

  File "asyncio\windows_events.py", line 591, in accept_coro

  File "asyncio\windows_events.py", line 837, in _poll

  File "asyncio\windows_events.py", line 580, in finish_accept

OSError: [WinError 64] 指定的网络名不再可用。

Please lodge a bug report at:
          File "asyncio\windows_events.py", line 580, in finish_accept
[13:17:34.901] Traceback (most recent call last):

  File "asyncio\proactor_events.py", line 839, in loop

OSError: [WinError 64] 指定的网络名不再可用。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues

**Comment by mhils** [comment]
How can we reproduce this? :)

**Comment by wlfzsd** [comment]
> How can we reproduce this? :)

When mitmproxy is running, and other software causes CPU usage to reach 100% and network usage to be around 99%, the aforementioned issue tends to occur easily. (It is not caused by any specific software, but rather when the system's CPU and network utilization are extremely high, the issue is particularly prone to happen.)
