### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_DEFAULT_METHOD'

### ISSUE THREAD

**Issue by byt3bl33d3r** [mitmproxy/mitmproxy#655]
Hi guys,
Just pulled down the latest changes from github and got this error when starting mitmdump
```
Traceback (most recent call last):
  File "/home/byt3bl33d3r/.local/bin/mitmdump", line 9, in <module>
    load_entry_point('mitmproxy==0.12.2', 'console_scripts', 'mitmdump')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/main.py", line 7, in <module>
    from . import version, cmdline
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/cmdline.py", line 6, in <module>
    from . import filt, utils, version
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/filt.py", line 38, in <module>
    from .protocol.http import decoded
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/protocol/__init__.py", line 1, in <module>
    from .primitives import *
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/protocol/primitives.py", line 6, in <module>
    from ..proxy.connection import ClientConnection, ServerConnection
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/__init__.py", line 2, in <module>
    from .config import ProxyConfig, process_proxy_options
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/config.py", line 31, in <module>
    class ProxyConfig:
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/config.py", line 52, in ProxyConfig
    ssl_version_client=tcp.SSL_DEFAULT_METHOD,
AttributeError: 'module' object has no attribute 'SSL_DEFAULT_METHOD'
```

**Comment by Kriechi** [comment]
Did you update your netlib code as well? There have been some recent changes which seem to be the problem. Please let us know if this fixed it for you.

**Comment by byt3bl33d3r** [comment]
@Kriechi thanks! updating netlib did the trick

**Comment by llazzaro** [comment]
got the same error and upgrading netlib fixed the issue

**Comment by mrlzh** [comment]
I got this error:
Traceback (most recent call last):
  File "proxy.py", line 9, in <module>
    from libmproxy import controller, proxy
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/__init__.py", line 2, in <module>
    from .config import ProxyConfig, process_proxy_options
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/config.py", line 31, in <module>
    class ProxyConfig:
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/config.py", line 51, in ProxyConfig
    ssl_version_client=tcp.SSL_DEFAULT_METHOD,
AttributeError: 'module' object has no attribute 'SSL_DEFAULT_METHOD'

I have updated netlib to v0.12.1 ,but it does not work.help!

**Comment by mhils** [comment]
answered in #668 again.
