### ISSUE TITLE
mitmproxy crashes when starting

### ISSUE THREAD

**Issue by aski71** [mitmproxy/mitmproxy#6618]
#### Problem Description
mitmproxy crashes when starting.
Installed on a naked and newly set up Linux machine using apt.

#### Steps to reproduce the behavior:

```
ak@experimental:~$ sudo mitmproxy -m socks5 -rawtcp
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/readfile.py", line 63, in load_flows_from_path
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'awtcp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/readfile.py", line 72, in doread
    await self.load_flows_from_path(ctx.options.rfile)
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/readfile.py", line 67, in load_flows_from_path
    raise exceptions.FlowReadException(str(e)) from e
mitmproxy.exceptions.FlowReadException: [Errno 2] No such file or directory: 'awtcp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/readfile.py", line 74, in doread
    raise exceptions.OptionsError(e) from e
mitmproxy.exceptions.OptionsError: [Errno 2] No such file or directory: 'awtcp'

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

#### System Information
ak@experimental:~$ mitmproxy --version
Mitmproxy: 6.0.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.0.2 15 Mar 2022
Platform:  Linux-5.15.0-92-generic-x86_64-with-glibc2.35

**Comment by aski71** [comment]
P.S.: Same happens with downloaded version.

`ak@experimental:~$ ./mitmproxy --version
Mitmproxy: 10.2.2 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-5.15.0-92-generic-x86_64-with-glibc2.35
`

**Comment by mhils** [comment]
`-rawtcp` is interpreted as `-r awtcp`, which causes the error you are seeing. Raw TCP processing is on by default, so you can just leave it out.

**Comment by aski71** [comment]
Apologies. That was a stupid mistake. 😂
In the documentation of mitmproxy helper on iOS it said "--rawtcp". So I forgot one minus.
Or as you just said: Leave it out.
Now it works. Thanks A lot.
