### ISSUE TITLE
New error in custom inline-script and provided example

### ISSUE THREAD

**Issue by mame82** [mitmproxy/mitmproxy#662]
Hey, 

I've got a proble with a custom inline-script, running mitmproxy-0.12.1 (not the provided 11.3) on kali-1.1.0, after an `apt-get upgrade`. So I don't know exactly what causes the problem, but it wasn't there before.

The custom script-code (stripped down to error parts)
```
from libmproxy.protocol.http import decoded
from bs4 import BeautifulSoup

def response(context, flow):
	if flow.response.headers.get_first("content-type", "").startswith("text/html"):
		with decoded(flow.response):  # automatically decode gzipped responses.
			# context.log("Type " + str(type(flow.response.content)))
			html = BeautifulSoup(flow.response.content)
			if html.head:
				# here some header-modifying-code, which isn't relevant for raising this error
				flow.response.content = str(html)
				context.log("Manipulated response header.")
```

Error-Dump of mitmproxy/mitmdump
```
Script error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/script.py", line 123, in run
    return (True, f(self.ctx, *args, **kwargs))
  File "/usr/share/doc/mitmproxy/examples/modify_response_header_error.py", line 12, in response
    context.log("Manipulated response header.")
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/protocol/http.py", line 78, in __exit__
    self.o.encode(self.ce)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/protocol/http.py", line 151, in encode
    self.content = encoding.encode(e, self.content)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/encoding.py", line 33, in encode
    return encoding_map[e](content)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/encoding.py", line 55, in encode_gzip
    gf.write(content)
  File "/usr/lib/python2.7/gzip.py", line 228, in write
    if len(data) > 0:
TypeError: object of type 'int' has no len()
```

encoding.py shouldn't have changed since my last usage of the script (and it worked)
For testing I've changed the `if html.head:` to `if html.head and html.body:` to make sure there's content present before encoding again, but with no effect.
Comparing to the examples, I've found that `iframe_injector.py` is producing exactly the same error because it uses the decoded() method.

```
Script error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/script.py", line 123, in run
    return (True, f(self.ctx, *args, **kwargs))
  File "/usr/share/doc/mitmproxy/examples/iframe_injector.py", line 27, in response
    context.log("Iframe inserted.")
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/protocol/http.py", line 78, in __exit__
    self.o.encode(self.ce)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/protocol/http.py", line 151, in encode
    self.content = encoding.encode(e, self.content)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/encoding.py", line 33, in encode
    return encoding_map[e](content)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.1-py2.7.egg/libmproxy/encoding.py", line 55, in encode_gzip
    gf.write(content)
  File "/usr/lib/python2.7/gzip.py", line 228, in write
    if len(data) > 0:
TypeError: object of type 'int' has no len()

```

**Comment by mhils** [comment]
The `iframe_injector.py` script is working fine for me (and your script looks fine on a first glance as well) - can you provide me with a site where it's failing?

**Comment by hhhaiai** [comment]
I can some problem also.  my environment is window+ + cygwin. please check type on windows

**Comment by carwyn** [comment]
I'm getting this with:
```
v0.13/examples/modify_response_body.py
```
Against most of the stackoverflow pages.

```
$ mitmdump -q --anticache --stream 500k -s "collectors/proxy/replace.py the eht"
Script error:
Traceback (most recent call last):
  File ".../.local/lib/python2.7/site-packages/libmproxy/script.py", line 123, in run
    return (True, f(self.ctx, *args, **kwargs))
  File "collectors/proxy/replace.py", line 18, in response
    context.new)
  File ".../.local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 78, in __exit__
    self.o.encode(self.ce)
  File ".../.local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 151, in encode
    self.content = encoding.encode(e, self.content)
  File ".../.local/lib/python2.7/site-packages/libmproxy/encoding.py", line 33, in encode
    return encoding_map[e](content)
  File ".../.local/lib/python2.7/site-packages/libmproxy/encoding.py", line 55, in encode_gzip
    gf.write(content)
  File "/usr/lib64/python2.7/gzip.py", line 240, in write
    if len(data) > 0:
TypeError: object of type 'int' has no len()
```

flow.response.content seems to be 0 (zero) when it happens.

**Comment by carwyn** [comment]
Modules installed at the time:

```
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.0
blinker==1.3
blivet==1.0.10
certifi==2015.4.28
cffi==0.8.6
chardet==2.2.1
ConfigArgParse==0.9.3
coverage==4.0b1
cryptography==0.9
cssselect==0.9.1
decorator==3.4.0
enum34==1.0.4
GDAL==1.11.2
hpack==1.1.0
html2text==2015.6.6
html5lib==0.999
idna==2.0
iniparse==0.4
ipaddress==1.0.7
IPy==0.81
kitchen==1.2.1
langtable==0.0.34
lxml==3.3.6
mitmproxy==0.13
netlib==0.13.1
nose==1.3.7
ntplib==0.3.2
numpy==1.9.2
passlib==1.6.2
Pillow==2.8.2
ply==3.4
policycoreutils-default-encoding==0.1
pwquality==1.2.4
pyasn1==0.1.7
pycparser==2.10
pycurl==7.19.5.1
pydot==1.0.28
pygobject==3.16.2
pygpgme==0.3
PyIscsi==1.0
pykickstart==1.99.66
pyliblzma==0.5.3
pymongo==2.5.2
pyOpenSSL==0.15.1
pyparsing==2.0.3
pyparted==3.10.3
pyperclip==1.5.12
python-augeas==0.5.0
python-dmidecode==3.10.13
python-meh==0.40
pytz===2012d
pyudev==0.16.1
pyxattr==0.5.3
requests==2.7.0
rpm-python==4.12.0.1
seobject==0.1
sepolicy==1.1
setroubleshoot==1.1
six==1.9.0
slip==0.6.3
slip.dbus==0.6.3
SSSDConfig==1.13.0
tornado==4.2.1
urlgrabber==3.10.1
urllib3==1.10.2
urwid==1.3.0
yum-metadata-parser==1.1.4
```

**Comment by mhils** [comment]
Thanks @carwyn. This is fixed on master - as a temporary workaround, you can disable the `--stream` option or only modify bodies with are not None or 0.
