### ISSUE TITLE
mitmproxy crashes while handling the Discord gateway

### ISSUE THREAD

**Issue by Not-Nik** [mitmproxy/mitmproxy#6622]
#### Problem Description
Trying to connect to Discord while mitmproxy is active, results in the following error:
```
[01:05:00.739][127.0.0.1:53692] mitmproxy has crashed!
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 380, in server_event
  File "mitmproxy/proxy/layer.py", line 156, in handle_event
  File "mitmproxy/proxy/layer.py", line 269, in handle_event
  File "mitmproxy/proxy/layer.py", line 156, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 880, in _handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 936, in event_to_child
  File "mitmproxy/proxy/layer.py", line 156, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 776, in passthrough
  File "mitmproxy/proxy/layer.py", line 156, in handle_event
  File "mitmproxy/proxy/tunnel.py", line 98, in _handle_event
  File "mitmproxy/proxy/layers/tls.py", line 485, in event_to_child
  File "mitmproxy/proxy/tunnel.py", line 153, in event_to_child
  File "mitmproxy/proxy/layer.py", line 156, in handle_event
  File "mitmproxy/proxy/tunnel.py", line 98, in _handle_event
  File "mitmproxy/proxy/tunnel.py", line 153, in event_to_child
  File "mitmproxy/proxy/layer.py", line 156, in handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 880, in _handle_event
  File "mitmproxy/proxy/layers/http/__init__.py", line 936, in event_to_child
  File "mitmproxy/proxy/layer.py", line 147, in handle_event
  File "mitmproxy/proxy/utils.py", line 26, in _check_event_type
AssertionError: Unexpected event type at HttpStream._handle_event: Expected Start|HttpEvent, got Reply(WebsocketStartHook(flow=<HTTPFlow
  request = Request(GET gateway.discord.gg:443/?encoding=json&v=9&compress=zlib-stream)
  response = Response(101, no content)
  websocket = <WebSocketData (0 messages)>
  client_conn = Client(127.0.0.1:53692, state=open, alpn=http/1.1)
  server_conn = Server(gateway.discord.gg:443, state=open, alpn=http/1.1, src_port=53693)>), None).
```

#### Steps to reproduce the behavior:
1. Run mitmproxy or mitmweb
2. Go to discord.com and log in if you haven't already
3. Monitor the event log

#### System Information
```
Mitmproxy: 10.2.1 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  macOS-14.3-x86_64-i386-64bit
```

**Comment by Not-Nik** [comment]
Nevermind, this is a duplicate of #6608, I'll update.
