### ISSUE TITLE
mitmproxy 10.2.2 returns error on IPv6 connections when using "--allow-hosts"

### ISSUE THREAD

**Issue by krt222** [mitmproxy/mitmproxy#6661]
#### Problem Description
When using mitmdump (10.2.2) with "--allow-hosts", the IPv6 connections return error of "too many values to unpack" and a traceback to the file "next_layer.py". IPv4 works correctly. Previous mitmproxy version (10.2.1) did not exhibit this problem.

Here is an example of connecting to imdb.com, which includes both IPv4 and IPv6 connections

```
[15:31:38.124] HTTP(S) proxy listening at *:8080.
[15:31:41.438][127.0.0.1:34730] client connect                                                                                                                                                        
[15:31:41.500][127.0.0.1:34730] server connect www.imdb.com:443 (52.85.152.173:443)
[15:31:42.664][127.0.0.1:34732] client connect                                                                                                                                                        
[15:31:42.691][127.0.0.1:34732] server connect m.media-amazon.com:443 ([2600:9000:2045:6000:1d:d7f6:39d3:d9e1]:443)
[15:31:42.697] Addon error: too many values to unpack (expected 2)                                                                                                                                    
Traceback (most recent call last):      
  File "/home/user/.local/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/next_layer.py", line 111, in next_layer
    nextlayer.layer = self._next_layer(                                                                                                                                                               
  File "/home/user/.local/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/next_layer.py", line 133, in _next_layer
    if self._ignore_connection(context, data_client, data_server):
  File "/home/user/.local/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/next_layer.py", line 222, in _ignore_connection
    host, port = context.server.peername                                                                                                                                                              
ValueError: too many values to unpack (expected 2)
[15:31:44.276][127.0.0.1:34744] client connect                                                                                                                                                        
[15:31:44.341][127.0.0.1:34744] server connect api.graphql.imdb.com:443 (52.85.158.29:443)
[15:31:44.395][127.0.0.1:34758] client connect                                                                                                                                                        
[15:31:44.441][127.0.0.1:34758] server connect api.graphql.imdb.com:443 (52.85.158.19:443)
[15:31:44.526][127.0.0.1:34762] client connect                                                     
[15:31:44.538][127.0.0.1:34776] client connect                                                     
[15:31:44.542][127.0.0.1:34762] server connect m.media-amazon.com:443 ([2600:9000:2045:6000:1d:d7f6:39d3:d9e1]:443)
[15:31:44.544] Addon error: too many values to unpack (expected 2)                                                                                                                                    
Traceback (most recent call last):     
  File "/home/user/.local/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/next_layer.py", line 111, in next_layer 
    nextlayer.layer = self._next_layer(                                                            
  File "/home/user/.local/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/next_layer.py", line 133, in _next_layer       
    if self._ignore_connection(context, data_client, data_server):
  File "/home/user/.local/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/next_layer.py", line 222, in _ignore_connection
    host, port = context.server.peername      
ValueError: too many values to unpack (expected 2)
```

#### Steps to reproduce the behavior:
1. mitmdump --allow-hosts '^somehost\.com$'
2. Connect with your browser to an IPv6-only or a hybrid IPv4/IPv6 site (e.g. imdb.com).

#### System Information
Mitmproxy: 10.2.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-5.15.0-94-generic-x86_64-with-glibc2.35

**Comment by errorxyz** [comment]
I think #6614 resolves this issue
