### ISSUE TITLE
what's the matter about SSL_DEFAULT_METHOD?

### ISSUE THREAD

**Issue by mrlzh** [mitmproxy/mitmproxy#668]
I get this error:
Traceback (most recent call last):
  File "proxy.py", line 9, in <module>
    from libmproxy import controller, proxy
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/__init__.py", line 2, in <module>
    from .config import ProxyConfig, process_proxy_options
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/config.py", line 31, in <module>
    class ProxyConfig:
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy-0.12.2-py2.7.egg/libmproxy/proxy/config.py", line 51, in ProxyConfig
    ssl_version_client=tcp.SSL_DEFAULT_METHOD,
AttributeError: 'module' object has no attribute 'SSL_DEFAULT_METHOD'

I have installed netlib v0.12.1.help me please

**Comment by mhils** [comment]
Please use our guide in the [README](https://github.com/mitmproxy/mitmproxy#hacking) to install mitmproxy from master. If you use mitmproxy from master, you need netlib from master as well.

Cheers,
Max
