### ISSUE TITLE
Reading file from stdin does not work

### ISSUE THREAD

**Issue by jaywor1** [mitmproxy/mitmproxy#6704]
#### Problem Description

In option `rfile` `-` is an invalid input

### mitmweb

```
root@mitmweb-01:~# tail -f /var/log/mitmproxy/dump-merged.har | mitmweb --rfile - -n
tail: /var/log/mitmproxy/dump-merged.har: file truncated
[21:00:07.316] Web server listening at http://127.0.0.1:8081/
[21:00:07.414] No web browser found. Please open a browser and point it to http://127.0.0.1:8081/
[21:00:07.414] Cannot load flows: [Errno 2] No such file or directory: '-'
[21:00:07.414] Failed to read -: [Errno 2] No such file or directory: '-'
Traceback (most recent call last):
  File "mitmproxy/addons/readfile.py", line 63, in load_flows_from_path
FileNotFoundError: [Errno 2] No such file or directory: '-'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy/addons/readfile.py", line 71, in doread
  File "mitmproxy/addons/readfile.py", line 67, in load_flows_from_path
mitmproxy.exceptions.FlowReadException: [Errno 2] No such file or directory: '-'
Errors logged during startup, exiting...
root@mitmweb-01:~# 
```

### mitmproxy
Really mess-ups terminal and i get this error
```
Invalid filter expression: 'on": "1.1"'
```

I tested the file running it with a `-r` option and it normally loads the file.

#### Steps to reproduce the behavior:
1. `tail -f /var/log/mitmproxy/dump-merged.har | mitmweb --rfile - -n`

#### System Information
```
Mitmproxy: 10.2.1 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-6.1.0-18-amd64-x86_64-with-glibc2.36
```

**Comment by mhils** [comment]
We're currently using the ReadFileStdin addon for mitmdump only, but I think we can enable it for mitmweb as well. For mitmproxy it won't work because we need stdin for user input.

Contributions welcome!

**Comment by jaywor1** [comment]
> We're currently using the ReadFileStdin addon for mitmdump only, but I think we can enable it for mitmweb as well....

Could you enable it please :pray:  I don't really know how and where (in the source code).

> For mitmproxy it won't work because we need stdin for user input.

That makes sense :D, fortunately I just need mitmweb

**Comment by jaywor1** [comment]
> Could you enable it please 🙏 I don't really know how and where (in the source code).

After some grep stuff I created PR: https://github.com/mitmproxy/mitmproxy/pull/6732

**Comment by jaywor1** [comment]
forgot to close this issue :smile: 

viz. https://github.com/mitmproxy/mitmproxy/pull/6732#issuecomment-1989489673
