### ISSUE TITLE
Deamonized mode

### ISSUE THREAD

**Issue by thedrow** [mitmproxy/mitmproxy#688]
Allow mitmproxy to be used in the background without the console UI.
This is useful for API testing in CI.

**Comment by Kriechi** [comment]
Could you explain a bit more?
Maybe `mitmdump` useful for you in some way?
What do you want to achieve? What are the current limitations you are experiencing?

**Comment by thedrow** [comment]
I'd like to use the reverse proxy for recording and replaying requests during our acceptance tests.
Since I'm running it in the background I don't need a console.

**Comment by thedrow** [comment]
When trying to use mitmproxy in the background I get:
```
mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
Traceback (most recent call last):
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 478, in run
    self.loop.run()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/raw_display.py", line 426, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/raw_display.py", line 500, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/raw_display.py", line 634, in _getch_nodelay
    return self._getch(0)
  File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/urwid/raw_display.py", line 544, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found
```
which makes sense if urwid is always being used.

**Comment by mhils** [comment]
As mentioned by @Kriechi - check out `mitmdump`, the headless version of mitmproxy.
