### ISSUE TITLE
Exiting mitmdump via ctrl+c can "crash" it

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#6908]
#### Problem Description

Not sure if this is worth fixing. I noticed that during bootup, if you time it just right (or wrong), you'll get this:

**10.3.0**

```
 $ ./mitmdump
^CTraceback (most recent call last):
  File "mitmdump.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mitmproxy/tools/main.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mitmproxy/master.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mitmproxy/addons/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mitmproxy/addons/clientplayback.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mitmproxy/options.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mitmproxy/optmanager.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "ruamel/yaml/__init__.py", line 51, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "ruamel/yaml/cyaml.py", line 4, in <module>
  File "_ruamel_yaml.pyx", line 20, in init ruamel.yaml.clib._ruamel_yaml
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
  File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
  File "PyInstaller/loader/pyimod01_archive.py", line 149, in extract
KeyboardInterrupt
[10898] Failed to execute script 'mitmdump' due to unhandled exception!
```

**main venv**

```
$ mitmdump 
^CTraceback (most recent call last):
  File "/src/mitmproxy/venv/bin/mitmdump", line 5, in <module>
    from mitmproxy.tools.main import mitmdump
  File "/src/mitmproxy/mitmproxy/tools/main.py", line 15, in <module>
    from mitmproxy import master
  File "/src/mitmproxy/mitmproxy/master.py", line 5, in <module>
    from .addons import termlog
  File "/src/mitmproxy/mitmproxy/addons/__init__.py", line 19, in <module>
    from mitmproxy.addons import onboarding
  File "/src/mitmproxy/mitmproxy/addons/onboarding.py", line 3, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/src/mitmproxy/mitmproxy/addons/onboardingapp/__init__.py", line 3, in <module>
    from flask import Flask
  File "/src/mitmproxy/venv/lib/python3.12/site-packages/flask/__init__.py", line 6, in <module>
    from .app import Flask as Flask
  File "/src/mitmproxy/venv/lib/python3.12/site-packages/flask/app.py", line 20, in <module>
    from werkzeug.routing import BuildError
  File "/src/mitmproxy/venv/lib/python3.12/site-packages/werkzeug/routing/__init__.py", line 123, in <module>
    from .map import Map as Map
  File "/src/mitmproxy/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 28, in <module>
    from .matcher import StateMachineMatcher
  File "/src/mitmproxy/venv/lib/python3.12/site-packages/werkzeug/routing/matcher.py", line 12, in <module>
    from .rules import Rule
  File "/src/mitmproxy/venv/lib/python3.12/site-packages/werkzeug/routing/rules.py", line 68, in <module>
    _converter_args_re = re.compile(
                         ^^^^^^^^^^^
  File "/usr/lib/python3.12/re/__init__.py", line 228, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/re/__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/re/_compiler.py", line 747, in compile
    code = _code(p, flags)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/re/_compiler.py", line 580, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.12/re/_compiler.py", line 128, in _compile
    _compile(code, p, _combine_flags(flags, add_flags, del_flags))
  File "/usr/lib/python3.12/re/_compiler.py", line 174, in _compile
    _compile(code, av, flags)
  File "/usr/lib/python3.12/re/_compiler.py", line 111, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.12/re/_compiler.py", line 86, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/re/_compiler.py", line 325, in _optimize_charset
    out.append((LITERAL, p))
KeyboardInterrupt

```

#### Steps to reproduce the behavior:
1. `mitmdump`
2. `ctrl + c` just right 👌

#### System Information

```
$ ./mitmdump --version
Mitmproxy: 10.3.0 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-6.5.0-35-generic-x86_64-with-glibc2.38

$ mitmdump --version
Mitmproxy: 11.0.0.dev (+523, commit fa8b899)
Python:    3.12.0
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-6.5.0-35-generic-x86_64-with-glibc2.38
```

**Comment by Prinzhorn** [comment]
But this also happens with the venv? Or are we doing some magical things that PyInstaller requires that has an effect even when running without it?

**Comment by Prinzhorn** [comment]
If you can confirm this is an issue exclusive to bootstrapping, then I don't see a reason fix it. I'm probably the only person to ever trigger this :smile:
