### ISSUE TITLE
Crashed on Elementary OS

### ISSUE THREAD

**Issue by djsan15** [mitmproxy/mitmproxy#693]
I got the following error while tracking some requests from my android phone.
This is the crash report:

    mitmproxy --host

    (mitmproxy:3429): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

    (mitmproxy:3429): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

    (mitmproxy:3429): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

    (mitmproxy:3429): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

    (mitmproxy:3429): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
    Gtk-Message: Failed to load module "canberra-gtk-module"
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 499, in run
    self.loop.run()
    File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
    File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
    File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 678, in run
    self._loop()
    File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
    File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
    File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
    File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
    File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
    File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
    File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
    File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/statusbar.py", line 123, in keypress
    return self.ab.keypress(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/statusbar.py", line 85, in keypress
    self._w.keypress(size, k)
    AttributeError: 'Text' object has no attribute 'keypress'

    mitmproxy has crashed!

**Comment by mhils** [comment]
Thanks. Can you tell us what you did/which keys you pressed to trigger this?

**Comment by djsan15** [comment]
I don't remember the keys as I was navigating through requests and responses.
May be some combination of keys as I was using the keyboard shortcuts to navigate.
