### ISSUE TITLE
pip install mitmproxy failure

### ISSUE THREAD

**Issue by tiam-bloom** [mitmproxy/mitmproxy#6945]
#### Problem Description
A clear and  description of what the bug is.

#### Steps to reproduce the behavior:
```shell
python-study on  main [!+?] via  v14.21.3 via 🐍 v3.12.0 
❯ pip install mitmproxy
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting mitmproxy
  Using cached https://mirrors.aliyun.com/pypi/packages/50/35/93fc42aac8faf6c5ff391827a4e4fb5841cd309afe91c9989a781ba2872a/mitmproxy-10.3.1-py3-none-any.whl (1.6 MB)
Collecting aioquic<=1.0.0,>=1.0.0 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/b8/7b/4da9a13cbce748d598da85ec005fe028c82c617d3ed035d7f7d9e042aa70/aioquic-1.0.0-cp38-abi3-win_amd64.whl (1.5 MB)
Collecting asgiref<=3.8.1,>=3.2.10 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/39/e3/893e8757be2612e6c266d9bb58ad2e3651524b5b40cf56761e985a28b13e/asgiref-3.8.1-py3-none-any.whl (23 kB)
Requirement already satisfied: Brotli<=1.1.0,>=1.0 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (1.1.0)
Requirement already satisfied: certifi>=2019.9.11 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (2023.7.22)
Collecting cryptography<42.1,>=42.0 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/a2/7b/b0d330852dd5953daee6b15f742f15d9f18e9c0154eb4cfcc8718f0436da/cryptography-42.0.8-cp39-abi3-win_amd64.whl (2.9 MB)
Requirement already satisfied: flask<=3.0.3,>=3.0 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (3.0.3)
Requirement already satisfied: h11<=0.14.0,>=0.11 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (0.14.0)
Requirement already satisfied: h2<=4.1.0,>=4.1 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (4.1.0)
Requirement already satisfied: hyperframe<=6.0.1,>=6.0 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (6.0.1)
Requirement already satisfied: kaitaistruct<=0.10,>=0.10 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (0.10)
Collecting ldap3<=2.9.1,>=2.8 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/4e/f6/71d6ec9f18da0b2201287ce9db6afb1a1f637dedb3f0703409558981c723/ldap3-2.9.1-py2.py3-none-any.whl (432 kB)
Collecting mitmproxy-rs<0.6,>=0.5.1 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/6d/a9/1c238664254212670b69f2b148951e27b63ce416365815c92d7505496f25/mitmproxy_rs-0.5.2-cp310-abi3-win_amd64.whl (1.1 MB)
Requirement already satisfied: msgpack<=1.0.8,>=1.0.0 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (1.0.8)
Collecting passlib<=1.7.4,>=1.6.5 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/3b/a4/ab6b7589382ca3df236e03faa71deac88cae040af60c071a78d254a62172/passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Requirement already satisfied: protobuf<=5.27.0,>=3.14 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (3.20.2)
Requirement already satisfied: pyOpenSSL<=24.1.0,>=22.1 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (23.3.0)
Requirement already satisfied: pyparsing<=3.1.2,>=2.4.2 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (3.1.2)
Collecting pyperclip<=1.8.2,>=1.6.0 (from mitmproxy)
  Using cached pyperclip-1.8.2-py3-none-any.whl
Collecting ruamel.yaml<=0.18.6,>=0.16 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/73/67/8ece580cc363331d9a53055130f86b096bf16e38156e33b1d3014fffda6b/ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
Requirement already satisfied: sortedcontainers<=2.4.0,>=2.3 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (2.4.0)
Requirement already satisfied: tornado<=6.4,>=6.2 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (6.4)
Collecting urwid-mitmproxy<2.2,>=2.1.1 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/e7/f8/f2e8fe84e413eed791c8eb45b2a7d9937b607e9b7d402b123c9849247a7d/urwid-mitmproxy-2.1.2.1.tar.gz (634 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wsproto<=1.2.0,>=1.0 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (1.2.0)
Collecting publicsuffix2<=2.20191221,>=2.20190812 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/9d/16/053c2945c5e3aebeefb4ccd5c5e7639e38bc30ad1bdc7ce86c6d01707726/publicsuffix2-2.20191221-py2.py3-none-any.whl (89 kB)
Requirement already satisfied: zstandard<=0.22.0,>=0.15 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (0.22.0)
Requirement already satisfied: pydivert<=2.1.0,>=2.0.3 in f:\programsdev\python\python312\lib\site-packages (from mitmproxy) (2.1.0)
Collecting pylsqpack<0.4.0,>=0.3.3 (from aioquic<=1.0.0,>=1.0.0->mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/83/6b/e62ec15297e3516e7b1c898cb94bd856781903ad9eb59fd84e23aaa7fe03/pylsqpack-0.3.18-cp38-abi3-win_amd64.whl (154 kB)
Collecting pyOpenSSL<=24.1.0,>=22.1 (from mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/54/a7/2104f674a5a6845b04c8ff01659becc6b8978ca410b82b94287e0b1e018b/pyOpenSSL-24.1.0-py3-none-any.whl (56 kB)
Collecting service-identity>=24.1.0 (from aioquic<=1.0.0,>=1.0.0->mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/3b/92/44669afe6354a7bed9968013862118c401690d8b5a805bab75ac1764845f/service_identity-24.1.0-py3-none-any.whl (12 kB)
Requirement already satisfied: cffi>=1.12 in f:\programsdev\python\python312\lib\site-packages (from cryptography<42.1,>=42.0->mitmproxy) (1.16.0)
Requirement already satisfied: Werkzeug>=3.0.0 in f:\programsdev\python\python312\lib\site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (3.0.2)
Requirement already satisfied: Jinja2>=3.1.2 in f:\programsdev\python\python312\lib\site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in f:\programsdev\python\python312\lib\site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (2.1.2)
Requirement already satisfied: click>=8.1.3 in f:\programsdev\python\python312\lib\site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in f:\programsdev\python\python312\lib\site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (1.7.0)
Requirement already satisfied: hpack<5,>=4.0 in f:\programsdev\python\python312\lib\site-packages (from h2<=4.1.0,>=4.1->mitmproxy) (4.0.0)
Requirement already satisfied: pyasn1>=0.4.6 in f:\programsdev\python\python312\lib\site-packages (from ldap3<=2.9.1,>=2.8->mitmproxy) (0.5.0)
Collecting mitmproxy_windows==0.5.2 (from mitmproxy-rs<0.6,>=0.5.1->mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/bf/88/dfb5dd7237f4838ff0594fa47c8b64dc7c171758c7e28efa9ae4e25783e8/mitmproxy_windows-0.5.2-py3-none-any.whl (475 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml<=0.18.6,>=0.16->mitmproxy)
  Using cached https://mirrors.aliyun.com/pypi/packages/10/d2/52a3d810d0b5b3720725c0504a27b3fced7b6f310fe928f7019d79387bc1/ruamel.yaml.clib-0.2.8-cp312-cp312-win_amd64.whl (115 kB)
Requirement already satisfied: pycparser in f:\programsdev\python\python312\lib\site-packages (from cffi>=1.12->cryptography<42.1,>=42.0->mitmproxy) (2.21)
Requirement already satisfied: colorama in f:\programsdev\python\python312\lib\site-packages (from click>=8.1.3->flask<=3.0.3,>=3.0->mitmproxy) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in f:\programsdev\python\python312\lib\site-packages (from Jinja2>=3.1.2->flask<=3.0.3,>=3.0->mitmproxy) (2.1.5)
Requirement already satisfied: attrs>=19.1.0 in f:\programsdev\python\python312\lib\site-packages (from service-identity>=24.1.0->aioquic<=1.0.0,>=1.0.0->mitmproxy) (23.1.0)
Requirement already satisfied: pyasn1-modules in f:\programsdev\python\python312\lib\site-packages (from service-identity>=24.1.0->aioquic<=1.0.0,>=1.0.0->mitmproxy) (0.3.0)
Building wheels for collected packages: urwid-mitmproxy
  Building wheel for urwid-mitmproxy (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\urwid
      copying urwid\canvas.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\command_map.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\compat.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\container.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\curses_display.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\decoration.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\display_common.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\escape.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\font.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\graphics.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\html_fragment.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\lcd_display.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\listbox.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\main_loop.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\monitored_list.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\numedit.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\old_str_util.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\raw_display.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\signals.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\split_repr.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\text_layout.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\treetools.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\util.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\version.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\vterm.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\web_display.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\widget.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\wimp.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\win32.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\_async_kw_event_loop.py -> build\lib.win-amd64-cpython-312\urwid
      copying urwid\__init__.py -> build\lib.win-amd64-cpython-312\urwid
      creating build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_canvas.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_container.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_decoration.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_doctests.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_escapes.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_event_loops.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_graphics.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_listbox.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_str_util.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_text_layout.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_util.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_vterm.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\test_widget.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\util.py -> build\lib.win-amd64-cpython-312\urwid\tests
      copying urwid\tests\__init__.py -> build\lib.win-amd64-cpython-312\urwid\tests
      running build_ext
      building 'urwid.str_util' extension
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Tiam\AppData\Local\Temp\pip-install-ivzeaeuu\urwid-mitmproxy_5ea9023aaef840279643b6a08accca58\setup.py", line 84, in <module>
          setup(**setup_d)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\command\bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\command\build_ext.py", line 93, in run
          _build_ext.run(self)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\command\build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\msvc.py", line 187, in _msvc14_get_vc_env
          vcvarsall, vcruntime = _msvc14_find_vcvarsall(plat_spec)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\msvc.py", line 131, in _msvc14_find_vcvarsall
          _, best_dir = _msvc14_find_vc2017()
                        ^^^^^^^^^^^^^^^^^^^^^
        File "F:\ProgramsDev\Python\Python312\Lib\site-packages\setuptools\msvc.py", line 110, in _msvc14_find_vc2017
          .decode(encoding="mbcs", errors="strict")
           ^^^^^^
      AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for urwid-mitmproxy
  Running setup.py clean for urwid-mitmproxy
Failed to build urwid-mitmproxy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (urwid-mitmproxy)
```
1. 
2. 
3. 

Env:
windows11
python3.12
```sh
❯ pip --version
pip 24.1 from F:\ProgramsDev\Python\Python312\Lib\site-packages\pip (python 3.12)
```

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by mhils** [comment]
This is not a mitmproxy bug, there's something weird with your installation of setuptools.
