### ISSUE TITLE
Make Rust default but optional dependency

### ISSUE THREAD

**Issue by barracuda156** [mitmproxy/mitmproxy#6947]
#### Problem Description
`mitmproxy` does not run without Rust components.
Rust is broken on some non-mainstream platforms.
On mainstream platforms it is still a very heavy dependency to build.

#### Proposal
Could we make Rust stuff optional? Enabled by default, but so that it can be disabled manually.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/master.py", line 54, in run_loop
    loop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urwid/main_loop.py", line 377, in _run
    self.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urwid/main_loop.py", line 353, in start
    self._reset_input_descriptors()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urwid/main_loop.py", line 373, in _reset_input_descriptors
    self.screen.hook_event_loop(self.event_loop, self._update)
    from .addons import termlog
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/addons/__init__.py", line 4, in <module>
    from mitmproxy.addons import blocklist
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/addons/blocklist.py", line 6, in <module>
    from mitmproxy import flowfilter
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/flowfilter.py", line 45, in <module>
    from mitmproxy import dns
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/dns.py", line 13, in <module>
    from mitmproxy import flow
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/flow.py", line 12, in <module>
    from mitmproxy import connection
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/connection.py", line 15, in <module>
    from mitmproxy.proxy import mode_specs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mitmproxy/proxy/mode_specs.py", line 34, in <module>
    import mitmproxy_rs
ModuleNotFoundError: No module named 'mitmproxy_rs'
```

**Comment by mhils** [comment]
I understand where you are coming from - we've thought about this as well when introducing Rust. Providing a build without Rust components would be a significant maintenance and support burden unfortunately. Going forward, we expect to increasingly adopt more Rust components, which would contribute to this problem. Long story short, we feel it's not worth the effort and Rust will stay a required component.

We do plan to extend our platform coverage to Linux arm64 and Windows arm64 builds soon if that helps.

**Comment by barracuda156** [comment]
@mhils This is disappointing, but what to do.
Could you please refer me to the last version free from Rust?

**Comment by mhils** [comment]
That's probably the release before we introduced WireGuard mode.

**Comment by barracuda156** [comment]
Going by depspecs, the last release not explicitly requiring rusty py-openssl and py-cryptography is 7.0.4: https://github.com/mitmproxy/mitmproxy/blob/c18d0ff246a48f45578dc7983d9d7f121bba415c/setup.py#L75-L85

**Comment by r00t-** [comment]
i got here trying to install on my postmarketOS phone (it actually got to compiling with rustc, but then failed due to some obscure reason i did not have the time to debug).

i found that up to [8.1.1](https://github.com/mitmproxy/mitmproxy/releases/tag/v8.1.1) worked (latest 8.x),
then the wireguard mode from [!5562](https://github.com/mitmproxy/mitmproxy/pull/5562/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R85) introduced rust code that has to be compiled at installation.
(and mitmproxy_wireguard became mitmproxy_rs in https://github.com/mitmproxy/mitmproxy/commit/a7e50c793e9c6840d9f0fc162893e293477a358e )
