### ISSUE TITLE
Crash when `--ssl-insecure` is enabled in reverse mode

### ISSUE THREAD

**Issue by vlzware** [mitmproxy/mitmproxy#6968]
#### Problem Description
When starting the latest version of mitmproxy (10.3.1) in reverse mode with a server using self-signed certificate it crashes if `--ssl-insecure` is enabled

#### Steps to reproduce the behavior:
1. `mitmproxy.exe  --listen-host 0.0.0.0 -m reverse:https://<my_server_ip>@443`
I get a TLS handshake failed, because the server certificate is self-signed:
```
Server TLS handshake failed. Certificate verify failed: self-signed certificate in certificate chain
```
2.  `mitmweb.exe  --listen-host 0.0.0.0 --ssl-insecure -m reverse:https://<my_server_ip>@443`
```
[10:36:49.235] reverse proxy to https://<my_server_ip> listening at *:443.
[10:36:49.238] Web server listening at http://127.0.0.1:8081/
[10:36:55.506][127.0.0.1:30879] client connect
[10:36:55.511][127.0.0.1:30881] client connect
[10:36:55.538][127.0.0.1:30879] server connect <my_server_ip>:443
[10:36:55.539][127.0.0.1:30879] client disconnect
[10:36:55.540][127.0.0.1:30879] server disconnect <my_server_ip>:443
[10:36:55.541][127.0.0.1:30881] server connect <my_server_ip>:443
[10:36:55.792][127.0.0.1:30881] mitmproxy has crashed!
Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 380, in server_event
  File "mitmproxy\proxy\layer.py", line 157, in handle_event
  File "mitmproxy\proxy\layer.py", line 270, in handle_event
  File "mitmproxy\proxy\layer.py", line 157, in handle_event
  File "mitmproxy\proxy\tunnel.py", line 70, in _handle_event
  File "mitmproxy\proxy\layers\tls.py", line 367, in receive_handshake_data
  File "mitmproxy\certs.py", line 89, in from_pyopenssl
  File "OpenSSL\crypto.py", line 1207, in to_cryptography
ValueError: error parsing asn1 value: ParseError { kind: EncodedDefault, location: ["Certificate::tbs_cert", "TbsCertificate::raw_extensions", 1, "Extension::critical"] }
```
The behavior is the same with mitmweb and mitmproxy. The Linux version crashes as well.

#### System Information
Mitmproxy: 10.3.1 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Windows-11-10.0.22631-SP0

Mitmproxy: 10.3.1 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Linux-6.1.0-21-amd64-x86_64-with-glibc2.36

**Comment by mhils** [comment]
Could you provide me with a certificate that exhibits this behavior?
