### ISSUE TITLE
Windows: mitmdump Requires Administrator Privledges

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#702]
I'm using mitmdump v0.13 on Windows 10. If I don't run in Administrator mode, mitmdump gives an "Access Denied" error. Works fine in Administrator mode. Is this a know issue? I didn't see it documented anywhere.

**Comment by mhils** [comment]
Works fine for me in mitmproxy's regular mode - are you running mitmproxy
as a transparent proxy?

BSalita <notifications@github.com> schrieb am So., 2. Aug. 2015 16:03:

**Comment by BSalita** [comment]
Yes, "mitmdump -T --host". Do you need a stack dump?

**Comment by BSalita** [comment]
Confirming that "Access Denied" occurs with -T and not -R.

Traceback (most recent call last):
  File "C:\Python27\Scripts\mitmdump-script.py", line 9, in <module>
    load_entry_point('mitmproxy==0.13', 'console_scripts', 'mitmdump')()
  File "C:\Python27\lib\site-packages\libmproxy\main.py", line 78, in mitmdump
    proxy_config = process_proxy_options(parser, options)
  File "C:\Python27\lib\site-packages\libmproxy\proxy\config.py", line 219, in process_proxy_options
    ssl_upstream_trusted_ca=options.ssl_upstream_trusted_ca
  File "C:\Python27\lib\site-packages\libmproxy\proxy\config.py", line 69, in __init__
    self.mode = TransparentProxyMode(platform.resolver(), ssl_ports)
  File "C:\Python27\lib\site-packages\libmproxy\platform\windows.py", line 22, in __init__
    TransparentProxy.setup()
  File "C:\Python27\lib\site-packages\libmproxy\platform\windows.py", line 232, in setup
    proxifier = TransparentProxy()
  File "C:\Python27\lib\site-packages\libmproxy\platform\windows.py", line 198, in __init__
    self.driver.register()
  File "C:\Python27\lib\site-packages\pydivert\decorators.py", line 34, in wrapper
    result = funct(instance, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pydivert\windivert.py", line 300, in register
    self.open_handle("false").close()
  File "C:\Python27\lib\site-packages\pydivert\windivert.py", line 126, in open_handle
    return Handle(self, filter, layer, priority, flags, self.encoding).open()
  File "C:\Python27\lib\site-packages\pydivert\decorators.py", line 37, in wrapper
    raise ctypes.WinError(code=retcode)
WindowsError: [Error 5] Access is denied.

**Comment by mhils** [comment]
This is expected - we should probably ask for elevated privileges at startup. Contributions for this are welcome!

**Comment by jessesanford** [comment]
I am running in a windows powershell with administrator privs and I also run "mitmdump.exe -T -v -d" as the administrator user and I get no output from mitmdump. It seems to hang without doing any real work. I am not sure how to debug? Other invocations of it work fine. mitmdump --version for instance will spit out "mitmdump 0.17" and then exit correctly. @mhils Any ideas?

**Comment by mhils** [comment]
@jessesanford:
You can start ``mitmproxy/platform/windows.py` separately first (as admin) and then start `mitmdump -T`. I suspect you'll probably get errors with `windows.py` already.

**Comment by jessesanford** [comment]
Yes starting windows.py seperately worked. Is it the case that step is always required? Any reason you can think of that mitmdump.exe is not correctly invoking it for me (if it's supposed to) ?

**Comment by mhils** [comment]
Oh, I missed that you are using the precompiled binary. In this case, we probably have a bug with pydivert which fails to install/load WinDivert. The workaround is to just use mitmproxy/mitmdump from source.
I'd be super happy if anyone goes and chases that pydivert bug down.

**Comment by mhils** [comment]
Fixed that with PyDivert 1.0.2!
