### ISSUE TITLE
AssertionError in _http1 after multiple calls

### ISSUE THREAD

**Issue by gdiepen** [mitmproxy/mitmproxy#7027]
#### Problem Description
I used mitmproxy to create an automatic upstream proxy switcher that based on the whether a certain host is available will use a specific upstream proxy, and otherwise it will route the traffic through a second instance of mitmproxy that functions just as a direct proxy (because you can only change upstream proxies, not switch from upstream proxy to direct connection).

Because of a new way of distributing my switcher solution, I now have a hard dependency on python 3.12 and therefore needed to upgrade from the mitmproxy 9.0.0 I was using (and was working perfectly) to a recent version. Therefore did an upgrade to mitmproxy 10.3.1

With mitmproxy 10.3.1, I started seeing assertion errors every now and then:

```
Traceback (most recent call last):
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\server.py", line 380, in server_event
    for command in layer_commands:
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layer.py", line 157, in handle_event
    command = command_generator.send(send)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layer.py", line 270, in handle_event
    yield from self._handle(event)
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layer.py", line 157, in handle_event
    command = command_generator.send(send)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\__init__.py", line 880, in _handle_event
    yield from self.event_to_child(stream, event)
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\__init__.py", line 961, in event_to_child
    yield from self.get_connection(command)
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\__init__.py", line 1003, in get_connection
    yield from self.event_to_child(
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\__init__.py", line 957, in event_to_child
    yield from self.event_to_child(conn, command.event)
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\__init__.py", line 936, in event_to_child
    for command in child.handle_event(event):
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layer.py", line 157, in handle_event
    command = command_generator.send(send)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\tunnel.py", line 98, in _handle_event
    yield from self.event_to_child(event)
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\tunnel.py", line 153, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layer.py", line 157, in handle_event
    command = command_generator.send(send)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layer.py", line 157, in handle_event
    command = command_generator.send(send)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\_http1.py", line 71, in _handle_event
    yield from self.send(event)
  File "c:\Users\Guido\switcher_venv\Lib\site-packages\mitmproxy\proxy\layers\http\_http1.py", line 353, in send
    assert self.stream_id == event.stream_id
AssertionError
```

I have narrowed it down to something that changed between 10.1.6 (which does NOT show this error) and 10.2.0 (which started to introduce this error)

#### Steps to reproduce the behavior:
1. Start mitmweb in upstream mode (`--mode upstream:http://some_other_proxy --set stream_large_bodies=1`) and listening to for examle port 7070
2. Start a podman ubuntu container (`podman run -it --rm ubuntu bash`) and set the proxy for http/https to `http://host.containers.internal:7070`
3. Run apt-get update

After about 9 connections, all of a sudden I get the above mentioned assertion error. However, apt-get probably does a retry, and eventually it finishes.

#### System Information
Mitmproxy: 10.3.1
Python:    3.12.0
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Windows-10-10.0.19045-SP0

**Comment by mhils** [comment]
Thank you for the detailed report! A regression from 10.1.6 to 10.2.0 is a bit surprising because there have been no HTTP-related changes in there beyond ignore_domains, which is not used here. I'm unfortunately unable to reproduce your original issue on Linux.

Can you reproduce with `--set proxy_debug -vvv` and (if yes) share the log here? Thanks!

**Comment by gdiepen** [comment]
I can indeed reproduce it with the proxy_debug.

For sake of completeness, I attach the logs for running the same command apt-get update in 10.1.6, 10.2.0, and 10.3.1.  

From what I can see, there is only one connection being made and it seems multiple calls are made over this connection, could that be a problem?
[logs_10.1.6.txt](https://github.com/user-attachments/files/16278778/logs_10.1.6.txt)
[logs_10.2.0.txt](https://github.com/user-attachments/files/16278779/logs_10.2.0.txt)
[logs_10.3.1.txt](https://github.com/user-attachments/files/16278780/logs_10.3.1.txt)


If I need to test anything else, happy to run additional tests

**Comment by gdiepen** [comment]
Maybe also useful, this is the output of pip list for the 10.3.1 environment:
```
Package          Version
---------------- ----------
aioquic          1.0.0
asgiref          3.8.1
attrs            23.2.0
blinker          1.8.2
Brotli           1.1.0
certifi          2024.7.4
cffi             1.16.0
click            8.1.7
cryptography     42.0.8
Flask            3.0.3
h11              0.14.0
h2               4.1.0
hpack            4.0.0
hyperframe       6.0.1
itsdangerous     2.2.0
Jinja2           3.1.4
kaitaistruct     0.10
ldap3            2.9.1
MarkupSafe       2.1.5
mitmproxy        10.3.1
mitmproxy_rs     0.5.2
msgpack          1.0.8
passlib          1.7.4
pip              24.0
protobuf         5.27.0
publicsuffix2    2.20191221
pyasn1           0.6.0
pyasn1_modules   0.4.0
pycparser        2.22
pylsqpack        0.3.18
pyOpenSSL        24.1.0
pyparsing        3.1.2
pyperclip        1.8.2
ruamel.yaml      0.18.6
ruamel.yaml.clib 0.2.8
service-identity 24.1.0
setuptools       69.5.1
sortedcontainers 2.4.0
tornado          6.4
urwid-mitmproxy  2.1.2.1
Werkzeug         3.0.3
wheel            0.43.0
wsproto          1.2.0
zstandard        0.22.0
```

This is the output for the 10.1.6 environment:
```
Package           Version
----------------- ----------
aioquic-mitmproxy 0.9.21.1
asgiref           3.7.2
attrs             23.2.0
blinker           1.8.2
Brotli            1.1.0
certifi           2024.7.4
cffi              1.16.0
click             8.1.7
cryptography      41.0.7
Flask             3.0.3
h11               0.14.0
h2                4.1.0
hpack             4.0.0
hyperframe        6.0.1
itsdangerous      2.2.0
Jinja2            3.1.4
kaitaistruct      0.10
ldap3             2.9.1
MarkupSafe        2.1.5
mitmproxy         10.1.6
mitmproxy_rs      0.4.1
msgpack           1.0.8
passlib           1.7.4
pip               24.0
protobuf          4.25.3
publicsuffix2     2.20191221
pyasn1            0.6.0
pyasn1_modules    0.4.0
pycparser         2.22
pylsqpack         0.3.18
pyOpenSSL         23.3.0
pyparsing         3.1.2
pyperclip         1.8.2
ruamel.yaml       0.18.6
ruamel.yaml.clib  0.2.8
service-identity  24.1.0
setuptools        69.5.1
sortedcontainers  2.4.0
tornado           6.4.1
urwid-mitmproxy   2.1.2.1
Werkzeug          3.0.3
wheel             0.43.0
wsproto           1.2.0
zstandard         0.22.0
```

I am using anaconda, but only to create separate environments with python=3.12.4 installed, all other installations were done via pip

**Comment by mhils** [comment]
Thank you for the super detailed logs! 🍰 

The failing log you posted should be perfect in theory, but I've tried to build two different test cases now based on that and still can't reproduce it. Can I ask you to do the following two things:

1. Record a PCAP capture with Wireshark during your test run (this may require to captures, one for loopback and one for your outgoing interface).
2. Replace the `assert` statement in `mitmproxy\proxy\layers\http\_http1.py", line 353` with the following:

```python
        assert self.stream_id == event.stream_id, f"{self.stream_id=} {event.stream_id=} {event.stream_id=} {self.request_done=} {self.response_done=} {self=} {len(self.buf)=}"
```

This should hopefully give more clues on what's happening here. Thanks!

**Comment by gdiepen** [comment]
Ok, with a bit of a delay, was all day out yesterday, here the requested items. I included the verbose log again (with line 353 assertion statement being changed).

Also ran two simultaneous tcpdump instances, one for the port http outside and one for the port 7070 on loopback interface lo (where the proxy is listening)

[mitmproxy_log_10.3.1.log](https://github.com/user-attachments/files/16319989/mitmproxy_log_10.3.1.log)
[dump_port_80.pcap.zip](https://github.com/user-attachments/files/16319995/dump_port_80.pcap.zip)
[dump_port_7070.pcap.zip](https://github.com/user-attachments/files/16319996/dump_port_7070.pcap.zip)

If you need me to run anything else, please let me know!

**Comment by mhils** [comment]
Thank you so much for the detailed logs! This was incredibly useful. I finally managed to repro things and track down the root cause. #7031 has a fix!

**Comment by gdiepen** [comment]
Awesome! thanks for taking the time to investigate!

Now that you found the problem, was it related to the change between 10.1.6 and 10.2.0 or was that just coincedence that now it got triggered more easily?

**Comment by mhils** [comment]
This was introduced in https://github.com/mitmproxy/mitmproxy/pull/6557/commits/0bb8298a23d8644cc2e04aa5ededb2345fe3717b, which indeed first made it into 10.2.0. :)

I still didn't manage to repro it with apt, but the last log had the final clue to get me on the right track: We were crashing with `self.response_done=False`, which means that 

https://github.com/mitmproxy/mitmproxy/blob/f45d6e970b05935e311b3a63e28261ea494f7105/mitmproxy/proxy/layers/http/_http1.py#L119

was not executed yet. But we also see
```
[13:43:57.805][127.0.0.1:57442]       << Receive(RequestEndOfMessage(stream_id=7))
```
in the logs from
https://github.com/mitmproxy/mitmproxy/blob/f45d6e970b05935e311b3a63e28261ea494f7105/mitmproxy/proxy/layers/http/_http1.py#L117

just two lines above. So there _must_ be some sort of race. That was very confusing as we spent a lot of effort to make sure the proxy core is _not_ multi-threaded (https://mitmproxy.org/posts/new-proxy-core/). So these issues shouldn't exist by design. 😅

Looking closer at the logs I found that we're starting to handle a second event in the middle of handling the first one. And I eventually realized that this happens because eager task execution kind of acts like an `await` as it pauses the current method to first execute a different task. I then built the test in #7031 to validate my assumptions and implemented a fix. :)

Thank you again for the fantastic logs! 🍰

**Comment by gdiepen** [comment]
For sake of completeness, I just installed the mitmproxy from your branch with the fix  in a brand new environment and tested it a couple of times and I can confirm that with this new version I am not able to reproduce the problem anymore!

**Comment by gdiepen** [comment]
Another question I have is when do you currently plan to have a release of mitmproxy that contains this fix?

**Comment by mhils** [comment]
No fixed timeline yet, at some point in the next two months. Would a faster new release with the fix make your life significantly easier?

**Comment by gdiepen** [comment]
It would make it easier in the way that I could release a new version of my switcher app such that less of my users will be affected by the assertion error as I don't have a way to switch back to 10.1.6 due to the fact no binary wheels exist for some dependencies for python 3.12 (which is something I can unfortunately not change due to the policies on the laptops)

**Comment by mhils** [comment]
I've triggered release CI for 10.4! :)

**Comment by gdiepen** [comment]
Awesome! Thank you very much
