### ISSUE TITLE
Concurrent decorator not supported for 'request' method.

### ISSUE THREAD

**Issue by Srijan67** [mitmproxy/mitmproxy#7044]
I am using concurrent with mitmproxy imported from mitmproxy.tools.main.
#### script.py code is: 
```
from mitmproxy import http
import logging
import time
from mitmproxy.script import concurrent

@concurrent
def request(flow: http.HTTPFlow):
    logging.info(f"handle request: {flow.request.host}{flow.request.path}")
    time.sleep(5)
    logging.info(f"start  request: {flow.request.host}{flow.request.path}")

if __name__ == '__main__':
    from mitmproxy.tools.main import mitmproxy
    mitmproxy(['-p','9999','-s', 'proxyserver.py', '--set', 'websocket=false','--set', 'stream_large_bodies=20k','--set', 'validate_inbound_headers=false', '--ssl-insecure', '--no-http2'])
```
#### Error coming: 

> Traceback (most recent call last):
>   File "C:\projects\python\proxyserver.py", line 13, in <module>
>     @concurrent
>      ^^^^^^^^^^
>   File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\mitmproxy\script\concurrent.py", line 13, in concurrent
>     raise NotImplementedError(
> NotImplementedError: Concurrent decorator not supported for 'request' method.

### Steps to reproduce the behavior:
1. on hitting `python script.py`. The error is coming
2. on hitting `mitmproxy -s script.py -p 9999 --set websocket=false --set stream_large_bodies=20k --set validate_inbound_headers=false --ssl-insecure --no-http2` directly in cmd . Error is not coming and it's working perfectly fine
3. Using asyncio. The script.py code works as well.

#### System Information
Mitmproxy: 10.2.2
Python:    3.12.2
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Windows-11-10.0.22621-SP0

**Comment by Srijan67** [comment]
I have fixed this issue by importing `from mitmproxy.tools.main import mitmproxy` above instead currently. 
```
from mitmproxy import http
import logging
import time
from mitmproxy.script import concurrent
from mitmproxy.tools.main import mitmproxy
@concurrent
def responseheaders(flow: http.HTTPFlow):
    logging.info(f"handle request: {flow.request.host}{flow.request.path}")
    time.sleep(5)
    logging.info(f"start  request: {flow.request.host}{flow.request.path}")

if __name__ == '__main__':
    mitmproxy(['-p','9999','-s', 'proxyserver.py', '--set', 'websocket=false','--set', 'stream_large_bodies=20k','--set', 'validate_inbound_headers=false', '--ssl-insecure', '--no-http2'])
```
This fixed my issue. 👍 
I will let know if any error occurs again around it here itself but for the time being I am closing this issue : )
