### ISSUE TITLE
【10.4.1】 mitm start failed: failed to get dns servers

### ISSUE THREAD

**Issue by Stephen0910** [mitmproxy/mitmproxy#7064]
#### Problem Description
After upgrading to 10.4.1 from 13.0.1, the mitm program could not be load.

#### Steps to reproduce the behavior:
1.  **pipx** --upgrade mitmproxy
2.  start mitmproxy
3. 

#### System Information
Paste the output of "mitmproxy --version" here.
**Failed**
(base) root@machine:/home/projects/mitmproxy# mitmproxy --version
Traceback (most recent call last):
  File "mitmproxy.py", line 3, in <module>
  File "mitmproxy/tools/main.py", line 137, in mitmproxy
  File "mitmproxy/tools/main.py", line 131, in run
  File "asyncio/runners.py", line 194, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 687, in run_until_complete
  File "mitmproxy/tools/main.py", line 67, in main
  File "mitmproxy/tools/console/master.py", line 50, in __init__
  File "mitmproxy/addonmanager.py", line 204, in add
  File "mitmproxy/addonmanager.py", line 194, in register
  File "mitmproxy/command.py", line 177, in collect_commands
  File "functools.py", line 995, in __get__
  File "mitmproxy/addons/dns_resolver.py", line 52, in name_servers
RuntimeError: failed to get dns servers: io error: other error
[1324413] Failed to execute script 'mitmproxy' due to unhandled exception!

**Comment by mhils** [comment]
Which OS are you on?

**Comment by Stephen0910** [comment]
`
(base) root@ttg-virtual-machine:~# uname -a
Linux ttg-virtual-machine 5.4.0-181-generic #201-Ubuntu SMP Thu Mar 28 15:39:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by Stephen0910** [comment]
When I downgraded the app version to 10.3.1, everything went back to normal.

**Comment by Stephen0910** [comment]
> Which OS are you on?

Ubuntu 20.04.6 LTS

**Comment by mhils** [comment]
Thanks! @errorxyz, can we hotfix this to use functool's `@cache` instead of `@cached_property`?

**Comment by camckee** [comment]
I get the same exception on Windows 11 using versions 10.4.0 and 10.4.1.  10.3.1 is working fine.

**Comment by mhils** [comment]
Thank you folks! @camckee, we'd be highly interested in getting the specific error message on Windows.

Irrespective of that, we'll likely ship a patch release for this today. :)

**Comment by mhils** [comment]
10.4.2 is out, which fixes the startup error. :)
