### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by guliping** [mitmproxy/mitmproxy#707]
when I run mitmweb, and open 127.0.0.1 with chrome, the problem happens.Here is the command I run:
 $ ./dev
$ source ../venv.mitmproxy/bin/activate
(venv.mitmproxy)➜  mitmproxy git:(master) ./mitmweb
Warning: You are using mitmdump 0.11.4 with netlib 0.13.1. Most likely, that won't work - please upgrade!

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/Users/guliping/work/mitmproxy/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/Users/guliping/work/mitmproxy/libmproxy/protocol/http.py", line 989, in handle_messages
    while self.handle_flow():
  File "/Users/guliping/work/mitmproxy/libmproxy/protocol/http.py", line 1052, in handle_flow
    wfile=self.c.client_conn.wfile
  File "/Users/guliping/work/mitmproxy/libmproxy/protocol/http.py", line 341, in from_stream
    req = http.read_request(
AttributeError: 'module' object has no attribute 'read_request'

**Comment by Kriechi** [comment]
As it says right there in the log:
```
Warning: You are using mitmdump 0.11.4 with netlib 0.13.1. Most likely, that won't work - please upgrade!
```

So, you need to fix that by upgrading mitmproxy to the same version as netlib.
