### ISSUE TITLE
【10.4.2】 wireguard mode dns Error

### ISSUE THREAD

**Issue by Stephen0910** [mitmproxy/mitmproxy#7074]
10.4.2 is out, which fixes the startup error. :)

_Originally posted by @mhils in https://github.com/mitmproxy/mitmproxy/issues/7064#issuecomment-2264978656_
            
[](https://github.com/mitmproxy/mitmproxy/issues/7064)

Thanks for the quick response, but unfortunately it still doesn't work in WireGuard mode! 

```

RuntimeError: failed to get dns servers: io error: other error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/addons/dns_resolver.py", line 87, in dns_request
    flow.response = await self.resolve_message(flow.request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/addons/dns_resolver.py", line 95, in resolve_message
    rrs.extend(await self.resolve_question(question))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/addons/dns_resolver.py", line 108, in resolve_question
    addrinfos = await self.resolver().lookup_ipv4(question.name)
                      ^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/addons/dns_resolver.py", line 46, in resolver
    name_servers=self.name_servers(),
                 ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/addons/dns_resolver.py", line 55, in name_servers
    raise RuntimeError(
RuntimeError: Failed to get system dns servers: failed to get dns servers: io error: other error
```

**Comment by mhils** [comment]
The error message you posted should continue with "Must set dns_name_servers option to run DNS mode.". Does setting [`dns_name_servers`](https://docs.mitmproxy.org/stable/concepts-options/#dns_name_servers) fix the issue for you?

**Comment by Stephen0910** [comment]
1.  setting a new dns_name_servers fixed the issue
2. ```
(py38) root@ttg-virtual-machine:~/.mitmproxy# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.53
dns nameserver 8.8.8.8
```
3.  ```
(py38) root@ttg-virtual-machine:~/.mitmproxy# mitmproxy --version
Traceback (most recent call last):
  File "/root/.local/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 135, in mitmproxy
    from mitmproxy.tools import console
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/tools/console/master.py", line 14, in <module>
    import urwid
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/widget/__init__.py", line 5, in <module>
    from .bar_graph import BarGraph, BarGraphError, BarGraphMeta, GraphVScale, scale_bar_values
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/widget/bar_graph.py", line 9, in <module>
    from .text import Text
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/widget/text.py", line 9, in <module>
    from urwid.util import decompose_tagmarkup, get_encoding
ImportError: cannot import name 'get_encoding' from 'urwid.util' (/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/util.py)
(py38) root@ttg-virtual-machine:~/.mitmproxy# mitmproxy --version
Traceback (most recent call last):
  File "/root/.local/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/tools/main.py", line 135, in mitmproxy
    from mitmproxy.tools import console
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/mitmproxy/tools/console/master.py", line 14, in <module>
    import urwid
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/widget/__init__.py", line 5, in <module>
    from .bar_graph import BarGraph, BarGraphError, BarGraphMeta, GraphVScale, scale_bar_values
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/widget/bar_graph.py", line 9, in <module>
    from .text import Text
  File "/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/widget/text.py", line 9, in <module>
    from urwid.util import decompose_tagmarkup, get_encoding
ImportError: cannot import name 'get_encoding' from 'urwid.util' (/root/.local/pipx/venvs/mitmproxy/lib/python3.11/site-packages/urwid/util.py)
```

By the way, I set the config data in `/root/.mitmproxy/config.yml`, but in mitmweb's option, it didn't work.

**Comment by mhils** [comment]
The third error points at an issue with your mitmproxy install. Without getting too much into that, `mitmdump --version` should work I assume?

**Comment by errorxyz** [comment]
> ```
> dns nameserver 8.8.8.8
> ```

This line should be `nameserver 8.8.8.8` and is the root cause behind mitmproxy not being able to get the system dns servers

**Comment by mhils** [comment]
> > ```
> > dns nameserver 8.8.8.8
> > ```
> 
> This line should be `nameserver 8.8.8.8` and is the root cause behind mitmproxy not being able to get the system dns servers

It looks like the file is auto-generated by systemd, so this looks like we need to fix hickory to understand that syntax. :)

**Comment by mhils** [comment]
@Stephen0910: Which OS/distro are you on? Did you do anything special to have this `dns nameserver ...` line, or is that just there for you?

**Comment by Stephen0910** [comment]
Ubuntu 20.04.6 LTS.
I have just upgraded the mitmproxy from 10.3.1. [like this issue](https://github.com/mitmproxy/mitmproxy/issues/7064) using the command `pipx upgrade mitmproxy` subsequent to the issue being fixed by you. Furthermore, I made no alterations to the DNS nameserver since it functioned properly in version 10.3.1.

**Comment by Stephen0910** [comment]
> Thanks! The third error points at an issue with your mitmproxy install. Without getting too much into that, `mitmdump --version` should work I assume?

(base) root@ttg-virtual-machine:/home/quickStart/debug_mitm# mitmdump --version
```
Mitmproxy: 10.4.2
Python:    3.11.0
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Linux-5.4.0-181-generic-x86_64-with-glibc2.31
```

**Comment by mhils** [comment]
Thanks! I've tried a few things, but I'm unable to get a "dns nameserver 8.8.8.8" line into my resolv.conf without editing it manually. Can you share some details on your setup? Did you manually configure DNS servers at some point?

**Comment by Stephen0910** [comment]
No, I don't know when the DNS server in resolv.conf was configured. The key point is that this configuration could use the WireGuard mode of mitmproxy in 10.3.1, but it didn't work after the upgrade. Now it can be used after manual configuration, so it doesn't matter whether to change it or not.

**Comment by mhils** [comment]
1. Do you recall ever setting your DNS server to 8.8.8.8 (Google DNS)? If so, how?
2. Can you share more details on your setup? Is it Ubuntu Desktop? Is it a cloud VM? Something else?

I'd basically like to understand if there are more people out there with `dns nameserver` in ther resolv.conf. If yes, we can fix it upstream and things should just work for everyone.

**Comment by Stephen0910** [comment]
> 1. Do you recall ever setting your DNS server to 8.8.8.8 (Google DNS)? If so, how?
> 2. Can you share more details on your setup? Is it Ubuntu Desktop? Is it a cloud VM? Something else?
> 
> I'd basically like to understand if there are more people out there with `dns nameserver` in ther resolv.conf. If yes, we can fix it upstream and things should just work for everyone.

1. I don't remember that I have set the DNS server, and it works fine in version 10.3.1 if I don't change any DNS name server setting.
2. There is no desktop manager in my Ubuntu server machine. I just upgraded it by 'pipx upgrade mitmproxy'
