### ISSUE TITLE
ImportError related to the cryptography library

### ISSUE THREAD

**Issue by winter-warm-sun** [mitmproxy/mitmproxy#7106]
#### Problem Description
This issue occurs when running a script agent in the background on a server and opening a proxy on the client using an IP and port number. After some time, frequent errors begin to appear the following day. The expected behavior is for the system to operate normally, but the actual behavior results in an ImportError related to the cryptography library.

#### Steps to Reproduce
1.The script agent executes in the background，Deploy on the server
2.Open the proxy on the client by IP+port number
3.Frequent errors will occur the next day
Tried through the command pip install cryptography -U update the corresponding dependencies，
the problem could be solved and executed normally at that time, but the same error would occur again the next day.

#### System Information
Mitmproxy: 10.4.2
Python:    3.10.9
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Linux-3.10.107-1-tlinux2_kvm_guest-0054-x86_64-with-glibc2.17

#### Relevant log output
Traceback (most recent call last):
File "/usr/local/bin/mitmdump", line 5, in
from mitmproxy.tools.main import mitmdump
File "/usr/local/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 15, in
from mitmproxy import master
File "/usr/local/lib/python3.10/site-packages/mitmproxy/master.py", line 5, in
from .addons import termlog
File "/usr/local/lib/python3.10/site-packages/mitmproxy/addons/init.py", line 6, in
from mitmproxy.addons import clientplayback
File "/usr/local/lib/python3.10/site-packages/mitmproxy/addons/clientplayback.py", line 25, in
from mitmproxy.proxy import layers
File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/init.py", line 3, in
from .http import HttpLayer
File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/init.py", line 14, in
from ..quic import QuicStreamEvent
File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/quic.py", line 13, in
from aioquic.h3.connection import ErrorCode as H3ErrorCode
File "/usr/local/lib/python3.10/site-packages/aioquic/h3/connection.py", line 19, in
from aioquic.quic.connection import QuicConnection, stream_is_unidirectional
File "/usr/local/lib/python3.10/site-packages/aioquic/quic/connection.py", line 21, in
from .. import tls
File "/usr/local/lib/python3.10/site-packages/aioquic/tls.py", line 41, in
from cryptography.hazmat.primitives.asymmetric.types import (
ImportError: cannot import name 'CertificateIssuerPublicKeyTypes' from 'cryptography.hazmat.primitives.asymmetric.types' (/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/types.py)

**Comment by mhils** [comment]
What's your output of `pip freeze`?
