### ISSUE TITLE
not a tnetstring: missing or invalid length prefix

### ISSUE THREAD

**Issue by 3052** [mitmproxy/mitmproxy#7132]
this script:

~~~py
from mitmproxy import ctx

def running():
   ctx.options.showhost = True
~~~

like this:

~~~
mitmproxy -r mitmproxy.py
~~~

result:

~~~
error: [18:27:31.340] Flow file corrupted.
error: [18:27:31.340] Unhandled errror in task.
Traceback (most recent call last):
  File "mitmproxy\io\io.py", line 66, in stream
  File "mitmproxy\io\tnetstring.py", line 178, in load
ValueError: not a tnetstring: missing or invalid length prefix

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy\addons\readfile.py", line 44, in load_flows
  File "mitmproxy\io\io.py", line 75, in stream
mitmproxy.exceptions.FlowReadException: Invalid data format.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy\addons\readfile.py", line 69, in doread
  File "mitmproxy\addons\readfile.py", line 62, in load_flows_from_path
  File "mitmproxy\addons\readfile.py", line 54, in load_flows
mitmproxy.exceptions.FlowReadException: Invalid data format.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy\addons\readfile.py", line 71, in doread
mitmproxy.exceptions.OptionsError: Invalid data format.
~~~

version:

~~~
Mitmproxy: 10.1.0 binary
Python:    3.11.5
OpenSSL:   OpenSSL 3.1.3 19 Sep 2023
Platform:  Windows-10-10.0.18363-SP0
~~~

**Comment by 3052** [comment]
should be:

mitmproxy -s mitmproxy.py
