### ISSUE TITLE
mitmproxy 0.12.1 crashes when adding new request

### ISSUE THREAD

**Issue by revintec** [mitmproxy/mitmproxy#718]
Symptom: when adding a new request, mitmproxy crashes(related: #426)
I'm running OS X 10.10.4, using version 0.12.1 installed through homebrew(latest version)

Reproduce: open mitmproxy, press n(create a new request), then g(for GET), then hit enter
mitmproxy crashes with the following message:
<img width="1410" alt="2015-08-10_00-51-36" src="https://cloud.githubusercontent.com/assets/8952734/9155924/4e5af1c6-3efb-11e5-8975-e3d01904d5da.png">
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 478, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/vendor/lib/python2.7/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 123, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 82, in keypress
    self.prompt_execute(self._w.get_edit_text())
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 104, in prompt_execute
    msg = p(txt, *args)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 310, in new_request
    f = self.master.create_request(method, scheme, host, port, path)
  File "/usr/local/Cellar/mitmproxy/0.12.1/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 828, in create_request
    headers = ODictCaseless()
NameError: global name 'ODictCaseless' is not defined

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...

**Comment by mhils** [comment]
Our latest release is mitmproxy 0.13. IIRC, this bug is fixed there - please upgrade.
