### ISSUE TITLE
mitmproxy has crashed.

### ISSUE THREAD

**Issue by KaarunyaKudimi** [mitmproxy/mitmproxy#7229]
#### Problem Description
TypeError: e.map is not a function

#### Steps to reproduce the behavior:
TypeError: e.map is not a function
    at CaptureSetup (http://127.0.0.1:8081/static/app.js:65:50926)
    at Ch (http://127.0.0.1:8081/static/app.js:5:55364)
    at li (http://127.0.0.1:8081/static/app.js:5:65205)
    at ck (http://127.0.0.1:8081/static/app.js:9:9934)
    at bk (http://127.0.0.1:8081/static/app.js:9:1017)
    at ak (http://127.0.0.1:8081/static/app.js:9:923)
    at Tj (http://127.0.0.1:8081/static/app.js:9:765)
    at Lj (http://127.0.0.1:8081/static/app.js:7:11182)
    at http://127.0.0.1:8081/static/app.js:5:40449
    at http://127.0.0.1:8081/static/app.js:1:12961

Component Stack:
    at CaptureSetup (http://127.0.0.1:8081/static/app.js:65:50487)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:65:52003)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:69:3070)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:58:5505)
    at Provider (http://127.0.0.1:8081/static/app.js:58:2818)

#### System Information
Mitmproxy: 11.0.0

![image](https://github.com/user-attachments/assets/9b754e15-1911-4453-90e7-ee73fe5122fb)

**Comment by Prinzhorn** [comment]
Potentially an old cached js version, try with cleared cache or private browsing window. Does that fix it?

**Comment by KaarunyaKudimi** [comment]
Thanks a lot @Prinzhorn after clearing cache its working fine thanks a lot !
