### ISSUE TITLE
Mitmweb can't run

### ISSUE THREAD

**Issue by guliping** [mitmproxy/mitmproxy#728]
```
(venv.mitmproxy)hanhaodeMacBook-Pro:mitmproxy hanhao$ mitmweb
Traceback (most recent call last):
  File "/Users/hanhao/venv.mitmproxy/bin/mitmweb", line 9, in <module>
    load_entry_point('mitmproxy==0.13.1', 'console_scripts', 'mitmweb')()
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/hanhao/mitmproxy/libmproxy/main.py", line 6, in <module>
    from netlib.version_check import check_pyopenssl_version, check_mitmproxy_version
  File "/Users/hanhao/netlib/netlib/version_check.py", line 10, in <module>
    import OpenSSL
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 11, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _BIO_new_CMS
  Referenced from: /Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
  Expected in: flat namespace
 in /Users/hanhao/venv.mitmproxy/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
```

**Comment by mhils** [comment]
This looks like your cryptography installation is broken.  
http://chriskief.com/2014/03/25/installing-cryptography-via-pip-with-macports-or-homebrew/
(thanks to @hynek for the pointer)

**Comment by guliping** [comment]
I have installed cryptography again according to http://chriskief.com/2014/03/25/installing-cryptography-via-pip-with-macports-or-homebrew/,but when I import openssl ,the error exits still.

>>> import OpenSSL
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Library/Python/2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
   from OpenSSL import rand, crypto, SSL
 File "/Library/Python/2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
   from OpenSSL._util import (
 File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
   from cryptography.hazmat.bindings.openssl.binding import Binding
 File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 11, in <module>
   from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _BIO_new_CMS
 Referenced from: /Library/Python/2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
 Expected in: flat namespace
in /Library/Python/2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
