### ISSUE TITLE
OSError: [WinError 64] 指定的网络名不再可用。

### ISSUE THREAD

**Issue by wlfzsd** [mitmproxy/mitmproxy#7301]
[18:58:45.435] Unhandled error in task.
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 566, in accept_coro
  File "asyncio\windows_events.py", line 803, in _poll
  File "asyncio\windows_events.py", line 555, in finish_accept
OSError: [WinError 64] 指定的网络名不再可用。
[18:58:45.437] Unhandled error in task.
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 846, in loop
OSError: [WinError 64] 指定的网络名不再可用。

I've previously reported this issue, and while it was difficult to reproduce consistently, I've finally pinpointed the steps. This bug exists across multiple versions, from 9 through 11.

The problem occurs when a client is connected to mitmproxy, and the Windows machine (Win10 or Win11) either has its local network connection disabled (disconnected from the network) or enters sleep mode (also disconnecting from the network) for an extended period, specifically 20 minutes or longer. Upon restoring the network connection, the error message appears. After the error appears, mitmproxy no longer receives or processes data, even though the network connection has been restored.

I previously submitted this issue, and at that time, the cause was high network usage leading to an inability to connect to the internet. In other words, any prolonged network disconnection can reproduce this bug.

**Comment by mhils** [comment]
Based on the call stack this looks like a Python issue, not a mitmproxy issue.

**Comment by wlfzsd** [comment]
> Based on the call stack this looks like a Python issue, not a mitmproxy issue.

In mitmproxy 9, this issue occurs less frequently, but in mitmproxy 11, it happens frequently. It doesn't only appear during network congestion or network restarts; after running continuously for several hours, this problem will occur.

**Comment by WangZichen99** [comment]
Yes, I have the same problem, how to fix it? @mhils 
python version: 3.10.11
mitmproxy version: 11.0.2
