### ISSUE TITLE
mitmproxy Windows incompatibility due to fcntl

### ISSUE THREAD

**Issue by daMatz** [mitmproxy/mitmproxy#7306]
#### Problem Description
There seems to be a problem with running mitmproxy on Windows clients, probably due to `fcntl` dependency, which is only available on Unix systems.
Error while running `mitmproxy` command:

```
Traceback (most recent call last):
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\master.py", line 80, in run
    await self.running()
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\tools\console\master.py", line 221, in running
    self.ui = window.Screen()
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\Scripts\mitmproxy.exe\__main__.py", line 7, in <module>
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\tools\main.py", line 143, in mitmproxy
    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\tools\main.py", line 137, in run
    return asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\tools\main.py", line 134, in main
    await master.run()
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\master.py", line 90, in run
    await self.done()
  File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\mitmproxy\tools\console\master.py", line 247, in done
    self.loop.stop()
AttributeError: 'ConsoleMaster' object has no attribute 'loop'
```

#### Steps to reproduce the behavior:
1. Run `mitmproxy` in PowerShell on Windows

#### System Information
`mitmproxy --version`:
```
mitmproxy --version
Mitmproxy: 11.0.0
Python:    3.10.11
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Windows-10-10.0.19045-SP0
```

`mitmweb` works without problems.

**Comment by lukant** [comment]
It seems that the problem originates from urwid library

    File "C:\Users\MyUserName\AppData\Roaming\Python\Python310\site-packages\urwid\raw_display.py", line 92, in __init__
         fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)

The `urwid\raw_display.py` was renamed to `urwid\display\raw.py` in change `e332b280730944afef0c6a7e8483ffb192e1d802` which was delivered in 2.4.0. That suggests you use `urwid` even older version of that library. Version 2.4.0 introduced support for RAW and Curses display on Windows (see https://urwid.org/changelog.html#release-2-4-0).

According to https://github.com/mitmproxy/mitmproxy/blob/v11.0.0/pyproject.toml#L58 mitmproxy 11.0.0 requires `urwid` to be at least 2.6.14.

Output of `pip freeze` command may be useful in troubleshooting.

**Comment by mhils** [comment]
If the precompiled binaries work, that's a very strong indicator that this is an issue with your local Python environment. We may be partially to blame for this, see https://github.com/mitmproxy/mitmproxy/issues/7227

**Comment by daMatz** [comment]
Yes, that seemed to be it, thanks! Installing the latest `urwid` version fixed the issue 👍
