### ISSUE TITLE
mitmweb 11.0.0 webpage has crashed

### ISSUE THREAD

**Issue by yufengzjj** [mitmproxy/mitmproxy#7314]
#### Problem Description
mitmweb web page crashed(tried install from pip and windows installer).
C:\Users\x> mitmweb
[18:01:16.832] HTTP(S) proxy listening at *:8080.
[18:01:16.834] Web server listening at http://127.0.0.1:8081/

web page output:

mitmproxy has crashed.
TypeError: e.map is not a function
    at CaptureSetup (http://127.0.0.1:8081/static/app.js:65:51312)
    at Ch (http://127.0.0.1:8081/static/app.js:5:55364)
    at li (http://127.0.0.1:8081/static/app.js:5:65205)
    at ck (http://127.0.0.1:8081/static/app.js:9:9934)
    at bk (http://127.0.0.1:8081/static/app.js:9:1017)
    at ak (http://127.0.0.1:8081/static/app.js:9:923)
    at Tj (http://127.0.0.1:8081/static/app.js:9:765)
    at Lj (http://127.0.0.1:8081/static/app.js:7:11182)
    at http://127.0.0.1:8081/static/app.js:5:40449
    at http://127.0.0.1:8081/static/app.js:1:12961

Component Stack:
    at CaptureSetup (http://127.0.0.1:8081/static/app.js:65:50873)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:65:52389)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:69:3122)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:58:5505)
    at Provider (http://127.0.0.1:8081/static/app.js:58:2818)

#### Steps to reproduce the behavior:
1. run mitmweb in cmd

#### System Information
Mitmproxy: 11.0.0
Python:    3.12.5
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Windows-11-10.0.22631-SP0

**Comment by yufengzjj** [comment]
chrome plugin issues

**Comment by dipcore** [comment]
@yufengzjj can you clarify which plugin causes the issue? I have the same problem.
