### ISSUE TITLE
mitmproxy 11.0版本，mitmweb启动报错

### ISSUE THREAD

**Issue by icecreate** [mitmproxy/mitmproxy#7357]
mitmproxy 11.0版本，mitmweb启动报错

TypeError: e.map is not a function
    at CaptureSetup (http://127.0.0.1:8081/static/app.js:65:50929)
    at Ch (http://127.0.0.1:8081/static/app.js:5:55364)
    at li (http://127.0.0.1:8081/static/app.js:5:65205)
    at ck (http://127.0.0.1:8081/static/app.js:9:9934)
    at bk (http://127.0.0.1:8081/static/app.js:9:1017)
    at ak (http://127.0.0.1:8081/static/app.js:9:923)
    at Tj (http://127.0.0.1:8081/static/app.js:9:765)
    at Lj (http://127.0.0.1:8081/static/app.js:7:11182)
    at http://127.0.0.1:8081/static/app.js:5:40449
    at http://127.0.0.1:8081/static/app.js:1:12961

Component Stack:
    at CaptureSetup (http://127.0.0.1:8081/static/app.js:65:50490)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:65:52006)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:69:3070)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:58:5505)
    at Provider (http://127.0.0.1:8081/static/app.js:58:2818)

**Comment by lups2000** [comment]
Could you please be more specific? Which are the steps to reproduce the issue?

**Comment by icecreate** [comment]
> Could you please be more specific? Which are the steps to reproduce the issue?

The same script execution under version 11.0 error, version back to 10.4 is ok

**Comment by lups2000** [comment]
> > Could you please be more specific? Which are the steps to reproduce the issue?
> 
> The same script execution under version 11.0 error, version back to 10.4 is ok

okay thanks! And did you do something in particular? Or after running mitmweb, it crashed?

**Comment by icecreate** [comment]
> Can you please clear your browser cache and reload mitmweb?

Yes，you are right，It's OK after clear browser cache，thanks!
