### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by r00tback** [mitmproxy/mitmproxy#7408]
#### Problem Description
mitmproxy has crashed!
Traceback (most recent call last):
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\server.py", line 391, in server_event
    for command in layer_commands:
                   ^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 181, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 270, in handle_event
    yield from self._handle(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 181, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 91, in _handle_event
    yield from super()._handle_event(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 98, in _handle_event
    yield from self.event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 397, in event_to_child
    yield from super().event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 96, in event_to_child
    yield from super().event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 153, in event_to_child
    for command in self.child_layer.handle_event(event):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 181, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 91, in _handle_event
    yield from super()._handle_event(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 83, in _handle_event
    yield from self.receive_data(event.data)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 304, in receive_data
    yield from self.event_to_child(
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 96, in event_to_child
    yield from super().event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 154, in event_to_child
    yield from self._handle_command(command)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 111, in _handle_command
    stream = self.quic._get_or_create_stream_for_send(command.stream_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\aioquic\quic\connection.py", line 1394, in _get_or_create_stream_for_send
    raise ValueError("Cannot send data on unknown peer-initiated stream")
ValueError: Cannot send data on unknown peer-initiated stream
#### Steps to reproduce the behavior:
1. android
2. http3 traffic 
3. 
before crash i got some error 

[01:44:59.117][10.0.0.1:41700] Client QUIC handshake failed. Cannot parse QUIC header: Malformed head (4a1fb465608c0c8ea543bee228f53703be63f932cca424fc424cb43db90e217371b81e85433e67b832c45ed36cfd5ba48da962a1dc74034543a1b572eba7fea618f065cfa11a73e6a3cb704c1dbf4eade32412dc68e849b54042a77f294cc134bf58dee76989032fa4121e2eb83a4fd46eac9524a865a8e72ac550cc4df31e30161404ee7e123f6df8e78aa3a5527182682613e985b1a2d80bd8571fc3ad3d88ccb754207501a3fa003803a43456d211dcaecfba437e206702cc7301c914505207e50c1805f688d7b8037f3d102b7a6b91b64f0355b3c008f422b66bb77e2001f85fd5fcd05966bffd3a0363e4a07af914e3192fb3eb39e56312c2ab6c6d796b5e43ebacab9644959c107fd115b7909233b85cf4c64d46e7df95eed07f9b87925e5c1a516997fe11469d917cdbd7a99aa95efd654f4711531f02bbafa7bab6b4f674b5227c0b5245cfddc16a21f5471baf0934899290171974695f98f5c94320018bcb61ff30b64b2bfef7f4bc10729434f0c490bf6bbe8e1fc4961c8f603c505d1d5854e3a6d01e20fd9805403cef3e5df9eff253d9b58a67c68c65234350b28f975dbb9d81f466354c903525024ff9b7fb972806d0a46a05e915491f38e31d3aaab9a37c5766b26671f6038d32ab48a106cc0e4302b7c9169efebb038e7656aa5a9475fdd1fedda78ed0e8938292dc9a4c798040706fa3dfd8ecb68482adadc70b8fa7907f6af5ee1bb2da7af0d51e477eee5cbc5ac8a9cf63cc2ca72ab84547cc0d2adab4f689dd19ed898c434d09e3394970507ef068be2c5a72a763001fb902ab6ab5106f78478a398b2ed3ed45f2795abced0198fda2b2903fb4365228d8d69bbc2c98d8db0c3b2354925386455c65c7ada330ad60002eb5189fabe013ca1579c76655206412b93a452dfb21dff90fb252886787777297ddecc9964718d6a6f6f88dc0249818b082ea3758f4472f92bff8c22cf5af60c7ca2fb08f17b72fe9c3372b17ebf03d71493a3c2947b8d08bff657f8b14cdc1d6a5bbf62a3048e1ab621b868daf952895bf182ff110cb4596767c8d7791df802bc56dc9e8a1823f168b77906fdfa01a5a80f3bdb3e1041eb74a15409eed45e88df076e75759dc2084e13e5c49bd79753f62b2f161b2a0f6c40f5f05ab0cdb12643722d2685b8d952e97f4898131df5e781e4ad31317210b78ebd51522ab087f09a44436bf6cd88bbd96b4f8353331f8cce7c9a0be549d55800cfa15f9b862f118042e9b1abcf29fd2b3dc56d03fe746f7ecf3e7920ba2ce6e1107eb769d200b8285db354a593b550abdd38213b570d88afb248e87b1dd974b9d175162e6dd9ace48f836fda569f901bc27ae0c5ce1c11223eda11242d602204a6d3f8d70aef16d70dfeb01d766fd5fcb6c58a4d7828823e54ca012da1df49be05100ffa8b94642e32ea747aa3e2f0a1278d6cd112e5606b71c18a7733de9c256320be46431f3fafcc0fc754962a5fdd291f66095cd49ed727b57b8e041c742dbb3a3481bb6bbd35321567540823bd08009623675965e009071d50801719e4d741a9589e114e42fbc4d38a152532b8497720c7c844144c1206df5e0952e5a1e1360dfe5c595adf2df482a5c207dbe351e73da4403ea0d05cb1e8a24aa52cccde7a310635ae8d187bd7c8a93d9a5d184bc7cfeac02914d3f08f642c47b72890919fc876391b97279dbb37628254c480a173c34f6f528d7dc544e04fef0ca76f3559793faaa64050c58a45a8f3a43c546)

#### System Information
Paste the output of "mitmproxy --version" here.
C:\Users\mrha1>mitmproxy --version
Mitmproxy: 11.0.0
Python:    3.12.7
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Windows-11-10.0.22631-SP0

**Comment by errorxyz** [comment]
Can you provide additional setup details? What mode are you using? Which website were you trying to access?

**Comment by r00tback** [comment]
site https://quic.nginx.org/
nox player on Windows using wireguard mode

**Comment by craftysecurity** [comment]
Having the same issue, I will try to find where its happening but I guess its probably on [aioquic](https://github.com/aiortc/aioquic/) side?

**System Information**
mitmproxy --version
Mitmproxy: 11.0.2 binary
Python:    3.12.7
OpenSSL:   OpenSSL 3.4.0 22 Oct 2024
Platform:  Windows-11-10.0.26100-SP0

mitmproxy --mode local:firefox

Platform: Windows-11-10.0.22631-SP0
.\openssl.exe --version
OpenSSL 3.2.3 3 Sep 2024 (Library: OpenSSL 3.2.3 3 Sep 2024)

**Comment by Anthony-76** [comment]
Hi,

Just in addition from @r00tback, I have the same issue with mitmproxy 11.0.2 on Windows 10.

mitmproxy --version
Mitmproxy: 11.0.1 binary
Python:    3.12.7
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Windows-10-10.0.19045-SP0

My problem appear even if I execute mitmproxy without send traffic to the proxy.


I downgraded mitmproxy to 11.0.1 and no problem appeared. It works fine.

**Comment by r00tback** [comment]
i installed 11.0.1 and still having the issue

maybe this can help debug

mitmproxy has crashed!
Traceback (most recent call last):
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\server.py", line 391, in server_event
    for command in layer_commands:
                   ^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 181, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 270, in handle_event
    yield from self._handle(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 181, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 91, in _handle_event
    yield from super()._handle_event(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 98, in _handle_event
    yield from self.event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 397, in event_to_child
    yield from super().event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 96, in event_to_child
    yield from super().event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 153, in event_to_child
    for command in self.child_layer.handle_event(event):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layer.py", line 181, in handle_event
    command = next(command_generator)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 91, in _handle_event
    yield from super()._handle_event(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 83, in _handle_event
    yield from self.receive_data(event.data)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 304, in receive_data
    yield from self.event_to_child(
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 96, in event_to_child
    yield from super().event_to_child(event)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\tunnel.py", line 154, in event_to_child
    yield from self._handle_command(command)
  File "C:\Users\mrha1\AppData\Roaming\Python\Python312\site-packages\mitmproxy\proxy\layers\quic\_stream_layers.py", line 112, in _handle_command
    existing_reset_error_code = stream.sender._reset_error_code
                                ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sender'


[08:33:14.744][10.0.0.1:60990] client connect
[08:33:14.745][10.0.0.1:60990] Client QUIC handshake failed. Cannot parse QUIC header: Malformed head (5943ab9d3e3608e474066a5c31df117cd0d56748e006f8a357ece76db357eb197282b77dc70093df061643c38cb435cce688db8a2a99f7f9f6e98b251630ea7a64ffec378e4971f29cf5e3d0ac4b69ba744eab389b43c041021b4f33e52d9ebb4a725b7bd6272beab936d1d90689b1e5f65a5a46e0637b48b10301743739501e44fa5778c20a5b674fdda1769c408b6d40417ff50701f49e8b6acccc27ee82a9b36ad6db701a7d46f8c5fc921cf94055215533b732bfb18cd73d4d4c951d5d58a538d70e452385258f4315bad34f80e9e04853a3c7dba569a6e40cfa9b64928377ba2e89b1158db3a18b1c5c0524b3f70a2f728c757c8608e7dc008ccc4094cd3f0cd2987dccca5f95ecce3fc4b82443c48a1f9a8bba274d55c09f2ac30d57e1d5e6225970eb9e95930f6145625f176b9592b98a7593d223ca8cda86746d8871a6aa43381d7e3252f934bef3209a6c673d910127c794fc130f1b44663879587ce75c8262e5f1b4289dfc54efd0be86fedc012dffcb3f659d979d938f06fab79f05b48893e992371d53a6905bf2c4f2dd8c51ce80f3b87461f3a98bb47452285f204837986e287cdca4fc3451cbd420aa36b7f0b82479485da2f5c5b7b46b91d5eda80c2d3e5d6d2ca1038972231a862a66226a52b87a6274f1a15982e1e56edd32339944fdc38316cace725084ea7c6b4c8d284a7066d2ba7f396e179a048a310f71251077ae01ea062190fe73581229502cc08098dd6ac2cfeb3acbe3f6046d83c85e8618fa2d4fc01b5b92cf20476862c76bf703b50ac1bfebd21c2cca047c9d0f89308a893f24cafdfc3977959ec8090a2c2b7855052e175645a3f5660309d55c51865f21ae24a29a1da5ed7f76a46b7aff48e4e59a36633eca4c1627b6f10fd97c02c804bdbd6d4179ab71702d989ae77c914d3ab05f531a4331c9b5f014cd12b71d18e19299f24e7f8af0b4469128f746de36c5807866bc53cb483724b86a86ddb71fe5b0b417f2312fe3142763ee636704d2aca63b55ae9005ab83efad29aa900690fd89f7c46e4969401eca5c245e178afc3ee519dbdf90658fb463612d25e81a12dc8658a5db47675520cc131ff973e9306c9fe90a546c181b9f7df7a113832f0cb221da96e779aef3fa061dd10ebedf991df75897cd326c052e2d43c6705fd59dc487ff12d2d496bf1ef9d9bb148ff4d72f215b367233369ba2875d62369833a561903e93e03ccd9b170da7d72d0a30be026d2ddd8cfb473a0d86e4fc4f887cc988c6b326e326d1ab00a359472cee0311624e6ba3f48790d51ff00e2c76af59d2766f515a67d5cb1cf3526ddaabbfcd595c777328f43b8f0013843dd3292da685e579693abf035f2da41f17799baa26c9d6ac8281acfe4cfbdebfd6887d3ab18fe413e128fd2b6314a021cfab2c3ee98072f7045988a62290478fde2ba26f132aee84fd36aceed0219f3ad97bf9cf9d1a689b6bafea2a23920a5e4e989b68f0b0a80f8033096db3a2b3f5128b6d553d825de652f99b80eef8f310c7dd1994ca7c13b566378050c4f8524d3476699b8c3c3e97368ea2ad8ff9f05407fdc90abbd01022329def34ab0d1703647783814b1560be79a6b565692559c6cd31de112b23ca8bec0eafc0ff97fb70ff31650d888f7cd792b36a367e56f3ecdd1e9f75e41470c48d4848c3f9ee50a7e50be0797df097e08ffadb04a7d9bdf26f3168766d4be6bfd3a9c8192c9f65037921ba878f54dc79630cf1fb1c72543c10161e)
[08:33:14.746][10.0.0.1:60990] client disconnect

**Comment by eswaldots** [comment]
any update on this?
