### ISSUE TITLE
Segfault in mitmproxy_rs when using wireguard mode

### ISSUE THREAD

**Issue by ntqbit** [mitmproxy/mitmproxy#7409]
#### Problem Description
When using `--mode wireguard` and there are some flows, when exiting mitmproxy a segfault occurs.
```
mitmproxy --mode wireguard
zsh: IOT instruction (core dumped)  mitmproxy --mode wireguard
````

I ran mitmproxy with gdb to get the segfault backtrace:
```
Thread 20 "tokio-runtime-w" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff0b456c0 (LWP 254180)]
0x00007ffff0b445e0 in ?? ()
(gdb) bt
#0  0x00007ffff0b445e0 in ?? ()
#1  0x00007ffff632b2df in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#2  0x00007ffff632afd1 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#3  0x00007ffff62bd636 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#4  0x00007ffff6381715 in _Unwind_ForcedUnwind_Phase2 (exc=exc@entry=0x7ffff0b45d30, context=context@entry=0x7ffff0b44480, frames_p=frames_p@entry=0x7ffff0b44388) at /usr/src/debug/gcc/gcc/libgcc/unwind.inc:183
#5  0x00007ffff6381df0 in _Unwind_ForcedUnwind (exc=0x7ffff0b45d30, stop=stop@entry=0x7ffff76abe80 <unwind_stop>, stop_argument=<optimized out>) at /usr/src/debug/gcc/gcc/libgcc/unwind.inc:218
#6  0x00007ffff76ac045 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:130
#7  0x00007ffff76a4732 in __do_cancel () at ../sysdeps/nptl/pthreadP.h:271
#8  __GI___pthread_exit (value=0x0) at pthread_exit.c:36
#9  0x00007ffff792acc9 in PyThread_exit_thread () from /usr/lib/libpython3.12.so.1.0
#10 0x00007ffff787f9fc in ?? () from /usr/lib/libpython3.12.so.1.0
#11 0x00007ffff7997ede in PyEval_RestoreThread () from /usr/lib/libpython3.12.so.1.0
#12 0x00007ffff7a83b6a in PyGILState_Ensure () from /usr/lib/libpython3.12.so.1.0
#13 0x00007ffff627dde6 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#14 0x00007ffff61b597b in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#15 0x00007ffff6143004 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#16 0x00007ffff6301aa7 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#17 0x00007ffff630bd31 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#18 0x00007ffff62f3f18 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#19 0x00007ffff62f3ba3 in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#20 0x00007ffff62ef3db in ?? () from /home/user/.local/pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so
#21 0x00007ffff76a339d in start_thread (arg=<optimized out>) at pthread_create.c:447
#22 0x00007ffff772849c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) 
```

Segfault does not occur if there are no flows, that is, no packets were sent to the mitmproxy's wireguard server.

#### Steps to reproduce the behavior:
1. Start mitmproxy in wireguard mode: `mitmproxy --wireguard`
2. Connect wireguard client to mitmproxy, send at least one packet to create a flow (segfault occured with both TCP and DNS packets)
3. Quit mitmproxy with `q` hotkey
4. Observe the segfault `zsh: segmentation fault (core dumped)  mitmproxy --mode wireguard`

#### System Information
```
mitmproxy --version
Mitmproxy: 11.0.2
Python:    3.12.7
OpenSSL:   OpenSSL 3.4.0 22 Oct 2024
Platform:  Linux-6.12.4-arch1-1-x86_64-with-glibc2.40
```

**Comment by dur-randir** [comment]
Looks kinda like https://github.com/mitmproxy/mitmproxy/issues/5708
