### ISSUE TITLE
Crash when clicking on event

### ISSUE THREAD

**Issue by jaens** [mitmproxy/mitmproxy#753]
```
└> env/bin/python mitmproxy --verbose --eventlog --no-upstream-cert
Traceback (most recent call last):
  File "mitmproxy/libmproxy/console/__init__.py", line 500, in run
    self.loop.run()
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/main_loop.py", line 496, in process_input
    event, button, col, row, focus=True ):
  File "mitmproxy/libmproxy/console/window.py", line 22, in mouse_event
    k = super(self.__class__, self).mouse_event(*args, **kwargs)
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/container.py", line 1169, in mouse_event
    event, button, col, row-htrim, focus )
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/container.py", line 1687, in mouse_event
    focus)
  File "mitmproxy/env/lib/python2.7/site-packages/urwid/listbox.py", line 1568, in mouse_event
    focus)
  File "mitmproxy/libmproxy/console/flowlist.py", line 175, in mouse_event
    self.master.view_flow(self.flow)
  File "mitmproxy/libmproxy/console/__init__.py", line 591, in view_flow
    flowview.FlowView(self, self.state, flow, tab_offset),
  File "mitmproxy/libmproxy/console/flowview.py", line 134, in __init__
    tab_offset
  File "mitmproxy/libmproxy/console/tabs.py", line 28, in __init__
    self.show()
  File "mitmproxy/libmproxy/console/tabs.py", line 66, in show
    body = self.tabs[self.tab_offset][1](),
  File "mitmproxy/libmproxy/console/flowview.py", line 156, in view_request
    return self.conn_text(self.flow.request)
  File "mitmproxy/libmproxy/console/flowview.py", line 207, in conn_text
    msg, body = self.content_view(viewmode, conn)
  File "mitmproxy/libmproxy/console/flowview.py", line 188, in content_view
    isinstance(conn, HTTPRequest)
  File "mitmproxy/libmproxy/utils.py", line 111, in get
    if args in self.cache:
TypeError: unhashable instance
```

**Comment by mhils** [comment]
Thanks. Which version of mitmproxy are you using?

**Comment by jaens** [comment]
commit d002371d30e4b0ab7d1d23023236a9446d4c2396

**Comment by mhils** [comment]
Fixed, thanks. You need to update netlib for this bug to disappear.
