### ISSUE TITLE
window，update version can not see details .

### ISSUE THREAD

**Issue by hhhaiai** [mitmproxy/mitmproxy#756]
hi:

   I sync native version.   phone can use mitm network. but can't see details(request/response/and so on).

environment ： window 7 +cygwin

and log:

Traceback (most recent call last):
  File "/home/sanbo/package/mitmproxy/libmproxy/console/__init__.py", line 500, in run
    self.loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/sanbo/package/mitmproxy/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/sanbo/package/mitmproxy/libmproxy/console/flowlist.py", line 380, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/sanbo/package/mitmproxy/libmproxy/console/flowlist.py", line 248, in keypress
    self.master.view_flow(self.flow)
  File "/home/sanbo/package/mitmproxy/libmproxy/console/__init__.py", line 591, in view_flow
    flowview.FlowView(self, self.state, flow, tab_offset),
  File "/home/sanbo/package/mitmproxy/libmproxy/console/flowview.py", line 134, in __init__
    tab_offset
  File "/home/sanbo/package/mitmproxy/libmproxy/console/tabs.py", line 28, in __init__
    self.show()
  File "/home/sanbo/package/mitmproxy/libmproxy/console/tabs.py", line 66, in show
    body = self.tabs[self.tab_offset][1](),
  File "/home/sanbo/package/mitmproxy/libmproxy/console/flowview.py", line 156, in view_request
    return self.conn_text(self.flow.request)
  File "/home/sanbo/package/mitmproxy/libmproxy/console/flowview.py", line 207, in conn_text
    msg, body = self.content_view(viewmode, conn)
  File "/home/sanbo/package/mitmproxy/libmproxy/console/flowview.py", line 188, in content_view
    isinstance(conn, HTTPRequest)
  File "/home/sanbo/package/mitmproxy/libmproxy/utils.py", line 111, in get
    if args in self.cache:
TypeError: unhashable instance

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...

**Comment by hhhaiai** [comment]
diff --git a/libmproxy/utils.py b/libmproxy/utils.py
index a29a53f..a6ca55f 100644
--- a/libmproxy/utils.py
+++ b/libmproxy/utils.py
@@ -1,11 +1,8 @@
 from __future__ import absolute_import
 import os
 import datetime
-import urllib
 import re
 import time
-import functools
-import cgi
 import json
 
@@ -60,49 +57,6 @@ def pretty_json(s):
     return json.dumps(p, sort_keys=True, indent=4).split("\n")
 
 
-def urldecode(s):
-    """
-        Takes a urlencoded string and returns a list of (key, value) tuples.
-    """
-    return cgi.parse_qsl(s, keep_blank_values=True)
-def urlencode(s):
-    """
-        Takes a list of (key, value) tuples and returns a urlencoded string.
-    """
-    s = [tuple(i) for i in s]
-    return urllib.urlencode(s, False)
-def multipartdecode(hdrs, content):
-    """
-        Takes a multipart boundary encoded string and returns list of (key, value) tuples.
-    """
-    v = hdrs.get_first("content-type")
-    if v:
-        v = parse_content_type(v)
-        if not v:
-            return []
-        boundary = v[2].get("boundary")
-        if not boundary:
-            return []
-
-        rx = re.compile(r'\bname="([^"]+)"')
-        r = []
-
-        for i in content.split("--" + boundary):
-            parts = i.splitlines()
-            if len(parts) > 1 and parts[0][0:2] != "--":
-                match = rx.search(parts[1])
-                if match:
-                    key = match.group(1)
-                    value = "".join(parts[3 + parts[2:].index(""):])
-                    r.append((key, value))
-        return r
-    return []
 def pretty_duration(secs):
     formatters = [
         (100, "{:.0f}s"),
@@ -168,50 +122,6 @@ class LRUCache:
             return ret
 
 
-def parse_content_type(c):
-    """
-        A simple parser for content-type values. Returns a (type, subtype,
-        parameters) tuple, where type and subtype are strings, and parameters
-        is a dict. If the string could not be parsed, return None.
-
-        E.g. the following string:
-
-            text/html; charset=UTF-8
-
-        Returns:
-
-            ("text", "html", {"charset": "UTF-8"})
-    """
-    parts = c.split(";", 1)
-    ts = parts[0].split("/", 1)
-    if len(ts) != 2:
-        return None
-    d = {}
-    if len(parts) == 2:
-        for i in parts[1].split(";"):
-            clause = i.split("=", 1)
-            if len(clause) == 2:
-                d[clause[0].strip()] = clause[1].strip()
-    return ts[0].lower(), ts[1].lower(), d
-def hostport(scheme, host, port):
-    """
-        Returns the host component, with a port specifcation if needed.
-    """
-    if (port, scheme) in [(80, "http"), (443, "https")]:
-        return host
-    else:
-        return "%s:%s" % (host, port)
-
-def unparse_url(scheme, host, port, path=""):
-    """
-        Returns a URL string, constructed from the specified compnents.
-    """
-    return "%s://%s%s" % (scheme, hostport(scheme, host, port), path)
 def clean_hanging_newline(t):
     """
         Many editors will silently add a newline to the final line of a

**Comment by mhils** [comment]
Looks like you installed mitmproxy from master? We fixed #753 a day ago,
please update.

Cheers,
Max

sanbo <notifications@github.com> schrieb am Mi., 9. Sep. 2015 08:34:

**Comment by hhhaiai** [comment]
ok, I'll try. thx
