### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'dev0'

### ISSUE THREAD

**Issue by sonicjh36** [mitmproxy/mitmproxy#759]
I use pip to install mitmproxy, when I start it, it occur an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.13', 'console_scripts', 'mitmproxy')()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/main.py", line 42, in mitmproxy
    netlib.version_check.version_check(version.IVERSION)
  File "/usr/local/lib/python2.7/dist-packages/netlib-0.13.1-py2.7.egg/netlib/version_check.py", line 32, in version_check
    v = tuple([int(x) for x in OpenSSL.__version__.split(".")][:2])
ValueError: invalid literal for int() with base 10: 'dev0'
```
Did I miss something not install?

**Comment by mhils** [comment]
Thanks for the report! Looks like you have installed pyOpenSSL from master, which breaks our version detection, which is a workaround for broken Python packaging on OSX, which is outside of our control. I'll fix the version detection on master. As an alternative workaround, you can switch to a regular version of pyopenssl.
