### ISSUE TITLE
'Unexpected EOF' error while running proxy in transparent mode

### ISSUE THREAD

**Issue by tuusberg** [mitmproxy/mitmproxy#760]
Hey!
I've faced this error today during Slack connections exploration. It only occurs in transparent mode, I'm using latest mitmdump from master.

here's the details:
```
192.168.42.10:58630: Cannot establish TLS with client: NetLibError("SSL handshake error: SysCallError(-1, 'Unexpected EOF')",)
192.168.42.10:58630: clientdisconnect
192.168.42.10:58628: clientdisconnect
192.168.42.10:58629: Traceback (most recent call last):
  File "/home/ubuntu/mitmproxy/libmproxy/proxy/server.py", line 115, in handle
    root_layer()
  File "/home/ubuntu/mitmproxy/libmproxy/proxy/modes/transparent_proxy.py", line 21, in __call__
    layer()
  File "/home/ubuntu/mitmproxy/libmproxy/protocol/tls.py", line 268, in __call__
    layer = self.ctx.next_layer(self)
  File "/home/ubuntu/mitmproxy/libmproxy/proxy/root_context.py", line 43, in next_layer
    layer = self._next_layer(top_layer)
  File "/home/ubuntu/mitmproxy/libmproxy/proxy/root_context.py", line 51, in _next_layer
    d = top_layer.client_conn.rfile.peek(3)
  File "/home/ubuntu/mitmproxy/netlib/netlib/tcp.py", line 298, in peek
    raise NetLibSSLError(repr(e))
NetLibSSLError: SysCallError(-1, 'Unexpected EOF')
```

**Comment by mhils** [comment]
Fixed, thanks! :smile:
