### ISSUE TITLE
Mitmweb can't run

### ISSUE THREAD

**Issue by guliping** [mitmproxy/mitmproxy#761]
When I run mitmweb,then open 121.0.0.1:8081, the error happened.
```
Traceback (most recent call last):
  File "/Users/venv.mitmproxy/lib/python2.7/site-packages/tornado/ioloop.py", line 1020, in _run
    return self.callback()
  File "/Users/mitmproxy/libmproxy/web/__init__.py", line 141, in tick
    flow.FlowMaster.tick(self, self.masterq, timeout=0)
  File "/Users/mitmproxy/libmproxy/flow.py", line 812, in tick
    return super(FlowMaster, self).tick(q, timeout)
  File "/Users/mitmproxy/libmproxy/controller.py", line 108, in tick
    self.handle(*msg)
  File "/Users/mitmproxy/libmproxy/controller.py", line 129, in handle
    m(obj)
  File "/Users/mitmproxy/libmproxy/web/__init__.py", line 167, in handle_request
    super(WebMaster, self).handle_request(f)
  File "/Users/mitmproxy/libmproxy/flow.py", line 990, in handle_request
    self.state.add_flow(f)
  File "/Users/mitmproxy/libmproxy/flow.py", line 561, in add_flow
    self.flows._add(f)
  File "/Users/mitmproxy/libmproxy/flow.py", line 469, in _add
    view._add(f)
  File "/Users/mitmproxy/libmproxy/web/__init__.py", line 23, in _add
    data=f.get_state(short=True)
  File "/Users/mitmproxy/libmproxy/models/flow.py", line 88, in get_state
    d = super(Flow, self).get_state(short)
  File "/Users/mitmproxy/libmproxy/stateobject.py", line 32, in get_state
    state[attr] = val.get_state(short)
  File "/Users/mitmproxy/libmproxy/models/connections.py", line 138, in get_state
    address={"address": self.address(),
TypeError: 'NoneType' object is not callable
ERROR:tornado.application:Exception in callback <bound method WebMaster.tick of <libmproxy.web.WebMaster object at 0x10cfe5a90>>
```

**Comment by mhils** [comment]
Which version of mitmproxy/mitmweb are you running?

**Comment by guliping** [comment]
I am running the version which I downloaded from https://github.com/mitmproxy/mitmproxy.git three days ago
