### ISSUE TITLE
Running libmproxy produces this error.

### ISSUE THREAD

**Issue by pixelmai** [mitmproxy/mitmproxy#779]
>>> import socket
>>> from libmproxy import controller, proxy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/__init__.py", line 1, in <module>
    from .primitives import *
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/primitives.py", line 2, in <module>
    from netlib import socks, tcp
  File "/Library/Python/2.7/site-packages/netlib/socks.py", line 5, in <module>
    from . import tcp, utils
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 26, in <module>
    'TLSv1.2': SSL.TLSv1_2_METHOD,
AttributeError: 'module' object has no attribute 'TLSv1_2_METHOD'
>>>

**Comment by pixelmai** [comment]
Had to move the remove OpenSSL file:
sudo mv /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL_

And reinstall pyopenssl thru pip again.
