### ISSUE TITLE
Error, mac osx "El capitan" when select and copy text. 

### ISSUE THREAD

**Issue by edtler** [mitmproxy/mitmproxy#800]
OS: El capitan
terminal:iterm2

Mitmproxy is installed with brew, and the next error ocurr when select and copy text.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 499, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/lib/python2.7/site-packages/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 123, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 82, in keypress
    self.prompt_execute(self._w.get_edit_text())
AttributeError: 'Text' object has no attribute 'get_edit_text'
```

**Comment by mhils** [comment]
Thanks. Which version of mitmproxy is that?
