### ISSUE TITLE
mitmproxy crashes

### ISSUE THREAD

**Issue by davinerd** [mitmproxy/mitmproxy#804]
When the 'victim' tries to get a non existent file from a remote location, mitmproxy crashes.
Here's the log:
```
(venv)srv@ubuntu:~/mitmnbdf$ mitmproxy --version
mitmproxy 0.13
(venv)srv@ubuntu:~/mitmnbdf$ mitmproxy -T --host -s "mitmnbdf_inline.py mitmnbdf.cfg"
Traceback (most recent call last):
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 499, in run
    self.loop.run()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 496, in process_input
    event, button, col, row, focus=True ):
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/libmproxy/console/window.py", line 22, in mouse_event
    k = super(self.__class__, self).mouse_event(*args, **kwargs)
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/container.py", line 1169, in mouse_event
    event, button, col, row-htrim, focus )
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/listbox.py", line 1538, in mouse_event
    focus=True)
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/urwid/listbox.py", line 342, in calculate_visible
    focus_widget, focus_pos = self.body.get_focus()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 270, in get_focus
    f = ConnectionItem(self.master, self.state, f, True) if f else None
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 106, in __init__
    w = self.get_text()
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 114, in get_text
    marked=self.state.flow_marked(self.flow)
  File "/home/srv/mitmnbdf/venv/local/lib/python2.7/site-packages/libmproxy/console/common.py", line 399, in format_flow
    contentdesc = netlib.utils.pretty_size(len(f.response.content))
TypeError: object of type 'HTTPFlow' has no len()

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

The victim's request is a simple `curl --write-out "%{time_total} - %{url_effective}\n" --silent --remote-name http://my.remote.host/non-existent-file.exe`.
It works fine if the file exists.

**Comment by davinerd** [comment]
I'm digging, this may not be related to mitmproxy core but my inline script (yet can't find a reference in the stack trace).

**Comment by davinerd** [comment]
Yes, confirmed: it's a bug on my script. Closing the issue. Thanks
