### ISSUE TITLE
"Invalid syntax" error in setup.py while installing 0.14

### ISSUE THREAD

**Issue by commandtab** [mitmproxy/mitmproxy#829]
I'm attempting to install mitmproxy 0.14 on OS X 10.10.5 under a Homebrew install of Python 2.7.10, and am getting a syntax error in setup.py:

```
$ python --version
Python 2.7.10
$ pip install mitmproxy
Collecting mitmproxy
  Using cached mitmproxy-0.14.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/2x/k12t17w5197cvg68_xrp1xsh00058y/T/pip-build-Gt72j1/mitmproxy/setup.py", line 17
        "netlib>=%s, <%s" % (version.MINORVERSION, version.NEXT_MINORVERSION),
                                                                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2x/k12t17w5197cvg68_xrp1xsh00058y/T/pip-build-Gt72j1/mitmproxy
```

I had mitmproxy 0.13 installed up until I ran into the error, successfully uninstalled it, but that did not affect whether or not I received the error. Is my setup missing something?

Thanks!

**Comment by commandtab** [comment]
Interesting... Somehow my Homebrew version of `pip` was referencing the OS X system version of Python instead of the Homebrew version of Python:

```
$ which pip
/usr/local/bin/pip
$ pip --version
pip 7.1.2 from /Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg (python 2.6)
```

Re-linking the Homebrew install of Python didn't fix it, but doing a complete uninstall and reinstall of Python via `brew uninstall python; brew install python` fixed it:

```
$ which pip
/usr/local/bin/pip
$ pip --version
pip 7.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

Afterwards, doing `pip install mitmproxy` was successful :+1:
