### ISSUE TITLE
TypeError in SOCKS mode

### ISSUE THREAD

**Issue by jo-m** [mitmproxy/mitmproxy#839]
##### Steps to reproduce the problem:
After starting (`mitmproxy -p 8888 --socks`), mitmproxy crashes after the first request (HTTP or HTTPS) with the following error shown:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/modes/socks_proxy.py", line 57, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 395, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 399, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 518, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/local/lib/python2.7/site-packages/netlib/certutils.py", line 335, in get_cert
    sans),
  File "/usr/local/lib/python2.7/site-packages/netlib/certutils.py", line 109, in dummy_cert
    [OpenSSL.crypto.X509Extension(b"subjectAltName", False, ss)])
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 651, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode
```
I installed mitmproxy via my homebrew Pythons pip (`/usr/local/bin/pip`).

---
mitmproxy version: `mitmproxy 0.14.0`
Operating System: `OSX 10.11.1 (15B42)`
Browser: `Firefox 42.0`

**Comment by mhils** [comment]
Thanks for the report!

**Comment by jo-m** [comment]
Well, thanks for mimtproxy ;) if you need any more info regarding Python env etc. just ask!

**Comment by joshenders** [comment]
Also seeing this:

```
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/libmproxy/proxy/modes/socks_proxy.py", line 57, in __call__
    layer()
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 395, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 399, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 518, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/netlib/certutils.py", line 335, in get_cert
    sans),
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/netlib/certutils.py", line 109, in dummy_cert
    [OpenSSL.crypto.X509Extension(b"subjectAltName", False, ss)])
  File "/Users/jenders/.venv/mitmproxy/lib/python2.7/site-packages/OpenSSL/crypto.py", line 651, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

mitmproxy version: mitmproxy 0.14.0
Operating System: OSX 10.11.1

**Comment by nrolland** [comment]
same here

**Comment by mhils** [comment]
Fixed on master, thanks again!
