### ISSUE TITLE
crash on macbook pro(version 10.11.1)

### ISSUE THREAD

**Issue by zeayes** [mitmproxy/mitmproxy#841]
installed by `brew install mitmproxy`, mitmproxy 0.14.0.
when I make iTerm2 fullscreen, it crash as followings:
```Bash
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 500, in run
    self.loop.run()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 706, in _loop
    self._entering_idle()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 667, in _entering_idle
    callback()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 560, in entering_idle
    self.draw_screen()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/main_loop.py", line 575, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/urwid/raw_display.py", line 749, in draw_screen
    if osb and osb[y] == row:
IndexError: list index out of range

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

**Comment by mhils** [comment]
Thanks for the report. This looks like a duplicate of #806?

**Comment by zeayes** [comment]
Sorry, I didn't see it!
