### ISSUE TITLE
crash when enabling SOCKS proxy for an interface in OSX

### ISSUE THREAD

**Issue by snatchev** [mitmproxy/mitmproxy#852]
Hello, I am seeing this crash after doing the following:

1.) enable SOCKS proxy for an interface:
![screen shot 2015-12-08 at 2 19 59 pm](https://cloud.githubusercontent.com/assets/3312/11665729/e646af06-9db6-11e5-91de-99322351b560.png)

2.) run mitmproxy like: `mitmproxy --socks`

```
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/modes/socks_proxy.py", line 57, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 395, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 399, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 518, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/netlib/certutils.py", line 335, in get_cert
    sans),
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/netlib/certutils.py", line 109, in dummy_cert
    [OpenSSL.crypto.X509Extension(b"subjectAltName", False, ss)])
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/OpenSSL/crypto.py", line 651, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by mhils** [comment]
Thanks. This looks like a duplicate of #839, can you please update to 0.15 and check again?

**Comment by snatchev** [comment]
@mhils that fixed it, thanks!
