### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ThePantsThief** [mitmproxy/mitmproxy#865]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
----------------------------------------
Error in processing of request from 10.0.1.27:50212
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/netlib/tcp.py", line 799, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 64, in handle_client_connection
    h.handle()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 151, in handle
    self.channel.tell("clientdisconnect", root_layer)
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/controller.py", line 65, in tell
    m.reply = DummyReply()
AttributeError: 'NoneType' object has no attribute 'reply'

----------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
----------------------------------------
Error in processing of request from 10.0.1.27:50210
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/netlib/tcp.py", line 799, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 64, in handle_client_connection
    h.handle()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 151, in handle
    self.channel.tell("clientdisconnect", root_layer)
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/controller.py", line 65, in tell
    m.reply = DummyReply()
AttributeError: 'NoneType' object has no attribute 'reply'

----------------------------------------
```

**Comment by mhils** [comment]
Could you please update to mitmproxy 0.15 and check if that fixes things?

**Comment by Lucifer1993** [comment]
::ffff:127.0.0.1
