### ISSUE TITLE
Couldn't install mitmproxy on Ubuntu 15.10

### ISSUE THREAD

**Issue by azangru** [mitmproxy/mitmproxy#868]
Hi,

I am running Ubuntu 15.10, and followed the instructions for installing mitmproxy on Ubuntu published on http://docs.mitmproxy.org.

But when I try to run mitmproxy, I get an error with the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.ssl-match-hostname<3.4.1,>=3.4.0.2' distribution was not found and is required by netlib
```

The Python version is `2.7.10 (default, Oct 14 2015, 16:09:02)`

Has anyone had any success with running mitmproxy on Ubuntu 15.10?

**Comment by mhils** [comment]
Thanks for the report!

Looks like some Python Packaging related stuff screwed up again. If you `pip uninstall netlib` `pip install netlib`, everything should work. We'll push an emergency release ASAP.

**Comment by azangru** [comment]
Perfect! It works. Thanks so much!

**Comment by mhils** [comment]
0.15.1 is shipped - Merry Christmas! :christmas_tree: :smiley:
