### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ssl_established'

### ISSUE THREAD

**Issue by biran0079** [mitmproxy/mitmproxy#885]
I run into this exception while trying to do something similar to 
https://github.com/mitmproxy/mitmproxy/blob/master/examples/dns_spoofing.py
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 994, in handle_messages
    while self.handle_flow():
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1082, in handle_flow
    self.process_server_address(flow)  # The inline script may have changed request.host
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1335, in process_server_address
    self.live.change_server(address, ssl=ssl)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/primitives.py", line 230, in change_server
    ssl != self.c.server_conn.ssl_established
AttributeError: 'NoneType' object has no attribute 'ssl_established'```

**Comment by mhils** [comment]
You're using an outdated version of mitmproxy.
