### ISSUE TITLE
Crash when using --tcp if no server_name extension

### ISSUE THREAD

**Issue by jquesnelle** [mitmproxy/mitmproxy#888]
I'm using --tcp in the hopes of transparently proxying SSL. The MITMed device is connecting via TLS without the "server_name" extension in the Client Hello. When this happens, I get the following crash (it looks like it's not checking to see if there is no host name for the connection). Reproduced this from the v0.15 tag

```
Traceback (most recent call last):
  File "/home/jeffq/mitmproxy-src/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/home/jeffq/mitmproxy-src/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/home/jeffq/mitmproxy-src/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/home/jeffq/mitmproxy-src/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/home/jeffq/mitmproxy-src/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/home/jeffq/mitmproxy-src/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/home/jeffq/mitmproxy-src/libmproxy/protocol/tls.py", line 497, in _find_cert
    host = self.server_conn.address.host
AttributeError: 'NoneType' object has no attribute 'host'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by mhils** [comment]
Thanks. FWIW, this is not related to the SNI extension, but to mitmproxy not knowing the server address by other means when generating a certificate for the client.

**Comment by dufferzafar** [comment]
Are this & #861 related?

**Comment by mhils** [comment]
Yes, looks like the same root cause. I'll take on that next week.
