### ISSUE TITLE
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

### ISSUE THREAD

**Issue by ahmetalpbalkan** [mitmproxy/mitmproxy#904]
I used `brew install mitmproxy` to install and I have v0.14.0.

and I start it like `mitmproxy --socks`, then once I start intercepting traffic I immediately see this for all requests:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/proxy/modes/socks_proxy.py", line 57, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 395, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 399, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 518, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/netlib/certutils.py", line 335, in get_cert
    sans),
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/netlib/certutils.py", line 109, in dummy_cert
    [OpenSSL.crypto.X509Extension(b"subjectAltName", False, ss)])
  File "/usr/local/Cellar/mitmproxy/0.14.0/libexec/vendor/lib/python2.7/site-packages/OpenSSL/crypto.py", line 651, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode
```

**Comment by Kriechi** [comment]
The homebrew formula is not maintained by us and outdated. Please try installing the latest release for OSX: https://mitmproxy.org/download/osx-mitmproxy-0.15.tgz
