### ISSUE TITLE
On Shutdown: flow is None and crashes

### ISSUE THREAD

**Issue by woodenwatcher** [mitmproxy/mitmproxy#907]
The Version is 0.15. Crash info as follow:

```
./mitmdump.run.sh: line 2: 14504 Segmentation fault      mitmdump -p 59873 > network
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 272, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 130, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 323, in __call__
    self.handle_regular_mode_connect(request)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 409, in handle_regular_mode_connect
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 272, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 130, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 340, in __call__
    self.get_response_from_server(flow)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 471, in get_response_from_server
    if flow.response.stream:
AttributeError: 'NoneType' object has no attribute 'response'
```

**Comment by mhils** [comment]
Thanks. How can I reproduce that?

**Comment by woodenwatcher** [comment]
Sorry,it was crashed occasionally,I do not know how to reproduce that.

**Comment by mhils** [comment]
I can reproduce this on shutdown.
