### ISSUE TITLE
ImportError: No module named frame

### ISSUE THREAD

**Issue by gfrench17** [mitmproxy/mitmproxy#908]
Good morning,
I fetch the newest updates of mitmproxy every couple of days, but yesterday night, I discovered the following error I never got before - is there anybody seeing the same issue or might it just be related to my own setup?

The installation went fine:

$ sudo pip install mitmproxy/ --upgrade
[...]
Installing collected packages: mitmproxy
  Found existing installation: mitmproxy 0.15
    Uninstalling mitmproxy:
      Successfully uninstalled mitmproxy
  Running setup.py install for mitmproxy
[...]
    Installing mitmdump script to /usr/local/bin
Successfully installed mitmproxy
Cleaning up...

But then:
$ mitmproxy
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.15', 'console_scripts', 'mitmproxy')()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2379, in load
    return self.resolve()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2385, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/libmproxy/main.py", line 7, in <module>
    from . import version, cmdline
  File "/Library/Python/2.7/site-packages/libmproxy/cmdline.py", line 10, in <module>
    from .proxy import config
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/__init__.py", line 3, in <module>
    from .server import ProxyServer, DummyServer
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/server.py", line 12, in <module>
    from ..protocol import Kill
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/__init__.py", line 30, in <module>
    from .http import Http1Layer, UpstreamConnectLayer, Http2Layer
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 13, in <module>
    from netlib.http.http2.frame import GoAwayFrame, PriorityFrame, WindowUpdateFrame
ImportError: No module named frame

Cheers
Gordon

**Comment by Kriechi** [comment]
You are right. I'm mistakenly merged a PR in netlib too soon, which removed some dependencies.
I guess you are running netlib from git-master?

**Comment by gfrench17** [comment]
Exactly!

**Comment by Kriechi** [comment]
Sorry for the troubles.
You either have to use netlib with version 0.15 for now, or wait until #883 is merged (should be only a couple of days)

/cc @mhils
