### ISSUE TITLE
HTTP2: StreamIDTooLowError

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#920]
```
mitmproxy has crashed!
127.0.0.1:53941: Traceback (most recent call last):
  File "c:\users\user\git\mitmproxy\libmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "c:\users\user\git\mitmproxy\libmproxy\proxy\modes\http_proxy.py", line 11, in __call__
    layer()
  File "c:\users\user\git\mitmproxy\libmproxy\protocol\tls.py", line 350, in __call__
    layer()
  File "c:\users\user\git\mitmproxy\libmproxy\protocol\http1.py", line 70, in __call__
    layer()
  File "c:\users\user\git\mitmproxy\libmproxy\protocol\http.py", line 163, in __call__
    self.handle_regular_mode_connect(request)
  File "c:\users\user\git\mitmproxy\libmproxy\protocol\http.py", line 252, in handle_regular_mode_connect
    layer()
  File "c:\users\user\git\mitmproxy\libmproxy\protocol\tls.py", line 350, in __call__
    layer()
  File "c:\users\user\git\mitmproxy\libmproxy\protocol\http2.py", line 225, in __call__
    events = source_conn.h2.receive_data(raw_frame)
  File "c:\users\user\git\hyper-h2\h2\connection.py", line 893, in receive_data
    events.extend(self._receive_frame(frame))
  File "c:\users\user\git\hyper-h2\h2\connection.py", line 916, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "c:\users\user\git\hyper-h2\h2\connection.py", line 974, in _receive_headers_frame
    frame.stream_id, AllowedStreamIDs(not self.client_side)
  File "c:\users\user\git\hyper-h2\h2\connection.py", line 413, in _get_or_create_stream
    return self._begin_new_stream(stream_id, allowed_ids)
  File "c:\users\user\git\hyper-h2\h2\connection.py", line 359, in _begin_new_stream
    raise StreamIDTooLowError(stream_id, highest_stream_id)
StreamIDTooLowError: StreamIDTooLowError: 11 is lower than 13
```
This can be reproduced by running `mitmdump --http2`, opening https://http2.golang.org/reqinfo and then spamming Ctrl-R.

**Comment by Kriechi** [comment]
Why would you even try something like that?
![but-why](https://cloud.githubusercontent.com/assets/114300/12881516/b20feae4-ce4a-11e5-9c92-eaa02f1d596c.gif)

**Comment by Kriechi** [comment]
I'm not sure, but I think this is out of my hands.
It calls `source_conn.h2.receive_data` and fails there. This is right after reading the frame from the socket - so no mitmproxy-related code involved...

Looks like the server is sending two HeaderFrames:
```
<ServerConnection: [ssl: http2.golang.org] http2.golang.org:443>: HeadersFrame(Stream: 5; Flags: END_HEADERS): 88c0bf6196d07abe9403...
<ServerConnection: [ssl: http2.golang.org] http2.golang.org:443>: HeadersFrame(Stream: 5; Flags: END_HEADERS): 88c0bf6196d07abe9403...
```

**Comment by mhils** [comment]
I don't think it's the server. I can reproduce the same behaviour on https://h2o.examp1e.net/
