### ISSUE TITLE
weird issue I cant figure out

### ISSUE THREAD

**Issue by ASKProducts** [mitmproxy/mitmproxy#96]
So I'm running mountain lion, and I have come across an error that I cannot figure out. It was just recently working fine, and then I quit out of it ans all of a sudden whenever I try to launch it I get this message. 

```
    Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 19, in <module>
    from libmproxy import proxy, console, cmdline, version
  File "/Library/Python/2.7/site-packages/libmproxy/proxy.py", line 19, in <module>
    from netlib import odict, tcp, http, wsgi, certutils, http_status
ImportError: No module named netlib
```

**Comment by tosiara** [comment]
Just wanted to share that I have same issue in openSUSE 13.2. Looks like some Pytnon2/3 conflict that only affects openSUSE. `mitmproxy` can't find netlib. Tried to install it from github - does not help
On Ubuntu all works fine

**Comment by tosiara** [comment]
```
user@linux:~/mitmproxy> sudo pip install mitmproxy
root's password:
Requirement already satisfied (use --upgrade to upgrade): mitmproxy in /home/user/mitmproxy
Requirement already satisfied (use --upgrade to upgrade): pyperclip>=1.5.8 in /usr/lib/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.6 in /usr/lib64/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.14 in /usr/lib/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): netlib>=0.11,<0.12 in /home/user/netlib (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>0.1.2 in /usr/lib/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0.2 in /usr/lib64/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): configargparse>=0.9.3 in /usr/lib/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.3.0 in /usr/lib64/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): urwid>=1.1 in /usr/lib64/python3.4/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.2.1 in /usr/lib64/python3.4/site-packages (from pyOpenSSL>=0.14->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python3.4/site-packages (from pyOpenSSL>=0.14->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): passlib>=1.6.2 in /usr/lib/python3.4/site-packages (from netlib>=0.11,<0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/lib/python3.4/site-packages (from tornado>=4.0.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cffi>=0.8 in /usr/lib64/python3.4/site-packages (from cryptography>=0.2.1->pyOpenSSL>=0.14->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.4/site-packages (from cryptography>=0.2.1->pyOpenSSL>=0.14->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python3.4/site-packages (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL>=0.14->mitmproxy)
Cleaning up...

user@linux:~/mitmproxy> ./mitmproxy
Traceback (most recent call last):
  File "./mitmproxy", line 2, in <module>
    from libmproxy.main import mitmproxy
  File "/home/user/mitmproxy/libmproxy/main.py", line 5, in <module>
    import netlib.version
ImportError: No module named netlib.version

```

**Comment by mhils** [comment]
@tosiara, you (or your system) have aliased pip for pip3, which is the Python 3 version of pip. You need to install mitmproxy (and thereby netlib) using the Python 2 version of pip.

**Comment by tosiara** [comment]
@mhils You were right:
```
user@linux:~/mitmproxy> ls -l /usr/bin/pip
lrwxrwxrwx 1 root root 21 Oct 27 17:05 /usr/bin/pip -> /etc/alternatives/pip
user@linux:~/mitmproxy> ls -l /etc/alternatives/pip
lrwxrwxrwx 1 root root 15 Oct 27 17:05 /etc/alternatives/pip -> /usr/bin/pip3.4
```
After running `sudo zypper in python-pip` I've got pip2 and was able to install all dependencies
Thanks
