### ISSUE TITLE
"TypeError: 'NoneType' object is not callable" crash

### ISSUE THREAD

**Issue by cmckain15** [mitmproxy/mitmproxy#966]
##### Steps to reproduce the problem:

1. Intercept all traffic (~i)
2. Open a GET request
3. Attempt response edit

##### What is the expected behavior?
Something that allows me to change the response code.

##### What went wrong?
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 498, in run
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/window.py", line 39, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowview.py", line 520, in keypress
    key = super(self.__class__, self).keypress(size, key)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/tabs.py", line 38, in keypress
    self.change_tab((self.tab_offset + 1) % n)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/tabs.py", line 33, in change_tab
    self.show()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/tabs.py", line 67, in show
    body = self.tabs[self.tab_offset][1](),
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowview.py", line 165, in view_details
    return flowdetailview.flowdetails(self.state, self.flow)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowdetailview.py", line 25, in flowdetails
    ["Address", "%s:%s" % sc.address()],
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/main.py", line 70, in mitmproxy
    m.run()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 508, in run
    self.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 679, in shutdown
    self.state.killall(self)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/flow.py", line 623, in killall
    self.flows.kill_all(master)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/flow.py", line 535, in kill_all
    f.kill(master)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/models/flow.py", line 151, in kill
    master.handle_error(self)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 725, in handle_error
    self.process_flow(f)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 716, in process_flow
    signals.flow_change.send(self, flow = f)
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowview.py", line 169, in sig_flow_change
    self.show()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/tabs.py", line 67, in show
    body = self.tabs[self.tab_offset][1](),
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowview.py", line 165, in view_details
    return flowdetailview.flowdetails(self.state, self.flow)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowdetailview.py", line 25, in flowdetails
    ["Address", "%s:%s" % sc.address()],
TypeError: 'NoneType' object is not callable
````

---

Mitmproxy Version:
`
----@vultr:~# mitmproxy --version
mitmproxy 0.16
`
Operating System: Ubuntu 15.10

**Comment by mhils** [comment]
Thanks!

**Comment by cmckain15** [comment]
Is there any way around this problem?

**Comment by mhils** [comment]
I just fixed this on master - the problem here was tabbing into the details screen when there was no server connection yet.

**Comment by cmckain15** [comment]
Thanks.
