### ISSUE TITLE
mitmproxy crashed when the containing tmux pane was resized

### ISSUE THREAD

**Issue by colemickens** [mitmproxy/mitmproxy#979]
##### Steps to reproduce the problem:

1. Capture some traffic
2. Inspect a request
3. Resize the tmux pane mitmproxy is running in (in my case I used the mouse to drag a split upward to make more room for mitmproxy running in the bottom pane)

##### What is the expected behavior?
mitmproxy resizes and continues running

##### What went wrong?
mitmproxy crashed

```
Traceback (most recent call last):
  File "/nix/store/zaamgkrc3vf4dshiljdk1cnd54h0sm87-python2.7-mitmproxy-0.14.0/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 500, in run
    self.loop.run()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 706, in _loop
    self._entering_idle()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 667, in _entering_idle
    callback()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 560, in entering_idle
    self.draw_screen()
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/main_loop.py", line 575, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/nix/store/4hafqycx6l1rs357004x2cda5d3c7adf-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/raw_display.py", line 749, in draw_screen
    if osb and osb[y] == row:
IndexError: list index out of range

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### Any other comments?
Possibly related: #497 (and from there: https://github.com/urwid/urwid/issues/96)

---

Mitmproxy Version: 0.14.0 (I'll try to update and repro...)
Operating System: NixOS

**Comment by Kriechi** [comment]
Please upgrade to mitmproxy 0.15 or 0.16 which contain urwid>=1.3.1 as dependency.
